import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.mohithash.byok"
    compileSdk = 37
    compileSdkMinor = 1

    defaultConfig {
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
    }
    signingConfigs {
        val ksProps = rootProject.file("keystore.properties")
        if (ksProps.exists()) {
            val props = Properties().apply { ksProps.inputStream().use { load(it) } }
            create("release") {
                storeFile = rootProject.file(props.getProperty("storeFile"))
                storePassword = props.getProperty("storePassword")
                keyAlias = props.getProperty("keyAlias")
                keyPassword = props.getProperty("keyPassword")
            }
        }
    }
    buildTypes {
        release {
            // Unminified on purpose: 100+ flavors build in minutes instead of hours; AAB download stays ~5 MB.
            isMinifyEnabled = false
            signingConfigs.findByName("release")?.let { signingConfig = it }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures { compose = true }

    flavorDimensions += "app"
    productFlavors {
        // FLAVORS-BEGIN (generated by gen.py)
        create("famberlight") { dimension = "app"; applicationId = "com.mohithash.byok.amberlight" }
        create("fbetweensessions") { dimension = "app"; applicationId = "com.mohithash.byok.betweensessions" }
        create("fcitesure") { dimension = "app"; applicationId = "com.mohithash.byok.citesure" }
        create("fconceivekit") { dimension = "app"; applicationId = "com.mohithash.byok.conceivekit" }
        create("fequitylens") { dimension = "app"; applicationId = "com.mohithash.byok.equitylens" }
        create("fframewrangler") { dimension = "app"; applicationId = "com.mohithash.byok.framewrangler" }
        create("ffunddecoder") { dimension = "app"; applicationId = "com.mohithash.byok.funddecoder" }
        create("fgraciousguest") { dimension = "app"; applicationId = "com.mohithash.byok.graciousguest" }
        create("fkdramakorean") { dimension = "app"; applicationId = "com.mohithash.byok.kdramakorean" }
        create("flecturelens") { dimension = "app"; applicationId = "com.mohithash.byok.lecturelens" }
        create("flitmatrix") { dimension = "app"; applicationId = "com.mohithash.byok.litmatrix" }
        create("flocalvoice") { dimension = "app"; applicationId = "com.mohithash.byok.localvoice" }
        create("flogicforge") { dimension = "app"; applicationId = "com.mohithash.byok.logicforge" }
        create("fmortgagelens") { dimension = "app"; applicationId = "com.mohithash.byok.mortgagelens" }
        create("fpivotpilot") { dimension = "app"; applicationId = "com.mohithash.byok.pivotpilot" }
        create("fprojectcrew") { dimension = "app"; applicationId = "com.mohithash.byok.projectcrew" }
        create("fshopfloor") { dimension = "app"; applicationId = "com.mohithash.byok.shopfloor" }
        create("fstrongafter50") { dimension = "app"; applicationId = "com.mohithash.byok.strongafter50" }
        create("ftalkoutline") { dimension = "app"; applicationId = "com.mohithash.byok.talkoutline" }
        create("ftrendlens") { dimension = "app"; applicationId = "com.mohithash.byok.trendlens" }
        // FLAVORS-END
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom-alpha:2026.09.00"))
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.11.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.11.0")
    implementation("androidx.navigation:navigation-compose:2.10.1")
    implementation("androidx.exifinterface:exifinterface:1.4.2")
    implementation("androidx.graphics:graphics-shapes:1.1.0")
    implementation("androidx.room:room-runtime:2.8.5")
    implementation("androidx.room:room-ktx:2.8.5")
    ksp("androidx.room:room-compiler:2.8.5")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
}
