import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.mohithash.byok"
    compileSdk = 37
    compileSdkMinor = 1

    defaultConfig {
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
    }
    signingConfigs {
        val ksProps = rootProject.file("keystore.properties")
        if (ksProps.exists()) {
            val props = Properties().apply { ksProps.inputStream().use { load(it) } }
            create("release") {
                storeFile = rootProject.file(props.getProperty("storeFile"))
                storePassword = props.getProperty("storePassword")
                keyAlias = props.getProperty("keyAlias")
                keyPassword = props.getProperty("keyPassword")
            }
        }
    }
    buildTypes {
        release {
            // Unminified on purpose: 100+ flavors build in minutes instead of hours; AAB download stays ~5 MB.
            isMinifyEnabled = false
            signingConfigs.findByName("release")?.let { signingConfig = it }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures { compose = true }

    flavorDimensions += "app"
    productFlavors {
        // FLAVORS-BEGIN (generated by gen.py)
        create("fanywherejobs") { dimension = "app"; applicationId = "com.mohithash.byok.anywherejobs" }
        create("fbendlab") { dimension = "app"; applicationId = "com.mohithash.byok.bendlab" }
        create("fbooknook") { dimension = "app"; applicationId = "com.mohithash.byok.booknook" }
        create("fcharttailor") { dimension = "app"; applicationId = "com.mohithash.byok.charttailor" }
        create("fclocked") { dimension = "app"; applicationId = "com.mohithash.byok.clocked" }
        create("fclubbulletin") { dimension = "app"; applicationId = "com.mohithash.byok.clubbulletin" }
        create("fdiscocall") { dimension = "app"; applicationId = "com.mohithash.byok.discocall" }
        create("fflawfinder") { dimension = "app"; applicationId = "com.mohithash.byok.flawfinder" }
        create("fkidneykeeper") { dimension = "app"; applicationId = "com.mohithash.byok.kidneykeeper" }
        create("fmetermate") { dimension = "app"; applicationId = "com.mohithash.byok.metermate" }
        create("fmotoskills") { dimension = "app"; applicationId = "com.mohithash.byok.motoskills" }
        create("fobjectiondojo") { dimension = "app"; applicationId = "com.mohithash.byok.objectiondojo" }
        create("freunionready") { dimension = "app"; applicationId = "com.mohithash.byok.reunionready" }
        create("frvcamper") { dimension = "app"; applicationId = "com.mohithash.byok.rvcamper" }
        create("fseobrief") { dimension = "app"; applicationId = "com.mohithash.byok.seobrief" }
        create("fsproutshelf") { dimension = "app"; applicationId = "com.mohithash.byok.sproutshelf" }
        create("fstrollermiles") { dimension = "app"; applicationId = "com.mohithash.byok.strollermiles" }
        create("fstylesheet") { dimension = "app"; applicationId = "com.mohithash.byok.stylesheet" }
        create("fswiftsidekick") { dimension = "app"; applicationId = "com.mohithash.byok.swiftsidekick" }
        create("ftidyrows") { dimension = "app"; applicationId = "com.mohithash.byok.tidyrows" }
        // FLAVORS-END
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom-alpha:2026.09.00"))
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.11.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.11.0")
    implementation("androidx.navigation:navigation-compose:2.10.1")
    implementation("androidx.exifinterface:exifinterface:1.4.2")
    implementation("androidx.graphics:graphics-shapes:1.1.0")
    implementation("androidx.room:room-runtime:2.8.5")
    implementation("androidx.room:room-ktx:2.8.5")
    ksp("androidx.room:room-compiler:2.8.5")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
}
