from dsl import *
FIN = "General information, not financial, tax or legal advice; consult a licensed professional."
MED = "General information, not medical advice; consult a clinician."

APP("presentation_kid", "Science Fair", "Projects, posters and presentations for students", "Education", ["#1565C0", "#FFB300", "#43A047"], "bulb",
 "Science Fair helps students pick a project, design a fair test, analyse results, build the poster and rehearse the judges' questions.",
 "You are a science-fair mentor: scientific method first, safe experiments, honest about effort; you guide rather than do the work.",
 "Win the fair, learn the method", "About the student.", ["Project ideas by level", "Fair-test design", "Poster & judge prep"],
 [F("student", "Student's grade / age", "text", "grade 7", required=True), CH("interest", "Interests", ["Biology", "Chemistry", "Physics", "Engineering", "Environment", "Computers"], multi=True), CH("weeks", "Weeks available", ["2", "4", "8"])],
 [T("ideas", "Project ideas", "Doable and interesting", "💡", [TXT("constraints", "Constraints", "no chemicals, small flat")],
    "8 project ideas for the profile with {constraints}: cards (project, body = question & method, meta = difficulty & cost), and a callout on the most winnable.", "cards, callout", "Ideas", "Thinking…"),
  T("design", "Design the experiment", "Variables and fair test", "🧪", [TXT("project", "Project", "", True)],
    "Design {project}: kv (question, hypothesis, independent/dependent/controlled variables, sample size), steps (procedure), checklist (materials), and a callout on safety.", "kv, steps, checklist, callout", "Design", "Designing…"),
  T("analyse", "Analyse results", "Paste your data", "📊", [LONG("data", "Data", "")],
    "Analyse: {data}. table (summary stats), text (what it shows), bullets (limitations), and a quote (a one-sentence conclusion).", "table, text, bullets, quote", "Analyse", "Crunching…"),
  T("poster", "Poster & judges", "Layout and Q&A", "🖼️", [TXT("project", "Project", "", True)],
    "For {project}: table (Poster section | Content | Visual), bullets (10 judge questions with answer hints), and a quote (30-second pitch).", "table, bullets, quote", "Prepare", "Preparing…")])

APP("adhd_daily", "Focus Friend", "ADHD-friendly structure for real days", "Health & Fitness", ["#FF7043", "#26A69A", "#5E35B1"], "brain",
 "Focus Friend builds low-friction daily plans, breaks tasks down to the first step, sets up body-doubling and dopamine-aware routines, and helps with transitions.",
 "You are an ADHD coach: strengths-based, external structure, tiny steps, no shame; you don't diagnose or advise on medication.",
 "Structure that forgives", "How your brain works.", ["Low-friction day plans", "Task breakdowns", "Transition & reset tools"],
 [NAME, CH("struggles", "Struggles", ["Starting", "Finishing", "Time blindness", "Transitions", "Overwhelm", "Mornings"], multi=True), CH("helps", "Helps", ["Timers", "Music", "Body doubling", "Movement", "Checklists"], multi=True)],
 [T("day", "Plan today", "Loose, forgiving", "🗓️", [LONG("must", "Must do", ""), TXT("energy", "Energy right now", "low")],
    "Plan for the profile given must-do: {must}, energy {energy}: table (Block | Task | First step | Timer), a callout on the one thing that matters, and a quote (permission slip).", "table, callout, quote", "Plan", "Planning…"),
  T("breakdown", "Break it down", "Until it's obvious", "🔨", [TXT("task", "Task", "renew passport", True)],
    "Break '{task}' into steps so small the first takes 2 minutes: steps, bullets (what to gather), and a callout on the step people avoid.", "steps, bullets, callout", "Break down", "Chunking…"),
  T("reset", "Reset", "Overwhelmed or frozen", "🧊", [CH("state", "State", ["Frozen", "Spiralling", "Hyperfocus hangover", "Post-meeting crash"], "Frozen")],
    "A 5-minute reset for {state}: steps, a quote (self-talk), and bullets (then what).", "steps, quote, bullets", "Reset", "Here…"),
  T("morning", "Morning routine", "Launch sequence", "🌅", [F("leave", "Leave by", "text", "08:15")],
    "A morning launch sequence to leave by {leave} for the profile: table (Time | Step | Cue), checklist (night-before), and a callout on decision fatigue.", "table, checklist, callout", "Build", "Building…")], "Not a substitute for diagnosis or treatment; talk to a clinician about medication or assessment.")

APP("grief_gentle", "Gentle Days", "Support through grief, one day at a time", "Health & Fitness", ["#5C6BC0", "#FFB74D", "#80CBC4"], "heart",
 "Gentle Days offers grief-informed support: what's normal, small daily anchors, words for hard moments, and ways to remember someone.",
 "You are a grief-informed counsellor-educator: gentle, non-prescriptive, culturally sensitive; you never rush anyone and always surface crisis resources when needed.",
 "There's no right way to grieve", "Only what you want to share.", ["Understanding what's normal", "Daily anchors", "Words for hard moments"],
 [NAME, TXT("loss", "Who or what you lost (optional)", ""), TXT("when", "When (optional)", "")],
 [T("normal", "Is this normal?", "What you're feeling", "💬", [LONG("feeling", "What's going on", "")],
    "Respond to: {feeling}. text (validation and what grief commonly does), bullets (gentle things that may help), and a callout on when extra support is worth seeking, with crisis guidance if risk is present.", "text, bullets, callout", "Tell me", "Listening…"),
  T("anchor", "Today's anchors", "Three small things", "⚓", [TXT("today", "Today", "")],
    "Three small anchors for today ({today}): checklist (3 items), a quote (something kind to hear), and a callout on lowering the bar.", "checklist, quote, callout", "Anchor me", "Gently…"),
  T("words", "Words for a moment", "Cards, replies, eulogies", "✍️", [CH("kind", "Kind", ["Replying to condolences", "Telling my workplace", "A eulogy", "An anniversary message", "Telling a child"], "Replying to condolences")],
    "Help with '{kind}' for the profile: quote (draft), bullets (adjustments), and a callout on taking your time.", "quote, bullets, callout", "Write", "Writing…"),
  T("remember", "Ways to remember", "Rituals and projects", "🕯️", [],
    "Ways to remember for the profile: cards (idea, body = how, meta = effort), and a callout on involving others.", "cards, callout", "Ideas", "Thinking…")], "This is not therapy. If you are in crisis or thinking of harming yourself, contact emergency services or a crisis line now.")

APP("neighbour_notes", "Good Neighbour", "Handle the awkward stuff next door", "Lifestyle", ["#00897B", "#FF8F00", "#5E35B1"], "home",
 "Good Neighbour drafts notes and conversations about noise, parking, pets and shared spaces, organises building groups and plans street events.",
 "You are a community mediator: warm, fair, de-escalating; assumes good faith while being clear.",
 "Keep the peace", "Your setup.", ["Notes that don't start wars", "Conversation scripts", "Building & street organising"],
 [NAME, CH("home", "Home", ["Flat", "Terrace", "Detached", "Shared house"]), TXT("country", "Country", "")],
 [T("note", "Write a note", "Noise, parking, bins…", "📝", [CH("about", "About", ["Noise", "Parking", "Pets", "Bins/shared space", "Building work", "Thank you"], "Noise"), LONG("details", "Details", "", False)],
    "A note about {about}: {details}. quote (friendly note), quote (firmer follow-up if needed), and bullets (what to avoid).", "quote, quote, bullets", "Write", "Drafting…"),
  T("talk", "Talk in person", "Script", "💬", [TXT("issue", "Issue", "", True)],
    "Script for '{issue}': quote (opener), steps (flow), and a callout on if it gets heated.", "quote, steps, callout", "Script", "Thinking…"),
  T("group", "Start a building group", "WhatsApp, rules, first message", "👥", [],
    "Start a residents' group for a {home}: quote (invite message), bullets (ground rules), and checklist (first-month topics).", "quote, bullets, checklist", "Start", "Organising…"),
  T("event", "Street party / meetup", "Plan it", "🎉", [NUM("people", "Expected people", "30")],
    "Plan a street/building event for {people}: table (Week | Task), checklist (permissions & supplies, general), and a callout on inclusion.", "table, checklist, callout", "Plan", "Planning…")])

APP("swim_coach", "Swim Smart", "Technique, sets and open-water prep", "Sports", ["#0288D1", "#FFB300", "#26A69A"], "drop",
 "Swim Smart writes pool sets for your level, fixes stroke technique from descriptions, and prepares you for open water and triathlons.",
 "You are a swim coach: technique before volume, drills with purpose, safety-first in open water.",
 "Swim further, easier", "Your swimming.", ["Pool sets by level", "Technique fixes", "Open-water prep"],
 [NAME, CH("level", "Level", ["Learning", "Can swim 400m", "1–2 km", "Competitive"]), CH("stroke", "Focus stroke", ["Freestyle", "Breaststroke", "Backstroke", "Butterfly"]), TXT("goal", "Goal", "")],
 [T("set", "Today's set", "Time available", "🏊", [NUM("minutes", "Minutes", "45"), CH("focus", "Focus", ["Technique", "Endurance", "Speed", "Recovery"], "Technique")],
    "A {minutes}-minute {focus} set for the profile: table (Part | Distance | Effort | Notes), bullets (drills explained), and a callout on rest.", "table, bullets, callout", "Build", "Planning…"),
  T("fix", "Fix my stroke", "Describe the problem", "🔧", [TXT("problem", "Problem", "legs sink in freestyle", True)],
    "Fix '{problem}' in the profile stroke: text (cause), steps (drills in order), and a callout on the one cue to think about.", "text, steps, callout", "Fix", "Analysing…"),
  T("openwater", "Open-water prep", "Sea, lake, river", "🌊", [TXT("event", "Event", "1.5 km sea swim", True)],
    "Prepare for {event}: table (Week | Sessions), checklist (kit & safety), and a callout on cold water and sighting.", "table, checklist, callout", "Prepare", "Preparing…"),
  T("plan", "8-week plan", "Toward your goal", "📅", [],
    "An 8-week plan toward the profile goal: table (Week | Session 1 | Session 2 | Session 3), and a callout on progression.", "table, callout", "Plan", "Planning…")], "Never swim alone in open water; not medical advice.")

APP("marathon_nutrition", "Fuel Up", "Sports nutrition for training and race day", "Sports", ["#EF6C00", "#00838F", "#43A047"], "flame",
 "Fuel Up plans daily nutrition for your training load, carb-loads before races, builds in-race fuelling and fixes GI issues.",
 "You are a sports dietitian: carbs-per-kg precise, practical foods, gut-training aware.",
 "Eat to perform", "Your training.", ["Daily fuelling by load", "Race-week carb loading", "In-race fuel plans"],
 [NAME, NUM("weight", "Weight (kg)", "70"), CH("sport", "Sport", ["Running", "Cycling", "Triathlon", "Hiking", "Team sport"]), TXT("event", "Next event", "")],
 [T("daily", "Today's fuel", "By session", "🍝", [TXT("session", "Today's training", "90-min ride, moderate", True)],
    "Fuel plan for {session} for the profile: kv (carbs g, protein g, timing before/after), table (Meal | What | Carbs), and a callout on hydration.", "kv, table, callout", "Plan", "Calculating…"),
  T("carbload", "Carb-load", "Race week", "📈", [TXT("race", "Race", "marathon Sunday", True)],
    "Carb-loading for {race} at the profile weight: table (Day | Carbs g | Sample foods), bullets (what to avoid), and a callout on weight gain being normal.", "table, bullets, callout", "Plan", "Planning…"),
  T("inrace", "In-race fuelling", "Gels, drinks, real food", "⛽", [TXT("race", "Race & expected time", "", True), TXT("gut", "Gut history", "")],
    "In-race plan for {race}, gut: {gut}: table (Time | Fuel | Carbs | Fluid), steps (gut training in the weeks before), and a callout on symptoms to stop for.", "table, steps, callout", "Plan", "Planning…"),
  T("gi", "Fix GI issues", "Cramps, nausea", "🤢", [TXT("issue", "What happens", "", True)],
    "For '{issue}': bullets (likely causes), steps (changes to test one at a time), and a callout on when to see a doctor.", "bullets, steps, callout", "Fix", "Thinking…")], MED)

APP("etsy_seller", "Maker Shop", "Sell your handmade goods online", "Business", ["#F4511E", "#26A69A", "#FFB300"], "bag",
 "Maker Shop writes listings with SEO-friendly titles, prices your products properly, plans photos and handles customer messages.",
 "You are a successful handmade-seller mentor: honest pricing maths, listing SEO, kind customer service.",
 "Turn craft into cash", "Your shop.", ["Listings that sell", "Pricing that pays you", "Customer message templates"],
 [F("shop", "Shop / what you make", "text", "hand-poured soy candles", required=True), CH("platform", "Platform", ["Etsy", "Own site", "Instagram", "Markets"], multi=True), F("currency", "Currency", "text", "$", default="$")],
 [T("listing", "Write a listing", "Title, description, tags", "🏷️", [TXT("product", "Product", "", True), PHOTO("Product photo (optional)")],
    "Listing for {product}: quote (title under 140 chars), quote (description), bullets (13 tags), and a callout on photos to add.", "quote, quote, bullets, callout", "Write", "Writing…"),
  T("price", "Price a product", "Materials, time, fees", "💲", [TXT("product", "Product", "", True), NUM("materials", "Materials cost", "6"), NUM("minutes", "Minutes to make", "40")],
    "Price {product} (materials {materials}, {minutes} min): kv (labour, overhead, fees, wholesale, retail), table (Scenario | Price | Profit), and a callout on underpricing.", "kv, table, callout", "Price", "Calculating…"),
  T("photos", "Photo plan", "Phone-friendly", "📷", [TXT("product", "Product", "", True)],
    "Photo plan for {product}: checklist (shots), kv (light, background, props), and a callout on consistency.", "checklist, kv, callout", "Plan", "Planning…"),
  T("message", "Customer message", "Reply well", "💬", [LONG("msg", "Their message", ""), TXT("facts", "Facts", "")],
    "Reply to: {msg}, facts: {facts}. quote (reply), and bullets (policy notes).", "quote, bullets", "Draft", "Drafting…")], FIN)

APP("landlord_lite", "Landlord Desk", "Manage a rental without the headaches", "Business", ["#37474F", "#FFB300", "#00897B"], "home",
 "Landlord Desk drafts tenant communications, builds inspection and maintenance schedules, calculates yield and prepares for handovers.",
 "You are a fair, organised property manager: compliant-minded (general), respectful of tenants, numbers-driven.",
 "Run it like a pro", "Your property.", ["Tenant letters", "Maintenance schedules", "Yield & cost maths"],
 [NAME, TXT("country", "Country / region", "", True), TXT("property", "Property", "2-bed flat"), NUM("rent", "Monthly rent", "1200")],
 [T("letter", "Write to a tenant", "Repairs, rent, notices", "✉️", [CH("about", "About", ["Rent reminder", "Inspection notice", "Repair update", "Rent review", "End of tenancy", "Welcome"], "Inspection notice"), LONG("details", "Details", "", False)],
    "Letter about {about}: {details} for {country}. quote (letter), bullets (notice periods and rules to verify locally), and a callout on tone.", "quote, bullets, callout", "Write", "Drafting…"),
  T("maintain", "Maintenance schedule", "Annual plan", "🗓️", [],
    "Annual maintenance/compliance schedule for the profile property in {country} (general): table (Month | Task | Who | Est. cost), and a callout on safety certificates to look up.", "table, callout", "Plan", "Planning…"),
  T("yield", "Yield & costs", "Is it working?", "📊", [LONG("costs", "Annual costs", "mortgage 7200, insurance 300, repairs 800")],
    "Yield for rent {rent}/month with costs {costs}: kv (gross yield, net yield, monthly cash flow), and bullets (levers).", "kv, bullets", "Calculate", "Calculating…"),
  T("handover", "Tenant handover", "Check-in / check-out", "🔑", [CH("which", "Which", ["Check-in", "Check-out"], "Check-in")],
    "A {which} process: checklist, quote (message to tenant), and a callout on deposit rules to verify.", "checklist, quote, callout", "Prepare", "Preparing…")], FIN)

APP("emergency_ready", "Ready Kit", "Prepare your household for emergencies", "Lifestyle", ["#C62828", "#FFB300", "#37474F"], "shield",
 "Ready Kit builds go-bags and home kits for your risks, writes family emergency plans and checklists for storms, outages and evacuations.",
 "You are an emergency-preparedness educator: calm, practical, region-aware, no doom.",
 "Prepared, not scared", "Your household.", ["Kits for your risks", "Family plans", "Event checklists"],
 [NAME, TXT("where", "Where you live", "", True), CH("risks", "Risks", ["Storms", "Floods", "Wildfire", "Earthquake", "Power cuts", "Heatwaves", "Winter storms"], multi=True), TXT("household", "Household", "2 adults, 1 child, 1 dog")],
 [T("kit", "Build my kit", "Home or go-bag", "🎒", [CH("kind", "Kit", ["Go-bag", "Home 72h", "Car"], "Go-bag")],
    "A {kind} kit for the profile: checklist (by category with quantities), a callout on medications/documents, and bullets (rotation schedule).", "checklist, callout, bullets", "Build", "Listing…"),
  T("plan", "Family plan", "Who does what", "📋", [],
    "A family emergency plan for the profile: table (Scenario | Action | Meeting point | Contact), quote (the card each person carries), and a callout on practising.", "table, quote, callout", "Plan", "Planning…"),
  T("event", "Something's coming", "Storm, outage, heatwave", "⚠️", [CH("event", "Event", ["Storm", "Flood", "Power cut", "Heatwave", "Wildfire smoke", "Snow"], "Storm"), NUM("hours", "Hours until", "24")],
    "{hours} hours before a {event}: steps (in order), checklist (last-minute items), and a callout on when to leave.", "steps, checklist, callout", "Prepare", "Preparing…"),
  T("after", "Afterwards", "Recovery steps", "🔄", [TXT("what", "What happened", "", True)],
    "After {what}: steps (safety first), checklist (insurance/documentation), and a callout on mental health.", "steps, checklist, callout", "Guide", "Guiding…")])

APP("interview_qs", "Hire Right", "Structured interviews for small teams", "Business", ["#1E88E5", "#FF7043", "#43A047"], "chat",
 "Hire Right writes job descriptions, structured interview questions with scoring rubrics, and candidate feedback — fair and consistent.",
 "You are a people-ops lead: structured, bias-aware, legally cautious (general), respectful to candidates.",
 "Hire fairly, hire well", "Your team.", ["Job descriptions", "Scored interview questions", "Feedback & offers"],
 [F("company", "Company", "text", ""), TXT("role", "Role you're hiring", ""), CH("stage", "Stage", ["Writing the JD", "Screening", "Interviewing", "Deciding"])],
 [T("jd", "Job description", "Clear and inclusive", "📄", [LONG("about", "Role details", "")],
    "JD for {role} at {company}: {about}. quote (JD with responsibilities, must-haves, nice-to-haves, salary guidance placeholder), and a callout on biased wording removed.", "quote, callout", "Write", "Writing…"),
  T("questions", "Interview questions", "With rubric", "❓", [CH("type", "Type", ["Screening call", "Technical", "Behavioural", "Final"], "Behavioural")],
    "{type} questions for {role}: table (Question | What good looks like | Score 1–4 anchors), and a callout on questions to avoid (general legal).", "table, callout", "Generate", "Writing…"),
  T("scorecard", "Compare candidates", "Paste notes", "⚖️", [LONG("notes", "Interview notes", "")],
    "From: {notes}. table (Candidate | Criterion scores | Evidence), bullets (risks), and a callout on bias checks before deciding.", "table, bullets, callout", "Compare", "Scoring…"),
  T("feedback", "Candidate feedback", "Rejection or offer", "✉️", [CH("outcome", "Outcome", ["Rejection", "Offer", "Next round"], "Rejection"), TXT("name", "Candidate", "")],
    "A {outcome} email to {name}: quote (email), and bullets (what to include/avoid).", "quote, bullets", "Draft", "Drafting…")])

APP("apartment_hunt", "Home Hunt", "Find, view and secure your next rental", "House & Home", ["#00838F", "#FF8F00", "#5E35B1"], "pin",
 "Home Hunt turns your needs into a search plan, scores listings, prepares viewing checklists and drafts applications that stand out.",
 "You are a savvy relocation consultant: red-flag aware, negotiation-minded, realistic about markets.",
 "Find the right place", "Your must-haves.", ["Search plans", "Listing scoring", "Viewing checklists & applications"],
 [NAME, TXT("city", "City", "", True), NUM("budget", "Max rent", "1500"), TXT("needs", "Must-haves", "2 bed, near metro, pets ok")],
 [T("plan", "Search plan", "Where and how", "🗺️", [],
    "A search plan for the profile: table (Area | Why | Typical rent | Watch-outs), bullets (search tactics), and a callout on timing.", "table, bullets, callout", "Plan", "Planning…"),
  T("score", "Score a listing", "Paste it", "⭐", [LONG("listing", "Listing text", "")],
    "Score: {listing} against the profile: kv (score /10, price vs market, red flags), bullets (questions to ask), and a callout verdict.", "kv, bullets, callout", "Score", "Scoring…"),
  T("viewing", "Viewing checklist", "Don't miss anything", "🔍", [],
    "Viewing checklist: checklist (by room + building + area), bullets (questions for the agent), and a callout on tests (water pressure, phone signal, noise).", "checklist, bullets, callout", "Checklist", "Listing…"),
  T("apply", "Application & offer", "Stand out", "✉️", [TXT("about", "About you", "two professionals, no pets, long-term")],
    "Application message for the profile: quote (message), bullets (documents to have ready), and a callout on negotiation points.", "quote, bullets, callout", "Draft", "Drafting…")], FIN)

APP("outfit_kids_school", "Uniform & Co", "School-year logistics for busy parents", "Parenting", ["#5E35B1", "#FFB300", "#26A69A"], "calendar",
 "Uniform & Co plans back-to-school lists, weekly family logistics, homework routines and communications with teachers.",
 "You are a super-organised school-parent coordinator: lists, routines, and diplomatic emails.",
 "Term time, handled", "Your kids.", ["Back-to-school lists", "Weekly logistics", "Teacher communications"],
 [F("kids", "Kids & years", "text", "Ali (Year 3), Sara (Year 6)", required=True), TXT("activities", "Activities", "swimming Tue, piano Thu")],
 [T("list", "Back-to-school list", "Everything, by child", "🎒", [NUM("budget", "Budget", "200")],
    "Back-to-school list for the profile kids under {budget}: checklist (by child), table (Item | Buy/Reuse | Est.), and a callout on labelling.", "checklist, table, callout", "List", "Listing…"),
  T("week", "Weekly logistics", "Who, where, when", "🗓️", [TXT("adults", "Adults' constraints", "I work late Wed")],
    "Weekly plan for the profile with {adults}: table (Day | Morning | After school | Who), checklist (night-before), and a callout on the crunch point.", "table, checklist, callout", "Plan", "Planning…"),
  T("routine", "Homework routine", "Less nagging", "📚", [],
    "A homework routine for the profile kids: table (Time | Step), bullets (motivation tricks by age), and a quote (the sentence to end battles).", "table, bullets, quote", "Build", "Building…"),
  T("teacher", "Email a teacher", "Concerns, requests, thanks", "✉️", [CH("about", "About", ["A concern", "A request", "Absence", "Thank you", "Bullying"], "A concern"), LONG("details", "Details", "", False)],
    "Email to the teacher about {about}: {details}. quote (email), and bullets (what to ask for).", "quote, bullets", "Draft", "Drafting…")])
