from dsl import *
MED = "This is general information, not medical advice; see a clinician for diagnosis or before changing medication."

APP("meal_prep_pro", "Meal Prep Pro", "A week of lunches in one Sunday session", "Food & Drink", ["#00695C", "#FF8F00", "#5E35B1"], "cup",
 "Meal Prep Pro plans batch-cooking sessions that fit your macros, containers and budget, with a shopping list and a cook order that finishes everything at once.",
 "You are a batch-cooking coach: practical, macro-aware, obsessed with reusing ingredients and minimising washing-up.",
 "Cook once, eat all week", "Tell us your goals and containers; get a plan you can shop and cook in one go.", ["Macro-aware meal plans", "One shopping list, grouped by aisle", "A cook order that finishes together"],
 [NAME, CH("goal", "Goal", ["Lose fat", "Build muscle", "Maintain", "Eat cheaper"]), CH("diet", "Diet", ["Anything", "Vegetarian", "Vegan", "Halal", "Gluten-free", "Dairy-free"]), F("containers", "Containers you own", "text", "6 glass boxes, 4 jars")],
 [T("plan", "Plan my week", "Lunches + dinners from one session", "🗓️", [CH("meals", "Meals to prep", ["5 lunches", "5 lunches + 5 dinners", "7 dinners"], "5 lunches"), NUM("budget", "Budget", "60"), TXT("likes", "Must include / avoid", "chicken thighs, no mushrooms")],
    "Build a prep plan: {meals}, budget {budget}, preferences: {likes}. Sections: table (Meal | Protein | Carb | Veg | kcal est.), a checklist shopping list grouped by aisle, steps for the cook order so everything finishes together, and a callout on storage life per dish.", "table, checklist, steps, callout", "Plan it", "Planning…"),
  T("macros", "Hit my macros", "Recipes for a protein/carb/fat target", "🎯", [NUM("protein", "Protein g/day", "150"), NUM("kcal", "Calories/day", "2000"), TXT("prefs", "Preferences", "")],
    "Design 3 day-templates hitting ~{protein} g protein and ~{kcal} kcal with preferences {prefs}. Cards per day (meta = kcal · P/C/F), then a kv of the highest-protein cheap foods per 100g.", "cards, kv", "Design", "Calculating…"),
  T("fridge", "Cook from my fridge", "Photo → what to prep", "📷", [PHOTO("Photo of your fridge/pantry", "", True)],
    "Inventory the visible food as a table (Item | Qty | Category). Then 4 batch-cook ideas as cards using mostly these items, and steps to prep the two that share the most ingredients.", "table, cards, steps", "Scan", "Looking…"),
  T("reheat", "Storage & reheating", "Keep prepped food safe and tasty", "🔥", [TXT("dish", "Dish", "chicken curry with rice", True)],
    "For {dish}: kv (fridge life, freezer life, best container, reheat method & time), a callout on food-safety mistakes, and bullets on keeping texture good.", "kv, callout, bullets", "Tell me", "Checking…")])

APP("bento_kids", "Lunchbox Hero", "School lunches kids actually eat", "Food & Drink", ["#F06292", "#4DB6AC", "#FFB74D"], "star",
 "Lunchbox Hero plans balanced, allergy-safe school lunches around what your child will actually eat, with a weekly rotation and a shopping list.",
 "You are a pragmatic parent-nutritionist: realistic about picky eaters, nut-free-school aware, never preachy.",
 "Pack lunches they'll finish", "Tell us about your kid's tastes and school rules.", ["5-day lunchbox rotations", "Picky-eater strategies", "Allergy-safe swaps"],
 [F("kid", "Child's name & age", "text", "Maya, 7"), F("likes", "Likes", "text", "cucumber, cheese, pasta"), F("dislikes", "Dislikes", "text", "anything soggy"), CH("rules", "School rules", ["Nut-free", "No reheating", "Vegetarian only", "None"], multi=True)],
 [T("week", "This week's lunches", "5 boxes, balanced and finishable", "🍱", [CH("style", "Style", ["Classic sandwich", "Bento bites", "Warm thermos", "Mix"], "Mix"), TXT("notes", "This week", "swimming Tuesday, big appetite")],
    "Plan 5 school lunches ({style}, notes: {notes}). Table (Day | Main | Fruit/Veg | Snack | Drink), a checklist shopping list, and bullets on prep-the-night-before tricks.", "table, checklist, bullets", "Plan lunches", "Packing…"),
  T("picky", "Picky-eater plan", "Get a new food accepted", "🥦", [TXT("food", "Food to introduce", "broccoli", True)],
    "A gentle 2-week exposure plan to get {food} accepted: steps (one per exposure), bullets of presentation ideas, and a callout on what not to do.", "steps, bullets, callout", "Make a plan", "Thinking…"),
  T("swap", "Allergy-safe swap", "Replace an ingredient safely", "🔁", [TXT("item", "Ingredient", "peanut butter", True), TXT("for", "In", "sandwiches")],
    "Safe substitutes for {item} in {for} given the school rules: kv (substitute → notes), and a callout on cross-contamination labels to check.", "kv, callout", "Find swaps", "Checking…"),
  T("leftover", "Leftover makeover", "Dinner → tomorrow's box", "♻️", [TXT("dinner", "Tonight's dinner", "roast chicken and potatoes", True)],
    "Turn {dinner} into 3 kid-friendly lunchbox ideas as cards (meta = prep minutes), then steps for the quickest, and a callout on keeping it safe until noon.", "cards, steps, callout", "Makeover", "Reinventing…")])

APP("sommelier_pocket", "Pocket Sommelier", "The right bottle for the plate and the budget", "Food & Drink", ["#6A1B9A", "#C62828", "#F9A825"], "cup",
 "Pocket Sommelier pairs wine (and beer, sake, cocktails) with what you're eating, decodes labels from a photo, and builds tasting notes you can actually use.",
 "You are a friendly sommelier: opinionated, budget-aware, never snobbish; you explain why a pairing works in one sentence.",
 "Drink better, spend smarter", "Tell us your taste and budget.", ["Pairings for any dish", "Label decoder from a photo", "Tasting notes & cellar tips"],
 [NAME, CH("taste", "You usually like", ["Dry whites", "Big reds", "Bubbles", "Rosé", "Natural", "Beer", "Cocktails"], multi=True), CH("budget", "Typical budget", ["Under 15", "15–30", "30–60", "Sky's the limit"])],
 [T("pair", "Pair my dinner", "Three bottles for tonight", "🍷", [TXT("dish", "What are you eating", "grilled salmon with lemon butter", True), CH("where", "Where", ["Home", "Restaurant list", "Supermarket"])],
    "Pair {dish} ({where}). 3 cards (wine style + example region/producer type, meta = price tier), one non-alcoholic option, a callout on why the pairing works, and bullets on serving temperature.", "cards, callout, bullets", "Pair it", "Tasting…"),
  T("label", "Decode a label", "Photo of a bottle → what it is", "📷", [PHOTO("Bottle label", "", True)],
    "Read the label: kv (producer, region, grape/style, vintage, ABV, drink-by window, expected price), a text section on taste profile, and bullets of 3 dishes it suits.", "kv, text, bullets", "Decode", "Reading…"),
  T("notes", "Tasting notes", "Sound like you know what you're saying", "📝", [TXT("wine", "Wine", "2019 Rioja Reserva", True), TXT("impressions", "Your impressions", "smelled like cherries and vanilla")],
    "Write structured tasting notes for {wine} using the impressions '{impressions}': kv (look, nose, palate, finish, score /100), a quote with one confident sentence to say at the table, and bullets on what to try next if you liked it.", "kv, quote, bullets", "Write notes", "Swirling…"),
  T("party", "Party math", "How much to buy for a crowd", "🎉", [NUM("guests", "Guests", "20"), NUM("hours", "Hours", "4"), CH("vibe", "Vibe", ["Dinner", "Cocktail party", "BBQ", "Wedding"])],
    "Drinks plan for {guests} guests over {hours} hours ({vibe}): table (Category | Bottles | Servings | Est. cost), a checklist of ice/glassware/mixers, and a callout on responsible-service basics.", "table, checklist, callout", "Calculate", "Counting…")])

APP("barista_home", "Home Barista", "Dial in café-quality coffee at home", "Food & Drink", ["#4E342E", "#FF8A65", "#8D6E63"], "cup",
 "Home Barista helps you dial in espresso, pour-over, AeroPress and cold brew with exact ratios, then troubleshoots taste problems.",
 "You are a patient specialty-coffee trainer who speaks in ratios, grams and seconds and always gives one change at a time.",
 "Better coffee tomorrow morning", "Tell us your gear and we'll give you recipes to match.", ["Recipes for your exact gear", "Fix sour/bitter shots", "Bean & grind guidance"],
 [CH("gear", "Gear", ["Espresso machine", "Pour-over", "AeroPress", "French press", "Moka pot", "Cold brew"], multi=True), F("grinder", "Grinder", "text", "Baratza Encore"), CH("milk", "Milk drinks?", ["Yes", "No"])],
 [T("recipe", "Dial-in recipe", "Ratio, time, grind for your method", "☕", [CH("method", "Method", ["Espresso", "Pour-over", "AeroPress", "French press", "Moka pot", "Cold brew"], "Pour-over"), TXT("beans", "Beans", "Ethiopian natural, roasted 10 days ago")],
    "A starting recipe for {method} with {beans} on the user's gear: kv (dose, water, ratio, grind description, temp, total time), steps for the brew, and a callout on the first variable to adjust.", "kv, steps, callout", "Dial in", "Grinding…"),
  T("fix", "Fix my cup", "Sour? Bitter? Weak?", "🔧", [CH("taste", "It tastes", ["Sour", "Bitter", "Weak/watery", "Muddy", "Astringent"], "Sour"), TXT("recipe", "What you did", "18g in, 36g out, 25s")],
    "The cup tastes {taste} with: {recipe}. Explain the likely cause in text, then steps with ONE change per attempt, and a table (Symptom | Cause | Fix).", "text, steps, table", "Diagnose", "Tasting…"),
  T("beans", "Choose beans", "What to buy for how you brew", "🫘", [CH("like", "You like", ["Fruity/bright", "Chocolatey", "Nutty", "Floral", "Classic strong"], "Chocolatey")],
    "Recommend bean origins/roast levels for '{like}' on the user's methods: cards (origin/process, meta = roast level), bullets on freshness and storage, and a callout on decoding roast dates.", "cards, bullets, callout", "Recommend", "Sniffing…"),
  T("latte", "Milk & latte art", "Texture and pour basics", "🥛", [CH("milk", "Milk", ["Whole", "Oat", "Almond", "Skim"], "Whole"), CH("goal", "Goal", ["Silky texture", "Heart", "Tulip", "Rosetta"], "Silky texture")],
    "Coach {goal} with {milk}: steps for steaming (temps, sounds, timing), bullets on common mistakes, and a quote with the one cue to remember.", "steps, bullets, quote", "Coach me", "Steaming…")])

APP("gut_guide", "Gut Guide", "Food & symptom diary that finds your patterns", "Health & Fitness", ["#2E7D32", "#FF7043", "#0288D1"], "leaf",
 "Gut Guide helps people with IBS, reflux or food sensitivities log meals and symptoms, spot likely triggers, and plan low-FODMAP or elimination phases.",
 "You are a careful digestive-health dietitian: evidence-based, never alarmist, always clear that patterns are hypotheses to test with a clinician.",
 "Find what your gut is telling you", "A few details help the analysis.", ["Trigger analysis from your diary", "Low-FODMAP & elimination plans", "Restaurant survival guides"],
 [NAME, CH("condition", "Working with", ["IBS", "Reflux", "Lactose", "Gluten", "Unknown"], multi=True), TXT("meds", "Medications / supplements", "")],
 [T("analyse", "Analyse my diary", "Paste days of meals + symptoms", "🔎", [LONG("diary", "Diary", "Mon: oats + banana → fine; lunch garlic pasta → bloated 2h later…")],
    "Analyse this food/symptom diary: {diary}. Table (Suspect | Evidence | Confidence), bullets of safe foods observed, steps for a 1-week test of the top suspect, and a callout that this is a hypothesis.", "table, bullets, steps, callout", "Analyse", "Reading…"),
  T("lowfodmap", "Low-FODMAP day", "Meals that are gentle", "🥗", [CH("meals", "Plan", ["1 day", "3 days"], "1 day"), TXT("prefs", "Preferences", "")],
    "Low-FODMAP plan for {meals} with preferences {prefs}: table (Meal | Dish | Watch-outs), a checklist shopping list, and a callout on portion thresholds.", "table, checklist, callout", "Plan", "Planning…"),
  T("menu", "Restaurant scan", "Photo of a menu → safe picks", "📷", [PHOTO("Menu photo", "", True)],
    "From the menu photo, mark safe picks vs risky as a table (Dish | Verdict | Why | Ask the server to…), then a quote with exactly what to say to the waiter.", "table, quote", "Scan menu", "Reading…"),
  T("flare", "Flare-up plan", "What to do in the next 48h", "🩹", [CH("symptom", "Main symptom", ["Bloating", "Cramps", "Diarrhoea", "Constipation", "Reflux"], "Bloating")],
    "A calm 48-hour plan for {symptom}: steps (hydration, gentle foods, movement), bullets of foods to pause, and a callout listing red-flag symptoms that need a doctor now.", "steps, bullets, callout", "Help me", "Thinking…")], MED)

APP("sleep_reset", "Sleep Reset", "Fall asleep faster, wake up human", "Health & Fitness", ["#283593", "#FFB300", "#26A69A"], "moon",
 "Sleep Reset builds a personal wind-down routine, fixes jet lag and shift-work schedules, and analyses your sleep diary for what's actually keeping you up.",
 "You are a CBT-I-informed sleep coach: kind, specific, evidence-based; you avoid supplements-first advice.",
 "Reclaim your nights", "Your schedule shapes the advice.", ["Wind-down routines that stick", "Jet-lag & shift plans", "Diary analysis"],
 [NAME, F("wake", "Usual wake time", "text", "06:45"), F("bed", "Usual bedtime", "text", "23:30"), CH("issue", "Main issue", ["Falling asleep", "Staying asleep", "Waking too early", "Unrefreshing"])],
 [T("routine", "Wind-down routine", "60 minutes to sleep", "🌙", [TXT("evening", "Typical evening", "phone in bed, dinner at 9")],
    "Design a 60-minute wind-down given: {evening}. Steps with clock times working back from bedtime, a checklist of bedroom fixes, and a callout on the one habit to change first.", "steps, checklist, callout", "Build routine", "Dimming…"),
  T("jetlag", "Jet-lag plan", "Shift your clock before you fly", "✈️", [TXT("from", "From (city)", "London", True), TXT("to", "To (city)", "Tokyo", True), TXT("date", "Departure date", "")],
    "Jet-lag plan {from} → {to}, departing {date}: table (Day | Light exposure | Avoid light | Sleep window | Caffeine), a callout about melatonin timing (general info), and bullets for the flight itself.", "table, callout, bullets", "Plan", "Calculating…"),
  T("diary", "Analyse my sleep diary", "Find the pattern", "📓", [LONG("diary", "Diary", "Mon: bed 23:40, asleep ~00:30, woke 3am, coffee at 4pm…")],
    "Analyse: {diary}. Bullets of patterns, a table (Factor | Effect seen | Fix), steps for next week, and a callout on when to see a doctor (e.g. snoring, apnoea signs).", "bullets, table, steps, callout", "Analyse", "Reading…"),
  T("nap", "Nap & caffeine timing", "Today's optimal schedule", "☕", [F("slept", "Hours slept last night", "number", "5"), TXT("plan", "Today", "meeting at 3pm, gym at 6")],
    "Given {slept}h sleep and today: {plan} — kv (last caffeine time, nap window & length, light exposure, bedtime tonight) and bullets on getting through the afternoon dip.", "kv, bullets", "Optimise", "Scheduling…")], MED)

APP("posture_desk", "Desk Doctor", "Fix the aches from sitting all day", "Health & Fitness", ["#00838F", "#FF7043", "#7E57C2"], "shield",
 "Desk Doctor sets up your workstation from a photo, prescribes micro-break routines, and builds mobility plans for neck, back, wrists and hips.",
 "You are a physio-minded ergonomics coach: concise, practical, never diagnosing; you flag red flags.",
 "Sit better, hurt less", "Tell us where it hurts and how you work.", ["Workstation setup from a photo", "Micro-break routines", "Mobility plans"],
 [NAME, CH("pain", "Where it aches", ["Neck", "Upper back", "Lower back", "Wrists", "Hips", "Eyes"], multi=True), CH("setup", "Setup", ["Laptop only", "Monitor + laptop", "Standing desk", "Sofa/bed"])],
 [T("setup", "Check my desk", "Photo → adjustments", "📷", [PHOTO("Photo of your workstation (side view)", "", True)],
    "Assess the workstation photo: table (Element | Now | Target | How to fix), a checklist of free fixes, and a callout on what's worth buying if anything.", "table, checklist, callout", "Assess", "Measuring…"),
  T("breaks", "Micro-break routine", "2 minutes every hour", "⏱️", [CH("focus", "Focus", ["Neck & shoulders", "Lower back", "Wrists", "Eyes", "Whole body"], "Whole body")],
    "A 2-minute hourly routine for {focus}: steps (each with reps/seconds), bullets on cues, and a quote with a one-line reminder to set as an alarm label.", "steps, bullets, quote", "Build", "Stretching…"),
  T("mobility", "Mobility plan", "10 min/day, 2 weeks", "🧘", [CH("area", "Area", ["Neck", "Thoracic", "Lower back", "Hips", "Wrists"], "Lower back")],
    "A 2-week, 10-minute daily mobility plan for {area}: table (Day | Exercises | Sets×reps), steps for correct form of the two key moves, and a callout on red flags that mean stop and see a clinician.", "table, steps, callout", "Plan", "Planning…"),
  T("flare", "Pain right now", "What to do today", "🩹", [TXT("what", "What happened", "woke up with a stiff neck, can't turn left", True)],
    "For: {what} — steps for the next 24h (heat/ice, movement, positions), bullets of what to avoid, and a callout listing symptoms that need urgent care.", "steps, bullets, callout", "Help", "Thinking…")], MED)

APP("hydrate_hub", "Hydrate Hub", "Drink right for your body, sport and weather", "Health & Fitness", ["#0277BD", "#00BFA5", "#FFB300"], "drop",
 "Hydrate Hub calculates daily fluid and electrolyte needs, builds race-day hydration plans, and decodes sports-drink labels.",
 "You are a sports-nutrition hydration specialist: numbers-first, practical, safety-aware about over-drinking.",
 "Drink smarter, not just more", "Body stats make the numbers accurate.", ["Personal daily targets", "Race & heat plans", "Electrolyte recipes"],
 [NAME, NUM("weight", "Weight (kg)", "70"), CH("activity", "Activity", ["Desk", "Active", "Athlete"]), CH("climate", "Climate", ["Cool", "Temperate", "Hot", "Humid"])],
 [T("daily", "My daily target", "Fluids + when", "💧", [TXT("today", "Today", "45-min run at lunch, office AC")],
    "Daily hydration target for the profile, today: {today}. kv (total ml, per-hour baseline, extra for exercise, sodium note), a table (Time | Drink | Amount), and a callout on signs of over-drinking.", "kv, table, callout", "Calculate", "Measuring…"),
  T("race", "Race-day plan", "Marathon, cycle, hike, match", "🏁", [TXT("event", "Event", "half marathon, 2h target, 24°C", True), TXT("gut", "Gut tolerance", "gels make me queasy")],
    "Hydration + fuel plan for {event}, tolerance: {gut}. Table (Time | Fluid | Carbs | Sodium), steps for the 24h before, and a callout on cramps and hyponatraemia.", "table, steps, callout", "Plan", "Planning…"),
  T("diy", "DIY electrolyte drink", "Cheap and tuned", "🧪", [CH("for", "For", ["Everyday", "Long workout", "Hot day", "Hangover"], "Long workout")],
    "A DIY electrolyte recipe for {for}: kv (ingredients with grams), steps to mix, and a table comparing it to 3 common commercial drinks (Drink | Sodium | Carbs | Cost/L).", "kv, steps, table", "Mix", "Mixing…"),
  T("label", "Decode a drink label", "Photo → is it worth it", "📷", [PHOTO("Label photo", "", True)],
    "Read the label: kv (sodium, potassium, carbs, sugar, caffeine per serving), a text verdict on when it's useful, and bullets on cheaper alternatives.", "kv, text, bullets", "Decode", "Reading…")], MED)

APP("run_coach", "Run Plan", "Couch to 5K to marathon, adapted to your week", "Health & Fitness", ["#C62828", "#FFB300", "#00838F"], "flame",
 "Run Plan builds training blocks around your real schedule, adjusts after missed runs, predicts race times and reviews your weeks.",
 "You are an experienced running coach: progressive, injury-aware, allergic to junk miles; you explain the purpose of every session.",
 "Run your next best race", "Where are you now, where are you going?", ["Plans around your calendar", "Missed-run adjustments", "Race predictions"],
 [NAME, CH("level", "Level", ["Beginner", "5K–10K", "Half", "Marathon"]), TXT("recent", "Recent result", "5K in 27:30"), CH("days", "Days/week", ["3", "4", "5", "6"])],
 [T("block", "Training block", "Next 4 weeks", "🏃", [TXT("goal", "Goal race & date", "10K on 12 Oct", True), TXT("constraints", "Constraints", "long run Sundays only, no Wednesdays")],
    "A 4-week block toward {goal} with constraints {constraints}: table (Week | Mon | Tue | Wed | Thu | Fri | Sat | Sun), text explaining the purpose of each session type, and a callout on how to judge effort.", "table, text, callout", "Build block", "Planning…"),
  T("adjust", "I missed runs", "Re-plan the week", "🔁", [TXT("missed", "What happened", "sick Tue–Thu, long run planned Sunday", True)],
    "Adjust the current week given: {missed}. Steps for the remaining days, a callout on what NOT to cram, and bullets on returning after illness.", "steps, callout, bullets", "Re-plan", "Adjusting…"),
  T("predict", "Race predictor", "Paces and a race plan", "⏱️", [TXT("race", "Target race", "half marathon", True)],
    "Predict a {race} time from the recent result and level: kv (predicted time, easy pace, tempo pace, interval pace), a table of even/negative split checkpoints, and bullets for race-week.", "kv, table, bullets", "Predict", "Calculating…"),
  T("review", "Review my week", "Paste your log", "📓", [LONG("log", "This week's runs", "Mon 5k easy 5:40/km HR 150; Wed 6×400…")],
    "Review: {log}. Bullets of what went well, a callout on the biggest risk (overreaching / too easy / niggles), steps for next week, and a quote with one focus cue.", "bullets, callout, steps, quote", "Review", "Reading…")], "Not medical advice; stop and see a clinician for sharp pain, chest symptoms or dizziness.")

APP("yoga_flow", "Flow Builder", "Yoga sequences for how you feel right now", "Health & Fitness", ["#7E57C2", "#26A69A", "#FFB74D"], "sun",
 "Flow Builder writes yoga and mobility sequences for your time, level and mood, with cues, modifications and a breathing practice to match.",
 "You are a thoughtful yoga teacher: anatomically careful, inclusive, with clear cues and options for every body.",
 "Roll out the mat", "A little about your practice.", ["Sequences for any time slot", "Modifications for injuries", "Breathwork & meditation"],
 [NAME, CH("level", "Level", ["New", "Some experience", "Regular"]), TXT("injuries", "Injuries / limits", "tight hamstrings, wrist pain")],
 [T("flow", "Build a flow", "Tell me time + mood", "🧘", [CH("minutes", "Minutes", ["10", "20", "30", "45"], "20"), CH("mood", "I need", ["Energy", "Calm", "Stretch", "Strength", "Back relief", "Sleep"], "Calm")],
    "A {minutes}-minute sequence for '{mood}' honouring the profile limits: steps (pose · breaths · cue), a callout on modifications for the listed injuries, and a quote with the intention for the practice.", "steps, callout, quote", "Build flow", "Sequencing…"),
  T("pose", "Fix a pose", "Photo or description", "📷", [PHOTO("Photo of you in the pose (optional)"), TXT("pose", "Pose", "downward dog")],
    "Coach {pose} from the photo/description: bullets on alignment fixes, steps to enter safely, a callout on what to avoid with the profile's limits.", "bullets, steps, callout", "Coach", "Observing…"),
  T("breath", "Breathwork", "5 minutes to shift state", "🌬️", [CH("goal", "Goal", ["Calm down", "Wake up", "Focus", "Sleep"], "Calm down")],
    "A 5-minute breathing practice to {goal}: steps with counts, a callout on contraindications, and text on what to notice.", "steps, callout, text", "Guide me", "Breathing…"),
  T("challenge", "7-day challenge", "A week of short practices", "📅", [CH("focus", "Focus", ["Flexibility", "Core", "Morning energy", "Stress"], "Flexibility")],
    "A 7-day {focus} challenge: table (Day | Focus | Minutes | Key poses), bullets on progression, and a callout on rest.", "table, bullets, callout", "Start", "Planning…")], "Listen to your body; not a substitute for medical advice.")
