from dsl import *
FIN = "General information, not financial, tax or legal advice; consult a licensed professional for your situation."

APP("split_smart", "Split Smart", "Fair bill splitting, no arguments", "Finance", ["#00695C", "#F4B400", "#6A4CB0"], "coin",
 "Split Smart reads receipts, splits by item or share, handles tips and tax, and writes the message that gets everyone to pay.",
 "You are a fair, tactful bill-splitting assistant who shows the maths.",
 "Never argue over the bill again", "Set your currency and default tip.", ["Receipt photo → per-person totals", "Uneven splits and shared items", "Ready-to-send payment messages"],
 [NAME, F("currency", "Currency symbol", "text", "$", default="$"), CH("tip", "Default tip", ["0%", "10%", "15%", "18%", "20%"], "15%")],
 [T("receipt", "Split a receipt", "Photo + who had what", "🧾", [PHOTO("Receipt photo", "", True), LONG("who", "Who had what", "Ana: pasta + wine; Ben: steak; shared: starter, dessert", False)],
    "Read the receipt, then split using: {who}. Apply the default tip and tax proportionally. Table (Person | Items | Subtotal | Tax+tip share | Total), a text section showing the maths, and a quote with a friendly group message listing each amount.", "table, text, quote", "Split it", "Reading…"),
  T("manual", "Quick split", "No photo, just numbers", "➗", [NUM("total", "Total bill", "126.40"), LONG("people", "People & shares", "Ana 1, Ben 1, Cara 0.5 (only a starter)")],
    "Split {total} among: {people} with the default tip. Table (Person | Share | Amount) and a quote with the message to send.", "table, quote", "Split", "Calculating…"),
  T("trip", "Trip settle-up", "Who owes whom after a trip", "🧳", [LONG("expenses", "Expenses", "Hotel 400 paid by Ana (all 3); dinner 90 paid by Ben (Ana, Ben)…")],
    "Settle up: {expenses}. Table (Person | Paid | Owes | Net), then steps with the minimum number of transfers, and a quote with the settle-up message.", "table, steps, quote", "Settle", "Balancing…"),
  T("nudge", "Polite reminder", "Chase money without awkwardness", "💬", [TXT("who", "Who", "Ben", True), NUM("amount", "Amount", "32.50"), CH("tone", "Tone", ["Light", "Direct", "Very polite"], "Light")],
    "Write 3 short reminder messages to {who} for {amount}, tone {tone}, as quote sections, and bullets on timing.", "quote, quote, quote, bullets", "Write", "Drafting…")])

APP("budget_buddy", "Budget Buddy", "A monthly budget that fits your real life", "Finance", ["#1565C0", "#FF8F00", "#2E7D32"], "coin",
 "Budget Buddy builds zero-based or 50/30/20 budgets from your income and bills, finds cuts you won't hate, and plans debt payoff.",
 "You are a non-judgemental money coach: concrete numbers, no shame, small wins first.",
 "Tell your money where to go", "Income and fixed costs make it real.", ["Budgets from your real numbers", "Painless cuts", "Debt snowball/avalanche plans"],
 [NAME, F("currency", "Currency", "text", "$", default="$"), NUM("income", "Monthly take-home", "3200"), TXT("goal", "Biggest money goal", "emergency fund, pay off card")],
 [T("budget", "Build my budget", "From bills to a plan", "📊", [LONG("bills", "Fixed bills", "rent 1200, car 300, phone 45, subscriptions ~60"), CH("style", "Style", ["50/30/20", "Zero-based", "Pay-yourself-first"], "50/30/20")],
    "Build a {style} monthly budget from income and bills: {bills}. Table (Category | Amount | % of income | Note), a callout on the one number that matters most, and a checklist of accounts/automations to set up.", "table, callout, checklist", "Build", "Crunching…"),
  T("cuts", "Find cuts", "Save without misery", "✂️", [LONG("spending", "Last month's spending", "eating out 340, groceries 420, Uber 90…")],
    "Find savings in: {spending}. Cards (cut, meta = monthly saving) ranked by ease, a callout on what NOT to cut, and steps for the first week.", "cards, callout, steps", "Find cuts", "Looking…"),
  T("debt", "Debt payoff plan", "Snowball vs avalanche", "🏔️", [LONG("debts", "Debts", "Card A 2400 @ 24%, min 60; Car 8000 @ 6%, min 210"), NUM("extra", "Extra per month", "150")],
    "Payoff plan for: {debts} with {extra} extra/month. Table comparing snowball vs avalanche (Method | Order | Payoff date | Interest paid), steps for month one, and a callout on refinancing/balance transfers (general).", "table, steps, callout", "Plan", "Calculating…"),
  T("bigbuy", "Can I afford it?", "Sanity-check a purchase", "🛍️", [TXT("item", "Purchase", "new laptop 1500", True), CH("how", "Paying", ["Cash", "Card", "Financing"], "Cash")],
    "Should the user buy {item} paying by {how}? kv (cost vs monthly surplus, months of saving, true cost with interest), bullets of cheaper routes, and a callout with a clear verdict.", "kv, bullets, callout", "Check", "Thinking…")], FIN)

APP("invoice_ninja_lite", "Invoice Pen", "Invoices, quotes and payment chasers for freelancers", "Business", ["#37474F", "#FF7043", "#26A69A"], "note",
 "Invoice Pen drafts professional invoices and quotes as clean text you can paste anywhere, calculates tax, and writes firm-but-friendly payment reminders.",
 "You are a freelancer's back-office: precise with numbers, polite with clients, firm on payment terms.",
 "Get paid on time", "Your business details go on every document.", ["Invoices & quotes in seconds", "Tax and totals done right", "Payment reminders that work"],
 [F("biz", "Business name", "text", "", required=True), F("details", "Address / tax ID / bank details", "longtext", ""), F("currency", "Currency", "text", "$", default="$"), NUM("tax", "Default tax %", "0")],
 [T("invoice", "Draft an invoice", "Items → formatted invoice", "🧾", [TXT("client", "Client", "Acme Ltd, attn. Jo", True), LONG("items", "Line items", "Logo design 2 days @ 400; Revisions 3h @ 60"), CH("terms", "Terms", ["Due on receipt", "Net 7", "Net 14", "Net 30"], "Net 14")],
    "Draft invoice from {biz} to {client}: items {items}, terms {terms}, default tax. Table (Description | Qty | Rate | Amount), kv (subtotal, tax, total, due date, invoice number suggestion), and a quote with the email body to send it.", "table, kv, quote", "Draft", "Drafting…"),
  T("quote", "Write a quote", "Scope, price, terms", "💼", [TXT("client", "Client", "", True), LONG("scope", "What they want", "5-page website, copy provided, 3 weeks"), NUM("rate", "Your rate", "")],
    "Write a quote for {client}: {scope} at rate {rate}. kv (price, timeline, payment schedule, validity), bullets of what's included/excluded, and a callout on assumptions to confirm.", "kv, bullets, callout", "Quote", "Pricing…"),
  T("chase", "Chase a payment", "Overdue? Escalate politely", "⏰", [TXT("client", "Client", "", True), NUM("amount", "Amount", ""), NUM("days", "Days overdue", "10")],
    "Three escalating messages to {client} for {amount}, {days} days overdue: quote (friendly), quote (firm), quote (final notice mentioning late fees/next steps), and bullets on when to send each.", "quote, quote, quote, bullets", "Write", "Drafting…"),
  T("tax", "Tax set-aside", "How much to keep back", "🏦", [NUM("earned", "Earned this month", "4200"), TXT("country", "Country", "UK")],
    "For {earned} earned in {country} as a freelancer: kv (suggested set-aside %, amount, quarterly estimate), bullets of common deductible expenses, and a callout to confirm with an accountant.", "kv, bullets, callout", "Estimate", "Estimating…")], FIN)

APP("focus_sprint", "Focus Sprint", "Beat procrastination one sprint at a time", "Productivity", ["#3949AB", "#FF6F00", "#00897B"], "clock",
 "Focus Sprint breaks scary tasks into 25-minute sprints, writes your first tiny step, and runs a quick review so tomorrow starts easier.",
 "You are an ADHD-friendly productivity coach: zero guilt, tiny first steps, external structure.",
 "Start in the next 5 minutes", "How do you like to work?", ["Tasks → sprint plans", "The smallest first step", "End-of-day reviews"],
 [NAME, CH("style", "Works best for you", ["Pomodoro", "Time-blocking", "Body doubling", "Deadlines"], multi=True), CH("energy", "Peak energy", ["Morning", "Afternoon", "Night"])],
 [T("sprint", "Plan sprints", "One scary task → sprints", "🏃", [TXT("task", "The task", "write the quarterly report", True), CH("hours", "Time available", ["1", "2", "3", "4"], "2")],
    "Break '{task}' into 25-min sprints for {hours} hours: table (Sprint | Goal | Done when), a quote with the very first 2-minute action, and a callout on the likely distraction and its countermeasure.", "table, quote, callout", "Plan sprints", "Chunking…"),
  T("unstick", "I'm stuck", "Get unstuck now", "🧱", [TXT("stuck", "What's happening", "I keep opening the doc and closing it", True)],
    "The user is stuck: {stuck}. Text naming the likely block (fear, unclear, boring, too big), steps for the next 10 minutes, and a quote with a self-talk line.", "text, steps, quote", "Unstick me", "Thinking…"),
  T("day", "Plan my day", "Tasks → a realistic schedule", "🗓️", [LONG("tasks", "Today's tasks", "report draft (2h), emails, call dentist, gym"), TXT("fixed", "Fixed events", "meeting 2–3pm")],
    "Schedule: {tasks} around {fixed} respecting peak energy. Table (Time | Block | Kind), a callout on what to drop if it slips, and a checklist for the morning start.", "table, callout, checklist", "Plan", "Scheduling…"),
  T("review", "End-of-day review", "2 minutes, honest", "🌙", [LONG("done", "What happened today", "did 3 sprints, got derailed by Slack, skipped gym")],
    "Review: {done}. Bullets (wins), a callout (one pattern to watch), kv (tomorrow's top 3 with first steps), and a quote to close the day kindly.", "bullets, callout, kv, quote", "Review", "Reflecting…")])

APP("meeting_mate", "Meeting Mate", "Agendas in, decisions out", "Productivity", ["#00695C", "#FFB300", "#5C6BC0"], "note",
 "Meeting Mate writes tight agendas, turns messy notes into minutes with owners and deadlines, and drafts the follow-up email.",
 "You are a crisp chief-of-staff: agendas with time boxes, minutes with owners, no fluff.",
 "Meetings that end on time", "Your role shapes the tone.", ["Time-boxed agendas", "Notes → minutes with owners", "Follow-up emails"],
 [NAME, F("role", "Your role", "text", "product manager"), F("team", "Team / company", "text", "")],
 [T("agenda", "Write an agenda", "Purpose → time-boxed plan", "📋", [TXT("purpose", "Meeting purpose", "decide Q4 roadmap priorities", True), NUM("minutes", "Length (min)", "45"), TXT("people", "Attendees", "eng lead, design, sales")],
    "Agenda for '{purpose}', {minutes} min, attendees {people}. Table (Time | Item | Owner | Outcome), a callout on pre-reads, and a quote with the calendar-invite description.", "table, callout, quote", "Write agenda", "Drafting…"),
  T("minutes", "Notes → minutes", "Paste raw notes", "📝", [LONG("notes", "Raw notes", "jo said budget tight, sam to check vendor by fri, decided to delay launch…")],
    "Turn into minutes: {notes}. Sections: bullets (decisions), table (Action | Owner | Due), bullets (open questions), and a quote with a 3-line summary for people who weren't there.", "bullets, table, bullets, quote", "Make minutes", "Tidying…"),
  T("followup", "Follow-up email", "Send within the hour", "✉️", [LONG("summary", "What was agreed", "")],
    "Follow-up email from the summary: {summary}. quote (subject + body), checklist of attachments/links to include.", "quote, checklist", "Draft", "Writing…"),
  T("cancel", "Should this be a meeting?", "Or an email", "🤔", [TXT("ask", "The meeting idea", "weekly status sync with 8 people", True)],
    "Assess '{ask}': callout verdict (meeting / async / cancel), bullets of reasoning, and a quote with the async alternative message if applicable.", "callout, bullets, quote", "Assess", "Judging…")])

APP("resume_forge", "Résumé Forge", "CVs and cover letters that pass the screen", "Business", ["#1E88E5", "#FF7043", "#43A047"], "note",
 "Résumé Forge tailors your CV to a job posting, writes cover letters in your voice, preps interview answers and negotiates offers.",
 "You are a senior recruiter turned career coach: ATS-savvy, allergic to clichés, insists on quantified achievements.",
 "Land the interview", "Paste your current CV once; we'll reuse it.", ["CV tailored to each job", "Cover letters in your voice", "Interview & salary prep"],
 [NAME, F("cv", "Your current CV (paste)", "longtext", ""), F("target", "Target roles", "text", "senior product designer")],
 [T("tailor", "Tailor my CV", "To a specific posting", "🎯", [LONG("job", "Job posting", "paste the description")],
    "Tailor the profile CV to this posting: {job}. Sections: bullets (keyword gaps to add), cards (rewritten bullets: title = original, body = improved with metrics), a callout on ATS formatting, and a quote with a 3-line professional summary.", "bullets, cards, callout, quote", "Tailor", "Matching…"),
  T("cover", "Cover letter", "Specific, short, human", "✉️", [LONG("job", "Job posting or company", ""), TXT("why", "Why you want it", "")],
    "Write a 180-220 word cover letter for {job}; motivation: {why}. quote (the letter), bullets on what to customise before sending.", "quote, bullets", "Write", "Writing…"),
  T("interview", "Interview prep", "Likely questions + your answers", "🎤", [TXT("role", "Role / company", "", True)],
    "Prep for {role}: cards (question, body = STAR answer outline from the CV, meta = type), bullets of questions to ask them, and a callout on the one weakness to prepare for.", "cards, bullets, callout", "Prep", "Preparing…"),
  T("offer", "Negotiate an offer", "Scripts and numbers", "💰", [TXT("offer", "The offer", "85k base, 10% bonus", True), TXT("want", "What you want", "95k")],
    "Negotiation plan for offer {offer} aiming for {want}: text on market framing, quote (the counter-offer email), quote (the phone script), and a callout on what not to say.", "text, quote, quote, callout", "Plan", "Strategising…")])

APP("study_planner", "Exam Countdown", "A revision timetable that adapts to you", "Education", ["#5E35B1", "#FFB300", "#00ACC1"], "calendar",
 "Exam Countdown turns your subjects and exam dates into a spaced-repetition revision timetable, then builds active-recall sessions and past-paper strategies.",
 "You are an evidence-based study coach: spaced repetition, active recall, interleaving; realistic about energy and procrastination.",
 "Revise smarter, not longer", "Your exams and weekly hours shape the plan.", ["Timetables that respect your life", "Active-recall sessions", "Exam-day strategy"],
 [NAME, LONG("exams", "Subjects & exam dates", "Biology 12 Jun, Maths 15 Jun, History 20 Jun", False), CH("hours", "Study hours/week", ["5", "10", "15", "20+"])],
 [T("timetable", "Build timetable", "From today to the exams", "📅", [TXT("weak", "Weakest topics", "cell division, integration"), TXT("busy", "Busy days", "Sat mornings football")],
    "Revision timetable from the profile exams, weak topics {weak}, busy: {busy}. Table (Date | Subject | Topic | Method (recall/practice/review)), a callout on spacing logic, and a checklist for the week before each exam.", "table, callout, checklist", "Build", "Scheduling…"),
  T("session", "Study session", "45 minutes, one topic", "⏱️", [TXT("topic", "Topic", "photosynthesis", True)],
    "A 45-minute active-recall session on {topic}: steps (timed blocks), bullets of 8 recall questions with brief answers, and a quote with a one-line mnemonic.", "steps, bullets, quote", "Start", "Preparing…"),
  T("paper", "Past-paper strategy", "How to attack the exam", "📝", [TXT("exam", "Exam", "GCSE Maths Paper 2", True)],
    "Strategy for {exam}: table (Section | Marks | Minutes | Tips), bullets of common mark-losers, and a callout on the last 5 minutes.", "table, bullets, callout", "Strategy", "Planning…"),
  T("slump", "I'm behind", "Rescue plan", "🆘", [TXT("situation", "Situation", "exam in 6 days, barely started", True)],
    "Triage for: {situation}. Callout (what to accept), table (Day | Priority topics | Hours), steps for tonight, and a quote of encouragement.", "callout, table, steps, quote", "Rescue me", "Triaging…")])

APP("habit_architect", "Habit Architect", "Design habits that survive bad weeks", "Productivity", ["#00897B", "#FF7043", "#5C6BC0"], "gear",
 "Habit Architect designs tiny habits with cues and rewards, stacks them onto routines you already have, and troubleshoots when you fall off.",
 "You are a behaviour-design coach (Fogg/Clear style): tiny, anchored, celebrated; never moralising.",
 "Make it obvious, easy and satisfying", "Tell us your routine anchors.", ["Habit recipes with cues", "Habit stacking on your day", "Relapse recovery"],
 [NAME, F("morning", "Morning routine", "text", "coffee, shower, commute at 8"), F("evening", "Evening routine", "text", "dinner at 7, TV, bed 11")],
 [T("design", "Design a habit", "From wish to recipe", "🧩", [TXT("habit", "I want to", "read more", True), CH("when", "When", ["Morning", "Midday", "Evening", "Anytime"], "Evening")],
    "Design '{habit}' for {when} using the routine anchors: kv (tiny version, anchor cue, celebration, scale-up plan), a callout on the biggest friction and its fix, and a quote of the habit recipe sentence ('After I…, I will…').", "kv, callout, quote", "Design", "Designing…"),
  T("stack", "Stack my morning", "Fit 3 habits into it", "🌅", [LONG("habits", "Habits to fit", "stretch, journal, vitamins", False)],
    "Stack {habits} onto the morning routine: table (Anchor | New habit | Tiny version | Minutes), steps for the first 3 days, and a callout on what to drop if late.", "table, steps, callout", "Stack", "Arranging…"),
  T("relapse", "I fell off", "Get back without guilt", "🔄", [TXT("what", "What happened", "stopped going to the gym 3 weeks ago", True)],
    "Recovery for: {what}. Text (reframe), steps for a 'never miss twice' restart at 20% size, and a quote to say to yourself.", "text, steps, quote", "Restart", "Reframing…"),
  T("tracker", "Weekly tracker", "Printable checklist", "✅", [LONG("habits", "Habits", "water, walk, no phone in bed", False)],
    "A weekly tracker for {habits}: table (Habit | Mon | Tue | Wed | Thu | Fri | Sat | Sun) with empty cells, bullets on scoring, and a callout on the 80% rule.", "table, bullets, callout", "Make", "Drawing…")])

APP("side_hustle", "Side Hustle Lab", "Validate and launch a small business in a weekend", "Business", ["#EF6C00", "#00838F", "#5E35B1"], "bulb",
 "Side Hustle Lab pressure-tests ideas, writes a one-page plan, prices your offer, and drafts the first landing page and launch posts.",
 "You are a scrappy startup mentor: customer-first, cash-flow honest, allergic to vanity plans.",
 "From idea to first customer", "Your skills and hours decide what's realistic.", ["Idea validation", "One-page plans & pricing", "Landing page + launch posts"],
 [NAME, F("skills", "Skills / assets", "text", "graphic design, a car, weekends"), CH("hours", "Hours/week", ["5", "10", "20", "Full-time"]), NUM("cash", "Cash to start", "500")],
 [T("validate", "Validate an idea", "Will anyone pay?", "🔬", [TXT("idea", "The idea", "dog-walking with GPS updates", True)],
    "Validate '{idea}' for the profile: kv (customer, pain, alternatives, willingness to pay, unfair advantage), table (Risk | Test | Cost | Days), a callout verdict, and steps for a 7-day test.", "kv, table, callout, steps", "Validate", "Stress-testing…"),
  T("plan", "One-page plan", "Model, costs, first 90 days", "📄", [TXT("idea", "The idea", "", True)],
    "One-page plan for {idea}: kv (offer, price, channel, cost to deliver, break-even), table (Month | Goal | Actions | Cash), and a callout on the biggest assumption.", "kv, table, callout", "Write plan", "Planning…"),
  T("price", "Price it", "Packages and anchors", "💲", [TXT("offer", "Offer", "logo + brand kit", True)],
    "Pricing for {offer}: cards (3 packages: title, body = what's in it, meta = price), text on anchoring logic, and bullets on objections and answers.", "cards, text, bullets", "Price", "Pricing…"),
  T("launch", "Launch kit", "Landing copy + posts", "🚀", [TXT("offer", "Offer", "", True), CH("channel", "Channels", ["Instagram", "LinkedIn", "WhatsApp groups", "Local Facebook", "TikTok"], multi=True)],
    "Launch kit for {offer} on {channel}: quote (landing-page hero + 3 bullets + CTA), cards (one post per channel, meta = channel), and a checklist for launch day.", "quote, cards, checklist", "Build kit", "Writing…")], FIN)

APP("negotiator", "Haggle", "Scripts for every negotiation", "Business", ["#37474F", "#FFB300", "#00897B"], "scale",
 "Haggle prepares you for salary talks, rent, car deals, freelance rates and refunds with numbers, scripts and counters.",
 "You are a calm negotiation coach (Voss/Fisher-style): interests over positions, anchors, silence, walk-away points.",
 "Get a better deal, politely", "A little context sharpens the scripts.", ["Prep sheets with walk-away points", "Word-for-word scripts", "Counter-offer playbooks"],
 [NAME, CH("style", "Your natural style", ["Avoid conflict", "Direct", "Analytical", "Charming"])],
 [T("prep", "Prep sheet", "Any negotiation", "📋", [TXT("what", "Negotiation", "rent increase from 1200 to 1350", True), TXT("facts", "Facts you know", "similar flats list at 1250")],
    "Prep for: {what}; facts: {facts}. kv (target, walk-away, their likely interests, your leverage, BATNA), table (Their move | Your counter), and a quote with the opening line.", "kv, table, quote", "Prepare", "Preparing…"),
  T("script", "Give me a script", "What to actually say", "🎭", [TXT("situation", "Situation", "asking for a raise after 2 years", True)],
    "Script for: {situation}. quote (opening), quote (if they push back), quote (closing with a next step), and bullets on tone and silence.", "quote, quote, quote, bullets", "Write script", "Writing…"),
  T("email", "Negotiation email", "Counter in writing", "✉️", [LONG("offer", "Their offer / message", ""), TXT("want", "What you want", "")],
    "Draft a counter to: {offer}, aiming for {want}. quote (email), callout on one thing to remove if it feels too aggressive.", "quote, callout", "Draft", "Drafting…"),
  T("refund", "Get a refund", "Consumer complaint that works", "↩️", [TXT("issue", "What went wrong", "flight cancelled, no refund after 30 days", True), TXT("company", "Company", "")],
    "Complaint to {company} about {issue}: quote (message citing typical consumer rights in general terms), steps for escalation (chargeback, ombudsman, regulator), and a callout on documentation to keep.", "quote, steps, callout", "Draft", "Drafting…")])
