from dsl import *

APP("closet_stylist", "Closet Stylist", "Outfits from the clothes you already own", "Lifestyle", ["#AD1457", "#00897B", "#FFB300"], "bag",
 "Closet Stylist builds outfits from your wardrobe photos, plans capsule wardrobes, and tells you what to pack or buy next.",
 "You are a practical personal stylist: body-neutral, budget-aware, focused on fit, colour and repeat-wear.",
 "Wear what you own, better", "Your style and climate shape the advice.", ["Outfits from your closet", "Capsule wardrobe plans", "Shop-smart lists"],
 [NAME, CH("style", "Style words", ["Minimal", "Classic", "Streetwear", "Boho", "Smart-casual", "Sporty"], multi=True), CH("climate", "Climate", ["Cold", "Mild", "Hot", "Four seasons"]), TXT("colours", "Colours you love / avoid", "")],
 [T("outfit", "Dress me", "Occasion + weather → outfits", "👗", [TXT("occasion", "Occasion", "client lunch, then drinks", True), TXT("weather", "Weather", "18°C, rain later"), PHOTO("Photo of options (optional)")],
    "Build 3 outfits for {occasion} in {weather} from the style profile (and photo if given): cards (outfit, body = pieces + why, meta = vibe), bullets on shoes/bag/layers, and a callout on the one thing that elevates it.", "cards, bullets, callout", "Style me", "Styling…"),
  T("closet", "Audit my closet", "Photo → keep/alter/donate", "📷", [PHOTO("Photo of a rail or drawer", "", True)],
    "Audit the clothes visible: table (Item | Verdict keep/alter/donate | Why), bullets of 5 new outfit combos from the keepers, and a callout on gaps.", "table, bullets, callout", "Audit", "Looking…"),
  T("capsule", "Capsule wardrobe", "30 pieces, 100 outfits", "🧳", [CH("season", "Season", ["Spring", "Summer", "Autumn", "Winter"], "Autumn"), NUM("budget", "Budget for gaps", "200")],
    "A {season} capsule for the profile with {budget} for gaps: table (Category | Piece | Colour | Have/Buy), bullets of 8 outfit formulas, and a callout on fabric care.", "table, bullets, callout", "Build capsule", "Curating…"),
  T("pack", "Pack for a trip", "Nothing unworn", "✈️", [TXT("trip", "Trip", "4 days Lisbon, mix of walking and dinners", True)],
    "Packing list for {trip} with max mixing: table (Piece | Days worn | Outfits), a checklist to pack, and a callout on what to leave out.", "table, checklist, callout", "Pack", "Packing…")])

APP("plant_doctor", "Leaf Doctor", "Identify, diagnose and care for houseplants", "House & Home", ["#2E7D32", "#FF8F00", "#0288D1"], "leaf",
 "Leaf Doctor identifies plants from a photo, builds care schedules, diagnoses yellow leaves and pests, and plans propagation.",
 "You are a botanist and houseplant whisperer: precise about light, water and roots; honest about confidence.",
 "Keep them alive and thriving", "Your home conditions matter.", ["Photo identification", "Care schedules", "Pest & problem diagnosis"],
 [NAME, CH("light", "Light at home", ["Low", "Medium", "Bright indirect", "Direct sun"]), CH("climate", "Climate", ["Tropical", "Arid", "Temperate", "Cold"]), CH("pets", "Pets?", ["Cats", "Dogs", "None"], multi=True)],
 [T("id", "Identify & care", "Photo → species + care plan", "🔍", [PHOTO("Photo of the plant", "", True)],
    "Identify the plant (state confidence). kv (common/scientific name, water interval, light, humidity, feeding, toxicity for the profile's pets), steps for the next 2 weeks, and bullets of 3 specific tips.", "kv, steps, bullets", "Identify", "Examining…"),
  T("diagnose", "What's wrong?", "Photo + symptoms → fix", "🩺", [PHOTO("Photo of the problem"), TXT("symptoms", "Symptoms", "yellow lower leaves, soil smells", True), TXT("care", "Recent care", "watered twice a week")],
    "Diagnose: {symptoms}; care: {care}. Text (likely issue + confidence), bullets (ranked causes), steps to fix, and a callout on urgency.", "text, bullets, steps, callout", "Diagnose", "Examining…"),
  T("schedule", "Care calendar", "All my plants, one week", "📅", [LONG("plants", "Your plants", "monstera (living room), pothos (bathroom), snake plant (bedroom)")],
    "Weekly care calendar for: {plants} in the profile conditions: table (Plant | Water | Feed | Rotate/Clean | Notes), and a callout on seasonal changes.", "table, callout", "Plan", "Scheduling…"),
  T("propagate", "Propagate", "Make more plants", "🌱", [TXT("plant", "Plant", "pothos", True)],
    "Propagation guide for {plant}: steps with timing, kv (method, time to root, success rate, best season), and bullets of common mistakes.", "steps, kv, bullets", "Guide me", "Rooting…")])

APP("home_fixit", "Fix-It Guide", "DIY repairs, explained step by step", "House & Home", ["#EF6C00", "#37474F", "#00838F"], "wrench",
 "Fix-It Guide diagnoses household problems from a photo, walks you through repairs with tools and safety, and tells you when to call a pro.",
 "You are a seasoned handyperson: safety-first, plain-spoken, honest about when a job needs a licensed trade.",
 "Fix it yourself, safely", "Your skill and tools set the guidance level.", ["Photo diagnosis", "Step-by-step repairs", "Call-a-pro guidance"],
 [NAME, CH("skill", "DIY skill", ["Beginner", "Handy", "Confident"]), TXT("tools", "Tools you own", "drill, basic screwdrivers")],
 [T("diagnose", "What's this problem?", "Photo → diagnosis", "📷", [PHOTO("Photo of the issue", "", True), TXT("desc", "Describe it", "tap drips even when off")],
    "Diagnose from photo + '{desc}': text (what it is), bullets (likely causes), a callout (DIY / call a pro, safety), and steps for the fix with tools and parts.", "text, bullets, callout, steps", "Diagnose", "Inspecting…"),
  T("howto", "How do I…", "Any repair", "🔧", [TXT("task", "Task", "replace a bathroom silicone seal", True)],
    "Guide for '{task}' at the profile's skill: checklist (tools & materials with rough cost), steps, a callout on safety/shut-offs, and bullets of pro tips.", "checklist, steps, callout, bullets", "Show me", "Writing…"),
  T("callpro", "Should I call someone?", "And what to ask", "☎️", [TXT("issue", "Issue", "breaker keeps tripping", True)],
    "For '{issue}': callout (DIY or which trade), bullets of questions to ask the tradesperson, kv (typical price range, time, red flags of a bad quote).", "callout, bullets, kv", "Advise", "Thinking…"),
  T("maintain", "Seasonal checklist", "Prevent expensive surprises", "🗓️", [CH("season", "Season", ["Spring", "Summer", "Autumn", "Winter"], "Autumn"), CH("home", "Home", ["Flat", "House", "Old house"], "House")],
    "A {season} maintenance checklist for a {home}: checklist grouped by area, a callout on the one job people skip, and kv (rough time & cost).", "checklist, callout, kv", "Checklist", "Listing…")], "Turn off power/water before working and follow local codes; some jobs legally require a licensed professional.")

APP("declutter_coach", "Declutter Coach", "A calmer home, one drawer at a time", "House & Home", ["#00897B", "#FFB74D", "#7E57C2"], "home",
 "Declutter Coach plans room-by-room sessions, decides what to keep from a photo, and designs storage that actually gets used.",
 "You are a gentle professional organiser: decisive, non-judgemental, focused on daily flow over Instagram perfection.",
 "Less stuff, more space", "How much time and what's hardest to let go?", ["15-minute sessions", "Photo keep/toss decisions", "Storage plans"],
 [NAME, CH("home", "Home", ["Studio", "Flat", "House"]), CH("hard", "Hardest to let go", ["Clothes", "Papers", "Sentimental", "Kitchen", "Kids' stuff"], multi=True)],
 [T("session", "Plan a session", "Room + minutes → plan", "⏱️", [TXT("area", "Area", "hall cupboard", True), CH("minutes", "Minutes", ["15", "30", "60"], "30")],
    "A {minutes}-minute session for {area}: steps with timings, a checklist of supplies (boxes: keep/donate/trash/relocate), and a quote with a decision rule for the hard items.", "steps, checklist, quote", "Plan", "Planning…"),
  T("photo", "Sort this photo", "What to keep", "📷", [PHOTO("Photo of a shelf, drawer or pile", "", True)],
    "Sort the visible items: table (Item | Keep/Donate/Toss/Relocate | Why), then bullets on how to store the keepers, and a callout on the emotional item.", "table, bullets, callout", "Sort", "Looking…"),
  T("storage", "Storage plan", "Make it easy to keep tidy", "🗄️", [TXT("space", "Space", "small kitchen, no pantry", True), NUM("budget", "Budget", "80")],
    "Storage plan for {space} under {budget}: cards (solution, body = what goes where, meta = cost), a callout on the 'landing zone' habit, and bullets of measurements to take.", "cards, callout, bullets", "Plan", "Designing…"),
  T("month", "30-day plan", "Whole home", "📅", [CH("pace", "Pace", ["Gentle", "Steady", "Blitz"], "Steady")],
    "A 30-day {pace} plan for the home: table (Day | Area | Minutes | Goal), a callout on rest days, and a quote with a mantra.", "table, callout, quote", "Plan", "Scheduling…")])

APP("dog_trainer", "Good Dog", "Training plans and behaviour fixes for your dog", "Lifestyle", ["#8D6E63", "#FF8F00", "#26A69A"], "paw",
 "Good Dog builds positive-reinforcement training plans, decodes behaviour problems, and helps with puppies, recall and reactivity.",
 "You are a certified force-free dog trainer: patient, science-based, clear about management vs training.",
 "Train with kindness", "Tell us about your dog.", ["Step-by-step training plans", "Behaviour troubleshooting", "Puppy schedules"],
 [F("dog", "Dog's name, breed, age", "text", "Milo, beagle, 8 months", required=True), CH("issues", "Working on", ["Pulling", "Recall", "Barking", "Separation", "Jumping", "Reactivity", "Toilet training"], multi=True), CH("time", "Training time/day", ["5 min", "15 min", "30 min"])],
 [T("plan", "Teach a skill", "A week-by-week plan", "🎓", [TXT("skill", "Skill", "reliable recall", True)],
    "A 4-week plan to teach {skill}: table (Week | Goal | Drill | Criteria to advance), steps for session 1, and a callout on common mistakes and when to go back a step.", "table, steps, callout", "Plan", "Planning…"),
  T("behaviour", "Fix a behaviour", "Understand and change it", "🐾", [TXT("problem", "What's happening", "barks at every passer-by from the window", True)],
    "Analyse '{problem}': text (likely function of the behaviour), bullets (management now), steps (training protocol), and a callout on when to see a vet/behaviourist.", "text, bullets, steps, callout", "Help", "Analysing…"),
  T("puppy", "Puppy day plan", "Sleep, toilet, play, training", "🐶", [NUM("weeks", "Age in weeks", "12")],
    "A daily schedule for a {weeks}-week puppy: table (Time | Activity | Notes), a checklist of socialisation targets this week, and a callout on toilet-training timing.", "table, checklist, callout", "Plan", "Scheduling…"),
  T("enrich", "Enrichment ideas", "Tire the brain", "🧩", [CH("weather", "Today", ["Rainy", "Hot", "Normal"], "Normal")],
    "5 enrichment activities for the dog on a {weather} day: cards (activity, body = how, meta = minutes), and a callout on food-safety.", "cards, callout", "Ideas", "Thinking…")], "For medical symptoms or aggression that risks injury, consult a vet or qualified behaviourist.")

APP("cat_whisperer", "Cat Sense", "Understand and care for your cat", "Lifestyle", ["#5E35B1", "#FF7043", "#26A69A"], "paw",
 "Cat Sense decodes behaviour, plans enrichment and litter/feeding routines, and helps with introductions and stress.",
 "You are a feline behaviour specialist: calm, practical, respectful of cats being cats.",
 "Happy cat, happy home", "About your cat.", ["Behaviour decoding", "Enrichment & routines", "Introductions & moves"],
 [F("cat", "Cat's name, age, indoor/outdoor", "text", "Luna, 3, indoor", required=True), CH("issues", "Concerns", ["Scratching", "Litter issues", "Night zoomies", "Aggression", "Hiding", "Overeating"], multi=True)],
 [T("decode", "Why is my cat…", "Behaviour explained", "🐱", [TXT("behaviour", "Behaviour", "pees outside the litter box", True)],
    "Explain '{behaviour}': text (likely reasons ranked), bullets of what to change at home, steps for the next week, and a callout on vet red flags.", "text, bullets, steps, callout", "Decode", "Observing…"),
  T("enrich", "Enrichment plan", "Indoor cat, rich life", "🧶", [CH("budget", "Budget", ["Free", "Small", "Splurge"], "Small")],
    "An enrichment plan ({budget}): cards (activity/setup, body, meta = cost), a table (Time | Routine) for a daily rhythm, and a callout on play technique.", "cards, table, callout", "Plan", "Planning…"),
  T("intro", "Introduce a new pet", "Slow and safe", "🤝", [TXT("who", "Who's coming", "second cat, 1 year old", True)],
    "Introduction plan for {who}: table (Phase | Days | Steps | Move on when), a checklist of supplies, and a callout on signs to slow down.", "table, checklist, callout", "Plan", "Planning…"),
  T("vet", "Vet visit prep", "Questions and symptoms", "🩺", [TXT("reason", "Reason", "annual check, been sneezing", True)],
    "Prep for a vet visit about {reason}: bullets (symptom log to bring), bullets (questions to ask), and a callout on carrier-stress reduction.", "bullets, bullets, callout", "Prep", "Preparing…")], "Not a substitute for veterinary care.")

APP("garden_planner", "Garden Planner", "What to sow, plant and harvest this month", "House & Home", ["#33691E", "#FF8F00", "#0288D1"], "leaf",
 "Garden Planner builds sowing calendars for your climate, designs beds and balconies, and troubleshoots pests organically.",
 "You are a market-gardener mentor: seasonal, organic-first, honest about what won't grow in your conditions.",
 "Grow more of what you eat", "Your climate and space are everything.", ["Monthly sowing calendars", "Bed & balcony layouts", "Organic pest fixes"],
 [NAME, TXT("where", "Location / climate zone", "Manchester, UK", True), CH("space", "Space", ["Balcony pots", "Small bed", "Allotment", "Big garden"]), CH("sun", "Sun", ["Shade", "Part sun", "Full sun"])],
 [T("month", "This month", "Sow, plant, harvest", "📅", [TXT("month", "Month", "April", True)],
    "For {month} in the profile location: table (Crop | Sow/Plant/Harvest | Where | Notes), a checklist of jobs, and a callout on frost/heat risks.", "table, checklist, callout", "Plan month", "Checking…"),
  T("layout", "Design my space", "Layout for what you want to grow", "📐", [TXT("want", "I want to grow", "tomatoes, herbs, salad, strawberries", True), TXT("dims", "Dimensions", "2m × 1m bed")],
    "Design {dims} for {want} in the profile conditions: table (Position | Plant | Spacing | Companion), steps to set up, and a callout on watering.", "table, steps, callout", "Design", "Designing…"),
  T("pest", "Pest or disease?", "Photo → organic fix", "🐛", [PHOTO("Photo of the damage", "", True), TXT("plant", "Plant", "")],
    "Identify the pest/disease on {plant} from the photo: text (what it is, confidence), steps (organic control now), bullets (prevention), and a callout on when to remove the plant.", "text, steps, bullets, callout", "Identify", "Examining…"),
  T("seedling", "Seed to harvest", "One crop, full guide", "🌱", [TXT("crop", "Crop", "cherry tomatoes", True)],
    "Guide for {crop} in the profile conditions: table (Stage | When | What to do), kv (spacing, depth, days to harvest, common problems), and a quote with the one tip that matters most.", "table, kv, quote", "Guide", "Growing…")])

APP("event_host", "Host Mode", "Parties and dinners without the panic", "Lifestyle", ["#C62828", "#FFB300", "#00897B"], "gift",
 "Host Mode plans dinner parties, birthdays and gatherings: menus, timelines, shopping lists, playlists and the awkward-moment scripts.",
 "You are a relaxed, well-organised host: menus that can be made ahead, timelines that keep you out of the kitchen, warmth over perfection.",
 "Host like you've done it a hundred times", "Your kitchen and style.", ["Menus with make-ahead timelines", "Shopping lists", "Games, playlists & toasts"],
 [NAME, CH("cooking", "Cooking confidence", ["Nervous", "Okay", "Confident"]), CH("style", "Style", ["Casual", "Elegant", "Themed", "Kids"], multi=True)],
 [T("dinner", "Plan a dinner", "Menu + timeline", "🍽️", [NUM("guests", "Guests", "6"), TXT("diet", "Dietary needs", "one vegetarian, one nut allergy"), CH("effort", "Effort", ["Low", "Medium", "Show-off"], "Medium")],
    "Dinner for {guests} ({diet}, effort {effort}): cards (course, body = dish + make-ahead note, meta = prep time), table (Time | Task) from the day before to serving, and a checklist shopping list.", "cards, table, checklist", "Plan", "Planning…"),
  T("party", "Party planner", "Birthday, housewarming, anything", "🎉", [TXT("event", "Event", "40th birthday, 25 people, garden", True), NUM("budget", "Budget", "400")],
    "Plan {event} with {budget}: kv (theme, food format, drinks, music, timings), a checklist by week, and a callout on the one thing people forget.", "kv, checklist, callout", "Plan", "Planning…"),
  T("games", "Games & icebreakers", "For this crowd", "🎲", [TXT("crowd", "The crowd", "mixed friends who don't know each other, 8 people", True)],
    "5 games/icebreakers for: {crowd}. cards (game, body = rules, meta = minutes), and a callout on reading the room.", "cards, callout", "Suggest", "Thinking…"),
  T("toast", "Write a toast", "Short, warm, funny", "🥂", [TXT("for", "For whom / occasion", "my sister's wedding", True), TXT("stories", "Stories to include", "")],
    "A 90-second toast for {for} using: {stories}. quote (the toast), bullets on delivery, and a callout on what to cut if nervous.", "quote, bullets, callout", "Write", "Writing…")])

APP("gift_genius", "Gift Genius", "The right gift, every time", "Shopping", ["#AD1457", "#FFB300", "#00897B"], "gift",
 "Gift Genius finds thoughtful gifts for anyone from a few details, writes cards, and plans experiences instead of stuff.",
 "You are a thoughtful, culturally aware gift consultant: specific over generic, mindful of budget and relationship.",
 "Thoughtful, not last-minute", "A few defaults save time.", ["Gift ideas from details", "Card messages", "Experience planning"],
 [NAME, F("currency", "Currency", "text", "$", default="$"), TXT("people", "People you often buy for", "mum (gardening), Sam (coffee nerd)")],
 [T("ideas", "Gift ideas", "Person + budget → ideas", "🎁", [TXT("who", "Who", "my dad, 62, into cycling and history", True), NUM("budget", "Budget", "60"), CH("occasion", "Occasion", ["Birthday", "Anniversary", "Holiday", "Thank you", "Just because"], "Birthday")],
    "8 gift ideas for {who}, budget {budget}, {occasion}: cards (gift, body = why it fits + where to find, meta = price), a callout on what to avoid, and a quote with a card message.", "cards, callout, quote", "Find gifts", "Thinking…"),
  T("card", "Write the card", "Words that land", "💌", [TXT("who", "To", "", True), TXT("occasion", "Occasion", ""), CH("tone", "Tone", ["Heartfelt", "Funny", "Short", "Formal"], "Heartfelt")],
    "3 card messages to {who} for {occasion}, tone {tone}, as quote sections.", "quote, quote, quote", "Write", "Writing…"),
  T("experience", "Plan an experience", "Memories over objects", "🎈", [TXT("who", "Who", "", True), NUM("budget", "Budget", "150")],
    "3 experience gifts for {who} within {budget}: cards (experience, body = how to organise, meta = cost), steps to make it a surprise, and a callout on booking timing.", "cards, steps, callout", "Plan", "Planning…"),
  T("group", "Group gift", "Organise everyone", "👥", [TXT("who", "For", "", True), TXT("group", "Contributors", "6 colleagues")],
    "Organise a group gift for {who} from {group}: kv (gift, per-person amount, deadline), a quote with the message to the group, and a checklist for the organiser.", "kv, quote, checklist", "Organise", "Organising…")])

APP("wedding_wiz", "Wedding Wiz", "Plan the day without losing your mind", "Lifestyle", ["#8E24AA", "#F9A825", "#26A69A"], "ring",
 "Wedding Wiz builds timelines, budgets, vendor questions, seating plans and speeches, from proposal to last dance.",
 "You are a seasoned wedding planner: realistic budgets, calm timelines, diplomatic with families.",
 "Your day, your way, on budget", "Basics first.", ["Month-by-month timelines", "Budget allocation", "Vendor questions, speeches, seating"],
 [F("couple", "Names", "text", "Ana & Ben"), TXT("date", "Date", ""), NUM("guests", "Guests", "80"), NUM("budget", "Total budget", "20000"), F("currency", "Currency", "text", "$", default="$")],
 [T("timeline", "Planning timeline", "From now to the day", "📅", [],
    "Month-by-month timeline for the profile wedding: table (When | Task | Owner | Done?), a callout on the 3 things to book first, and a checklist for the final week.", "table, callout, checklist", "Build", "Planning…"),
  T("budget", "Allocate the budget", "Where the money goes", "💰", [CH("priority", "Top priority", ["Food", "Venue", "Photos", "Music", "Dress", "Guests' experience"], "Food")],
    "Allocate the profile budget with priority {priority}: table (Category | % | Amount | Save-tip), a callout on hidden costs, and bullets on where to cut without anyone noticing.", "table, callout, bullets", "Allocate", "Calculating…"),
  T("vendor", "Vendor questions", "Don't get burned", "📋", [CH("vendor", "Vendor", ["Venue", "Photographer", "Caterer", "DJ/Band", "Florist", "Planner"], "Photographer")],
    "Questions to ask a {vendor}: checklist grouped by topic, a callout on contract red flags, and kv (typical price range for the profile size).", "checklist, callout, kv", "List", "Listing…"),
  T("speech", "Write a speech", "Vows, best man, parent", "🎤", [CH("kind", "Kind", ["Vows", "Best man/maid", "Parent", "Couple's thank-you"], "Vows"), LONG("stories", "Stories & feelings", "", False)],
    "Write a {kind} speech from: {stories}. quote (the speech, 2-3 minutes), bullets on delivery, and a callout on what to cut.", "quote, bullets, callout", "Write", "Writing…")])
