from dsl import *

APP("math_mentor", "Math Mentor", "Step-by-step help that teaches, not tells", "Education", ["#1565C0", "#FF7043", "#43A047"], "graph",
 "Math Mentor solves problems step by step from a photo or text, explains the why, generates practice sets and spots your recurring mistakes.",
 "You are a patient maths tutor: Socratic when asked, always shows working, checks answers by substitution, flags common misconceptions.",
 "Understand it, don't just copy it", "Your level tunes the explanations.", ["Photo → worked solution", "Practice sets with answers", "Mistake analysis"],
 [NAME, CH("level", "Level", ["Primary", "Middle school", "High school", "University"]), TXT("topics", "Current topics", "quadratics, trig")],
 [T("solve", "Solve & explain", "Photo or typed problem", "🧮", [PHOTO("Photo of the problem"), TXT("problem", "Or type it", "solve x² − 5x + 6 = 0"), CH("mode", "Mode", ["Full solution", "Hints only", "Check my answer"], "Full solution")],
    "Problem: {problem} (or photo). Mode: {mode}. Steps (each with the rule used), a callout on the common trap here, kv (final answer, check by substitution), and bullets of 2 similar problems to try.", "steps, callout, kv, bullets", "Solve", "Working…"),
  T("practice", "Practice set", "10 questions, one topic", "📝", [TXT("topic", "Topic", "fractions with unlike denominators", True), CH("difficulty", "Difficulty", ["Easy", "Mixed", "Hard"], "Mixed")],
    "A 10-question {difficulty} practice set on {topic} for the profile level: table (No. | Question | Answer), then steps for the hardest one, and a callout on the skill being drilled.", "table, steps, callout", "Generate", "Writing…"),
  T("explain", "Explain a concept", "Like I'm curious, not stupid", "💡", [TXT("concept", "Concept", "why does dividing by a fraction flip it?", True)],
    "Explain '{concept}' at the profile level: text (intuition with a concrete example), steps (the formal reasoning), a quote (one-line memory hook), and bullets (where students go wrong).", "text, steps, quote, bullets", "Explain", "Thinking…"),
  T("mistakes", "Analyse my mistakes", "Paste wrong answers", "🔍", [LONG("work", "Your work / wrong answers", "")],
    "Analyse: {work}. Table (Error | Type | Correct approach), a callout on the one habit to fix, and bullets of targeted drills.", "table, callout, bullets", "Analyse", "Reviewing…")])

APP("essay_coach", "Essay Coach", "Outlines, feedback and thesis polish", "Education", ["#6A1B9A", "#FFB300", "#00897B"], "note",
 "Essay Coach turns prompts into outlines, gives rubric-based feedback on drafts, sharpens thesis statements and fixes citations — without writing it for you.",
 "You are a writing tutor who improves the student's own work: rubric-based, honest, never ghostwrites whole essays.",
 "Write it better, in your voice", "Level and citation style.", ["Outlines from prompts", "Rubric-based feedback", "Thesis & citation help"],
 [NAME, CH("level", "Level", ["High school", "Undergraduate", "Postgraduate"]), CH("style", "Citation style", ["APA", "MLA", "Chicago", "Harvard", "None"])],
 [T("outline", "Outline from a prompt", "Structure before words", "🗂️", [LONG("prompt", "Essay prompt", ""), NUM("words", "Word count", "1500")],
    "Outline for the prompt ({words} words): kv (working thesis, angle, counter-argument), table (Section | Purpose | Key points | Words), and a callout on the strongest possible argument.", "kv, table, callout", "Outline", "Structuring…"),
  T("feedback", "Feedback on my draft", "Paste a draft", "📝", [LONG("draft", "Draft", "")],
    "Give feedback on: {draft}. Table (Criterion | Score/5 | Comment) for argument, evidence, structure, style, mechanics; bullets of the 3 highest-impact fixes; a quote showing one paragraph rewritten as an example (clearly labelled as an example, not a replacement).", "table, bullets, quote", "Review", "Reading…"),
  T("thesis", "Sharpen my thesis", "From vague to arguable", "🎯", [TXT("thesis", "Current thesis", "", True)],
    "Sharpen '{thesis}': bullets (what's weak), cards (3 stronger versions, meta = angle), and a callout on the evidence each would need.", "bullets, cards, callout", "Sharpen", "Sharpening…"),
  T("cite", "Fix citations", "Format references", "📚", [LONG("sources", "Sources (any format)", "")],
    "Format in the profile style: bullets (each reference correctly formatted), a callout on in-text format, and a table (Source | Missing info).", "bullets, callout, table", "Format", "Formatting…")])

APP("science_lab", "Science Explainer", "Any science question, explained at your level", "Education", ["#00838F", "#FF7043", "#7E57C2"], "bulb",
 "Science Explainer answers physics, chemistry and biology questions with intuition first, then rigour, plus experiments you can do at home and exam-style practice.",
 "You are an enthusiastic science teacher: analogies, then equations; accuracy over hype; safety-first for experiments.",
 "Curiosity, satisfied", "Your level sets the depth.", ["Explanations at your level", "Home experiments", "Exam practice"],
 [NAME, CH("level", "Level", ["Kid", "Teen", "Adult curious", "Student"]), CH("subjects", "Interests", ["Physics", "Chemistry", "Biology", "Earth & space"], multi=True)],
 [T("explain", "Explain", "Any question", "🔬", [TXT("q", "Question", "why is the sky blue but sunsets red?", True)],
    "Answer '{q}' at the profile level: text (intuitive explanation), steps (the mechanism), kv (key terms), and bullets (2 follow-up questions to explore).", "text, steps, kv, bullets", "Explain", "Thinking…"),
  T("experiment", "Home experiment", "Safe, cheap, wow", "🧪", [TXT("topic", "Topic", "density", True)],
    "A home experiment on {topic} for the profile level: checklist (materials), steps, a callout on safety, text (what you'll see and why).", "checklist, steps, callout, text", "Design", "Designing…"),
  T("quiz", "Quiz me", "10 questions", "❓", [TXT("topic", "Topic", "cell biology", True)],
    "10 questions on {topic} for the profile level as a table (No. | Question | Answer | Why), and a callout on the concept most people get wrong.", "table, callout", "Quiz", "Writing…"),
  T("diagram", "Explain this diagram", "Photo of a textbook figure", "📷", [PHOTO("Photo of the diagram", "", True)],
    "Explain the diagram: text (what it shows), kv (labelled parts → meaning), steps (the process it depicts), and a callout on exam phrasing.", "text, kv, steps, callout", "Explain", "Reading…")])

APP("code_tutor", "Code Tutor", "Learn to code with a patient mentor", "Education", ["#37474F", "#00E676", "#2979FF"], "gear",
 "Code Tutor explains concepts, reviews your code, debugs errors from screenshots and sets daily practice — in Python, JavaScript, Kotlin and more.",
 "You are a senior engineer who mentors juniors: explains why, prefers small examples, never just pastes solutions without teaching.",
 "Ship your first real program", "Language and goal.", ["Concept explanations", "Code review & debugging", "Daily practice"],
 [NAME, CH("lang", "Language", ["Python", "JavaScript", "Kotlin", "Java", "Swift", "Go", "SQL"]), CH("level", "Level", ["Beginner", "Intermediate", "Advanced"]), TXT("goal", "Goal", "build a web app")],
 [T("explain", "Explain a concept", "With a tiny example", "💡", [TXT("concept", "Concept", "closures", True)],
    "Explain {concept} in the profile language/level: text (intuition), quote (a minimal code example), bullets (pitfalls), and steps (an exercise to try).", "text, quote, bullets, steps", "Explain", "Thinking…"),
  T("debug", "Debug this", "Paste code or a screenshot", "🐞", [PHOTO("Screenshot of error (optional)"), LONG("code", "Code / error", "", False)],
    "Debug: {code} (or screenshot). text (what's wrong and why), quote (fixed code), steps (how to find this class of bug next time), and a callout on the concept to review.", "text, quote, steps, callout", "Debug", "Reading…"),
  T("review", "Review my code", "Honest, kind, specific", "🔍", [LONG("code", "Code", "")],
    "Review: {code}. Table (Line/area | Issue | Fix | Severity), bullets (what's good), and a quote with the top refactor.", "table, bullets, quote", "Review", "Reviewing…"),
  T("daily", "Daily challenge", "15 minutes", "📅", [TXT("focus", "Focus", "loops and lists")],
    "A 15-minute challenge on {focus} for the profile: text (problem), bullets (hints, hidden until needed), quote (reference solution), and a callout on extension.", "text, bullets, quote, callout", "Challenge", "Writing…")])

APP("kids_tutor", "Homework Helper", "Help your child without doing it for them", "Education", ["#FF7043", "#4DB6AC", "#FFB300"], "book",
 "Homework Helper explains school topics to parents and kids, turns worksheets into guided practice, and builds games for spelling and times tables.",
 "You are a warm primary/middle-school teacher: guides with questions, celebrates effort, never gives the answer before the child tries.",
 "Homework without tears", "About your child.", ["Photo of homework → guided help", "Spelling & tables games", "Reading comprehension"],
 [F("child", "Child's name & age", "text", "Aarav, 9", required=True), CH("subjects", "Subjects", ["Maths", "Reading", "Spelling", "Science", "Writing"], multi=True)],
 [T("help", "Help with this", "Photo of the homework", "📷", [PHOTO("Photo of the worksheet", "", True)],
    "For the worksheet: text (what the task is really practising), steps for the parent to guide with questions (not answers), a quote with a sentence to say if the child gets stuck, and a callout on how to check answers.", "text, steps, quote, callout", "Help", "Reading…"),
  T("spelling", "Spelling game", "This week's list", "🔤", [LONG("words", "Word list", "because, friend, thought, laugh", False)],
    "Games for the words: {words}. cards (game, body = how to play, meta = minutes), table (Word | Trick to remember), and a quote with a silly sentence using all words.", "cards, table, quote", "Make games", "Inventing…"),
  T("tables", "Times tables", "Practice that sticks", "✖️", [CH("table", "Table", ["2", "3", "4", "5", "6", "7", "8", "9", "12"], "7")],
    "Practice for the {table} times table: table (Question | Answer), bullets (patterns/tricks), steps for a 5-minute daily routine, and a quote with a rhyme.", "table, bullets, steps, quote", "Practise", "Building…"),
  T("reading", "Reading questions", "Comprehension for any text", "📖", [LONG("text", "Paste the passage", "")],
    "For the passage: bullets (5 questions: literal → inferential → opinion), kv (new vocabulary → kid-friendly meaning), and a callout on discussion prompts.", "bullets, kv, callout", "Questions", "Reading…")])

APP("lingo_flash", "Phrasebook Pro", "Say it right in any language, right now", "Education", ["#1565C0", "#FF7043", "#26A69A"], "globe",
 "Phrasebook Pro gives situation-ready phrases with pronunciation, translates menus and signs from photos, and drills you on what you'll actually say.",
 "You are a multilingual guide: natural phrasing, simple pronunciation guides, cultural etiquette notes.",
 "Speak before you land", "Your languages.", ["Situational phrases with pronunciation", "Photo translation", "Quick drills"],
 [NAME, TXT("native", "I speak", "English", True), TXT("target", "I'm learning / visiting", "Japanese", True)],
 [T("situation", "Phrases for…", "Any situation", "💬", [TXT("situation", "Situation", "ordering at a ramen shop", True)],
    "Phrases in {target} for '{situation}': table (Phrase | Pronunciation | Meaning), a callout on etiquette, and a quote with the single most useful sentence.", "table, callout, quote", "Get phrases", "Translating…"),
  T("photo", "Translate a photo", "Menu, sign, label", "📷", [PHOTO("Photo of text", "", True)],
    "Translate the text in the photo to {native}: table (Original | Translation | Note), and a callout on anything important (allergens, warnings, prices).", "table, callout", "Translate", "Reading…"),
  T("drill", "Drill me", "10 quick-fire cards", "⚡", [TXT("topic", "Topic", "numbers and prices")],
    "10 flashcards in {target} on {topic}: table (Prompt in {native} | Answer | Pronunciation), and bullets of a memory trick for the hardest two.", "table, bullets", "Drill", "Shuffling…"),
  T("fix", "Fix my sentence", "Say it naturally", "✏️", [TXT("sentence", "Your attempt", "", True)],
    "Correct '{sentence}' in {target}: quote (natural version), kv (what changed → why), and bullets (2 alternatives by formality).", "quote, kv, bullets", "Fix", "Checking…")])

APP("public_speaker", "Stage Ready", "Speeches, pitches and presentations that land", "Business", ["#C62828", "#FFB300", "#37474F"], "mic",
 "Stage Ready structures talks, writes openings and closings, builds slide outlines, and rehearses you with tough questions.",
 "You are a speaking coach: story-first structure, concrete openings, ruthless about cutting; supportive about nerves.",
 "Own the room", "Your context.", ["Talk structures", "Openings & closings", "Q&A rehearsal"],
 [NAME, CH("context", "Usually speaking at", ["Work meetings", "Conferences", "Pitches", "Weddings/events", "Classes"], multi=True), CH("nerves", "Nerves", ["Low", "Medium", "High"])],
 [T("structure", "Structure my talk", "Message → outline", "🏗️", [TXT("topic", "Topic & audience", "quarterly results to the exec team", True), NUM("minutes", "Minutes", "10")],
    "Structure a {minutes}-minute talk on {topic}: kv (one-sentence message, audience takeaway), table (Section | Minutes | Content | Slide), quote (opening line), quote (closing line).", "kv, table, quote, quote", "Structure", "Structuring…"),
  T("slides", "Slide outline", "Titles that make the point", "🖥️", [LONG("content", "Content / notes", "")],
    "Slide outline from: {content}. table (Slide | Headline (a sentence, not a topic) | Visual | Speaker note), and a callout on the slide to cut.", "table, callout", "Outline", "Designing…"),
  T("qa", "Rehearse Q&A", "Tough questions", "❓", [TXT("topic", "Topic", "", True)],
    "10 tough questions on {topic}: cards (question, body = a strong answer outline, meta = type: hostile/technical/curious), and a callout on bridging phrases.", "cards, callout", "Rehearse", "Preparing…"),
  T("nerves", "Calm my nerves", "Before you go on", "🫁", [NUM("minutes", "Minutes until you speak", "15")],
    "A {minutes}-minute pre-talk routine for the profile nerves level: steps with timings, a quote with a self-talk line, and bullets of what to do if you blank.", "steps, quote, bullets", "Calm me", "Breathing…")])

APP("book_club", "Book Companion", "Read deeper, remember more, discuss better", "Books & Reference", ["#5D4037", "#FFB300", "#00897B"], "book",
 "Book Companion builds discussion questions, summarises chapters without spoilers ahead, explains references, and recommends your next read.",
 "You are a well-read, spoiler-careful literary companion: insightful, never pretentious.",
 "Get more from every book", "What you're reading.", ["Spoiler-safe chapter recaps", "Discussion questions", "Next-read recommendations"],
 [NAME, TXT("reading", "Currently reading", "", False), CH("likes", "You like", ["Literary", "Thrillers", "Sci-fi/Fantasy", "Non-fiction", "Romance", "History", "Memoir"], multi=True)],
 [T("recap", "Recap so far", "Spoiler-safe", "📖", [TXT("book", "Book", "", True), TXT("upto", "I'm at", "chapter 12")],
    "Recap {book} up to {upto} with NO spoilers beyond: bullets (what's happened), kv (characters → who they are), a callout on themes emerging, and bullets (questions to keep in mind).", "bullets, kv, callout, bullets", "Recap", "Recalling…"),
  T("discuss", "Discussion questions", "For a club or yourself", "💬", [TXT("book", "Book", "", True)],
    "12 discussion questions for {book}: bullets (plot & character), bullets (themes & craft), bullets (personal connection), and a quote with a provocative opening question.", "bullets, bullets, bullets, quote", "Generate", "Thinking…"),
  T("explain", "Explain a reference", "Allusions, history, words", "🔎", [TXT("ref", "Reference / passage", "", True)],
    "Explain '{ref}': text (meaning and context), kv (origin, why the author used it), and bullets of related things worth knowing.", "text, kv, bullets", "Explain", "Looking up…"),
  T("next", "What next?", "Recommendations", "📚", [TXT("loved", "Books you loved", "", True), TXT("mood", "Mood", "something lighter")],
    "Recommend 6 books for someone who loved {loved} wanting {mood}: cards (title & author, body = why, meta = vibe/length), and a callout on the wildcard pick.", "cards, callout", "Recommend", "Browsing…")])

APP("history_time", "Time Machine", "History explained like a great documentary", "Education", ["#795548", "#FFB300", "#00838F"], "clock",
 "Time Machine explains any period, event or person with context, timelines, primary-source flavour and 'what if' debates.",
 "You are an engaging historian: balanced, source-aware, distinguishes fact from interpretation, vivid but accurate.",
 "Understand the past, properly", "Your interests.", ["Timelines & context", "People & places", "Debate prompts"],
 [NAME, CH("level", "Depth", ["Curious", "Student", "Deep dive"]), CH("eras", "Interests", ["Ancient", "Medieval", "Early modern", "Modern", "20th century"], multi=True)],
 [T("event", "Explain an event", "Causes, course, consequences", "🏛️", [TXT("event", "Event or period", "the fall of Constantinople", True)],
    "Explain {event} at the profile depth: text (why it matters), table (Date | What happened), bullets (causes), bullets (consequences), and a callout on historiographical debate.", "text, table, bullets, bullets, callout", "Explain", "Researching…"),
  T("person", "A life in brief", "Any historical figure", "👤", [TXT("who", "Who", "", True)],
    "Profile {who}: kv (born/died, role, known for, contemporaries), steps (life in 6 turning points), a quote (an attributed or characteristic saying, flagged if disputed), and a callout on myths vs evidence.", "kv, steps, quote, callout", "Profile", "Reading…"),
  T("compare", "Compare", "Two things side by side", "⚖️", [TXT("a", "A", "Roman Republic", True), TXT("b", "B", "Athenian democracy", True)],
    "Compare {a} and {b}: table (Aspect | A | B), bullets (surprising similarities), and a callout on the lazy comparison to avoid.", "table, bullets, callout", "Compare", "Comparing…"),
  T("debate", "Debate a 'what if'", "Counterfactual, carefully", "🤔", [TXT("q", "What if…", "what if the Library of Alexandria hadn't burned?", True)],
    "Explore '{q}': text (what we actually know), bullets (plausible consequences with confidence), bullets (why historians are cautious), and a quote with a discussion prompt.", "text, bullets, bullets, quote", "Explore", "Speculating…")])

APP("career_pivot", "Pivot Path", "Change careers with a plan, not a leap", "Business", ["#00695C", "#FF8F00", "#5E35B1"], "graph",
 "Pivot Path maps your transferable skills to new roles, builds 90-day transition plans, writes your new narrative and finds the gaps to close.",
 "You are a career strategist who has seen hundreds of pivots: honest about gaps, creative about bridges, practical about money.",
 "Your next chapter, planned", "Where you are and where you're curious.", ["Skills mapping", "90-day transition plans", "Story & networking scripts"],
 [NAME, LONG("current", "Current role & experience", "", False), TXT("toward", "Curious about", "product management, UX"), CH("runway", "Financial runway", ["None", "3 months", "6+ months"])],
 [T("map", "Map my options", "Where your skills transfer", "🗺️", [],
    "From the profile: table (Target role | Transferable skills | Gaps | Fit /5), cards (3 bridge roles, meta = time to reach), and a callout on the most realistic first step.", "table, cards, callout", "Map", "Mapping…"),
  T("plan", "90-day plan", "Toward one role", "📅", [TXT("role", "Target role", "", True)],
    "A 90-day plan toward {role}: table (Week | Learn | Build | Connect), a checklist of proof-of-work artefacts, and a callout on how to know if it's not working.", "table, checklist, callout", "Plan", "Planning…"),
  T("story", "My pivot story", "For LinkedIn and interviews", "🧵", [TXT("role", "Target role", "", True)],
    "Write the pivot narrative toward {role}: quote (LinkedIn About, 120 words), quote (30-second interview answer 'why the change'), and bullets on evidence to back each claim.", "quote, quote, bullets", "Write", "Writing…"),
  T("outreach", "Networking messages", "Coffee-chat asks that get replies", "☕", [TXT("who", "Who", "a PM at a fintech I admire", True)],
    "Outreach to {who}: quote (LinkedIn message, 60 words), quote (follow-up after a week), bullets (questions to ask on the call), and a callout on the ask to avoid.", "quote, quote, bullets, callout", "Draft", "Drafting…")])
