from dsl import *
MED = "General information, not medical advice; consult a clinician for diagnosis or urgent concerns."

APP("city_break", "City Break", "48 hours in any city, done right", "Travel & Local", ["#0277BD", "#FF8F00", "#2E7D32"], "pin",
 "City Break plans weekend itineraries grouped by neighbourhood, finds food worth the walk, and handles logistics from the airport to the last train.",
 "You are a seasoned travel editor: neighbourhood-first planning, honest about tourist traps, precise about logistics; you flag when facts may have changed.",
 "Weekend, planned", "Your travel style.", ["Neighbourhood-grouped days", "Food & coffee picks", "Transport & safety notes"],
 [NAME, CH("style", "Style", ["Food-first", "Museums", "Walking", "Nightlife", "Chill", "Kids"], multi=True), CH("budget", "Budget", ["Shoestring", "Mid", "Splurge"])],
 [T("plan", "Plan 48 hours", "City + dates", "🗺️", [TXT("city", "City", "Porto", True), TXT("when", "When", "next weekend, arriving Fri 6pm")],
    "48-hour plan for {city}, {when}, for the profile style/budget: table (Day/Time | Activity | Area | Note), cards (3 places to eat, meta = meal & price tier), and a callout on logistics (airport → centre, transport pass, safety).", "table, cards, callout", "Plan", "Planning…"),
  T("food", "Where to eat", "Real, not touristy", "🍽️", [TXT("city", "City / area", "", True), TXT("craving", "Craving", "local, cheap, seafood")],
    "Food picks in {city} for '{craving}': cards (type of place/dish and where to look, meta = price tier), bullets on ordering etiquette, and a callout on tourist traps to skip.", "cards, bullets, callout", "Find", "Searching…"),
  T("rainy", "Rainy-day plan", "Indoors, still great", "🌧️", [TXT("city", "City", "", True)],
    "A rainy day in {city}: steps (a route of indoor stops), cards (3 options, meta = cost), and a callout on booking ahead.", "steps, cards, callout", "Plan", "Planning…"),
  T("phrases", "Local basics", "Phrases, tipping, customs", "🗣️", [TXT("city", "City / country", "", True)],
    "Local basics for {city}: table (Phrase | Pronunciation | Meaning), kv (tipping, plugs, water, cards vs cash, emergency number), and bullets on etiquette.", "table, kv, bullets", "Brief me", "Compiling…")], "Verify opening hours, prices and safety advice locally before relying on them.")

APP("road_trip", "Road Trip Radio", "Routes, stops and playlists for the open road", "Travel & Local", ["#EF6C00", "#0288D1", "#43A047"], "car",
 "Road Trip Radio plans multi-day drives with sensible daily distances, worthwhile stops, budgets and packing — plus games and playlist themes.",
 "You are a road-trip veteran: realistic driving hours, scenic-over-fast when it's worth it, safety and fatigue aware.",
 "Miles of fun", "Your vehicle and crew.", ["Day-by-day routes", "Stops worth the detour", "Budget, packing, games"],
 [NAME, CH("vehicle", "Vehicle", ["Car", "Campervan", "Motorbike", "EV"]), TXT("crew", "Who's coming", "2 adults, 1 kid, a dog"), CH("hours", "Max driving/day", ["3", "5", "7"])],
 [T("route", "Plan the route", "From A to B with stops", "🛣️", [TXT("from", "From", "", True), TXT("to", "To", "", True), NUM("days", "Days", "5"), TXT("interests", "Interests", "nature, small towns, food")],
    "Plan {from} → {to} over {days} days for the profile crew, interests {interests}: table (Day | Drive | Stops | Overnight area), cards (3 detours worth it, meta = extra minutes), and a callout on fatigue/charging/fuel planning.", "table, cards, callout", "Plan route", "Routing…"),
  T("budget", "Budget the trip", "Fuel, stays, food", "💰", [TXT("trip", "Trip summary", "1200 km, 5 days, 2 people", True)],
    "Budget for {trip}: table (Category | Estimate | Assumption), bullets on saving, and a callout on the usual surprise costs.", "table, bullets, callout", "Estimate", "Calculating…"),
  T("pack", "Packing & car prep", "Nothing forgotten", "🎒", [CH("season", "Season", ["Summer", "Winter", "Shoulder"], "Summer")],
    "Checklist (car prep), checklist (packing for the crew, {season}), and a callout on the emergency kit.", "checklist, checklist, callout", "Checklist", "Listing…"),
  T("fun", "Games & playlist", "Keep everyone happy", "🎶", [TXT("vibe", "Vibe", "90s nostalgia, kid-friendly")],
    "cards (5 car games, body = rules, meta = ages), bullets (playlist themes and 10 seed songs for '{vibe}'), and a callout on screen-free stretches.", "cards, bullets, callout", "Entertain", "Curating…")])

APP("baby_days", "Baby Days", "The first year, one calm answer at a time", "Parenting", ["#F06292", "#4DB6AC", "#FFB74D"], "baby",
 "Baby Days answers new-parent questions with evidence-based, non-judgemental guidance: sleep, feeding, milestones, weaning and what to ask the doctor.",
 "You are a reassuring paediatric nurse-educator: evidence-based, culturally sensitive, clear about red flags, never shaming feeding choices.",
 "You're doing better than you think", "About your baby.", ["Age-specific guidance", "Sleep & feeding plans", "Red-flag checker"],
 [F("baby", "Baby's name & age", "text", "Zara, 5 months", required=True), CH("feeding", "Feeding", ["Breast", "Formula", "Mixed", "Weaning"]), TXT("concerns", "Current concerns", "")],
 [T("ask", "Ask anything", "Sleep, feeding, crying…", "💬", [TXT("q", "Question", "how do I start weaning?", True)],
    "Answer '{q}' for the profile baby: text (evidence-based answer), steps (what to do), bullets (what's normal), and a callout on red flags that need a doctor.", "text, steps, bullets, callout", "Ask", "Thinking…"),
  T("sleep", "Sleep plan", "Gentle, age-appropriate", "🌙", [TXT("now", "Current pattern", "wakes every 2h, feeds to sleep")],
    "A gentle sleep plan for the baby's age given: {now}. table (Time | Routine), steps for the first 3 nights, and a callout on safe-sleep rules and what not to expect.", "table, steps, callout", "Plan", "Planning…"),
  T("milestones", "Milestones", "What to expect this month", "📈", [],
    "Milestones for the baby's age: table (Area | Typical | Encourage with), bullets (play ideas), and a callout on when to raise a concern.", "table, bullets, callout", "Show", "Looking up…"),
  T("doctor", "Doctor visit prep", "Questions and symptom log", "🩺", [TXT("reason", "Reason", "check-up, rash on cheeks", True)],
    "Prep for a visit about {reason}: bullets (symptom details to note), bullets (questions to ask), and a callout on what to bring.", "bullets, bullets, callout", "Prep", "Preparing…")], MED)

APP("teen_talk", "Teen Talk", "Scripts for the hard conversations with your teenager", "Parenting", ["#5E35B1", "#FF7043", "#26A69A"], "chat",
 "Teen Talk helps parents open conversations about screens, school, friends, mental health and risk — with scripts, boundaries and what not to say.",
 "You are a family therapist and parent coach: connection before correction, developmental-stage aware, practical scripts.",
 "Talk so they'll listen", "About your teen.", ["Conversation scripts", "Boundary agreements", "De-escalation"],
 [F("teen", "Teen's age", "number", "15"), CH("topics", "Topics", ["Screens", "School", "Friends", "Mood", "Risk", "Independence", "Sleep"], multi=True)],
 [T("script", "Start a conversation", "Topic → opener + flow", "💬", [TXT("topic", "Topic", "I found vapes in their bag", True)],
    "Script for '{topic}' with a teen of the profile age: quote (opener), steps (the flow, including listening turns), bullets (what NOT to say), and a callout on when to pause.", "quote, steps, bullets, callout", "Script", "Thinking…"),
  T("agreement", "Family agreement", "Screens, curfews, chores", "📝", [TXT("about", "About", "phone use on school nights", True)],
    "A collaborative agreement about {about}: table (Expectation | Why | What happens if not), steps to negotiate it together, and a quote with the framing sentence to open.", "table, steps, quote", "Draft", "Drafting…"),
  T("deescalate", "It's escalating", "Right now", "🔥", [TXT("what", "What's happening", "shouting, door slammed", True)],
    "De-escalate: {what}. steps (next 10 minutes), quote (one sentence to say), bullets (repair later), and a callout on safety.", "steps, quote, bullets, callout", "Help", "Breathing…"),
  T("worry", "Should I worry?", "Mood, behaviour changes", "🧠", [LONG("signs", "What you've noticed", "")],
    "Assess: {signs}. text (normal development vs concern), bullets (supportive actions), and a callout with red flags and how to get professional help.", "text, bullets, callout", "Assess", "Considering…")], MED)

APP("mind_ease", "Mind Ease", "Tools for anxious moments and heavy days", "Health & Fitness", ["#3949AB", "#26A69A", "#FFB300"], "brain",
 "Mind Ease offers CBT-style thought records, grounding exercises, worry scheduling and self-compassion practices — private, on your phone.",
 "You are a CBT-informed wellbeing coach: warm, structured, non-diagnostic; you always surface crisis resources when risk appears.",
 "A calmer mind, one tool at a time", "What tends to help you?", ["Thought records", "Grounding in 3 minutes", "Worry & sleep tools"],
 [NAME, CH("helps", "What helps you", ["Structure", "Movement", "Talking", "Writing", "Breathing"], multi=True), CH("focus", "Working on", ["Anxiety", "Low mood", "Stress", "Overthinking", "Sleep"], multi=True)],
 [T("thought", "Thought record", "Challenge a thought", "🧾", [LONG("thought", "The thought / situation", "I'll mess up the presentation and everyone will think I'm useless")],
    "CBT thought record for: {thought}. kv (situation, emotion & intensity, automatic thought, distortion type), bullets (evidence for), bullets (evidence against), quote (balanced thought), and a callout on re-rating the emotion.", "kv, bullets, bullets, quote, callout", "Work through it", "Listening…"),
  T("ground", "Ground me now", "3 minutes", "🌿", [CH("state", "Right now I feel", ["Panicky", "Numb", "Angry", "Overwhelmed", "Can't sleep"], "Overwhelmed")],
    "A 3-minute grounding practice for feeling {state}: steps with timings, a quote with a phrase to repeat, and a callout with crisis resources if things feel unsafe.", "steps, quote, callout", "Start", "Here with you…"),
  T("worry", "Worry time", "Sort worries", "🗂️", [LONG("worries", "Everything on your mind", "")],
    "Sort: {worries}. table (Worry | Solvable? | Next tiny action or 'let go'), a callout on scheduling worry time, and a quote for closing the list.", "table, callout, quote", "Sort", "Sorting…"),
  T("compassion", "Self-compassion", "Talk to yourself like a friend", "💛", [TXT("situation", "What happened", "", True)],
    "For: {situation}. quote (what a kind friend would say), steps (a 5-minute self-compassion break), and bullets (common self-criticism traps).", "quote, steps, bullets", "Begin", "Softening…")], "Not therapy or crisis support. If you are in danger or thinking of harming yourself, contact local emergency services or a crisis line now.")

APP("dream_journal", "Dream Decoder", "Record dreams, notice patterns, sleep curious", "Lifestyle", ["#4527A0", "#FFB300", "#26C6DA"], "moon",
 "Dream Decoder helps you capture dreams fast, explores possible meanings from several traditions without claiming certainty, and tracks recurring themes.",
 "You are a curious, grounded dream companion: you offer perspectives (psychological, cultural, symbolic) as possibilities, never predictions.",
 "What was that about?", "A little context.", ["Fast capture prompts", "Multi-perspective interpretations", "Pattern tracking"],
 [NAME, CH("lens", "Preferred lens", ["Psychological", "Symbolic", "Cultural/mythic", "Just curious"], multi=True)],
 [T("decode", "Decode a dream", "Tell it as you remember", "🌙", [LONG("dream", "The dream", "")],
    "Explore: {dream}. kv (setting, characters, emotion, standout symbol), cards (3 interpretations from the profile lenses, meta = lens), bullets (questions to reflect on), and a callout that these are possibilities not facts.", "kv, cards, bullets, callout", "Decode", "Wondering…"),
  T("capture", "Capture prompts", "Before it fades", "✍️", [],
    "A 2-minute capture routine: steps (questions to answer in order), and a quote with a template sentence.", "steps, quote", "Show", "Ready…"),
  T("patterns", "Find patterns", "Paste several dreams", "🔁", [LONG("dreams", "Several dreams", "")],
    "Patterns across: {dreams}. table (Theme | Appears in | Possible link to waking life), and a callout on what to try (e.g. sleep, stress).", "table, callout", "Analyse", "Reading…"),
  T("lucid", "Lucid dreaming", "Beginner's plan", "✨", [],
    "A 2-week lucid-dreaming starter: table (Day | Practice | Minutes), bullets (reality checks), and a callout on sleep hygiene and who should skip it.", "table, bullets, callout", "Plan", "Planning…")])

APP("songwriter", "Song Forge", "Lyrics, chords and structure for your next song", "Music & Audio", ["#AD1457", "#FFB300", "#00838F"], "music",
 "Song Forge co-writes lyrics in your voice, suggests chord progressions and structures, and gives honest feedback on drafts.",
 "You are a working songwriter and producer: specific imagery over clichés, prosody-aware, genre-fluent; you improve the writer's own lines.",
 "Finish the song", "Your sound.", ["Lyrics & rhyme help", "Chords & structure", "Draft feedback"],
 [NAME, CH("genre", "Genres", ["Pop", "Indie", "Hip-hop", "R&B", "Country", "Rock", "Folk", "Electronic"], multi=True), CH("instrument", "You play", ["Guitar", "Piano", "Neither", "Producer"]), TXT("influences", "Influences", "")],
 [T("lyrics", "Write with me", "Theme → verse/chorus", "🎤", [TXT("theme", "Theme / story", "leaving a small town", True), CH("mood", "Mood", ["Hopeful", "Bittersweet", "Angry", "Euphoric", "Lonely"], "Bittersweet")],
    "Co-write on '{theme}', mood {mood}, in the profile genre: quote (verse 1), quote (chorus), bullets (3 alternative hooks), and a callout on imagery to avoid.", "quote, quote, bullets, callout", "Write", "Humming…"),
  T("chords", "Chords & structure", "For this song", "🎸", [TXT("key", "Key / vibe", "C major, driving", True)],
    "For {key} in the profile genre: table (Section | Chords | Bars | Notes), bullets (2 alternative progressions), and a callout on where to modulate or drop out.", "table, bullets, callout", "Suggest", "Voicing…"),
  T("feedback", "Feedback on lyrics", "Paste a draft", "📝", [LONG("draft", "Lyrics", "")],
    "Feedback on: {draft}. table (Line | Issue | Stronger option), bullets (what's working), and a quote with the single line that should be the hook.", "table, bullets, quote", "Review", "Listening…"),
  T("title", "Titles & concepts", "Get unstuck", "💡", [TXT("seed", "Seed idea", "")],
    "10 song concepts from '{seed}': cards (title, body = concept & POV, meta = genre), and a callout on the freshest one.", "cards, callout", "Brainstorm", "Riffing…")])

APP("novel_ist", "Plot Smith", "Outline, characters and scenes for your novel", "Books & Reference", ["#37474F", "#FF8F00", "#8E24AA"], "book",
 "Plot Smith helps novelists plan: beat-sheet outlines, character bibles, scene cards, and feedback on chapters — always in service of your book.",
 "You are a developmental editor: story structure, character motivation, stakes; you never replace the author's voice.",
 "Write the book you keep thinking about", "Your project.", ["Beat-sheet outlines", "Character bibles", "Chapter feedback"],
 [NAME, TXT("project", "Working title & premise", "", False), CH("genre", "Genre", ["Literary", "Fantasy", "Sci-fi", "Romance", "Thriller", "Mystery", "YA", "Horror"]), CH("stage", "Stage", ["Idea", "Outlining", "Drafting", "Revising"])],
 [T("outline", "Beat sheet", "Premise → structure", "🗂️", [LONG("premise", "Premise", "", False)],
    "Beat sheet for the profile project ({premise}): table (Beat | What happens | % of book), a callout on the midpoint reversal, and bullets of 3 possible endings.", "table, callout, bullets", "Outline", "Plotting…"),
  T("character", "Character bible", "Make them real", "👤", [TXT("who", "Character", "the antagonist, a retired judge", True)],
    "Bible for {who}: kv (want, need, wound, lie they believe, contradiction), bullets (voice & mannerisms), steps (their arc across the book), and a quote (a line only they would say).", "kv, bullets, steps, quote", "Build", "Imagining…"),
  T("scene", "Plan a scene", "Purpose, conflict, turn", "🎬", [TXT("scene", "Scene", "the confrontation at the pier", True)],
    "Scene plan for {scene}: kv (goal, conflict, turn, exit emotion), steps (beats), and a callout on subtext.", "kv, steps, callout", "Plan", "Blocking…"),
  T("feedback", "Chapter feedback", "Paste a chapter", "📝", [LONG("chapter", "Chapter", "")],
    "Developmental feedback on: {chapter}. table (Aspect | Works | Needs), bullets (line-level habits to watch), and a quote showing one sentence tightened as an example.", "table, bullets, quote", "Review", "Reading…")])

APP("social_caption", "Caption Craft", "Captions, hashtags and content calendars", "Social", ["#E91E63", "#FFC107", "#00BCD4"], "camera",
 "Caption Craft writes on-brand captions from a photo, plans a month of posts, and turns one idea into formats for every platform.",
 "You are a social media strategist with taste: hooks that stop the scroll, no cringe, platform-native, honest about what performs.",
 "Post with confidence", "Your brand voice.", ["Photo → captions", "30-day content calendars", "Repurpose across platforms"],
 [F("brand", "Brand / who you are", "text", "small bakery in Leeds", required=True), CH("voice", "Voice", ["Playful", "Warm", "Bold", "Minimal", "Expert"], multi=True), CH("platforms", "Platforms", ["Instagram", "TikTok", "LinkedIn", "X", "Facebook", "Pinterest"], multi=True)],
 [T("caption", "Caption this", "Photo → 3 captions", "📷", [PHOTO("The photo", "", True), TXT("context", "Context", "new sourdough launch")],
    "For the photo ({context}) in the profile voice: cards (3 captions, meta = platform), bullets (hashtag set), and a callout on the best posting time and CTA.", "cards, bullets, callout", "Write", "Looking…"),
  T("calendar", "30-day calendar", "Never stare at a blank feed", "📅", [TXT("goals", "Goals this month", "grow followers, push the new menu")],
    "A 30-day calendar for the brand, goals: {goals}. table (Day | Platform | Format | Idea | Hook), bullets (recurring series), and a callout on batching.", "table, bullets, callout", "Plan", "Planning…"),
  T("repurpose", "Repurpose", "One idea, every platform", "♻️", [LONG("idea", "The idea / post", "")],
    "Repurpose: {idea}. cards (one per profile platform: title = platform, body = the post, meta = format), and a callout on what to change per platform.", "cards, callout", "Repurpose", "Adapting…"),
  T("reply", "Reply to comments", "Even the rude ones", "💬", [LONG("comments", "Comments", "")],
    "Replies in the brand voice to: {comments}. table (Comment | Reply | Note), and a callout on when not to engage.", "table, callout", "Draft", "Drafting…")])

APP("dating_wing", "Wingmate", "Profiles, openers and date ideas — genuinely you", "Dating", ["#D81B60", "#FF8F00", "#26A69A"], "heart",
 "Wingmate polishes your dating profile, writes openers based on their profile, plans dates and helps you communicate honestly.",
 "You are a kind, funny dating coach: authenticity over tricks, consent and respect always, no manipulation.",
 "Show up as yourself, well", "About you.", ["Profile polish", "Openers that get replies", "Date planning & tough texts"],
 [NAME, CH("looking", "Looking for", ["Relationship", "Casual", "Not sure"]), TXT("about", "3 things about you", "climber, bad cook, loves 70s soul"), CH("humour", "Humour", ["Dry", "Silly", "Warm", "Nerdy"])],
 [T("profile", "Polish my profile", "Bio + prompts", "✨", [LONG("current", "Current bio / prompts", "", False)],
    "Improve: {current} for the profile: quote (bio, under 60 words), cards (3 prompt answers, meta = prompt), bullets (photo lineup advice), and a callout on what reads as a red flag.", "quote, cards, bullets, callout", "Polish", "Polishing…"),
  T("opener", "Write an opener", "From their profile", "💬", [LONG("theirs", "Their profile / photos description", "")],
    "3 openers for: {theirs}, in the profile humour: quote, quote, quote, and a callout on what to avoid.", "quote, quote, quote, callout", "Write", "Thinking…"),
  T("date", "Plan a date", "First, second, or the big one", "🍷", [CH("which", "Which", ["First date", "Second date", "Anniversary"], "First date"), TXT("them", "About them", "loves art, doesn't drink"), NUM("budget", "Budget", "50")],
    "Plan a {which} for someone who {them}, budget {budget}: cards (3 ideas, meta = cost & time), steps (how to suggest it), and a callout on safety/logistics.", "cards, steps, callout", "Plan", "Planning…"),
  T("text", "Help me reply", "Awkward text situations", "📱", [LONG("situation", "The situation / their message", "")],
    "For: {situation}. quote (kind, honest reply), quote (alternative), bullets (why), and a callout on boundaries.", "quote, quote, bullets, callout", "Draft", "Drafting…")])
