from dsl import *

APP("email_polish", "Inbox Pilot", "Emails written, summarised and answered in seconds", "Communication", ["#00838F", "#F4511E", "#5E35B1"], "chat",
 "Inbox Pilot drafts replies in your tone, summarises long threads, writes difficult emails (no, sorry, chase, escalate) and turns bullet points into polished messages.",
 "You are an executive assistant with impeccable judgement: concise, warm, culturally aware, never robotic.",
 "Own your inbox", "Your voice and sign-off.", ["Replies in your tone", "Thread summaries", "Hard emails made easy"],
 [NAME, F("signoff", "Sign-off", "text", "Best, Sam"), CH("tone", "Default tone", ["Friendly", "Professional", "Direct"], "Professional"), TXT("role", "Your role", "")],
 [T("reply", "Reply to this", "Paste the email", "↩️", [LONG("email", "The email you received", ""), TXT("intent", "What you want to say", "yes but not before Friday")],
    "Reply to: {email}. Intent: {intent}. quote (reply in the profile tone), quote (shorter version), and bullets on anything to double-check before sending.", "quote, quote, bullets", "Draft reply", "Drafting…"),
  T("summarise", "Summarise a thread", "Long → clear", "🧾", [LONG("thread", "Thread", "")],
    "Summarise: {thread}. bullets (what's decided), table (Action | Owner | Due), bullets (open questions), and a quote (one-line status for your boss).", "bullets, table, bullets, quote", "Summarise", "Reading…"),
  T("hard", "The hard email", "No, sorry, chase, escalate", "🧊", [CH("kind", "Kind", ["Say no", "Apologise", "Chase", "Escalate", "Deliver bad news", "Ask for a favour"], "Say no"), LONG("context", "Context", "", False)],
    "Write a '{kind}' email for: {context}. quote (the email), bullets (why it works), and a callout on what NOT to include.", "quote, bullets, callout", "Write", "Writing…"),
  T("expand", "Bullets → email", "Rough notes to polished", "🧱", [LONG("notes", "Your notes", "")],
    "Turn into a polished email: {notes}. quote (subject + body), and bullets on tone tweaks for different recipients.", "quote, bullets", "Polish", "Polishing…")])

APP("excel_wizard", "Sheet Wizard", "Spreadsheet formulas explained and written", "Productivity", ["#1B5E20", "#FFB300", "#0288D1"], "graph",
 "Sheet Wizard writes Excel/Google Sheets formulas from plain English, explains scary ones, fixes errors and designs sheet layouts.",
 "You are a spreadsheet expert: exact formulas for the stated app, explains each part, warns about pitfalls.",
 "Formulas without the frustration", "Which app?", ["Plain English → formula", "Explain & fix formulas", "Sheet design"],
 [CH("app", "App", ["Excel", "Google Sheets", "LibreOffice"], "Excel"), CH("level", "Level", ["Beginner", "Comfortable", "Power user"])],
 [T("write", "Write a formula", "Describe what you need", "🧮", [LONG("need", "What you need", "sum column C where column A says 'Paid' and date in B is this month")],
    "Formula for the profile app: {need}. quote (the formula), kv (each part → what it does), bullets (edge cases), and a callout on a simpler alternative if one exists.", "quote, kv, bullets, callout", "Write", "Composing…"),
  T("explain", "Explain a formula", "Paste it", "🔍", [TXT("formula", "Formula", "=INDEX(B:B,MATCH(1,(A:A=F1)*(C:C=G1),0))", True)],
    "Explain {formula} step by step: steps (evaluation order), kv (functions used), and a callout on where it breaks.", "steps, kv, callout", "Explain", "Parsing…"),
  T("fix", "Fix an error", "#REF!, #N/A, wrong result", "🩹", [TXT("formula", "Formula", "", True), TXT("problem", "Problem", "#N/A on some rows")],
    "Fix {formula} showing {problem}: text (cause), quote (fixed formula), and bullets (how to prevent it).", "text, quote, bullets", "Fix", "Debugging…"),
  T("design", "Design a sheet", "Layout for a task", "📐", [TXT("task", "Purpose", "track freelance invoices and payments", True)],
    "Design a sheet for {task}: table (Sheet/Tab | Columns | Notes), bullets (formulas to add), and a callout on data validation.", "table, bullets, callout", "Design", "Designing…")])

APP("linkedin_lift", "Profile Lift", "LinkedIn that gets recruiters to message you", "Business", ["#0A66C2", "#FF8F00", "#00897B"], "graph",
 "Profile Lift rewrites headlines and About sections, turns job history into achievement bullets, and drafts posts that build credibility.",
 "You are a personal-branding strategist for professionals: specific, credible, zero buzzwords.",
 "Be found for the right work", "Your goal.", ["Headline & About rewrites", "Achievement bullets", "Posts that get engagement"],
 [NAME, TXT("role", "Current role", ""), TXT("goal", "Goal", "get contacted for senior roles"), LONG("about", "Current About / experience", "", False)],
 [T("headline", "Headline & About", "Rewrite", "✨", [],
    "From the profile: cards (3 headlines, meta = angle), quote (About section, 150 words), and a callout on keywords to include.", "cards, quote, callout", "Rewrite", "Writing…"),
  T("bullets", "Achievement bullets", "For one role", "🎯", [LONG("role", "Role & what you did", "")],
    "Turn into achievement bullets: {role}. bullets (5-7 quantified bullets), a callout on numbers to find, and a quote (one-line role summary).", "bullets, callout, quote", "Convert", "Quantifying…"),
  T("post", "Write a post", "Credibility, not cringe", "📝", [TXT("idea", "Idea / story", "", True), CH("format", "Format", ["Story", "Lesson list", "Contrarian take", "How-to"], "Story")],
    "A LinkedIn post ({format}) from: {idea}. quote (the post with a strong first line), bullets (3 alternative hooks), and a callout on the comment to seed.", "quote, bullets, callout", "Write", "Writing…"),
  T("message", "Recruiter reply", "Say yes, no, or maybe", "💬", [LONG("msg", "Their message", ""), CH("answer", "Your answer", ["Interested", "Not now", "Need more info"], "Need more info")],
    "Reply '{answer}' to: {msg}. quote (reply), bullets (questions to ask), and a callout on salary framing.", "quote, bullets, callout", "Draft", "Drafting…")])

APP("prompt_smith", "Prompt Smith", "Write better prompts for any AI", "Tools", ["#37474F", "#00E5FF", "#FF4081"], "spark",
 "Prompt Smith turns rough asks into structured prompts, critiques your prompts, builds reusable templates and explains why outputs went wrong.",
 "You are a prompt engineer who teaches: clear role/task/context/format, examples over adjectives, testable criteria.",
 "Ask better, get better", "What do you use AI for?", ["Rough ask → structured prompt", "Prompt critique", "Reusable templates"],
 [NAME, CH("use", "Use cases", ["Writing", "Coding", "Research", "Images", "Data", "Customer support"], multi=True)],
 [T("improve", "Improve my prompt", "Paste it", "✨", [LONG("prompt", "Your prompt", "")],
    "Improve: {prompt}. quote (rewritten prompt with role, context, task, format, constraints), table (Change | Why), and a callout on how to test it.", "quote, table, callout", "Improve", "Refining…"),
  T("build", "Build from a goal", "Describe the outcome", "🏗️", [TXT("goal", "Goal", "get a weekly meal plan I can shop for", True)],
    "A complete prompt for '{goal}': quote (the prompt), bullets (variables to fill), and a callout on common failure modes.", "quote, bullets, callout", "Build", "Building…"),
  T("why", "Why did it fail?", "Paste prompt + bad output", "🔍", [LONG("prompt", "Prompt", ""), LONG("output", "Bad output", "", False)],
    "Diagnose why {prompt} produced {output}: bullets (causes), quote (fixed prompt), and a callout on model limits.", "bullets, quote, callout", "Diagnose", "Analysing…"),
  T("template", "Template library", "For your use case", "📚", [TXT("task", "Recurring task", "weekly status report", True)],
    "A reusable template for {task}: quote (template with {{placeholders}}), kv (placeholder → guidance), and bullets on variants.", "quote, kv, bullets", "Create", "Creating…")])

APP("sql_buddy", "Query Buddy", "SQL from plain English, explained", "Tools", ["#0D47A1", "#FFB300", "#00BFA5"], "gear",
 "Query Buddy writes SQL for your schema, explains and optimises queries, and helps you design tables.",
 "You are a database engineer: dialect-exact SQL, index-aware, explains trade-offs, never guesses column names without saying so.",
 "Ask your database anything", "Dialect and schema.", ["English → SQL", "Explain & optimise", "Schema design"],
 [CH("dialect", "Dialect", ["PostgreSQL", "MySQL", "SQLite", "SQL Server", "BigQuery"], "PostgreSQL"), LONG("schema", "Schema (tables & columns)", "", False)],
 [T("write", "Write a query", "Describe the result you want", "🧾", [LONG("need", "What you need", "monthly revenue per customer for 2025, top 20")],
    "Query for the profile dialect/schema: {need}. quote (SQL), steps (how it works), bullets (assumptions about columns), and a callout on performance.", "quote, steps, bullets, callout", "Write", "Composing…"),
  T("explain", "Explain a query", "Paste SQL", "🔍", [LONG("sql", "SQL", "")],
    "Explain: {sql}. steps (execution logic), kv (clauses → purpose), and a callout on pitfalls.", "steps, kv, callout", "Explain", "Parsing…"),
  T("optimise", "Optimise", "Make it fast", "⚡", [LONG("sql", "Slow SQL", ""), TXT("size", "Table sizes", "orders 50M rows")],
    "Optimise {sql} ({size}): quote (rewritten SQL), bullets (indexes to add), table (Change | Expected effect), and a callout on how to verify with EXPLAIN.", "quote, bullets, table, callout", "Optimise", "Tuning…"),
  T("design", "Design tables", "From a description", "📐", [LONG("domain", "What you're modelling", "a gym: members, classes, bookings, payments")],
    "Schema for: {domain}. quote (CREATE TABLE statements), table (Table | Key columns | Relationships), and a callout on indexes and constraints.", "quote, table, callout", "Design", "Designing…")])

APP("regex_ranger", "Pattern Pal", "Regex written, explained and tested", "Tools", ["#4E342E", "#00E676", "#FF7043"], "gear",
 "Pattern Pal builds regular expressions from examples, explains cryptic patterns, and generates test cases — for JS, Python, Go and more.",
 "You are a regex expert who writes readable patterns and always provides test strings that pass and fail.",
 "Match exactly what you mean", "Your language.", ["Examples → regex", "Explain any pattern", "Test cases"],
 [CH("lang", "Language / flavour", ["JavaScript", "Python", "Go", "Java", "PCRE", "grep/sed"], "JavaScript")],
 [T("build", "Build a regex", "From description + examples", "🧩", [LONG("want", "What to match", "UK postcodes like SW1A 1AA and M1 1AE"), TXT("not", "Should NOT match", "12345")],
    "Regex for the profile flavour: match {want}, not {not}. quote (pattern), kv (each part → meaning), table (Test string | Should match | Result), and a callout on edge cases.", "quote, kv, table, callout", "Build", "Composing…"),
  T("explain", "Explain a regex", "Paste it", "🔍", [TXT("regex", "Regex", "", True)],
    "Explain {regex}: kv (token → meaning), steps (how it matches), and bullets (what it wrongly matches).", "kv, steps, bullets", "Explain", "Parsing…"),
  T("replace", "Find & replace", "Transform text", "🔁", [LONG("from", "Input example", ""), LONG("to", "Desired output", "", False)],
    "Find/replace turning {from} into {to} in the profile flavour: quote (pattern), quote (replacement), and a callout on capture groups.", "quote, quote, callout", "Build", "Composing…"),
  T("validate", "Validate input", "Email, phone, dates…", "✅", [CH("what", "What", ["Email", "Phone (intl)", "URL", "Date ISO", "Password rules", "Username"], "Email")],
    "A pragmatic validation regex for {what}: quote (pattern), bullets (what it intentionally allows/rejects), and a callout on why perfect validation is a trap.", "quote, bullets, callout", "Get pattern", "Composing…")])

APP("git_guide", "Git Rescue", "Undo, merge, rebase — without fear", "Tools", ["#F05032", "#263238", "#00ACC1"], "wrench",
 "Git Rescue explains what happened, gives exact commands to fix it, writes commit messages and PR descriptions, and teaches workflows.",
 "You are a calm senior engineer: exact commands, explains what each does, always shows the safe path and the undo.",
 "You can always get it back", "Your setup.", ["Fix any git mess", "Commit & PR writing", "Workflow coaching"],
 [CH("host", "Host", ["GitHub", "GitLab", "Bitbucket", "Other"], "GitHub"), CH("level", "Comfort", ["Nervous", "Okay", "Confident"])],
 [T("fix", "Fix my mess", "Describe or paste the error", "🆘", [LONG("situation", "What happened", "committed to main by mistake, need it on a branch")],
    "Fix: {situation}. text (what state you're in), steps (exact commands with what each does), a callout on the risky command to avoid, and bullets on how to undo the fix.", "text, steps, callout, bullets", "Rescue", "Assessing…"),
  T("commit", "Commit message", "From a diff or description", "📝", [LONG("changes", "Changes (diff or description)", "")],
    "Commit message for: {changes}. quote (conventional-commit style: subject + body), and bullets on splitting if it should be several commits.", "quote, bullets", "Write", "Writing…"),
  T("pr", "PR description", "Reviewers will thank you", "🔀", [LONG("changes", "What the PR does", ""), TXT("why", "Why", "")],
    "PR description: {changes}, because {why}. quote (title + description with sections: Why, What, How to test, Risks), and a checklist for the author before requesting review.", "quote, checklist", "Draft", "Drafting…"),
  T("explain", "Explain a command", "What does this do?", "🔍", [TXT("cmd", "Command", "git rebase -i HEAD~3", True)],
    "Explain {cmd}: text (plain-English), steps (what happens), kv (flags), and a callout on when NOT to use it.", "text, steps, kv, callout", "Explain", "Reading…")])

APP("api_docs", "Doc Writer", "READMEs, API docs and changelogs that people read", "Tools", ["#455A64", "#FFB300", "#26A69A"], "note",
 "Doc Writer turns code and notes into READMEs, API references, changelogs and onboarding guides with examples.",
 "You are a technical writer engineers respect: example-first, accurate, scannable, no fluff.",
 "Docs people actually read", "Your project.", ["README generator", "API reference from code", "Changelogs & guides"],
 [TXT("project", "Project", ""), CH("stack", "Stack", ["JavaScript/TS", "Python", "Kotlin/Java", "Go", "Rust", "Other"], "Python")],
 [T("readme", "Write a README", "From a description or code", "📄", [LONG("about", "What the project does / paste code", "")],
    "README for: {about}. quote (full README in Markdown: title, one-liner, install, quick start, usage examples, config, contributing), and a checklist of things to verify.", "quote, checklist", "Write", "Writing…"),
  T("api", "API reference", "From a function or endpoint", "🔌", [LONG("code", "Function / endpoint", "")],
    "Reference for: {code}. table (Parameter | Type | Required | Description), quote (example request/call and response), bullets (errors), and a callout on gotchas.", "table, quote, bullets, callout", "Document", "Documenting…"),
  T("changelog", "Changelog entry", "From commits", "🧾", [LONG("commits", "Commits / changes", ""), TXT("version", "Version", "1.4.0")],
    "Changelog for {version}: quote (Keep-a-Changelog format: Added/Changed/Fixed/Removed), and a callout on breaking changes and migration.", "quote, callout", "Write", "Writing…"),
  T("onboard", "Onboarding guide", "New dev, day one", "🚀", [LONG("repo", "About the repo & setup", "")],
    "Onboarding guide for: {repo}. steps (setup), bullets (architecture tour), kv (where things live), and a callout on the common first-day mistake.", "steps, bullets, kv, callout", "Write", "Writing…")])

APP("customer_reply", "Support Scribe", "Customer replies that de-escalate and delight", "Business", ["#00695C", "#FF7043", "#7E57C2"], "chat",
 "Support Scribe drafts empathetic, on-policy replies to customer messages, handles refunds and complaints, and writes macros.",
 "You are a top-tier support lead: empathetic first line, clear next step, never over-promises, on-brand.",
 "Every reply, a good one", "Your product and policies.", ["Replies to any message", "Complaint de-escalation", "Macro library"],
 [F("company", "Company / product", "text", "", required=True), LONG("policy", "Key policies (refunds, SLAs)", "", False), CH("tone", "Tone", ["Warm", "Professional", "Playful"], "Warm")],
 [T("reply", "Reply to a customer", "Paste their message", "💬", [LONG("msg", "Customer message", ""), TXT("facts", "Facts / what you can offer", "refund possible within 30 days")],
    "Reply to: {msg}. Facts: {facts}. quote (reply in the profile tone), bullets (internal notes), and a callout on anything to escalate.", "quote, bullets, callout", "Draft", "Drafting…"),
  T("angry", "De-escalate", "Angry customer", "🔥", [LONG("msg", "Their message", "")],
    "De-escalate: {msg}. quote (first reply: acknowledge, own, next step), quote (follow-up after resolution), and bullets on what not to say.", "quote, quote, bullets", "De-escalate", "Calming…"),
  T("macro", "Write macros", "For common cases", "📚", [TXT("cases", "Common cases", "where is my order, refund, password reset", True)],
    "Macros for: {cases}. cards (title = case, body = macro with {{placeholders}}, meta = when to use), and a callout on personalisation.", "cards, callout", "Create", "Writing…"),
  T("review", "Respond to a review", "Public, gracious", "⭐", [LONG("review", "Review text", ""), CH("stars", "Stars", ["1", "2", "3", "4", "5"], "2")],
    "Public reply to a {stars}-star review: {review}. quote (reply), bullets (why), and a callout on legal/PII cautions.", "quote, bullets, callout", "Reply", "Drafting…")])

APP("brand_namer", "Name Storm", "Names, taglines and domains for anything", "Business", ["#6A1B9A", "#FFB300", "#00BCD4"], "bulb",
 "Name Storm generates brand, product and project names with rationale, checks pronounceability and meaning across languages, and writes taglines.",
 "You are a naming strategist: distinctive, sayable, ownable; you flag negative meanings and trademark risk (general).",
 "A name you'll be proud to say", "Your project.", ["50 names with rationale", "Taglines", "Domain & social handle ideas"],
 [TXT("what", "What needs a name", "a meal-kit for students"), CH("vibe", "Vibe", ["Playful", "Premium", "Techy", "Warm", "Bold", "Minimal"], multi=True), TXT("avoid", "Avoid", "")],
 [T("names", "Generate names", "50, sorted by style", "💡", [TXT("keywords", "Keywords", "fresh, fast, budget")],
    "50 names for the profile project with keywords {keywords}: table (Name | Style | Rationale), bullets (top 5 with why), and a callout on trademark/domain checking (general).", "table, bullets, callout", "Generate", "Storming…"),
  T("check", "Check a name", "Meaning, sayability, risks", "🔍", [TXT("name", "Name", "", True)],
    "Assess '{name}': kv (pronounceability, spelling risk, meanings in major languages, similar brands (general)), bullets (pros/cons), and a callout verdict.", "kv, bullets, callout", "Check", "Checking…"),
  T("tagline", "Taglines", "Short, sharp", "✨", [TXT("name", "Name", "", True)],
    "10 taglines for {name}: bullets (taglines), and a quote with the best one plus one-line reasoning.", "bullets, quote", "Write", "Writing…"),
  T("domains", "Domains & handles", "Available-style ideas", "🌐", [TXT("name", "Name", "", True)],
    "Domain/handle ideas for {name}: table (Idea | Type (.com/.io/get-/-app) | Note), and a callout on checking availability.", "table, callout", "Suggest", "Suggesting…")])
