from dsl import *
MED = "General information, not medical advice; consult a clinician for diagnosis or before changing medication."

APP("symptom_prep", "Doctor Prep", "Walk into appointments prepared", "Medical", ["#00838F", "#FF7043", "#5E35B1"], "shield",
 "Doctor Prep organises your symptoms into a clear timeline, prepares the questions to ask, explains test results in plain language and helps you understand medication instructions.",
 "You are a patient-advocate nurse: organises information clearly, explains jargon, never diagnoses, always defers to the clinician.",
 "Make the most of 10 minutes", "Your context.", ["Symptom timelines", "Questions to ask", "Results & medication explained"],
 [NAME, TXT("conditions", "Known conditions", ""), TXT("meds", "Medications", "")],
 [T("summary", "Symptom summary", "For the appointment", "📋", [LONG("symptoms", "What's been happening", "")],
    "Organise: {symptoms}. table (When | Symptom | Severity | Triggers/relievers), bullets (questions to ask), a quote (a 30-second summary to say first), and a callout on red flags that mean seek urgent care.", "table, bullets, quote, callout", "Organise", "Organising…"),
  T("results", "Explain my results", "Paste or photo", "🧪", [PHOTO("Photo of results (optional)"), LONG("results", "Results text", "", False)],
    "Explain in plain language: {results}. table (Test | Your value | Typical range | Meaning), bullets (questions for your doctor), and a callout that interpretation depends on context.", "table, bullets, callout", "Explain", "Reading…"),
  T("medication", "Understand a medication", "How to take it", "💊", [TXT("med", "Medication", "", True)],
    "About {med} (general): kv (what it's for, how usually taken, common side effects, interactions to ask about), bullets (practical tips), and a callout to follow the prescriber's label.", "kv, bullets, callout", "Explain", "Looking up…"),
  T("second", "Prepare for a second opinion", "Or a specialist", "🩺", [TXT("condition", "Condition / referral", "", True)],
    "Prep for a specialist about {condition}: checklist (records to bring), bullets (questions), and a callout on how to ask for a second opinion respectfully.", "checklist, bullets, callout", "Prepare", "Preparing…")], MED)

APP("period_pal", "Cycle Sense", "Understand your cycle, plan around it", "Health & Fitness", ["#AD1457", "#26A69A", "#FFB300"], "heart",
 "Cycle Sense explains cycle phases, predicts from your dates, suggests training and nutrition by phase, and helps track symptoms for your doctor.",
 "You are a women's-health educator: evidence-based, inclusive, never diagnostic; supportive about PMS, PCOS, perimenopause questions.",
 "Work with your cycle", "Your typical cycle.", ["Phase-by-phase guidance", "Training & food by phase", "Symptom logs for doctors"],
 [NAME, NUM("length", "Typical cycle length (days)", "28"), TXT("last", "Last period start", ""), CH("goals", "Interests", ["Energy", "Training", "Fertility awareness", "PMS relief", "Perimenopause"], multi=True)],
 [T("now", "Where am I?", "Today's phase & tips", "📅", [],
    "From the profile dates: kv (current phase, day, predicted next period, fertile window (educational)), bullets (what's typical now), and a callout on tracking accuracy.", "kv, bullets, callout", "Check", "Calculating…"),
  T("plan", "Plan my week by phase", "Training, food, energy", "🗓️", [TXT("week", "This week", "half marathon Sunday, exam Thursday")],
    "Plan the week ({week}) by cycle phase: table (Day | Phase | Training | Food focus | Energy note), and a callout on listening to your body.", "table, callout", "Plan", "Planning…"),
  T("symptom", "Symptom log", "Prepare for your doctor", "📝", [LONG("symptoms", "Symptoms & when", "")],
    "Organise: {symptoms}. table (Cycle day | Symptom | Severity), bullets (questions to ask), and a callout on red flags.", "table, bullets, callout", "Organise", "Organising…"),
  T("learn", "Explain", "Any cycle question", "💬", [TXT("q", "Question", "why do I get migraines before my period?", True)],
    "Answer '{q}': text (explanation), bullets (what may help), and a callout on when to see a doctor.", "text, bullets, callout", "Explain", "Thinking…")], MED)

APP("skin_coach", "Skin Routine", "Routines that fit your skin and budget", "Beauty", ["#F06292", "#4DB6AC", "#FFB300"], "sun",
 "Skin Routine builds AM/PM routines, decodes ingredient lists from photos, checks product compatibility and troubleshoots breakouts.",
 "You are a cosmetic chemist and aesthetician: ingredient-literate, budget-honest, patch-test cautious; you refer persistent issues to dermatologists.",
 "Fewer products, better skin", "Your skin.", ["AM/PM routines", "Ingredient decoding", "Compatibility checks"],
 [NAME, CH("type", "Skin type", ["Oily", "Dry", "Combination", "Normal", "Sensitive"]), CH("concerns", "Concerns", ["Acne", "Dark spots", "Fine lines", "Redness", "Dullness", "Texture"], multi=True), CH("budget", "Budget", ["Drugstore", "Mid", "Premium"])],
 [T("routine", "Build my routine", "AM + PM", "🧴", [TXT("have", "Products you own", "")],
    "AM/PM routine for the profile using: {have}. table (Step | AM | PM | Why), bullets (what to add first), and a callout on introducing actives slowly and SPF.", "table, bullets, callout", "Build", "Building…"),
  T("decode", "Decode ingredients", "Photo of the label", "📷", [PHOTO("Ingredient list", "", True)],
    "Decode the ingredients: table (Ingredient | Role | Note for the profile skin), a callout on irritants/fragrance, and a quote verdict.", "table, callout, quote", "Decode", "Reading…"),
  T("compat", "Can I use these together?", "Actives compatibility", "🔬", [TXT("a", "Product/ingredient A", "retinol", True), TXT("b", "B", "vitamin C", True)],
    "Combine {a} with {b}? callout (verdict), bullets (how to schedule them), and kv (waiting times, order).", "callout, bullets, kv", "Check", "Checking…"),
  T("breakout", "Breakout help", "What's going on", "🩹", [PHOTO("Photo (optional)"), TXT("desc", "Describe", "small bumps on forehead after new moisturiser")],
    "Assess: {desc}. text (likely cause), steps (next 2 weeks), bullets (what to stop), and a callout on when to see a dermatologist.", "text, steps, bullets, callout", "Help", "Assessing…")], "Not medical advice; patch-test new products and see a dermatologist for persistent or severe issues.")

APP("hair_care", "Hair Plan", "Routines for your curl, texture and goals", "Beauty", ["#6D4C41", "#FF8F00", "#26A69A"], "sun",
 "Hair Plan builds wash-day routines, decodes product labels, plans colour and cuts, and tackles frizz, damage and growth.",
 "You are a stylist and trichology-aware educator: texture-specific, honest about damage, budget-friendly.",
 "Good hair days, planned", "Your hair.", ["Wash-day routines", "Label decoding", "Colour & cut planning"],
 [NAME, CH("type", "Hair", ["Straight", "Wavy", "Curly", "Coily", "Fine", "Thick"], multi=True), CH("concerns", "Concerns", ["Frizz", "Damage", "Growth", "Oily scalp", "Dry ends", "Thinning"], multi=True), TXT("treated", "Colour/chemical treated?", "")],
 [T("routine", "Wash-day routine", "Step by step", "🚿", [TXT("products", "Products you own", "")],
    "Wash-day routine for the profile using {products}: steps, table (Product type | Frequency | Why), and a callout on the biggest mistake for this hair type.", "steps, table, callout", "Build", "Building…"),
  T("decode", "Decode a label", "Photo", "📷", [PHOTO("Product ingredients", "", True)],
    "Decode: table (Ingredient | Role | Good/Caution for the profile), and a quote verdict.", "table, quote", "Decode", "Reading…"),
  T("colour", "Plan a colour or cut", "Before the salon", "✂️", [TXT("want", "What you want", "going from dark brown to caramel balayage", True)],
    "Plan '{want}' for the profile hair: kv (sessions, time, cost range, maintenance), bullets (what to tell the stylist), and a callout on damage risk.", "kv, bullets, callout", "Plan", "Planning…"),
  T("fix", "Fix a problem", "Frizz, breakage, dryness", "🩹", [TXT("problem", "Problem", "", True)],
    "For {problem}: text (likely causes), steps (4-week plan), and bullets (products types to look for).", "text, steps, bullets", "Help", "Thinking…")])

APP("chess_coach", "Chess Coach", "Openings, tactics and post-game reviews", "Games", ["#37474F", "#FFB300", "#8D6E63"], "star",
 "Chess Coach builds an opening repertoire for your level, drills tactics, reviews your games from PGN and explains plans in plain language.",
 "You are a patient chess coach (FIDE-trainer style): principles over memorisation, honest about mistakes, level-appropriate.",
 "Play with a plan", "Your level.", ["Opening repertoire", "Tactics drills", "Game reviews"],
 [NAME, CH("rating", "Rating", ["<800", "800–1200", "1200–1600", "1600–2000", "2000+"]), CH("colour", "Prefer", ["White", "Black", "Both"]), CH("style", "Style", ["Attacking", "Positional", "Solid", "Not sure"])],
 [T("repertoire", "Build a repertoire", "For your level", "📚", [CH("side", "As", ["White", "Black vs e4", "Black vs d4"], "White")],
    "A repertoire as {side} for the profile: cards (opening, body = main ideas & key line, meta = difficulty), bullets (typical plans), and a callout on the trap to know.", "cards, bullets, callout", "Build", "Preparing…"),
  T("review", "Review my game", "Paste PGN or moves", "🔍", [LONG("pgn", "PGN / moves", "")],
    "Review: {pgn}. table (Move | Issue | Better | Why), bullets (the 3 lessons), and a quote with one principle to remember.", "table, bullets, quote", "Review", "Analysing…"),
  T("tactics", "Tactics drill", "10 patterns", "⚔️", [CH("theme", "Theme", ["Forks", "Pins", "Skewers", "Discovered attacks", "Back rank", "Mixed"], "Mixed")],
    "10 {theme} puzzles for the profile as a table (No. | Position (FEN or description) | Solution | Idea), and a callout on the spotting habit.", "table, callout", "Drill", "Setting up…"),
  T("plan", "What's the plan?", "Describe a position", "🧭", [LONG("position", "Position (FEN or description)", "")],
    "Plan for: {position}. text (assessment), bullets (candidate plans), steps (the next 3 moves with ideas), and a callout on what the opponent wants.", "text, bullets, steps, callout", "Explain", "Thinking…")])

APP("photo_mentor", "Shot Mentor", "Take better photos with the camera you have", "Photography", ["#263238", "#FFB300", "#00ACC1"], "camera",
 "Shot Mentor critiques your photos, gives camera settings for any scene, plans shoots and teaches editing recipes.",
 "You are a working photographer and teacher: composition-first, honest critiques, gear-agnostic.",
 "See better, shoot better", "Your gear.", ["Photo critiques", "Settings for any scene", "Shoot plans & edit recipes"],
 [NAME, CH("gear", "Gear", ["Phone", "Mirrorless/DSLR", "Film", "Drone"], multi=True), CH("interests", "Interests", ["Portraits", "Landscape", "Street", "Food", "Product", "Travel"], multi=True)],
 [T("critique", "Critique my photo", "Honest and useful", "📷", [PHOTO("Your photo", "", True)],
    "Critique the photo: table (Aspect | Score/5 | Note) for composition, light, subject, colour, moment; bullets (3 specific improvements); a callout on the edit that would help most.", "table, bullets, callout", "Critique", "Looking…"),
  T("settings", "Settings for…", "Any scene", "⚙️", [TXT("scene", "Scene", "night street, handheld, phone", True)],
    "Settings for {scene} on the profile gear: kv (mode, ISO, aperture, shutter, focus, white balance), steps (how to shoot it), and a callout on the common mistake.", "kv, steps, callout", "Get settings", "Metering…"),
  T("shoot", "Plan a shoot", "Location, time, shot list", "🗺️", [TXT("brief", "Brief", "golden-hour portraits of my friend in the city", True)],
    "Plan: {brief}. kv (time, light direction, lens/phone mode), checklist (shot list), and a callout on backup plans.", "kv, checklist, callout", "Plan", "Planning…"),
  T("edit", "Edit recipe", "For a look", "🎨", [CH("look", "Look", ["Clean & bright", "Moody", "Film", "Black & white", "Vibrant"], "Film"), CH("app", "App", ["Lightroom", "Snapseed", "VSCO", "Phone editor"], "Lightroom")],
    "An edit recipe for '{look}' in {app}: table (Control | Value | Why), steps (order), and a callout on not overdoing it.", "table, steps, callout", "Recipe", "Mixing…")])

APP("board_game_night", "Game Night", "Pick, teach and host tabletop games", "Games", ["#5E35B1", "#FFB300", "#26A69A"], "star",
 "Game Night picks games for your group, explains rules in 2 minutes, settles rule disputes and designs house variants.",
 "You are a board-game café host: knows hundreds of games, teaches clearly, matches games to people.",
 "Perfect game, every night", "Your shelf and crowd.", ["Recommendations for your group", "2-minute rule teaches", "Dispute settling"],
 [NAME, LONG("shelf", "Games you own", "", False), CH("crowd", "Usual crowd", ["Family with kids", "Couples", "Gamers", "Party", "Two players"], multi=True)],
 [T("pick", "What should we play?", "Tonight", "🎲", [NUM("players", "Players", "4"), NUM("minutes", "Time", "60"), CH("mood", "Mood", ["Light", "Strategic", "Co-op", "Party", "Bluffing"], "Light")],
    "Pick for {players} players, {minutes} min, mood {mood}, preferring the profile shelf: cards (game, body = why, meta = time & complexity), and a callout on the teach order.", "cards, callout", "Pick", "Browsing…"),
  T("teach", "Teach it in 2 minutes", "Rules summary", "📖", [TXT("game", "Game", "", True)],
    "Teach {game}: steps (setup → turn → win), bullets (common rule mistakes), and a quote (the one-sentence pitch).", "steps, bullets, quote", "Teach", "Reading…"),
  T("dispute", "Settle a dispute", "What does the rule say?", "⚖️", [TXT("game", "Game", "", True), TXT("q", "The question", "can you build on the same turn you trade?")],
    "Rule question in {game}: {q}. callout (ruling with confidence level), text (reasoning), and bullets (related edge cases).", "callout, text, bullets", "Rule", "Checking…"),
  T("variant", "House variant", "Make it fresh", "🧪", [TXT("game", "Game", "", True), TXT("goal", "Goal", "faster, fairer for kids")],
    "Variants for {game} to be {goal}: cards (variant, body = rule change, meta = effect), and a callout on balance.", "cards, callout", "Design", "Designing…")])

APP("trivia_master", "Quiz Host", "Pub quizzes and trivia nights in minutes", "Games", ["#C62828", "#FFB300", "#1565C0"], "star",
 "Quiz Host writes themed quiz rounds with answers, picture-round ideas, tie-breakers and host scripts.",
 "You are a witty quiz master: accurate facts, well-pitched difficulty, fun rounds.",
 "Host a great quiz", "Your usual crowd.", ["Themed rounds with answers", "Difficulty tuning", "Host scripts"],
 [NAME, CH("audience", "Audience", ["Pub", "Family", "Office", "Kids", "Nerds"]), CH("difficulty", "Difficulty", ["Easy", "Mixed", "Hard"], "Mixed")],
 [T("round", "Write a round", "10 questions", "❓", [TXT("theme", "Theme", "90s music", True)],
    "A 10-question {theme} round for the profile: table (No. | Question | Answer | Points), and a callout on a bonus question.", "table, callout", "Write", "Writing…"),
  T("full", "Full quiz", "6 rounds", "🏆", [TXT("themes", "Themes", "general, music, film, sport, science, picture")],
    "A 6-round quiz ({themes}): cards (round title, body = 5 questions with answers, meta = difficulty), and a quote with a host intro.", "cards, quote", "Build", "Building…"),
  T("tiebreak", "Tie-breakers", "Closest-number style", "⚖️", [],
    "10 tie-breaker questions: table (Question | Answer), and a callout on how to run a tie-break.", "table, callout", "Write", "Writing…"),
  T("script", "Host script", "Welcome, rules, banter", "🎤", [TXT("event", "Event", "office charity quiz", True)],
    "Host script for {event}: quote (welcome + rules), bullets (banter lines between rounds), and a callout on pacing.", "quote, bullets, callout", "Write", "Writing…")])

APP("diy_crafts", "Craft Corner", "Projects, patterns and fixes for makers", "Hobbies", ["#8E24AA", "#FF8F00", "#26A69A"], "wrench",
 "Craft Corner plans knitting, sewing, woodworking and paper projects to your skill, converts patterns and troubleshoots mistakes.",
 "You are a generous craft teacher across fibre, wood and paper: precise measurements, honest about difficulty.",
 "Make something this weekend", "Your crafts.", ["Projects for your skill", "Pattern maths", "Fix a mistake"],
 [NAME, CH("crafts", "Crafts", ["Knitting", "Crochet", "Sewing", "Woodwork", "Paper", "Jewellery", "Candles/soap"], multi=True), CH("level", "Level", ["Beginner", "Intermediate", "Advanced"])],
 [T("project", "Suggest a project", "Time + materials", "🧶", [CH("time", "Time", ["An evening", "A weekend", "A month"], "A weekend"), TXT("materials", "Materials on hand", "")],
    "A project for the profile in {time} with {materials}: kv (project, difficulty, cost, time), checklist (materials & tools), steps (build), and a callout on the tricky step.", "kv, checklist, steps, callout", "Suggest", "Thinking…"),
  T("maths", "Pattern maths", "Resize, gauge, yardage", "📐", [LONG("q", "Your question", "pattern gauge 20 sts/10cm, mine is 22 — how to adjust for 90cm chest?")],
    "Solve: {q}. steps (the calculation), kv (results), and a callout on swatching/testing.", "steps, kv, callout", "Calculate", "Calculating…"),
  T("fix", "Fix a mistake", "Photo + description", "🩹", [PHOTO("Photo (optional)"), TXT("problem", "Problem", "", True)],
    "Fix: {problem}. text (what happened), steps (fix), and bullets (prevent next time).", "text, steps, bullets", "Fix", "Looking…"),
  T("gift", "Handmade gift ideas", "For someone", "🎁", [TXT("who", "Who", "", True), CH("time", "Time", ["An evening", "A weekend"], "A weekend")],
    "Handmade gifts for {who} in {time} using the profile crafts: cards (gift, body = how, meta = cost/time), and a callout on presentation.", "cards, callout", "Ideas", "Thinking…")])

APP("bike_mechanic", "Bike Fix", "Maintenance, repairs and fit for any bike", "Sports", ["#00838F", "#FF7043", "#263238"], "wrench",
 "Bike Fix diagnoses noises and problems, walks through repairs with tools, sets up bike fit, and plans seasonal maintenance.",
 "You are a friendly bike-shop mechanic: safety-critical items flagged, exact torque and tools, no snobbery.",
 "Keep it rolling", "Your bike.", ["Noise & problem diagnosis", "Step-by-step repairs", "Bike fit & maintenance plans"],
 [NAME, CH("bike", "Bike", ["Road", "Gravel", "MTB", "Commuter", "E-bike", "Kids"]), CH("skill", "Skill", ["Beginner", "Handy", "Confident"]), TXT("tools", "Tools", "")],
 [T("diagnose", "What's that noise?", "Describe or photo", "🔊", [TXT("symptom", "Symptom", "clicking when pedalling hard", True), PHOTO("Photo (optional)")],
    "Diagnose '{symptom}': bullets (ranked causes), steps (checks in order), a callout on safety-critical parts, and kv (tools & parts).", "bullets, steps, callout, kv", "Diagnose", "Listening…"),
  T("repair", "How do I…", "Any repair", "🔧", [TXT("task", "Task", "index my rear derailleur", True)],
    "Guide for '{task}' on a {bike} at the profile skill: checklist (tools), steps (with torque where relevant), and a callout on when to visit a shop.", "checklist, steps, callout", "Show me", "Writing…"),
  T("fit", "Bike fit basics", "Comfort and power", "📏", [TXT("issue", "Issue", "numb hands, sore knees", True), NUM("height", "Height (cm)", "175")],
    "Fit adjustments for {issue} at {height} cm: table (Adjustment | Direction | How much | Why), steps (order), and a callout on when to get a pro fit.", "table, steps, callout", "Adjust", "Measuring…"),
  T("service", "Service schedule", "By distance and season", "🗓️", [NUM("km", "Km per week", "60")],
    "Maintenance schedule for a {bike} at {km} km/week: table (Interval | Task | DIY?), checklist (pre-ride), and a callout on the most neglected item.", "table, checklist, callout", "Plan", "Planning…")])
