from dsl import *
FIN = "General information, not financial, tax or legal advice; consult a licensed professional."

APP("tenant_rights", "Rent Ready", "Letters, checklists and know-how for renters", "House & Home", ["#1565C0", "#FF8F00", "#43A047"], "home",
 "Rent Ready writes letters to landlords, builds move-in/move-out inspection checklists, decodes lease clauses and explains deposit disputes in general terms.",
 "You are a tenant-support advisor: calm, well-documented, general-law aware (you always say to check local rules), never inflammatory.",
 "Know your lease, keep your deposit", "Your situation.", ["Landlord letters", "Inspection checklists", "Lease decoding"],
 [NAME, TXT("where", "Country / state", "England", True), CH("stage", "Stage", ["Looking", "Moving in", "Living there", "Moving out", "Dispute"])],
 [T("letter", "Write to my landlord", "Repairs, deposit, notice", "✉️", [CH("about", "About", ["Repair request", "Deposit return", "Giving notice", "Rent increase", "Noise/neighbours", "Other"], "Repair request"), LONG("details", "Details", "", False)],
    "Letter about {about}: {details}, for {where}. quote (the letter, dated, factual, polite, with a deadline), bullets (evidence to attach), and a callout on the general legal position and where to check locally.", "quote, bullets, callout", "Write", "Drafting…"),
  T("inspect", "Inspection checklist", "Move-in / move-out", "📋", [CH("which", "Which", ["Move-in", "Move-out"], "Move-in")],
    "A {which} inspection checklist by room: checklist, bullets (photo/video protocol), and a callout on what to send the landlord.", "checklist, bullets, callout", "Checklist", "Listing…"),
  T("lease", "Decode a clause", "Paste it", "🔍", [LONG("clause", "Lease clause", "")],
    "Explain: {clause} (for {where}, general): text (plain-English meaning), bullets (what it means in practice), and a callout on whether it's typical/enforceable in general terms and how to verify.", "text, bullets, callout", "Decode", "Reading…"),
  T("deposit", "Deposit dispute", "Get it back", "💰", [LONG("situation", "What happened", "")],
    "Deposit dispute: {situation} ({where}). steps (what to do in order), bullets (evidence), quote (message to the landlord), and a callout on schemes/ombudsmen to look up.", "steps, bullets, quote, callout", "Plan", "Planning…")], FIN)

APP("car_buyer", "Car Sense", "Buy, sell and maintain a car without getting fleeced", "Auto & Vehicles", ["#263238", "#FF7043", "#00ACC1"], "car",
 "Car Sense compares models for your needs, prepares inspection checklists and haggling scripts, decodes listings and plans maintenance.",
 "You are an honest mechanic-turned-consumer-advocate: reliability-first, total-cost-of-ownership minded.",
 "Drive a good deal", "What you need from a car.", ["Model shortlists", "Inspection & haggle scripts", "Maintenance plans"],
 [NAME, TXT("country", "Country", ""), NUM("budget", "Budget", "12000"), CH("needs", "Needs", ["City", "Family", "Long commutes", "Towing", "Fun", "Low running cost"], multi=True)],
 [T("shortlist", "Shortlist models", "For your needs and budget", "🚗", [CH("age", "Age", ["New", "1–3 yrs", "4–8 yrs", "Older"], "4–8 yrs"), CH("fuel", "Fuel", ["Petrol", "Diesel", "Hybrid", "EV", "Any"], "Any")],
    "Shortlist for the profile, {age}, {fuel}: cards (model & years, body = why + known issues, meta = typical price), table (Model | Reliability | Running cost | Space), and a callout on the one to avoid.", "cards, table, callout", "Shortlist", "Researching…"),
  T("inspect", "Inspect a used car", "Checklist + questions", "🔍", [TXT("car", "Car", "2018 Golf 1.6 TDI, 80k km", True)],
    "Inspection for {car}: checklist (walk-around, under bonnet, interior, test drive), bullets (questions for the seller), and a callout on the deal-breakers for this model.", "checklist, bullets, callout", "Prepare", "Preparing…"),
  T("listing", "Decode a listing", "Photo or paste", "📷", [PHOTO("Screenshot of the listing"), LONG("text", "Or paste", "", False)],
    "Decode the listing: kv (fair price estimate (general), red flags, missing info), bullets (questions to ask), and a quote (opening haggle message).", "kv, bullets, quote", "Decode", "Reading…"),
  T("maintain", "Maintenance plan", "By km and age", "🗓️", [TXT("car", "Car & mileage", "", True)],
    "Plan for {car}: table (Km/Time | Service | DIY? | Est. cost), and a callout on the expensive items coming up.", "table, callout", "Plan", "Planning…")], FIN)

APP("eco_home", "Green Home", "Cut bills and carbon, room by room", "House & Home", ["#2E7D32", "#FFB300", "#0288D1"], "leaf",
 "Green Home audits your energy use, ranks upgrades by payback, decodes bills and plans a low-waste kitchen.",
 "You are an energy-efficiency assessor with a budget: payback-first, no greenwashing, honest about what actually moves the needle.",
 "Lower bills, lighter footprint", "Your home.", ["Energy audits", "Upgrades ranked by payback", "Bill decoding"],
 [NAME, CH("home", "Home", ["Flat", "Terrace", "Semi", "Detached"]), CH("heating", "Heating", ["Gas", "Electric", "Heat pump", "Oil", "District"]), TXT("country", "Country", "")],
 [T("audit", "Quick audit", "Where the energy goes", "🔎", [LONG("info", "Tell us about your home", "1990s semi, double glazing, old boiler, 4 people")],
    "Audit: {info}. table (Area | Likely share of use | Quick win | Cost), cards (top 3 upgrades, meta = payback years), and a callout on free actions first.", "table, cards, callout", "Audit", "Assessing…"),
  T("bill", "Decode my bill", "Photo of a bill", "📷", [PHOTO("Bill photo", "", True)],
    "Decode the bill: kv (usage, unit rate, standing charge, period, comparison to typical), bullets (savings), and a callout on tariff switching (general).", "kv, bullets, callout", "Decode", "Reading…"),
  T("upgrade", "Is it worth it?", "Any upgrade", "💡", [TXT("upgrade", "Upgrade", "solar panels 4kW", True)],
    "Assess {upgrade} for the profile: kv (cost range, savings/yr, payback, carbon saved), bullets (things to check), and a callout verdict.", "kv, bullets, callout", "Assess", "Calculating…"),
  T("waste", "Low-waste kitchen", "Practical, not preachy", "♻️", [],
    "A low-waste kitchen plan: checklist (swaps), table (Habit | Saves | Effort), and a callout on the one that saves most money.", "checklist, table, callout", "Plan", "Planning…")])

APP("volunteer_match", "Do Good", "Find and plan volunteering that fits your life", "Social", ["#00897B", "#FF7043", "#5E35B1"], "heart",
 "Do Good matches your skills to volunteering ideas, plans fundraisers and drafts outreach to organisations.",
 "You are a community organiser: practical, inclusive, focused on sustainable commitment over grand gestures.",
 "Help in ways that last", "Your time and skills.", ["Volunteering ideas", "Fundraiser plans", "Outreach messages"],
 [NAME, TXT("skills", "Skills", "accounting, driving, good with kids"), CH("time", "Time", ["An hour a month", "Weekly", "A project"]), TXT("causes", "Causes", "")],
 [T("match", "Match me", "Ideas for your profile", "🤝", [TXT("where", "Where you are", "")],
    "Volunteering ideas for the profile in {where}: cards (role type, body = what you'd do & who to approach, meta = commitment), bullets (questions to ask organisations), and a callout on safeguarding checks.", "cards, bullets, callout", "Match", "Matching…"),
  T("fundraiser", "Plan a fundraiser", "From bake sale to 10k", "🎯", [TXT("cause", "Cause", "", True), NUM("target", "Target", "1000")],
    "Fundraiser for {cause} targeting {target}: cards (3 formats, meta = effort), table (Week | Task), and a quote (the ask message).", "cards, table, quote", "Plan", "Planning…"),
  T("outreach", "Write to an organisation", "Offer your help", "✉️", [TXT("org", "Organisation", "", True)],
    "Outreach to {org} offering the profile skills: quote (email), and bullets (what to include).", "quote, bullets", "Draft", "Drafting…"),
  T("impact", "Reflect", "Make it sustainable", "🌱", [LONG("done", "What you've been doing", "")],
    "Reflect on: {done}. bullets (impact), a callout on burnout signs, and steps (next quarter).", "bullets, callout, steps", "Reflect", "Reflecting…")])

APP("astro_night", "Night Sky", "What to see tonight and how to see it", "Education", ["#1A237E", "#FFB300", "#26C6DA"], "moon",
 "Night Sky plans stargazing sessions for your location and gear, explains what you're seeing and teaches astrophotography basics.",
 "You are an amateur-astronomy guide: practical, light-pollution honest, accurate about what naked eyes/binoculars/scopes can show; you say when to verify times with an app.",
 "Look up, know what you see", "Your location and gear.", ["Tonight's targets", "Object explainers", "Astrophotography basics"],
 [NAME, TXT("where", "Location", "", True), CH("gear", "Gear", ["Naked eye", "Binoculars", "Small telescope", "Phone camera"], multi=True), CH("sky", "Sky", ["City", "Suburb", "Dark site"])],
 [T("tonight", "What's up tonight?", "Targets for your gear", "🌌", [TXT("date", "Date", "tonight")],
    "Targets for {date} from the profile location/gear/sky: table (Object | Direction/time | How to find | What you'll see), a callout on moon phase and verifying times with an app, and bullets on comfort/gear.", "table, callout, bullets", "Plan", "Charting…"),
  T("explain", "What am I seeing?", "Describe or photo", "🔭", [PHOTO("Photo (optional)"), TXT("desc", "Describe", "bright object in the east around 9pm")],
    "Identify: {desc}. text (likely object with confidence), kv (facts), and bullets (how to confirm).", "text, kv, bullets", "Identify", "Looking…"),
  T("photo", "Astrophotography", "With your gear", "📷", [TXT("target", "Target", "Milky Way", True)],
    "Shoot {target} with the profile gear: kv (settings), steps, and a callout on the mistake beginners make.", "kv, steps, callout", "Teach", "Focusing…"),
  T("learn", "Learn the sky", "4-week plan", "📚", [],
    "A 4-week learn-the-sky plan for the profile: table (Week | Constellations | Objects | Skill), and a quote with a memory trick.", "table, quote", "Plan", "Planning…")])

APP("interview_kids", "Story Keeper", "Capture your family's stories before they're gone", "Lifestyle", ["#8D6E63", "#FFB300", "#00897B"], "mic",
 "Story Keeper prepares interview questions for grandparents and relatives, turns rambling recordings into polished stories and builds a family timeline.",
 "You are an oral-history interviewer and editor: gentle questions, respectful editing, preserves voice.",
 "Their stories, kept", "Who you're recording.", ["Interview question sets", "Transcript → story", "Family timeline"],
 [NAME, TXT("who", "Who you're recording", "my grandmother, 84, grew up in Kerala")],
 [T("questions", "Interview questions", "For one session", "🎙️", [CH("theme", "Theme", ["Childhood", "Love & family", "Work", "Migration", "Hard times", "Advice"], "Childhood")],
    "Questions on {theme} for the profile person: bullets (12 open questions in order), a callout on follow-up prompts, and a quote (a gentle opener).", "bullets, callout, quote", "Prepare", "Preparing…"),
  T("story", "Turn notes into a story", "Paste transcript or notes", "📖", [LONG("transcript", "Transcript / notes", "")],
    "Edit into a first-person story preserving voice: quote (the story, 300-500 words), bullets (details to confirm), and a callout on what was cut.", "quote, bullets, callout", "Write", "Editing…"),
  T("timeline", "Family timeline", "From what you know", "🗓️", [LONG("facts", "Facts & dates", "")],
    "Timeline from: {facts}. table (Year | Event | Who | Source), and bullets (gaps to ask about).", "table, bullets", "Build", "Building…"),
  T("book", "Plan a memory book", "Chapters and photos", "📚", [],
    "Plan a memory book for the profile person: table (Chapter | Stories | Photos to find), and a checklist for production.", "table, checklist", "Plan", "Planning…")])

APP("move_planner", "Move Master", "Relocating without the chaos", "House & Home", ["#EF6C00", "#00838F", "#5E35B1"], "home",
 "Move Master builds moving timelines, room-by-room packing plans, address-change checklists and first-week setup for a new city.",
 "You are a relocation coordinator: timeline-driven, thorough, calm.",
 "Everything in its box", "Your move.", ["8-week timelines", "Packing plans", "Address-change & setup lists"],
 [NAME, TXT("from", "From", ""), TXT("to", "To", ""), TXT("date", "Move date", ""), CH("home", "Home size", ["Room", "1-bed", "2-bed", "3+ bed"])],
 [T("timeline", "Moving timeline", "From now to move day", "📅", [],
    "Timeline for the profile move: table (When | Task | Done?), and a callout on the 3 things to book first.", "table, callout", "Plan", "Planning…"),
  T("pack", "Packing plan", "Room by room", "📦", [],
    "Packing plan for a {home}: table (Room | Boxes est. | Pack when | Notes), checklist (supplies), and bullets (labelling system).", "table, checklist, bullets", "Plan", "Planning…"),
  T("admin", "Address change list", "Who to tell", "✉️", [TXT("country", "Country", "")],
    "Address-change checklist for {country} (general): checklist grouped by category, and a callout on timing.", "checklist, callout", "List", "Listing…"),
  T("settle", "First week in a new place", "Set up life fast", "🏠", [],
    "First-week plan in {to}: table (Day | Tasks), bullets (finding a GP/dentist/gym/community), and a callout on loneliness and routines.", "table, bullets, callout", "Plan", "Planning…")])

APP("speech_therapy_home", "Talk Time", "Speech and language play for little ones", "Parenting", ["#26A69A", "#FF7043", "#FFB300"], "baby",
 "Talk Time suggests age-appropriate speech and language activities, explains typical milestones and helps you prepare for a speech therapist.",
 "You are a paediatric speech-language educator: play-based, milestone-aware, never diagnostic, refers to SLPs when appropriate.",
 "Talk, play, grow", "About your child.", ["Play-based activities", "Milestone explainers", "SLP visit prep"],
 [F("child", "Child's age (months)", "number", "24", required=True), TXT("concerns", "What you've noticed", ""), TXT("languages", "Languages at home", "")],
 [T("activities", "Activities this week", "5 minutes a day", "🧸", [CH("focus", "Focus", ["First words", "Two-word phrases", "Sounds (s, r…)", "Understanding", "Bilingual"], "First words")],
    "Activities for {focus} at the profile age: cards (activity, body = how, meta = minutes), bullets (words/sounds to model), and a callout on what's typical.", "cards, bullets, callout", "Suggest", "Thinking…"),
  T("milestones", "Milestones", "What to expect", "📈", [],
    "Speech/language milestones at the profile age: table (Area | Typical | Encourage with), and a callout on when to seek assessment.", "table, callout", "Show", "Looking up…"),
  T("book", "Book time", "Reading for language", "📚", [],
    "Reading strategies for the profile age: steps (dialogic reading), bullets (book types), and a quote (an example exchange).", "steps, bullets, quote", "Show", "Preparing…"),
  T("slp", "Prepare for an SLP visit", "Questions & notes", "🩺", [],
    "Prep for a speech therapist: bullets (observations to record), bullets (questions), and a callout on what to bring.", "bullets, bullets, callout", "Prepare", "Preparing…")], "Not a substitute for a speech-language pathologist's assessment.")

APP("wine_food_veg", "Veg Forward", "Delicious plant-based meals, no lectures", "Food & Drink", ["#2E7D32", "#FF7043", "#FFB300"], "leaf",
 "Veg Forward builds plant-based meals with complete protein, veganises your favourites, and plans balanced weeks.",
 "You are a plant-based chef and nutrition-literate: flavour-first, protein-aware, honest about B12 and iron.",
 "Eat more plants, happily", "Your style.", ["Veganise any dish", "Protein-complete meals", "Weekly plans"],
 [NAME, CH("level", "You are", ["Curious", "Flexitarian", "Vegetarian", "Vegan"]), TXT("dislikes", "Dislikes", ""), CH("time", "Cooking time", ["15 min", "30 min", "Weekend cook"])],
 [T("veganise", "Veganise this", "Any dish", "🌱", [TXT("dish", "Dish", "lasagne", True)],
    "Veganise {dish}: kv (swaps → why), steps (method), and a callout on texture/flavour tricks.", "kv, steps, callout", "Convert", "Converting…"),
  T("protein", "Protein-complete meal", "Hit 30g", "💪", [TXT("have", "Ingredients", "")],
    "A 30g-protein plant meal from {have}: cards (2 options, meta = protein g), steps (best one), and a table (Ingredient | Protein/100g).", "cards, steps, table", "Build", "Building…"),
  T("week", "Weekly plan", "Balanced and cheap", "🗓️", [NUM("budget", "Budget", "50")],
    "A 7-dinner plant-based plan under {budget}: table (Day | Dish | Protein source | Minutes), checklist (shopping), and a callout on B12/iron/omega-3.", "table, checklist, callout", "Plan", "Planning…"),
  T("eatout", "Eating out", "Find options anywhere", "🍽️", [TXT("place", "Restaurant type / menu", "Italian place, menu: …", True)],
    "Plant-based options at {place}: bullets (dishes & modifications), a quote (what to ask the server), and a callout on hidden animal products.", "bullets, quote, callout", "Find", "Scanning…")])

APP("allergy_safe", "Allergy Safe", "Eat out and cook safely with food allergies", "Health & Fitness", ["#C62828", "#FFB300", "#00897B"], "shield",
 "Allergy Safe scans labels and menus for your allergens, writes chef cards in any language, and plans safe meals and travel.",
 "You are an allergy-aware dietitian: precise about hidden ingredients and cross-contact, cautious, never says 'probably fine'.",
 "Safe, not sorry", "Your allergens.", ["Label & menu scanning", "Chef cards in any language", "Safe recipes & travel"],
 [NAME, F("allergens", "Allergens", "text", "peanuts, tree nuts, sesame", required=True), CH("severity", "Severity", ["Mild", "Moderate", "Anaphylaxis"])],
 [T("label", "Scan a label", "Photo → verdict", "📷", [PHOTO("Ingredient label", "", True)],
    "Scan for the profile allergens: callout (verdict: safe / unsafe / uncertain with why), table (Ingredient | Risk | Note), and bullets (hidden names and 'may contain' guidance).", "callout, table, bullets", "Scan", "Reading…"),
  T("menu", "Scan a menu", "Photo → safe picks", "🍽️", [PHOTO("Menu photo", "", True)],
    "For the profile allergens: table (Dish | Verdict | Why | Ask), and a quote (exact words for the server about cross-contact).", "table, quote", "Scan", "Reading…"),
  T("chefcard", "Chef card", "In any language", "🗂️", [TXT("language", "Language", "Japanese", True)],
    "A chef card in {language} for the profile allergens: quote (card text in {language}), quote (English version), and a callout on emergency phrases.", "quote, quote, callout", "Create", "Translating…"),
  T("recipe", "Safe recipe", "Swap out allergens", "🍳", [TXT("dish", "Dish", "", True)],
    "Make {dish} safe for the profile: kv (swaps), steps, and a callout on cross-contact in the kitchen.", "kv, steps, callout", "Adapt", "Adapting…")], "Always carry prescribed emergency medication and confirm ingredients with the kitchen; this app cannot guarantee safety.")
