from dsl import *
FIN = "General information, not financial, tax or legal advice; consult a licensed professional."
MED = "General information, not medical advice; consult a clinician."

APP("crypto_clarity", "Crypto Clarity", "Understand crypto without the hype", "Finance", ["#F7931A", "#263238", "#26A69A"], "coin",
 "Crypto Clarity explains coins, protocols and wallets in plain language, decodes whitepapers, walks through security setups and flags scam patterns.",
 "You are a sceptical, security-first crypto educator: explains mechanisms, never predicts prices, always names risks.",
 "Learn before you leap", "Your level.", ["Plain-language explainers", "Security checklists", "Scam pattern spotting"],
 [NAME, CH("level", "Level", ["Total beginner", "Some", "Experienced"]), CH("interest", "Interest", ["Bitcoin", "Ethereum/DeFi", "NFTs", "Stablecoins", "Just curious"], multi=True)],
 [T("explain", "Explain", "Any concept or coin", "💡", [TXT("q", "Question", "what is staking and what are the risks?", True)],
    "Explain '{q}' for the profile level: text (mechanism), kv (key facts), bullets (risks), and a callout that nothing here is investment advice.", "text, kv, bullets, callout", "Explain", "Thinking…"),
  T("security", "Secure my setup", "Wallets, keys, 2FA", "🔐", [CH("holding", "You hold on", ["Exchange", "Hot wallet", "Hardware wallet", "Not yet"], "Exchange")],
    "Security checklist for {holding}: checklist (ordered), a callout on seed-phrase rules, and bullets (common attacks).", "checklist, callout, bullets", "Secure", "Reviewing…"),
  T("scam", "Is this a scam?", "Paste the pitch", "🚩", [LONG("pitch", "The message / offer", "")],
    "Assess: {pitch}. callout (verdict with confidence), bullets (red flags found), and steps (what to do).", "callout, bullets, steps", "Assess", "Checking…"),
  T("whitepaper", "Decode a project", "Paste a summary or link text", "📄", [LONG("text", "Project description", "")],
    "Decode: {text}. kv (what it claims, how it works, token role, who benefits), bullets (questions to ask), and a callout on risks.", "kv, bullets, callout", "Decode", "Reading…")], FIN)

APP("tax_tidy", "Tax Tidy", "Get organised for tax season", "Finance", ["#2E7D32", "#FFB300", "#5E35B1"], "note",
 "Tax Tidy builds document checklists for your situation, explains common deductions in general terms, and turns receipts into categorised expense logs.",
 "You are a friendly bookkeeper: organised, plain-spoken, always says to confirm with an accountant or official guidance.",
 "No more shoebox", "Your situation.", ["Document checklists", "Deduction explainers (general)", "Receipt → expense log"],
 [NAME, TXT("country", "Country", "", True), CH("status", "Status", ["Employee", "Self-employed", "Both", "Landlord", "Investor"], multi=True)],
 [T("checklist", "What do I need?", "Documents for filing", "📋", [],
    "Filing checklist for the profile in {country} (general): checklist grouped by category, a callout on deadlines to look up, and bullets on what people forget.", "checklist, callout, bullets", "List", "Listing…"),
  T("receipt", "Log a receipt", "Photo → expense entry", "📷", [PHOTO("Receipt photo", "", True)],
    "From the receipt: kv (date, merchant, total, tax, category, business purpose prompt), and a callout on whether it's typically deductible for the profile (general).", "kv, callout", "Log", "Reading…"),
  T("deduct", "Can I deduct this?", "General guidance", "❓", [TXT("expense", "Expense", "home office chair", True)],
    "Is '{expense}' typically deductible for the profile in {country}? callout (general answer), bullets (conditions), and a text note to confirm officially.", "callout, bullets, text", "Check", "Checking…"),
  T("quarter", "Quarterly summary", "Paste transactions", "📊", [LONG("tx", "Transactions", "")],
    "Categorise: {tx}. table (Category | Total | Count), bullets (anomalies), and a callout on set-aside estimate (general).", "table, bullets, callout", "Summarise", "Sorting…")], FIN)

APP("kid_activities", "Rainy Day Box", "Kids' activities from what's in the house", "Parenting", ["#FF7043", "#4DB6AC", "#FFCA28"], "star",
 "Rainy Day Box invents age-appropriate activities from household items, plans birthday parties and screen-free afternoons, and turns chores into games.",
 "You are a playful early-years educator: safe, cheap, mess-honest, learning-in-disguise.",
 "Bored? Not for long", "Your kids.", ["Activities from household stuff", "Party plans", "Chores as games"],
 [F("kids", "Kids' ages", "text", "4 and 7", required=True), CH("mess", "Mess tolerance", ["Low", "Medium", "Bring it on"])],
 [T("now", "Something to do now", "From what you have", "🎨", [TXT("have", "Stuff around", "cardboard boxes, tape, dried pasta"), NUM("minutes", "Minutes to fill", "45")],
    "Activities for the profile kids using {have}, {minutes} minutes: cards (activity, body = how, meta = mess & minutes), and a callout on the learning hidden inside.", "cards, callout", "Ideas", "Inventing…"),
  T("party", "Birthday party", "Plan it", "🎂", [NUM("age", "Turning", "6"), NUM("guests", "Kids", "10"), CH("where", "Where", ["Home", "Park", "Venue"], "Home"), NUM("budget", "Budget", "150")],
    "Party for a {age}-year-old, {guests} kids at {where}, budget {budget}: table (Time | Activity), checklist (supplies), and a callout on the meltdown moment and how to avoid it.", "table, checklist, callout", "Plan", "Planning…"),
  T("chores", "Chores as games", "Get help without nagging", "🧹", [TXT("chores", "Chores", "tidy toys, set the table", True)],
    "Turn {chores} into games for the profile kids: cards (game, body = rules, meta = chore), and a quote (the invitation line to say).", "cards, quote", "Gamify", "Inventing…"),
  T("outing", "Free outing", "Nearby, low cost", "🌳", [TXT("where", "Where you live", ""), CH("weather", "Weather", ["Sunny", "Rainy", "Cold"], "Sunny")],
    "Free/cheap outings in {where} on a {weather} day for the profile kids: cards (outing, body = what to do there, meta = cost), and a checklist (bag).", "cards, checklist", "Suggest", "Thinking…")])

APP("elder_care", "Care Compass", "Support for those caring for ageing parents", "Medical", ["#5E35B1", "#FFB300", "#26A69A"], "heart",
 "Care Compass helps family caregivers organise medications, prepare for appointments, plan safe homes and navigate difficult conversations.",
 "You are a geriatric-care coordinator: compassionate, organised, safety-focused, never diagnostic; supports the caregiver too.",
 "You don't have to carry it alone", "About who you care for.", ["Medication & appointment organisers", "Home safety plans", "Conversation scripts"],
 [NAME, F("person", "Who you care for", "text", "my dad, 82, mild dementia", required=True), TXT("conditions", "Conditions & medications", "")],
 [T("meds", "Medication schedule", "Clear and printable", "💊", [LONG("meds", "Medications & instructions", "")],
    "Organise: {meds}. table (Time | Medication | Dose | With food? | Note), bullets (interactions to ask the pharmacist about), and a callout to confirm with the prescriber.", "table, bullets, callout", "Organise", "Organising…"),
  T("safety", "Home safety", "Room by room", "🏠", [CH("risks", "Concerns", ["Falls", "Wandering", "Kitchen", "Bathroom", "Stairs", "Medication errors"], multi=True)],
    "Home safety plan for the profile person, concerns {risks}: checklist by room, cards (top 3 changes, meta = cost), and a callout on the most effective one.", "checklist, cards, callout", "Plan", "Planning…"),
  T("talk", "Difficult conversation", "Driving, moving, help", "💬", [CH("topic", "Topic", ["Stopping driving", "Accepting help at home", "Moving to care", "Finances", "End-of-life wishes"], "Accepting help at home")],
    "Script for '{topic}' with the profile person: quote (opener), steps (the conversation), bullets (what not to say), and a callout on respecting autonomy.", "quote, steps, bullets, callout", "Script", "Thinking…"),
  T("me", "Caregiver check-in", "You matter too", "💛", [LONG("how", "How are you doing?", "")],
    "Check-in: {how}. text (validation), bullets (signs of burnout), steps (respite plan), and a callout on support resources to look up.", "text, bullets, steps, callout", "Check in", "Listening…")], MED)

APP("first_aid_ref", "First Aid Now", "Calm, step-by-step first aid guidance", "Medical", ["#C62828", "#FFFFFF", "#1565C0"], "shield",
 "First Aid Now gives clear step-by-step first aid for common situations, builds home and travel kits and teaches you before you need it.",
 "You are a first-aid instructor: calm, numbered steps, always says when to call emergency services first.",
 "Know what to do", "Your context.", ["Step-by-step for emergencies", "Kit checklists", "Practice scenarios"],
 [NAME, TXT("country", "Country (for emergency number)", ""), CH("context", "Context", ["Home with kids", "Outdoors", "Workplace", "Elderly at home"], multi=True)],
 [T("help", "What do I do?", "Describe the situation", "🚨", [TXT("situation", "Situation", "adult choking, can't speak", True)],
    "For '{situation}': callout (call emergency services now? with the number for the profile country), steps (numbered, short), bullets (do NOT), and text (what to watch for).", "callout, steps, bullets, text", "Guide me", "Ready…"),
  T("kit", "Build a kit", "Home, car, travel", "🧰", [CH("kind", "Kit", ["Home", "Car", "Travel", "Hiking", "Baby"], "Home")],
    "A {kind} first-aid kit: checklist (items with quantities), a callout on medication expiry, and bullets (skills to pair with it).", "checklist, callout, bullets", "List", "Listing…"),
  T("learn", "Learn a skill", "Before you need it", "📚", [CH("skill", "Skill", ["CPR", "Choking", "Bleeding control", "Burns", "Anaphylaxis", "Stroke recognition"], "CPR")],
    "Teach {skill}: steps, a quote (memory aid), bullets (common mistakes), and a callout on getting certified.", "steps, quote, bullets, callout", "Teach", "Teaching…"),
  T("scenario", "Practice scenario", "Test yourself", "🎭", [],
    "A practice scenario for the profile context: text (the scene), bullets (what would you do — questions), and steps (model answer).", "text, bullets, steps", "Practise", "Setting up…")], "In an emergency call your local emergency number first. This is educational guidance, not a substitute for training or professional care.")

APP("keto_kitchen", "Keto Kitchen", "Low-carb meals that don't feel like a diet", "Food & Drink", ["#6D4C41", "#FF8F00", "#43A047"], "cup",
 "Keto Kitchen builds low-carb meals and weeks, checks net carbs from labels, adapts favourites and handles restaurants.",
 "You are a low-carb chef and nutrition-literate coach: net-carb precise, flavour-first, honest about electrolytes.",
 "Fat-fuelled, flavour-full", "Your targets.", ["Meals under your carb limit", "Label net-carb checks", "Restaurant survival"],
 [NAME, NUM("carbs", "Net carbs/day", "25"), CH("style", "Style", ["Strict keto", "Low-carb", "Carnivore-ish"]), TXT("dislikes", "Dislikes", "")],
 [T("meal", "Meal ideas", "From what you have", "🥩", [TXT("have", "Ingredients", ""), CH("meal", "Meal", ["Breakfast", "Lunch", "Dinner", "Snack"], "Dinner")],
    "3 {meal} ideas from {have} within the profile carb limit: cards (dish, body = how, meta = net carbs & minutes), steps (best one).", "cards, steps", "Suggest", "Cooking…"),
  T("label", "Net carbs from a label", "Photo", "📷", [PHOTO("Nutrition label", "", True)],
    "From the label: kv (serving, total carbs, fibre, sugar alcohols, net carbs, verdict), and a callout on hidden sugars.", "kv, callout", "Check", "Reading…"),
  T("week", "Weekly plan", "Under your limit", "🗓️", [],
    "7-day plan for the profile: table (Day | Breakfast | Lunch | Dinner | Net carbs), checklist (shopping), and a callout on electrolytes.", "table, checklist, callout", "Plan", "Planning…"),
  T("out", "Eating out", "Any cuisine", "🍽️", [TXT("cuisine", "Cuisine / menu", "Thai", True)],
    "Keto-friendly ordering for {cuisine}: bullets (dishes & modifications), quote (what to ask), and a callout on hidden carbs.", "bullets, quote, callout", "Find", "Scanning…")], MED)

APP("intermittent_fast", "Fast Track", "Intermittent fasting, made sustainable", "Health & Fitness", ["#00838F", "#FFB300", "#5E35B1"], "clock",
 "Fast Track designs fasting schedules around your life, plans what to eat in your window, handles hunger and social events, and reviews your week.",
 "You are a measured fasting coach: evidence-aware, never extreme, clear about who should not fast.",
 "Eat in a window, live in the day", "Your routine.", ["Schedules that fit your life", "Eating-window plans", "Hunger & social strategies"],
 [NAME, CH("protocol", "Protocol", ["16:8", "14:10", "5:2", "OMAD", "Not sure"]), F("wake", "Wake time", "text", "07:00"), TXT("goal", "Goal", "")],
 [T("schedule", "My schedule", "Window + timing", "⏰", [TXT("life", "Your day", "gym at 6pm, family dinner at 8")],
    "A fasting schedule for the profile given: {life}. kv (window, first meal, last meal, coffee rules), table (Time | What), and a callout on who should not fast.", "kv, table, callout", "Plan", "Planning…"),
  T("window", "What to eat", "In the window", "🍽️", [NUM("kcal", "Calories target", "1800")],
    "Meals for the profile window at {kcal} kcal: cards (meal, meta = kcal & protein), and bullets (break-fast gently).", "cards, bullets", "Plan", "Planning…"),
  T("hunger", "I'm hungry", "Get through it", "😖", [TXT("when", "When", "3pm, 2 hours before window", True)],
    "Hunger at {when}: steps (next 30 minutes), bullets (what's allowed), and a callout on when to just eat.", "steps, bullets, callout", "Help", "Thinking…"),
  T("review", "Weekly review", "Paste your log", "📓", [LONG("log", "Log", "")],
    "Review: {log}. bullets (patterns), a callout (adjustment), and steps (next week).", "bullets, callout, steps", "Review", "Reading…")], MED)

APP("tea_master", "Tea Master", "Brew every tea to its best", "Food & Drink", ["#2E7D32", "#FFB300", "#8D6E63"], "cup",
 "Tea Master gives exact brewing parameters, identifies teas from photos, pairs teas with moods and food, and builds a tasting practice.",
 "You are a tea sommelier: precise temperatures and times, gongfu and western methods, no snobbery.",
 "Steep it right", "Your tea habits.", ["Brew parameters", "Tea identification", "Pairings & tasting"],
 [NAME, CH("teas", "You drink", ["Green", "Black", "Oolong", "White", "Pu-erh", "Herbal", "Matcha"], multi=True), CH("method", "Method", ["Teapot", "Gongfu", "Mug", "Cold brew"])],
 [T("brew", "How do I brew this?", "Any tea", "🍵", [TXT("tea", "Tea", "Tie Guan Yin oolong", True)],
    "Brew {tea} with the profile method: kv (leaf per ml, temperature, first steep time, re-steeps), steps, and a callout on the common mistake.", "kv, steps, callout", "Brew", "Steeping…"),
  T("id", "Identify a tea", "Photo of leaves or packet", "📷", [PHOTO("Photo", "", True)],
    "Identify the tea: text (type & confidence), kv (origin, processing, flavour), and bullets (how to brew).", "text, kv, bullets", "Identify", "Looking…"),
  T("pair", "Pair with…", "Food or mood", "🧀", [TXT("with", "Food or mood", "dim sum", True)],
    "Teas for {with}: cards (tea, body = why, meta = caffeine), and a callout on serving temperature.", "cards, callout", "Pair", "Pairing…"),
  T("taste", "Tasting session", "Train your palate", "👅", [],
    "A tasting session for the profile teas: steps, table (Aspect | What to notice | Vocabulary), and a quote with a note-taking template.", "steps, table, quote", "Guide", "Preparing…")])

APP("cocktail_bar", "Home Bar", "Cocktails from what's on your shelf", "Food & Drink", ["#37474F", "#FFB300", "#E91E63"], "cup",
 "Home Bar suggests cocktails from the bottles you own, scales recipes for parties, builds a starter bar and creates mocktails.",
 "You are a bartender who loves teaching: exact measures, technique, responsible-service aware.",
 "Shake, stir, serve", "Your shelf.", ["Cocktails from your bottles", "Batch recipes for parties", "Mocktails"],
 [NAME, LONG("shelf", "Bottles you own", "gin, vermouth, Campari, lime", False), CH("taste", "Taste", ["Bitter", "Sour", "Sweet", "Strong", "Fizzy"], multi=True)],
 [T("make", "What can I make?", "From your shelf", "🍸", [TXT("extra", "Also have", "")],
    "Cocktails from the profile shelf plus {extra}: cards (drink, body = recipe & method, meta = strength), and a callout on the one missing bottle that unlocks most.", "cards, callout", "Suggest", "Mixing…"),
  T("batch", "Batch for a party", "Scale it", "🥳", [TXT("drink", "Drink", "margarita", True), NUM("serves", "Serves", "12")],
    "Batch {drink} for {serves}: kv (each ingredient scaled), steps (batching, dilution, chilling), and a callout on serving & responsible pacing.", "kv, steps, callout", "Scale", "Scaling…"),
  T("starter", "Build a starter bar", "For your taste", "🧰", [NUM("budget", "Budget", "150")],
    "A starter bar for the profile taste under {budget}: table (Bottle | Why | Est. cost), bullets (tools), and cards (5 drinks it unlocks).", "table, bullets, cards", "Build", "Stocking…"),
  T("mocktail", "Mocktails", "Just as good", "🍹", [TXT("vibe", "Vibe", "summer, not too sweet")],
    "3 mocktails for '{vibe}': cards (drink, body = recipe, meta = time), and a callout on garnishes.", "cards, callout", "Suggest", "Mixing…")], "Please drink responsibly and never drink and drive.")

APP("bread_baker", "Bread Lab", "Sourdough and bread, troubleshot", "Food & Drink", ["#8D6E63", "#FFB300", "#5D4037"], "cup",
 "Bread Lab builds bake schedules around your day, scales recipes by baker's percentages, diagnoses flat loaves from photos and adapts to your flour.",
 "You are a patient baker: baker's percentages, hydration-aware, honest about ambient temperature.",
 "Bake better bread", "Your setup.", ["Bake schedules", "Baker's % scaling", "Crumb & crust diagnosis"],
 [NAME, CH("starter", "Starter", ["Sourdough", "Yeast", "Both"]), TXT("oven", "Oven / dutch oven", ""), TXT("temp", "Kitchen temp", "21°C")],
 [T("schedule", "Bake schedule", "Fit it around your day", "⏰", [TXT("day", "Your day", "work 9–6, want bread for Sunday lunch", True)],
    "Sourdough/yeast schedule for the profile given: {day}. table (Time | Step | Notes), and a callout on temperature adjustments.", "table, callout", "Plan", "Planning…"),
  T("scale", "Scale a recipe", "Baker's percentages", "⚖️", [LONG("recipe", "Recipe", "500 flour, 375 water, 100 starter, 10 salt"), NUM("target", "Target flour (g)", "800")],
    "Scale {recipe} to {target} g flour: table (Ingredient | % | Grams), and a callout on hydration effects.", "table, callout", "Scale", "Calculating…"),
  T("diagnose", "What went wrong?", "Photo of crumb/crust", "📷", [PHOTO("Photo of the loaf/crumb", "", True), TXT("process", "What you did", "")],
    "Diagnose from photo and: {process}. text (likely cause), bullets (fixes ranked), and steps (next bake).", "text, bullets, steps", "Diagnose", "Examining…"),
  T("recipe", "Recipe for…", "Any bread", "🥖", [TXT("bread", "Bread", "focaccia", True)],
    "A {bread} recipe for the profile setup: table (Ingredient | Grams | %), steps, and a callout on the make-or-break step.", "table, steps, callout", "Recipe", "Writing…")])
