from dsl import *

# w03 — Food & Drink: home brewing, fermentation, smoothies, juicing, tea/coffee niches, non-alcoholic

APP("homebrew_beer", "Brew Day", "Design, brew and troubleshoot beer at home", "Food & Drink", ["#E65100", "#3E2723", "#FDD835"], "flame",
 "Brew Day designs beer recipes for your kit and batch size, writes a brew-day timeline with clock times, calculates priming sugar and ABV, and diagnoses stuck ferments and off-flavours.",
 "You are a seasoned homebrew-club mentor: precise with grams, litres and gravities, obsessed with sanitation, and honest about which mistakes matter and which don't.",
 "Your next batch, planned properly", "Tell us your kit and batch size so the numbers come out right.", ["Recipes scaled to your kit", "Brew-day timelines and checklists", "Fixes for stuck ferments and off-flavours"],
 [NAME, CH("method", "Method", ["Extract", "BIAB", "All-grain"]), NUM("batch", "Batch size (L)", "20"), CH("temp", "Fermentation control", ["Room temp", "Fridge + controller", "Cool cupboard"])],
 [T("recipe", "Design a recipe", "Style + target ABV → grain, hops, yeast", "🍺",
    [CH("style", "Style", ["Pale ale", "IPA", "Stout", "Wheat", "Lager", "Saison", "Bitter", "Belgian"], "Pale ale"), NUM("abv", "Target ABV %", "5.5"), TXT("notes", "Twists or constraints", "only Citra and Mosaic, no crystal malt")],
    "Design a {style} at {abv}% ABV for the profile's method and batch size, honouring: {notes}. Sections: kv (OG, FG, IBU, SRM, assumed efficiency, yeast strain), a table of the grain bill and hop schedule (Ingredient | Amount g | When | Purpose), steps for mash, boil and fermentation with temperatures and times, and a callout on the one thing most likely to go wrong with this style.",
    "kv, table, steps, callout", "Design recipe", "Milling…"),
  T("brewday", "Brew-day timeline", "Clock times from heat-up to pitch", "⏱️",
    [TXT("start", "Start time", "09:00", True), TXT("recipe", "Recipe summary", "20 L pale ale, 60-min mash, 60-min boil")],
    "Write a brew-day timeline starting at {start} for: {recipe}, using the profile's method. Steps with clock times (heat strike water, mash in, mash out, sparge, boil start, each hop addition, chill, pitch), a checklist of equipment to sanitise before each stage, and a callout on the two moments where sanitation matters most.",
    "steps, checklist, callout", "Plan the day", "Heating water…"),
  T("ferment", "Fermentation check", "Is it stuck? Is it done?", "🌡️",
    [TXT("gravities", "OG → current gravity", "1.052 → 1.020", True), NUM("days", "Days since pitch", "7"), TXT("yeast", "Yeast + temperature", "US-05 at 18°C")],
    "Gravity readings {gravities} after {days} days on {yeast}. Give kv (expected FG, ABV so far, attenuation %, verdict: fermenting / stuck / done), text explaining the verdict, steps to rouse or restart if it is stuck ordered from least to most intervention, and a callout on when it is safe to bottle.",
    "kv, text, steps, callout", "Check it", "Reading gravity…"),
  T("offflavour", "Fix an off-flavour", "Taste → cause → fix", "👃",
    [CH("taste", "It tastes like", ["Green apple", "Butter", "Band-aid / medicinal", "Rotten egg", "Cardboard", "Sour", "Solvent / hot alcohol", "Banana + clove (unwanted)"], "Green apple"), TXT("process", "What you did", "fermented at 24°C, bottled day 10")],
    "The beer tastes of {taste}; process: {process}. Table (Compound | Likely cause | Fix next batch | Will it fade?), steps to salvage this batch if possible, and bullets on the process changes to make first given the profile's temperature control.",
    "table, steps, bullets", "Diagnose", "Sniffing the glass…"),
  T("bottle", "Bottling calculator", "Priming sugar + carbonation", "🧴",
    [NUM("volume", "Volume to bottle (L)", "19"), CH("carb", "Carbonation", ["Low (British)", "Medium (ale)", "High (wheat / Belgian)"], "Medium (ale)"), NUM("temp", "Beer temp at bottling (°C)", "20")],
    "Calculate priming for {volume} L at {carb} carbonation with the beer at {temp}°C. kv (target CO2 volumes, table sugar g, dextrose g, honey g, 500 ml bottles needed), steps for making and mixing the priming solution evenly, a checklist for bottling day, and a callout on bottle-bomb warning signs.",
    "kv, steps, checklist, callout", "Calculate", "Counting bottles…")],
 "Homebrewing laws vary by country; check yours. Sanitise everything, never bottle before fermentation has finished (bottle bombs), and keep boiling wort and CO2 away from children and pets.")


APP("kombucha_lab", "Booch Lab", "Kombucha and jun, batch after batch", "Food & Drink", ["#00897B", "#F4511E", "#FFD54F"], "spark",
 "Booch Lab schedules first and second ferments for your kitchen temperature, designs flavours that actually carbonate, checks SCOBY health from a photo, and troubleshoots vinegar, flat bottles and mould.",
 "You are a friendly kombucha brewer and food-safety nerd: you love flavour experiments but never gamble on a suspect batch.",
 "Brew the booch you actually want", "Your vessel and kitchen temperature set every timeline.", ["1F and 2F timelines for your kitchen", "Flavour recipes that carbonate", "SCOBY check from a photo"],
 [NAME, CH("brew", "You brew", ["Kombucha", "Jun", "Both"]), NUM("vessel", "Vessel size (L)", "4"), NUM("room", "Kitchen temp (°C)", "22")],
 [T("batch", "Plan a batch", "Tea, sugar, starter and dates", "🫖",
    [CH("tea", "Tea base", ["Black", "Green", "Oolong", "Black + green mix", "Jun (green + honey)"], "Black"), CH("target", "Target taste", ["Sweet", "Balanced", "Tart"], "Balanced"), TXT("start", "Start day", "Saturday")],
    "Plan a first ferment in the profile's vessel with a {tea} base aiming {target}, starting {start}, at the profile's kitchen temperature. kv (tea g, sugar g, water L, starter liquid ml, expected 1F days), steps from brewing the tea to covering the jar, a table (Day | What to check | What it should taste like), and a callout on the pH and taste cues that mean it is ready.",
    "kv, steps, table, callout", "Plan batch", "Steeping…"),
  T("flavour", "Second-ferment flavour", "Fruit, herbs, fizz", "🍓",
    [TXT("have", "Ingredients you have", "ginger, frozen mango, mint", True), CH("fizz", "Fizz level", ["Gentle", "Lively", "Champagne"], "Lively")],
    "Design 4 second-ferment flavours from {have} for {fizz} fizz as cards (meta = g or ml per 500 ml bottle · 2F days at the profile's temperature). Then steps for bottling (headspace, bottle type, burping schedule) and a callout on sugar sources that over-carbonate and how to avoid exploding bottles.",
    "cards, steps, callout", "Flavour it", "Adding the fruit…"),
  T("scoby", "Check my SCOBY", "Photo → healthy, yeasty or mould", "📷",
    [PHOTO("Photo of the SCOBY or jar surface", "Good light, from above", True)],
    "Assess the photo. kv (verdict: healthy / yeast-heavy / suspect / mould — discard, confidence, key visual evidence), a table (Feature seen | Normal? | What it means), steps for what to do next (keep brewing, rebalance yeast, or discard and sanitise), and a callout that fuzzy or coloured mould has only one safe response: discard everything.",
    "kv, table, steps, callout", "Check", "Peering in…"),
  T("fix", "Troubleshoot", "Vinegary, flat, slimy, fruit flies", "🔧",
    [CH("problem", "Problem", ["Too vinegary", "Too sweet / slow", "Flat bottles", "Over-carbonated", "Stringy brown bits", "Fruit flies", "Off smell"], "Too vinegary"), TXT("details", "Details", "10 days, 26°C, second batch with this SCOBY")],
    "Problem: {problem}. Details: {details}. Explain the likely cause in text, then steps to fix this batch and the next, bullets on prevention tuned to the profile's temperature, and a callout if anything described means the batch must be discarded.",
    "text, steps, bullets, callout", "Diagnose", "Tasting a sample…"),
  T("hotel", "SCOBY hotel & pause", "Holidays, breaks, sharing", "🏨",
    [CH("plan", "I want to", ["Pause for 2–4 weeks", "Pause for months", "Split and share a SCOBY", "Restart a neglected hotel"], "Pause for 2–4 weeks")],
    "For '{plan}' with the profile's vessel, give steps with quantities and timings. Then a checklist of what to check when you come back, and a callout on the signs the culture did not survive.",
    "steps, checklist, callout", "Show me", "Tucking it in…")],
 "Home ferments carry food-safety risk. Discard any batch with fuzzy mould, and check with a clinician before drinking kombucha if pregnant, immunocompromised or managing a health condition. Not medical advice.")


APP("ferment_crock", "Crock & Brine", "Sauerkraut, pickles and hot sauce, by the numbers", "Food & Drink", ["#8D6E63", "#C62828", "#7CB342"], "leaf",
 "Crock & Brine calculates salt by weight, writes ferment recipes for kraut, pickles, hot sauce and garlic honey, tracks timelines for your kitchen temperature, and tells you from a photo whether that film is kahm or mould.",
 "You are a meticulous fermentation teacher: salt percentages by weight, vegetables always submerged, and a firm 'when in doubt, throw it out'.",
 "Ferment vegetables with confidence", "Your gear and kitchen temperature shape every timeline.", ["Brine and dry-salt calculator", "Recipes for kraut, pickles and hot sauce", "Kahm-or-mould photo check"],
 [NAME, CH("gear", "Gear", ["Mason jars", "Crock with weights", "Airlock lids", "Vacuum bags"], multi=True), NUM("room", "Kitchen temp (°C)", "20"), CH("heat", "Heat tolerance", ["Mild", "Medium", "Hot", "Extra hot"])],
 [T("brine", "Brine calculator", "Exact salt for your jar", "⚖️",
    [NUM("veg", "Vegetable weight (g)", "800"), NUM("water", "Water added (ml)", "500"), CH("pct", "Salt %", ["2", "2.5", "3", "3.5", "5"], "2.5")],
    "Calculate salt for {veg} g of vegetables plus {water} ml water at {pct}% of total weight. kv (salt g for the brine method, salt g for the dry-salt method, brine strength check, headspace to leave), a table (Vegetable type | Recommended % | Why), and a callout on which salts to avoid and why iodised salt and chlorinated water cause trouble.",
    "kv, table, callout", "Calculate", "Weighing the salt…"),
  T("recipe", "Ferment recipe", "Kraut, pickles, carrots, salsa…", "🥬",
    [TXT("veg", "What you have", "1 red cabbage, 3 carrots, 2 jalapeños", True), CH("style", "Make it", ["Classic kraut", "Curtido", "Dill pickles", "Fermented salsa", "Garlic honey", "Giardiniera", "Fermented carrots"], "Classic kraut")],
    "A {style} recipe from {veg} for the profile's gear and heat tolerance. kv (yield, salt g, ferment days at the profile's temperature, ready-when cues), steps with weights in grams, a table (Day | Look for | Taste), and a callout on keeping everything submerged.",
    "kv, steps, table, callout", "Write recipe", "Salting the cabbage…"),
  T("check", "Kahm or mould?", "Photo of the jar surface", "📷",
    [PHOTO("Photo of the surface or jar", "Natural light, lid off", True)],
    "Assess the ferment surface in the photo. kv (verdict: normal / kahm yeast / mould — discard / cannot tell, confidence, evidence), bullets contrasting what is visible with textbook kahm versus mould, steps for what to do now, and a callout that fuzzy, blue, black, pink or slimy growth means discard the whole jar.",
    "kv, bullets, steps, callout", "Check", "Looking closely…"),
  T("hotsauce", "Hot sauce builder", "From mash to bottle", "🌶️",
    [TXT("chillies", "Chillies + extras", "500 g habanero, 2 mangoes, garlic", True), CH("finish", "Finish", ["Smooth & pourable", "Chunky", "Thick Sriracha-style"], "Smooth & pourable")],
    "Build a fermented hot sauce from {chillies} with a {finish} finish for the profile's heat tolerance. Steps for the mash ferment with salt % and days, then steps for blending, straining, vinegar and thickener in ml and g, kv (estimated heat, yield, fridge life, pH target for shelf stability), and a callout on capsaicin safety (gloves, ventilation, blender lid).",
    "steps, kv, callout", "Build sauce", "Wearing gloves…"),
  T("timeline", "Timeline & storage", "When it's ready, how long it keeps", "📅",
    [TXT("batch", "Batch + start date", "2 L kraut, started Monday", True), CH("goal", "Flavour goal", ["Crunchy & mild", "Balanced", "Very sour"], "Balanced")],
    "For {batch} aiming '{goal}' at the profile's temperature, produce a table (Day range | Stage | What to check | Action) and kv (expected ready date, fridge life once cold, best container). Then bullets on slowing or speeding the ferment, and a callout on why refrigeration stops the clock but not the flavour.",
    "table, kv, bullets, callout", "Plan", "Checking dates…")],
 "Weigh your salt, keep vegetables submerged, and discard anything fuzzy, pink, slimy or foul-smelling. Not medical advice; if in doubt, throw it out.")


APP("smoothie_blend", "Blend Book", "Smoothies built for your goal, blender and week", "Food & Drink", ["#D81B60", "#7CB342", "#FFB300"], "bolt",
 "Blend Book writes smoothies around your goal and the produce you have, preps a week of freezer packs, fixes texture and taste, and estimates the nutrition of what is in the cup.",
 "You are a practical smoothie-bar owner and nutrition-literate cook: you balance protein, fibre and sweetness, and you never oversell health claims.",
 "Better blends, less waste", "Your blender and goal change the recipes.", ["Recipes for your goal and gear", "Weekly freezer-pack prep", "Fix any smoothie that went wrong"],
 [NAME, CH("blender", "Blender", ["High-power", "Standard jug", "Personal / bullet", "Hand blender"]), CH("goal", "Main goal", ["Breakfast replacement", "Post-workout", "More greens", "Kids", "Weight management", "Just tasty"]), TXT("avoid", "Avoid", "dairy, banana")],
 [T("blend", "Blend from what I have", "Produce + goal → 3 recipes", "🥤",
    [LONG("have", "What you have", "spinach, frozen berries, oats, peanut butter, oat milk"), CH("texture", "Texture", ["Thin & drinkable", "Thick & spoonable", "Bowl"], "Thin & drinkable")],
    "Using {have} at {texture} texture for the profile's goal, blender and avoid-list: 3 recipes as cards (meta = ml · kcal est. · protein g est.), steps for the blending order that avoids chunks on the profile's blender, and bullets on what to add to each for more protein or fibre.",
    "cards, steps, bullets", "Blend", "Whirring…"),
  T("packs", "Freezer packs", "A week of grab-and-blend bags", "🧊",
    [NUM("count", "Packs to make", "5"), NUM("budget", "Budget", "25"), TXT("theme", "Theme", "green mornings, tropical")],
    "Plan {count} freezer smoothie packs on a {budget} budget with theme '{theme}' for the profile's goal and avoid-list. Table (Pack | Contents with grams | Add on the day | kcal est.), a checklist shopping list, steps for the assembly session with portioning tips, and a callout on freezer life and what not to freeze.",
    "table, checklist, steps, callout", "Plan packs", "Filling bags…"),
  T("fix", "Fix my smoothie", "Too thick, bitter, separated…", "🔧",
    [CH("problem", "Problem", ["Too thick", "Too thin / watery", "Bitter or grassy", "Too sweet", "Chalky protein", "Separates", "Gritty seeds", "Bland"], "Bitter or grassy"), TXT("recipe", "What went in", "2 cups kale, 1 apple, water, chia")],
    "Problem: {problem}. Recipe: {recipe}. Text on why it happened, a table (Fix | How much | Trade-off), and steps to rescue the glass in front of you right now.",
    "text, table, steps", "Fix it", "Re-blending…"),
  T("nutrition", "Estimate nutrition", "What's really in the cup", "📊",
    [LONG("recipe", "Recipe with amounts", "1 banana, 200 ml whole milk, 30 g whey, 1 tbsp peanut butter")],
    "Estimate nutrition for: {recipe}. Table (Ingredient | Amount | kcal | Protein g | Carbs g | Fibre g | Sugar g), kv (totals per serving, sugar from fruit vs added), a callout on whether it fits the profile's goal, and bullets on 2 swaps that would improve it.",
    "table, kv, callout, bullets", "Estimate", "Counting calories…"),
  T("scan", "Scan my fruit bowl", "Photo → blend it before it turns", "📷",
    [PHOTO("Photo of your fruit bowl or fridge", "", True)],
    "List every fruit and vegetable visible as a table (Item | Ripeness | Use within days | Best in). Then 3 smoothies as cards prioritising the ripest items and honouring the profile's avoid-list (meta = ml · kcal est.), and bullets on what to freeze today for later.",
    "table, cards, bullets", "Scan", "Checking ripeness…")],
 "Nutrition figures are estimates, not medical advice. Talk to a clinician or dietitian about medical diets, allergies, supplements or feeding infants.")


APP("juice_press", "Pulp & Press", "Juicing recipes, produce yields and zero-waste pulp", "Food & Drink", ["#F57C00", "#43A047", "#E53935"], "drop",
 "Pulp & Press writes juice recipes for your juicer, calculates how much produce you need, plans a juicing week with storage rules, and turns pulp into crackers, broths and muffins.",
 "You are a cold-press juice-bar founder: obsessed with produce yield, allergic to waste, and careful never to promise that juice cures anything.",
 "Juice more, waste less", "Your juicer type sets yields and shelf life.", ["Recipes tuned to your juicer", "Produce-to-ml yield calculator", "Pulp recipes so nothing is binned"],
 [NAME, CH("juicer", "Juicer", ["Masticating (slow)", "Centrifugal", "Twin gear", "Citrus press", "Blender + strain"]), CH("taste", "You like", ["Green & savoury", "Sweet & fruity", "Spicy ginger", "Rooty (beet / carrot)"], multi=True)],
 [T("recipe", "Juice recipe", "From what's in the fridge", "🥕",
    [LONG("produce", "Produce available", "6 carrots, 2 apples, ginger, half a lemon, celery"), CH("mood", "Mood", ["Green & lean", "Bright citrus", "Sweet & rooty", "Ginger kick", "Kid-friendly"], "Green & lean")],
    "From {produce} make a '{mood}' juice on the profile's juicer: 3 recipes as cards (meta = ml yield est. · kcal est.), steps for the feeding order that maximises yield and avoids foaming on this juicer, and a kv of sugar g per glass compared with a glass of orange juice for context.",
    "cards, steps, kv", "Juice it", "Feeding the chute…"),
  T("yield", "Produce calculator", "How much to buy for X ml", "🧮",
    [TXT("juice", "Juice + amount", "500 ml carrot-apple-ginger a day for 5 days", True)],
    "Calculate produce for {juice} on the profile's juicer. Table (Produce | Weight kg | Pieces approx | ml yield | Est. cost), kv (total ml, total cost, cost per glass vs bought cold-pressed), a checklist shopping list, and a callout on which items to buy organic or peel and which can be budget.",
    "table, kv, checklist, callout", "Calculate", "Weighing carrots…"),
  T("week", "Juicing week", "Batch, store, drink on time", "📅",
    [CH("glasses", "Glasses per day", ["1", "2", "3"], "1"), TXT("prefs", "Preferences this week", "less beet, more citrus")],
    "Plan 7 days of {glasses} glass(es) per day with preferences: {prefs}, for the profile's taste. Table (Day | Juice | Make on | Drink by), steps for two batch sessions with bottling and storage rules for the profile's juicer, a checklist shopping list, and a callout on storage life, filling bottles to the brim, and how to tell a juice has turned.",
    "table, steps, checklist, callout", "Plan week", "Lining up bottles…"),
  T("pulp", "Use the pulp", "Crackers, broth, muffins, dog treats", "♻️",
    [TXT("pulp", "Pulp type + amount", "2 cups carrot-apple pulp", True), CH("make", "Make", ["Crackers", "Muffins", "Veggie burgers", "Broth", "Dog treats", "Compost tips"], "Crackers")],
    "Turn {pulp} into {make} with steps that give grams and oven temperatures. Add kv (prep minutes, yield, keeps for) and bullets on 3 other uses for this exact pulp.",
    "steps, kv, bullets", "Use it", "Rescuing the pulp…"),
  T("clean", "Clean & maintain", "Your juicer, done right", "🧽",
    [CH("issue", "Issue", ["Routine clean", "Stained parts", "Smells", "Screen clogs", "Less juice than before", "Loud / grinding"], "Routine clean")],
    "For '{issue}' on the profile's juicer, give steps in order. Then a checklist of parts to inspect, and a callout on what not to put in the dishwasher or scrub with metal.",
    "steps, checklist, callout", "Show me", "Scrubbing…")],
 "Juice is food, not a treatment. Nutrition is estimated; drink fresh juice within 72 hours (24 hours from a centrifugal juicer). Speak to a clinician before juice-only days if pregnant, diabetic or on medication.")


APP("matcha_whisk", "Whisk & Bowl", "Matcha, from grade to froth to latte", "Food & Drink", ["#33691E", "#AED581", "#455A64"], "star",
 "Whisk & Bowl decodes matcha grades from a tin photo, coaches usucha and koicha technique, builds lattes and bakes, and plans caffeine so the afternoon bowl doesn't wreck your sleep.",
 "You are a matcha specialist who trained in an Uji tea house and a modern café: precise about grams, water temperature and whisking, and relaxed about how people actually drink it.",
 "Get the froth every time", "Your kit and taste shape the coaching.", ["Grade decoder from a photo", "Whisking technique, fixed", "Lattes, bakes and caffeine plans"],
 [NAME, CH("kit", "Kit", ["Chasen + chawan", "Electric frother", "Shaker bottle", "Just a spoon"]), CH("taste", "You want", ["Ceremonial, straight", "Lattes", "Both"]), CH("sweet", "Sweetness", ["None", "A little", "Sweet"])],
 [T("grade", "Decode a tin", "Photo → grade, origin, best use", "📷",
    [PHOTO("Photo of the tin, packet or the powder itself", "", True)],
    "Read the photo. kv (brand or origin if visible, stated grade, likely real grade from colour and packaging, harvest if stated, price tier, best use), text on what the colour and texture tell you, bullets on whether it suits the profile's taste, and a callout on storage after opening.",
    "kv, text, bullets, callout", "Decode", "Reading the label…"),
  T("whisk", "Whisk technique", "Usucha, koicha, or with your kit", "🍵",
    [CH("style", "Style", ["Usucha (thin)", "Koicha (thick)", "Frother latte base", "Shaker cold matcha"], "Usucha (thin)"), CH("problem", "Problem", ["Clumps", "No froth", "Bitter", "Weak", "Just learning"], "Just learning")],
    "Coach {style} for the profile's kit with problem '{problem}'. kv (grams, water ml, temperature °C, sift yes/no, whisk seconds), steps with the motion described precisely, a table (Symptom | Cause | Fix), and a quote with one cue to say to yourself while whisking.",
    "kv, steps, table, quote", "Coach me", "Sifting…"),
  T("latte", "Latte & drinks", "Iced, hot, strawberry, hojicha swap", "🥛",
    [CH("milk", "Milk", ["Oat", "Whole", "Almond", "Soy", "Coconut"], "Oat"), CH("temp", "Serve", ["Iced", "Hot"], "Iced"), TXT("twist", "Twist", "strawberry, vanilla, no syrup")],
    "Build 3 {temp} matcha drinks with {milk} milk and twist '{twist}' at the profile's sweetness as cards (meta = matcha g · ml · caffeine mg est.). Then steps for the best one including how to avoid a bitter or clumpy base, and bullets on cheaper ways to get café texture with the profile's kit.",
    "cards, steps, bullets", "Make drinks", "Frothing…"),
  T("bake", "Bake with matcha", "Cookies, cakes, mochi", "🍪",
    [CH("bake", "Bake", ["Cookies", "Pound cake", "Mochi", "Cheesecake", "Pancakes", "Ice cream"], "Cookies"), NUM("serves", "Servings", "12")],
    "Write a matcha {bake} recipe for {serves} servings. Sections: kv (matcha grams and which grade to use so it stays green and not bitter, prep and bake minutes), steps with grams and temperatures, and a callout on keeping the colour vivid.",
    "kv, steps, callout", "Bake", "Preheating…"),
  T("caffeine", "Caffeine plan", "Bowls, lattes and sleep", "🌙",
    [TXT("day", "Today's drinks", "1 usucha 7am, oat latte 2pm", True), TXT("bed", "Bedtime", "23:00")],
    "Today: {day}, bedtime {bed}. Table (Time | Drink | Caffeine mg est. | Still in system at bedtime est.), kv (total mg, last sensible matcha time for this bedtime), and bullets on L-theanine and swapping to hojicha or genmaicha later in the day.",
    "table, kv, bullets", "Plan", "Counting milligrams…")],
 "Caffeine figures are estimates and this is not medical advice; check with a clinician if pregnant, caffeine-sensitive or on medication.")


APP("coffee_roaster", "Roast Curve", "Roast green coffee at home, batch by batch", "Food & Drink", ["#5D4037", "#FF6F00", "#212121"], "gear",
 "Roast Curve plans roast profiles for your roaster and beans, analyses your roast logs by first-crack timing, judges roast colour from a photo, and schedules resting so you brew at peak.",
 "You are a small-batch roaster who teaches: you speak in charge temperature, development-time ratio and first crack, and you treat smoke and chaff as real hazards.",
 "Your roaster, your beans, a plan", "Tell us the machine and batch size so the times make sense.", ["Profiles for popper, air or drum roaster", "Roast-log analysis", "Colour check from a photo"],
 [NAME, CH("roaster", "Roaster", ["Popcorn popper", "Air roaster (e.g. Fresh Roast)", "Small drum (e.g. Gene, Kaleido)", "Pan / oven", "Behmor"]), NUM("batch", "Batch size (g)", "150"), CH("like", "You like", ["Light & fruity", "Medium & sweet", "Dark & bold"])],
 [T("profile", "Plan a roast profile", "Beans → target curve", "📈",
    [TXT("beans", "Green beans", "Ethiopia Guji natural, high density", True), CH("target", "Target", ["Light (filter)", "Medium (all-round)", "Medium-dark (espresso)", "Dark"], "Medium (all-round)")],
    "Plan a roast of {beans} to {target} for the profile's roaster and batch size. kv (charge temp or fan/heat setting, expected first-crack time, drop time, development-time ratio %, weight loss %), a table (Phase | Time window | Temp or setting | What to watch), steps for the roast including cooling, and a callout on the most common failure mode for this bean-roaster combination.",
    "kv, table, steps, callout", "Plan roast", "Charging the drum…"),
  T("log", "Analyse my roast log", "Paste times and temps", "📓",
    [LONG("log", "Roast log", "charge 200°C, turning point 1:10 @ 95°C, yellow 4:00, FC 8:30 @ 196°C, drop 10:15 @ 212°C, 14% loss")],
    "Analyse: {log}. kv (DTR %, rate-of-rise trend, total time, verdict), bullets on what the numbers suggest about flavour (baked, scorched, underdeveloped, good), a table (Metric | Yours | Target for the profile's preference | Adjust by), and steps for the next roast changing one variable.",
    "kv, bullets, table, steps", "Analyse", "Reading the curve…"),
  T("colour", "Judge the roast", "Photo of beans → level and defects", "📷",
    [PHOTO("Photo of roasted beans on white paper", "Even light, no shadows", True)],
    "Judge the roasted beans in the photo. Give kv (roast level, Agtron range est., evenness, surface oil, defects seen such as tipping, scorching or quakers), a table (Observation | Cause | Fix next time), and bullets on how this level will brew best.",
    "kv, table, bullets", "Judge", "Squinting at beans…"),
  T("green", "Buy green beans", "What to order next", "🛒",
    [NUM("budget", "Budget", "40"), TXT("want", "Wanting", "something chocolatey for espresso, plus one washed Kenyan")],
    "Recommend green beans for {budget} with wish: {want}, for the profile's roaster and taste. Cards (origin · process · variety, meta = price tier · roast difficulty), bullets on reading a green-coffee listing (density, moisture, screen size, crop year), and a callout on storing greens.",
    "cards, bullets, callout", "Recommend", "Browsing lots…"),
  T("rest", "Rest & brew schedule", "When each batch peaks", "☕",
    [LONG("batches", "Batches roasted", "Mon: 150 g Guji light; Wed: 200 g Brazil medium-dark")],
    "For {batches}, build a table (Batch | Roast level | Rest days before brewing | Peak window | Best brew method). Then steps for degassing and storage, and a callout on why fresh-off-the-roaster espresso tastes wrong.",
    "table, steps, callout", "Schedule", "Letting it breathe…")],
 "Roasting makes smoke, hot chaff and carbon monoxide. Roast with strong ventilation, never leave a roaster unattended, keep chaff away from heat, and keep an extinguisher nearby.")


APP("milk_tea_lab", "Chai & Boba", "Masala chai, boba and milk teas of the world", "Food & Drink", ["#8E24AA", "#D4A373", "#3E2723"], "cup",
 "Chai & Boba makes café-quality milk teas at home: masala blends ground to your taste, tapioca pearls and brown-sugar syrup that actually work, regional recipes from Hong Kong to Kolkata, and chai for a crowd.",
 "You are a chai-wallah turned boba-shop owner: generous with spice, exact with steep times, and honest about what needs a shop machine and what doesn't.",
 "Your cup, your way", "Tell us your milk and sweetness so recipes land right.", ["Masala blends ground to your taste", "Chewy pearls and shop-style syrups", "Regional milk teas, home-scaled"],
 [NAME, CH("milk", "Milk", ["Whole", "Oat", "Almond", "Soy", "Evaporated", "Lactose-free"]), CH("sweet", "Sweetness", ["0%", "25%", "50%", "75%", "100%"], "50%"), CH("caff", "Caffeine", ["Full", "Half", "Decaf where possible"])],
 [T("masala", "Masala blend builder", "Grind your own chai masala", "🫚",
    [CH("lead", "Lead flavour", ["Cardamom-forward", "Ginger-heavy", "Warm cinnamon", "Peppery", "Balanced"], "Cardamom-forward"), NUM("cups", "Batch for how many cups", "20"), TXT("avoid", "Avoid", "cloves, star anise")],
    "Design a {lead} chai masala for {cups} cups avoiding {avoid}. Table (Spice | Grams | Whole or ground | Role), steps for toasting, grinding and storing, kv (masala g per cup, tea g per cup, steep minutes, milk ratio for the profile's milk), and bullets on 3 variations from the same blend.",
    "table, steps, kv, bullets", "Build blend", "Toasting cardamom…"),
  T("boba", "Boba at home", "Pearls, syrup, tea base", "🧋",
    [CH("drink", "Drink", ["Classic brown-sugar milk tea", "Taro", "Thai tea", "Matcha", "Fruit tea with jelly", "Cheese-foam tea"], "Classic brown-sugar milk tea"), CH("pearls", "Pearls", ["Make from scratch", "Dried store pearls", "No pearls"], "Dried store pearls")],
    "Make {drink} with {pearls} for the profile's milk and sweetness. Steps for the pearls (cook and rest minutes, syrup soak), steps for the syrup or topping with grams, kv (tea g, steep temp and minutes, ice, cup ml, caffeine mg est.), and a callout on pearl shelf life and choking risk for young children.",
    "steps, kv, callout", "Make it", "Boiling pearls…"),
  T("regional", "Regional milk tea", "HK, teh tarik, Kashmiri, Thai, Taiwanese…", "🌏",
    [CH("style", "Style", ["Hong Kong silk-stocking", "Teh tarik", "Kashmiri noon chai", "Thai iced tea", "Kolkata roadside chai", "Taiwanese milk tea", "Turkish çay"], "Hong Kong silk-stocking")],
    "Teach {style} at home for the profile's milk. Sections: text on what makes it distinct and which parts need shop gear, kv (tea type and grams, water ml, time, milk and sugar for the profile's sweetness), steps including the signature technique, and bullets on substitutions when the exact tea is unavailable.",
    "text, kv, steps, bullets", "Teach me", "Pulling the tea…"),
  T("crowd", "Chai for a crowd", "Scale, keep hot, serve", "🫖",
    [NUM("people", "People", "30"), CH("serve", "Serving", ["Thermos", "Pot on stove", "Slow cooker", "Iced dispenser"], "Thermos")],
    "Scale chai for {people} people served from {serve} at the profile's sweetness. Sections: kv (water L, milk L for the profile's milk, tea g, masala g, sugar g), steps for brewing in stages so it does not stew, a checklist of gear and cups, and a callout on keeping milk tea safe over 2+ hours.",
    "kv, steps, checklist, callout", "Scale it", "Filling the pot…"),
  T("tune", "Tune my cup", "Bitter, weak, split milk, gummy pearls", "🔧",
    [CH("problem", "Problem", ["Bitter / astringent", "Weak", "Milk curdled or split", "Pearls hard in the middle", "Pearls mushy", "Too sweet", "Skin on top"], "Bitter / astringent"), TXT("did", "What you did", "boiled tea 10 min with milk")],
    "Problem: {problem}; you did: {did}. Text on the cause, a table (Change | To | Why), and steps for the next cup.",
    "text, table, steps", "Fix it", "Re-steeping…")],
 "Tapioca pearls and jellies are a choking hazard for children under 4. Caffeine figures are estimates, not medical advice.")


APP("zero_proof", "Zero Proof", "Alcohol-free drinks that don't feel like a compromise", "Food & Drink", ["#1E88E5", "#00ACC1", "#FF7043"], "moon",
 "Zero Proof helps sober-curious and alcohol-free drinkers find non-alcoholic beers, wines and spirits that match what they liked, make shrubs and syrups from scratch, plan dry parties, and handle 'why aren't you drinking?' with grace.",
 "You are a zero-proof bar director: encyclopaedic on NA beers, dealcoholised wines and botanical spirits, never judgemental about anyone's reasons, and honest about which products are worth the money.",
 "Drink well without alcohol", "Tell us what you used to enjoy so recommendations fit.", ["NA picks matched to your old favourites", "Shrubs, syrups and house drinks", "Dry parties and bar scripts"],
 [NAME, CH("liked", "You liked", ["IPA / craft beer", "Lager", "Red wine", "White / sparkling", "Gin & tonic", "Whisky", "Cocktails", "Never drank"], multi=True), CH("why", "Approach", ["Fully alcohol-free", "Cutting down", "Pregnancy", "Driving / training", "Prefer not to say"]), CH("budget", "Budget per bottle", ["Under 5", "5–15", "15–30", "Any"])],
 [T("match", "Find my match", "NA versions of what you liked", "🔍",
    [CH("want", "Tonight I want", ["A beer", "A wine", "A spirit & mixer", "A sipping drink", "A sparkling toast"], "A beer"), TXT("occasion", "Occasion / notes", "Friday night curry, want something hoppy")],
    "Recommend zero-proof options for '{want}' with notes: {occasion}, matched to the profile's past favourites and budget. Cards (product style with example product types, meta = closest to · price tier · 0.0% or ≤0.5%), text on what to expect versus the alcoholic version, and bullets on where these are usually stocked.",
    "cards, text, bullets", "Find matches", "Reading labels…"),
  T("label", "Decode an NA label", "Photo → ABV, sugar, what it's like", "📷",
    [PHOTO("Photo of the bottle or can label", "", True)],
    "Read the label. kv (product type, stated ABV, dealcoholised or brewed low, sugar g per 100 ml, calories, key botanicals or hops), text on how it will taste and what to mix it with, a callout on whether it suits the profile's approach (0.0% versus 0.5%), and bullets on 2 similar alternatives.",
    "kv, text, callout, bullets", "Decode", "Reading…"),
  T("house", "House drink", "Shrubs, syrups, spritzes from scratch", "🍋",
    [TXT("have", "What's in the kitchen", "apples, apple cider vinegar, rosemary, soda water", True), CH("style", "Style", ["Spritz", "Sour", "Highball", "Warm / winter", "Dessert"], "Spritz")],
    "Create 3 {style} zero-proof drinks from {have} as cards (meta = minutes · makes N · sweetness). Then steps for one shrub or syrup base with grams and ml that keeps 2 weeks in the fridge, and bullets on adding bitterness, tannin or heat so it drinks like a grown-up drink.",
    "cards, steps, bullets", "Create", "Muddling…"),
  T("party", "Dry party plan", "Quantities, a menu and a bar layout", "🎉",
    [NUM("guests", "Guests", "20"), NUM("hours", "Hours", "4"), TXT("vibe", "Vibe", "summer garden, some guests will drink")],
    "Plan a zero-proof bar for {guests} guests over {hours} hours ({vibe}) within the profile's budget. Table (Drink | Batch size | Servings | Est. cost), a checklist of glassware, ice, garnishes and signage, steps for batching the day before, and a callout on presenting NA drinks so they are never the sad option.",
    "table, checklist, steps, callout", "Plan party", "Chilling glasses…"),
  T("script", "What to say", "Bars, weddings, the pushy friend", "💬",
    [CH("scene", "Scene", ["Ordering at a bar", "Work drinks", "Wedding toast", "A friend who keeps pushing", "Family dinner", "First date"], "Ordering at a bar"), CH("tone", "Tone", ["Light and funny", "Direct", "Private, no explanation"], "Light and funny")],
    "For '{scene}' in a {tone} tone, write a quote with exactly what to say (2 alternatives). Then bullets on what to order or bring so you have a good drink in hand, and a callout on your right not to explain.",
    "quote, bullets, callout", "Give me lines", "Rehearsing…")],
 "Most 'alcohol-free' drinks contain up to 0.5% ABV and some closely mimic alcohol. If you are in recovery, pregnant or on medication, check with your clinician or support programme. Not medical advice.")


APP("cider_mead", "Hive & Orchard", "Mead, cider and country wines you'll be proud of", "Food & Drink", ["#F9A825", "#6D4C41", "#C0CA33"], "sun",
 "Hive & Orchard designs mead, hard cider and fruit wine recipes for your batch size, schedules yeast nutrients, turns gravity readings into ABV, and gets you safely through stabilising, back-sweetening and bottling.",
 "You are a patient meadery and cidery mentor: exact about gravities, nutrients and sulphites, and firm that nobody bottles a still-fermenting brew.",
 "From honey or apples to a clean bottle", "Batch size and gear make the numbers exact.", ["Recipes scaled to your carboy", "Nutrient and gravity schedules", "Safe stabilising and bottling"],
 [NAME, NUM("batch", "Batch size (L)", "5"), CH("gear", "Gear", ["Demijohn / carboy + airlock", "Bucket fermenter", "Hydrometer", "Refractometer", "Kegging"], multi=True), CH("style", "You mostly want", ["Dry", "Off-dry", "Sweet", "Sparkling"])],
 [T("recipe", "Design a batch", "Mead, cider, cyser, melomel, country wine", "🍯",
    [CH("type", "Type", ["Traditional mead", "Melomel (fruit mead)", "Cyser (apple mead)", "Hard cider", "Country wine (any fruit)", "Braggot", "Alcoholic ginger beer"], "Traditional mead"), NUM("abv", "Target ABV %", "12"), TXT("ingredients", "Ingredients / flavour ideas", "wildflower honey, 1 kg raspberries")],
    "Design a {type} at {abv}% ABV for the profile's batch size and style preference using: {ingredients}. kv (honey or juice kg, water L, OG target, expected FG, yeast strain, expected time to dry), a table of ingredients (Item | Amount | When added | Why), steps from sanitising to pitching, and a callout on the classic mistake for this type.",
    "kv, table, steps, callout", "Design", "Warming the honey…"),
  T("nutrients", "Nutrient schedule", "Staggered additions, done right", "🧪",
    [NUM("og", "Original gravity", "1.110"), TXT("yeast", "Yeast + volume", "Lalvin 71B, 5 L", True), CH("nutrient", "Nutrient on hand", ["Fermaid O", "Fermaid K + DAP", "Generic yeast nutrient", "None yet"], "Fermaid O")],
    "Build a staggered nutrient schedule for OG {og} with {yeast} using {nutrient}. Table (Addition | Day or gravity point | Grams | Notes), steps for degassing and adding safely to avoid foam-overs, kv (total YAN target, temperature range), and a callout on why late additions cause off-flavours.",
    "table, steps, kv, callout", "Schedule", "Feeding the yeast…"),
  T("gravity", "Gravity to ABV", "And is it finished?", "📏",
    [TXT("readings", "Readings with dates", "1.100 day 0, 1.030 day 10, 1.012 day 21", True), CH("tool", "Measured with", ["Hydrometer", "Refractometer (Brix)"], "Hydrometer")],
    "Readings: {readings}, taken with {tool} (correct refractometer readings for alcohol if needed). kv (ABV now, attenuation %, expected final gravity, verdict: fermenting / stalled / finished), text explaining the verdict, steps for what to do next, and a callout that two identical readings 3 days apart are required before stabilising or bottling.",
    "kv, text, steps, callout", "Calculate", "Taking a reading…"),
  T("finish", "Stabilise & sweeten", "Sulphite, sorbate, back-sweeten, clear", "🍾",
    [CH("goal", "Goal", ["Back-sweeten still", "Sparkling dry (bottle condition)", "Clear it faster", "Age and mellow", "Oak or spice it"], "Back-sweeten still"), TXT("state", "Current state", "dry at 0.996, cloudy, tastes hot")],
    "Goal: {goal}. State: {state}. Steps with grams per litre for the profile's batch (sulphite, sorbate, finings or priming sugar as relevant), a table (Day | Action | Check), kv (target FG for the profile's style, sensible ageing months), and a callout on the bottle-bomb rule: never back-sweeten an unstabilised batch and never bottle-condition a back-sweetened one.",
    "steps, table, kv, callout", "Finish it", "Racking…"),
  T("fix", "Something's wrong", "Sulphur, rocket fuel, stuck, film", "🚨",
    [CH("problem", "Problem", ["Rotten-egg smell", "Hot / rocket fuel", "Stuck fermentation", "Film or mould on top", "Won't clear", "Vinegar / sour", "Too sweet, won't restart"], "Rotten-egg smell"), TXT("details", "Details", "day 8, 24°C, no nutrients added")],
    "Problem: {problem}; details: {details}. Text on the likely cause, steps to fix now ordered least drastic first, bullets to prevent it next batch, and a callout on when to discard (true mould versus a harmless pellicle).",
    "text, steps, bullets, callout", "Diagnose", "Sniffing airlock…")],
 "Check local laws on home fermentation. Sanitise everything, never bottle a still-fermenting batch (bottle bombs), and never back-sweeten without stabilising. Not medical advice.")
