from dsl import *
MH = "Not therapy or medical advice. If you're in crisis or thinking about harming yourself or someone else, contact local emergency services or a crisis line now."
LIGHT = "A wellbeing tool, not a substitute for professional support; if low mood or stress persists, talk to a clinician."

APP("burnout_radar", "Burnout Radar", "Catch burnout early and plan the way back", "Health & Fitness", ["#E65100", "#37474F", "#FFC107"], "bolt",
 "Burnout Radar checks where you sit on the exhaustion curve, audits what drains and refills you, scripts the hard conversations, and builds a recovery plan for a job you can't just quit.",
 "You are a calm occupational-health coach who knows the burnout research: honest without catastrophising, practical about jobs people can't leave, and clear that severe symptoms need a professional.",
 "How close to the edge are you?", "A little about your work helps the check-in be honest.", ["Weekly burnout check-in", "Energy audit of your real week", "Scripts for boundaries and leave"],
 [NAME, TXT("job", "Job / role", "ICU nurse, nights"), CH("hours", "Typical week", ["Under 40h", "40–50h", "50–60h", "60h+"]), CH("support", "Support at work", ["Good manager", "Neutral", "Unsupportive", "Self-employed"])],
 [T("checkin", "Burnout check-in", "Three questions, an honest reading", "🌡️",
    [CH("exhaustion", "Exhaustion this week", ["Rarely", "Some days", "Most days", "Every day"], "Some days"), CH("cynicism", "Detachment / cynicism", ["Rarely", "Some days", "Most days", "Every day"], "Some days"), CH("efficacy", "Feeling effective", ["Usually", "Sometimes", "Rarely", "Never"], "Sometimes")],
    "Interpret a burnout check-in for the profile: exhaustion {exhaustion}, detachment {cynicism}, sense of effectiveness {efficacy}. Produce a kv (Stage: engaged / strained / burning out / burnt out, Main driver, Most protective factor, Trend to watch), a text section explaining the reading in plain words without diagnosing, a checklist of 5 concrete actions for the next 7 days ordered by effort, and a callout on the signs that mean speak to a GP or therapist this week.",
    "kv, text, checklist, callout", "Read my level", "Taking the reading…"),
  T("audit", "Energy audit", "Paste your week → drains and refills", "🔋",
    [LONG("week", "Your week, roughly", "Mon 9–7 back-to-back calls, skipped lunch; Tue site visit, felt good…")],
    "Audit this week: {week}. Table (Activity | Hours est. | Drain or refill | Why), bullets naming the 3 biggest drains and the 2 most reliable refills, steps to rebalance next week by moving or shrinking specific drains, and a callout on the one thing to protect even on the worst day.",
    "table, bullets, steps, callout", "Audit my week", "Weighing it up…"),
  T("boundary", "Say no gracefully", "Scripts for a specific ask", "🚧",
    [TXT("ask", "The request", "cover the weekend shift again", True), CH("who", "From", ["Manager", "Colleague", "Client", "Family"], "Manager"), CH("tone", "Tone", ["Warm", "Neutral", "Firm"], "Warm")],
    "Write a {tone} boundary for the request '{ask}' from my {who}. Quote with the exact words to say or send (under 80 words) followed by a second short version for when they push back, bullets on a trade-off to offer if I genuinely can, and a callout on what not to apologise for.",
    "quote, bullets, callout", "Write it", "Finding the words…"),
  T("recover", "Recovery plan", "Fourteen days to refill", "🛟",
    [CH("leave", "Time off available", ["None", "A long weekend", "One week", "Two weeks+"], "A long weekend"), TXT("nonneg", "Non-negotiables", "school run, on-call Tuesdays")],
    "Build a 14-day recovery plan given {leave} off and these non-negotiables: {nonneg}. Table (Day | Rest | Movement | Connection | Work limit), a checklist of things to switch off or hand over before it starts, bullets on what recovery actually feels like in week 1 versus week 2, and a callout on the difference between rest and numbing.",
    "table, checklist, bullets, callout", "Plan recovery", "Clearing space…"),
  T("talk", "Talk to my manager", "Prepare the conversation", "💬",
    [CH("goal", "I want", ["Lighter load", "Time off", "Change of role", "Just to flag it"], "Lighter load"), TXT("context", "Context", "3 people left, I'm covering two roles")],
    "Prepare a conversation with my manager asking for '{goal}', context: {context}. Steps for the conversation (open, evidence, ask, close), a quote with the opening three sentences, a table (Likely objection | Response), and a callout on what to put in writing afterwards.",
    "steps, quote, table, callout", "Prep me", "Rehearsing…")], MH)

APP("thanks_ledger", "Thanks Ledger", "A gratitude journal that notices more than you do", "Lifestyle", ["#F9A825", "#8D6E63", "#43A047"], "star",
 "Thanks Ledger turns a messy day into three specific things worth keeping, spots what keeps showing up across your entries, and writes the thank-you notes you've been meaning to send.",
 "You are a warm, unsentimental gratitude coach: you favour small, specific, sensory details over big abstractions and never scold anyone for a bad day.",
 "Notice what's already good", "Tell us a bit about your days so the prompts fit.", ["Three specifics from any day", "Patterns across your entries", "Thank-you notes worth sending"],
 [NAME, CH("time", "You journal at", ["Morning", "Lunch", "Evening", "Whenever"]), TXT("people", "People who matter", "Sam, Mum, my team")],
 [T("tonight", "Tonight's three", "Turn your day into three keepers", "✨",
    [LONG("day", "How was today", "dull meeting, nice coffee from Priya, rain on the walk home…"), CH("mood", "Mood right now", ["Good", "Flat", "Rough"], "Flat")],
    "From this day: {day} (mood: {mood}) draw out 3 gratitude entries as cards (title = the specific thing, meta = who or what made it happen), each 1–2 sentences naming a sensory detail. Then a quote with a one-line entry to copy into the journal, and if the mood is Rough, a callout that acknowledges the hard part before the gratitude.",
    "cards, quote, callout", "Find my three", "Sifting the day…"),
  T("thankyou", "Write a thank-you", "A note someone will keep", "💌",
    [TXT("to", "To", "my old teacher Mr Ade", True), LONG("why", "What they did", "wrote me a reference and checked in after"), CH("format", "Format", ["Text message", "Handwritten card", "Email", "Voice-note script"], "Text message")],
    "Write a thank-you to {to} for this: {why}, as a {format}. Quote with the full message (specific, no clichés, the right length for the format), bullets with 3 details from the story that could be added, and a kv (Best moment to send, Follow-up in a month).",
    "quote, bullets, kv", "Write it", "Choosing the words…"),
  T("rewind", "Weekly rewind", "Paste entries → what keeps showing up", "🔁",
    [LONG("entries", "This week's entries", "Mon: quiet morning, Sam's text… Tue: …")],
    "Read these entries: {entries}. Table (Theme | Times it appeared | Example), bullets on who and what shows up most, a text section on one thing that's clearly working and worth doing on purpose, and a quote with a single sentence to open next week's first entry.",
    "table, bullets, text, quote", "Rewind", "Reading back…"),
  T("savour", "Savour it", "Stretch a good moment", "🍯",
    [TXT("moment", "The moment", "Sunday breakfast with the kids", True)],
    "Guide a 3-minute savouring practice for {moment}: steps (notice, name, share, anchor) with exactly what to do at each, bullets on how to bring the moment back on a grey day, and a callout on why savouring beats chasing the next thing.",
    "steps, bullets, callout", "Savour", "Slowing down…"),
  T("jar", "30-day prompt jar", "A month of prompts", "🫙",
    [CH("flavour", "Flavour", ["Everyday", "Relationships", "Body & health", "Work", "Tough season"], "Everyday")],
    "Write 30 gratitude prompts with the '{flavour}' flavour as a table (Day | Prompt | Twist for a bad day). Keep prompts specific and answerable in one sentence, no two alike. End with bullets on how to use the jar when journaling feels forced.",
    "table, bullets", "Fill the jar", "Writing prompts…")], LIGHT)

APP("between_sessions", "Between Sessions", "Get more from therapy in the days between", "Health & Fitness", ["#5C6BC0", "#26A69A", "#FF8A65"], "book",
 "Between Sessions helps you prepare for and debrief therapy, build the exposure ladders and activity schedules your therapist assigned, and decode any worksheet you've been handed.",
 "You are a psychologically literate homework buddy: you support the plan the user's therapist set, never replace it, and stay concrete and encouraging.",
 "Make the homework stick", "Tell us about your therapy so the tools fit the approach.", ["Session prep and debrief", "Exposure ladders and activity plans", "Worksheet decoder from a photo"],
 [NAME, CH("approach", "Therapy type", ["CBT", "ACT", "DBT", "Psychodynamic", "EMDR", "Not sure"]), CH("freq", "Sessions", ["Weekly", "Fortnightly", "Monthly", "Between therapists"]), TXT("focus", "Working on", "social anxiety, panic on trains")],
 [T("prep", "Prep my session", "Don't waste the first ten minutes", "📝",
    [LONG("since", "Since last session", "had a panic on Tuesday, avoided the party, slept badly…"), TXT("avoid", "Thing I keep not saying", "the drinking")],
    "Prepare for the next session from: {since}, plus the thing I keep not saying: {avoid}. Bullets of 3–5 agenda items ordered by importance, a kv (Wins, Setbacks, Questions for my therapist, Homework status), a quote with one sentence to open the session with the hard topic, and a callout reminding me it's fine to read from notes.",
    "bullets, kv, quote, callout", "Prep me", "Gathering notes…"),
  T("debrief", "Debrief a session", "Capture it before it fades", "🧠",
    [LONG("notes", "What happened", "we talked about my dad, she suggested tracking avoidance…")],
    "Debrief this session: {notes}. Kv (Key insight, Thing that landed hard, Homework agreed, Question for next time), a checklist of the homework broken into small tickable tasks with a suggested day for each, and bullets on what to notice this week.",
    "kv, checklist, bullets", "Debrief", "Writing it down…"),
  T("ladder", "Exposure ladder", "Fear → ten rungs you can climb", "🪜",
    [TXT("fear", "The fear", "riding the tube at rush hour", True), CH("start", "Current comfort", ["Can't think about it", "Can imagine it", "Can do a tiny version", "Can do it with support"], "Can do a tiny version")],
    "Build a graded exposure ladder for {fear}, starting from '{start}'. Table (Rung | Situation | Predicted anxiety 0–100 | Safety behaviour to drop | Repeat until), steps for how to run a single exposure (before, during and after ratings), and a callout on when to pause and check with the therapist.",
    "table, steps, callout", "Build ladder", "Setting the rungs…"),
  T("activate", "Activity schedule", "Behavioural activation for a flat week", "📅",
    [TXT("enjoy", "Things I used to enjoy", "climbing, cooking for friends, drawing"), CH("energy", "Energy right now", ["Very low", "Low", "Some", "Okay"], "Low")],
    "Plan a behavioural-activation week with energy '{energy}' from these former joys: {enjoy}. Table (Day | Activity | Minutes | Type: pleasure / mastery / connection | Predicted enjoyment 0–10), bullets on how to shrink each activity if the day is bad, and a callout on rating actual enjoyment afterwards to compare with the prediction.",
    "table, bullets, callout", "Plan week", "Scheduling…"),
  T("worksheet", "Decode a worksheet", "Photo → what it wants from you", "📷",
    [PHOTO("Photo of the worksheet", "", True)],
    "Explain the worksheet in the photo: text on what it's for and which approach it comes from, steps to fill it in with an example line for each field, a callout on common mistakes people make with it, and bullets of questions to ask the therapist if it doesn't fit.",
    "text, steps, callout, bullets", "Explain it", "Reading the sheet…")], MH)

APP("body_calm", "Body Calm", "Release stress where your body actually holds it", "Health & Fitness", ["#00897B", "#D4E157", "#8E24AA"], "heart",
 "Body Calm works on stress from the neck down: progressive muscle relaxation scripts, a tension map from how you feel, shake-it-off movement resets and a body scan for sleep.",
 "You are a somatic-informed relaxation coach: unhurried, specific about muscles and breath, and clear that pain, numbness or trauma responses need a professional.",
 "Stress lives in the body too", "Tell us where you tense up and how long you have.", ["PMR scripts timed to your slot", "Tension map from how you feel", "Movement resets between meetings"],
 [NAME, CH("holds", "Where you hold tension", ["Jaw", "Neck & shoulders", "Chest", "Stomach", "Hands", "Lower back"], multi=True), CH("slot", "Usual time available", ["3 minutes", "10 minutes", "20 minutes"]), TXT("limits", "Injuries / limits", "bad knee")],
 [T("pmr", "Progressive relaxation", "Tense-and-release, timed", "🧘",
    [CH("minutes", "Minutes", ["5", "10", "15", "20"], "10"), CH("where", "Where are you", ["Lying down", "Sitting at a desk", "Public place"], "Sitting at a desk")],
    "Write a {minutes}-minute progressive muscle relaxation script for someone {where}, honouring the profile limits. Steps in order from feet to face (muscle group · tense seconds · release seconds · cue words), skipping groups that would be awkward {where}, a callout on not straining the areas listed as limits, and a quote with the closing lines to read slowly.",
    "steps, callout, quote", "Start script", "Softening…"),
  T("map", "Tension map", "Describe it → what to release first", "🗺️",
    [LONG("feel", "How your body feels right now", "jaw clenched, shallow breathing, shoulders up by my ears"), CH("cause", "Likely cause", ["Work", "Conflict", "Screen time", "Not sure"], "Not sure")],
    "Map this: {feel} (likely cause: {cause}). Table (Area | What you described | Probable pattern | 60-second release), steps for the single highest-payoff release right now, and a callout listing symptoms that are not stress and need a doctor (chest pain, numbness, one-sided weakness).",
    "table, steps, callout", "Map it", "Locating…"),
  T("shake", "Shake it off", "A movement reset in under 3 minutes", "🕺",
    [CH("state", "Right now I feel", ["Wired", "Frozen", "Foggy", "Angry"], "Wired"), CH("space", "Space", ["Desk chair", "Small room", "Outdoors"], "Small room")],
    "A movement reset for feeling '{state}' in a {space}, under 3 minutes: steps (movement · seconds · breathing pattern) matched to the state (discharge for wired or angry, gentle activation for frozen or foggy), bullets on how to tell it worked, and a callout on modifications for the profile's limits.",
    "steps, bullets, callout", "Reset me", "Shaking loose…"),
  T("scan", "Body scan for sleep", "Head to toe, lights off", "🌙",
    [CH("length", "Length", ["8 minutes", "15 minutes", "25 minutes"], "15 minutes"), TXT("busy", "What's on your mind", "presentation tomorrow")],
    "A {length} sleep body-scan script that gently parks '{busy}'. Text with a three-sentence opening that names the worry and sets it down, steps region by region with the words to say and the pause length, and a callout on what to do if the mind keeps returning to the worry.",
    "text, steps, callout", "Scan me", "Dimming lights…"),
  T("premeet", "Pre-meeting release", "Unclench before the hard thing", "⏱️",
    [TXT("next", "What's next", "difficult call with a client"), NUM("minutes", "Minutes you have", "2")],
    "In {minutes} minutes before '{next}': steps with a jaw, shoulder and breath release sequence sized to the time, a kv (Posture cue, Breath ratio, What to do with the hands), and a quote with one sentence to say to yourself walking in.",
    "steps, kv, quote", "Release", "Unclenching…")], MH)

APP("unsent_letters", "Unsent", "Write the letter you'll never send, then decide", "Lifestyle", ["#6D4C41", "#C2185B", "#FFCC80"], "note",
 "Unsent helps you write letters to people you can't or shouldn't send them to — an ex, a parent, your younger self, someone who's gone — then reflect on what came out and choose what, if anything, to actually say.",
 "You are a steady writing companion for difficult feelings: you help the user say the unsaid honestly, never rush them to forgiveness, and gently separate venting from action.",
 "Say it all, send nothing", "Who's on your mind? It stays private and unsent.", ["Letters that get the whole thing out", "Reflection on what's underneath", "A sendable version, only if you want one"],
 [NAME, CH("style", "Your writing voice", ["Blunt", "Measured", "Poetic", "Whatever comes"]), TXT("recipients", "People you might write to", "my dad, my ex, 16-year-old me")],
 [T("draft", "Draft the letter", "Get the whole thing out", "✉️",
    [TXT("to", "To", "my ex", True), CH("feeling", "Loudest feeling", ["Anger", "Grief", "Guilt", "Longing", "Relief", "Confusion"], "Anger"), LONG("raw", "What you want to say, unfiltered", "you left without explaining and I still…")],
    "Draft an unsent letter to {to} in the profile's voice, leading with {feeling}, from these raw notes: {raw}. Quote with the full letter (200–400 words, first person, specific, no softening the user didn't ask for), bullets naming 3 lines the user might want to sit with, and a callout that this stays unsent until they decide otherwise.",
    "quote, bullets, callout", "Write it out", "Uncapping the pen…"),
  T("underneath", "What's underneath", "Read the letter back", "🔍",
    [LONG("letter", "Paste your letter", "")],
    "Reflect on this unsent letter: {letter}. Kv (Primary feeling, Feeling under that, Unmet need, What the writer seems to want now), text with a gentle two-paragraph reading of what the letter is really about, bullets of 3 questions to journal on next, and a callout if anything suggests the writer needs support beyond a journal.",
    "kv, text, bullets, callout", "Read it back", "Listening…"),
  T("reply", "Reply as them", "A perspective-taking exercise", "🪞",
    [LONG("letter", "Your letter", ""), CH("version", "Version of them", ["Their best self", "Realistic", "How they'd actually respond"], "Realistic")],
    "Write the reply the '{version}' version of the recipient might send to this letter: {letter}. Quote with the reply (150–250 words in their plausible voice, not a fantasy apology unless their best self was chosen), bullets on what this shows about what the user can and can't get from them, and a callout that this is imagination, not prediction.",
    "quote, bullets, callout", "Hear a reply", "Imagining…"),
  T("sendable", "Make it sendable", "Only if you choose to", "📮",
    [LONG("letter", "Unsent version", ""), CH("goal", "Goal of sending", ["Set a boundary", "Ask for repair", "Close the door", "Reconnect"], "Set a boundary")],
    "Turn this unsent letter into something that could be sent in order to {goal}: {letter}. Quote with the sendable version (under 150 words, no accusations that invite a fight, one clear ask or statement), a table (Original line | Why it was cut or changed), and a callout with 3 questions to answer honestly before sending, including whether to wait 48 hours.",
    "quote, table, callout", "Make sendable", "Cooling it down…"),
  T("ritual", "Close the letter", "Burn, keep or bury it", "🕯️",
    [CH("mode", "I want to", ["Let it go", "Keep it safely", "Mark a chapter ending"], "Let it go")],
    "Design a small private ritual to {mode} for a finished unsent letter: steps (10 minutes max, safe, no flames indoors), a quote with a closing sentence to say aloud, and bullets on what to do if the feelings come back next week.",
    "steps, quote, bullets", "Close it", "Folding it up…")], MH)

APP("still_minutes", "Still Minutes", "Meditation scripts written for you, not a crowd", "Health & Fitness", ["#455A64", "#80CBC4", "#FFAB91"], "spark",
 "Still Minutes writes guided meditations for your exact time, goal and setting, fixes the classic problems (falling asleep, racing mind, boredom) and builds a four-week practice that grows with you.",
 "You are a secular, plain-spoken meditation teacher: you write scripts that can be read aloud or recorded, avoid mysticism, and treat fidgeting and doubt as normal.",
 "A practice that fits your life", "How much time do you actually have, and what gets in the way?", ["Scripts for your exact minutes", "Fixes for sleepy or racing minds", "A 4-week progression"],
 [NAME, CH("experience", "Experience", ["Never tried", "A few sessions", "On and off", "Daily-ish"]), CH("minutes", "Realistic daily minutes", ["3", "5", "10", "20"]), CH("obstacle", "Biggest obstacle", ["Falling asleep", "Racing thoughts", "Boredom", "No time", "Discomfort"])],
 [T("script", "Write a meditation", "Read it or record it", "🎙️",
    [CH("style", "Style", ["Breath", "Body scan", "Loving-kindness", "Open awareness", "Visualisation"], "Breath"), CH("length", "Length", ["3 min", "5 min", "10 min", "20 min"], "5 min"), TXT("intent", "Today's intention", "calm before my exam")],
    "Write a {length} {style} meditation script for the intention '{intent}', matched to the profile's experience. Steps where each step is a spoken passage followed by a pause length in seconds so the total fits {length}, a callout addressing the profile's biggest obstacle when it shows up mid-practice, and a quote with the closing sentence.",
    "steps, callout, quote", "Write script", "Settling in…"),
  T("fix", "Fix my practice", "Sleepy, restless, bored, sore", "🔧",
    [CH("problem", "What keeps happening", ["I fall asleep", "I can't stop thinking", "I get bored", "My back hurts", "I keep skipping it"], "I can't stop thinking"), TXT("detail", "Detail", "usually 3 minutes in, then I give up")],
    "The problem: {problem}; detail: {detail}. Text explaining in plain words why this happens and why it isn't failure, a table (Adjustment | How | Try it for), steps for the next session using the top adjustment, and a quote with a one-line reframe to remember.",
    "text, table, steps, quote", "Fix it", "Adjusting…"),
  T("walk", "Everyday mindfulness", "Practice without sitting", "🚶",
    [CH("activity", "During", ["Walking", "Washing up", "Commuting", "Eating", "Waiting in a queue"], "Walking"), NUM("minutes", "Minutes", "10")],
    "An informal {minutes}-minute mindfulness practice during {activity}: steps (what to attend to, in what order, with a phrase to return to), bullets on the moments most people drift, and a callout on staying safe while attending to the activity (traffic, hot water, other people).",
    "steps, bullets, callout", "Guide me", "Stepping out…"),
  T("month", "4-week progression", "Build the habit gently", "📈",
    [CH("goal", "Goal", ["Consistency", "Calmer days", "Better focus", "Sleep", "Less reactivity"], "Consistency")],
    "A 4-week meditation progression for '{goal}' starting from the profile's minutes and experience: table (Week | Daily minutes | Style | Focus | Milestone), a checklist of setup steps (time, place, cue, tracker), and a callout on what to do after a missed week.",
    "table, checklist, callout", "Build plan", "Mapping weeks…")], MH)

APP("sunday_scaries", "Sunday Scaries", "End the weekend without dreading Monday", "Health & Fitness", ["#7B1FA2", "#FFB300", "#00ACC1"], "calendar",
 "Sunday Scaries breaks the Sunday-night dread loop: it sorts what's actually on your plate, scripts a soft landing for Monday, builds a decompression ritual for hard days and a Friday shutdown that keeps work at work.",
 "You are a practical work-life coach: you take anticipatory anxiety seriously, turn vague dread into named tasks, and protect evenings and weekends without pretending the job doesn't exist.",
 "Take your weekend back", "A few details about your work rhythm.", ["Sunday reset in 20 minutes", "Monday-morning soft landing", "Friday shutdown ritual"],
 [NAME, CH("pattern", "Work pattern", ["Office 9–5", "Hybrid", "Remote", "Shifts", "Self-employed"]), CH("dread", "Dread usually starts", ["Saturday", "Sunday afternoon", "Sunday night", "Monday morning"]), TXT("worst", "Worst part of the week", "Monday 9am pipeline review")],
 [T("sort", "Sort the dread", "Brain dump → what's real", "🧹",
    [LONG("dump", "Everything in your head about the week", "inbox, the Jenkins thing, Priya's feedback, dentist, I haven't done the report…")],
    "Sort this Sunday brain dump: {dump}. Table (Item | Real task, vague worry or not mine | First 10-minute step | When), bullets naming the 1–2 items driving most of the dread and why, a checklist of the three things to do tonight (20 minutes total), and a callout on what to consciously leave until Monday.",
    "table, bullets, checklist, callout", "Sort it", "Untangling…"),
  T("monday", "Monday soft landing", "Script the first 90 minutes", "🌅",
    [TXT("first", "First thing on Monday", "pipeline review at 9"), CH("energy", "Expected energy", ["Low", "Medium", "High"], "Low")],
    "Plan Monday's first 90 minutes around '{first}' with {energy} energy: steps with clock times from waking to the first hard task, a kv (Night-before setup, Breakfast, First small win, Reward), and a quote with a one-sentence message to send a colleague or manager if you need a lighter start.",
    "steps, kv, quote", "Plan Monday", "Easing in…"),
  T("decompress", "Decompress a bad day", "Leave it at the door", "🛁",
    [LONG("what", "What happened", "got torn apart in the review, then two more fires"), NUM("minutes", "Minutes before you need to be present", "30")],
    "Help me decompress after: {what}, with {minutes} minutes before I need to be present for other people. Text with a two-paragraph honest reframe that neither minimises nor catastrophises, steps for a transition ritual sized to {minutes} minutes, and bullets on what to say if someone asks how your day was.",
    "text, steps, bullets", "Decompress", "Exhaling…"),
  T("friday", "Friday shutdown", "So Sunday has nothing to chew on", "🔒",
    [TXT("open", "Open loops", "two unanswered emails, unfinished deck")],
    "Design a 15-minute Friday shutdown that closes or parks: {open}. Checklist in order (each item under 3 minutes), a quote with the out-of-hours message or auto-reply to set, and a callout with the one rule for the weekend (e.g. no inbox on the phone) and how to make it easy to keep.",
    "checklist, quote, callout", "Shut down", "Closing tabs…"),
  T("weekend", "Rescue the weekend", "Plan one that actually restores", "🎈",
    [CH("mode", "This weekend I need", ["Rest", "Fun", "Get things done", "People"], "Rest"), TXT("fixed", "Fixed commitments", "kids' football Sat 10, dinner Sun")],
    "Plan a restoring weekend built around {mode} with these fixed commitments: {fixed}. Table (Slot | Saturday | Sunday) covering morning, afternoon and evening, bullets on protecting Sunday evening given the profile's dread pattern, and a callout on the difference between rest and scrolling.",
    "table, bullets, callout", "Plan weekend", "Clearing Sunday…")], MH)

APP("cool_down", "Cool Down", "Anger that doesn't wreck your relationships", "Health & Fitness", ["#0277BD", "#EF5350", "#546E7A"], "drop",
 "Cool Down helps you get through the hot moment, log what set you off, find the pattern behind your anger, and repair after you've said something you regret.",
 "You are a non-judgemental anger coach: anger is information, not a character flaw; you focus on the gap between feeling and action, and you say plainly when anger has tipped into risk to others.",
 "Turn heat into information", "Tell us where anger tends to show up for you.", ["90-second cool-down in the moment", "Anger log that finds patterns", "Repair scripts that actually land"],
 [NAME, CH("where", "Anger shows up most", ["Partner", "Kids", "Work", "Driving", "Family", "Online"], multi=True), CH("style", "Your style", ["Explode", "Go silent", "Sarcastic", "Stew for days"])],
 [T("now", "Cool down now", "Ninety seconds before you act", "🧊",
    [CH("level", "Heat level", ["Simmering", "Hot", "Boiling"], "Hot"), TXT("trigger", "What just happened", "he interrupted me again in front of everyone")],
    "Heat: {level}. Trigger: {trigger}. Steps for the next 90 seconds with exact timings (exit, body, breath, one sentence), a quote with the exact line to say to buy time without escalating, and a callout on the sign that it's not safe to stay in the room.",
    "steps, quote, callout", "Cool me down", "Dropping the heat…"),
  T("log", "Log an episode", "Trigger → thought → action → cost", "📓",
    [LONG("episode", "What happened", "kids ignored me three times, I shouted, everyone cried, felt awful"), CH("outcome", "How it ended", ["I walked away", "I shouted", "I said something cruel", "I went silent", "It got physical"], "I shouted")],
    "Log this episode: {episode} (it ended: {outcome}). Kv (Trigger, Hot thought, Underlying need, Action, Cost), a table (Earlier exit point | What it could have looked like), bullets on the one thing to try next time the same trigger appears, and a callout urging professional help if episodes involve threats or physical contact.",
    "kv, table, bullets, callout", "Log it", "Writing it down…"),
  T("patterns", "Find my patterns", "Paste several entries", "🔎",
    [LONG("entries", "Your log entries", "Mon: traffic, cut off, shouted alone… Wed: partner's tone…")],
    "Analyse these entries: {entries}. Table (Pattern | Triggers | Time of day or state | Frequency), bullets on the two conditions that make anger most likely (hunger, sleep, feeling unheard, etc.), steps for a 2-week experiment targeting the top condition, and a callout on how to know if it's working.",
    "table, bullets, steps, callout", "Find patterns", "Looking closely…"),
  T("repair", "Repair after blowing up", "Own it without grovelling", "🩹",
    [TXT("who", "Who", "my 9-year-old", True), LONG("said", "What you did or said", "yelled that she never listens and slammed the door")],
    "Write a repair for {who} after this: {said}. Quote with what to say (under 100 words, ownership without excuses, no 'but'), steps for the conversation including what to do if they're not ready, bullets on the follow-through that proves it, and a callout on what not to do (over-apologising, gifts instead of change).",
    "quote, steps, bullets, callout", "Write repair", "Finding the words…"),
  T("assert", "Say it without heat", "Turn a rant into a request", "🗣️",
    [LONG("rant", "The rant version", "I'm sick of being the only one who cleans anything in this house")],
    "Convert this rant into an assertive request: {rant}. Quote with the assertive version (observation, feeling, need, one specific ask), a table (Rant phrase | Assertive phrase | Why it lands better), and bullets on the best timing and place to say it.",
    "quote, table, bullets", "Rewrite it", "Cooling the words…")], MH + " If anger has become physical, seek help from a professional or a domestic-abuse service.")

APP("stoic_evening", "Stoic Evening", "Ancient journaling for modern nerves", "Lifestyle", ["#263238", "#BF360C", "#CFD8DC"], "moon",
 "Stoic Evening runs the classic Stoic practices as a daily journal: a morning premeditation, an evening review of what you controlled, a control sorter for any worry, and voluntary-discomfort challenges that build calm.",
 "You are a Stoic mentor in the spirit of Epictetus and Marcus Aurelius but in plain English: direct, kind, allergic to fatalism; you separate what is up to us from what isn't and never use Stoicism to excuse injustice or suppress feeling.",
 "What's up to you today?", "Tell us what you're facing so the practice is specific.", ["Morning premeditation, evening review", "Sort any worry by control", "Weekly discomfort challenges"],
 [NAME, TXT("season", "What this season of life is about", "new job, ageing parents"), CH("tradition", "Voice you prefer", ["Marcus (private, gentle)", "Epictetus (blunt)", "Seneca (letters)", "Mixed"])],
 [T("morning", "Morning premeditation", "Prepare for the day's people and problems", "🌄",
    [TXT("today", "Today holds", "budget meeting, dentist, dinner with in-laws")],
    "Write a morning premeditation for a day holding: {today}, in the profile's preferred voice. Text of 3–4 short paragraphs anticipating the difficult people and setbacks without dread, a kv (Up to me today, Not up to me today, Virtue to practise, Likely temptation), and a quote with one line to carry into the first hard moment.",
    "text, kv, quote", "Prepare me", "Sharpening…"),
  T("evening", "Evening review", "Three questions, honestly", "🌙",
    [LONG("day", "How the day went", "snapped at Sam, handled the meeting okay, avoided the email again")],
    "Run the Stoic evening review on: {day}. Kv (What I did well, Where I fell short, What I left undone), a table (Moment | What was in my control | What I did | What I'd do again), bullets with 2 amends or follow-ups for tomorrow, and a quote with a short line of self-forgiveness in the profile's voice.",
    "kv, table, bullets, quote", "Review my day", "Weighing the day…"),
  T("control", "Sort a worry", "Dichotomy of control, applied", "⚖️",
    [LONG("worry", "What's worrying you", "my presentation might bomb and I'll lose the promotion")],
    "Apply the dichotomy of control to: {worry}. Table (Element | Fully mine, partly mine or not mine | What I can do about it), text with a two-paragraph reframe that keeps the effort and drops the outcome-anxiety, steps for the next 24 hours on the fully-mine parts, and a callout on what to say to yourself if the feared outcome happens anyway.",
    "table, text, steps, callout", "Sort it", "Dividing…"),
  T("discomfort", "Discomfort challenge", "Voluntary hardship, safely", "🧗",
    [CH("area", "Area", ["Comfort", "Attention", "Money", "Social", "Physical"], "Comfort"), CH("intensity", "Intensity", ["Gentle", "Medium", "Bold"], "Gentle")],
    "Set a week of {intensity} voluntary-discomfort practices in the {area} area: table (Day | Practice | Duration | Reflection question), a callout on safety limits and who should skip physical or fasting practices, and bullets on what to notice by the end of the week.",
    "table, callout, bullets", "Set challenge", "Testing resolve…"),
  T("passage", "Decode a passage", "Paste a line, get it for today", "📜",
    [LONG("passage", "The passage", "You have power over your mind, not outside events…"), TXT("situation", "Your situation", "being ghosted by a friend")],
    "Interpret this passage: {passage}, for the situation: {situation}. Text with what the author most likely meant in context (2 paragraphs), bullets with 3 concrete applications to the situation, a callout on a common misreading of the line, and a quote with a modern one-sentence rewrite.",
    "text, bullets, callout, quote", "Decode", "Consulting…")], LIGHT)

APP("values_compass", "Values Compass", "Know what matters, then act like it", "Health & Fitness", ["#2E7D32", "#F57C00", "#1565C0"], "pin",
 "Values Compass uses acceptance-and-commitment tools to clarify what you actually value, spot when you're moving away from it, plan small committed actions and unhook from the thoughts that stop you.",
 "You are an ACT-informed coach: curious rather than corrective, focused on workable action over feeling better, and honest that values are chosen directions, not destinations.",
 "Which way is your life pointing?", "A quick sketch of your life areas helps.", ["Values clarification that's specific", "Toward vs away moves", "Unhook from sticky thoughts"],
 [NAME, CH("areas", "Areas that matter most", ["Relationships", "Work", "Health", "Learning", "Creativity", "Community", "Spirituality", "Play"], multi=True), TXT("stuck", "Where you feel stuck", "I keep saying I'll call my brother")],
 [T("clarify", "Clarify my values", "From stories, not slogans", "🧭",
    [LONG("moments", "Two moments you felt most alive, and one you felt ashamed of", "building the treehouse with Dad; the night we talked till 4; skipping Mum's birthday for work")],
    "Draw values from these moments: {moments}. Table (Value | Evidence from the stories | How it shows up when honoured | How it shows up when ignored), bullets with the top 3 values written as verbs ('being present with…'), a kv (Value most neglected, Smallest next action for it, Person to tell), and a callout on the difference between a value and a goal.",
    "table, bullets, kv, callout", "Clarify", "Reading the stories…"),
  T("moves", "Toward or away", "Audit a day against your values", "↔️",
    [LONG("day", "Yesterday, roughly", "scrolled till 1am, cancelled on Jo, good workout, bit my tongue at work")],
    "Classify yesterday: {day}. Table (Action | Toward or away move | Value involved | What the away move was avoiding), bullets on the pattern in the away moves, steps for one swap tomorrow that turns an away move into a toward move, and a quote with a non-judgemental sentence to say when noticing an away move.",
    "table, bullets, steps, quote", "Audit", "Plotting the moves…"),
  T("commit", "Committed action", "A week of tiny value-driven steps", "✅",
    [CH("value", "Value to act on", ["Connection", "Health", "Growth", "Creativity", "Contribution", "Honesty", "Adventure"], "Connection"), CH("size", "Step size", ["Tiny (2 min)", "Small (15 min)", "Real (1 hour)"], "Small (15 min)")],
    "Plan a week of committed actions for the value '{value}' at the '{size}' size, aimed at the profile's stuck area: checklist of 7 actions (one per day, each specific enough to know whether it happened), a table (Action | Likely obstacle | If-then plan), and a callout on what to do when you miss a day.",
    "checklist, table, callout", "Plan the week", "Setting course…"),
  T("unhook", "Unhook a thought", "Defusion for a sticky story", "🪝",
    [TXT("thought", "The thought", "I'm too old to change careers", True), CH("hook", "How it hooks you", ["Stops me acting", "Makes me argue with it", "Makes me avoid people", "Keeps me up at night"], "Stops me acting")],
    "The thought: '{thought}' — it {hook}. Steps through 4 defusion exercises (naming the story, thanking the mind, silly voice, leaves on a stream) with the exact words for this thought, a callout that the goal is workability not truth, bullets on how to act on the value while the thought is still there, and a quote with the thought rewritten as 'I'm having the thought that…'.",
    "steps, callout, bullets, quote", "Unhook", "Loosening the hook…"),
  T("willing", "Willingness plan", "Do the hard thing with the feeling", "🌊",
    [TXT("action", "The thing you're avoiding", "asking for a raise", True), CH("feeling", "Feeling that shows up", ["Anxiety", "Shame", "Sadness", "Boredom", "Anger"], "Anxiety")],
    "Build a willingness plan for '{action}' when {feeling} shows up: kv (Value served, Feeling expected 0–10, Room to make for it, First physical step), steps to do the action while carrying the feeling (before, during, after), bullets on what struggling with the feeling looks like versus willingness, and a callout on when avoidance is actually the wise choice.",
    "kv, steps, bullets, callout", "Make room", "Opening up…")], MH)
