from dsl import *

PREG = "General pregnancy information, not medical advice. Always follow your midwife or doctor. Seek urgent care for bleeding, severe pain, severe headache or vision changes, fever, fluid loss or reduced baby movements."
BIRTH = "Antenatal education, not medical advice. Your midwife or doctor's guidance overrides anything here; call your maternity unit if you are unsure whether to go in."
POST = "General postnatal information, not medical advice. Contact your midwife, GP or emergency services for heavy bleeding, fever, chest pain, calf pain, severe headache, or any thoughts of harming yourself or your baby."
LACT = "General lactation information, not medical advice. Confirm medications with a pharmacist or the LactMed / BfN databases, and see a clinician or IBCLC for persistent pain, fever, or feeding and weight concerns."
MENO = "General menopause information, not medical advice. HRT and other prescribing decisions belong with your doctor; report bleeding after 12 months without periods, very heavy bleeding, or chest pain promptly."
STRONG = "Fitness and nutrition information, not medical advice. Get clearance from your doctor before a new programme if you have osteoporosis, heart disease, prolapse or a recent injury; stop and seek help for chest pain, dizziness or sharp pain."
FAM = "Educational information about fertility awareness, not medical or contraceptive advice. Charting to avoid pregnancy requires proper instruction and consistent daily records; unclear signs mean treat the day as fertile."
TTC = "General fertility information, not medical advice. Do not start or stop medications without your doctor; see a GP or fertility specialist for personal assessment and testing."
IVF = "General information to support your treatment, not medical advice. Your clinic's written protocol and instructions always take precedence; call your clinic for any concern and emergency services for severe symptoms."
PELVIC = "General pelvic health information, not medical advice or a substitute for assessment by a pelvic health physiotherapist or doctor. Seek care for pain, bleeding, blood in urine, or sudden changes."

# 1 ─────────────────────────────────────────────────────────────────────────────
APP("bump_weekly", "Bump Weekly", "Your pregnancy, one week at a time", "Medical", ["#8E24AA", "#26A69A", "#FFB300"], "calendar",
 "Bump Weekly explains what's happening to you and the baby each week, checks whether a symptom is normal or needs a call, answers 'is this safe?' questions and preps you for every appointment.",
 "You are a calm, evidence-based midwife: reassuring but honest, clear about red flags, and never judgemental about food, work or worries.",
 "Congratulations — let's get organised", "Your due date and history shape every answer.", ["Week-by-week body & baby guide", "Normal-or-call symptom checker", "Appointment question lists"],
 [NAME, F("due", "Due date", "text", "14 March"), CH("pregnancy", "This pregnancy", ["First", "Second+", "Twins/multiples", "IVF"]), TXT("history", "Conditions / history", "asthma, previous C-section")],
 [T("week", "This week", "Body, baby, to-dos", "🗓️", [TXT("today", "Today's date", "19 September", True)],
    "Work out the current week from the profile's due date and today's date {today}. Sections: kv (week, trimester, baby size comparison, key development this week), text on what the user's body is doing this week and the common symptoms, a checklist of to-dos this week (appointments, tests, decisions, paperwork), and a callout on symptoms that should be reported to a midwife at this stage.", "kv, text, checklist, callout", "Show my week", "Counting weeks…"),
  T("safe", "Is this safe?", "Food, meds, activities, beauty", "✅", [TXT("thing", "What are you asking about", "sushi, hair dye, ibuprofen, hot yoga", True), PHOTO("Photo of the label or menu (optional)")],
    "Assess {thing} in pregnancy (use the photo of the label or menu if provided) for the profile's stage and history. Sections: a callout with the verdict (Generally fine / Fine with limits / Avoid / Ask your clinician) and a one-line reason, bullets on safer alternatives or how to make it safer, and a kv of the specific limits (amount, frequency, trimester notes). Say clearly when to check with a pharmacist or midwife.", "callout, bullets, kv", "Check it", "Checking…"),
  T("symptom", "Normal or call?", "Aches, spotting, headaches, swelling", "🩺", [LONG("symptom", "What's going on", "mild cramping since this morning, no bleeding"), CH("urgency", "How bad", ["Mild", "Moderate", "Severe"], "Mild")],
    "The user reports: {symptom} (severity: {urgency}) at the profile's stage. Sections: a callout with a triage level (Self-care & monitor / Call the midwife today / Go in now), text explaining the likely benign causes at this stage, bullets on self-care that helps, and a checklist of red flags that would change the level. Never diagnose; be clear that reduced movements, bleeding, severe headache, vision changes or sudden swelling always mean call.", "callout, text, bullets, checklist", "Check symptom", "Reviewing…"),
  T("appt", "Appointment prep", "Questions for your midwife or OB", "📋", [CH("type", "Appointment", ["Booking / first visit", "Scan", "Routine check", "Glucose test", "Birth planning", "Specialist"], "Routine check"), TXT("worries", "On your mind", "worried about weight gain, want to ask about VBAC")],
    "Prepare the user for a {type} appointment with concerns: {worries}. Sections: bullets of 8 prioritised questions to ask, a kv of what typically happens at this visit (tests, measurements, decisions), a checklist of what to bring and log beforehand (BP readings, symptoms, medications), and a quote with a one-sentence opener for raising the biggest worry.", "bullets, kv, checklist, quote", "Prep me", "Writing questions…"),
  T("relief", "Symptom relief", "Nausea, heartburn, back pain, insomnia", "🌿", [CH("issue", "Bothering you", ["Nausea", "Heartburn", "Back / pelvic pain", "Insomnia", "Constipation", "Leg cramps", "Fatigue"], "Nausea")],
    "Build a relief plan for {issue} at the profile's stage. Sections: steps to try today in order (cheapest and safest first), a table (Remedy | How | Evidence | Watch-outs) of 5 options including which over-the-counter options are usually considered pregnancy-compatible and must be confirmed with a pharmacist, and a callout on when the symptom needs a clinician.", "steps, table, callout", "Help me", "Finding relief…")], PREG)

# 2 ─────────────────────────────────────────────────────────────────────────────
APP("birth_ready", "Birth Ready", "Labour, birth and the bag — prepared, not scared", "Parenting", ["#AD1457", "#00897B", "#F9A825"], "heart",
 "Birth Ready writes your birth preferences, packs the hospital bag, coaches your birth partner, decodes contraction timing and builds a comfort toolkit for each stage of labour.",
 "You are a warm, experienced antenatal educator and doula: practical, unbiased about birth choices, honest that plans change, and never fear-mongering.",
 "Get ready for the big day", "Where and how you hope to give birth shapes the plan.", ["Birth preferences in plain language", "Partner cheat sheets", "Contraction & when-to-go-in guidance"],
 [NAME, CH("place", "Planned birth place", ["Hospital", "Birth centre", "Home", "Not sure"]), CH("hopes", "Hoping for", ["Unmedicated", "Epidural", "Water birth", "Planned caesarean", "VBAC", "Open to anything"], multi=True), TXT("partner", "Birth partner", "Sam (husband)")],
 [T("plan", "Birth preferences", "A one-page document for your team", "📝", [LONG("wishes", "Your wishes and worries", "dim lights, delayed cord clamping, scared of forceps…"), TXT("date", "Due date", "14 March")],
    "Draft a one-page birth preferences document for the profile from: {wishes} (due {date}). Sections: a quote containing the full document in first person with headings (Environment, Pain relief, Monitoring, Second stage, Third stage, Baby's first hour, If a caesarean is needed), then a checklist of preferences to confirm with the midwife before it's final, and a callout reminding that preferences are flexible and staff will explain any deviation.", "quote, checklist, callout", "Draft it", "Writing…"),
  T("bag", "Pack the bag", "Hospital bag, split by who carries it", "🎒", [CH("season", "Season", ["Summer", "Winter", "Mild"], "Mild"), CH("stay", "Expected stay", ["Day case / home birth", "1–2 nights", "3+ nights / caesarean"], "1–2 nights")],
    "Build a hospital bag list for a {stay} stay in {season}, at the profile's birth place. Sections: a checklist split into three labelled groups — Labour bag (for the room), Postnatal bag (for after) and Baby bag — with quantities, then a kv of documents and things to prepare at home (car seat fitted, maternity notes, snacks, phone numbers), and bullets of items people pack but never use.", "checklist, kv, bullets", "Pack it", "Packing…"),
  T("partner", "Partner cheat sheet", "What to do in each stage", "🤝", [CH("stage", "Stage", ["Early labour", "Active labour", "Transition", "Pushing", "First hours after"], "Active labour")],
    "Coach the profile's birth partner for {stage} of labour, matching the profile's hopes. Sections: steps for exactly what to do and say, a table (She says / does | It probably means | You do), a quote with 3 phrases that help and 3 to avoid, and a callout on when to call the midwife or press the buzzer.", "steps, table, quote, callout", "Coach partner", "Briefing…"),
  T("contractions", "Contraction check", "Timing → what stage, when to go in", "⏱️", [LONG("timing", "Your timings", "every 7 min, lasting 45s, for 1 hour; waters intact; manageable"), TXT("distance", "Minutes to birth place", "25")],
    "Interpret these contraction timings: {timing}, with {distance} minutes to the birth place, given the profile. Sections: a callout with the likely stage and a clear Stay home / Call now / Go in now verdict using standard guidance (e.g. 3 in 10 minutes lasting 60s, waters breaking, bleeding, reduced movements, feeling pushy), bullets on what to do in the meantime, and a kv of what to tell the triage line (timings, waters colour, movements, history).", "callout, bullets, kv", "Check timing", "Timing…"),
  T("comfort", "Comfort toolkit", "Positions, breathing, TENS, water", "🌊", [CH("wants", "Work with", ["Positions & movement", "Breathing", "Water", "TENS & massage", "Everything"], "Everything")],
    "Build a comfort toolkit focused on {wants} for the profile's hopes and birth place. Sections: cards (technique, meta = stage it suits · needs kit?), steps to practise the top two at home this week, a table of pain-relief options (Option | Where available | Pros | Cons | Can still move?) so choices are informed, and a callout that changing your mind on the day is fine.", "cards, steps, table, callout", "Build toolkit", "Gathering…")], BIRTH)

# 3 ─────────────────────────────────────────────────────────────────────────────
APP("fourth_tri", "Fourth Trimester", "Recovery for the parent, not just the baby", "Medical", ["#5C6BC0", "#EC407A", "#66BB6A"], "sun",
 "Fourth Trimester guides your own recovery after birth: healing by birth type, bleeding and pain checks, mood check-ins, scripts to ask for help, and a plan for the six-week check.",
 "You are a postnatal midwife and perinatal mental-health nurse in one: gentle, unhurried, frank about what's normal, and quick to name red flags.",
 "You just did something huge", "Tell us how you gave birth so recovery advice fits.", ["Healing plans by birth type", "Bleeding, pain & mood checks", "Scripts for asking for help"],
 [NAME, CH("birth", "Birth", ["Vaginal", "Vaginal with stitches", "Assisted (forceps / ventouse)", "Planned caesarean", "Emergency caesarean"]), TXT("born", "Baby born on", "2 September"), CH("feeding", "Feeding", ["Breast", "Bottle", "Mixed"])],
 [T("heal", "Recovery this week", "What's healing, what to do", "🩹", [TXT("today", "Today's date", "19 September", True), TXT("how", "How you're feeling", "sore, tired, stitches sting")],
    "Work out days or weeks postpartum from the profile's birth date and today {today}; the user feels: {how}. Sections: kv (stage, what is healing now, what bleeding usually looks like this week, sensible activity level), a checklist of daily care for the profile's birth type (wound or perineum care, pain-relief timing, bowel and bladder, rest), bullets on what to gently avoid, and a callout on red flags (heavy bleeding or clots, fever, wound changes, calf pain, chest pain, severe headache).", "kv, checklist, bullets, callout", "Show my week", "Checking in…"),
  T("check", "Is this normal?", "Bleeding, pain, wound, breasts, bladder", "🔎", [LONG("symptom", "What's happening", "bleeding got heavier again on day 10, bright red")],
    "Assess: {symptom} for the profile's birth type and timing. Sections: a callout with a level (Normal & monitor / Call midwife or GP today / Urgent care now) and a one-line reason, text on the likely explanations, bullets of what helps now, and a checklist of changes that should trigger an immediate call. Never diagnose; always err toward calling when unsure.", "callout, text, bullets, checklist", "Check", "Reviewing…"),
  T("mood", "Mood check-in", "Baby blues, anxiety, or more", "💛", [LONG("feelings", "How the last few days have felt", "crying a lot, can't sleep even when baby sleeps, don't feel bonded"), CH("sleep", "Sleep in 24h", ["Under 3h", "3–5h", "5h+"], "3–5h")],
    "Reflect on: {feelings}, with {sleep} of sleep. Sections: text that validates without minimising and distinguishes baby blues, postnatal depression or anxiety, and birth trauma in general terms, bullets of small things that help in the next 48 hours, a quote with one sentence the user can say to a partner or friend to ask for support, and a callout on when to contact a GP, midwife or crisis line today, including intrusive thoughts, thoughts of harming self or baby, or not sleeping at all.", "text, bullets, quote, callout", "Check in", "Listening…"),
  T("help", "Ask for help", "Scripts for partner, family, visitors, work", "🗣️", [CH("who", "Who", ["Partner", "Parents / in-laws", "Friends", "Employer", "Visitors"], "Partner"), TXT("need", "What you need", "someone to take the baby 6–8am so I can sleep")],
    "Write scripts to ask {who} for: {need}. Sections: a quote with a kind, direct message (text or spoken) followed by a firmer version to use if the first is brushed off, bullets of specific tasks to delegate this week, and a callout on setting visitor boundaries without guilt.", "quote, bullets, callout", "Write scripts", "Drafting…"),
  T("sixweek", "Six-week check prep", "Questions, contraception, exercise, sex", "📋", [TXT("concerns", "Your concerns", "leaking when I sneeze, sex sounds terrifying, want to run again")],
    "Prepare the user for the 6–8 week postnatal check with concerns: {concerns}. Sections: bullets of 8 prioritised questions, a table (Topic | Ask about | Why it matters) covering wound, bleeding, pelvic floor, mood, contraception, feeding, return to exercise and sex, a checklist of things to note beforehand, and a callout on what should not wait for the check.", "bullets, table, checklist, callout", "Prep me", "Preparing…")], POST)

# 4 ─────────────────────────────────────────────────────────────────────────────
APP("latch_lab", "Latch Lab", "Breastfeeding and pumping, without the guesswork", "Parenting", ["#0097A7", "#F06292", "#FFCA28"], "drop",
 "Latch Lab troubleshoots latch pain and supply worries, checks whether baby is getting enough, builds pumping schedules for going back to work, checks medications and handles blocked ducts and mastitis.",
 "You are an IBCLC-style lactation consultant: practical, non-judgemental about combination or formula feeding, precise about positioning, and clear when a problem needs hands-on help.",
 "Feeding, your way", "A few details make the advice fit your baby's age.", ["Latch & pain fixes", "Supply and pumping plans", "Medication and mastitis guidance"],
 [NAME, F("age", "Baby's age", "text", "3 weeks"), CH("feeding", "Currently", ["Exclusively breast", "Mixed", "Exclusively pumping", "Weaning"]), TXT("pump", "Pump (if any)", "Spectra S1")],
 [T("pain", "Fix the latch", "Pain, clicking, shallow latch", "🤱", [LONG("problem", "What's happening", "toe-curling pain at the start, nipple looks lipstick-shaped after"), PHOTO("Photo of the latch or nipple after a feed (optional)")],
    "Troubleshoot: {problem} for the profile's baby age (assess the photo if provided). Sections: text on the most likely causes ranked, steps for a deep-latch reset (positioning, baby-led attachment, breaking suction safely), a table (Sign | Suggests | Fix), and a callout listing signs that need an in-person lactation consultant or clinician (tongue-tie assessment, cracked or bleeding nipples, thrush, mastitis).", "text, steps, table, callout", "Troubleshoot", "Looking…"),
  T("supply", "Is baby getting enough?", "Nappies, weight, feeding pattern", "⚖️", [NUM("wet", "Wet nappies in 24h", "6"), NUM("feeds", "Feeds in 24h", "10"), TXT("weight", "Weight trend", "born 3.4kg, 3.3kg at day 5")],
    "Assess intake with {wet} wet nappies, {feeds} feeds per 24h and weight: {weight}, for the profile's baby age. Sections: a callout with the verdict (Reassuring / Watch closely / Get weighed and seen today) using standard nappy and weight-gain benchmarks for this age, kv of the expected numbers at this age, bullets of ways to boost supply if needed (frequency, breast compression, switch nursing, pumping after feeds), and a checklist of hunger versus satiety cues.", "callout, kv, bullets, checklist", "Assess", "Counting…"),
  T("pumping", "Pumping schedule", "Back to work, building a stash", "🍼", [TXT("hours", "Work hours / separation", "8:30–17:30 Mon–Fri, starting in 3 weeks", True), CH("goal", "Goal", ["Maintain supply", "Build a freezer stash", "Exclusively pump", "Wean off the pump"], "Maintain supply")],
    "Design a pumping plan for {hours} with goal {goal} for the profile's baby age and pump. Sections: table (Time | Where | Minutes | Expected ml range | Notes), steps for the first week of transition, a kv on milk storage (room, fridge, freezer, thawed, combining sessions), and a checklist of pumping-at-work rights and kit.", "table, steps, kv, checklist", "Build schedule", "Scheduling…"),
  T("meds", "Can I take this?", "Medication & breastfeeding", "💊", [TXT("med", "Medication or substance", "ibuprofen, sertraline, a glass of wine", True)],
    "Give general information on {med} while breastfeeding for the profile's baby age. Sections: a callout with the general compatibility category (Usually compatible / Use with care / Usually avoided / Ask a pharmacist) and the reasoning in one line, kv (how much passes into milk in general terms, timing relative to feeds, what to watch for in baby), bullets of usually-preferred alternatives, and a closing callout telling the user to confirm with a pharmacist or the LactMed / BfN resources, because this is not a prescription.", "callout, kv, bullets", "Check", "Checking…"),
  T("blocked", "Blocked duct or mastitis?", "Lumps, redness, fever", "🔥", [LONG("symptoms", "Symptoms", "hard tender lump upper left, no fever, started yesterday")],
    "Assess: {symptoms}. Sections: a callout distinguishing blocked duct, engorgement, mastitis and abscess signs in general terms with a level (Self-care / See a GP within 24h / Urgent), steps for current best-practice self-care (keep feeding normally, gentle lymphatic massage, cold, anti-inflammatories, avoid deep massage and over-pumping), bullets of what not to do, and a checklist of signs to seek care today (fever, flu-like feeling, spreading redness, no improvement in 24h).", "callout, steps, bullets, checklist", "Assess", "Checking…")], LACT)

# 5 ─────────────────────────────────────────────────────────────────────────────
APP("second_spring", "Second Spring", "Perimenopause and menopause, decoded", "Medical", ["#E64A19", "#7CB342", "#5E35B1"], "leaf",
 "Second Spring makes sense of perimenopause and menopause: decode your symptom diary, build a hot-flush plan, prepare for a hormone-therapy conversation, and manage brain fog and mood on hard days.",
 "You are a menopause specialist nurse: evidence-based, frank about HRT benefits and risks, never dismissive, and alert to symptoms that need a doctor rather than a hormone explanation.",
 "Not 'just your age'", "Where you are in the transition changes the advice.", ["Symptom diary analysis", "Hot-flush and hard-day plans", "HRT conversation prep"],
 [NAME, NUM("age", "Age", "48"), CH("stage", "Stage", ["Periods regular", "Periods changing", "No period 3–12 months", "No period 12+ months", "Surgical / medical menopause"]), TXT("treatment", "Current treatment", "none / oestrogen patch / SSRI")],
 [T("decode", "Decode my symptoms", "Paste a week or month of notes", "🔎", [LONG("diary", "Symptom diary", "Mon: 4 hot flushes, woke 3am, snappy; Tue: joint aches, forgot a meeting…")],
    "Analyse this diary: {diary} for the profile. Sections: a table (Symptom | Frequency | Likely link to hormones? | Other causes to rule out), bullets of patterns and triggers noticed (caffeine, alcohol, timing, cycle), a kv of the top 3 symptoms with one first-line action each, and a callout listing symptoms that are NOT typical menopause and need a GP (bleeding after 12 months, very heavy bleeding, chest pain, severe depression).", "table, bullets, kv, callout", "Analyse", "Reading…"),
  T("flush", "Hot-flush plan", "Fewer, shorter, less disruptive", "🔥", [CH("when", "Worst at", ["Night", "Work / day", "Both"], "Both"), TXT("triggers", "Known triggers", "red wine, spicy food, stress")],
    "Build a hot-flush plan for flushes worst at {when} with triggers {triggers}, for the profile. Sections: a checklist of environment and clothing fixes (layers, fabrics, bedding, fans, cooling kit), steps for a paced-breathing technique to use at the start of a flush, a table (Option | Type: lifestyle / non-hormonal / hormonal | Evidence | Discuss with) covering CBT, SSRIs/SNRIs, gabapentin, fezolinetant and HRT in general terms, and a callout on supplements with weak evidence.", "checklist, steps, table, callout", "Build plan", "Cooling down…"),
  T("hrt", "HRT conversation", "Prep for the appointment", "🩺", [LONG("situation", "Your situation & worries", "mum had breast cancer, migraine with aura, terrible sleep"), CH("goal", "You want to", ["Understand options", "Ask to start", "Review current dose", "Discuss stopping"], "Understand options")],
    "Prepare a menopause hormone therapy conversation for: {situation}, goal: {goal}, for the profile. Sections: text summarising in plain language what HRT is and how benefits and risks are generally weighed by age and years since menopause, a table (Option | Form | Typically suits | Common cautions) covering oestrogen routes, progestogen options, vaginal oestrogen and testosterone, bullets of 8 questions to ask, a quote with an opener that gets taken seriously, and a callout that prescribing decisions are the clinician's and depend on the full history.", "text, table, bullets, quote, callout", "Prep me", "Preparing…"),
  T("fog", "Brain-fog day plan", "Work through a foggy, anxious day", "🧠", [TXT("day", "What today holds", "two meetings, a deadline, school pick-up"), CH("feeling", "Feeling", ["Foggy", "Anxious", "Flat", "Irritable", "Wired & tired"], "Foggy")],
    "Plan a {feeling} day with: {day}. Sections: steps with clock-anchored blocks (single-tasking, breaks, protein, daylight, movement), bullets of memory scaffolds that work (externalise everything, one-list rule), a quote with a sentence to explain a lapse at work without over-apologising, and a callout on when persistent low mood or anxiety deserves its own conversation with a GP.", "steps, bullets, quote, callout", "Plan my day", "Clearing fog…"),
  T("vaginal", "Below the belt", "Dryness, urgency, painful sex, UTIs", "🌸", [CH("issue", "Main issue", ["Dryness / irritation", "Painful sex", "Urgency / frequency", "Recurrent UTIs", "Low libido"], "Dryness / irritation")],
    "Give plain, unembarrassed guidance on {issue} in menopause (genitourinary syndrome of menopause) for the profile. Sections: text on why it happens and why it rarely improves without treatment, a table (Option | How it works | Prescription? | Notes) covering moisturisers, lubricants, local vaginal oestrogen, DHEA / ospemifene, pelvic floor physio and libido approaches, steps to raise it with a GP in one sentence, and a callout on symptoms that need examination (bleeding, unusual discharge, blood in urine).", "text, table, steps, callout", "Tell me", "Answering…")], MENO)

# 6 ─────────────────────────────────────────────────────────────────────────────
APP("meno_strong", "Meno Strong", "Muscle, bone and metabolism after 45", "Health & Fitness", ["#C2185B", "#37474F", "#FFB300"], "dumbbell",
 "Meno Strong builds strength and bone-loading programmes, protein-first meal plans and joint-friendly cardio for the perimenopause years, then explains your DEXA and blood results in plain English.",
 "You are a strength coach and sports dietitian who specialises in midlife women: evidence-led, anti-diet-culture, lifts-first, and clear that a doctor owns the medical decisions.",
 "Stronger through the transition", "Your training history and limits shape the programme.", ["Progressive strength & bone plans", "Protein-first meal frameworks", "Result decoders for DEXA & bloods"],
 [NAME, CH("experience", "Lifting experience", ["None", "Some", "Regular"]), CH("kit", "Kit", ["Bodyweight only", "Dumbbells", "Bands", "Full gym"], multi=True), TXT("limits", "Joints / conditions", "knee arthritis, osteopenia, on HRT")],
 [T("program", "Strength block", "4 weeks, progressive", "🏋️", [CH("days", "Days per week", ["2", "3", "4"], "3"), NUM("minutes", "Minutes per session", "40")],
    "Write a 4-week strength block: {days} days per week, {minutes} minutes each, using the profile's kit, experience and limits. Sections: a table (Day | Exercise | Sets × reps | Load cue | Rest) for week 1, bullets on how weeks 2–4 progress, steps for perfect form on the two most important patterns (hip hinge and squat), and a callout on bone-loading impact work and what to skip with osteoporosis or prolapse until cleared.", "table, bullets, steps, callout", "Build block", "Loading plates…"),
  T("protein", "Protein-first day", "Hit 1.2–1.6 g/kg without a spreadsheet", "🥚", [NUM("weight", "Weight (kg)", "68"), CH("diet", "Diet", ["Anything", "Vegetarian", "Vegan", "Pescatarian"], "Anything")],
    "Design a protein-first eating day for {weight} kg on a {diet} diet. Sections: kv (daily protein target range in grams, per-meal target, fibre and calcium targets), a table (Meal | Food | Protein g | Calcium source?) hitting the target across 4 eating occasions, bullets of 6 grab-and-go options with protein grams, and a callout on why protein plus resistance training beats calorie-cutting at this stage.", "kv, table, bullets, callout", "Plan my plates", "Portioning…"),
  T("cardio", "Joint-friendly cardio", "Zone 2 + short intervals, no injuries", "🚴", [CH("likes", "You like", ["Walking", "Cycling", "Swimming", "Rowing", "Running", "Dancing"], multi=True), TXT("weekly", "Time available per week", "3 × 30 min")],
    "Build a weekly cardio plan using {likes} within {weekly}, respecting the profile's limits. Sections: table (Session | Type: zone 2 / intervals / mobility | Minutes | Effort cue | Notes), bullets on why short intervals matter for insulin sensitivity and VO2max in midlife, steps for one safe interval session, and a callout on pelvic floor and joint warning signs.", "table, bullets, steps, callout", "Plan cardio", "Pacing…"),
  T("results", "Decode my results", "DEXA, cholesterol, HbA1c, vitamin D", "📄", [LONG("results", "Paste results", "DEXA spine T-score -1.8, hip -1.2; LDL 3.9; HbA1c 41; vit D 38"), PHOTO("Photo of the report (optional)")],
    "Explain in plain English: {results} (or the report photo). Sections: a table (Marker | Your value | Typical range | What it suggests | Training or nutrition lever), text summarising the overall picture without diagnosing, bullets of 5 questions to ask the doctor, and a callout that interpretation and treatment (e.g. bone medication, statins) are the clinician's call.", "table, text, bullets, callout", "Decode", "Reading…"),
  T("changes", "Midlife body changes", "Weight, belly, plateaus, without crash diets", "⚖️", [LONG("story", "What's changed", "gained 5kg in 2 years, mostly belly, eating the same")],
    "Respond to: {story} for the profile. Sections: text explaining what shifts hormonally and metabolically (muscle loss, fat redistribution, sleep, insulin sensitivity) in a non-shaming way, a checklist of the 6 highest-leverage habits ranked, a kv of realistic expectations (rate of change, what to measure instead of the scale), and a callout on when to get thyroid, HbA1c and sleep apnoea checked.", "text, checklist, kv, callout", "Explain", "Thinking…")], STRONG)

# 7 ─────────────────────────────────────────────────────────────────────────────
APP("chart_wise", "Chart Wise", "Read your fertility signs with confidence", "Health & Fitness", ["#3949AB", "#EC407A", "#00ACC1"], "graph",
 "Chart Wise interprets your basal body temperature, cervical mucus and OPK results using sympto-thermal rules, confirms ovulation, explains confusing cycles and teaches each sign step by step.",
 "You are a certified fertility awareness educator: precise about the rules, honest about uncertainty, and clear that avoiding pregnancy with FAM needs proper instruction and consistent charting.",
 "Learn your cycle's language", "Your goal changes how conservatively signs are interpreted.", ["Chart interpretation with the rules shown", "OPK photo reading", "Sign-by-sign teaching"],
 [NAME, CH("goal", "Charting to", ["Conceive", "Avoid pregnancy", "Understand my health"]), NUM("cycle", "Typical cycle length (days)", "29"), CH("method", "Method", ["Sympto-thermal", "Temperature only", "Mucus only (Billings / Creighton)", "Just starting"])],
 [T("read", "Read my chart", "Paste temps + mucus + OPKs", "📈", [LONG("chart", "Cycle so far", "CD1–6 bleed; CD10 36.4 sticky; CD12 36.3 eggwhite; CD13 36.35 EW OPK+; CD14 36.7; CD15 36.75; CD16 36.8 dry…"), PHOTO("Photo of your chart app (optional)")],
    "Interpret this cycle: {chart} (use the chart photo too if given) under the profile's method and goal. Sections: kv (peak mucus day, temperature shift day, coverline value, ovulation estimate, confirmation status, fertile window opened / closed), text explaining exactly which rule was applied (e.g. 3-over-6 temperature rule, peak-plus-3 mucus rule) and what data is missing, a table (CD | Temp | Mucus | OPK | Interpretation) for the key days, and a callout with the conservative verdict for the profile's goal; for avoiding pregnancy, state clearly that an unclear chart means treat as fertile.", "kv, text, table, callout", "Interpret", "Reading chart…"),
  T("opk", "Read my OPK", "Photo of the strip", "🧪", [PHOTO("Photo of the ovulation test strip", "Good light, within the read window", True), TXT("cd", "Cycle day", "13")],
    "Read the ovulation test strip photo taken on cycle day {cd}. Sections: a callout with the read (Negative / Approaching / Positive / Invalid) and the test-versus-control comparison in one line, kv (what a positive means for timing, expected ovulation window, when to retest), bullets on common misreads (evaporation lines, dilute urine, PCOS false positives), and text on how this fits with the profile's other signs.", "callout, kv, bullets, text", "Read strip", "Comparing lines…"),
  T("today", "Where am I today?", "Fertile or not, from what you've seen", "📍", [NUM("cd", "Cycle day", "11"), TXT("signs", "Signs today", "creamy mucus, temp 36.4, no OPK yet")],
    "On cycle day {cd} with signs: {signs}, given the profile's cycle length, method and goal. Sections: a callout with today's status (Pre-fertile / Fertile / Peak / Post-ovulatory) and a confidence level, text on what to look for over the next 3 days, a checklist of what to record tonight, and bullets on timing for the profile's goal.", "callout, text, checklist, bullets", "Tell me", "Locating…"),
  T("learn", "Learn a sign", "Mucus, temperature, cervix, OPKs", "📚", [CH("sign", "Sign", ["Cervical mucus", "Basal temperature", "Cervical position", "OPKs", "Coverline & rules"], "Cervical mucus")],
    "Teach {sign} for the profile's method. Sections: steps for exactly how to observe and record it (timing, technique, wording), a table (What you see or measure | Category | Fertility meaning), bullets of the most common beginner mistakes, and a quote with a one-line memory hook.", "steps, table, bullets, quote", "Teach me", "Explaining…"),
  T("weird", "Weird cycle", "Delayed ovulation, split peaks, no shift", "❓", [LONG("issue", "What's odd", "two patches of eggwhite, no temp rise by CD24, spotting CD20")],
    "Explain this cycle oddity: {issue} for the profile. Sections: text on the likely explanations (stress-delayed ovulation, anovulatory cycle, illness, disturbed temps, short luteal phase), a table (Possibility | What the chart would show | What to do), a callout on the safe interpretation for the profile's goal, and bullets on when repeated patterns are worth discussing with a doctor (e.g. cycles over 35 days, luteal phase under 10 days, mid-cycle bleeding).", "text, table, callout, bullets", "Explain", "Puzzling…")], FAM)

# 8 ─────────────────────────────────────────────────────────────────────────────
APP("conceive_kit", "Conceive Kit", "Trying for a baby, with a plan and less panic", "Health & Fitness", ["#2E7D32", "#F48FB1", "#FDD835"], "star",
 "Conceive Kit turns trying to conceive into a calm plan: preconception checklists for both of you, timing for this cycle, an honest two-week-wait companion, sperm-health basics and when-to-get-help guidance.",
 "You are a reproductive health nurse and coach: warm, science-first, inclusive of all couples and solo parents, and honest that most healthy couples take up to a year.",
 "Let's make a plan", "A little context keeps the advice realistic.", ["Preconception checklists for both", "Cycle timing without obsession", "Two-week-wait sanity"],
 [NAME, NUM("age", "Your age", "33"), TXT("trying", "Trying since", "March"), CH("situation", "Situation", ["Partner with sperm", "Donor / solo", "Same-sex couple", "Known fertility issue"])],
 [T("prep", "Preconception checklist", "3 months out, for both", "✅", [CH("who", "For", ["Me", "Partner", "Both"], "Both"), TXT("health", "Health notes", "on sertraline, vegan, partner smokes")],
    "Build a 3-month preconception checklist for {who} with health notes: {health}, for the profile. Sections: a checklist of medical to-dos (folic acid 400 mcg or higher-dose if indicated, vaccines, medication review, cervical screening, dental), a second checklist of lifestyle to-dos per person (alcohol, smoking, caffeine limits, sleep, heat exposure for sperm), a table (Supplement | Who | Dose, general | Why), and a callout on medications that must not be stopped without a doctor.", "checklist, table, callout", "Build checklist", "Preparing…"),
  T("timing", "This cycle's timing", "When to try, without a spreadsheet", "📅", [TXT("lmp", "First day of last period", "1 September", True), NUM("length", "Usual cycle length", "28"), CH("style", "Approach", ["Every 1–2 days in the window", "Every other day", "Just tell me the best 3 days"], "Every 1–2 days in the window")],
    "From last period {lmp} and a {length}-day cycle, with approach {style}. Sections: kv (estimated ovulation date, fertile window dates, best 3 days, earliest sensible test date), a table (Date | Fertility | Try? | Notes), bullets on what raises odds (sperm-friendly lubricant, not saving up, OPK timing) and what doesn't (positions, legs up), and a callout that irregular cycles need sign-based tracking instead of calendar maths.", "kv, table, bullets, callout", "Calculate", "Counting days…"),
  T("tww", "Two-week wait", "Symptom-spotting, honestly", "⏳", [NUM("dpo", "Days past ovulation", "8"), LONG("feeling", "What you're noticing / feeling", "sore boobs, cramping, googling everything", False)],
    "Support the two-week wait at {dpo} days past ovulation with: {feeling}. Sections: text that is honest that progesterone causes identical symptoms whether or not pregnant, kv (earliest reliable test day, what hCG does day by day in general terms, when a faint line is meaningful), a checklist of things to do instead of symptom-spotting, and a quote with a kind message to self for today.", "text, kv, checklist, quote", "Get me through", "Waiting with you…"),
  T("help", "When to get help", "Timelines, tests, first appointment", "🩺", [LONG("story", "Your story", "trying 9 months, cycles 35–45 days, partner is 41")],
    "Assess: {story} for the profile. Sections: a callout with the standard guidance for when to seek help (12 months under 35, 6 months at 35 and over, sooner with known issues or irregular cycles) applied to this case, a table (Test | Who | What it checks | When in cycle) covering day-3 hormones, AMH, mid-luteal progesterone, semen analysis, tubal checks and thyroid, bullets of 8 questions for the first appointment, and steps to get the referral (what the GP needs, what to bring).", "callout, table, bullets, steps", "Assess", "Reviewing…"),
  T("sperm", "Sperm health basics", "For the partner or donor conversation", "🧬", [TXT("habits", "Their habits", "cycling 10h a week, hot tubs, 4 beers a night, vapes")],
    "Give sperm-health guidance for: {habits}. Sections: a table (Habit | Effect on sperm, with evidence strength | Change | Time to see effect, roughly 3 months), a checklist of the top 6 changes ranked, kv on what a semen analysis measures and general reference ranges, and a callout that supplements are not a substitute for a semen analysis if it has been a while.", "table, checklist, kv, callout", "Advise", "Reviewing…")], TTC)

# 9 ─────────────────────────────────────────────────────────────────────────────
APP("ivf_companion", "IVF Companion", "Your cycle, your protocol, one calm place", "Medical", ["#00838F", "#8E24AA", "#FF8A65"], "pill",
 "IVF Companion explains each stage of fertility treatment, turns your clinic protocol into a day-by-day schedule, checks side effects, preps transfer day and decodes scan, embryo and hCG results.",
 "You are a fertility nurse specialist: organised, warm, precise about protocols but always deferring to the user's clinic, and mindful of how emotionally hard treatment is.",
 "One step at a time", "Your treatment type shapes the schedule and advice.", ["Protocol → daily schedule", "Side-effect checks", "Transfer & results support"],
 [NAME, CH("treatment", "Treatment", ["IVF", "ICSI", "IUI", "Frozen embryo transfer", "Egg freezing", "Donor cycle"]), CH("cycle", "Cycle number", ["1st", "2nd", "3rd+"]), TXT("notes", "Diagnosis / notes", "low AMH, endometriosis, male factor")],
 [T("schedule", "Build my schedule", "Paste the protocol", "💉", [LONG("protocol", "Clinic protocol / instructions", "Gonal-F 225 from day 2, Cetrotide from day 6, scan day 8, trigger when 3 follicles over 17mm…"), TXT("start", "Start date", "3 October")],
    "Turn this protocol into a schedule starting {start}: {protocol}. Sections: a table (Date | Day | Medication & dose | Time | Appointment or test | Notes), a checklist of supplies and storage (fridge items, sharps bin, pen needles, swabs), steps for injection technique and site rotation, and a callout that the clinic's written instructions override this and to call the clinic if anything conflicts.", "table, checklist, steps, callout", "Build schedule", "Organising…"),
  T("explain", "Explain this stage", "What's happening and why", "📖", [CH("stage", "Stage", ["Down-regulation", "Stimulation", "Monitoring scans", "Trigger", "Egg collection", "Fertilisation & embryo updates", "Transfer", "Luteal support", "Two-week wait"], "Stimulation")],
    "Explain {stage} for the profile's treatment and cycle number. Sections: text on what happens and why, kv (typical duration, what the clinic measures, what good looks like in general terms, common feelings), bullets of practical tips, and a callout on what to phone the clinic about at this stage.", "text, kv, bullets, callout", "Explain", "Explaining…"),
  T("side", "Side-effect check", "Bloating, pain, headaches, mood", "🌡️", [LONG("symptom", "What you're feeling", "very bloated 3 days after collection, hard to breathe lying flat, weight up 2kg")],
    "Assess: {symptom} for the profile's treatment. Sections: a callout with a level (Expected, self-care / Call the clinic today / Emergency now), text on the likely cause, bullets of what helps, and a checklist of OHSS and other red flags (rapid weight gain, breathlessness, severe pain, low urine output, calf swelling).", "callout, text, bullets, checklist", "Check", "Reviewing…"),
  T("transfer", "Transfer day prep", "What to do, what not to worry about", "🌱", [TXT("date", "Transfer date", "17 October"), CH("type", "Embryo", ["Fresh", "Frozen", "Not sure"], "Frozen")],
    "Prepare for a {type} embryo transfer on {date} for the profile. Sections: a checklist for the 48h before (medications, bladder timing, what to wear, what to bring), kv (what happens in the room, how long, what you'll be told), bullets of evidence-based do's and don'ts afterwards (normal activity is fine; bed rest is not needed), and a quote with a grounding phrase for the procedure.", "checklist, kv, bullets, quote", "Prep me", "Preparing…"),
  T("results", "Decode results", "Scans, embryo grades, beta hCG", "🔬", [LONG("results", "What the clinic said", "8 eggs, 6 mature, 4 fertilised, day 5: one 4AA, one 3BB")],
    "Explain in plain English: {results} for the profile. Sections: a table (Item | Your number or grade | What it means | Typical range), text on what this suggests for next steps without promising outcomes, bullets of questions to ask the embryologist or nurse, and a callout that grades and numbers are imperfect predictors and the clinic makes the decisions.", "table, text, bullets, callout", "Decode", "Interpreting…")], IVF)

# 10 ────────────────────────────────────────────────────────────────────────────
APP("core_and_floor", "Core & Floor", "Pelvic floor, core and bladder — rebuilt properly", "Health & Fitness", ["#6D4C41", "#26C6DA", "#FF7043"], "shield",
 "Core & Floor builds pelvic floor and deep-core programmes, analyses your bladder diary, guides a diastasis recti self-check, adapts exercise for leaks and prolapse, and preps you for a pelvic health physio visit.",
 "You are a pelvic health physiotherapist: precise about technique, matter-of-fact about leaks, prolapse and pain, and firm that persistent symptoms deserve an in-person assessment.",
 "Leaks and pressure aren't just part of it", "Your situation shapes what's safe and useful.", ["Pelvic floor programmes with real cues", "Bladder diary analysis", "Prolapse-safe exercise swaps"],
 [NAME, CH("stage", "Stage", ["Pregnant", "Postpartum under 1 year", "Postpartum 1 year+", "Perimenopause / menopause", "Not related to birth"]), CH("issues", "Issues", ["Leaking with cough / sneeze / jump", "Urgency", "Heaviness / prolapse", "Pain with sex", "Diastasis recti", "Constipation", "Tailbone / pelvic pain"], multi=True), TXT("physio", "Seen a pelvic physio?", "no / yes, 2 years ago")],
 [T("program", "Pelvic floor programme", "4 weeks, with cues that work", "🎯", [CH("type", "Main goal", ["Strengthen (leaks)", "Relax (tightness, pain)", "Coordinate (pressure, prolapse)"], "Strengthen (leaks)"), NUM("minutes", "Minutes per day", "10")],
    "Write a 4-week programme to {type} in {minutes} minutes per day for the profile. Sections: steps to find and feel a correct contraction and a full relaxation (cues, positions, and wrong cues like breath-holding or glute squeezing), a table (Week | Exercise | Hold / relax | Reps | Position), bullets on integrating it into daily life (the knack before coughing or lifting), and a callout on when self-guided work is not enough (no change in 6 weeks, pain, prolapse symptoms).", "steps, table, bullets, callout", "Build programme", "Engaging…"),
  T("bladder", "Bladder diary", "Paste 24–72h of drinks and toilet trips", "💧", [LONG("diary", "Diary", "7:00 coffee 250ml; 7:30 wee; 9:00 wee, urgent; 10:00 tea; 10:40 wee, small…")],
    "Analyse this bladder diary: {diary} for the profile. Sections: kv (daily fluid total, number of voids, voids per night, longest gap, urgency episodes, estimated bladder capacity trend), a table (Pattern | Evidence | Likely driver | Fix), steps for a bladder-training plan with target gaps for the next 2 weeks, bullets on drink timing and irritants, and a callout on when to see a doctor (blood in urine, pain, sudden change, UTI signs).", "kv, table, steps, bullets, callout", "Analyse", "Reading diary…"),
  T("dr", "Diastasis check", "Self-check + deep-core rehab", "🤰", [TXT("finding", "Your self-check", "2 fingers wide above navel, feels soft, doming when I sit up"), PHOTO("Photo of your belly during a gentle head lift (optional)")],
    "Interpret the self-check: {finding} (and the photo if provided) for the profile. Sections: steps for a correct self-check to confirm (position, where to press, what to note: width, depth, tension), a callout with the likely category (functional gap vs needs assessment) and why tension matters more than width, a table (Week | Exercise | Sets × reps | Cue) for a 4-week deep-core progression, and bullets of movements to modify for now (and how) rather than avoid forever.", "steps, callout, table, bullets", "Check", "Assessing…"),
  T("safe", "Can I do this?", "Exercise, lifting, running with symptoms", "🏃", [TXT("activity", "Activity", "return to running, CrossFit, carrying a toddler upstairs", True)],
    "Assess {activity} for the profile's stage and issues. Sections: a callout with a verdict (Go / Modify / Not yet, build to it), a table (Version | Modification | Why | Progress when…), a checklist of readiness tests (e.g. for running: single-leg hop, 30 jumps, no leaking or heaviness), and bullets on breathing and pressure management during lifts.", "callout, table, checklist, bullets", "Assess", "Checking…"),
  T("visit", "Pelvic physio visit", "What happens, what to ask", "🩺", [LONG("story", "Your story in a few lines", "leaking since second baby 2 years ago, worse on the trampoline, avoid running")],
    "Prepare for a pelvic health physiotherapy appointment with: {story}. Sections: text on what a first assessment usually involves (history, external and, with consent, internal exam, what you can decline), bullets of 8 questions to ask, a checklist of what to track for a week beforehand, a quote with a one-line summary to open the appointment, and a callout on how to find a qualified pelvic physio and what a GP referral needs.", "text, bullets, checklist, quote, callout", "Prep me", "Preparing…")], PELVIC)
