from dsl import *
FIT = "Not medical advice. Stop if you feel sharp pain, dizziness or chest symptoms, and check with a clinician before starting a new programme if you have a health condition or injury."
REHAB = "Rehab Road supports, and never replaces, the plan from your physiotherapist or doctor. It does not diagnose. Stop and seek care for numbness, sudden swelling, night pain, fever, or pain that keeps getting worse."

# ---------------------------------------------------------------- 1. Kettlebells
APP("kettle_coach", "Iron Bell", "Kettlebell sessions built around the bells you own", "Health & Fitness", ["#37474F", "#FF6F00", "#00897B"], "flame",
 "Iron Bell programmes kettlebell training around the exact bells you own: swings, get-ups, presses, snatches and complexes, with form checks, a path to the next bell size and honest session reviews.",
 "You are a hardstyle kettlebell instructor: technique-first, tension-aware, allergic to sloppy swings; you prescribe in sets, reps, bell kilograms and rest in seconds.",
 "Which bells do you own?", "Iron Bell plans every session around your actual weights and minutes.", ["Sessions from your exact bells", "Swing, press and get-up form fixes", "A path to the next bell size"],
 [NAME, TXT("bells", "Bells you own (kg)", "12, 16, 24"), CH("level", "Level", ["New to bells", "Can swing and press", "Snatch and get-up comfortable"]), CH("goal", "Main goal", ["Strength", "Conditioning", "Fat loss", "Simple daily practice", "Athletic power"])],
 [T("session", "Today's session", "Built from your bells and minutes", "🔔",
    [CH("minutes", "Minutes", ["15", "25", "40"], "25"), CH("focus", "Focus", ["Full body", "Swings and hinge", "Press and pull", "Conditioning", "Grinds (slow strength)"], "Full body"), TXT("note", "Anything to work around", "sore lower back, only one 16")],
    "Write a {minutes}-minute kettlebell session with focus '{focus}' using only the profile bells, working around: {note}. Sections: steps for a 4-minute warm-up (halos, hip hinges, goblet squat pry), a table for the main work (Exercise | Bell kg | Sets x reps | Rest s | Cue), bullets on tempo and breathing, and a callout on when to drop a bell size mid-session.",
    "steps, table, bullets, callout", "Build session", "Chalking up…"),
  T("form", "Check my form", "Photo or description of a swing, press or get-up", "📷",
    [PHOTO("Photo mid-rep (optional)"), CH("move", "Movement", ["Swing", "Clean", "Press", "Snatch", "Turkish get-up", "Goblet squat"], "Swing"), TXT("issue", "What feels off", "bell bangs my forearm on cleans")],
    "Coach the {move} from the photo (if one was given) and this description: {issue}. Sections: bullets of the 3 most likely faults ranked by likelihood, steps for one corrective drill with reps, a table (Fault | What it looks like | Fix), and a callout on the safety cue that matters most for the {move}.",
    "bullets, steps, table, callout", "Coach me", "Watching the arc…"),
  T("complex", "Build a complex", "Chains and flows without putting the bell down", "🔗",
    [CH("count", "Bells in hand", ["Single", "Double"], "Single"), CH("style", "Style", ["EMOM", "Ladder", "Chain", "Flow", "AMRAP"], "Chain"), NUM("rounds", "Rounds", "5")],
    "Design a {count}-bell {style} complex for {rounds} rounds at the profile level and goal. Sections: kv (bell weight to use, work time, rest, total time), steps listing each movement in order with reps and the transition cue, a callout on grip fatigue and when to break the set, and bullets for a lighter and a heavier variant.",
    "kv, steps, callout, bullets", "Design", "Chaining moves…"),
  T("nextbell", "Earn the next bell", "Bridge the gap to a heavier kettlebell", "⬆️",
    [CH("lift", "Lift", ["Swing", "Press", "Snatch", "Get-up", "Front squat"], "Press"), NUM("target", "Target bell (kg)", "24")],
    "Plan the jump to a {target} kg bell on the {lift} from the profile bells. Sections: a table for a 6-week bridge (Week | Sessions | Sets x reps | Bell kg | Assistance work), a checklist of readiness tests to pass before the first attempt, bullets on technique changes a heavier bell demands, and a callout on shoulder and lower-back warning signs.",
    "table, checklist, bullets, callout", "Plan the jump", "Sizing up…"),
  T("review", "Review my week", "Paste your training log", "📓",
    [LONG("log", "This week's sessions", "Mon: 100 swings @24 in 5 min, 5 get-ups each side @16…")],
    "Review this kettlebell log against the profile goal: {log}. Sections: bullets of what is progressing, a table (Lift | Volume this week | Trend | Next week), a callout on the biggest risk (grip, lower back, overusing one pattern), and a quote with one technical cue to carry into next week.",
    "bullets, table, callout, quote", "Review", "Counting swings…")], FIT)

# ---------------------------------------------------------------- 2. Calisthenics skills
APP("gravity_gym", "Gravity Gym", "Pull-ups, handstands and levers, one rung at a time", "Health & Fitness", ["#1A237E", "#FFC400", "#26C6DA"], "star",
 "Gravity Gym is a calisthenics coach that maps the road from zero pull-ups to muscle-ups, handstands, front levers and pistol squats, with skill sessions, photo form checks and plateau fixes.",
 "You are a calisthenics coach with a gymnastics background: patient about progressions, strict on form, and clear that skills are earned with consistency, not intensity.",
 "Where are you on the bar?", "Your current numbers set the starting rung of every progression.", ["Progression trees for every skill", "Sessions for bar, rings or floor", "Fix a stalled skill"],
 [NAME, CH("gear", "Equipment", ["Pull-up bar", "Rings", "Parallettes", "Dip bars", "Resistance bands", "Floor only"], multi=True), TXT("numbers", "Current numbers", "3 pull-ups, 10 push-ups, 20 s hollow hold"), CH("days", "Training days/week", ["2", "3", "4", "5"])],
 [T("roadmap", "Skill roadmap", "Every rung from where you are to the skill", "🗺️",
    [CH("skill", "Skill", ["First pull-up", "Muscle-up", "Handstand", "Front lever", "Back lever", "Pistol squat", "L-sit", "Planche lean"], "Handstand")],
    "Build the progression road to a {skill} from the profile numbers and equipment. Sections: steps listing each progression rung in order with the hold time or rep target needed to graduate, a table (Rung | Sets x reps or secs | Sessions per week | Typical weeks), bullets on prerequisite strength or mobility, and a callout on the most common way people get stuck on this skill.",
    "steps, table, bullets, callout", "Map it", "Charting rungs…"),
  T("session", "Today's skill session", "Skill work while fresh, then strength", "🤸",
    [CH("minutes", "Minutes", ["20", "35", "50"], "35"), CH("emphasis", "Emphasis", ["Push", "Pull", "Legs and core", "Handstand", "Full body"], "Full body")],
    "Write a {minutes}-minute calisthenics session with emphasis '{emphasis}' for the profile equipment and numbers. Sections: steps for a wrist, shoulder and scapula warm-up, a table for the session (Block | Exercise | Sets x reps or secs | Rest | Form cue) with skill work first, bullets on how to scale each exercise up or down, and a callout on stopping a set when form breaks.",
    "steps, table, bullets, callout", "Build session", "Finding the bar…"),
  T("form", "Check my form", "Photo of a hold or rep", "📷",
    [PHOTO("Photo at the hardest point of the rep", "", True), TXT("move", "Movement", "tuck front lever", True)],
    "Assess the {move} in the photo. Sections: bullets on body position (scapula, hips, elbows, feet), a table (Fault | Why it matters | Drill to fix), steps for one corrective drill with sets and reps, and a callout if the position suggests stepping back a rung.",
    "bullets, table, steps, callout", "Assess", "Studying lines…"),
  T("stuck", "Break a plateau", "Stalled reps or a skill that will not come", "🧱",
    [TXT("stall", "What is stuck", "stuck at 8 pull-ups for 2 months", True), TXT("tried", "What you have tried", "greasing the groove, weighted sets")],
    "Diagnose this plateau: {stall}. Already tried: {tried}. Sections: bullets ranking the likely causes (volume, frequency, weak link, recovery, technique), a table of 3 four-week fixes (Approach | What changes | How to run it | Expect), steps for the single best fix, and a callout on when a plateau is really a sleep or recovery problem.",
    "bullets, table, steps, callout", "Diagnose", "Loosening the bolt…"),
  T("test", "Test day", "Re-measure the profile numbers", "📏", [],
    "Design a test day to re-measure the profile numbers and set the next 8 weeks. Sections: steps for the test order with rest between tests, a table (Test | Standard for the next skill | Your last number | Pass or retest), a checklist of what to record, and a callout on not testing while fatigued or sore.",
    "steps, table, checklist, callout", "Plan test day", "Setting the bar…")], FIT)

# ---------------------------------------------------------------- 3. Powerlifting
APP("third_attempt", "Third Attempt", "Programming and meet prep for squat, bench, deadlift", "Health & Fitness", ["#B71C1C", "#263238", "#FFD600"], "graph",
 "Third Attempt writes powerlifting blocks from your current maxes, picks meet-day attempts and warm-up timing, fixes sticking points and plans a weight cut that will not cost you kilos on the platform.",
 "You are a powerlifting coach who has handled hundreds of meets: percentage-based, RPE-literate, conservative with openers and honest about what a lifter needs versus what they want.",
 "What are your numbers?", "Current maxes and your federation shape every block and attempt.", ["Blocks from your real maxes", "Attempt selection and warm-up timing", "Sticking-point fixes"],
 [NAME, TXT("maxes", "Current maxes (kg)", "S 140 / B 90 / D 180"), CH("exp", "Experience", ["First year", "1–3 years", "3+ years", "Competed before"]), TXT("fed", "Federation and class", "IPF, 83 kg, raw")],
 [T("block", "Build a block", "Percentage or RPE, 4–8 weeks", "📈",
    [CH("weeks", "Length (weeks)", ["4", "6", "8"], "6"), CH("style", "Loading", ["Percentage", "RPE", "Mixed"], "Mixed"), CH("days", "Days/week", ["3", "4", "5"], "4")],
    "Write a {weeks}-week powerlifting block with {style} loading, {days} training days per week, from the profile maxes and experience. Sections: a table (Week | Day | Main lift | Sets x reps | % or RPE | Load kg), bullets on accessory selection and why, a callout on the deload and taper logic, and kv (projected squat, bench and deadlift at block end).",
    "table, bullets, callout, kv", "Write block", "Loading the bar…"),
  T("attempts", "Pick my attempts", "Openers to thirds plus warm-ups", "🎯",
    [TXT("recent", "Best recent training lifts", "S 150x1 @RPE 9, B 95x2, D 190x1"), TXT("meetdate", "Meet date", "in 3 weeks")],
    "Select meet attempts from the profile maxes and these recent lifts: {recent}, meet {meetdate}. Sections: a table (Lift | Opener | Second | Third conservative | Third if flying), steps for warm-up timing per lift counted back from the flight (attempts out, warm-up loads, reps), a callout on the opener rule (a weight you could triple on a bad day), and bullets on what to change if a second attempt misses.",
    "table, steps, callout, bullets", "Pick attempts", "Chalking hands…"),
  T("stick", "Fix a sticking point", "Where the lift fails and why", "🔧",
    [CH("lift", "Lift", ["Squat", "Bench", "Deadlift"], "Deadlift"), CH("where", "Where it fails", ["Off the floor or bottom", "Mid-range", "Lockout", "Unracking or setup"], "Mid-range"), TXT("detail", "Details", "hips shoot up, bar drifts forward")],
    "The {lift} fails at '{where}': {detail}. Sections: bullets ranking the likely technical and strength causes, a table (Cause | Fix exercise | Sets x reps | Weeks to expect change), steps for a technique drill with a light bar, and a quote with the single cue to think during the rep.",
    "bullets, table, steps, quote", "Diagnose", "Reviewing footage…"),
  T("cut", "Make weight", "A weigh-in plan that keeps your strength", "⚖️",
    [NUM("now", "Current bodyweight (kg)", "86"), NUM("limit", "Class limit (kg)", "83"), CH("window", "Weigh-in to lifting", ["2 hours", "24 hours"], "2 hours")],
    "Plan making weight from {now} kg to a {limit} kg limit with a {window} weigh-in window. Sections: kv (kg to lose, how much via diet versus water, go or no-go verdict), a table (Days out | Food | Fluids | Sodium | Training), steps for the refeed after weigh-in, and a callout on hard limits (only a small water cut for a 2-hour window; no diuretics, saunas or extreme cuts).",
    "kv, table, steps, callout", "Plan the cut", "Checking the scale…"),
  T("meetday", "Meet-day playbook", "Gear, timing, food, headspace", "🏟️", [],
    "Write a meet-day playbook for the profile federation and experience. Sections: a checklist for the gear bag (belt, sleeves, singlet, chalk, food, membership card), a table (Time | What to do | Eat and drink), bullets on rack heights, commands and common red lights in the profile federation, and a quote with a pre-attempt mantra.",
    "checklist, table, bullets, quote", "Playbook", "Warming up…")],
 "Not medical advice. Weight cuts and maximal lifting carry risk: never cut water beyond a small margin for a same-day weigh-in, and see a clinician about persistent pain.")

# ---------------------------------------------------------------- 4. Home workouts (small flat, no kit)
APP("living_room_gym", "Living Room Gym", "Real workouts in a small flat, no kit, no noise", "Health & Fitness", ["#00796B", "#FF7043", "#FBC02D"], "home",
 "Living Room Gym writes no-equipment workouts that fit a rug-sized space and quiet hours, turns backpacks and chairs into weights, and progresses you for weeks without buying anything.",
 "You are a practical home-fitness coach who trains people in studio flats with downstairs neighbours: inventive with furniture, strict about safety, and you never suggest buying kit.",
 "How much floor do you have?", "Space, noise limits and time shape every session.", ["Quiet, no-jump workouts", "Household objects as weights", "Weeks of progression, zero purchases"],
 [NAME, CH("space", "Space", ["Yoga-mat sized", "Rug sized", "Whole room"]), CH("noise", "Noise limit", ["Silent (neighbours below)", "Some thuds OK", "No limit"]), CH("level", "Level", ["Starting out", "Regular", "Fit"])],
 [T("today", "Today's workout", "Minutes, goal, go", "🛋️",
    [CH("minutes", "Minutes", ["10", "20", "30", "45"], "20"), CH("goal", "Goal", ["Strength", "Sweat", "Core", "Full body", "Lower body", "Upper body"], "Full body"), TXT("avoid", "Avoid today", "knees, wrists")],
    "Write a {minutes}-minute workout for '{goal}' in the profile space and noise limit, avoiding: {avoid}. Sections: steps for a 3-minute warm-up, a table (Block | Exercise | Reps or seconds | Rounds | Quiet version), bullets on how to make each exercise harder without equipment, and a callout on floor and furniture safety.",
    "steps, table, bullets, callout", "Start", "Clearing the rug…"),
  T("objects", "Make weights", "Backpacks, bottles, chairs into a loaded session", "🎒",
    [PHOTO("Photo of what you have (optional)"), TXT("items", "What you have", "backpack, 6 water bottles, sturdy chair, towel")],
    "Turn these into training equipment: {items}, plus anything visible in the photo if one was given. Sections: a table (Object | Load it to | Exercises it unlocks | Safety check), steps for packing a backpack so the load does not shift, cards for 3 loaded exercises (meta = muscles · estimated kg), and a callout on chair and door-frame limits.",
    "table, steps, cards, callout", "Build kit", "Filling bottles…"),
  T("quiet", "Silent cardio", "Out of breath without a single jump", "🤫",
    [CH("minutes", "Minutes", ["8", "12", "20"], "12"), CH("format", "Format", ["Intervals", "Circuit", "Ladder", "Tabata-style"], "Circuit")],
    "Design {minutes} minutes of no-jump, no-thud cardio as a {format} for the profile level. Sections: a table (Round | Exercise | Work s | Rest s | Intensity cue), bullets on breathing and pacing, a callout on the signs to slow down, and a quote with one line to read before starting.",
    "table, bullets, callout, quote", "Go quiet", "Tiptoeing…"),
  T("plan", "4-week progression", "Get stronger without buying anything", "📅",
    [CH("days", "Days/week", ["2", "3", "4", "5"], "3"), CH("focus", "Focus", ["Push-up progress", "First row or pull", "Legs", "Core", "Overall"], "Overall")],
    "Plan 4 weeks, {days} days per week, focused on '{focus}' for the profile level, space and noise limit. Sections: a table (Week | Day | Session | Key progression), steps for the two exercises being progressed showing each easier-to-harder variation, a checklist of weekly targets, and a callout on rest days and soreness.",
    "table, steps, checklist, callout", "Plan month", "Marking calendar…"),
  T("form", "Check my form", "Photo mid-rep, no coach needed", "📷",
    [PHOTO("Photo at the hardest point of the rep", "", True), TXT("exercise", "Exercise", "push-up, split squat, glute bridge", True), TXT("feel", "What you feel", "lower back, not glutes")],
    "Check the {exercise} in the photo for someone training alone at home; they report feeling it in: {feel}. Sections: bullets on what already looks right, a table (Fault | Why it matters | Fix cue | Easier version), steps for a 2-minute practice set using a wall, chair or towel as a guide, and a callout on the sign that means stop today (sharp joint pain, numbness, or the fix does not change the feeling).",
    "bullets, table, steps, callout", "Check form", "Watching the rep…")], FIT)

# ---------------------------------------------------------------- 5. Physio-style rehab companion
APP("rehab_road", "Rehab Road", "Follow your physio plan without guessing what is OK", "Health & Fitness", ["#2E7D32", "#0288D1", "#FFA000"], "shield",
 "Rehab Road helps you follow a physiotherapist's plan for a diagnosed injury: it explains your exercise sheet, maps the phases, applies pain traffic-light rules to each session and checks return-to-sport readiness.",
 "You are a sports-physio-minded rehab guide: you never diagnose, you reinforce the treating clinician's plan, you explain the why behind each exercise and you are strict about red flags.",
 "What did your clinician diagnose?", "Rehab Road works from a diagnosis you already have, never from a guess.", ["Understand your exercise sheet", "Pain rules for every session", "Return-to-sport checks"],
 [NAME, TXT("injury", "Diagnosis (from your clinician)", "grade 2 lateral ankle sprain"), TXT("since", "When it happened or surgery date", "3 weeks ago"), TXT("sport", "Activity to return to", "5-a-side football, running")],
 [T("sheet", "Explain my exercise sheet", "Paste the exercises your physio gave you", "📄",
    [LONG("exercises", "Your exercise list", "single-leg balance 3x30 s, calf raises 3x15, band eversion…")],
    "Explain this physio exercise list for the profile diagnosis: {exercises}. Sections: a table (Exercise | What it is for | Sets x reps as written | Common mistake | Cue), steps for the recommended order in a session, bullets on how you know each one is working, and a callout to check with the treating clinician before changing anything.",
    "table, steps, bullets, callout", "Explain", "Reading the sheet…"),
  T("phases", "Map the phases", "What each stage of rehab looks like", "🗺️",
    [CH("phase", "Where you are now", ["Acute (pain and swelling)", "Early (regaining motion)", "Mid (building strength)", "Late (power and sport drills)", "Not sure"], "Not sure")],
    "Lay out the typical rehab phases for the profile diagnosis, starting from '{phase}' and the time since injury. Sections: a table (Phase | Goal | Typical weeks | Exercise types | Move on when), bullets on what tends to slow people down, a callout that timelines are only typical and the clinician sets the pace, and a checklist of milestones for the current phase.",
    "table, bullets, callout, checklist", "Map phases", "Plotting the road…"),
  T("session", "Today's session", "Adjusted for how it feels today", "🩹",
    [NUM("pain", "Pain right now (0–10)", "2"), CH("swelling", "Swelling or stiffness today", ["None", "A little", "Noticeable", "Worse than yesterday"], "A little"), TXT("plan", "Exercises you are meant to do", "from my physio sheet")],
    "Adapt today's rehab session for the profile diagnosis. Pain now {pain}/10, swelling: {swelling}, planned: {plan}. Sections: kv (go, modify or rest verdict with the reason), steps for the adapted session with sets, reps and tempo, a callout on the pain traffic light (up to 3/10 during exercise and settled by next morning is usually acceptable; above that, reduce), and bullets on what to note for the next physio visit.",
    "kv, steps, callout, bullets", "Adapt session", "Checking in…"),
  T("painok", "Was that pain OK?", "Judge a flare after exercise or activity", "🚦",
    [TXT("did", "What you did", "20-minute jog, first since injury", True), NUM("during", "Pain during (0–10)", "3"), NUM("morning", "Pain next morning (0–10)", "5")],
    "Judge this response for the profile diagnosis: {did}, pain during {during}/10, next morning {morning}/10. Sections: kv (verdict: acceptable, too much, or stop and contact your clinician, with why), a table (Signal | Meaning | Next step), steps to adjust the next attempt (volume, intensity, rest), and a callout listing red flags that need same-day medical contact.",
    "kv, table, steps, callout", "Judge it", "Reading the signal…"),
  T("return", "Ready to return?", "Score yourself against return criteria", "🏁",
    [LONG("tests", "What you can do now", "hop on injured leg 10x no pain, single-leg calf raises 22 vs 28 on the good side…")],
    "Assess return readiness for the profile sport from: {tests}. Sections: a table (Criterion | Typical target | You now | Pass or not yet), a checklist of remaining gaps to close, steps for a graded return (training before matches, minutes capped, then full), and a callout that the final clearance belongs to the treating clinician.",
    "table, checklist, steps, callout", "Assess", "Scoring criteria…")], REHAB)

# ---------------------------------------------------------------- 6. Mobility for lifters
APP("range_finder", "Range Finder", "Mobility that fixes your squat, press and hinge", "Health & Fitness", ["#6A1B9A", "#AEEA00", "#FF6D00"], "gear",
 "Range Finder is mobility for people who lift: it screens your squat and overhead positions from a photo, finds the joint limiting a lift, and writes pre-lift warm-ups and 4-week range programmes for ankles, hips, thoracic spine and shoulders.",
 "You are a strength coach who takes mobility seriously: you test before you stretch, you load new range so it sticks, and you never prescribe 30 minutes of foam rolling.",
 "Which lift feels restricted?", "Your lifts and sticky joints decide the screens and drills.", ["Screen positions from a photo", "Find the limiting joint", "Load new range so it stays"],
 [NAME, CH("lifts", "Lifts you train", ["Back squat", "Front squat", "Overhead press", "Snatch or clean", "Deadlift", "Bench"], multi=True), CH("sticky", "Sticky areas", ["Ankles", "Hips", "Thoracic spine", "Shoulders", "Wrists", "Hamstrings"], multi=True)],
 [T("screen", "Screen a position", "Photo at the bottom of a squat or overhead", "📷",
    [PHOTO("Photo at the bottom of the squat or with arms overhead", "", True), CH("position", "Position", ["Squat bottom", "Overhead reach", "Front rack", "Hinge or deadlift setup", "Deep lunge"], "Squat bottom")],
    "Screen the {position} in the photo. Sections: a table (Joint | What I see | Likely limiter: mobility, stability or technique | Test to confirm), steps for the confirming at-home test with a pass mark, bullets on what to change in the lift today, and a callout on when a restriction is a job for a clinician (pain, pinching, injury history).",
    "table, steps, bullets, callout", "Screen", "Drawing angles…"),
  T("fix", "Fix a restriction", "Depth, lockout, heels, butt wink…", "🎯",
    [CH("problem", "Problem", ["Cannot squat to depth", "Heels lift in the squat", "Cannot lock out overhead", "Front rack hurts wrists", "Rounded back on the hinge", "Butt wink at the bottom"], "Cannot squat to depth")],
    "Solve '{problem}' for the profile lifts and sticky areas. Sections: bullets ranking the likely culprits (ankle, hip, thoracic, shoulder, technique), a table (Drill | Joint | Sets x reps or seconds | When to do it | Retest), steps for a 5-minute test, drill, retest sequence, and a callout on drills to skip if there is pinching or sharp pain.",
    "bullets, table, steps, callout", "Fix it", "Finding the limiter…"),
  T("warmup", "Pre-lift warm-up", "Minutes tailored to today's lift", "🔥",
    [CH("lift", "Today's main lift", ["Squat", "Deadlift", "Overhead press", "Bench", "Olympic lifts", "Full body"], "Squat"), CH("minutes", "Minutes", ["5", "8", "12"], "8")],
    "Write a {minutes}-minute warm-up before {lift} for the profile sticky areas. Sections: steps in order (drill · reps or seconds · what it opens), a table (Drill | Target joint | Cue), a callout on how to know you are warm enough (a feeling, not a time), and bullets on empty-bar ramp sets after the warm-up.",
    "steps, table, callout, bullets", "Warm up", "Greasing joints…"),
  T("programme", "4-week range programme", "Daily minutes, one joint at a time", "📅",
    [CH("joint", "Joint", ["Ankles", "Hips", "Thoracic spine", "Shoulders", "Wrists", "Hamstrings"], "Hips"), CH("minutes", "Daily minutes", ["10", "15", "20"], "10")],
    "Write a 4-week {joint} range programme at {minutes} minutes per day for the profile lifts. Sections: a table (Week | Daily drills | Sets x reps or holds | Loading progression), steps for the two key drills with form cues, a checklist of weekly retests with measurable targets (for example knee-to-wall cm), and a callout on loading new range in the lift so it sticks.",
    "table, steps, checklist, callout", "Build programme", "Opening range…"),
  T("retest", "Log a retest", "Before and after numbers into a verdict", "📏",
    [CH("joint", "Joint", ["Ankles", "Hips", "Thoracic spine", "Shoulders", "Wrists", "Hamstrings"], "Ankles"), TXT("before", "Starting measurement", "knee-to-wall 6 cm left, 8 cm right", True), TXT("now", "Today's measurement", "knee-to-wall 9 cm left, 10 cm right", True)],
    "Compare the {joint} retest {now} against the start {before} for the profile lifts. Sections: kv (change per side, asymmetry, weeks of programme run, verdict: keep going, change drills, or move to loading in the lift), a table (Test | Typical standard for the profile lifts | Start | Now | Pass or not yet), steps for the next 2 weeks (which drills to keep, drop or load heavier), and a callout on a stalled retest usually meaning a stability or technique limit rather than a need for more stretching.",
    "kv, table, steps, callout", "Compare", "Measuring range…")], FIT)

# ---------------------------------------------------------------- 7. Dumbbell-only hypertrophy
APP("dumbbell_only", "Dumbbell Only", "Build muscle with one pair of dumbbells and a bench", "Health & Fitness", ["#1565C0", "#FF8F00", "#546E7A"], "dumbbell",
 "Dumbbell Only writes hypertrophy programmes around the exact dumbbells you own, turns any gym exercise into a dumbbell version, tracks progressive overload from your log and plans deloads before you burn out.",
 "You are an evidence-based hypertrophy coach who trains people in garages: fixated on effective reps, progressive overload and full range, honest that a pair of dumbbells goes further than most think.",
 "What dumbbells do you own?", "Dumbbells, bench and days per week set every programme.", ["Programmes for your exact weights", "Any gym exercise into a dumbbell version", "Overload tracking from your log"],
 [NAME, TXT("kit", "Dumbbells (kg) and bench", "adjustable 2.5–24 kg pair, flat bench"), CH("days", "Days/week", ["2", "3", "4", "5", "6"]), CH("goal", "Priority", ["Overall muscle", "Chest and shoulders", "Back and arms", "Legs and glutes", "Lean and athletic"])],
 [T("programme", "Write my programme", "Split, sets, reps, progression", "📋",
    [CH("weeks", "Length (weeks)", ["4", "6", "8"], "6"), CH("minutes", "Session length", ["30", "45", "60"], "45")],
    "Write a {weeks}-week hypertrophy programme with {minutes}-minute sessions for the profile dumbbells, bench, days and priority. Sections: kv (split name, weekly sets per muscle, rep ranges, rest), a table (Day | Exercise | Sets x reps | Target RPE | Progression rule), bullets on progressing when the heaviest dumbbell is not heavy enough (tempo, pauses, unilateral, rest-pause), and a callout on the deload in the final week.",
    "kv, table, bullets, callout", "Write programme", "Racking dumbbells…"),
  T("swap", "Swap an exercise", "Machine or barbell move into a dumbbell version", "🔁",
    [TXT("exercise", "Exercise to replace", "lat pulldown", True), TXT("why", "Why", "no cable machine, shoulder clicks")],
    "Replace {exercise} with dumbbell-only options because: {why}. Sections: cards for 3 substitutes (meta = muscles · difficulty · needs bench?), steps for setting up the best one correctly, a table (Substitute | Load guidance | Reps | What it misses versus the original), and a callout if the original was avoided because of pain.",
    "cards, steps, table, callout", "Find swaps", "Searching the rack…"),
  T("overload", "Am I progressing?", "Paste your log for one lift", "📈",
    [LONG("log", "Log for one exercise", "DB bench: 18 kg 3x10, 3x11, 3x12; 20 kg 3x8, 3x8, 3x9…")],
    "Analyse this exercise log: {log}. Sections: kv (trend, estimated 10RM now versus start, weekly volume change), a table (Session | Load | Reps | Volume | Note), steps for the next 3 sessions with exact loads and reps, and a callout on signs of a true stall versus a normal flat week.",
    "kv, table, steps, callout", "Analyse", "Plotting reps…"),
  T("special", "Specialisation block", "Bring up a lagging muscle", "🎯",
    [CH("muscle", "Muscle", ["Chest", "Back", "Shoulders", "Arms", "Glutes", "Quads", "Hamstrings", "Calves"], "Shoulders"), CH("weeks", "Length (weeks)", ["3", "4", "6"], "4")],
    "Design a {weeks}-week {muscle} specialisation block for the profile dumbbells and days, keeping other muscles at maintenance. Sections: a table (Day | Exercise | Sets x reps | Intensity technique), bullets on why the extra frequency works and what to pull back on, steps for the two highest-value exercises with form cues, and a callout on elbow and shoulder overuse warning signs.",
    "table, bullets, steps, callout", "Design block", "Isolating…"),
  T("deload", "Plan a deload", "Recover without losing gains", "🛌",
    [TXT("feel", "How you feel", "joints achy, sleep poor, lifts stalled 2 weeks")],
    "Decide whether the profile lifter needs a deload given: {feel}. Sections: kv (verdict; deload type: volume, intensity or full rest; length), a table (Day | Session | Sets x reps | Load versus normal), bullets on sleep and food during the deload, and a callout on what should feel different when it is over.",
    "kv, table, bullets, callout", "Plan deload", "Lowering volume…")], FIT)

# ---------------------------------------------------------------- 8. Flexibility goals (splits, bridge, pancake)
APP("bend_lab", "Bend Lab", "Front splits, bridge, pancake, trained like a skill", "Health & Fitness", ["#AD1457", "#7C4DFF", "#00BFA5"], "sun",
 "Bend Lab trains flexibility goals the way gymnasts do: measured tests, an 8-week programme for splits, bridge, pancake or pike, PNF and loaded stretching coached step by step, and retests that show real centimetres.",
 "You are a contortion-and-gymnastics flexibility coach: methodical, obsessed with measured progress, protective of hamstring tendons and the lower back.",
 "Which shape are you chasing?", "Goal, current distance from the floor and training days set the plan.", ["Splits, bridge, pancake and pike plans", "Measured tests and retests", "PNF and loaded stretching coached"],
 [NAME, CH("goal", "Goal", ["Front splits", "Middle splits", "Full bridge", "Pancake", "Pike (head to knees)", "Shoulder flexibility"]), TXT("baseline", "Current measurement", "front split 25 cm from floor, right leg forward"), CH("days", "Days/week", ["2", "3", "4", "5", "6"])],
 [T("test", "Measure my baseline", "Tests with a tape measure and a wall", "📏", [],
    "Design a measured flexibility test battery for the profile goal. Sections: steps for each test (setup, what to measure, how to keep it repeatable), a table (Test | Measures | Beginner | Intermediate | Advanced), a checklist of what to photograph and record, and a callout on warming up before testing and never bouncing.",
    "steps, table, checklist, callout", "Set up tests", "Unrolling the tape…"),
  T("programme", "8-week programme", "Skill-style flexibility training", "📅",
    [CH("session", "Session length", ["15 min", "25 min", "40 min"], "25 min"), TXT("limits", "Limits", "old hamstring strain, tight hip flexors")],
    "Write an 8-week programme for the profile goal with {session} sessions on the profile days, respecting: {limits}. Sections: a table (Week | Session | Stretches with holds x secs | Strength-in-range work | Retest), steps for the 3 key stretches with exact positions and breathing, bullets on how to progress each week, and a callout on tendon pain at the sit bone or behind the knee meaning back off.",
    "table, steps, bullets, callout", "Build programme", "Lengthening…"),
  T("today", "Today's session", "One flexibility session, coached", "🧘",
    [CH("minutes", "Minutes", ["10", "20", "30"], "20"), CH("type", "Type", ["PNF (contract-relax)", "Loaded stretching", "Active flexibility", "Relaxed long holds", "Mixed"], "Mixed")],
    "Write a {minutes}-minute {type} session for the profile goal. Sections: steps in order with holds in seconds, contract and relax counts and the target sensation, a table (Stretch | Position | Seconds | Rounds | Cue), a callout on the difference between stretch and pain, and a quote with a breathing cue.",
    "steps, table, callout, quote", "Start session", "Breathing out…"),
  T("form", "Check a stretch", "Photo in the position", "📷",
    [PHOTO("Photo in the stretch", "", True), TXT("stretch", "Which stretch", "front split, left leg forward", True)],
    "Assess the {stretch} in the photo. Sections: bullets on alignment (square hips, knee tracking, spine, foot), a table (Fault | Risk | Fix), steps to re-enter the position correctly with props if needed, and a callout if the photo suggests regressing or a clinician check.",
    "bullets, table, steps, callout", "Assess", "Checking lines…"),
  T("retest", "Retest and adjust", "Compare with baseline, change the plan", "📊",
    [TXT("now", "Today's measurement", "front split 18 cm from floor, right leg forward", True), NUM("weeks", "Weeks since baseline", "4")],
    "Compare {now} with the profile baseline after {weeks} weeks. Sections: kv (change, rate per week, projected weeks to goal), bullets on why progress may be fast, slow or stalled, steps for the next 4 weeks of adjustments, and a callout on plateaus that need strength in the new range rather than more stretching.",
    "kv, bullets, steps, callout", "Compare", "Measuring gains…")], FIT)

# ---------------------------------------------------------------- 9. Beginner's first gym programme
APP("first_rep", "First Rep", "Your first gym programme, minus the fear", "Health & Fitness", ["#00897B", "#3949AB", "#FFD54F"], "spark",
 "First Rep gets a nervous beginner through the gym door: it identifies any machine from a photo and shows how to use it, writes a simple 8-week starter programme, explains etiquette, and finds a replacement when the kit you need is taken.",
 "You are a friendly gym-floor coach for absolute beginners: zero jargon, zero judgement, form before load, and you answer the questions people are embarrassed to ask.",
 "First time in a gym?", "Tell First Rep about your gym and goals; it will handle the awkward bits.", ["Identify any machine from a photo", "Simple 8-week starter plan", "Etiquette and what to do when kit is taken"],
 [NAME, CH("gym", "Gym type", ["Big-box chain", "Small local gym", "Hotel or building gym", "Not joined yet"]), CH("goal", "Goal", ["Feel stronger", "Lose fat", "Tone up", "Confidence and habit", "Doctor told me to"]), CH("days", "Days/week", ["2", "3", "4"])],
 [T("machine", "What is this machine?", "Photo into name, muscles and setup", "📷",
    [PHOTO("Photo of the machine", "", True)],
    "Identify the machine in the photo. Sections: kv (name, muscles worked, beginner difficulty, what to adjust: seat, pad or pin), steps for setting it up and doing one clean rep, bullets on the 3 mistakes beginners make on it, and a callout on the starting-weight rule (a weight you can do 12 comfortable reps with).",
    "kv, steps, bullets, callout", "Identify", "Reading the labels…"),
  T("programme", "8-week starter plan", "Full body, simple, progressive", "🗓️",
    [CH("style", "Prefer", ["Mostly machines", "Machines and dumbbells", "Free weights", "Whatever is free"], "Machines and dumbbells"), CH("minutes", "Minutes per visit", ["30", "45", "60"], "45")],
    "Write an 8-week beginner programme for the profile gym, goal and days, using {style}, {minutes} minutes per visit. Sections: a table (Weeks | Day | Exercise | Sets x reps | How to progress), steps for the first visit minute by minute (arrive, warm up, session, stretch), a checklist of what to bring and record, and a callout on week-one soreness and when to rest.",
    "table, steps, checklist, callout", "Write plan", "Writing week one…"),
  T("taken", "Kit is taken", "Swap to something free right now", "🔁",
    [TXT("exercise", "Exercise you planned", "leg press", True), TXT("free", "What looks free", "dumbbells, a cable machine, the mats")],
    "Replace {exercise} with what is free: {free}. Sections: cards for 3 alternatives (meta = same muscles? · difficulty · kit), steps for the best alternative with setup and form cues, a callout on how to politely ask to work in on a machine, and a quote with the exact sentence to say.",
    "cards, steps, callout, quote", "Swap", "Looking around…"),
  T("etiquette", "Etiquette and fears", "The unwritten rules, answered", "🙋",
    [TXT("question", "What are you worried about", "will people judge me, do I wipe the bench", True)],
    "Answer this beginner worry warmly and specifically for the profile gym type: {question}. Sections: text answering it honestly, bullets of unwritten rules that apply (re-racking, wiping, sharing, phones, mirrors), a checklist for a stress-free visit, and a quote with one reassuring line to remember at the door.",
    "text, bullets, checklist, quote", "Reassure me", "Walking in with you…"),
  T("form", "Check my form", "Photo of a squat, row or press", "🎥",
    [PHOTO("Photo mid-rep", "", True), TXT("exercise", "Exercise", "goblet squat", True)],
    "Check the {exercise} in the photo for a beginner. Sections: bullets on what looks good first, a table (Fix | Why | Cue), steps for a lighter practice set to groove the fix, and a callout on the signs that mean lower the weight today.",
    "bullets, table, steps, callout", "Check form", "Watching the rep…")], FIT)

# ---------------------------------------------------------------- 10. Conditioning / engine work
APP("engine_room", "Engine Room", "Conditioning that makes you fitter, not just tired", "Health & Fitness", ["#212121", "#00B0FF", "#FF1744"], "bolt",
 "Engine Room builds conditioning around the machines and space you have (rower, air bike, ski erg, sled, bodyweight) with paced intervals, EMOMs and benchmark tests that show your engine growing week by week.",
 "You are a conditioning coach from the CrossFit and rowing worlds: you programme by intent (aerobic base, threshold, sprint), you hate random sweat sessions, and you make people hold a pace instead of blowing up.",
 "What machines can you use?", "Kit, weekly lifting days and current benchmarks shape every piece.", ["Intervals with target paces", "Benchmark tests you can retest", "Conditioning that fits around lifting"],
 [NAME, CH("kit", "Available", ["Rower", "Air bike", "Ski erg", "Spin bike", "Treadmill", "Sled", "Jump rope", "Bodyweight only"], multi=True), TXT("bench", "Recent benchmarks", "2k row 8:10, 1-mile run 8:30"), CH("lifting", "Lifting days/week", ["0", "1–2", "3–4", "5+"])],
 [T("piece", "Build a piece", "Intent, minutes and kit into a paced workout", "⚙️",
    [CH("intent", "Intent", ["Aerobic base", "Threshold", "VO2 intervals", "Sprint or power", "Mixed-modal (EMOM or AMRAP)"], "Threshold"), CH("minutes", "Minutes", ["12", "20", "30", "45"], "20"), TXT("avoid", "Avoid", "no running today, sore calf")],
    "Design a {minutes}-minute conditioning piece with intent '{intent}' from the profile kit and benchmarks, avoiding: {avoid}. Sections: kv (format, target pace or RPE, work to rest, what the session trains), a table (Interval | Work | Rest | Target pace, watts or RPE | Cue), steps for a warm-up that matches the intent, and a callout on the stop signal (a pace drop over 5 percent means the piece is done).",
    "kv, table, steps, callout", "Build piece", "Setting the damper…"),
  T("benchmark", "Benchmark test", "Set or retest a standard", "⏱️",
    [CH("test", "Test", ["2k row", "500m row", "1-mile run", "5-min air bike max calories", "1k ski", "10-min burpee AMRAP"], "2k row")],
    "Prepare the profile athlete for a {test}. Sections: steps for pacing the test with target splits per segment derived from the profile benchmarks, a table (Segment | Target split or pace | Effort | What to think), a checklist for warm-up and setup (damper, screen units, timing), and a callout on when to abandon a test.",
    "steps, table, checklist, callout", "Prep test", "Calibrating…"),
  T("week", "Conditioning week", "Pieces that fit around your lifting", "📅",
    [CH("sessions", "Conditioning sessions", ["2", "3", "4"], "3"), CH("goal", "6-week goal", ["Bigger aerobic base", "Faster 2k or mile", "Repeat-sprint fitness", "Fat loss", "Hyrox or mixed event"], "Bigger aerobic base")],
    "Plan a conditioning week with {sessions} sessions toward '{goal}' around the profile lifting days and kit. Sections: a table (Day | Lifting? | Conditioning piece | Intent | Duration), bullets on ordering conditioning before or after lifting, a callout on total weekly hard minutes to avoid overreaching, and kv (paces to hold this week per machine).",
    "table, bullets, callout, kv", "Plan week", "Balancing load…"),
  T("pacing", "Review my splits", "Paste splits or a monitor summary", "📊",
    [LONG("splits", "Splits or summary", "2k row: 2:01, 2:03, 2:06, 2:12, total 8:22")],
    "Analyse these splits against the profile benchmarks: {splits}. Sections: kv (pacing verdict: even, positive or negative split, and its cost in seconds), a table (Segment | Split | Versus target | What happened), bullets on the technical or pacing cause, and steps for the next attempt with exact target splits.",
    "kv, table, bullets, steps", "Analyse", "Reading the monitor…"),
  T("machine", "Machine technique", "Row, ski, bike and sled done properly", "🚣",
    [CH("machine", "Machine", ["Rower", "Ski erg", "Air bike", "Sled push or pull", "Jump rope"], "Rower"), TXT("issue", "What goes wrong", "back tires before legs")],
    "Teach {machine} technique for this problem: {issue}. Sections: steps for the stroke or movement sequence with timing ratios, a table (Fault | Symptom | Fix drill), bullets on damper, settings or setup, and a quote with the one cue to repeat during the piece.",
    "steps, table, bullets, quote", "Teach me", "Tuning the stroke…")], FIT)
