from dsl import *
# w11 — Sports / Health: martial arts, pilates, dance, climbing, skiing, surfing, golf, tennis technique

SPORT = "Not medical advice. Warm up, train within your ability, and see a clinician for sharp pain, swelling, numbness or any injury before training again."

# ---------------------------------------------------------------- 1. Brazilian jiu-jitsu
APP("roll_log", "Roll Log", "Turn every BJJ roll into what to drill next", "Sports", ["#1A237E", "#C99A2E", "#B71C1C"], "shield",
 "Roll Log turns your Brazilian jiu-jitsu training notes into a game: it debriefs rolls, builds position-specific game plans and drilling blocks, preps you for competition and maps what your next belt actually expects.",
 "You are a patient black-belt BJJ coach: position before submission, concept-driven, honest about what each belt should and shouldn't be drilling; you never encourage rolling through injury.",
 "Where's your game at?", "Belt, style and how often you train shape every plan.", ["Roll notes → what to drill next", "Position-by-position game plans", "Competition and belt prep"],
 [CH("belt", "Belt", ["White", "Blue", "Purple", "Brown", "Black"]), CH("style", "Gi or no-gi", ["Gi", "No-gi", "Both"]), CH("days", "Sessions per week", ["1–2", "3–4", "5+"]), TXT("game", "Your A-game / weak spots", "half guard bottom is ok, keep getting knee-cut passed")],
 [T("debrief", "Debrief a roll", "What happened → what to fix", "🥋",
    [LONG("notes", "What happened", "swept from closed guard 3x, stuck under side control, tapped to a triangle"), CH("partner", "Partner", ["Lower belt", "Same belt", "Higher belt", "Much bigger"], "Same belt")],
    "Debrief this roll against a {partner} partner for the profile belt and style: {notes}. Sections: a table (Moment | What went wrong | Likely cause | Fix), bullets of the 2 things that went right, steps for one drill to run next class with reps and rounds, and a quote with a single focus cue for the next roll.",
    "table, bullets, steps, quote", "Debrief", "Rewatching the roll…"),
  T("position", "Position game plan", "Three linked techniques from one spot", "🧩",
    [CH("position", "Position", ["Closed guard", "Half guard", "Open guard", "Side control", "Mount", "Back", "Turtle", "Standing"], "Half guard"), CH("role", "I'm on", ["Top", "Bottom"], "Bottom")],
    "Build a {role} game plan from {position} for the profile belt and style. Sections: cards for 3 linked techniques (meta = belt level · gi/no-gi), a table of the opponent's most common reactions (They do | You do | Why it works), steps for a 10-minute positional-sparring plan, and a callout on the mistake that loses this position most often.",
    "cards, table, steps, callout", "Build plan", "Chaining moves…"),
  T("comp", "Competition prep", "Weeks out → match morning", "🏆",
    [TXT("event", "Event & date", "local open in 3 weeks, gi", True), TXT("weight", "Current weight → division", "80 kg → 76 kg"), CH("ruleset", "Ruleset", ["IBJJF", "ADCC / sub-only", "Not sure"], "IBJJF")],
    "Prepare for {event} under {ruleset} rules with weight situation {weight}. Sections: a table (Week | Training focus | Rounds per session | Weight target), a checklist for the day before and match morning (weigh-in, food, warm-up, mouthguard), bullets on scoring or match-winning tactics specific to {ruleset}, and a callout on safe weight management and when a cut is not worth it.",
    "table, checklist, bullets, callout", "Get ready", "Bowing in…"),
  T("belt", "Next-belt map", "What the next stripe or belt expects", "🎗️", [],
    "Using the profile belt, style, sessions per week and weak spots, describe what the next belt typically requires. Sections: a checklist of techniques and concepts expected at the next belt grouped by position, kv (typical time at this belt, stripe cadence, common promotion signals), steps for a 4-week focus block that addresses the profile weak spots, and a callout on not comparing your timeline to teammates.",
    "checklist, kv, steps, callout", "Map my path", "Checking stripes…"),
  T("tweak", "Sore or tweaked?", "Train, modify or rest", "🩹",
    [TXT("issue", "What's sore or tweaked", "neck cranked in a guillotine, stiff turning left", True), CH("when", "Next class", ["Tonight", "Tomorrow", "In a few days"], "Tomorrow")],
    "The user reports: {issue}, with the next class {when}. Sections: text on whether training {when} is sensible and how to modify (drill only, flow roll, skip), bullets of positions and submissions to avoid on the mat, steps for a self-care routine for the next 48 hours, and a callout listing signs (numbness, tingling, swelling, a joint that won't straighten) that mean see a clinician before rolling again.",
    "text, bullets, steps, callout", "Advise me", "Icing…")],
 "Not medical advice. Tap early, train with supervision, and see a clinician for joint pain, numbness or any injury before returning to the mat.")

# ---------------------------------------------------------------- 2. Boxing / kickboxing / Muay Thai
APP("strike_lab", "Strike Lab", "Bag rounds, combos and sparring prep that make sense", "Sports", ["#B71C1C", "#212121", "#FFC107"], "bolt",
 "Strike Lab builds heavy-bag and shadowboxing rounds, fixes your combos, stance and footwork, and preps you for sparring or a first amateur bout, whether you box, kickbox or train Muay Thai.",
 "You are a corner coach who has trained beginners and amateurs: defence first, obsessed with the basics, counting rounds in minutes and rest in seconds; you never push sparring before the fundamentals are there.",
 "Gloves on", "Your discipline, stance and gear shape every round.", ["Bag and shadow rounds for your minutes", "Combo, stance and footwork fixes", "Sparring and fight-night prep"],
 [CH("discipline", "Discipline", ["Boxing", "Kickboxing", "Muay Thai", "Fitness only"]), CH("stance", "Stance", ["Orthodox", "Southpaw", "Switch"]), CH("gear", "Gear at home", ["Heavy bag", "Double-end bag", "Pads with a partner", "Nothing (shadow only)"], multi=True), CH("level", "Level", ["First month", "Regular class-goer", "Sparring", "Amateur competitor"])],
 [T("rounds", "Build my rounds", "3-minute rounds for your gear", "🥊",
    [CH("rounds", "Rounds", ["4", "6", "8", "10", "12"], "6"), CH("focus", "Focus", ["Fundamentals", "Combinations", "Defence", "Power", "Conditioning"], "Fundamentals"), TXT("note", "Anything to work around", "sore left shoulder, only 25 minutes")],
    "Write {rounds} × 3-minute rounds with 1-minute rests, focus '{focus}', for the profile discipline, stance and gear, working around: {note}. Sections: steps for a warm-up (rope, shadow, mobility, with minutes), a table (Round | Drill | Combos or task | Intensity | Cue), bullets on breathing and bringing hands back, and a callout on the one fault to police for the whole session.",
    "steps, table, bullets, callout", "Build rounds", "Wrapping hands…"),
  T("combo", "Combo builder", "Four combinations with a purpose", "🔗",
    [TXT("opening", "Start from", "jab–cross", True), CH("goal", "Purpose", ["Set up the body shot", "Exit at an angle", "Counter a jab", "Close distance", "Finish with a kick"], "Exit at an angle")],
    "Build 4 combinations that start from '{opening}' with the purpose '{goal}', legal and sensible for the profile discipline and stance. Sections: cards per combo (meta = number of strikes · range), a table (Strike | Target | Weight shift | Common fault), steps for drilling one combo from slow shadow to bag at speed, and a quote with a rhythm count to say out loud.",
    "cards, table, steps, quote", "Build combos", "Chaining shots…"),
  T("form", "Check my stance", "Photo or description → fixes", "📷",
    [PHOTO("Photo in your stance or mid-punch (optional)"), TXT("issue", "What feels off", "my cross has no power and I drop my right hand", True)],
    "Assess the stance or strike from the photo (if attached) and this description: {issue}, for the profile stance and discipline. Sections: bullets of the 3 most likely faults ranked, a table (Fault | What it looks like | Fix | Drill), steps for one mirror drill with reps, and a callout on the defensive habit that must not slip while fixing it.",
    "bullets, table, steps, callout", "Assess", "Watching the hands…"),
  T("spar", "Sparring prep", "Gear, game plan, warm-up, safety", "🛡️",
    [CH("type", "Session", ["First light spar", "Technical sparring", "Hard sparring", "Amateur bout"], "First light spar"), TXT("opponent", "Opponent style (if known)", "taller, long jab, backs up")],
    "Prepare for {type} against: {opponent}, for the profile level and stance. Sections: a checklist of gear and readiness checks (mouthguard, headgear, hand health, sleep), bullets with a 3-point game plan matched to the opponent style, a table (If they… | You…), steps for the 20-minute warm-up before the bell, and a callout on when to stop a spar (dazed, headache, vision change) and concussion basics.",
    "checklist, bullets, table, steps, callout", "Prep me", "Ringside…"),
  T("footwork", "Footwork drill", "Tape on the floor, minutes on the clock", "👣",
    [CH("skill", "Skill", ["Pivot", "Lateral step", "In-and-out", "Cutting the ring", "Switching stance"], "Pivot"), NUM("minutes", "Minutes", "10")],
    "A {minutes}-minute footwork session on '{skill}' for the profile stance, done with tape on the floor or around a bag. Sections: steps (each with seconds or reps), kv (foot position, weight split, head position, hand position), bullets on common mistakes, and a quote with a one-line cue.",
    "steps, kv, bullets, quote", "Drill it", "Moving feet…")],
 "Not medical advice. Head contact carries concussion risk: spar only with headgear, a mouthguard and a coach present, and stop immediately for dizziness, headache or vision changes.")

# ---------------------------------------------------------------- 3. Pilates
APP("powerhouse_pilates", "Powerhouse", "Mat Pilates built for your body and your minutes", "Health & Fitness", ["#6D9773", "#D98C8C", "#F0C987"], "spark",
 "Powerhouse builds mat Pilates sessions for your level and kit, translates reformer classes to home, fixes form on the classical exercises and adapts safely for pregnancy, postnatal and back-care needs.",
 "You are a classically trained Pilates instructor: precise about breath and alignment, quality over reps, with a modification for every exercise and a clear line on when to refer to a physio.",
 "Find your powerhouse", "Your experience, kit and any conditions shape every session.", ["Mat sessions from 10 to 45 minutes", "Reformer → home translations", "Form fixes and safe modifications"],
 [NAME, CH("level", "Experience", ["Never tried", "Beginner", "Intermediate", "Advanced"]), CH("kit", "Kit at home", ["Mat only", "Ball", "Band", "Magic circle", "Foam roller", "Reformer"], multi=True), TXT("body", "Conditions / limits", "diastasis recti, tight hip flexors")],
 [T("session", "Mat session", "Exercises, breaths and cues", "🧘",
    [CH("minutes", "Minutes", ["10", "20", "30", "45"], "20"), CH("focus", "Focus", ["Core & spine", "Glutes & hips", "Posture & back care", "Full body flow", "Flexibility"], "Core & spine")],
    "Design a {minutes}-minute mat Pilates session on '{focus}' for the profile level, kit and limits. Sections: steps (exercise · reps or breaths · breath cue), a table (Exercise | Muscles | Modification | Progression), a callout on the exercises to skip or modify given the profile limits, and a quote with the principle for the day (e.g. 'imprint before you lift').",
    "steps, table, callout, quote", "Build session", "Finding neutral…"),
  T("translate", "Reformer → mat", "Recreate class at home", "🔁",
    [LONG("class", "Exercises from class", "footwork, hundred, short spine, elephant, knee stretches…")],
    "Translate these reformer exercises to home using the profile kit: {class}. Sections: a table (Reformer exercise | Home version | Kit needed | What changes), steps for the 3 hardest to replicate, and bullets on what a reformer gives that a mat cannot and how to compensate.",
    "table, steps, bullets", "Translate", "Unhooking springs…"),
  T("form", "Fix an exercise", "Photo or description → cues", "📷",
    [PHOTO("Photo mid-exercise (optional)"), CH("exercise", "Exercise", ["The Hundred", "Roll Up", "Single Leg Circle", "Rolling Like a Ball", "Teaser", "Swan", "Side Kick series", "Leg Pull / Plank"], "The Hundred"), TXT("issue", "What's happening", "neck aches, lower back arches")],
    "Coach {exercise} from the photo (if attached) and this description (if given): {issue}, for the profile level and limits. Sections: bullets of the likely causes ranked, steps for a regression that fixes the fault and then a rebuild to the full exercise, kv (breath pattern, pelvis position, ribs, gaze), and a callout on when neck or back pain means stop.",
    "bullets, steps, kv, callout", "Coach me", "Checking alignment…"),
  T("adapt", "Pregnancy, postnatal, back", "Safe adaptations for your stage", "🤱",
    [CH("stage", "Situation", ["Pregnant 1st trimester", "Pregnant 2nd/3rd trimester", "Postnatal 0–12 weeks", "Postnatal 3–12 months", "Lower-back pain history", "Osteoporosis"], "Postnatal 3–12 months"), TXT("cleared", "What your clinician said", "cleared at 6-week check, avoid crunches")],
    "Adapt Pilates for '{stage}' given the clinician note: {cleared}. Sections: a callout first on the non-negotiable avoids for this stage, a checklist of safe foundational exercises to start with, a table (Classical exercise | Safe now? | Swap), steps for a 12-minute gentle routine, and bullets on signs (coning, leaking, pain) that mean regress and consult.",
    "callout, checklist, table, steps, bullets", "Adapt", "Gently…"),
  T("month", "4-week progression", "Three sessions a week, from the profile", "📅", [],
    "Write a 4-week home Pilates progression for the profile level, kit and limits at 3 sessions a week. Sections: a table (Week | Session A | Session B | Session C | Minutes), bullets on what should feel different by week 4, steps for a self-test to run in week 1 and again in week 4 (roll-up quality, plank hold, single-leg stand), and a callout on rest and normal soreness versus pain.",
    "table, bullets, steps, callout", "Plan month", "Sequencing…")],
 "Not medical advice. Get clearance from your doctor or physio before exercising if you are pregnant, postnatal or have a back, pelvic-floor or bone condition, and stop for any pain.")

# ---------------------------------------------------------------- 4. Partner / social dance
APP("lead_follow", "Lead & Follow", "Social dance moves, counts and confidence", "Lifestyle", ["#AD1457", "#00897B", "#FFB300"], "music",
 "Lead & Follow helps social dancers learn salsa, bachata, swing, tango and ballroom: move breakdowns in counts, floor-craft for busy socials, partner communication and choreography for a wedding first dance.",
 "You are a warm social-dance teacher: count-driven, technically correct without being heavy, equally fluent in leading and following, and clear that connection and consent matter more than flashy moves.",
 "Ready for the floor?", "Your style, role and level shape every breakdown.", ["Moves broken into counts", "Social-floor confidence", "Wedding first-dance choreography"],
 [NAME, CH("style", "Main style", ["Salsa", "Bachata", "Kizomba", "Swing / Lindy", "Argentine tango", "Ballroom / Latin", "West Coast Swing"]), CH("role", "Role", ["Lead", "Follow", "Both"]), CH("level", "Level", ["Just started", "Improver", "Intermediate", "Advanced"])],
 [T("move", "Break down a move", "Counts, feet, frame, connection", "💃",
    [TXT("move", "Move", "cross-body lead with inside turn", True), TXT("stuck", "Where it falls apart", "my partner ends up too far away")],
    "Break down '{move}' in the profile style for the profile role, addressing this sticking point if given: {stuck}. Sections: a table (Count | Lead's feet & frame | Follow's feet & frame | Connection cue), bullets of the 3 most common errors and their fixes, steps for solo practice without a partner, and a quote with the timing spoken in words (e.g. 'quick-quick-slow').",
    "table, bullets, steps, quote", "Break it down", "Counting in…"),
  T("social", "Survive a social", "Asking, blanking, crowds", "🪩",
    [CH("worry", "Biggest worry", ["Asking people to dance", "Forgetting moves mid-song", "Crowded floor", "Dancing with better dancers", "Keeping time with live music"], "Forgetting moves mid-song")],
    "Coach the profile dancer through '{worry}' at a social. Sections: text reframing the worry in 3 sentences, a checklist for the evening (arrival, warm-up dances, breaks, exit), bullets of 5 fallback basics to cycle through when the mind goes blank, a quote with a polite way to ask for a dance and a polite way to decline one, and a callout on floor etiquette and consent.",
    "text, checklist, bullets, quote, callout", "Coach me", "Lacing shoes…"),
  T("wedding", "First-dance choreography", "Song → moves, counts, 6-week plan", "💍",
    [TXT("song", "Song & length", "Perfect – Ed Sheeran, 4:23", True), CH("skill", "Couple's experience", ["None", "A few lessons", "One dances well", "Both dance"], "None"), CH("vibe", "Vibe", ["Simple and sweet", "A little showy", "Big finish"], "Simple and sweet")],
    "Choreograph a first dance to {song} for a couple with experience '{skill}' and vibe '{vibe}'. Sections: a table (Song section | Time | Move | Counts | Notes), steps for a 6-week practice schedule with minutes per session, bullets of 3 rescue moves if they lose their place, and a callout on dress, shoes and floor considerations.",
    "table, steps, bullets, callout", "Choreograph", "Cueing the song…"),
  T("music", "Hear the music", "Find the 1, hit the breaks", "🎶",
    [CH("goal", "Learn to", ["Find the 1", "Dance on 2", "Hit breaks and accents", "Play with slow and fast"], "Find the 1")],
    "Teach '{goal}' for the profile style. Sections: text explaining the structure of a typical song in that style (bars, phrases, which instruments mark the beat), steps for a listening drill using 3 named songs, bullets of body cues to mark the beat, and a callout on what to do when you lose the count mid-dance.",
    "text, steps, bullets, callout", "Train my ear", "Pressing play…"),
  T("partner", "Say it kindly", "Feedback for a dance partner", "🗣️",
    [TXT("issue", "What's happening", "he grips my hand too hard on turns", True)],
    "The user needs to raise this with a dance partner: {issue}. Sections: text on whether this is a technique issue or a comfort and safety one, a quote with a kind, specific 2-sentence way to say it on the floor, bullets of technique fixes both roles can try, and a callout on when to simply stop the dance.",
    "text, quote, bullets, callout", "Write it", "Choosing words…")],
 "Warm up, wear suitable shoes and stop for pain; not medical advice.")

# ---------------------------------------------------------------- 5. Choreography / urban dance
APP("choreo_lab", "Choreo Lab", "Learn routines faster and make your own", "Entertainment", ["#6A1B9A", "#00E5FF", "#FF4081"], "star",
 "Choreo Lab helps dancers learn routines faster and create their own: it turns your notes into 8-count sheets, cleans a run-through from a still, choreographs combos to a track, runs freestyle sessions and preps you for auditions and team tryouts.",
 "You are a working choreographer and dance-team captain: 8-count fluent, honest but encouraging, big on cleaning (timing, levels, angles) and on protecting knees and ankles.",
 "Let's make it clean", "Your styles, level and goal shape every count.", ["Routines written in 8-counts", "Cleaning plans that fix timing", "Freestyle and audition prep"],
 [NAME, CH("styles", "Styles", ["Hip hop", "K-pop", "Contemporary", "Jazz", "Heels", "House", "Popping / Locking", "Bollywood"], multi=True), CH("level", "Level", ["Beginner", "Intermediate", "Advanced", "Teach / lead"]), CH("goal", "Goal", ["Learn covers", "Join a team", "Auditions", "Make my own", "Fitness & fun"])],
 [T("counts", "Notes → 8-counts", "Your description → a count sheet", "🔢",
    [LONG("routine", "Describe the routine", "body roll on 1, arms cross on 3-4, step-touch left right, chorus is a groove…"), TXT("song", "Song", "Dynamite – BTS")],
    "Convert this routine description (song: {song}) into a clean count sheet: {routine}. Sections: a table (8-count | Counts | Movement | Level / direction | Cue word), bullets flagging where the description is ambiguous and what to check in the video, steps for a chunk-and-loop learning order (which 8s to learn first and how to join them), and a quote with the cue words in order as a chant.",
    "table, bullets, steps, quote", "Write counts", "5-6-7-8…"),
  T("clean", "Clean my run-through", "Still + notes → fixes", "📷",
    [PHOTO("Still from your video (optional)"), LONG("notes", "What looks off", "late on the chorus, arms look soft, my spins travel")],
    "Diagnose and clean from the photo (if attached) and these notes for the profile level: {notes}. Sections: a table (Symptom | Likely cause | Fix | Drill), steps for a 20-minute cleaning session (slow-mo, half-time, mirror, film-and-compare), bullets on angles, levels and energy, and a callout on knee and ankle safety for jumps and floorwork.",
    "table, steps, bullets, callout", "Clean it", "Half-time…"),
  T("make", "Make a combo", "Choreograph to a track", "✨",
    [TXT("track", "Song / vibe", "slow R&B, 70 bpm", True), CH("length", "Length", ["2 eights", "4 eights", "8 eights", "Full chorus"], "4 eights"), CH("style", "Style for this piece", ["Hip hop", "K-pop", "Contemporary", "Jazz", "Heels", "House", "Popping / Locking", "Bollywood"], "Hip hop")],
    "Choreograph {length} in {style} to '{track}' for the profile level. Sections: a table (8-count | Counts | Movement | Texture (sharp / smooth) | Facing or formation), text with the concept in 2 sentences, bullets of 3 variations to make it easier or harder, and a callout on musicality: which accents in the track to hit.",
    "table, text, bullets, callout", "Choreograph", "Feeling the beat…"),
  T("freestyle", "Freestyle session", "Constraints that unlock movement", "🎧",
    [CH("minutes", "Session length", ["5", "10", "20"], "10")],
    "Design a {minutes}-minute freestyle practice for the profile styles. Sections: steps (round · minutes · constraint, e.g. 'only levels', 'one body part', 'textures'), bullets of grooves to fall back on, a quote with a mantra for when you freeze, and kv (a tempo range and 3 suggested tracks per profile style).",
    "steps, bullets, quote, kv", "Start session", "Dropping a beat…"),
  T("audition", "Audition / tryout prep", "Two weeks to the room", "🎫",
    [TXT("event", "Audition", "uni hip-hop team tryouts in 2 weeks, learn 2 combos on the day", True)],
    "Prepare for: {event}, for the profile level and goal. Sections: a 14-day table (Day | Focus | Minutes), a checklist for audition day (outfit, shoes, water, warm-up, number, video release), bullets on how to pick up choreography fast in the room, steps for a 10-minute warm-up, and a callout on handling nerves and what panels actually score.",
    "table, checklist, bullets, steps, callout", "Prep me", "Pinning the number…")],
 "Warm up first and stop for sharp knee, ankle or back pain; not medical advice.")

# ---------------------------------------------------------------- 6. Climbing
APP("send_beta", "Send Beta", "Project tactics and training that match your grade", "Sports", ["#E65100", "#455A64", "#8BC34A"], "gear",
 "Send Beta is a coach for boulderers and sport climbers: it reads your project from a photo, writes training blocks matched to your grade, guides finger and elbow niggles, analyses your grade pyramid and preps trips.",
 "You are a climbing coach who has seen too many finger injuries: technique and tactics before fingerboarding, honest about what a grade needs, and clear that ropes, knots and gear are learned in person, never from an app.",
 "What are you projecting?", "Grade, discipline and years climbing shape every plan.", ["Beta and tactics for your project", "Training matched to your grade", "Finger and elbow care"],
 [NAME, CH("discipline", "Discipline", ["Bouldering", "Sport", "Trad", "Gym only"], multi=True), TXT("grade", "Current grades (flash / redpoint)", "V4 flash, 6b+ redpoint"), CH("years", "Years climbing", ["Under 1", "1–3", "3–7", "7+"])],
 [T("project", "Read my project", "Photo → sequence and tactics", "📷",
    [PHOTO("Photo of the route or boulder", "", True), TXT("target", "Grade & where you fall", "V5, keep falling going for the top sloper")],
    "Read the route photo for a project described as: {target}, for the profile grade. Sections: steps for a plausible sequence hold by hold (hand, foot, body position), a table (Crux section | Why it's hard | Technique | Rest point), bullets of tactics (warm-up sequence, attempts per session, rest between goes, skipping holds, chalk), and a callout that the beta is a hypothesis to test and on pad, spotter and fall-zone safety.",
    "steps, table, bullets, callout", "Read beta", "Chalking up…"),
  T("train", "Training block", "Weeks, days, sets, intensity", "📈",
    [CH("weeks", "Weeks", ["4", "6", "8"], "6"), CH("weak", "Weakness", ["Finger strength", "Power / dynos", "Endurance", "Technique / footwork", "Core & body tension", "Head game"], "Finger strength"), CH("days", "Climbing days per week", ["2", "3", "4", "5"], "3")],
    "Write a {weeks}-week training block for weakness '{weak}' at {days} days a week for the profile grade and years climbing. Sections: a callout first on whether hangboarding is appropriate at the profile experience and how to load safely, a table (Week | Day | Session | Sets × reps or time | Intensity), bullets on how to tell it's working, and steps for the warm-up used before every session.",
    "callout, table, bullets, steps", "Build block", "Loading the board…"),
  T("niggle", "Finger or elbow niggle", "What it might be, what to do", "🩹",
    [CH("where", "Where", ["Finger pulley", "Finger joint", "Elbow (inside)", "Elbow (outside)", "Shoulder", "Wrist"], "Finger pulley"), TXT("what", "What happened", "pop on a crimp, swelling at the base of the ring finger", True)],
    "The climber reports {where} trouble: {what}. Sections: text on the likely category of issue in plain words (not a diagnosis), a table (Sign | Suggests | What to do), steps for the first 72 hours, bullets on what to avoid and how to return to climbing gradually, and a callout on signs (a pop with bowstringing, can't bend the finger, numbness, night pain) that need a clinician or hand specialist now.",
    "text, table, steps, bullets, callout", "Assess", "Taping up…"),
  T("pyramid", "Grade pyramid", "Send log → what's missing", "🔺",
    [LONG("log", "Recent sends", "V3 ×10, V4 ×6, V5 ×2, V6 ×0; 6b ×5, 6b+ ×2 redpoint"), TXT("goal", "Goal", "V6 by December")],
    "Analyse this send log toward the goal '{goal}': {log}. Sections: kv (pyramid shape, the gap holding the goal back, realistic timeline), a table (Grade | Sends | Needed for a healthy pyramid | Priority), bullets of style biases to fix (slab vs overhang, crimps vs slopers, static vs dynamic), and steps for the next 4 sessions.",
    "kv, table, bullets, steps", "Analyse", "Stacking sends…"),
  T("trip", "Trip prep", "Gear, days, skin, safety", "🎒",
    [TXT("where", "Destination & dates", "Fontainebleau, 5 days in October", True), CH("with", "Group", ["Solo", "Partner", "Group"], "Partner")],
    "Prepare a climbing trip to {where} travelling as '{with}' for the profile discipline. Sections: a checklist of gear grouped by category with pad or rope counts, a table (Day | Plan | Rest strategy | Skin care), bullets on local etiquette and conditions, and a callout on safety essentials (guidebook or app, partner checks, emergency numbers, telling someone your plan).",
    "checklist, table, bullets, callout", "Plan trip", "Packing pads…")],
 "Not medical advice and not a substitute for in-person instruction. Learn belaying, knots, gear placement and falling from a qualified instructor; check every knot and anchor; see a clinician for finger pops, numbness or swelling.")

# ---------------------------------------------------------------- 7. Skiing / snowboarding
APP("carve_coach", "Carve Coach", "Ski and snowboard better, from fix to first lift", "Sports", ["#0288D1", "#B3E5FC", "#FF6F00"], "sun",
 "Carve Coach fixes your skiing or snowboarding by symptom, builds pre-season leg and balance prep, plans a resort day for your level and the conditions, answers gear questions and explains off-piste basics you then learn properly on a course.",
 "You are a ski-school instructor who also rides: friendly, drill-based, one fix at a time, matching terrain to ability; you never send anyone off-piste without beacon, shovel, probe, training and a partner.",
 "Which way do you point?", "Discipline and level shape every drill and plan.", ["Technique fixes by symptom", "6-week pre-season prep", "Day plans for your level and the snow"],
 [NAME, CH("discipline", "Discipline", ["Ski", "Snowboard", "Both"]), CH("level", "Level", ["First week", "Blues", "Reds / blacks", "Off-piste / park"]), CH("days", "Days per season", ["1–5", "6–15", "15+"])],
 [T("fix", "Fix my technique", "Symptom → drills in order", "🎿",
    [PHOTO("Photo or video still (optional)"), CH("symptom", "Symptom", ["Skidding not carving", "Leaning back", "Catching edges", "Can't link turns", "Legs burn fast", "Scared on steeps", "Bumps / moguls", "Powder"], "Skidding not carving"), TXT("detail", "More detail", "worse on my left turns")],
    "Coach the profile discipline and level for '{symptom}' from the photo (if attached) and this detail (if given): {detail}. Sections: text with the root cause in 2 sentences, steps for 3 drills in order (terrain, what to feel, reps), a table (Fault | What you feel | Fix cue), and a callout on the terrain to practise on and the terrain to avoid until it's fixed.",
    "text, steps, table, callout", "Coach me", "Setting the edge…"),
  T("prep", "Pre-season prep", "Legs, balance, knees", "🦵",
    [CH("weeks", "Weeks until trip", ["3", "6", "10"], "6"), CH("kit", "Training kit", ["Bodyweight", "Gym", "Bike / running"], multi=True), TXT("body", "Injuries / concerns", "old ACL, weak ankles")],
    "Write a {weeks}-week pre-season plan using {kit} with these concerns: {body}, for the profile discipline and level. Sections: a table (Week | Session 1 | Session 2 | Session 3 | Focus), steps for the 5 key exercises with reps (wall sits, lateral hops, single-leg balance, step-downs, hip hinges), bullets on progression and on the last 3 days before the trip, and a callout on knee safety.",
    "table, steps, bullets, callout", "Build plan", "Wall sit…"),
  T("day", "Plan my mountain day", "Where, when and why", "🗺️",
    [TXT("resort", "Resort", "Val Thorens", True), TXT("conditions", "Conditions / forecast", "20 cm overnight, sunny then clouding over, -8°C"), CH("group", "Group", ["Solo", "Same level", "Mixed levels", "With kids"], "Same level")],
    "Plan a day at {resort} for the profile level with conditions {conditions} and group '{group}'. Sections: a table (Time | Terrain type or area | Why now | Watch for), a checklist for the morning (layers, goggle lens, sunscreen, water, pass, lift map, meeting point), bullets on managing the group's energy and confidence, and a callout on sun, cold, flat light and end-of-day fatigue risk.",
    "table, checklist, bullets, callout", "Plan day", "Checking lifts…"),
  T("gear", "Gear & setup", "Length, tune, boots, bindings", "🔧",
    [CH("question", "Question", ["What length / size", "Tune & wax", "Boot pain", "Binding setup", "Rent vs buy", "Helmet & goggles"], "What length / size"), TXT("stats", "Height, weight, current gear", "178 cm, 80 kg, 170 cm all-mountain skis")],
    "Answer '{question}' for the profile discipline and level with stats: {stats}. Sections: kv with the specific recommendation (numbers or settings), a table (Option | Best for | Trade-off | Price band), bullets on what to ask in the shop, and a callout on what must be done by a technician (binding DIN, boot fitting) rather than at home.",
    "kv, table, bullets, callout", "Advise me", "Waxing…"),
  T("offpiste", "Off-piste basics", "Orientation before the course", "⚠️",
    [CH("topic", "Topic", ["Avalanche danger scale", "Beacon, shovel, probe", "Reading terrain", "Tree wells", "Going with a guide", "First ski-touring day"], "Avalanche danger scale")],
    "Explain '{topic}' for a recreational rider at the profile level. Sections: text with the essentials in plain words, a checklist of what to have and check before leaving the piste, bullets of the most common fatal mistakes, kv (rule-of-thumb numbers such as danger levels and slope angles), and a callout stating this is orientation only and that a certified avalanche course plus a guide are required before going off-piste.",
    "text, checklist, bullets, kv, callout", "Explain", "Reading bulletin…")],
 "Not a substitute for lessons, a guide or an avalanche course. Ride within your ability, wear a helmet, and never leave the piste without training, equipment and a partner.")

# ---------------------------------------------------------------- 8. Surfing
APP("surf_lineup", "Dawn Patrol", "Read the forecast, pick the board, catch more waves", "Sports", ["#00838F", "#F4D19B", "#FF7043"], "drop",
 "Dawn Patrol reads the surf forecast for you, picks the right board for the day, coaches your pop-up and turns, explains rips and etiquette, and keeps you surf-fit through landlocked weeks.",
 "You are a surf coach and lifeguard: stoked but safety-first, honest about board volume and conditions, explaining waves in plain language and always respecting the locals.",
 "Where do you surf?", "Your level, boards and home break shape every tip.", ["Forecast → go or no-go", "Board picks for the day", "Pop-up, turns and etiquette"],
 [NAME, CH("level", "Level", ["Whitewater", "Catching green waves", "Starting to turn", "Intermediate+"]), TXT("boards", "Boards you own", "8' foamie, 7'2 mini-mal"), TXT("home", "Home break", "Fistral, beach break")],
 [T("forecast", "Read the forecast", "Paste it → go or skip", "🌊",
    [LONG("forecast", "Paste the forecast", "Swell 1.2 m @ 11 s WSW, wind 15 kt NE offshore, high tide 09:40, low 15:50"), CH("when", "When", ["Dawn", "Mid-morning", "Lunch", "Afternoon", "Evening"], "Mid-morning")],
    "Interpret this forecast for the profile level and home break, planning to surf {when}: {forecast}. Sections: kv (verdict go / maybe / skip, expected wave face height, wind effect, best tide window), a table (Time | Tide | Wind | Expected quality), bullets on which of the profile boards to bring and why, and a callout on hazards (rips, size, crowds, cold) at this level.",
    "kv, table, bullets, callout", "Read it", "Checking the cam…"),
  T("board", "Board picker", "Volume, shape, three options", "🏄",
    [TXT("stats", "Height & weight", "175 cm, 78 kg", True), CH("goal", "Next board is for", ["Progressing to green waves", "Learning to turn", "Small summer days", "Bigger winter days", "Travel"], "Learning to turn")],
    "Recommend a next board for stats {stats}, the profile level and goal '{goal}'. Sections: kv (shape, length, width, thickness, volume in litres, fin setup), cards for 3 options (meta = volume · price band), a table (Option | Paddle | Turning | Forgiveness), and bullets on what to check when buying second-hand.",
    "kv, cards, table, bullets", "Pick board", "Measuring litres…"),
  T("technique", "Fix my surfing", "Pop-up, nosedives, turns", "📷",
    [PHOTO("Photo or video still (optional)"), CH("issue", "Problem", ["Pop-up too slow", "Nosediving", "Missing waves", "Can't get past the whitewater", "Stuck going straight", "Bottom turn", "Cutback"], "Pop-up too slow")],
    "Coach '{issue}' from the photo (if attached) for the profile level and boards. Sections: text on the root cause in 2 sentences, steps for 2 on-land drills and 1 in-water drill with reps, a table (What you're doing | What to do instead | Cue), and a callout on the one habit that fixes most of this.",
    "text, steps, table, callout", "Coach me", "Watching the set…"),
  T("safety", "Rips, etiquette, hazards", "Plain-language ocean sense", "🚩",
    [CH("topic", "Topic", ["Spotting a rip", "Caught in a rip", "Priority & drop-ins", "Paddling out on a bigger day", "Surfing a new spot", "Cold-water surfing", "Reef breaks"], "Spotting a rip")],
    "Explain '{topic}' for the profile level. Sections: text in plain language, steps for exactly what to do, bullets of the signs to look for, a quote with what to say to a local or a lifeguard, and a callout on when not to paddle out at all.",
    "text, steps, bullets, quote, callout", "Explain", "Scanning the water…"),
  T("fitness", "Landlocked training", "Paddle, pop-up, balance", "💪",
    [CH("weeks", "Weeks until next surf", ["2", "4", "8"], "4"), CH("kit", "Kit", ["Bodyweight", "Gym", "Pool", "Balance board"], multi=True)],
    "A {weeks}-week surf-fitness plan with {kit} for the profile level. Sections: a table (Week | Paddle strength | Pop-up & mobility | Balance & legs | Breath work), steps for the 5 core exercises with reps, bullets on shoulder care for paddling, and a callout on breath-hold training safety (never alone, never in water without supervision).",
    "table, steps, bullets, callout", "Build plan", "Paddling on land…")],
 "Not a substitute for lessons or lifeguard advice. Surf within your ability, never alone at unfamiliar spots, and if in doubt, don't go out.")

# ---------------------------------------------------------------- 9. Golf
APP("fairway_fix", "Fairway Fix", "Fix the ball flight, play the smart shot, score lower", "Sports", ["#2E7D32", "#FDD835", "#795548"], "pin",
 "Fairway Fix diagnoses swing faults from your ball flight, builds a club-distance chart, plans strategy hole by hole, fixes chipping and putting, and turns range time into practice that actually lowers your handicap.",
 "You are a teaching pro: ball-flight first, one swing thought at a time, more interested in course management and the short game than in a pretty swing.",
 "Let's lower that number", "Your handicap and usual miss shape every fix.", ["Swing fixes from your ball flight", "Hole-by-hole strategy", "Short game and putting plans"],
 [NAME, TXT("handicap", "Handicap / typical score", "18, shoot mid-90s"), CH("miss", "Usual miss", ["Slice", "Hook", "Fat", "Thin", "Push", "Pull", "Inconsistent"]), CH("hand", "Plays", ["Right-handed", "Left-handed"])],
 [T("flight", "Fix my ball flight", "Club + flight → cause and drill", "⛳",
    [CH("club", "Club", ["Driver", "Fairway wood / hybrid", "Long iron", "Mid iron", "Short iron / wedge"], "Driver"), CH("flight", "Ball flight", ["Slice", "Hook", "Push", "Pull", "Fat", "Thin / topped", "Sky", "Low and weak"], "Slice"), PHOTO("Photo at address or top of swing (optional)")],
    "Diagnose a {flight} with the {club} from the photo (if attached) for the profile handedness and usual miss. Sections: text on the likely face-and-path cause in 2 sentences, a table (Possible cause | How to check | Fix | Drill), steps for one range drill with ball counts, and a quote with a single swing thought for the next round.",
    "text, table, steps, quote", "Diagnose", "Reading the divot…"),
  T("yardage", "Club distance chart", "Carries, gaps, partial wedges", "📏",
    [LONG("shots", "Your carry distances or recent shots", "driver 220, 7i 145, PW 110, SW 80…")],
    "Build a yardage chart from: {shots}, filling gaps sensibly for the profile handicap. Sections: a table (Club | Carry | Total | Gap to next | Note), bullets flagging gaps or overlaps in the set, kv (three-quarter and knock-down yardages for the wedges), and a callout on measuring properly (launch monitor or marked range, 10-shot average, ignore the best one).",
    "table, bullets, kv, callout", "Build chart", "Pacing it off…"),
  T("hole", "Play this hole", "Shot-by-shot strategy", "🧭",
    [TXT("hole", "Hole description", "par 4, 380 yds, water left of fairway at 240, bunkers right of green", True), CH("wind", "Wind", ["Calm", "Into", "Downwind", "Left-to-right", "Right-to-left"], "Calm")],
    "Plan this hole: {hole}, with wind '{wind}', for the profile handicap and usual miss. Sections: steps shot by shot (club, target, miss side to favour), a table (Option | Risk | Reward | Choose if…), bullets on where a bogey is fine and where to stay away from, and a quote with the pre-shot commitment sentence.",
    "steps, table, bullets, quote", "Plan hole", "Reading the wind…"),
  T("short", "Short game & putting", "Chips, pitches, bunkers, putts", "🕳️",
    [CH("skill", "Skill", ["Chipping", "Pitching", "Bunker", "Lag putting", "Short putts", "Green reading"], "Chipping"), TXT("problem", "What goes wrong", "blade it across the green or duff it into the bunker")],
    "Coach '{skill}' with the problem: {problem}, for the profile handicap. Sections: kv (setup: ball position, weight, shaft lean, club choice), steps for a 20-minute practice game with scoring, a table (Fault | Cause | Fix), and a callout on the tour-pro technique the profile should NOT copy.",
    "kv, steps, table, callout", "Coach me", "Opening the face…"),
  T("range", "Range session", "Practice that transfers to the course", "🪣",
    [CH("minutes", "Minutes", ["30", "45", "60", "90"], "45"), CH("where", "Where", ["Range only", "Range + short-game area", "Putting green only", "Simulator"], "Range + short-game area")],
    "Design a {minutes}-minute practice session at '{where}' for the profile handicap and usual miss. Sections: a table (Block | Minutes | Drill | Balls | Success measure), steps for a warm-up, bullets on making it random (change club and target every shot) rather than blocked, and a callout on what to record afterwards.",
    "table, steps, bullets, callout", "Plan session", "Buying a bucket…")],
 "Warm up before swinging and stop for back, wrist or elbow pain; not medical advice.")

# ---------------------------------------------------------------- 10. Tennis
APP("baseline_tennis", "Baseline", "Stroke fixes, serve clinics and match tactics", "Sports", ["#D84315", "#C6FF00", "#1565C0"], "flame",
 "Baseline fixes your tennis strokes and serve one cue at a time, builds tactics against the opponent in front of you, plans practice with a partner, wall or machine, and turns match notes into a clear next step.",
 "You are a club tennis coach: technique by symptom, tactics before power, drill-driven, and honest that consistency beats winners for most players.",
 "What's your game?", "Level, backhand and playing style shape every drill.", ["Stroke and serve fixes", "Tactics against any opponent", "Practice plans with or without a partner"],
 [NAME, CH("level", "Level (NTRP-style)", ["2.5 beginner", "3.0", "3.5", "4.0", "4.5+"]), CH("backhand", "Backhand", ["Two-handed", "One-handed"]), CH("style", "Style", ["Baseliner", "All-court", "Serve & volley", "Counterpuncher", "Not sure"])],
 [T("stroke", "Fix a stroke", "Symptom → cause, drill, cue", "🎾",
    [CH("stroke", "Stroke", ["Forehand", "Backhand", "Volley", "Overhead", "Slice", "Return"], "Forehand"), CH("symptom", "Symptom", ["Into the net", "Long", "Framing / shanks", "No pace", "Wide / no control", "Late on fast balls"], "Long"), PHOTO("Photo or video still (optional)")],
    "Diagnose a {stroke} going '{symptom}' from the photo (if attached) for the profile level and backhand type. Sections: text on the most likely cause in 2 sentences, a table (Cause | How to check | Fix | Shadow drill), steps for a progressive drill (drop-feed → cooperative rally → live points), and a quote with one cue to say before each ball.",
    "text, table, steps, quote", "Diagnose", "Watching contact…"),
  T("serve", "Serve clinic", "Toss, contact, targets, ball counts", "🎯",
    [CH("goal", "Work on", ["First-serve consistency", "More pace", "Kick serve", "Slice serve", "The toss", "Second-serve confidence"], "First-serve consistency"), NUM("balls", "Balls available", "30")],
    "A serve session on '{goal}' with {balls} balls for the profile level. Sections: kv (stance, grip, toss position, contact point, target), steps for a drill sequence with ball counts that add up to {balls}, a table (Fault | What you'd see | Fix), and a callout on shoulder and back care for serving volume.",
    "kv, steps, table, callout", "Build session", "Tossing…"),
  T("tactics", "Beat this opponent", "Scout → game plan", "♟️",
    [LONG("opp", "Describe them", "big forehand, weak backhand, hates the net, gets nervous at 30-30"), CH("format", "Match", ["Singles", "Doubles"], "Singles")],
    "Build a {format} game plan for the profile style and level against: {opp}. Sections: bullets with a 3-point game plan, a table (Situation | Their tendency | Your play), steps for the first 4 games (what to test), a callout on what to change if it isn't working by mid-first-set, and a quote with a between-points reset line.",
    "bullets, table, steps, callout, quote", "Plan match", "Scouting…"),
  T("practice", "Practice plan", "Partner, wall, machine or feed", "🧱",
    [CH("with", "Practising with", ["A partner", "A wall", "Ball machine", "Coach feed"], "A partner"), CH("minutes", "Minutes", ["30", "60", "90"], "60"), CH("focus", "Focus", ["Consistency", "Footwork", "Net play", "Serve + return", "Match play"], "Consistency")],
    "A {minutes}-minute session with {with} on '{focus}' for the profile level. Sections: a table (Block | Minutes | Drill | Target or scoring), steps for a warm-up with a mini-tennis progression, bullets on keeping a practice partner engaged so both get reps, and a callout on when to stop for elbow or shoulder pain.",
    "table, steps, bullets, callout", "Plan it", "Opening a can…"),
  T("match", "Review my match", "Notes → the stat that decided it", "📓",
    [LONG("notes", "Match notes (score, what happened)", "lost 4-6 6-3 4-6, 8 double faults, won most net points, lost the long rallies"), CH("feel", "How it felt", ["Nervous", "Fine", "Frustrated", "Confident"], "Fine")],
    "Review this match (it felt {feel}): {notes}. Sections: kv (result summary, the stat that decided it, biggest strength shown), a table (Pattern | Evidence | Next step), bullets of 2 things to keep doing, steps for the next 2 practice sessions, and a quote with one line to write in the notebook.",
    "kv, table, bullets, steps, quote", "Review", "Rewinding…")],
 "Not medical advice; see a clinician for persistent elbow, shoulder or wrist pain.")
