from dsl import *
FIN = "General information, not financial, tax or legal advice; rules, thresholds and entitlements differ by country and change — confirm with official sources or a regulated adviser before acting."
IMM = "General information, not financial, tax, legal or immigration advice; rules differ by country and by your status and change often — check official sources, a registered adviser or a recognised migrant-support charity."
SEP = "General information, not legal or financial advice; separation and tenancy rules differ by country and by whether you are married — speak to a solicitor, mediator or free advice service before signing or paying anything."

# ---------------------------------------------------------------- students
APP("term_purse", "Term Purse", "Make the loan drop last until the next one", "Finance", ["#3949AB", "#FFB300", "#26A69A"], "hat",
 "Term Purse turns each student loan or grant instalment into a weekly allowance that survives the whole term, plans around rent day and exam weeks, and finds the part-time hours that pay without wrecking your grades.",
 "You are a straight-talking student money mentor: you know rent eats the loan first, you never lecture about coffee, and you plan in weeks not months.",
 "Stretch the drop", "Tell us when money lands and what rent costs; we do the weekly maths.", ["Weekly allowance from each instalment", "Rent-day and exam-week planning", "Part-time hours that fit your timetable"],
 [NAME, CH("year", "Year of study", ["First", "Second", "Third+", "Postgrad"]), NUM("rent", "Monthly rent incl. bills", "550"), TXT("currency", "Currency", "GBP")],
 [T("stretch", "Stretch this instalment", "Lump sum → weekly allowance", "📆", [NUM("amount", "Instalment received", "2900"), NUM("weeks", "Weeks until the next one", "15"), TXT("fixed", "Fixed costs this term", "phone 15/mo, gym 20/mo, society fees 30")],
    "Instalment {amount} must last {weeks} weeks with the profile's monthly rent and these fixed costs: {fixed}. Sections: kv (total fixed for the period, safe-to-spend total, weekly allowance, a 'panic line' balance you must not go under before the next drop); table (Week | Opening balance | Rent/fixed due | Allowance | Closing balance) with one row per week; a callout on the two weeks most likely to blow the plan (arrival/freshers week, exam week, birthdays) and how much to hold back for them; bullets of 3 ways to cut the weekly figure if the allowance is under what you can live on.", "kv, table, callout, bullets", "Do the maths", "Stretching…"),
  T("hours", "Part-time hours math", "How many shifts you actually need", "🕒", [NUM("gap", "Monthly shortfall to cover", "180"), NUM("wage", "Hourly wage after tax", "10.5"), CH("load", "Course load", ["Light", "Normal", "Heavy (labs/placement)"], "Normal")],
    "Shortfall {gap} per month at {wage} per hour with a {load} course load. Sections: kv (hours per month needed, hours per week, shifts per week at 4-hour shifts, a maximum safe weekly cap for this course load); cards for 4 student-friendly job types (meta = typical hourly · flexibility · exam-season friendliness); a callout on the weekly hours where grades typically start to slide and how to raise exam weeks with a manager; a quote with a message asking for reduced hours during exams.", "kv, cards, callout, quote", "Count the hours", "Counting shifts…"),
  T("kit", "Course kit on a budget", "Textbooks, software, equipment", "📚", [LONG("list", "Reading list / kit list", "Organic Chemistry 9th ed, lab coat, graphics calculator, Adobe CC…"), NUM("budget", "Kit budget", "120")],
    "Kit list: {list}. Budget: {budget}. Sections: table (Item | Buy new | Used / older edition | Borrow / library / free alternative | Recommended route | Est. cost); a checklist of where to look, in order (library reserve, department loan, student-union sales, older editions, student software licences); a callout on the items you genuinely should not skimp on; kv (total at the recommended route vs budget, saving vs buying everything new).", "table, checklist, callout, kv", "Cut the kit cost", "Hunting bargains…"),
  T("emergency", "Money ran out", "Get to the next drop safely", "🆘", [NUM("left", "Money left", "40"), NUM("days", "Days until next instalment", "19"), TXT("owed", "Bills due before then", "rent 550 on the 1st")],
    "Only {left} left with {days} days to go and bills due: {owed}. Sections: steps in priority order for the next 48 hours (talk to accommodation office or landlord about a later rent date, university hardship fund, arranged-overdraft rules, food bank or community pantry, selling or pausing subscriptions); a checklist of what to gather for a hardship-fund application; a quote with an email to the university hardship or student-money team explaining the situation in under 120 words; a callout listing what NOT to do (payday loans, stacking buy-now-pay-later, ignoring rent) and reminding that student support services are confidential.", "steps, checklist, quote, callout", "Get me through", "Finding options…"),
  T("summer", "Summer gap plan", "No loan over the break", "☀️", [NUM("weeks", "Weeks of break", "14"), CH("plan", "This summer", ["Working full-time", "Paid internship", "Unpaid internship", "Living at home", "Staying in uni town"], "Working full-time"), NUM("costs", "Monthly costs over summer", "400")],
    "Summer: {weeks} weeks, plan: {plan}, monthly costs {costs}. Sections: kv (total summer cost, income needed, target savings to carry into next term, weekly allowance); table (Month | Income | Rent/costs | Save toward term | Notes); bullets on summer-only costs students forget (rent on an empty room, storage, travel home, local-tax rules for students); a callout on whether a summer sublet or a shorter contract makes sense for the profile.", "kv, table, bullets, callout", "Plan summer", "Planning summer…")], FIN)

# ---------------------------------------------------------------- couples: merging
APP("joint_jar", "Joint Jar", "Merge money with your partner without merging fights", "Finance", ["#AD1457", "#00897B", "#FFB74D"], "ring",
 "Joint Jar helps couples decide what's yours, mine and ours, split shared bills fairly when incomes differ, run a monthly money date, work through spending disagreements, and save for the goals you share.",
 "You are a calm couples money coach: fairness over equality, no scorekeeping, and you always give both partners a script.",
 "Two people, one plan", "A little about how you live and earn; nothing is shared with anyone.", ["Yours / mine / ours, designed for you", "Fair splits when incomes differ", "Money dates with an agenda"],
 [NAME, TXT("partner", "Partner's name", "Sam"), CH("stage", "Stage", ["Just moved in", "Living together a while", "Engaged", "Married", "Kids at home"]), CH("split", "Currently", ["Everything separate", "50/50 shared bills", "Proportional split", "One joint pot", "Not decided"])],
 [T("system", "Design our system", "Yours, mine, ours", "🏺", [NUM("income1", "Your monthly take-home", "2600"), NUM("income2", "Partner's monthly take-home", "1900"), NUM("shared", "Shared bills per month", "1850")],
    "Design a money system for the profile couple: you take home {income1}, your partner {income2}, shared bills are {shared}. Sections: cards for 3 systems (proportional split, one joint pot with equal personal allowances, 50/50 with a top-up from the higher earner), meta = fairness · simplicity · independence; table (Item | Who pays | From which account) for a typical month covering rent, groceries, subscriptions, debt, fun money; kv for the recommended system (each person's contribution, each person's personal money, joint buffer target); a callout on when to revisit the system (income change, baby, one partner studying or unemployed).", "cards, table, kv, callout", "Design it", "Balancing…"),
  T("fairsplit", "Fair split for a cost", "When incomes differ", "⚖️", [TXT("bill", "The cost", "holiday to Portugal 1400", True), CH("method", "Split by", ["Proportional to income", "Equal", "Whoever wanted it more", "Suggest one"], "Suggest one")],
    "Split {bill} using '{method}' for the profile couple. Sections: table (Method | Your share | Partner's share | Feels fair when…) comparing proportional, equal and a suggested hybrid; text recommending one for this specific cost and why; a quote with how to propose it to your partner in two sentences.", "table, text, quote", "Split it", "Weighing…"),
  T("date", "Monthly money date", "A 30-minute agenda", "🗓️", [TXT("month", "What happened this month", "overspent on eating out, car needs tyres"), CH("mood", "Mood going in", ["Fine", "Tense", "Avoiding it"], "Fine")],
    "Run a 30-minute money date; this month: {month}; mood: {mood}. Sections: steps with minutes for each agenda item (wins first, the numbers, upcoming costs, one decision, book the next date); kv (3 numbers to look at together); bullets of ground rules (no blame words, phones down, one topic parked if heated); a quote with an opening line that lowers the temperature.", "steps, kv, bullets, quote", "Set the agenda", "Lighting candles…"),
  T("clash", "We disagree about money", "Spender vs saver, and the rest", "🌧️", [LONG("issue", "What the disagreement is", "I think 300/month on takeaways is fine, they think it's reckless")],
    "Help the profile couple with: {issue}. Sections: text naming the pattern underneath (values, fear, childhood money scripts) without taking sides; table (Your view | Partner's view | What each is protecting); steps for a 20-minute conversation that ends in a one-month experiment; a quote with a sentence each partner could say to open; a callout on signs the issue is financial control rather than disagreement, and where to seek confidential support.", "text, table, steps, quote, callout", "Help us talk", "Listening…"),
  T("goal", "Save for a shared goal", "Deposit, wedding, trip, baby", "🎯", [TXT("goal", "The goal", "house deposit 30,000", True), TXT("by", "Target date", "in 3 years"), NUM("saved", "Already saved", "6000")],
    "Shared goal {goal} by {by}, already saved {saved}. Sections: kv (amount still needed, monthly total, a fair monthly split for each partner based on the profile's current arrangement, expected date at that pace); table (Milestone | Amount | Month) with 5 checkpoints; bullets of 4 ways to shorten it; a callout on keeping goal money separate from the emergency buffer and being clear whose name the account is in.", "kv, table, bullets, callout", "Plan the goal", "Saving up…")], FIN)

# ---------------------------------------------------------------- couples: separating
APP("untangle_money", "Untangle", "Separate your money after a breakup, fairly and fast", "Finance", ["#455A64", "#EF6C00", "#7E57C2"], "scale",
 "Untangle helps couples who are splitting up divide shared money calmly: who keeps what, closing joint accounts and subscriptions, settling the deposit and the furniture, rebuilding a solo budget, and the messages that get you paid back.",
 "You are a practical, neutral separation money guide: you keep score only where it matters, protect both people from rash moves, and know when a lawyer or mediator is worth the fee.",
 "Split the money, keep your head", "A few facts about the situation keep the advice relevant.", ["A fair division of shared things", "Joint accounts and bills, closed cleanly", "Scripts for the awkward messages"],
 [NAME, CH("status", "Legal status", ["Unmarried, living together", "Married / civil partnership", "Engaged", "Not sure"]), CH("home", "Home", ["Renting together", "One of us owns it", "Own together", "Neither / other"]), TXT("country", "Country / region", "UK")],
 [T("inventory", "Divide what's shared", "Furniture, deposit, pets, debt", "📦", [LONG("items", "Shared things & money", "sofa 900 (I paid), deposit 1500 (split), joint credit card 1200 owed, the dog…"), CH("style", "You want to be", ["Strictly fair", "Generous to move on", "Firm, they've been unfair"], "Strictly fair")],
    "Shared items and money: {items}; approach: {style}. Sections: table (Item | Who paid / whose name | Suggested outcome | Reasoning); kv (net balancing payment and who pays whom); a callout on items that are legally different from 'stuff' (joint debt, tenancy deposits, pets, anything in one name only) and which need advice given the profile's status and region; a quote with a short neutral message proposing the split.", "table, kv, callout, quote", "Propose a split", "Untangling…"),
  T("accounts", "Close the joint stuff", "Accounts, bills, subscriptions", "✂️", [LONG("joint", "Everything joint", "joint current account, Netflix on my card, energy in both names, phone family plan…")],
    "Joint items: {joint}. Sections: checklist in the safest order (freeze new borrowing first, then bills, then subscriptions, then close accounts), one line per item with who does it; table (Item | Risk if left open | Action | Deadline); a callout on protecting your credit file from a joint account or shared address and on never emptying a joint account unilaterally; steps for the day you close the main joint account.", "checklist, table, callout, steps", "Make the list", "Cutting cords…"),
  T("housing", "Who stays, who goes", "Rent, deposit and moving costs", "🏠", [NUM("rent", "Monthly rent / mortgage", "1400"), NUM("deposit", "Deposit held", "1600"), CH("plan", "Likely outcome", ["I stay", "They stay", "Both leave", "Undecided"], "Undecided")],
    "Home cost {rent}, deposit {deposit}, likely outcome {plan}, home situation from the profile. Sections: table (Option | Monthly cost to you | Deposit handling | Notice / moving cost | Watch-outs) comparing you staying, them staying and both leaving; kv (cash you need to leave, or to stay alone, including first month and deposit); a callout on tenancy or ownership rules that vary by region (notice, release from a joint tenancy, landlord consent, who is liable) and that this is not legal advice; a quote with a message to the landlord or agent asking what is possible.", "table, kv, callout, quote", "Compare options", "Measuring rooms…"),
  T("solo", "My solo budget", "Life on one income again", "🧍", [NUM("income", "Your monthly take-home", "2300"), LONG("costs", "Your new costs", "rent 950, transport 90, phone 20, groceries 250…")],
    "Rebuild a single budget: income {income}, costs {costs}. Sections: table (Category | Amount | Share of income | Adjust?); kv (left over per month, emergency-fund target for a solo household, weeks to reach it); bullets of 5 costs that quietly doubled after the split and how to soften each; a callout on the first 3 months being the expensive ones and what to tell yourself about it.", "table, kv, bullets, callout", "Rebuild", "Resetting…"),
  T("message", "Write the money message", "Ask for what you're owed, calmly", "✉️", [LONG("situation", "What you need to say", "they owe me 400 for the last month's bills and haven't replied in 2 weeks"), CH("tone", "Tone", ["Warm", "Neutral", "Firm", "Final notice"], "Neutral")],
    "Draft a message about: {situation}, tone {tone}. Sections: quote with the message (under 120 words, one clear ask, a date, no raking over history); bullets on what to do if there is no reply (keep a written record, mediation or small-claims as general options, when to let it go); a callout on keeping evidence (screenshots, bank records) and avoiding anything that reads as a threat.", "quote, bullets, callout", "Write it", "Choosing words…")], SEP)

# ---------------------------------------------------------------- new parents
APP("cradle_costs", "Cradle Costs", "Budget for the baby before the baby arrives", "Finance", ["#EC407A", "#29B6F6", "#FFCA28"], "baby",
 "Cradle Costs prices the first year of a baby, plans the income dip during parental leave month by month, works out whether going back to work pays after childcare, trims the buy-list to what newborns actually need, and lists the support to check for.",
 "You are a warm, numbers-first new-parent money planner: you separate marketing from need, plan the leave gap month by month, and never shame either parent's choice.",
 "Plan the year before it starts", "Due date, income and leave plans make the numbers real.", ["A first-year cost forecast", "Parental-leave cash plan, month by month", "Childcare vs going back to work, in numbers"],
 [NAME, TXT("due", "Due date / baby's age", "due 14 March"), NUM("income", "Household monthly take-home now", "4200"), TXT("country", "Country / region", "Ireland")],
 [T("buylist", "The buy list, trimmed", "Need, nice, skip", "🍼", [CH("budget", "Setup budget", ["Under 300", "300–800", "800–1500", "No fixed limit"], "300–800"), CH("space", "Home", ["Small flat", "House", "Sharing with family"], "Small flat"), TXT("have", "Already have / offered", "cot from sister, pram gifted")],
    "Build a newborn setup list for budget {budget}, home {space}, already have: {have}. Sections: table (Item | Need / Nice / Skip | New vs second-hand | Est. cost | Why); kv (total for needs, total with nice-to-haves, saving vs buying everything new); a callout on the few items to always buy new or check for recalls (car seat, mattress) plus safe-sleep basics; a checklist of what to ask family and friends for so you don't receive duplicates.", "table, kv, callout, checklist", "Trim the list", "Sorting the nursery…"),
  T("leave", "Parental-leave cash plan", "The income dip, month by month", "📉", [LONG("leave", "Leave plans and pay", "me: 6 months at 90% then 3 months statutory; partner: 2 weeks full pay"), NUM("costs", "Household monthly costs", "3300"), NUM("savings", "Savings now", "5000")],
    "Leave and pay: {leave}; household costs {costs}; savings {savings}; current income from the profile. Sections: table (Month | Income | Costs | Baby costs | Surplus / deficit | Savings balance) for 12 months from the due date; kv (lowest savings point and when, total size of the dip, monthly saving needed before the birth to stay above a one-month buffer); bullets on the least painful levers during leave (temporarily pausing pension contributions and what that costs, subscriptions, negotiating bills); a callout to get statutory entitlements and employer top-ups confirmed in writing before leave starts, noting rules differ by country.", "table, kv, bullets, callout", "Plan the dip", "Forecasting…"),
  T("childcare", "Back to work or not?", "Childcare vs salary, honestly", "🧮", [NUM("salary", "Returning parent's monthly take-home", "2400"), NUM("care", "Childcare cost per month", "1100"), CH("days", "Days per week", ["5", "4", "3", "2"], "5")],
    "Returning salary {salary}, childcare {care}, {days} days per week. Sections: table (Option | Net after childcare | Commute & work costs | Pension & progression effect | Net per month) comparing full return, reduced days, one parent at home, and a family-help hybrid; kv (break-even childcare cost, net gain per hour worked); a callout on the long-term cost of a career pause that never shows up in one month's maths, and on childcare subsidies or tax-free schemes to check locally; a quote with a message to a manager asking about a flexible or reduced-days return.", "table, kv, callout, quote", "Run the numbers", "Balancing…"),
  T("monthly", "First-year monthly budget", "What a baby costs each month", "📆", [CH("feeding", "Feeding", ["Breastfeeding", "Formula", "Mixed"], "Mixed"), CH("nappies", "Nappies", ["Disposable", "Cloth", "Mix"], "Disposable"), CH("stage", "Stage", ["0–3 months", "3–6 months", "6–12 months"], "0–3 months")],
    "Monthly baby budget for {stage}, feeding: {feeding}, nappies: {nappies}. Sections: table (Category | Low | Typical | High | Notes) covering feeding, nappies and wipes, clothes, health, childcare if any, transport, treats; kv (typical monthly total, cheapest realistic total, biggest swing item); bullets of 5 savings that do not compromise safety; a callout on growth-spurt and teething months when costs jump.", "table, kv, bullets, callout", "Show the budget", "Counting nappies…"),
  T("entitle", "What we're entitled to", "Benefits, leave and grants to check", "🗂️", [CH("work", "Work situation", ["Both employed", "One employed", "Self-employed", "Student / unemployed", "Mixed"], "Both employed")],
    "For a new-parent household with {work} in the profile's region, list the kinds of support to check. Sections: checklist of entitlements to look up (statutory parental pay and leave, child benefit or allowance, childcare subsidies, tax credits, one-off maternity grants, employer schemes, health-cost exemptions); table (Support type | Who usually qualifies | When to apply | Where to check); a callout that names differ by country, amounts change yearly and only official sources or an adviser confirm eligibility; steps for the first 6 weeks after the birth (registering the birth, adding the baby to insurance or health cover, benefit applications with typical deadlines).", "checklist, table, callout, steps", "Show the list", "Checking…")], FIN)

# ---------------------------------------------------------------- freelancers
APP("even_keel", "Even Keel", "Pay yourself a steady salary from lumpy freelance income", "Finance", ["#00695C", "#FFA000", "#5C6BC0"], "graph",
 "Even Keel turns feast-and-famine freelance income into a steady monthly salary: a buffer target, tax and holiday pots, pre-funded time off, a lean-month cash plan and a monthly review that fits on one screen.",
 "You are a freelancer's financial operations partner: unflappable, pot-based, and honest that the buffer is the product.",
 "Smooth the lumps", "Your income pattern and fixed costs shape the salary you can pay yourself.", ["A monthly salary you can rely on", "Tax, holiday and buffer pots", "Lean-month cash plans before the panic"],
 [NAME, TXT("work", "What you do", "freelance illustrator"), NUM("costs", "Personal monthly costs", "2100"), TXT("currency", "Currency", "EUR")],
 [T("salary", "Pay myself a salary", "From the last 6–12 months", "💶", [LONG("months", "Income by month, last 6–12 months", "Jan 1200, Feb 4800, Mar 900, Apr 3100…"), NUM("buffer", "Business buffer now", "3500")],
    "Monthly income history: {months}; buffer {buffer}; personal costs from the profile. Sections: kv (average monthly income, worst 3-month average, recommended monthly salary, buffer target in months of costs, months to reach it); table (Month | Income | Salary paid | To tax pot | To buffer | Buffer balance) replaying the history with the recommended salary to show whether it would have held; a callout with the rule for when to raise the salary and when to cut it; bullets on keeping business and personal accounts separate.", "kv, table, callout, bullets", "Set my salary", "Smoothing…"),
  T("pots", "Set up my pots", "Tax, holiday, sick, pension", "🫙", [NUM("rate", "Rough tax + contributions rate %", "28"), CH("holiday", "Paid weeks off per year", ["2", "4", "6", "8"], "4"), CH("pension", "Pension saving", ["None yet", "5% of income", "10% of income", "15%+"], "5% of income")],
    "Design pots with an estimated tax rate of {rate}%, {holiday} weeks of holiday per year, pension {pension}. Sections: table (Pot | % of every payment | Purpose | Minimum balance | When you touch it); steps for the day an invoice is paid (the split order); kv (worked example of a 2000 payment split across the pots); a callout that the tax percentage is a planning estimate to confirm with an accountant or official calculator, and on separate-account habits.", "table, steps, kv, callout", "Build the pots", "Labelling jars…"),
  T("timeoff", "Take time off", "Pre-fund a holiday or a break", "🏝️", [NUM("weeks", "Weeks off", "3"), TXT("when", "When", "August"), NUM("pot", "Holiday pot now", "600")],
    "Plan {weeks} weeks off in {when} with {pot} already in the holiday pot, using the profile's costs and work. Sections: kv (cost of the break in lost income plus living costs, amount to add per month between now and then, client-notice date, minimum work to line up for the return); table (Month | Extra to save | Pot balance); a quote with a client notice message that protects the booking; a callout on sick-pay gaps for freelancers and income-protection insurance as something to price, in general terms.", "kv, table, quote, callout", "Fund the break", "Packing…"),
  T("lean", "Lean-month mode", "The pipeline dried up", "🌵", [NUM("cash", "Cash across all pots", "2800"), TXT("pipeline", "What's in the pipeline", "one 1500 invoice due in 3 weeks, a maybe-project in May")],
    "Cash {cash}, pipeline: {pipeline}, monthly costs from the profile. Sections: kv (weeks of runway, the date to trigger emergency mode, minimum income needed this month); table (Pot | Draw from it? | Order | Repay rule) deciding which pots to raid and in what order; steps for cutting costs in order of least pain; a callout on what not to do (undercut long-term rates, borrow at high cost, raid the tax pot without a repayment date).", "kv, table, steps, callout", "Make a plan", "Rationing…"),
  T("review", "Monthly review", "Numbers, late invoices, one decision", "📊", [LONG("numbers", "This month's numbers", "invoiced 3400, paid 2100, spent 2300, late invoices: 1800 from Acme")],
    "Review: {numbers} against the profile's costs. Sections: kv (paid vs invoiced, salary covered?, buffer change, late total); bullets of 3 wins and 3 risks; table (Late invoice | Days late | Next action | Date); a callout with the single decision for next month.", "kv, bullets, table, callout", "Review", "Reading the month…")], FIN)

# ---------------------------------------------------------------- gig workers
APP("gig_gauge", "Gig Gauge", "Know what a shift really pays after fuel, wear and tax", "Finance", ["#F57C00", "#37474F", "#00ACC1"], "car",
 "Gig Gauge works out what delivery, rideshare and task-app work really pays per hour after fuel, vehicle wear, fees and tax, then plans the hours and zones to hit a weekly target, logs expenses from receipt photos and checks your tax set-aside.",
 "You are a sharp gig-economy accountant who has done the driving: brutally honest about true hourly rates, allergic to vanity earnings screenshots, and precise about mileage.",
 "Every shift, priced honestly", "Your vehicle and apps shape the true-cost maths.", ["True hourly rate after all costs", "Hours and zones to hit your weekly target", "Expense logs and a tax set-aside check"],
 [NAME, CH("vehicle", "Vehicle", ["Car (petrol/diesel)", "Car (EV)", "Scooter / motorbike", "E-bike", "Bicycle", "On foot"]), CH("apps", "Apps", ["Food delivery", "Rideshare", "Parcels / courier", "Grocery shopping", "Tasks / handyman", "Other"], multi=True), TXT("currency", "Currency", "USD")],
 [T("truerate", "True hourly rate", "A week's earnings, all costs out", "⏱️", [LONG("week", "This week's numbers", "Mon 6h 92 earned 45 miles; Tue 5h 70 earned 38 miles…"), NUM("fuel", "Fuel / charging cost per 100 km or miles", "12"), TXT("costs", "Other weekly costs", "insurance 25, phone data 5, bag rental 2")],
    "Week: {week}. Fuel cost {fuel} per 100 distance units, other weekly costs {costs}, vehicle from the profile. Sections: table (Day | Hours | Gross | Distance | Fuel | Wear & tear est. | Net | Net per hour); kv (gross hourly, true hourly, cost per distance unit including depreciation and maintenance, suggested tax set-aside on the net); a callout explaining the wear-and-tear assumption used for this vehicle type and how to override it; bullets of the 3 highest-leverage changes (best days, dead miles, multi-apping).", "table, kv, callout, bullets", "Show true rate", "Counting miles…"),
  T("target", "Hit my weekly target", "Hours and zones to plan", "🎯", [NUM("goal", "Take-home target this week", "600"), NUM("truehour", "Your true hourly rate", "14"), CH("avail", "Days you can work", ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], multi=True)],
    "Target {goal} at a true rate of {truehour} per hour on days {avail}. Sections: kv (hours needed, hours per available day, the cap where fatigue makes it unsafe); table (Day | Block | Hours | Why this block) using typical demand peaks for the profile's apps (lunch, dinner, weekend nights, bad weather); a checklist for every shift (charge, fuel level, snacks, offline breaks); a callout on rest, road safety and the point where an extra hour is no longer worth it.", "kv, table, checklist, callout", "Plan my week", "Mapping peaks…"),
  T("receipt", "Log an expense", "Photo of a receipt → the log line", "🧾", [PHOTO("Receipt or fuel-pump photo", "", True), CH("type", "Type", ["Fuel / charging", "Maintenance", "Insurance", "Equipment", "Phone / data", "Parking / tolls", "Other"], "Fuel / charging")],
    "Read the receipt photo as a {type} expense. Sections: kv (vendor, date, amount, tax portion if shown, category, likely deductible?); a quote with a one-line log entry in the format 'date | category | vendor | amount | note' ready to paste into a spreadsheet; a callout on what records to keep for this expense type and that deductibility depends on local rules.", "kv, quote, callout", "Log it", "Reading receipt…"),
  T("quarter", "Tax set-aside check", "Am I saving enough for the bill?", "🏦", [NUM("earned", "Net earnings this quarter so far", "5400"), NUM("saved", "Set aside so far", "600"), TXT("country", "Country / state", "Texas, USA")],
    "Earnings {earned}, set aside {saved}, location {country}, vehicle and apps from the profile. Sections: kv (an estimate range for income tax plus self-employment or social contributions, gap vs saved, weekly top-up needed to close it); table (Deduction type | Typical for gig work | Records needed) covering mileage vs actual costs, phone, equipment, platform fees; steps for a 20-minute monthly tax routine; a callout that this is a planning estimate only and that rates, thresholds and filing dates must be checked with official sources or a tax professional.", "kv, table, steps, callout", "Check set-aside", "Estimating…"),
  T("slow", "Slow week plan", "Demand dropped, bills didn't", "📉", [TXT("what", "What's happening", "rain all week, orders down 40%"), NUM("need", "Minimum I need this week", "350")],
    "Situation: {what}; minimum needed {need}; apps from the profile. Sections: steps to rescue the week (switch apps, change zone or hours, bonuses and quests, adjacent work like parcel drops or grocery shops); table (Option | Expected per hour | Setup effort | Risk); bullets on cost cutting that doesn't hurt earning capacity; a callout on the trap of chasing losses with unsafe hours.", "steps, table, bullets, callout", "Rescue the week", "Rerouting…")], FIN)

# ---------------------------------------------------------------- immigrants: settled, supporting family
APP("send_home", "Send Home", "Support family back home without sinking your own budget", "Finance", ["#6A1B9A", "#43A047", "#FFB300"], "globe",
 "Send Home helps immigrants balance remittances to family with rent, savings and a future here: a send-home amount you can sustain, kind but firm scripts for relatives' requests, building credit from zero, decoding your payslip and spotting the scams aimed at newcomers.",
 "You are a trusted community money mentor who has lived the newcomer years: respectful of family duty, protective of the person in front of you, and clear that rules differ by country.",
 "Two homes, one budget", "Where you live, what you earn and who depends on you shape every answer.", ["A remittance plan you can sustain", "Kind, firm scripts for family requests", "Credit from zero and payslips decoded"],
 [NAME, TXT("country", "Country you live in now", "Canada"), TXT("home", "Country family is in", "Philippines"), NUM("income", "Monthly take-home", "3100")],
 [T("ratio", "My send-home plan", "How much to send, sustainably", "🌏", [NUM("send", "Currently sending per month", "800"), NUM("costs", "Your essential costs here", "2100"), TXT("needs", "What the money covers at home", "parents' medicine, brother's school fees")],
    "Sends {send} per month, essentials {costs}, income from the profile, covering: {needs}. Sections: kv (left after essentials and sending, months of emergency buffer you hold, a sustainable send range, an amount to save here each month); table (Scenario | Send | Save here | Left for you | Buffer reached in) for current, sustainable and stretch levels; a callout on why an emergency fund here also protects the family at home (a job loss means sending stops entirely); bullets of 3 ways to lower the cost of what the money covers at home (paying the school or pharmacy directly, bulk-paying fees per term, agreeing one fixed monthly amount instead of ad-hoc top-ups).", "kv, table, callout, bullets", "Set my plan", "Balancing homes…"),
  T("family", "A request from family", "Say yes, no or not yet, kindly", "💬", [LONG("ask", "The request", "my cousin wants 1,500 for a motorbike for his business"), CH("answer", "You want to say", ["Yes, a smaller amount", "Not now", "No", "Yes, as a loan with terms", "Not sure"], "Not sure")],
    "Request: {ask}; leaning toward: {answer}. Sections: text weighing the request against the profile's situation without judging the family; table (Option | Cost to you | Effect on the relationship | How to say it); a quote with the message in warm, respectful language; a callout on patterns that signal a dependence that needs a family conversation, and on never borrowing at high interest in order to send.", "text, table, quote, callout", "Help me answer", "Choosing words…"),
  T("credit", "Build credit from zero", "No history here yet", "🧱", [CH("have", "You already have", ["A local bank account", "A secured card", "A phone contract", "Nothing yet"], multi=True), CH("goal", "Goal", ["Rent a flat", "Car loan", "Mortgage one day", "Just a normal card"], "Just a normal card")],
    "Already has: {have}; goal: {goal}; country from the profile. Sections: steps in order over 12 months (account, secured or credit-builder product, one small recurring bill, a utilisation rule, checking the report); table (Month | Action | What it does for the file); bullets of mistakes that set newcomers back (missed tiny bills, too many applications, co-signing for others); a callout that credit systems, bureaus and product names differ by country and to rely on official or regulator-listed sources.", "steps, table, bullets, callout", "Start building", "Laying bricks…"),
  T("payslip", "Decode my payslip", "Photo → what every line means", "🧾", [PHOTO("Photo of your payslip", "", True)],
    "Read the payslip photo. Sections: table (Line | Amount | What it is | Normal?) for every line; kv (gross, total deductions, net, effective deduction rate, hours or rate if shown); a callout flagging anything unusual (missing contributions, unexplained deductions, pay below what the hours suggest) with where to raise it (employer payroll first, then a labour or tax authority) and that this is not legal advice; bullets on which records to keep and for how long.", "table, kv, callout, bullets", "Decode", "Reading lines…"),
  T("scam", "Is this a scam?", "Paste the message, call or offer", "🚨", [LONG("msg", "The message, call or offer", "Text says my immigration file has a problem and I must pay a fee by gift card today…")],
    "Assess: {msg}, for someone in the profile's country. Sections: kv (verdict: scam / likely scam / suspicious / probably fine, confidence, the tactic being used); bullets of red flags found; steps for what to do now (do not pay, verify via an official number you look up yourself, report, protect accounts); a quote with a reply or script to end the contact; a callout listing common newcomer-targeted scams (immigration fees, fake jobs, rental deposits, 'government' calls) and reminding that officials never ask for gift cards or crypto.", "kv, bullets, steps, quote, callout", "Check it", "Sniffing…")], IMM)

# ---------------------------------------------------------------- students → first job
APP("first_payday", "First Payday", "Your first real salary, without the lifestyle creep", "Finance", ["#2E7D32", "#FF5252", "#1E88E5"], "coin",
 "First Payday helps new graduates and first-jobbers split the salary before it disappears, decide whether to overpay a student loan, check if moving out adds up, compare job offers beyond the headline number and plan the first 12 months.",
 "You are an older-sibling money mentor for first salaries: candid about lifestyle creep, pro employer pension match, and never boring.",
 "Salary in, plan ready", "Tell us what you'll earn and where you live now.", ["A split for every payday", "Student loan: overpay or not?", "Moving-out affordability, honestly"],
 [NAME, NUM("salary", "Annual salary (gross)", "29000"), CH("living", "Living", ["With family", "Shared house", "Renting alone", "With partner"]), TXT("country", "Country", "UK")],
 [T("split", "Split my first payday", "Where every unit of pay goes", "💸", [NUM("net", "Monthly take-home", "1950"), TXT("fixed", "Fixed costs", "rent 700, travel 120, phone 25, loan 60"), CH("goal", "Priority", ["Build a buffer", "Move out", "Clear debt", "Travel", "Invest early"], "Build a buffer")],
    "Take-home {net}, fixed costs {fixed}, priority {goal}, living situation from the profile. Sections: kv (fixed total, needs / wants / save split in amounts, buffer target of 3 months' fixed costs, months to reach it); table (Pot | Amount | Account | Day it moves) for an automatic payday routine; a callout on the employer pension match and why skipping it is the most expensive mistake; bullets naming 4 lifestyle-creep traps of the first year with a spend limit for each.", "kv, table, callout, bullets", "Split it", "Dividing…"),
  T("loan", "Student loan: overpay?", "The maths for your loan type", "🎓", [NUM("balance", "Loan balance", "42000"), NUM("rate", "Interest rate %", "6.2"), TXT("type", "Loan type / repayment rule", "UK Plan 2, 9% over the threshold")],
    "Balance {balance}, rate {rate}%, type: {type}, salary from the profile. Sections: text explaining how this loan type actually behaves (income-contingent with write-off vs a standard amortising loan) in plain words; table (Strategy | Monthly | Total paid | Years | Best when…) for minimum only, plus 100 per month, a lump sum, and prioritising other goals; kv (recommended stance for this profile and the one number that would change it); a callout that this is general information, loan rules change, and the official loan body is the source of truth.", "text, table, kv, callout", "Compare", "Crunching…"),
  T("moveout", "Can I move out?", "Rent, deposit, the real monthly", "🚪", [NUM("rent", "Rent you're looking at", "900"), NUM("bills", "Estimated bills + local tax", "220"), NUM("saved", "Saved so far", "1500")],
    "Rent {rent}, bills {bills}, saved {saved}, salary and living situation from the profile. Sections: kv (move-in cash needed: deposit, first month, furniture basics, fees where legal; shortfall vs saved; months to save it; rent as a share of take-home); table (Cost | One-off | Monthly | Notes) including the things first-timers forget (contents insurance, broadband setup, a bed); a callout with the affordability rule of thumb and a verdict for this case; a checklist for viewing and signing safely.", "kv, table, callout, checklist", "Check it", "Packing boxes…"),
  T("offer", "Compare job offers", "Salary is not the whole number", "🤝", [LONG("offers", "The offers", "A: 30k, 5% pension match, hybrid, 25 days. B: 33k, no match, fully office, 20 days, 1h commute")],
    "Offers: {offers}, home location from the profile. Sections: table (Factor | Offer A | Offer B | Annual value estimate) covering pay, pension match, commute cost and time, holiday, bonuses, training; kv (total compensation estimate for each, monthly net after commute for each, the tie-breaker question); a quote with a polite negotiation message to the lower offer; a callout on what to verify in the contract before accepting.", "table, kv, quote, callout", "Compare offers", "Weighing…"),
  T("year", "My first 12 months", "Milestones from payday one", "🗓️", [],
    "Build a 12-month money plan for the profile's first year on this salary. Sections: table (Month | Milestone | Amount | Why now) covering buffer, pension check, credit basics, tax-code check, first pay review; checklist for the first 30 days (payslip check, tax code, pension enrolment, bank account setup, automatic transfers); a callout on the annual tax and pay-review moments to put in the diary; a quote with a one-sentence rule to remember every payday.", "table, checklist, callout, quote", "Plan the year", "Sketching the year…")], FIN)

# ---------------------------------------------------------------- seasonal / term-time gig workers
APP("off_season", "Off Season", "Seasonal pay, year-round bills, one calm plan", "Finance", ["#0277BD", "#FFB74D", "#8D6E63"], "sun",
 "Off Season helps seasonal and term-time workers — tourism, ski and beach, agriculture, festivals, school staff — bank the busy months, spend the quiet ones without dread, decode seasonal contracts, and line up off-season income early.",
 "You are a seasonal-work money planner: you think in seasons not months, keep the peak-season cash boring, and know the off-season is where plans fail.",
 "Bank the peak, breathe the lull", "Your season shape makes the plan.", ["Peak-month saving targets", "An off-season allowance you can live on", "Bridge income lined up early"],
 [NAME, TXT("work", "Seasonal work", "ski instructor Dec–Apr"), TXT("peak", "Peak months", "Dec, Jan, Feb, Mar, Apr"), NUM("costs", "Monthly costs, year-round", "1500")],
 [T("cycle", "My year, month by month", "Peak saving → off-season allowance", "🔄", [NUM("peakpay", "Typical monthly take-home in peak", "3200"), NUM("offpay", "Typical monthly income off-season", "400"), NUM("saved", "Savings now", "1200")],
    "Peak pay {peakpay}, off-season income {offpay}, savings {saved}, peak months and costs from the profile. Sections: table (Month | Income | Costs | Save / draw | Balance) for the next 12 months starting this month; kv (required saving per peak month, off-season monthly allowance, lowest balance and its month, buffer beyond the plan); a callout on the month the plan is most fragile and one fix; bullets on annual costs to prepay during peak (insurance, licence renewals, equipment).", "table, kv, callout, bullets", "Map my year", "Turning seasons…"),
  T("bridge", "Off-season income ideas", "Matched to your skills", "🌉", [TXT("skills", "Skills and gear you have", "first-aid cert, a van, good with kids, speak French"), CH("want", "Off-season you want", ["Mostly rest", "Part-time income", "Full earning", "Travel + some work"], "Part-time income")],
    "Skills: {skills}, wanting: {want}, seasonal work from the profile. Sections: cards for 6 bridge-income options (meta = typical monthly · setup time · fits with rest?) ranging from opposite-season versions of the same job to remote and local work; table (Option | Lead time to arrange | Where to look | Start applying by); a callout on contract terms to check (return dates, exclusivity) so bridge work doesn't jeopardise the main season; steps for lining it up before peak ends.", "cards, table, callout, steps", "Find bridges", "Scouting…"),
  T("contract", "Read my seasonal contract", "Pay, hours, housing deductions", "📄", [LONG("terms", "Paste the pay and terms", "hourly 14.50, staff housing deducted 90/week, tips pooled, end-of-season bonus 500 if completed…")],
    "Terms: {terms}. Sections: kv (real weekly take-home after housing or meal deductions, effective hourly, bonus conditions, notice rules if stated); table (Clause | What it means | Watch-out | Question to ask); a callout on deductions that commonly exceed legal limits or push effective pay below minimum wage, noting that employment rules differ by country and this is not legal advice; a quote with 3 questions to email the employer before signing.", "kv, table, callout, quote", "Decode terms", "Reading fine print…"),
  T("taxes", "Uneven income and tax", "Refunds, thresholds, records", "🧾", [TXT("country", "Country / region", "Australia"), CH("status", "You're paid as", ["Employee", "Self-employed / contractor", "Both", "Not sure"], "Employee")],
    "For {country}, paid as {status}, with the profile's seasonal pattern, explain the tax shape of uneven income. Sections: text on why seasonal workers are often over- or under-withheld and what that means for refunds or bills; checklist of records to keep through the season (payslips, deductions, travel, equipment, housing); table (Moment | What to do | Why) for start of season, end of season and the year-end return; a callout that this is general information and thresholds, refunds and deadlines must be checked with the official tax body or an adviser.", "text, checklist, table, callout", "Explain", "Sorting papers…"),
  T("gear", "Kit and travel budget", "Getting to the season, equipped", "🎒", [TXT("season", "Next season", "summer camp counsellor, Maine, 10 weeks"), NUM("budget", "Budget for kit and travel", "700")],
    "Next season: {season}, budget {budget}. Sections: table (Item | Need / Nice | New / used / borrow | Est. cost) for travel, kit, deposits and the first week before pay; kv (total vs budget, first-payday cash gap, amount to arrive with); a checklist for the week before departure (insurance, bank notice, paperwork, phone plan); a callout on deposits and 'arrive with' rules employers may require.", "table, kv, checklist, callout", "Budget the kit", "Packing…")], FIN)

# ---------------------------------------------------------------- immigrants: just arrived
APP("landing_funds", "Landing Funds", "Make your arrival savings last until the first paycheck", "Finance", ["#C62828", "#00838F", "#FDD835"], "plane",
 "Landing Funds helps newcomers who arrive with limited savings stretch them until the first wage: a landing runway in weeks, setup costs in must/should/later order, a cheap-start guide, a fair-price check for rent, deposits and fees, and what to do if the money runs short.",
 "You are a practical resettlement money guide: calm, non-judgmental, fluent in deposits and 'proof of address' loops, and clear about where free help exists.",
 "Land on your feet", "Your savings, arrival plans and household size set the runway.", ["Weeks of runway, honestly counted", "Setup costs in the right order", "Fair-price checks before you pay"],
 [NAME, TXT("country", "Arriving in", "Germany"), NUM("savings", "Savings you land with", "4500"), CH("household", "Household", ["Just me", "Couple", "Family with kids", "Joining relatives"])],
 [T("runway", "My landing runway", "Weeks until the money's gone", "🛬", [TXT("housing", "Housing plan", "hostel 2 weeks, then a shared flat ~500/month + deposit"), TXT("job", "Job status", "job offer, first pay ~6 weeks after start"), NUM("weekly", "Weekly living costs estimate", "150")],
    "Housing: {housing}; job: {job}; weekly costs {weekly}; savings and household from the profile. Sections: kv (weeks of runway, cash needed until first pay, surplus or shortfall, the date to worry by); table (Week | Housing | Living | One-offs | Balance) until the first paycheck plus two weeks; a callout on the first-paycheck delay trap (pay in arrears, payroll cut-off dates) and what to ask HR on day one (pay date, cut-off, whether a first-month advance is possible); bullets of 3 adjustments if there is a shortfall.", "kv, table, callout, bullets", "Count my runway", "Counting weeks…"),
  T("setup", "Setup costs, in order", "Must, should, later", "🧰", [CH("have", "Already sorted", ["Phone / SIM", "Bank account", "Housing", "Transport pass", "Health cover", "Nothing yet"], multi=True), NUM("cap", "Amount you can spend on setup", "900")],
    "Already sorted: {have}; setup cap {cap}; country and household from the profile. Sections: table (Item | Must / Should / Later | Est. cost | Cheapest route | Depends on) covering SIM, bank, deposit, registration or ID fees, transport, bedding and kitchen basics, work clothes, health cover; kv (must total, should total, what fits under the cap); steps in the order that unblocks the most (address → registration → bank → phone contract, or the local equivalent); a callout on the 'proof of address' circularity and the workarounds people commonly use.", "table, kv, steps, callout", "Order the list", "Sorting priorities…"),
  T("cheap", "Cheap start guide", "Furnish and feed a home for less", "🛋️", [CH("need", "What you need most", ["Furniture & bedding", "Kitchen basics", "Winter clothes", "Kids' things", "Work clothes / tools"], multi=True), CH("style", "Style", ["Free first", "Cheap and quick", "Buy once, keep"], "Free first")],
    "Needs: {need}, style {style}, household from the profile. Sections: cards for 6 sourcing channels (meta = cost · speed · effort) such as community groups, charity shops, swap and buy-nothing groups, newcomer organisations, discount chains; a checklist of a 'first week kit' with target costs; bullets on safety when buying second-hand (mattresses, electrics, child seats); a callout on scams around 'free' items and deposits.", "cards, checklist, bullets, callout", "Show me", "Scouring listings…"),
  T("fair", "Is this a fair price?", "Rent, deposits, fees, plans", "🏷️", [LONG("quote", "What you're being asked to pay", "room in shared flat 650/month, 3 months' deposit, 200 'admin fee', pay cash before viewing"), CH("kind", "What it's for", ["Rent / deposit", "Phone / internet plan", "Agency or admin fee", "Second-hand item", "Transport / licence", "Other"], "Rent / deposit")],
    "Price check for {kind}: {quote}, for a newcomer in the profile's country with the profile's household. Sections: kv (verdict: fair / high / walk away, a typical range for this in general terms, the single biggest red flag if any); table (Charge | Asked | Typical | Customary or legal? | What to ask) with one row per fee or term in the quote; bullets of 4 questions to ask before paying anything; a quote with a polite message that queries or counters the price without sounding difficult; a callout that deposit caps, fee bans and cooling-off rights differ by country, never to pay cash without a receipt or before seeing the thing, and that this is not legal advice.", "kv, table, bullets, quote, callout", "Check the price", "Comparing prices…"),
  T("short", "Money is running out", "Where help exists, what to do first", "🆘", [TXT("situation", "What's happening", "rent due Friday, 90 left, job starts in 3 weeks"), CH("status", "Your status", ["Work visa", "Student", "Refugee / asylum", "Family reunion", "Free movement", "Other / prefer not to say"], "Work visa")],
    "Situation: {situation}, status {status}, country and household from the profile. Sections: steps for the next 72 hours in priority order (talk to the landlord before missing the date, newcomer and migrant support organisations, community and faith groups, emergency food, embassy or consulate where relevant); table (Type of help | Who usually offers it | What to bring | Notes); a callout that eligibility for public support depends on status and country, that this is not immigration or legal advice, and to seek a registered adviser or recognised charity; a quote with a short message to the landlord asking for a few days.", "steps, table, callout, quote", "Help me now", "Finding help…")], IMM)
