from dsl import *
FIN = "General business information, not financial, tax or legal advice; check the numbers with your accountant before acting."
CUR = CH("currency", "Currency", ["USD", "EUR", "GBP", "INR", "AUD", "CAD"])

# 1 — Cash-flow forecasting for owner-operators
APP("runway_radar", "Runway Radar", "See your cash 13 weeks ahead, before it bites", "Finance", ["#0B3D91", "#F4B400", "#00A896"], "graph",
 "Runway Radar turns your bank balance, invoices and bills into a 13-week cash forecast, stress-tests payroll and rent, and ranks which receivables to chase first.",
 "You are a fractional CFO for small businesses: blunt about cash, allergic to vanity metrics, and you always show the maths behind every number.",
 "Cash is the only metric that can kill you", "Tell us about your business so forecasts use the right rhythm.", ["13-week forecasts from a paste", "Payroll & rent stress tests", "Chase-first list for receivables"],
 [TXT("biz", "Business", "12-seat café / 3-person agency"), CH("cycle", "Pay cycle", ["Weekly", "Fortnightly", "Monthly"]), NUM("fixed", "Fixed monthly costs", "18000"), CUR],
 [T("forecast", "13-week forecast", "Bank balance + what's coming → week by week", "📈",
    [NUM("balance", "Cash in bank today", "24000"), LONG("inflows", "Expected money in", "Invoice #41 4,200 due 3 Oct; weekend takings ~1,800/wk…"), LONG("outflows", "Money out", "rent 2,400 on the 1st; payroll 6,100 on the 28th; supplier 900 fortnightly…")],
    "Starting balance {balance}. Inflows: {inflows}. Outflows: {outflows}. Build a 13-week cash forecast as a table (Week | In | Out | Net | Closing balance), using the profile's fixed costs and pay cycle wherever the inputs are silent. Then a callout naming the lowest-balance week and the shortfall (if any), bullets of the 3 assumptions most likely to be wrong, and a checklist of actions to take this week.",
    "table, callout, bullets, checklist", "Forecast", "Counting the weeks…"),
  T("stress", "Can I make payroll?", "Stress-test one big commitment", "🧯",
    [TXT("commitment", "The commitment", "payroll of 6,100 on the 28th", True), NUM("balance", "Cash today", "9500"), TXT("scenario", "What if…", "the big client pays 2 weeks late")],
    "Cash today {balance}; commitment: {commitment}; scenario: {scenario}. Produce a kv (days until the commitment, cash needed, expected cash on that date, gap or headroom), a table of 3 scenarios (Scenario | Closing cash | Verdict), steps to close any gap ordered from cheapest to most expensive, and a callout on what to say to staff or the landlord if it is tight.",
    "kv, table, steps, callout", "Stress test", "Running numbers…"),
  T("chase", "Chase-first list", "Which unpaid invoices to work today", "📋",
    [LONG("receivables", "Unpaid invoices", "Acme 3,200 due 12 days ago, usually pays late; Bloom 950 due tomorrow…")],
    "Rank these receivables: {receivables}. Table (Customer | Amount | Days overdue | Likelihood | Action) sorted by expected cash recovered soonest, a quote with a 3-line chase message for the top one, and bullets on which customers to move to deposits or shorter terms.",
    "table, quote, bullets", "Rank them", "Sorting…"),
  T("gap", "Bridge a cash gap", "Compare ways to cover a shortfall", "🌉",
    [NUM("gap", "Shortfall", "7000"), NUM("weeks", "Weeks until it clears", "6"), CH("options", "Open to", ["Overdraft", "Invoice finance", "Card / loan", "Supplier terms", "Owner top-up", "Sell stock"], multi=True)],
    "Shortfall {gap} for about {weeks} weeks; options considered: {options}. Compare as a table (Option | Speed | Typical cost | Risk | Fit), steps to execute the best fit within 7 days, bullets of levers that cost nothing (deposits, terms, cutting a subscription), and a callout on warning signs that mean it is a structural rather than timing problem.",
    "table, steps, bullets, callout", "Compare options", "Weighing…"),
  T("review", "Month-end cash review", "Opening to closing, explained", "🗓️",
    [LONG("month", "This month's numbers", "opened 18k, closed 14.5k; sales 31k; payroll 12k; bought a new oven 4k…")],
    "Review this month: {month}. kv (opening, closing, net change, cash burn or build, months of runway at this rate), bullets on the 3 biggest drivers, a callout on the one number to watch next month, and a quote with a 2-sentence summary for a business partner or bank manager.",
    "kv, bullets, callout, quote", "Review", "Reconciling…")],
 "General business information, not financial advice; check forecasts with your accountant before borrowing or committing.")

# 2 — Restaurant menu costing & engineering
APP("menu_margin", "Menu Margins", "Know what every dish really earns", "Business", ["#B71C1C", "#FFC107", "#33691E"], "flame",
 "Menu Margins costs every dish from its recipe, sorts your menu into stars and dogs, reprices for your target food cost and rewrites descriptions that sell.",
 "You are a restaurant consultant who has run kitchens: obsessed with food-cost percentage, plate-count data and menu psychology, and honest when a dish should be cut.",
 "Price the menu, not the guesswork", "A few numbers about your place make the maths accurate.", ["Plate cost & margin per dish", "Star / plowhorse / puzzle / dog matrix", "Descriptions and layouts that sell"],
 [TXT("venue", "Venue", "40-cover bistro, dinner only"), NUM("target", "Target food cost %", "30"), CH("cuisine", "Cuisine", ["Café", "Bistro", "Pizza", "Asian", "Indian", "Bar food", "Fine dining", "Other"]), CUR],
 [T("cost", "Cost a dish", "Recipe + prices → plate cost and margin", "🧾",
    [TXT("dish", "Dish", "chicken parmigiana", True), LONG("recipe", "Recipe with quantities & purchase prices", "250g chicken breast (7.20/kg), 80g mozzarella (8/kg), 120g passata…"), NUM("price", "Current menu price", "16")],
    "Cost {dish} at menu price {price} from: {recipe}. Table (Ingredient | Qty | Unit cost | Line cost) including a 5% waste and garnish allowance, kv (plate cost, food cost %, gross profit per plate, price needed to hit the profile target), bullets of 3 ways to cut the plate cost without guests noticing, and a callout if the food cost is over 35%.",
    "table, kv, bullets, callout", "Cost it", "Weighing portions…"),
  T("matrix", "Menu engineering", "Stars, plowhorses, puzzles, dogs", "⭐",
    [LONG("sales", "Dishes with price, plate cost and units sold", "Burger 14 / 4.10 / 220; Risotto 15 / 3.80 / 60; Sea bass 24 / 11 / 45…")],
    "Menu-engineer these dishes: {sales}. Compute contribution margin and popularity for each, then a table (Dish | Price | Margin | Units | Class) using Star / Plowhorse / Puzzle / Dog, a kv stating the margin and popularity thresholds you used, cards with one action per class (meta = expected effect), and a callout on the two changes to make first.",
    "table, kv, cards, callout", "Classify", "Sorting the menu…"),
  T("reprice", "Reprice the menu", "New prices with the psychology built in", "💷",
    [LONG("menu", "Menu items with prices and plate costs", "Margherita 11 (cost 2.40), Diavola 13 (cost 3.30)…"), CH("goal", "Goal", ["Hit target food cost", "Absorb supplier increases", "Premium repositioning", "Value push"], "Hit target food cost")],
    "Reprice this menu for '{goal}': {menu}. Table (Item | Now | Suggested | Food cost % after | Why) using charm-pricing and anchor logic, bullets on which items to raise, hold or cut, a quote with a 2-sentence note to staff explaining the changes to guests, and a callout on how to phase the increases.",
    "table, bullets, quote, callout", "Reprice", "Recalculating…"),
  T("photo", "Critique my menu", "Photo of the menu → layout and copy fixes", "📷",
    [PHOTO("Photo of your printed menu or board", "", True)],
    "Critique the menu in the photo: bullets on layout, eye-flow, price formatting and description quality, a table (Item | Issue | Rewrite) with rewritten descriptions for up to 6 items, steps to re-lay-out the page for higher average spend, and a callout on any allergen or legal labelling gaps to check.",
    "bullets, table, steps, callout", "Critique", "Reading the menu…"),
  T("special", "Price a special", "Tonight's dish, priced and pitched", "🍽️",
    [TXT("special", "Tonight's special", "pan-seared duck breast with cherry jus", True), NUM("cost", "Plate cost", "7.40"), NUM("covers", "Expected covers", "35")],
    "For the special '{special}' at plate cost {cost} and {covers} covers: kv (suggested price, food cost %, gross profit per plate, total GP if sold out), a quote with a 25-word server upsell line, bullets of 3 pairing add-ons with their margins, and a callout on the minimum plates to sell before prep cost is covered.",
    "kv, quote, bullets, callout", "Price it", "Plating…")],
 "Business guidance only, not financial advice; verify allergen and labelling requirements against local regulations.")

# 3 — Independent retail stock & buying
APP("shelf_sense", "Shelf Sense", "Stock the right amount of the right things", "Business", ["#5D4037", "#00ACC1", "#FFB300"], "bag",
 "Shelf Sense helps independent shop owners set reorder points, plan open-to-buy budgets, clear slow stock without killing margin and tidy displays from a photo.",
 "You are a seasoned independent-retail buyer: numbers-led on sell-through and weeks of cover, allergic to dead stock, and practical about small back rooms.",
 "Less dead stock, fewer empty shelves", "Tell us about your shop so the buying maths fits.", ["Reorder points per product", "Open-to-buy budgets by season", "Markdowns that protect margin"],
 [TXT("shop", "Shop", "gift & homeware, 60 m², high street"), CH("lead", "Typical supplier lead time", ["Under a week", "1–2 weeks", "3–4 weeks", "6+ weeks"]), NUM("margin", "Average gross margin %", "52"), CUR],
 [T("reorder", "Reorder points", "When and how much to reorder", "🔁",
    [LONG("lines", "Products with weekly sales and stock on hand", "Soy candle: sells 12/wk, 30 in stock, 6 per case; Linen tea towel: 5/wk, 40 in stock…")],
    "Set reorder points for: {lines}, using the profile lead time. Table (Product | Weekly sales | Weeks of cover | Reorder point | Order qty | Order now?), a kv explaining the safety stock (formula, lead time used, service level), a checklist of what to order this week, and a callout on any line overstocked by more than 8 weeks.",
    "table, kv, checklist, callout", "Calculate", "Counting stock…"),
  T("otb", "Open-to-buy plan", "A buying budget for the season", "🧮",
    [NUM("sales", "Planned sales this season", "48000"), NUM("stock", "Stock on hand at cost", "14000"), CH("season", "Season", ["Spring", "Summer", "Autumn", "Christmas", "Sale period"], "Christmas")],
    "Build an open-to-buy plan for {season} with planned sales {sales} and opening stock at cost {stock}, using the profile margin. kv (planned sales at cost, target closing stock, open-to-buy total), a table (Month | Planned sales | Receipts | Closing stock), bullets splitting the budget across categories with a reason each, and a callout on when to stop buying.",
    "kv, table, bullets, callout", "Plan budget", "Budgeting…"),
  T("markdown", "Clear slow stock", "Markdown ladder that frees cash", "🏷️",
    [LONG("slow", "Slow lines with cost, price and quantity", "Ceramic vase: cost 9, price 24, 38 left, sold 2 last month…")],
    "Plan markdowns for: {slow}. Table (Product | Qty | Markdown % | New price | Margin after | Cash freed), steps for a 3-stage markdown ladder with dates, bullets of non-price tactics (bundles, placement, staff picks), and a callout on lines to return to the supplier or donate instead.",
    "table, steps, bullets, callout", "Plan markdowns", "Clearing shelves…"),
  T("shelf", "Shelf check", "Photo of a display → merchandising fixes", "📷",
    [PHOTO("Photo of a shelf or display", "", True), CH("goal", "Goal", ["Higher basket size", "Move slow stock", "Look fuller", "Seasonal push"], "Higher basket size")],
    "Assess the display in the photo for '{goal}': bullets on what is working, a table (Zone | Now | Change | Why) covering eye level, ends and price points, steps to re-merchandise it in under 30 minutes, and a quote with one shelf-talker line to print.",
    "bullets, table, steps, quote", "Assess shelf", "Eyeing the shelf…"),
  T("supplier", "Supplier order email", "A clean purchase order to send", "✉️",
    [TXT("supplier", "Supplier", "Nordic Home Ltd", True), LONG("order", "What to order", "24 × soy candle (SKU SC-01), 12 × tea towel (LT-04)…"), TXT("ask", "Anything to ask for", "free shipping over 500, 60-day terms")],
    "Write a purchase-order email to {supplier} for: {order}, asking for: {ask}. A quote with the full email (subject line, PO lines as plain text, delivery window, terms), a kv of what to confirm on their acknowledgement, and a checklist for goods-in when it arrives.",
    "quote, kv, checklist", "Write order", "Drafting…")],
 "General retail guidance, not financial advice; check buying budgets against your own accounts.")

# 4 — Bookkeeping for owner-operators
APP("ledger_light", "Ledger Light", "Bookkeeping you can actually keep up with", "Finance", ["#1B5E20", "#8E24AA", "#FDD835"], "note",
 "Ledger Light categorises bank transactions, walks you through month-end close, explains your P&L in plain English and sets up a chart of accounts that fits your business.",
 "You are a friendly bookkeeper for owner-operators: tidy, consistent, allergic to 'miscellaneous', and always clear when something needs an accountant.",
 "Books that close in an hour", "Your set-up shapes the categories and the close routine.", ["Categorise a bank export in seconds", "Month-end close checklist", "P&L explained like a human"],
 [TXT("biz", "Business", "mobile dog groomer, sole trader"), CH("structure", "Structure", ["Sole trader", "Partnership", "Ltd / LLC", "Non-profit"]), CH("software", "Books kept in", ["Spreadsheet", "Xero", "QuickBooks", "Wave", "FreshBooks", "Other"]), CH("vat", "Sales tax / VAT registered?", ["Yes", "No", "Not sure"])],
 [T("categorise", "Categorise transactions", "Paste bank lines → coded and totalled", "🗂️",
    [LONG("txns", "Paste bank lines", "03/09 AMAZON MKTPLACE -42.10; 04/09 STRIPE PAYOUT +1,240.55; 05/09 SHELL -61.00…")],
    "Categorise these transactions: {txns}. Table (Date | Description | Amount | Category | Tax treatment | Needs receipt?), bullets of lines that look personal or ambiguous with the question to ask about each, a kv of totals per category, and a callout on anything that looks like a duplicate or a transfer rather than income.",
    "table, bullets, kv, callout", "Categorise", "Sorting lines…"),
  T("close", "Month-end close", "The routine, in order", "✅",
    [CH("month", "Month to close", ["Last month", "This month"], "Last month"), TXT("notes", "Anything unusual", "bought a van, received a grant")],
    "Build a month-end close for {month} with notes: {notes}, tailored to the profile software and structure. A checklist in order (bank reconciliation, receivables, payables, accruals, fixed assets, payroll, sales tax), steps for the two trickiest items given the notes, a kv of the reports to run at the end, and a callout on the mistakes that create year-end pain.",
    "checklist, steps, kv, callout", "Start close", "Tying out…"),
  T("explain", "Explain my P&L", "What the numbers actually say", "💬",
    [LONG("pnl", "Paste your P&L or its key lines", "Revenue 18,400; COGS 6,100; wages 5,200; rent 1,500; marketing 900; net 2,300…")],
    "Explain this P&L in plain English: {pnl}. kv (gross margin %, net margin %, largest cost as % of revenue, break-even revenue), a text section of 5 sentences on what the numbers say about the business, bullets of 3 questions to ask yourself, and a callout on any line that looks mis-categorised or missing.",
    "kv, text, bullets, callout", "Explain", "Reading the lines…"),
  T("coa", "Chart of accounts", "Accounts that fit your trade", "🏗️",
    [TXT("detail", "How detailed", "simple, I just need tax time to be easy")],
    "Design a chart of accounts for the profile business, detail level: {detail}. Table (Code | Account | Type | Use it for), bullets of accounts people in this trade forget, and a callout on keeping owner's drawings and loans out of expenses.",
    "table, bullets, callout", "Design accounts", "Numbering…"),
  T("mismatch", "Fix a mismatch", "Bank and books disagree", "🔍",
    [TXT("diff", "The difference", "bank says 4,210.55, books say 4,180.55", True), LONG("clues", "What you've checked", "all invoices posted, one refund pending", False)],
    "Reconciliation difference: {diff}. Already checked: {clues}. Steps to find it (transposition, timing, bank fees, duplicates, refunds) ordered by likelihood, a table (Cause | Test | Typical sign), and a callout on when to post an adjustment versus keep looking.",
    "steps, table, callout", "Find it", "Hunting pennies…")],
 "General bookkeeping guidance, not accounting, tax or legal advice; confirm treatments with a qualified accountant.")

# 5 — Pricing strategy for established small firms
APP("price_ladder", "Price Ladder", "Raise prices, add tiers, keep customers", "Business", ["#4A148C", "#00BFA5", "#FF6F00"], "scale",
 "Price Ladder builds good-better-best tiers, proves what a discount really costs, scripts price increases and reads competitor pricing from a screenshot.",
 "You are a pricing strategist for small firms: you think in margins and willingness-to-pay, distrust discounting reflexes, and write increase letters customers accept.",
 "Stop leaving money on the table", "Your margin and market set the guardrails.", ["Good / better / best tiers", "Discount & increase maths", "Price-rise letters that land"],
 [TXT("offer", "What you sell", "monthly lawn-care plans / handmade leather bags"), CH("model", "Model", ["One-off products", "Services by the hour", "Packages", "Subscriptions"]), NUM("margin", "Gross margin %", "45"), CUR],
 [T("tiers", "Build tiers", "Good, better, best around your core offer", "🪜",
    [TXT("core", "Core offer & price", "basic lawn cut, 40 per visit", True), TXT("extras", "Things you could add or remove", "edging, fertiliser, priority scheduling, same-day")],
    "Design good-better-best tiers around {core} using: {extras}. Cards for each tier (name, what's in, meta = price · target customer), a table (Feature | Good | Better | Best) with ticks, bullets explaining the anchoring and the decoy, and a callout on the one feature to keep out of the cheapest tier.",
    "cards, table, bullets, callout", "Build tiers", "Stacking tiers…"),
  T("discount", "What a discount costs", "Extra units needed to break even", "📉",
    [NUM("discount", "Discount %", "20"), NUM("price", "Price", "120"), NUM("volume", "Units sold per month now", "80")],
    "At price {price}, {volume} units per month and the profile margin, model a {discount}% discount: kv (margin before, margin after, extra units needed to earn the same profit, % volume lift required), a table (Discount % | Units needed | Realistic?) for 5%, 10%, 15%, 20% and 30%, bullets of alternatives to a blanket discount (bundles, bonuses, terms), and a callout on when a discount is genuinely worth it.",
    "kv, table, bullets, callout", "Run the maths", "Crunching…"),
  T("increase", "Announce a price rise", "The letter, the footer, the phone line", "📨",
    [NUM("pct", "Increase %", "8"), TXT("when", "Effective date", "1 January"), CH("tone", "Tone", ["Warm", "Straight", "Premium"], "Warm")],
    "Write a {tone} price-increase notice for a {pct}% rise effective {when} for the profile offer. A quote with the full email (subject, reason, what stays the same, date, thank-you), a kv with an invoice-footer line, an SMS version and a phone opener, bullets on handling the 3 most common pushbacks, and a callout on grandfathering and notice periods.",
    "quote, kv, bullets, callout", "Write notice", "Choosing words…"),
  T("compare", "Read competitor pricing", "Screenshot → their tiers vs yours", "🔭",
    [PHOTO("Screenshot of a competitor's pricing page or shelf tag", "", True), TXT("mine", "Your current price", "95/month")],
    "From the screenshot, extract the competitor's pricing as a table (Tier or product | Price | What's included | Notes), compare against my price {mine} in a kv (positioning, gap %, apparent value differences), bullets on how to differentiate without matching, and a callout on any claim in the screenshot worth checking.",
    "table, kv, bullets, callout", "Compare", "Reading the page…"),
  T("custom", "Price a custom job", "Floor, target and stretch for bespoke work", "🎯",
    [LONG("job", "Describe the job", "logo + 3 social templates for a bakery, 2 rounds of revisions"), NUM("hours", "Estimated hours", "14"), CH("basis", "Price by", ["Hourly", "Value", "Package"], "Value")],
    "Price this custom job by {basis}: {job}, estimated {hours} hours, for the profile margin and model. kv (floor price, target price, stretch price, with the reasoning for each), a table of 3 options (Option | Included | Price | Turnaround), a quote with a 3-sentence line to present the price, and a callout on scope-creep clauses to include.",
    "kv, table, quote, callout", "Price the job", "Weighing value…")],
 "Pricing guidance is general business information, not financial or legal advice; check consumer-notice rules for your region.")

# 6 — E-commerce store operations
APP("cart_ops", "Cart Ops", "Run your online store like a pro ops team", "Business", ["#E65100", "#1E88E5", "#43A047"], "cart",
 "Cart Ops works the back end of an online store: SKU unit economics, shipping and returns policies, abandoned-cart sequences, product-page critiques and stock-out playbooks.",
 "You are a DTC e-commerce operator who has scaled stores: contribution-margin first, conversion-obsessed, and practical about carriers, packaging and returns.",
 "Profit per order, not just orders", "Platform and product type shape the advice.", ["Unit economics per SKU", "Shipping & returns policies", "Abandoned-cart email sequences"],
 [TXT("store", "Store", "skincare, 40 SKUs"), CH("platform", "Platform", ["Shopify", "WooCommerce", "Amazon", "Etsy", "BigCommerce", "Other"]), NUM("aov", "Average order value", "54"), CH("ships", "Ships to", ["Domestic only", "Domestic + a few countries", "Worldwide"])],
 [T("unit", "SKU unit economics", "What each product earns after everything", "🧮",
    [LONG("sku", "SKU numbers", "Face oil 30ml: price 38, COGS 9.20, packaging 1.10, shipping 4.50, payment fees 3%, CAC ~11…")],
    "Compute unit economics for: {sku}. Table (SKU | Price | Landed COGS | Fulfilment | Fees | CAC | Contribution margin | CM %), kv (blended CM %, break-even CAC, orders per month needed to cover any fixed costs mentioned), bullets of the 3 biggest margin leaks, and a callout on any SKU that loses money after CAC.",
    "table, kv, bullets, callout", "Calculate", "Summing pennies…"),
  T("shipping", "Shipping & returns policy", "Thresholds, who pays, the page copy", "📦",
    [CH("free", "Free shipping?", ["Never", "Over a threshold", "Always"], "Over a threshold"), NUM("threshold", "Threshold", "60"), CH("returns", "Returns window", ["14 days", "30 days", "60 days", "Final sale"], "30 days")],
    "Design shipping and returns for the profile store: free shipping {free} at {threshold}, returns window {returns}. kv (recommended threshold vs the profile AOV, expected AOV lift, cost per order at the threshold), a quote with customer-facing policy text (one paragraph for shipping, one for returns), a table (Scenario | Who pays | Refund type | Notes) for damaged, changed-mind, wrong-item and late-delivery cases, and a callout on legal minimums to check for the ship-to regions.",
    "kv, quote, table, callout", "Write policy", "Boxing it up…"),
  T("abandon", "Abandoned-cart sequence", "Three emails that bring them back", "🛒",
    [TXT("product", "Typical cart", "vitamin C serum + cleanser"), CH("incentive", "Incentive", ["None", "Free shipping", "10% off", "Gift with purchase"], "None")],
    "Write a 3-email abandoned-cart sequence for a cart like '{product}' with incentive: {incentive}. Table (Email | Send after | Subject line | Goal), then a quote with the full copy of all three emails, each under 120 words and clearly numbered, bullets with SMS and push variants, and a callout on frequency caps and unsubscribe hygiene.",
    "table, quote, bullets, callout", "Write sequence", "Nudging carts…"),
  T("page", "Critique a product page", "Screenshot → conversion fixes", "📷",
    [PHOTO("Screenshot of the product page", "", True)],
    "Critique the product-page screenshot for conversion: table (Element | Now | Fix | Priority) covering title, price display, images, trust signals, CTA, shipping info and reviews, a quote with a rewritten title and the first 2 lines of description, a checklist of quick wins under 30 minutes, and a callout on any claim that may need substantiation.",
    "table, quote, checklist, callout", "Critique page", "Scrolling…"),
  T("stockout", "Stock-out playbook", "Keep selling when the shelf is empty", "🚫",
    [TXT("item", "Item out of stock", "best-selling cleanser", True), TXT("eta", "Restock ETA", "3 weeks, maybe longer")],
    "Handle a stock-out of {item} with ETA {eta}: steps for the product page (back-in-stock capture, pre-order, substitute), a quote with the customer email for open orders, bullets of substitute-offer tactics, and a kv of the metrics to watch (lost sessions, waitlist size, refund rate).",
    "steps, quote, bullets, kv", "Make a plan", "Planning…")],
 "General e-commerce guidance, not legal advice; consumer and distance-selling rules vary by region.")

# 7 — Trades quoting
APP("quote_van", "Quote Van", "Job quotes tradespeople can send from the driveway", "Business", ["#F57F17", "#37474F", "#0097A7"], "wrench",
 "Quote Van turns a job description or photo into a priced quote for plumbers, electricians, decorators and builders, and handles variations, deposits and payment terms.",
 "You are an estimator who has run a trades business: fair on labour, realistic on materials and access, and precise about what is excluded.",
 "Quote it right the first time", "Your trade and rates power every estimate.", ["Quotes from a description or photo", "Variations and extras priced fast", "Deposits, terms and sign-off text"],
 [TXT("trade", "Trade", "plumber & heating"), NUM("rate", "Hourly rate", "65"), NUM("markup", "Materials markup %", "20"), CUR],
 [T("quote", "Build a quote", "Description → itemised, ready-to-send quote", "🧾",
    [LONG("job", "Job description", "replace kitchen mixer tap, isolate, supply tap, dispose of old"), TXT("client", "Client & address", "Mrs Patel, 14 Elm Rd"), CH("access", "Access / conditions", ["Easy", "Awkward", "Occupied home", "Site / commercial"], "Easy")],
    "Estimate the job: {job} for {client}, access {access}, using the profile rate and markup. Table (Item | Qty | Unit | Unit price | Line total) split into Labour and Materials, kv (subtotal, contingency, tax note, total, validity in days), a quote with the clean quote text to send including exclusions and assumptions, and a callout on risks to price in or exclude.",
    "table, kv, quote, callout", "Build quote", "Pricing the job…"),
  T("photo", "Estimate from a photo", "Snap the job, get a range", "📷",
    [PHOTO("Photo of the job", "", True), TXT("ask", "What the customer wants", "fix the leak and retile this corner")],
    "From the photo and the request '{ask}', identify the work needed as bullets, then a table (Task | Hours | Materials | Est. cost) using the profile rate, a callout on what cannot be judged from a photo and needs a site visit, and a quote with a short message to the customer giving a price range.",
    "bullets, table, callout, quote", "Estimate", "Eyeing the job…"),
  T("variation", "Price a variation", "They changed their mind mid-job", "🔧",
    [TXT("original", "Original job", "bathroom refit, quoted 4,800", True), LONG("change", "What changed", "they now want underfloor heating and a second shower head")],
    "Price the variation to '{original}': {change}. Table (Extra | Labour | Materials | Total), kv (new contract total, extra days, when the extra payment is due), a quote with a variation-order note for the customer to sign off, and a callout on why not to start the extra work until it is agreed.",
    "table, kv, quote, callout", "Price change", "Adding it up…"),
  T("terms", "Deposits & terms", "Stage payments and plain-English T&Cs", "🤝",
    [NUM("total", "Job total", "4800"), NUM("days", "Job length (days)", "6"), CH("type", "Customer", ["Homeowner", "Landlord", "Business", "Main contractor"], "Homeowner")],
    "Set payment terms for a {total} job over {days} days for a {type}: kv (deposit %, stage payments with their triggers, final payment due, late-payment note), a quote with plain-English terms and conditions under 200 words, a checklist of things to get in writing before starting, and a callout on materials-upfront and cancellation basics.",
    "kv, quote, checklist, callout", "Set terms", "Drafting terms…"),
  T("followup", "Chase a quote", "Turn a sent quote into a booked job", "📲",
    [TXT("job", "Job quoted", "boiler swap, quoted 2 weeks ago", True), CH("stage", "Situation", ["No reply yet", "Said it's too expensive", "Comparing quotes", "Went quiet after yes"], "No reply yet")],
    "Follow up the quote for '{job}', situation: {stage}. A quote with a 60-word text message and a second version as a short email, bullets on what to offer to close (timing, scope trim, payment options, not price cuts), and a callout on when to walk away.",
    "quote, bullets, callout", "Write follow-up", "Nudging…")],
 "Estimates are guidance, not a substitute for a site survey; contract and consumer-notice rules vary by region.")

# 8 — Importing / product sourcing
APP("import_desk", "Import Desk", "Land products from overseas without surprises", "Business", ["#01579B", "#FF8F00", "#6D4C41"], "globe",
 "Import Desk calculates true landed cost, writes supplier RFQs, compares quotes, decodes Incoterms and lead times, and checks samples so first orders don't go wrong.",
 "You are a sourcing manager who has imported for small brands: precise about landed cost, duties and MOQs, and cautious about samples, payment terms and freight surprises.",
 "Know the real cost before you order", "Where you import to and how you ship set duties and freight.", ["Landed cost per unit", "Supplier RFQs and quote comparison", "Sample and QC checklists"],
 [TXT("product", "Product line", "insulated water bottles"), CH("dest", "Importing to", ["USA", "UK", "EU", "Canada", "Australia", "India", "Other"]), CH("mode", "Usual freight", ["Air express", "Air freight", "Sea LCL", "Sea FCL", "Rail"]), CUR],
 [T("landed", "Landed cost", "FOB price → cost on your shelf", "🚢",
    [NUM("unit", "Unit price (FOB)", "4.20"), NUM("qty", "Quantity", "1000"), LONG("extras", "Freight, duty and fees you know", "freight quote 1,150; duty ~6.5%; broker 120; insurance 45")],
    "Landed cost for {qty} units at {unit} FOB with: {extras}, destination per the profile. Table (Cost line | Total | Per unit) covering goods, freight, insurance, duty, import tax, brokerage, inland delivery and payment fees, kv (landed cost per unit, landed cost as % of FOB, minimum sell price at 50% margin), bullets of costs people forget, and a callout that duty rates depend on the HS code and must be confirmed.",
    "table, kv, bullets, callout", "Calculate", "Loading the ship…"),
  T("rfq", "Write an RFQ", "A request suppliers can quote properly", "📝",
    [LONG("spec", "Product spec", "750ml double-wall stainless bottle, powder coat, laser logo, 2 colours"), NUM("qty", "Quantity", "1000"), TXT("needs", "Must-haves", "BPA-free cert, sample first, 30% deposit")],
    "Write a request-for-quotation for {qty} units of: {spec}, must-haves: {needs}. A quote with the full RFQ email (spec as plain-text lines, packaging, labelling, certifications, sample request, payment terms, Incoterm, lead time, and a request for both FOB and EXW prices), a checklist of what a good reply includes, and a callout on red flags in supplier responses.",
    "quote, checklist, callout", "Write RFQ", "Drafting…"),
  T("compare", "Compare supplier quotes", "True cost after freight and terms", "⚖️",
    [LONG("quotes", "Paste the quotes", "A: 4.20 FOB, MOQ 1000, 35 days, 30/70; B: 3.90 EXW, MOQ 2000, 45 days, 50/50…")],
    "Compare: {quotes}. Table (Supplier | Unit price | Incoterm | MOQ | Lead time | Terms | Est. landed per unit | Risk), a kv of the true comparison after freight and payment terms, bullets of negotiation asks per supplier, and a callout on the trade-off between MOQ and cash tied up.",
    "table, kv, bullets, callout", "Compare", "Weighing quotes…"),
  T("incoterm", "Incoterms & timeline", "Who pays what, and when it lands", "🗺️",
    [CH("term", "Incoterm", ["EXW", "FOB", "CIF", "DAP", "DDP"], "FOB"), TXT("date", "Order date", "15 Oct")],
    "Explain {term} for the profile freight mode and destination: kv (who pays what, where risk passes, documents you need), a table (Stage | Who | Typical days | Watch-outs) from the purchase order on {date} to goods on your shelf with estimated dates, and a callout on what changes if you switch to DDP.",
    "kv, table, callout", "Explain", "Mapping the route…"),
  T("sample", "Check a sample", "Photo vs spec before you approve", "📷",
    [PHOTO("Photo of the sample", "", True), TXT("spec", "What was specified", "matte black, 750ml, logo 40mm centred")],
    "Inspect the sample photo against the spec '{spec}': table (Check | Spec | Observed | Pass?), a checklist of hands-on tests to run before approving (fit, finish, function, packaging), bullets of what to write back to the supplier, and a callout on booking an AQL inspection before the full order ships.",
    "table, checklist, bullets, callout", "Inspect", "Looking closely…")],
 "General import guidance, not customs, tax or legal advice; confirm HS codes and duty rates with a licensed customs broker.")

# 9 — Market stall / craft fair traders
APP("stall_day", "Stall Day", "Markets and fairs that actually pay for the pitch", "Business", ["#AD1457", "#00897B", "#FFA000"], "pin",
 "Stall Day helps market traders and craft-fair vendors decide which events are worth it, plan stock and cash float, lay out a stall that stops people, and review each day's takings.",
 "You are a veteran market trader: honest about pitch fees and weather, sharp on what sells at 10am versus 3pm, and generous with display tricks.",
 "Make the pitch fee back by noon", "What you sell and your usual takings tune the plan.", ["Go / no-go on any event", "Stock & float plans", "Stall layout from a photo"],
 [TXT("sells", "What you sell", "hand-poured candles and wax melts"), NUM("avg", "Average sale", "18"), NUM("typical", "Typical day's takings", "420"), CUR],
 [T("worth", "Is this event worth it?", "Fees, footfall and a verdict", "🎪",
    [TXT("event", "Event", "Christmas market, 2 days, 3,000 visitors a day", True), NUM("fee", "Pitch fee", "180"), TXT("costs", "Other costs", "fuel 30, parking 20, helper 80, table hire 15")],
    "Evaluate {event} at pitch fee {fee} with costs: {costs}, against the profile takings and average sale. kv (total cost, break-even sales, sales needed to make 2× the costs, conversion needed as % of visitors), a table (Scenario | Takings | Profit) for poor, typical and great days, bullets of questions to ask the organiser, and a callout with a go / maybe / skip verdict and why.",
    "kv, table, bullets, callout", "Judge it", "Sizing the crowd…"),
  T("pack", "Pack list & float", "What to bring and how much change", "🚗",
    [TXT("event", "Event & hours", "Saturday farmers' market, 8am–2pm", True), CH("weather", "Forecast", ["Sunny", "Cloudy", "Rain", "Cold", "Windy"], "Cloudy"), NUM("target", "Target takings", "500")],
    "Plan stock and kit for {event}, forecast {weather}, target {target}. Table (Product | Units to bring | Price | Potential) sized to hit the target with 20% headroom, a checklist of kit (weights, cover, signage, card reader, float), kv (cash float amount and denomination breakdown), and a callout on weather-specific prep.",
    "table, checklist, kv, callout", "Pack it", "Loading the car…"),
  T("layout", "Stall layout check", "Photo → what stops passers-by", "📷",
    [PHOTO("Photo of your stall or table", "", True)],
    "Critique the stall in the photo: bullets on what stops passers-by and what doesn't, a table (Zone | Now | Change | Why) covering height, hero product, price visibility, signage and reach, steps to re-set it in 15 minutes, and a quote with a 6-word sign for the front.",
    "bullets, table, steps, quote", "Check layout", "Standing back…"),
  T("review", "Review the day", "Takings → lessons for next time", "🧾",
    [LONG("day", "How it went", "took 380, 21 sales, dead 8–10, sold out of vanilla, nobody touched the gift sets, rain at 1")],
    "Review the day: {day}, against the profile typical takings. kv (takings vs typical, average sale vs profile, sales per hour, profit after fees if given), bullets of what to change next time, a table (Product | Signal | Action) for sold-out, ignored and steady lines, and a callout on the one experiment to run at the next event.",
    "kv, bullets, table, callout", "Review day", "Counting the tin…"),
  T("pitch", "Talk to shoppers", "Lines for the moments that sell", "🗣️",
    [CH("moment", "Moment", ["Someone picks it up", "Asks the price", "Says 'just looking'", "Wants a discount", "Buys — upsell"], "Asks the price")],
    "Give me lines for when '{moment}' happens at a stall selling the profile products: a quote with 3 short things to say, bullets on body language and timing, and a callout on what not to say.",
    "quote, bullets, callout", "Give me lines", "Warming up…")],
 "General trading guidance, not financial or legal advice; check licence and food-hygiene rules for your event.")

# 10 — Daily till / cash-up for shops
APP("till_tally", "Till Tally", "Cash up, spot leaks, know your shop's day", "Business", ["#263238", "#00C853", "#FFD600"], "coin",
 "Till Tally reads your end-of-day Z report, investigates cash variances, sets floats and staffing against sales by hour, and turns a week of takings into a one-page dashboard.",
 "You are a multi-site shop manager turned trainer: calm about variances, forensic about patterns, and never accusatory without evidence.",
 "Cash up in five minutes, learn something every day", "Your set-up tells the analysis what normal looks like.", ["Z-report analysis in seconds", "Variance investigation steps", "Hourly staffing vs sales"],
 [TXT("shop", "Shop", "convenience store, 7am–10pm"), NUM("float", "Standard float", "150"), CH("tills", "Tills", ["1", "2", "3+"]), CUR],
 [T("zreport", "Read my Z report", "Photo or figures → what today says", "🧾",
    [PHOTO("Photo of the Z / end-of-day report"), LONG("figures", "Or type the figures", "gross 2,140; card 1,480; cash 610; refunds 45; voids 6; no-sales 11; declared cash 585", False)],
    "Analyse the end-of-day report from the photo and/or these figures: {figures}. kv (gross, net of refunds, card vs cash split %, expected cash, declared cash, variance), a table (Signal | Value | Normal range | Flag?) for refunds, voids, no-sales, discounts and average transaction, bullets on what the flags usually mean, and a callout on what to check before tomorrow's open.",
    "kv, table, bullets, callout", "Analyse", "Cashing up…"),
  T("variance", "Investigate a variance", "Find where the cash went", "🔎",
    [NUM("amount", "Variance", "-38.50"), TXT("context", "Context", "Saturday, 2 staff, busy 12–3, new starter on till 2", True)],
    "Cash variance of {amount}; context: {context}. Steps to investigate in order (recount, float check, change errors, refunds and voids log, card-as-cash tender errors, safe drops, CCTV window), a table (Cause | Likelihood | How to confirm), a quote with a neutral way to raise it with staff, and a callout on when a repeating pattern justifies a formal process.",
    "steps, table, quote, callout", "Investigate", "Following the cash…"),
  T("float", "Float & change plan", "Denominations, safe drops, open/close", "🪙",
    [CH("day", "Day type", ["Quiet weekday", "Busy Saturday", "Event / holiday", "Sale day"], "Busy Saturday")],
    "Set the cash float for a {day} at the profile shop: kv (float per till and denomination breakdown), a table (Time | Action | Who) for safe drops and change runs across the day, a checklist for opening and closing each till, and a callout on the maximum cash to hold in a drawer.",
    "kv, table, checklist, callout", "Set float", "Counting coins…"),
  T("hours", "Staff to sales by hour", "Put people where the sales are", "⏰",
    [LONG("hourly", "Sales by hour", "7am 60, 8am 210, 9am 180, 12pm 340, 1pm 390, 5pm 300, 9pm 90…"), NUM("staffcost", "Hourly staff cost", "14")],
    "Match staffing to these hourly sales: {hourly}, at staff cost {staffcost} per hour. Table (Hour | Sales | Staff suggested | Wage % of sales), bullets of the shifts to move, kv (labour % of sales before and after if current staffing is given), and a callout on minimum safe staffing and breaks.",
    "table, bullets, kv, callout", "Plan shifts", "Shuffling rotas…"),
  T("week", "Weekly dashboard", "Seven days on one page", "📊",
    [LONG("week", "Daily takings this week", "Mon 1,420 / Tue 1,380 / Wed 1,510 / Thu 1,690 / Fri 2,240 / Sat 2,610 / Sun 1,900; last week total 12,100")],
    "Build a one-page weekly dashboard from: {week}. kv (week total, vs last week %, best and worst day, average transaction if given, cash variance total if given), a table (Day | Takings | vs last week | Note), bullets of 3 insights, and a quote with a 3-line summary to send to the owner or team.",
    "kv, table, bullets, quote", "Build dashboard", "Adding it up…")],
 "General retail-operations guidance, not financial, legal or HR advice; follow local employment law before any staff process.")
