from dsl import *
# Batch w16 — Education: study systems for university students (thesis, citations, labs, group projects, exam anxiety).
# Deliberately avoids existing concepts: essay_coach (essay outlines/feedback), error_bars (lab-report uncertainty/discussion),
# study_planner (revision timetable), stat_check (stats), mind_ease (general anxiety), focus_sprint (procrastination), campus_abroad.

MH = "Quiet Hall offers general coping strategies, not therapy or diagnosis. If anxiety is affecting daily life, or you have thoughts of harming yourself, contact your university wellbeing service, a doctor or a crisis line now."
LABSAFE = "Safety information here is general and must never replace your institution's risk assessment, your lab manual or the supervisor in the room."
ETHICS = "Templates and drafts here do not replace your institution's ethics process or your supervisor's approval. Never collect data from people before ethics approval is granted."

APP("thesis_pilot", "Thesis Pilot", "From vague topic to submitted dissertation", "Education", ["#1A237E", "#00897B", "#FFB300"], "pin",
 "Thesis Pilot turns a fuzzy topic into a defensible research question, plans your chapters backwards from the deadline, preps every supervisor meeting and gets you ready for the viva.",
 "You are a seasoned dissertation supervisor: rigorous about scope, allergic to vague questions, generous with structure, and firm that the student does the writing.",
 "Land the dissertation", "Tell us your level, field and deadline so every plan fits your calendar.", ["Research questions that are actually doable", "Chapter plans with real dates", "Supervisor meetings and viva prep"],
 [NAME, CH("level", "Level", ["Undergraduate", "Master's", "PhD"], "Undergraduate"), TXT("field", "Field / discipline", "sociology, mechanical engineering…"), TXT("deadline", "Submission deadline", "15 May")],
 [T("scope", "Scope my question", "From a topic to 3 doable questions", "🎯",
    [LONG("topic", "Your topic or interest", "social media and loneliness in first-year students"), CH("method", "Methods you can use", ["Survey", "Interviews", "Experiment", "Secondary data", "Literature-based", "Not sure"], "Not sure", True), NUM("words", "Word limit", "10000")],
    "Topic: {topic}. Available methods: {method}. Word limit: {words}. Propose 3 research questions as cards (meta = method · feasibility for the profile's level and deadline), then a table (Question | What you'd need | Biggest risk | Verdict). Finish with a callout on scope creep: the one thing to cut if the question is still too big.",
    "cards, table, callout", "Scope it", "Narrowing down…"),
  T("plan", "Chapter plan", "Backwards from the deadline", "🗓️",
    [TXT("question", "Your research question", "", True), CH("stage", "Where you are", ["Nothing written", "Lit review drafted", "Data collected", "Analysis done", "Full draft exists"], "Nothing written"), NUM("weekly", "Hours per week", "12")],
    "Research question: {question}. Current stage: {stage}. Available: {weekly} hours per week until the profile's deadline. Build a chapter plan as a table (Chapter | Target words | Start | Draft due | Depends on), then steps for the next 14 days with a concrete output per session, and a callout on the buffer: how many days are reserved for formatting, references and supervisor feedback.",
    "table, steps, callout", "Plan chapters", "Working backwards…"),
  T("meeting", "Prep a supervisor meeting", "Agenda, questions, follow-up email", "🧑‍🏫",
    [LONG("done", "What you've done since last time", "finished 8 of 12 interviews, started coding transcripts", False), LONG("stuck", "Where you're stuck", "not sure whether to use thematic analysis or grounded theory")],
    "Since last meeting: {done}. Stuck on: {stuck}. Produce a checklist agenda for a 30-minute meeting (5 items, most important first, with minutes each), bullets of 5 precise questions that get decisions rather than vague advice, and a quote with the email to send 24 hours beforehand summarising progress and attaching the agenda.",
    "checklist, bullets, quote", "Prep meeting", "Setting the agenda…"),
  T("unstick", "Unblock a chapter", "Stuck, behind or overwhelmed", "🧱",
    [CH("chapter", "Chapter", ["Introduction", "Literature review", "Methodology", "Results", "Discussion", "Conclusion", "Abstract"], "Literature review"), LONG("problem", "What's going wrong", "I have 40 papers and no argument")],
    "Chapter: {chapter}. Problem: {problem}. Explain in text what this chapter must do for the examiner and the one job the student is probably over-complicating. Then steps for a 90-minute session that ends with something on the page (each step with minutes and a concrete output), a kv of the section headings this chapter usually needs with target word counts for the profile's level, and a callout on what NOT to do (more reading, rewriting the intro).",
    "text, steps, kv, callout", "Unblock me", "Loosening the knot…"),
  T("viva", "Viva prep", "Predict the questions, rehearse the answers", "🎓",
    [LONG("summary", "Summary of your thesis", "Mixed-methods study of… found that…"), TXT("weak", "Weakest part (honest)", "small sample, one university")],
    "Thesis summary: {summary}. Self-declared weakness: {weak}. Produce a table of 10 likely examiner questions (Question | Why they ask it | Strong answer in one line), ordered from warm-up to hardest. Then a quote with a 90-second opening statement the student can rehearse, a checklist for viva day (what to bring, how to handle 'I don't know'), and a callout on turning the weakness into a limitations-and-future-work answer.",
    "table, quote, checklist, callout", "Prep viva", "Interrogating…")])

APP("cite_sure", "Cite Sure", "Every reference right, every style, no integrity scare", "Education", ["#4E342E", "#F9A825", "#00838F"], "book",
 "Cite Sure builds and fixes references in APA, MLA, Chicago, Harvard, IEEE or Vancouver, checks a bibliography from a photo, converts whole lists between styles and tells you whether a paraphrase is too close to the source.",
 "You are a meticulous academic librarian: exact about punctuation and italics, calm about integrity questions, and clear when a source lacks the fields a style needs.",
 "Reference without the dread", "Set your default style and how you cite in-text; every tool uses it.", ["References built from a DOI, URL or scraps", "Bibliography checked from a photo", "Paraphrase-too-close checks"],
 [NAME, CH("style", "Default style", ["APA 7", "MLA 9", "Chicago (notes)", "Chicago (author-date)", "Harvard", "IEEE", "Vancouver", "OSCOLA"], "APA 7"), TXT("dept", "Department / course", "Psychology, 2nd year"), CH("intext", "In-text preference", ["Author-date", "Numeric", "Footnotes"], "Author-date")],
 [T("build", "Build a reference", "DOI, URL or scraps → formatted entry", "📎",
    [LONG("source", "Source details", "doi:10.1037/… or 'Smith 2019 Nature article about sleep and memory'"), CH("type", "Source type", ["Journal article", "Book", "Book chapter", "Website", "Report", "Thesis", "Lecture / slides", "Video", "Dataset", "Not sure"], "Not sure"), CH("override", "Style override", ["Use my default", "APA 7", "MLA 9", "Chicago (notes)", "Chicago (author-date)", "Harvard", "IEEE", "Vancouver"], "Use my default")],
    "Source: {source}. Type: {type}. Style: {override} (if 'Use my default', use the profile's style). Produce a kv of every field the style needs (author, year, title, container, volume/issue, pages, publisher, DOI/URL, access date), marking any you could not find as 'MISSING — check'. Then a quote containing the reference-list entry exactly formatted, a second quote with the in-text citation in first and subsequent forms, and a callout on any guess you made (e.g. inferred year) that the student must verify.",
    "kv, quote, callout", "Build it", "Formatting…"),
  T("scan", "Check my bibliography", "Photo of a reference list → fixes", "📷",
    [PHOTO("Photo or screenshot of your reference list", "", True), CH("target", "Should be in", ["My default style", "APA 7", "MLA 9", "Chicago", "Harvard", "IEEE", "Vancouver"], "My default style")],
    "Read every entry in the reference-list photo and check it against {target} (if 'My default style', use the profile's style). Table (# | Entry as written | Problems | Corrected entry) covering ordering, punctuation, italics, capitalisation, missing DOIs and hanging indents. Then a checklist of global fixes to apply across the whole list, and a callout on the single most common error found.",
    "table, checklist, callout", "Check list", "Reading the list…"),
  T("close", "Too close to the source?", "Paraphrase vs patchwriting check", "🔍",
    [LONG("original", "Original passage", "paste the source text"), LONG("mine", "Your version", "paste your sentence(s)"), CH("cited", "Have you cited it?", ["Yes", "No", "Not sure how"], "Yes")],
    "Original: {original}. Student's version: {mine}. Cited: {cited}. Compare them in a table (Source phrase | Student phrase | Verdict: copied / patchwritten / paraphrased / original), give a text verdict on whether a marker or similarity checker would flag it and why, steps to rewrite it into a genuine paraphrase that changes structure not just words, a quote with one properly attributed rewrite in the profile's style, and a callout on when a direct quotation is the honest choice.",
    "table, text, steps, quote, callout", "Check it", "Comparing…"),
  T("convert", "Convert a list", "Change every entry to another style", "🔁",
    [LONG("list", "Paste your reference list", ""), CH("frm", "From", ["APA 7", "MLA 9", "Chicago", "Harvard", "IEEE", "Vancouver", "Mixed / unknown"], "Mixed / unknown"), CH("to", "To", ["APA 7", "MLA 9", "Chicago (notes)", "Chicago (author-date)", "Harvard", "IEEE", "Vancouver"], "APA 7")],
    "Convert this list from {frm} to {to}: {list}. Output a quote containing the full converted list in the order the target style requires (alphabetical or numeric), then a table (Entry | What changed) and a callout listing entries where the original lacked information the target style needs.",
    "quote, table, callout", "Convert", "Reformatting…"),
  T("rule", "Ask a citation rule", "Odd sources, secondary cites, et al.", "❓",
    [TXT("q", "Your question", "how do I cite a lecture recording in Harvard?", True)],
    "Question: {q} — answer for the profile's style unless the question names another. Give a text answer in plain English, a kv with the exact pattern (reference-list form and in-text form) plus one filled example, and bullets on the 3 nearby rules students confuse with this one (secondary citations, same author same year, no date).",
    "text, kv, bullets", "Answer", "Checking the manual…")])

APP("bench_brief", "Bench Brief", "Walk into every practical knowing exactly what to do", "Education", ["#2E7D32", "#F4511E", "#1E88E5"], "drop",
 "Bench Brief preps you before a lab practical: protocol walk-throughs with timings and hazards, risk assessments, clean lab-notebook entries, a methods section written properly, and drills for practical exams.",
 "You are a friendly lab demonstrator with a safety-first mindset: precise about technique, honest about what usually goes wrong, and never a substitute for the supervisor in the room.",
 "Own the bench", "Tell us your subject and level so every walkthrough uses the right techniques.", ["Protocol walk-throughs with timings", "Risk assessments and notebook entries", "Practical-exam drills"],
 [NAME, CH("subject", "Lab subject", ["Chemistry", "Biology", "Biochemistry", "Physics", "Engineering", "Pharmacy", "Environmental"], "Chemistry"), CH("level", "Level", ["Year 1", "Year 2", "Final year", "Master's"], "Year 1"), TXT("kit", "Equipment you've used before", "pipettes, spectrophotometer, PCR")],
 [T("prelab", "Pre-lab brief", "Paste the protocol → what to expect", "📋",
    [LONG("protocol", "Protocol / lab script", "paste the method from the lab manual"), NUM("minutes", "Session length (min)", "180")],
    "Protocol: {protocol}. Session: {minutes} minutes. Produce steps for the practical with a time budget per step that fits the session and includes waiting periods, a table (Step | What can go wrong | How to tell | Fix), a checklist of every value and observation to record (with units and precision), and a callout on the single most common mistake for this technique at the profile's level.",
    "steps, table, checklist, callout", "Brief me", "Reading the script…"),
  T("risk", "Risk assessment", "Chemicals + equipment → hazards and controls", "⚠️",
    [LONG("materials", "Chemicals, organisms, equipment", "conc. HCl, ethanol, Bunsen burner, E. coli K-12"), CH("scale", "Scale", ["Test-tube", "Bench (100 mL–1 L)", "Pilot / larger"], "Test-tube")],
    "Materials: {materials}. Scale: {scale}. Build a table (Substance or equipment | Hazard class | Route of exposure | Control measure | Disposal), a checklist of PPE and setup checks before starting, steps for the emergency response to the two most likely incidents (spill, splash, burn, cut), and a callout stating this is a draft the supervisor must approve against the institution's own COSHH or equivalent forms.",
    "table, checklist, steps, callout", "Assess", "Checking hazards…"),
  T("notebook", "Notebook entry", "Messy notes → a proper lab-book page", "📓",
    [LONG("notes", "Your raw notes", "weighed 2.03 g NaCl, dissolved in ~50 mL, heated 5 min, went cloudy…"), TXT("aim", "Aim of the experiment", "determine the solubility of…")],
    "Aim: {aim}. Raw notes: {notes}. Rewrite as a lab-notebook entry: kv (Date, Title, Aim, Hypothesis, Materials, Method reference), a table of observations and measurements (Time | Action | Observation or value | Units | Notes), bullets of deviations from the protocol that must be recorded, and a callout on notebook rules: no erasing, single-line strikethrough, date and sign every page.",
    "kv, table, bullets, callout", "Write entry", "Tidying…"),
  T("methods", "Write the methods", "Past tense, reproducible, no results", "✍️",
    [LONG("what", "What you actually did", "including any changes from the script"), CH("style", "House style", ["Passive past tense", "Active past tense", "Numbered protocol"], "Passive past tense")],
    "What was done: {what}. Style: {style}. Write a text methods section that another student could reproduce (quantities, concentrations, instruments with model where given, times, temperatures), then bullets of what markers deduct for in methods (results creeping in, missing controls, vague 'appropriate amount'), and a checklist to compare the draft against the original protocol so no step is missing.",
    "text, bullets, checklist", "Draft methods", "Writing it up…"),
  T("drill", "Practical exam drill", "Rehearse a technique out loud", "🧪",
    [TXT("technique", "Technique", "serial dilution", True), CH("mode", "Drill", ["Talk me through it", "Quiz me", "Common errors"], "Talk me through it")],
    "Technique: {technique}. Mode: {mode}. Produce steps for the technique with the exact hand movements, volumes and checks an examiner watches for, a table (Examiner checks | What good looks like | Marks lost for), a quote with a mnemonic or one-line cue for the trickiest step, and bullets of 6 questions the examiner might ask at the bench with short model answers (make them harder if the mode is 'Quiz me', error-focused if 'Common errors').",
    "steps, table, quote, bullets", "Drill", "Setting up…")], LABSAFE)

APP("project_crew", "Project Crew", "Group projects without the group chat meltdown", "Education", ["#E65100", "#00ACC1", "#7B1FA2"], "chat",
 "Project Crew sets up a team charter, splits the work fairly, turns messy meetings into minutes with owners, scripts the awkward conversation with the teammate who has gone quiet, and writes honest peer assessments.",
 "You are a calm project-team facilitator who has watched hundreds of student groups: fair, allergic to vagueness, and good at making conflict boring and procedural.",
 "Make the group work", "Tell us about the project so plans, agendas and messages fit your team.", ["Charters and fair task splits", "Minutes with owners and dates", "Scripts for the freeloader talk"],
 [NAME, TXT("project", "Project", "Marketing plan for a local café, 4,000 words + pitch"), NUM("size", "Team size", "4"), TXT("due", "Final deadline", "28 March")],
 [T("charter", "Team charter", "Roles, rules and a kickoff message", "🤝",
    [LONG("members", "Members and strengths / constraints", "Ana: good writer, away 10–14 Mar; Ben: does the numbers; …"), CH("grading", "How it's graded", ["One group mark", "Group mark + peer weighting", "Individual sections", "Not sure"], "One group mark")],
    "Members: {members}. Grading: {grading}. Create a table (Role | Person | Responsibilities | Backup) covering coordinator, editor, research and deliverable owners, a checklist of 8 ground rules the team agrees to (response times, where files live, what happens if someone misses a deadline), a kv of the meeting rhythm (when, where, how long, who runs it), and a quote with a friendly kickoff message for the group chat that gets everyone to confirm their role.",
    "table, checklist, kv, quote", "Draft charter", "Assembling the crew…"),
  T("split", "Split the work", "Brief → tasks, owners, dates", "🧩",
    [LONG("brief", "Assignment brief or deliverables", "report sections, slides, data analysis…"), TXT("avail", "Availability clashes", "Ana away 10–14 Mar, Ben has exams week 6")],
    "Brief: {brief}. Availability: {avail}. Break the project into a table (Task | Owner | Est. hours | Due | Needs from others) that balances hours across the team and lands everything a week before the profile's deadline for integration. Then steps for the three integration milestones (first stitch, full draft, final polish) with what each person brings, and a callout on the highest-risk dependency and how to de-risk it now.",
    "table, steps, callout", "Split it", "Dealing the cards…"),
  T("minutes", "Minutes from my notes", "Rough notes → decisions and actions", "📝",
    [LONG("notes", "Rough meeting notes", "talked about intro, Ben will do charts by fri?, need to ask tutor re word count…")],
    "Notes: {notes}. Write a kv (Date, Attendees, Absent, Next meeting), bullets of decisions made (one line each, no discussion), a checklist of actions in the form 'Owner — action — due date' with any missing owner or date marked '[decide]', and a quote with a short follow-up message for the group chat so people who missed it know exactly what to do.",
    "kv, bullets, checklist, quote", "Write minutes", "Capturing…"),
  T("talk", "The awkward conversation", "Someone's not pulling their weight", "😬",
    [LONG("situation", "What's happening", "Sam hasn't replied in 9 days and owns the data section"), CH("tone", "Tone", ["Gentle check-in", "Direct but kind", "Formal / final warning"], "Direct but kind"), CH("channel", "Channel", ["Group chat", "Private message", "In person", "Email to tutor"], "Private message")],
    "Situation: {situation}. Tone: {tone}. Channel: {channel}. Explain in text the likely reasons a teammate goes quiet and why the first message should offer an exit ramp. Then a quote with the exact message to send in the chosen channel and tone, plus a second version one step firmer, steps for the escalation ladder with time limits at each rung (message → call → group meeting → tutor), and a callout on documenting contributions before escalating.",
    "text, quote, steps, callout", "Script it", "Choosing words…"),
  T("peer", "Peer assessment", "Fair, evidenced, not petty", "⚖️",
    [LONG("contrib", "What each person did", "Ana wrote sections 1–2 and edited all; Ben charts late but good; …"), CH("format", "Format required", ["Score out of 10 + comment", "Percentage split", "Written statement only"], "Score out of 10 + comment")],
    "Contributions: {contrib}. Format: {format}. Produce a table (Member | Delivered | Quality | Reliability | Suggested rating) with ratings justified by evidence not feelings, a quote with a fair written comment per member in the required format that a tutor could read without wincing, and a callout on what to do if the assessment is not anonymous.",
    "table, quote, callout", "Assess fairly", "Weighing it up…")])

APP("quiet_hall", "Quiet Hall", "Exam nerves handled: the night before, in the room, after", "Education", ["#37474F", "#80CBC4", "#FFCC80"], "heart",
 "Quiet Hall is a pocket toolkit for exam anxiety: a night-before plan, a 60-second reset for panic in the room, a strategy for when your mind goes blank, a stop to the post-exam spiral, and help requesting the support you are entitled to.",
 "You are a university counsellor trained in CBT and exam-stress support: warm, concrete, never dismissive, and clear about when a student should speak to a professional.",
 "Walk in steadier", "A little about how anxiety shows up for you makes the tools sharper.", ["Night-before plans with clock times", "60-second in-room resets", "Post-exam spiral stoppers"],
 [NAME, CH("shows", "How it shows up", ["Racing heart", "Blank mind", "Nausea", "Can't sleep before", "Overthinking after", "Avoidance"], "", True), CH("format", "Exam format", ["Written, in a hall", "Multiple choice", "Online / open book", "Oral / viva", "Practical"], "Written, in a hall"), TXT("history", "Anything that's helped before", "walking, breathing app, talking to a friend")],
 [T("night", "Night-before plan", "Sleep, bag, brain, all sorted", "🌙",
    [TXT("exam", "Exam and time", "Microeconomics, 9am", True), CH("feeling", "Right now I feel", ["Wired", "Exhausted", "Numb", "Okay-ish", "Panicking"], "Wired"), TXT("bedtime", "Planned bedtime", "23:00")],
    "Exam: {exam}. Feeling: {feeling}. Bedtime: {bedtime}. Produce steps for the evening with clock times working back from bedtime (light-review cap, food, screens, wind-down, what to do if sleep doesn't come), a checklist for the bag and the morning (ID, permitted items, route, breakfast), a callout on why the all-nighter loses marks, and a quote with a short, believable sentence to say to yourself when the worry starts.",
    "steps, checklist, callout, quote", "Plan tonight", "Settling in…"),
  T("reset", "Panic in the room", "60 seconds to get back to the paper", "🫁",
    [CH("symptom", "What's happening", ["Heart racing", "Can't breathe properly", "Shaking hands", "Feel sick", "Tears", "Frozen"], "Heart racing"), CH("left", "Time left", ["Just started", "Middle", "Last 20 minutes"], "Middle")],
    "Symptom: {symptom}. Time left: {left}. Give steps for a 60-second reset that can be done silently at a desk (breathing count, grounding on the paper, posture, one micro-task), then bullets on re-entering the exam given the time left (which question to pick first, how to bank easy marks), a quote with a three-word cue to write in the margin, and a callout on when and how to signal an invigilator and what they can do.",
    "steps, bullets, quote, callout", "Reset me", "Breathing…"),
  T("blank", "Mind went blank", "Retrieve it, or earn partial credit", "🧠",
    [TXT("topic", "The question topic", "supply and demand elasticity", True), CH("qtype", "Question type", ["Essay", "Short answer", "Calculation", "Multiple choice"], "Essay")],
    "Blank on: {topic}. Question type: {qtype}. Provide steps for cued retrieval (rewrite the question in your own words, list any related word, sketch a diagram, recall the lecture's context) taking under 3 minutes, bullets of partial-credit tactics specific to this question type (define terms, state the method, show structure), a table (If you remember only… | Write this) with 4 rows, and a quote with a starting sentence that opens the answer without committing to facts you don't have yet.",
    "steps, bullets, table, quote", "Help me recall", "Searching memory…"),
  T("after", "Post-exam spiral", "Stop replaying it", "🔁",
    [LONG("replay", "What you keep replaying", "I think I misread question 3 and everyone said it was easy"), CH("next", "What's next", ["Another exam tomorrow", "Another exam this week", "That was the last one"], "Another exam this week")],
    "Replaying: {replay}. Next: {next}. Write a table (Thought | Evidence for | Evidence against | More balanced thought) for the 2 strongest worries, text on why post-mortems with classmates inflate anxiety and rarely change marks, steps for the next 3 hours that close the loop (one-line note of anything to check later, movement, food, a firm rule on not discussing answers), and a callout on signs the spiral is more than exam stress and who to contact at a university (counselling, GP, crisis line).",
    "table, text, steps, callout", "Break the loop", "Unwinding…"),
  T("support", "Ask for adjustments", "Extra time, separate room, deferrals", "📨",
    [LONG("situation", "Your situation", "diagnosed anxiety, panic attacks in exam halls, no formal support yet"), CH("want", "What you need", ["Extra time", "Separate / smaller room", "Rest breaks", "Deferral", "Not sure what exists"], "Not sure what exists")],
    "Situation: {situation}. Looking for: {want}. Give bullets of the adjustments universities commonly offer for anxiety and the evidence usually required (without promising what any institution will grant), a checklist of steps from first contact to the exam with typical lead times, a quote with an email to the disability or wellbeing service requesting a meeting that states the need without over-disclosing, and a callout on deadlines: adjustments are often needed weeks before the exam period.",
    "bullets, checklist, quote, callout", "Draft request", "Finding support…")], MH)

APP("lit_matrix", "Lit Matrix", "A literature review that argues, not a list of summaries", "Education", ["#4527A0", "#827717", "#FF8F00"], "graph",
 "Lit Matrix builds database search strings, logs each paper into a synthesis matrix, groups them into themes, finds the gap your study fills and turns your notes into synthesis paragraphs that compare rather than list.",
 "You are a research-methods tutor who teaches systematic searching and synthesis: rigorous about sources, blunt about paper-by-paper listing, and insistent that every theme relates back to the research question.",
 "Build the review", "Your research question anchors every search, matrix row and paragraph.", ["Boolean search strings per database", "Synthesis matrix, one paper at a time", "Themes, gaps and synthesis paragraphs"],
 [NAME, LONG("rq", "Your research question", "How does remote work affect junior employees' skill development?", False), CH("field", "Field", ["Social sciences", "Health / medicine", "Business", "Education", "STEM / engineering", "Humanities", "Law"], "Social sciences"), CH("scope", "Review type", ["Undergraduate dissertation", "Master's thesis", "Systematic review", "PhD chapter"], "Undergraduate dissertation")],
 [T("search", "Search strings", "Boolean strings per database", "🔎",
    [LONG("concepts", "Key concepts", "remote work; skill development; early-career employees"), TXT("limits", "Limits", "2015 onwards, English, peer-reviewed")],
    "Concepts: {concepts}. Limits: {limits}. Build a table (Concept | Synonyms and related terms | Truncation / wildcards) with at least 5 alternatives per concept, then a second table (Database | Search string | Filters to apply) for 4 databases appropriate to the profile's field with full Boolean syntax, a kv of inclusion and exclusion criteria written so two people would apply them the same way, and a callout on recording the search (date, hits, database) for the methods section.",
    "table, kv, callout", "Build strings", "Combining terms…"),
  T("add", "Add a paper", "Abstract or notes → matrix row", "📄",
    [LONG("paper", "Citation + abstract or your notes", "Smith & Lee (2021)… paste the abstract"), TXT("why", "Why you picked it", "highly cited, same population")],
    "Paper: {paper}. Reason chosen: {why}. Extract a kv (Citation, Aim, Theory or framework, Design and method, Sample and setting, Key findings, Limitations, Quality rating and why). Then a table with a single synthesis-matrix row (Author, year | Concept A | Concept B | Concept C | Relevance to RQ) using concepts drawn from the profile's research question, bullets on how it agrees or conflicts with typical findings in the field, and a callout on anything in the abstract that needs checking in the full text before citing.",
    "kv, table, bullets, callout", "Add to matrix", "Filing…"),
  T("themes", "Find the themes", "Many papers → themes and the gap", "🧭",
    [LONG("matrix", "Paste your matrix or notes on several papers", "Smith 2021: mentoring drops 40% remote; Ahmed 2020: …")],
    "Notes: {matrix}. Group the papers into 3–5 themes as a table (Theme | Papers | Where they agree | Where they conflict | Strength of evidence), write text identifying the gap or tension the profile's research question can address and the sentence that states it, bullets of alternative structures for the review (chronological, thematic, methodological) with which fits best and why, and a callout warning of any theme resting on a single paper.",
    "table, text, bullets, callout", "Find themes", "Sorting the pile…"),
  T("appraise", "Appraise a study", "Is it strong enough to lean on?", "🔬",
    [LONG("method", "The paper's method section or your summary", "cross-sectional survey, n=120, one company, self-report"), CH("design", "Design", ["RCT / experiment", "Survey / cross-sectional", "Qualitative interviews", "Case study", "Review / meta-analysis", "Mixed methods", "Not sure"], "Not sure")],
    "Method: {method}. Design: {design}. Appraise with a table (Criterion | Verdict | Why) using criteria appropriate to the design (sampling, measurement validity, confounders, reflexivity, analysis transparency, generalisability), a kv with an overall rating (Strong / Moderate / Weak) and the one sentence to use when citing it with appropriate hedging, and bullets of limitations the student can raise in the review without being unfair.",
    "table, kv, bullets", "Appraise", "Scrutinising…"),
  T("synth", "Synthesis paragraph", "Your notes on a theme → one argued paragraph", "✍️",
    [TXT("theme", "Theme", "loss of informal mentoring in remote teams", True), LONG("evidence", "Your notes: who found what", "Smith 2021 found…; Ahmed 2020 contradicts…; Ng 2022 explains…")],
    "Theme: {theme}. Evidence: {evidence}. Write a text paragraph plan (claim → evidence compared → explanation of disagreement → link to RQ) with the key sentence written out for each move, then a quote with one model synthesis paragraph built strictly from the student's notes, citing in author-date form and using comparison language (whereas, similarly, in contrast), and bullets showing three places where the paragraph avoids paper-by-paper listing and how.",
    "text, quote, bullets", "Synthesise", "Weaving…")])

APP("lecture_lens", "Lecture Lens", "Slides and scribbles into notes you'll actually revise", "Education", ["#F9A825", "#283593", "#E53935"], "bulb",
 "Lecture Lens turns photos of slides and messy lecture scribbles into Cornell-style notes, flashcards, concept maps and a weekly consolidation session, so notes get made once and used many times.",
 "You are a learning-skills tutor who lives by active recall and spaced repetition: crisp, structured, and always turning content into questions.",
 "Notes that work for you", "Tell us your modules and how you like to learn.", ["Slide photo → structured notes", "Cornell format and flashcards", "Weekly consolidation sessions"],
 [NAME, TXT("modules", "Modules this term", "Cell Biology, Statistics 1, Genetics"), CH("style", "Notes style", ["Cornell", "Outline", "Mind map", "Q&A"], "Cornell"), CH("tool", "Where notes live", ["Paper", "Notion / OneNote", "Anki", "Google Docs", "Other"], "Notion / OneNote")],
 [T("slide", "Snap a slide", "Photo → what it means and what's examinable", "📷",
    [PHOTO("Photo of the slide or board", "", True), TXT("module", "Module", "Cell Biology")],
    "From the photo (module: {module}), write a text explanation of the slide in plain language at the level of a student meeting it for the first time, a kv of every term or symbol defined, bullets of the 3 things a lecturer usually wants remembered from a slide like this, and a callout with the exam question it is most likely to become.",
    "text, kv, bullets, callout", "Explain slide", "Zooming in…"),
  T("cornell", "Cornell my notes", "Messy notes → cues, notes, summary", "📓",
    [LONG("notes", "Your lecture notes", "paste or type the mess"), TXT("topic", "Lecture topic", "Krebs cycle")],
    "Topic: {topic}. Notes: {notes}. Restructure into a table (Cue or question | Notes) where every cue is a question the notes column answers, then text with a 3-sentence summary in the student's voice, a checklist of gaps and unclear points to check against the slides or textbook, and bullets on which items are pure recall versus need understanding.",
    "table, text, checklist, bullets", "Cornell it", "Restructuring…"),
  T("cards", "Make flashcards", "Notes → 15 spaced-repetition cards", "🗂️",
    [LONG("source", "Notes or slide text", ""), CH("mix", "Card mix", ["Mostly recall", "Mostly understanding", "Balanced", "Cloze deletions"], "Balanced")],
    "Source: {source}. Mix: {mix}. Produce a table of 15 cards (Front | Back | Type: recall / why / apply / cloze) written so the front has one answer and the back is under 25 words, formatted so it can be pasted into the profile's notes tool. Then bullets on a review schedule (day 1, 3, 7, 14, 30) and a callout on the two cards most likely to be too vague and how to split them.",
    "table, bullets, callout", "Make cards", "Cutting cards…"),
  T("map", "Concept map", "Topic → nodes and links", "🕸️",
    [TXT("topic", "Topic", "photosynthesis", True), LONG("notes", "Your notes (optional)", "", False)],
    "Topic: {topic}. Notes: {notes}. Build a table (Concept | Links to | Relationship in 3–5 words) with 12–20 links suitable for drawing, steps for laying it out on one page (centre, first ring, second ring, cross-links), a quote with the one-sentence takeaway that should sit under the map, and bullets of 3 cross-links students usually miss.",
    "table, steps, quote, bullets", "Map it", "Connecting dots…"),
  T("weekly", "Weekly consolidation", "90 minutes that beat cramming", "📅",
    [LONG("covered", "What each module covered this week", "Cell Bio: membranes, transport; Stats: t-tests…"), CH("time", "Time available", ["45 min", "90 min", "2 hours"], "90 min")],
    "This week: {covered}. Time: {time}. Build steps for a consolidation session within the time (per block: module, activity, minutes) mixing recall, self-testing and one synthesis task, a table (Module | Weakest topic | Why it's weak | Fix this week), and a checklist of what to carry into next week's lectures (questions to ask, prep reading).",
    "steps, table, checklist", "Plan session", "Consolidating…")])

APP("seminar_ready", "Seminar Ready", "Read smarter, then say something worth hearing", "Education", ["#1B5E20", "#BF360C", "#FDD835"], "mic",
 "Seminar Ready triages your reading list, decodes dense passages, prepares talking points and sharp questions, and debriefs after the seminar so you show up prepared and get credit for participating.",
 "You are a seminar tutor who loves a well-prepared student: candid about what can be skimmed, generous with reading strategies, and encouraging to people who hate speaking up.",
 "Speak up with confidence", "Tell us your course and how you feel about speaking so prep matches the room.", ["Reading-list triage with minutes per item", "Dense passages decoded", "Talking points and good questions"],
 [NAME, TXT("course", "Course / module", "Political Theory, 2nd year"), CH("speaking", "Speaking in seminars", ["Hate it", "Nervous but try", "Comfortable", "Too much"], "Nervous but try"), CH("assessed", "Participation graded?", ["Yes", "No", "Not sure"], "Not sure")],
 [T("triage", "Triage the reading list", "Hours available → what to read how", "⏱️",
    [LONG("list", "This week's readings", "paste the list with page counts if known"), NUM("hours", "Hours you actually have", "4"), TXT("focus", "Seminar question / focus", "Is Rawls' veil of ignorance persuasive?")],
    "Readings: {list}. Hours: {hours}. Seminar focus: {focus}. Produce a table (Reading | Priority | Mode: deep / strategic / abstract-and-conclusion / skip | Minutes | What to extract) that fits within the hours, then steps for the reading order with the strategic-reading routine for each mode (abstract → conclusion → headings → first sentences), and a callout on which reading the tutor will almost certainly build the discussion around.",
    "table, steps, callout", "Triage", "Prioritising…"),
  T("decode", "Decode a passage", "Photo or paste → plain English", "🔍",
    [PHOTO("Photo of the page (optional)"), LONG("passage", "Or paste the passage", "", False), TXT("author", "Author / text", "Foucault, Discipline and Punish")],
    "Passage (from the photo or the text): {passage}. Source: {author}. Give a text restatement in plain English at roughly half the length, a kv glossary of the jargon and any names referenced, bullets of the author's argument as claim → reasons → what they are arguing against, and a quote with one sentence the student could say in the seminar that shows they understood it.",
    "text, kv, bullets, quote", "Decode", "Translating…"),
  T("points", "Talking points", "Your reaction → 3 things to say", "💬",
    [TXT("reading", "The reading", "Rawls, A Theory of Justice, ch. 3", True), LONG("reaction", "Your honest reaction", "seems idealistic; how would this work with real inequality?")],
    "Reading: {reading}. Reaction: {reaction}. Produce bullets of 3 talking points, each with a claim, a reference to a specific part of the reading and a why-it-matters, a quote with an opening line for the student's first contribution calibrated to the profile's comfort with speaking, a table (If someone says… | You could respond…) with 4 rows for likely pushback, and a callout on the minimum viable contribution if nerves win: one question, asked early.",
    "bullets, quote, table, callout", "Prep points", "Sharpening…"),
  T("ask", "Ask a good question", "Four kinds of question, ready to go", "❓",
    [TXT("reading", "The reading or topic", "", True)],
    "For {reading}, write cards for 4 questions (meta = type: clarifying · challenging · connecting · applying), each card with the question, why it's a good one and a follow-up if the room goes quiet. Then bullets on timing: when in the seminar each type lands best.",
    "cards, bullets", "Give me questions", "Wondering…"),
  T("debrief", "After the seminar", "What happened, what next", "📝",
    [LONG("what", "What happened", "said one thing, tutor pushed back, didn't know how to respond"), CH("felt", "How it felt", ["Went well", "Okay", "Embarrassing", "Said nothing"], "Okay")],
    "What happened: {what}. Felt: {felt}. Write text reframing the experience honestly (what worked, what the tutor's pushback usually means), a kv logging the seminar (Key idea, Best point heard, My contribution, Open question), steps for next week that are one notch braver than this week, and a quote with the sentence to use next time when challenged ('That's fair — I think the stronger version of my point is…').",
    "text, kv, steps, quote", "Debrief", "Reflecting…")])

APP("rubric_radar", "Rubric Radar", "Decode the brief, hit the top band, learn from feedback", "Education", ["#B71C1C", "#455A64", "#FFC107"], "scale",
 "Rubric Radar reads assignment briefs and marking rubrics so you write to the top band, translates marker feedback into concrete fixes, calculates what you need on the next assessment and drafts extension requests that get approved.",
 "You are a study-skills adviser who has read thousands of rubrics: forensic about criteria, plain-spoken about what 'critical analysis' actually means, and honest about grade maths.",
 "Play the assessment game well", "Your course and target grade shape every plan.", ["Briefs and rubrics decoded", "Feedback turned into fixes", "Grade calculator and extension emails"],
 [NAME, TXT("course", "Course", "BA History, year 2"), CH("target", "Target grade", ["Pass", "Merit / 2:2", "Distinction / 2:1", "First / A"], "Distinction / 2:1"), CH("system", "Grading system", ["UK classification", "US GPA / letters", "Percentage", "ECTS / other"], "UK classification")],
 [T("brief", "Decode the brief", "Paste the assignment → what they really want", "🔎",
    [LONG("brief", "Assignment brief", "paste the task description")],
    "Brief: {brief}. Extract a kv (Task in one sentence, Word count, Weighting, Due date, Format and referencing, Submission route). Then a table (Requirement | Where the brief says it | How it will be assessed) including implicit requirements hidden in verbs like 'evaluate' or 'critically discuss', a checklist of deliverables and formatting to tick before submitting, and a callout on the most commonly missed requirement in briefs like this.",
    "kv, table, checklist, callout", "Decode brief", "Between the lines…"),
  T("rubric", "Rubric to plan", "Criteria → what the top band looks like", "🎯",
    [LONG("rubric", "Marking rubric / criteria", "paste the grid or descriptors"), TXT("piece", "What you're writing", "2,500-word essay on the causes of the 1848 revolutions")],
    "Rubric: {rubric}. Piece: {piece}. Produce a table (Criterion | Weight | Top-band descriptor in plain English | What that looks like in this piece | Words to spend) aimed at the profile's target grade, bullets translating vague rubric words (critical, synthesis, originality, structure) into observable features, and steps for a self-marking pass the night before submission.",
    "table, bullets, steps", "Plan to rubric", "Mapping criteria…"),
  T("feedback", "Decode feedback", "Marker comments → fixes for next time", "📝",
    [LONG("comments", "Marker's comments", "'Good grasp but descriptive in places; engage more critically with the secondary literature.'"), TXT("mark", "Mark received", "58")],
    "Feedback: {comments}. Mark: {mark}. Build a table (Comment | What it actually means | Evidence a marker looks for | Fix next time), text on the gap between the mark and the profile's target and which single change closes most of it, steps for applying the fixes on the next assignment from planning to final read, and a quote with a short, non-defensive email asking the marker for a feedback conversation.",
    "table, text, steps, quote", "Decode feedback", "Translating…"),
  T("grade", "What do I need?", "Current marks → required scores", "🧮",
    [LONG("marks", "Marks so far with weights", "Essay 1: 62 (30%), Presentation: 70 (20%)"), LONG("remaining", "Remaining assessments with weights", "Exam (50%)")],
    "So far: {marks}. Remaining: {remaining}. Compute a kv (Current weighted average, Weight remaining, Mark needed on remaining for the profile's target, Mark needed for the band below, Best achievable), a table (Remaining assessment | Weight | Needed for target | Needed for band below), and a callout on realism: how the needed mark compares to marks so far and where the effort pays most.",
    "kv, table, callout", "Calculate", "Doing the maths…"),
  T("extension", "Extension request", "Say the right thing, attach the right evidence", "📨",
    [LONG("reason", "Why you need it", "flu since Monday, GP note available"), TXT("days", "Days requested", "5"), TXT("deadline", "Original deadline", "Friday 14th")],
    "Reason: {reason}. Requesting: {days} days. Deadline: {deadline}. Write a quote with a concise, honest extension-request email that states the reason, the evidence attached, the new date requested and a commitment, then a checklist of evidence and forms universities typically ask for in this situation, bullets on what usually strengthens or weakens a request, and a callout on the alternative if the extension is refused (late-penalty maths, mitigating-circumstances routes).",
    "quote, checklist, bullets, callout", "Draft request", "Writing carefully…")])

APP("fieldwork_kit", "Fieldwork Kit", "Surveys, interviews and ethics forms that get approved", "Education", ["#006064", "#AD1457", "#9E9D24"], "note",
 "Fieldwork Kit helps student researchers design questionnaires, write interview guides, draft ethics applications and consent forms, recruit participants and take a first pass at coding qualitative data.",
 "You are a research-methods lecturer and ethics-committee reviewer: practical, protective of participants, and insistent that nothing is collected before approval.",
 "Collect data properly", "Your study design shapes every instrument and form.", ["Questionnaires without leading questions", "Interview guides with probes", "Ethics applications and consent sheets"],
 [NAME, LONG("study", "Your study in one or two sentences", "Interviews with 12 nurses about shift handovers", False), CH("participants", "Participants", ["Adults (general)", "Students", "Professionals / employees", "Patients or service users", "Children / under 18", "Vulnerable groups"], "Adults (general)"), CH("approach", "Approach", ["Quantitative", "Qualitative", "Mixed methods"], "Qualitative")],
 [T("survey", "Design a questionnaire", "Constructs → clean questions", "📊",
    [LONG("constructs", "What you need to measure", "job satisfaction, intention to leave, perceived support"), NUM("length", "Max minutes to complete", "8"), CH("platform", "Platform", ["Qualtrics", "Google Forms", "Microsoft Forms", "Paper", "Other"], "Google Forms")],
    "Constructs: {constructs}. Max length: {length} minutes. Platform: {platform}. Produce a table (# | Question | Type | Scale or options | Construct measured) in a logical order (screeners → easy → sensitive → demographics) that fits the time limit, bullets of pitfalls checked (leading, double-barrelled, acquiescence, missing 'prefer not to say'), steps for a 5-person pilot and what to change after it, and a callout on validated scales that may already exist for these constructs and the permission needed to use them.",
    "table, bullets, steps, callout", "Design survey", "Drafting items…"),
  T("interview", "Interview guide", "Opening, core questions, probes, close", "🎙️",
    [LONG("aims", "What you want to learn", "how handovers fail and what nurses do to cope"), CH("style", "Style", ["Semi-structured", "Structured", "Narrative / life history", "Focus group"], "Semi-structured"), NUM("mins", "Interview length (min)", "45")],
    "Aims: {aims}. Style: {style}. Length: {mins} minutes. Write steps for the guide (opening script, warm-up, 6–8 core questions each with 2 probes, closing) with minutes per section, a quote with the verbatim opening including consent reminder and recording check, a checklist for the interviewer (equipment, safeguarding, what to do if the participant is upset), and bullets on avoiding leading questions specific to the profile's participants.",
    "steps, quote, checklist, bullets", "Build guide", "Composing…"),
  T("ethics", "Ethics application", "Study → risks, mitigations, attachments", "📋",
    [LONG("design", "Study design in detail", "who, how recruited, what they'll do, where data is stored"), CH("data", "Data sensitivity", ["Anonymous", "Pseudonymised", "Identifiable", "Special category (health, ethnicity…)"], "Pseudonymised")],
    "Design: {design}. Data: {data}. Draft a kv of the sections a typical university ethics form asks for (Aims, Participants and recruitment, Procedure, Risks to participants, Risks to researcher, Data storage and retention, Withdrawal, Debrief) with a filled paragraph each. Then a table (Risk | Likelihood | Mitigation | Who to contact), a checklist of attachments (info sheet, consent form, recruitment text, instruments, gatekeeper letters), and a callout that this is a draft: the institution's committee decides, and no data may be collected before written approval.",
    "kv, table, checklist, callout", "Draft application", "Filling the form…"),
  T("consent", "Info sheet & consent", "Participant-facing documents", "✅",
    [TXT("title", "Study title", "", True), TXT("contact", "Your name, role, email", "Priya Shah, MSc student, p.shah@…")],
    "Study: {title}. Researcher: {contact}. Write text for a participant information sheet in plain language (purpose, what taking part involves and how long, risks and benefits, confidentiality and data handling, right to withdraw, who to complain to), a checklist of consent statements a participant ticks and initials, and a quote with a short recruitment message for email or a poster that a gatekeeper would approve. Base the details on the profile's study and participants.",
    "text, checklist, quote", "Write documents", "Drafting…"),
  T("code", "Code my transcripts", "Excerpts → codes and candidate themes", "🏷️",
    [LONG("excerpts", "Transcript excerpts", "P3: 'Handover is when everything goes wrong, you just hope…'"), CH("method", "Method", ["Thematic analysis (reflexive)", "Content analysis", "Framework analysis", "Grounded theory (initial coding)"], "Thematic analysis (reflexive)")],
    "Excerpts: {excerpts}. Method: {method}. Produce a table (Excerpt | Initial code | Candidate theme | Note) with codes staying close to participants' words, bullets of emerging candidate themes with the excerpts supporting each, steps for the next stage of the chosen method (collating, reviewing, defining themes), and a callout on reflexivity: what assumptions the researcher should log about this coding pass.",
    "table, bullets, steps, callout", "Code it", "Reading closely…")], ETHICS)
