from dsl import *
HR = "General management guidance, not legal or HR advice. Employment rules vary by jurisdiction; follow your organisation's policies and involve HR or legal counsel on ratings, pay, conduct and employment decisions."

# 1 — 1:1s (manager side)
APP("one_on_one_prep", "1:1 Prep", "Walk into every 1:1 knowing what matters", "Business", ["#00695C", "#FF7043", "#5C6BC0"], "chat",
 "1:1 Prep turns your scrappy notes into a focused agenda for each direct report, gives you the right questions for the moment, tracks what you promised, and catches the quiet signs that someone is drifting.",
 "You are a seasoned people manager and coach: curious before directive, allergic to status-update 1:1s, and firm that the meeting belongs to the report, not the manager.",
 "Make every 1:1 count", "Tell us about your team and how you like to run things.", ["Agendas from your rough notes", "Questions for any situation", "Never drop a follow-up again"],
 [NAME, NUM("reports", "Direct reports", "6"), CH("cadence", "1:1 cadence", ["Weekly", "Fortnightly", "Monthly"], "Weekly"), CH("style", "Your style", ["Coaching", "Hands-on", "Hands-off", "Still figuring it out"])],
 [T("prep", "Prep this 1:1", "Notes → a focused agenda", "🗒️",
    [TXT("who", "Who", "Priya, senior engineer, 2 years in", True), LONG("notes", "Your notes since last time", "shipped the billing fix late; seemed flat on Tuesday; asked about conference budget"), CH("focus", "Lean toward", ["Their agenda", "Career", "A concern I have", "Recognition", "Catch-up"], "Their agenda")],
    "Prepare a 1:1 (at the profile's cadence) with {who}, leaning toward '{focus}', from these notes: {notes}. Produce a kv (opening question, one thing to recognise, one thing to probe, time split in minutes), a checklist agenda of at most 5 items with the report's items first, and bullets of 3 follow-up questions to use if the conversation stalls. Finish with a callout on anything in the notes that hints at a bigger issue to handle separately.",
    "kv, checklist, bullets, callout", "Prep it", "Reading your notes…"),
  T("questions", "Question bank", "The right questions for the moment", "❓",
    [CH("situation", "Situation", ["New hire", "Seems disengaged", "Just got promoted", "After a failure", "High performer, bored", "Remote, hard to read", "Returning from leave"], "Seems disengaged")],
    "Give me 1:1 questions for the situation '{situation}', suited to the profile's style. Bullets of 8 open questions ordered from safest to most direct, a table (Question | What a good answer sounds like | What a worrying answer sounds like) for the 3 most important ones, and a callout on what NOT to ask or say in this situation.",
    "bullets, table, callout", "Give me questions", "Thinking…"),
  T("followups", "Track my promises", "Paste notes → every open commitment", "📌",
    [LONG("log", "Paste notes from recent 1:1s", "Mon w/ Sam: I'll ask about the training budget; Sam to draft proposal by Fri…")],
    "From these 1:1 notes: {log} — extract every commitment. Table (Owner | Commitment | Due | Status guess) with the manager's own promises listed first, a checklist of what the manager must do before the next round of 1:1s, and a quote with a two-line message to send a report whose item is overdue.",
    "table, checklist, quote", "Extract", "Finding promises…"),
  T("drift", "Is someone drifting?", "Read the quiet signals", "🧭",
    [TXT("who", "Who", "Jordan", True), LONG("signals", "What you've noticed", "camera off, shorter answers, missed two standups, used to volunteer for demos")],
    "Interpret these signals about {who}: {signals}. Text with the 3 most likely explanations ranked from benign to serious, bullets of what to observe over the next two weeks, steps for a gentle check-in conversation with the exact opening line, and a callout on when to involve HR or an employee-assistance programme rather than handle it alone.",
    "text, bullets, steps, callout", "Interpret", "Reading signals…"),
  T("skip", "Skip-level 1:1", "Meet your reports' reports well", "🪜",
    [TXT("who", "Who and their manager", "Lee, reports to Dana", True), CH("goal", "Goal", ["Get to know them", "Check on their manager", "Hear about the team", "Career interest"], "Get to know them")],
    "Plan a skip-level 1:1 with {who} where the goal is '{goal}'. Steps for the 30 minutes with timings, bullets of 6 questions that won't feel like spying on their manager, a quote with how to open the meeting so it feels safe, and a callout on what to do with anything sensitive they tell you.",
    "steps, bullets, quote, callout", "Plan it", "Climbing a level…")])

# 2 — Performance reviews (manager side)
APP("review_writer", "Review Writer", "Fair, evidence-based reviews without the dread", "Business", ["#37474F", "#FFB300", "#00ACC1"], "note",
 "Review Writer turns a year of scattered notes into fair, evidence-based performance reviews, checks your language for bias, calibrates ratings across the team and preps you to deliver the hard ones.",
 "You are an experienced HR business partner and manager coach: evidence over adjectives, calibrated and fair, and aware that vague language is where bias hides.",
 "Reviews people can actually use", "A few details about your review cycle keep the drafts on-format.", ["Drafts from your notes and their self-review", "Bias and vagueness check", "Calibration across your team"],
 [NAME, CH("scale", "Rating scale", ["3-point", "4-point", "5-point", "No ratings"], "5-point"), TXT("format", "Your company's review sections", "Impact, Behaviours, Growth areas"), CH("teamtype", "Team type", ["Engineering", "Sales", "Ops", "Creative", "Support", "Mixed"])],
 [T("draft", "Draft a review", "Notes + self-review → full draft", "✍️",
    [TXT("who", "Who and role", "Ana, product designer L3", True), LONG("evidence", "Your notes and examples", "led checkout redesign, +8% conversion; missed 2 deadlines in Q2; mentored intern…"), LONG("self", "Their self-review (optional)", "", False)],
    "Write a performance review for {who} on the profile's rating scale using its review sections, from this evidence: {evidence} and their self-review: {self}. Produce text for each section citing specific examples with outcomes, a kv (proposed rating, one-line justification, biggest strength, biggest gap), a table (Claim in self-review | Manager's view | Evidence) for anything where you and they differ, and a callout flagging statements that need more evidence before they go in.",
    "text, kv, table, callout", "Draft review", "Weighing evidence…"),
  T("bias", "Bias & vagueness check", "Audit a draft before it's sent", "🔍",
    [LONG("review", "Paste a draft review", "Sam is a great team player but can be abrasive…")],
    "Audit this review draft for bias and vagueness: {review}. Table (Phrase | Problem — personality not behaviour, gendered pattern, no evidence, recency | Rewrite), bullets on the overall balance of praise vs critique and whether the rating matches the text, and a quote with the rewritten review at the same length and rating.",
    "table, bullets, quote", "Audit", "Reading closely…"),
  T("calibrate", "Calibrate my team", "Consistent ratings across people", "⚖️",
    [LONG("team", "Your team with proposed ratings and one line each", "Ana 4 – shipped checkout; Ben 3 – solid, no stretch; Cai 5 – …")],
    "Calibrate these proposed ratings on the profile's rating scale: {team}. Table (Person | Proposed | Suggested | Why) checking for consistency across similar evidence, bullets on distribution risks (too many top ratings, harshness toward one person, tenure or visibility bias), and steps to prepare for the calibration meeting including the one case to defend hardest.",
    "table, bullets, steps", "Calibrate", "Comparing…"),
  T("deliver", "Deliver a tough review", "Script the conversation", "🎙️",
    [TXT("who", "Who", "Ben", True), CH("news", "The hard part", ["Lower rating than they expect", "No promotion this cycle", "Behaviour problem", "Role no longer a fit", "Great review but no raise"], "Lower rating than they expect"), TXT("context", "Context", "he's been here 5 years and thinks he's a 5")],
    "Script the review conversation with {who} where the hard part is '{news}', context: {context}. Steps for the 45 minutes with timings, a quote with the exact first two minutes word-for-word, a table (If they say | You say) for 5 likely reactions including anger and silence, and a callout on what must not be promised or implied in the room.",
    "steps, quote, table, callout", "Script it", "Rehearsing…"),
  T("goals", "Next-cycle goals", "Measurable goals for one person", "🎯",
    [TXT("who", "Who", "Ana", True), LONG("gaps", "Growth areas and team priorities", "needs to influence without authority; team priority is the mobile relaunch")],
    "Write next-cycle goals for {who} from: {gaps}. Table (Goal | Measure of success | Evidence to collect | Check-in date) with 3–4 goals mixing delivery and growth, bullets of stretch opportunities on the team's roadmap that serve these goals, and a quote with the one paragraph to paste into the review system.",
    "table, bullets, quote", "Set goals", "Planning…")], HR)

# 3 — Difficult feedback
APP("straight_talk", "Straight Talk", "Feedback that is kind, specific and unmissable", "Business", ["#C62828", "#FDD835", "#26A69A"], "mic",
 "Straight Talk helps managers give feedback that is specific, kind and impossible to misread: scripting the conversation, rehearsing the pushback, fixing the words before you say them and making praise land.",
 "You are a direct but humane feedback coach in the SBI and radical-candour tradition: behaviour not personality, one message per conversation, and never a compliment sandwich.",
 "Say the hard thing well", "How you naturally communicate shapes the scripts.", ["SBI scripts for any situation", "Rehearse the pushback", "Praise that actually lands"],
 [NAME, CH("tone", "Your natural tone", ["Blunt", "Diplomatic", "Conflict-avoidant", "Warm but rambling"]), CH("setting", "Usual setting", ["In person", "Video call", "Chat / async"], "Video call")],
 [T("script", "Script the feedback", "Situation → 90-second script", "🗣️",
    [TXT("who", "Who", "Marcus, senior analyst", True), LONG("issue", "What happened and the impact", "interrupted the client twice in the QBR; client emailed me about it"), CH("severity", "Severity", ["First mention", "Pattern", "Serious"], "First mention")],
    "Write feedback for {who} about: {issue} (severity: {severity}), adjusted for the profile's tone and setting. Quote with a Situation–Behaviour–Impact script under 90 seconds in plain spoken language, bullets of 3 questions to ask afterwards so it becomes a conversation, a kv (best time and place, what to leave out, the ask, follow-up date), and a callout on the one habit from the user's natural tone that would undermine the message.",
    "quote, bullets, kv, callout", "Write script", "Choosing words…"),
  T("rehearse", "Rehearse the pushback", "Play out how they might react", "🥊",
    [LONG("script", "Your planned feedback", "I want to talk about the QBR…"), CH("reaction", "Expect them to", ["Get defensive", "Go quiet", "Cry", "Argue the facts", "Blame someone else", "Agree too fast"], "Get defensive")],
    "Rehearse this feedback: {script}, assuming they {reaction}. Table (They say | You say | Why it works) for 5 escalating rounds, a callout on the moment to stop talking and listen, and bullets of 3 closing lines that keep the relationship intact without softening the ask.",
    "table, callout, bullets", "Rehearse", "Sparring…"),
  T("written", "Put it in writing", "Recap, async note or formal record", "📨",
    [TXT("who", "Who", "Marcus", True), LONG("said", "What was discussed or needs saying", "we agreed he'd let the client finish and check in with me before QBRs"), CH("purpose", "Purpose", ["Recap after talking", "Async first mention", "Formal record"], "Recap after talking")],
    "Write a message to {who} covering: {said}, for the purpose '{purpose}' and the profile's usual setting. Quote with the full message (under 150 words, no jargon, a specific ask and a date), bullets on what to change if this becomes an HR record, and a callout on what should never go in writing.",
    "quote, bullets, callout", "Write it", "Typing…"),
  T("critique", "Critique what I said", "Learn from a feedback moment that went badly", "🔁",
    [LONG("transcript", "What you actually said (as best you remember)", "So, um, don't take this the wrong way but some people felt you were a bit much in the meeting…")],
    "Critique this feedback as delivered: {transcript}. Table (What you said | Problem — hedging, vague, 'some people', personality label, sandwich | Better) line by line, a kv (clarity /10, kindness /10, did they know what to change: yes or no), and a quote with a short follow-up message that repairs the biggest problem without re-litigating everything.",
    "table, kv, quote", "Critique", "Replaying…"),
  T("praise", "Praise that lands", "Specific recognition, not 'great job'", "🌟",
    [TXT("who", "Who", "Lena", True), LONG("what", "What they did", "stayed late to fix the deploy and wrote a clear post-mortem")],
    "Turn this into specific recognition for {who}: {what}. Quote with the exact words to say in person (behaviour, impact, why it matters to you) followed by a public version for team chat, and bullets on how to make praise feel earned rather than routine for this person.",
    "quote, bullets", "Write praise", "Finding the words…")])

# 4 — Underperformance and improvement plans
APP("turnaround_plan", "Turnaround Plan", "Handle underperformance fairly and clearly", "Business", ["#4527A0", "#FF8F00", "#43A047"], "graph",
 "Turnaround Plan helps managers handle underperformance fairly: diagnose the real cause, set measurable improvement goals, run honest weekly check-ins, keep clean records and know when it's time to decide.",
 "You are a fair-minded manager coach with HR experience: you assume good faith, insist on clarity and measurable goals, and document without drama.",
 "Fair, clear, documented", "Tell us about your context so the plans fit your rules.", ["Diagnose skill, will or clarity", "Measurable improvement plans", "Check-ins and records that hold up"],
 [NAME, CH("hr", "HR support", ["Dedicated HR partner", "Shared HR", "None — it's me"], "Shared HR"), CH("region", "Region (for norms)", ["US", "UK / EU", "Other"], "US"), NUM("tenure", "Your years managing", "3")],
 [T("diagnose", "Diagnose the gap", "Skill, will, clarity or something else?", "🩺",
    [TXT("who", "Who and role", "Omar, account manager", True), LONG("gap", "What's going wrong", "missed quota 3 quarters; pipeline reports late; fine in meetings"), LONG("done", "What you've already tried", "two informal chats, paired him with Sara", False)],
    "Diagnose the performance gap for {who}: {gap}, given what's been tried: {done}. Table (Hypothesis — skill, will, clarity, capacity, fit, manager | Evidence for | Evidence against | How to test) for the 4 most plausible causes, text with your best single explanation and how confident to be, and a callout on whether this is a formal-plan situation yet or an expectations-reset conversation first.",
    "table, text, callout", "Diagnose", "Looking for causes…"),
  T("plan", "Draft the improvement plan", "Measurable, time-boxed, winnable", "📋",
    [TXT("who", "Who", "Omar", True), LONG("expectations", "What good looks like", "hit 80% of quota; pipeline updated every Friday; 10 discovery calls a week"), CH("weeks", "Duration", ["30 days", "45 days", "60 days", "90 days"], "60 days")],
    "Write a {weeks} improvement plan for {who} with these expectations: {expectations}. Table (Area | Current | Required | How measured | Support provided | Review date), steps for presenting it in the meeting, a quote with the plain-English opening statement that makes clear this is serious and also winnable, and a callout on what to have HR check before it's issued given the profile's HR support and region.",
    "table, steps, quote, callout", "Draft plan", "Setting the bar…"),
  T("checkin", "Weekly check-in", "Where they stand this week", "📆",
    [TXT("who", "Who", "Omar", True), LONG("week", "This week's results and observations", "7 discovery calls, report on time, seemed anxious")],
    "Run the weekly plan check-in for {who} from: {week}. kv (on track / at risk / off track per plan area, overall trajectory), bullets for the conversation naming what improved and what didn't in specific terms, a quote with the written summary to send afterwards, and a callout if anything suggests the plan itself needs adjusting.",
    "kv, bullets, quote, callout", "Check in", "Scoring the week…"),
  T("record", "Document it fairly", "Raw account → neutral file note", "🗃️",
    [LONG("event", "What happened", "Tuesday: pipeline report 2 days late again; said he forgot; I reminded him of the plan")],
    "Turn this into a clean file note: {event}. Quote with the note written for a neutral reader (date, facts, what was said by whom, agreed next step, no adjectives or speculation), bullets on what was removed from the raw account and why, and a checklist of what a complete performance file for this person should contain.",
    "quote, bullets, checklist", "Write note", "Sticking to facts…"),
  T("decide", "Time to decide?", "Extend, pass, move or exit", "🚦",
    [LONG("summary", "Where things stand", "45 days in; 2 of 4 areas met; attitude better; still no quota")],
    "Help decide the outcome of the plan from: {summary}. Table (Option — extend, close as passed, move role, exit | Case for | Case against | Risks), text with a recommendation and the evidence it rests on, steps for the next two weeks depending on the choice, and a callout on the HR and legal steps that must happen before any exit conversation in the profile's region.",
    "table, text, steps, callout", "Weigh it", "Deliberating…")], HR)

# 5 — Hiring: the last mile (selling, references, offers, rejections)
APP("offer_close", "Offer Close", "Land the candidate you want, let the rest down well", "Business", ["#1B5E20", "#FFC107", "#3949AB"], "spark",
 "Offer Close handles the last mile of hiring for managers: selling the role to the candidate you want, running reference calls that reveal something, making the offer call, handling counter-offers and saying no to everyone else with grace.",
 "You are a hiring manager's closer: honest about the role, candidate-centred, and clear that a hire who leaves in six months is worse than no hire.",
 "Close the candidate you want", "A little about your team makes every pitch specific.", ["Pitch the role to their motivations", "Reference calls that reveal something", "Offers, counter-offers and kind rejections"],
 [NAME, TXT("team", "Your team in one line", "8-person platform team at a Series B fintech"), TXT("sell", "Honest strengths of working here", "real ownership, small team, remote-first"), TXT("weak", "Honest weaknesses", "below-market base, on-call rota")],
 [T("pitch", "Sell the role", "A pitch built on what they care about", "🎁",
    [TXT("who", "Candidate", "Nadia, staff engineer from a big tech co", True), LONG("motives", "What you've learned they care about", "tired of politics; wants to ship; worried about stability; has a competing offer")],
    "Build a pitch for {who} based on what they care about: {motives} and the profile's honest strengths and weaknesses. Table (Their motivation | What we offer | Story or evidence to tell | Weak spot to own), a quote with a 60-second spoken pitch, bullets of 3 people or experiences to put in front of them before they decide, and a callout on the one thing not to overpromise.",
    "table, quote, bullets, callout", "Build pitch", "Finding the angle…"),
  T("reference", "Reference call", "Twenty minutes that actually tell you something", "📞",
    [TXT("who", "Candidate and role", "Nadia, staff engineer", True), LONG("concerns", "What you want to verify or worry about", "how she handles conflict; whether she really led the migration")],
    "Plan a 20-minute reference call about {who} to probe: {concerns}. Steps with timings, bullets of 8 questions ordered so the revealing ones come after rapport, a table (Concern | Question | Green-flag answer | Red-flag answer), and a callout on questions you must not ask in most jurisdictions.",
    "steps, bullets, table, callout", "Plan call", "Dialling…"),
  T("offer", "The offer call", "Say the number and hold the room", "🤝",
    [TXT("who", "Candidate", "Nadia", True), TXT("package", "Package", "base 165k, 0.1% equity, 4 weeks leave", True), CH("risk", "Your read", ["They'll accept", "They're torn", "They have a better offer", "Anchored on a number we can't hit"], "They're torn")],
    "Script the offer call to {who} for {package} where your read is '{risk}'. Steps for the call including when to say the number, a quote with the opening 30 seconds, a table (If they say | You say | Room to move) covering start date, base, equity and title, and a callout on what to confirm in writing within an hour of the call.",
    "steps, quote, table, callout", "Script call", "Saying the number…"),
  T("counter", "Counter-offer & holdouts", "When they stall or get countered", "⏳",
    [LONG("situation", "What happened", "she got a counter from her employer at 180k and asked for a week")],
    "Advise on this: {situation}. Text with an honest read of the odds and what the delay usually means, bullets of what you can offer that isn't base salary, a quote with the message to send today, and a callout on the point at which to walk away and who to line up as backup.",
    "text, bullets, quote, callout", "Advise me", "Reading the signals…"),
  T("decline", "Decline with dignity", "Rejections that keep doors open", "🕊️",
    [TXT("who", "Candidate", "Raj, final round", True), CH("stage", "Stage reached", ["Screen", "Interview", "Final round", "Offer withdrawn"], "Final round"), TXT("why", "Real reason (private)", "strong but less depth on distributed systems than Nadia")],
    "Write the rejection for {who} at stage '{stage}', real reason: {why}. Quote with an email under 120 words that is specific, warm and honest without creating legal risk, bullets on whether and how to give feedback if they ask, and a callout on keeping the door open if they might fit a future role.",
    "quote, bullets, callout", "Write it", "Being kind…")], HR)

# 6 — Team rituals: retros, standups, agreements, recognition
APP("retro_room", "Retro Room", "Team rituals people don't dread", "Business", ["#AD1457", "#00897B", "#FFA726"], "bulb",
 "Retro Room designs team rituals that people actually show up for: retrospectives matched to the team's mood, standups that stay short, working agreements everyone owns and recognition that feels real.",
 "You are a facilitator who has run hundreds of retros: format-flexible, allergic to blame, and ruthless about turning talk into two or three actions with owners.",
 "Rituals worth showing up for", "Tell us how your team works and we'll fit the formats.", ["Retro formats matched to the mood", "Sticky notes → themes and actions", "Standups and agreements that stick"],
 [NAME, NUM("size", "Team size", "7"), CH("mode", "Team mode", ["Co-located", "Hybrid", "Fully remote"], "Hybrid"), CH("cycle", "Cycle", ["Weekly", "Fortnightly sprints", "Monthly", "Project-based"], "Fortnightly sprints")],
 [T("design", "Design a retro", "A format for how the team feels", "🎨",
    [CH("mood", "Team mood right now", ["Tired", "Just shipped big", "After a failure", "Flat and routine", "New team", "Tense"], "Flat and routine"), NUM("minutes", "Minutes", "60"), TXT("focus", "Anything to focus on", "the release process")],
    "Design a {minutes}-minute retrospective for a team that is '{mood}', focus: {focus}, for the profile's size and mode. kv (format name and why it fits, tools needed, prime directive to read aloud), steps with timings for each activity including the check-in and the close, bullets of prompts for the main activity, and a callout on the facilitation trap most likely with this mood.",
    "kv, steps, bullets, callout", "Design retro", "Picking a format…"),
  T("themes", "Theme the sticky notes", "Raw notes → themes, actions, summary", "🗂️",
    [LONG("notes", "Paste all the notes", "deploys are scary; nobody reviews PRs on Fridays; loved the pairing week; too many meetings…")],
    "Cluster these retro notes: {notes}. Table (Theme | Notes in it | Sentiment | Suggested votes) with at most 6 themes, bullets of 3 discussion questions for the top theme, a checklist of 2–3 concrete actions each with an owner placeholder and a due date, and a quote with a one-paragraph summary to post in the team channel.",
    "table, bullets, checklist, quote", "Cluster", "Sorting stickies…"),
  T("charter", "Working agreements", "'We…' statements the team will own", "📜",
    [LONG("pains", "What keeps going wrong", "people join late; decisions get re-opened in DMs; unclear who reviews what"), CH("scope", "Scope", ["Meetings", "Communication", "Code & reviews", "Everything"], "Everything")],
    "Draft team working agreements for scope '{scope}' addressing: {pains}, suited to the profile's team mode. Checklist of 6–10 agreements phrased as observable 'We…' statements, a table (Agreement | Why | How we'll notice it slipping), steps for a 30-minute session where the team edits and owns them, and a quote with the intro line the manager says so it isn't a top-down rulebook.",
    "checklist, table, steps, quote", "Draft charter", "Drafting 'we'…"),
  T("standup", "Fix our standup", "Shorter, peer-to-peer, remote-friendly", "⏱️",
    [LONG("problem", "What's wrong with it", "runs 25 minutes; people report to me not each other; remote folks stay silent")],
    "Redesign the standup given: {problem} for the profile's team mode and size. kv (format, length, speaking order, who goes first, async alternative), steps for the first week of the new format, a callout on the manager's own behaviour to change, and bullets of signals to check after two weeks.",
    "kv, steps, callout, bullets", "Fix it", "Trimming minutes…"),
  T("celebrate", "Celebrate a win", "Recognition that names real contributions", "🎉",
    [TXT("win", "The win", "shipped the migration two weeks early", True), CH("style", "Team style", ["Low-key", "Loud", "Remote-friendly", "Budget-free"], "Remote-friendly")],
    "Plan recognition for '{win}' in a '{style}' style. Cards of 4 ideas (meta = cost · minutes to organise), a quote with what the manager says to the team naming specific contributions, and a callout on making sure quieter contributors get named too.",
    "cards, quote, callout", "Plan it", "Popping corks…")])

# 7 — First-time manager
APP("first_lead", "First Lead", "The pocket coach for brand-new managers", "Business", ["#0277BD", "#FF6F00", "#7B1FA2"], "hat",
 "First Lead is the pocket coach for first-time managers: a first-90-days plan, a 'how I work' README, delegation that isn't dumping, managing former peers and a rescue plan for the week you're drowning.",
 "You are a warm, no-nonsense mentor who has coached dozens of first-time managers: you normalise the awkwardness, hand out scripts, and keep them focused on the team's output rather than their own.",
 "New to managing? Start here", "A few facts about your situation shape every plan.", ["A first-90-days plan", "Delegate without dumping", "Scripts for the awkward bits"],
 [NAME, CH("path", "How you got here", ["Promoted from the team", "Hired in", "Interim / acting", "Founder"], "Promoted from the team"), NUM("reports", "Direct reports", "5"), TXT("team", "What the team does", "customer support for a SaaS product")],
 [T("ninety", "My first 90 days", "Listen, decide, deliver — in that order", "🗓️",
    [TXT("start", "Start date", "next Monday"), LONG("context", "What you're walking into", "two people wanted the job; backlog is huge; my manager wants faster response times")],
    "Build a first-90-days plan for a new manager starting {start} in this situation: {context}, given the profile's path and team. Table (Weeks | Listen | Decide | Deliver | Don't) for weeks 0–2, 3–6 and 7–12, a checklist of the 10 conversations to have in the first two weeks, bullets of early wins to look for, and a callout on the classic mistake for the profile's path.",
    "table, checklist, bullets, callout", "Build plan", "Mapping 90 days…"),
  T("readme", "My manager README", "Tell the team how you work", "📖",
    [LONG("prefs", "How you actually work", "I reply to chat slowly; I like written proposals; I get quiet when stressed; I hate surprises")],
    "Write a 'how I work' README from: {prefs}. Quote with the full document under 350 words in sections (what I expect, how to reach me, how I give feedback, my quirks, what I'm working on as a manager), bullets on what to leave out because it reads as a demand, and a callout on how to share it without it feeling self-important.",
    "quote, bullets, callout", "Write README", "Describing you…"),
  T("delegate", "What should I delegate?", "Keep, delegate, drop or automate", "📤",
    [LONG("tasks", "Your week's tasks", "weekly report; approving refunds; hiring screen calls; escalation rota; 1:1s; roadmap input")],
    "Sort these tasks: {tasks}. Table (Task | Keep / Delegate / Drop / Automate | To whom (role) | Why), keeping only what needs your authority or relationships; then steps for handing over the biggest delegation including check-in points, a quote with how to frame it to the person as growth not dumping, and a callout on the task you're keeping for the wrong reason.",
    "table, steps, quote, callout", "Sort tasks", "Letting go…"),
  T("peers", "Managing former peers", "When your friend is now your report", "🤝",
    [LONG("situation", "What's awkward", "my friend Tom is now my report and still jokes about my old mistakes in standup")],
    "Handle this: {situation}. Text naming what's really going on and what's normal, steps for a reset conversation with the person, a quote with the opening line, bullets of boundaries to set on friendship and information, and a callout on behaviours that would be a problem no matter the history.",
    "text, steps, quote, bullets, callout", "Help me", "Untangling…"),
  T("drowning", "I'm drowning", "Triage a week that's too much", "🆘",
    [LONG("week", "What this week looks like", "23 meetings, 3 escalations, my own tickets, review due Friday"), CH("feel", "Right now you feel", ["Behind", "Guilty", "Useless", "Angry", "Numb"], "Behind")],
    "Triage this week: {week}, feeling {feel}. Checklist of what to cancel, delegate or shorten today with the exact message to send for each, a kv (hours reclaimed, one thing to do first, one thing to tell your manager), bullets on the pattern that created this, and a callout normalising that this is the standard month-three wall.",
    "checklist, kv, bullets, callout", "Triage", "Bailing water…")])

# 8 — Career growth and promotions (manager side)
APP("growth_ladder", "Growth Ladder", "Grow your people on purpose, not by accident", "Business", ["#00838F", "#F4511E", "#8E24AA"], "star",
 "Growth Ladder is the manager's side of career growth: real career conversations, development plans built on stretch work, promotion cases that survive committee, an honest 'not yet', and retention risk spotted before the resignation.",
 "You are a manager coach and former promotion-committee member: honest about bars, specific about evidence, and convinced that growth happens through work rather than courses.",
 "Grow your people on purpose", "Your ladder and team shape every plan.", ["Career conversations that go somewhere", "Promotion cases that pass", "Honest 'not yet' scripts"],
 [NAME, TXT("ladder", "Your levels", "IC1–IC5, M1–M3"), TXT("team", "Team and domain", "10-person data team"), CH("cycle", "Promotion cycle", ["Twice a year", "Annual", "Rolling", "Informal"], "Twice a year")],
 [T("convo", "Career conversation", "Forty-five minutes about their future", "🧭",
    [TXT("who", "Who and level", "Diego, IC3, 2 years at level", True), LONG("know", "What you know about their ambitions", "mentioned management once; likes mentoring; frustrated by slow projects", False)],
    "Prep a career conversation with {who} given: {know}. Steps for a 45-minute conversation with timings, bullets of 8 questions moving from past energisers to future direction, a table (Possible path | What they'd need to show | First experiment next quarter) for 3 paths against the profile's ladder, and a callout on promises a manager can't make.",
    "steps, bullets, table, callout", "Prep it", "Thinking ahead…"),
  T("plan", "Development plan", "Stretch work, not a list of courses", "🌱",
    [TXT("who", "Who", "Diego", True), TXT("target", "Target level or role", "IC4 in 12 months", True), LONG("gaps", "Gaps vs the bar", "hasn't led a cross-team project; writing is unclear; technically strong")],
    "Build a development plan for {who} toward {target} closing: {gaps}. Table (Gap | Stretch assignment from real work | Support — mentor, budget | Evidence when done | Target date), bullets of 3 assignments on the profile's team that would serve this, steps for the quarterly check-in, and a callout on keeping a 70/20/10 balance so it isn't a list of courses.",
    "table, bullets, steps, callout", "Build plan", "Finding stretch…"),
  T("case", "Promotion case", "Evidence that survives committee", "🏆",
    [TXT("who", "Who", "Diego, IC3 → IC4", True), LONG("evidence", "Evidence", "led the warehouse migration, 3 teams, saved 40h/week; mentored 2 juniors; presented at all-hands"), LONG("bar", "Your company's bar for the next level (paste if you have it)", "", False)],
    "Write a promotion case for {who} against the bar: {bar} from this evidence: {evidence}. Text of the case under 400 words organised by the level's expectations with scope, impact and behaviour examples, a table (Expectation | Evidence | Strength — strong / adequate / thin), bullets of the questions a sceptical committee will ask with answers, and a callout on the thinnest area and whether to wait a cycle.",
    "text, table, bullets, callout", "Write case", "Building the case…"),
  T("notyet", "The 'not yet' conversation", "Decline a promotion honestly", "⏸️",
    [TXT("who", "Who", "Priya", True), LONG("why", "Why not this cycle", "scope is still single-team; two strong peers ahead; committee said not yet")],
    "Script telling {who} they are not being promoted this cycle because: {why}. Quote with the first two minutes word-for-word (decision first, then reasons, then path), a table (If they say | You say) for disappointment, comparison to peers, threat to leave and silence, a checklist of what they must be able to repeat back at the end, and a callout on not hiding behind the committee.",
    "quote, table, checklist, callout", "Script it", "Choosing words…"),
  T("retention", "Retention risk check", "Who might leave, and what would keep them", "🚪",
    [LONG("team", "Your team, one line each", "Diego – ambitious, underpaid; Mei – new baby; Sam – 4 years, bored; Lou – just promoted")],
    "Assess retention risk for: {team}. Table (Person | Risk — low / medium / high | Likely trigger | What would keep them | Next action this month), bullets on the two people to act on first, and a quote with a 'stay interview' opening question for the highest-risk person.",
    "table, bullets, quote", "Assess", "Scanning the team…")], HR)

# 9 — Conflict on the team
APP("team_truce", "Team Truce", "Untangle conflict between people on your team", "Business", ["#5D4037", "#26C6DA", "#FFCA28"], "scale",
 "Team Truce helps managers untangle conflict between people on their team: map what's really going on, talk to each side, run a mediation that ends in agreements, reset the team afterwards and know when it's an HR matter.",
 "You are a workplace mediator: multipartial rather than neutral, curious about the interests behind positions, and clear-eyed about when something is misconduct rather than conflict.",
 "Conflict without the drama", "Your team context helps calibrate what's normal.", ["Map the real conflict", "Scripts for each side", "Mediations that end in agreements"],
 [NAME, NUM("size", "Team size", "9"), CH("mode", "Team mode", ["Co-located", "Hybrid", "Remote"], "Hybrid"), CH("hr", "HR support", ["Yes", "Limited", "None"], "Limited")],
 [T("map", "Map the conflict", "Positions, interests, fears", "🗺️",
    [LONG("story", "What's happening", "Ana and Ben stopped talking after the launch; Ben says Ana took credit; Ana says Ben missed deadlines; the team is picking sides")],
    "Map this conflict: {story}. Table (Party | Position | Likely underlying interest | Fear | What they need to hear), text with your read of the type — task, process, relationship or values — and how far it has escalated, bullets of what the manager may have contributed, and a callout on whether anything described crosses into harassment, discrimination or bullying that must go to HR.",
    "table, text, bullets, callout", "Map it", "Hearing both sides…"),
  T("sides", "Talk to one side", "A one-on-one that doesn't take sides", "👤",
    [TXT("who", "Who you're talking to", "Ana", True), LONG("their", "What you know of their view", "feels Ben undermines her in front of the team")],
    "Prep a one-on-one with {who} about the conflict, given: {their}. Steps for a 30-minute conversation, a quote with an opening that doesn't take sides, bullets of 6 questions that move from venting to interests, a kv (what to promise, what not to promise, what to say if they ask what the other person said), and a callout on when to stop and escalate.",
    "steps, quote, bullets, kv, callout", "Prep it", "Staying even…"),
  T("mediate", "Run a mediation", "Ground rules to agreements", "🕊️",
    [TXT("parties", "Who", "Ana and Ben", True), LONG("issues", "The issues on the table", "credit for the launch; missed deadlines; tone in code reviews"), NUM("minutes", "Minutes", "60")],
    "Plan a {minutes}-minute mediation between {parties} on: {issues}. Steps with timings (ground rules, each side uninterrupted, reframing, options, agreements), a quote with the ground rules to read aloud, a table (Issue | Possible agreement | How we'll know it's kept), and a callout on what to do if one party refuses or it turns hostile.",
    "steps, quote, table, callout", "Plan session", "Setting the table…"),
  T("reset", "Reset the team", "Recover the room after a fight", "🔄",
    [LONG("aftermath", "Where the team is now", "people still whisper; two juniors are anxious; Ben is quieter")],
    "Plan a team reset after conflict given: {aftermath}, for the profile's team size and mode. Steps for the next 2 weeks (what the manager says in the team meeting, 1:1s to hold, norms to reinstate), a quote with a team-meeting statement under 120 words that acknowledges without airing details, a checklist of signals the team has recovered, and a callout on the mistake of pretending it didn't happen.",
    "steps, quote, checklist, callout", "Plan reset", "Clearing the air…"),
  T("escalate", "HR or handle it?", "Conflict, or conduct?", "🚨",
    [LONG("facts", "What happened, factually", "Ben called Ana 'hysterical' in a meeting; second time; Ana asked me to keep it quiet")],
    "Assess: {facts}. Text with a clear view on whether this is a conflict to mediate or a conduct matter for HR and why, bullets of what the manager must do in the next 24 hours regardless, a quote with what to say to the person who asked for it to be kept quiet, and a callout on record-keeping and the limits of confidentiality a manager can promise.",
    "text, bullets, quote, callout", "Assess", "Checking the line…")], HR)

# 10 — Delivering bad news: layoffs, reorgs, cancellations
APP("hard_news", "Hard News", "Deliver layoffs and reorgs like a human", "Business", ["#263238", "#EF6C00", "#42A5F5"], "shield",
 "Hard News gets managers through the announcements nobody wants to make — layoffs, reorgs, cancelled projects, pay freezes, leaders leaving — with honest scripts, question prep and a plan for the people who stay.",
 "You are a crisis-communications-minded leadership coach: clear over comforting, never corporate-speak, and insistent that the people who remain are watching how you treat the people who leave.",
 "Deliver hard news like a human", "Your role and constraints shape what you can say.", ["Scripts for layoff conversations", "Team announcements without spin", "Plans for the people who stay"],
 [NAME, CH("role", "Your role", ["Team lead", "Manager of managers", "Director+", "Founder"], "Team lead"), NUM("size", "People in your org", "12"), CH("region", "Region", ["US", "UK / EU", "Other"], "US")],
 [T("announce", "Announce a change", "Decision, why, what changes, what's next", "📣",
    [CH("kind", "Change", ["Layoffs", "Reorg", "Project cancelled", "Pay or hiring freeze", "Leader leaving", "Return to office"], "Reorg"), LONG("facts", "Facts you can share", "two teams merge under Dana; no job losses; new reporting lines Monday"), LONG("cant", "What you can't say yet", "budget cut of 15% next year; possible second round", False)],
    "Write the team announcement for '{kind}' with these shareable facts: {facts} and things not yet shareable: {cant}. Quote with a spoken announcement under 200 words (decision, why, what changes for them, what doesn't, what happens next, how to raise questions), bullets of 6 phrases to avoid because they sound like spin, a table (Likely question | Honest answer | If you can't answer) for 6 questions, and a callout on handling what you can't say without lying.",
    "quote, bullets, table, callout", "Write it", "Cutting the spin…"),
  T("layoff", "The layoff conversation", "Fifteen minutes with dignity", "🪑",
    [TXT("who", "Who", "Chris, 6 years, two kids", True), TXT("terms", "Terms you can share", "8 weeks severance, health cover to March, HR call after", True), CH("your", "You feel", ["Guilty", "Numb", "Angry at leadership", "Relieved it's not me", "Steady"], "Guilty")],
    "Script the individual notification for {who} with terms {terms}, where you feel {your}. Steps for the 15 minutes (decision in the first 30 seconds, no debate, logistics, dignity), a quote with the exact first four sentences, a table (If they say | You say) for anger, tears, bargaining, silence and 'why me', a checklist of what must happen in the hour after, and a callout on what you must not say or promise in the profile's region.",
    "steps, quote, table, checklist, callout", "Script it", "Steadying…"),
  T("survivors", "The team that stays", "The first two weeks after", "🌦️",
    [LONG("situation", "What happened", "3 of 12 laid off Tuesday; the rest are scared and angry; two asked about job security")],
    "Plan the first two weeks for the remaining team after: {situation}. Steps day by day for the first 3 days then weekly, a quote with a team-meeting opening that acknowledges the loss without selling it as an opportunity, bullets of what each remaining person needs to hear in 1:1s, a table (Fear | What you can say honestly | What you can do), and a callout on manager self-care so you can keep showing up.",
    "steps, quote, bullets, table, callout", "Plan it", "Holding the team…"),
  T("faq", "Prep the tough questions", "Including the hostile ones", "🎤",
    [CH("kind", "About", ["Layoffs", "Reorg", "Project cancelled", "Pay freeze", "Leader leaving", "Strategy shift"], "Layoffs"), LONG("context", "Context", "company missed targets; leadership got bonuses last year; rumours of a sale")],
    "Prepare for the hardest questions about '{kind}' given: {context}. Table (Question — including the hostile ones | Honest answer | Don't say) for 10 questions, bullets on how to say 'I don't know' and 'I can't share that' credibly, a quote with a response to the most personal accusation likely, and a callout on what to escalate to leadership before the meeting.",
    "table, bullets, quote, callout", "Prep me", "Bracing…"),
  T("transition", "Reorg transition plan", "Everything that breaks when lines move", "🔀",
    [LONG("change", "The reorg", "support team splits into tier 1 and tier 2; Sam moves to tier 2 lead; two people change managers"), TXT("date", "Effective date", "1 Nov")],
    "Build a transition plan for: {change}, effective {date}. Table (Week | Communication | Decisions needed | Owner) for the 4 weeks around the date, a checklist of everything that breaks in a reorg (access, on-call, 1:1s, goals, reviews in progress), bullets of the people most affected with a first conversation for each, and a callout on the ambiguity that will linger and how to name it.",
    "table, checklist, bullets, callout", "Build plan", "Redrawing lines…")], "Not legal advice. Redundancy, notice and consultation rules vary by jurisdiction; coordinate every termination or restructure with HR and legal counsel.")
