from dsl import *
SIGN = "Text descriptions are a study aid; learn signs from Deaf instructors or video in your chosen sign language, since regional variants and details differ."

APP("vamos_spanish", "Vamos Spanish", "Travel Spanish for the country you're actually visiting", "Education", ["#E64A19", "#FDD835", "#00897B"], "plane",
 "Vamos Spanish teaches the Spanish they actually speak where you're going — Mexico, Spain, Argentina or Colombia — with situation scripts, menu decoding and the replies you'll hear back.",
 "You are a well-travelled Spanish tutor who switches naturally between Mexican, Castilian, Rioplatense and Colombian Spanish, always gives the local word first, and marks stress with capitals in pronunciation.",
 "Where are you headed?", "Pick your destination and level; every phrase will be tuned to that country.", ["Scripts with the replies you'll hear", "Menus and signs decoded from a photo", "Local words, not textbook Spanish"],
 [NAME, CH("country", "Destination", ["Mexico", "Spain", "Argentina", "Colombia", "Peru", "Costa Rica"], "Mexico"), CH("level", "Level", ["Zero", "Tourist basics", "Can hold a chat"], "Tourist basics"), CH("trip", "Trip style", ["Backpacking", "Beach", "City & food", "Business", "Family"], "City & food")],
 [T("script", "Situation script", "The dialogue with likely replies", "🗣️",
    [CH("situation", "Situation", ["Taxi / rideshare", "Ordering food", "Hotel check-in", "Pharmacy", "Market haggling", "Asking directions", "Meeting locals"], "Ordering food"), TXT("detail", "Specifics", "vegetarian, want to sit outside")],
    "Write a realistic {situation} dialogue for the profile's destination with specifics: {detail}. Sections: steps (each = one exchange: what you say in local Spanish, pronunciation with stressed syllables in CAPITALS, English meaning, then the 2 most likely replies you'll hear), a table of the key words (Spanish | Local variant | English), and a callout on one cultural courtesy for this situation in that country.",
    "steps, table, callout", "Write script", "Rehearsing…"),
  T("menu", "Decode a menu or sign", "Photo → what it says and what to pick", "📷",
    [PHOTO("Photo of the menu, sign or ticket", "", True), TXT("want", "What you're looking for", "something not spicy, under 200 pesos")],
    "Read the Spanish in the photo and translate it for a traveller looking for: {want}. Sections: a table (Original | English | Notes — spicy, contains pork, local specialty), cards for the 3 best picks given the request (meta = price if visible · why), and a quote with the exact sentence to order or ask the question in local Spanish.",
    "table, cards, quote", "Decode", "Reading…"),
  T("heard", "What did they say?", "Type what you heard, get the reply", "👂",
    [LONG("heard", "What you heard (as best you can)", "no hay, se acabó, mañana sí")],
    "The traveller heard '{heard}' in the profile's destination. Sections: text giving the likely intended sentence and its meaning (including slang and dropped words), kv (Tone: friendly/neutral/impatient; Register: tú/usted/vos; Region clue), and a quote with 3 short replies they could say next, each with pronunciation.",
    "text, kv, quote", "Explain", "Listening…"),
  T("regional", "Say it like a local", "One phrase, four countries", "🌎",
    [TXT("phrase", "Phrase in English", "the bill please / that's too expensive", True)],
    "Translate '{phrase}' as locals actually say it: a table (Country | Phrase | Pronunciation | Notes) covering Mexico, Spain, Argentina and Colombia, bullets of words to avoid because they are rude or mean something else in one of those countries, and a callout naming the safe neutral version that works everywhere.",
    "table, bullets, callout", "Compare", "Travelling…"),
  T("daily", "Tomorrow's 10 words", "Vocabulary for the plan", "📅",
    [TXT("plan", "Tomorrow's plan", "bus to Oaxaca, market, cooking class")],
    "Pick the 10 most useful words and 3 phrases for tomorrow: {plan}, for the profile's destination and level. Sections: a table (Spanish | Pronunciation | English | Use it when), a checklist of 5 mini-missions to attempt during the day (e.g. 'ask the price of one thing'), and a quote with one sentence to say if you get stuck.",
    "table, checklist, quote", "Prep me", "Packing words…")])

APP("boardroom_english", "Boardroom English", "Sound fluent and professional in every meeting", "Education", ["#1A237E", "#C9A227", "#546E7A"], "bag",
 "Boardroom English helps non-native professionals rewrite blunt or translated sentences, master meeting language, decode idioms and hedging, and rehearse presentations.",
 "You are a business-English coach for international professionals: precise about register and tone, never condescending, always giving the natural phrase a native colleague would use.",
 "English that sounds like you belong", "Tell us your first language and industry so the fixes target your real habits.", ["Rewrite sentences in the right register", "Meeting and negotiation phrases", "Decode idioms and polite hedging"],
 [NAME, TXT("native", "First language", "Portuguese"), TXT("industry", "Industry & role", "fintech, product manager"), CH("variant", "English you work in", ["US", "UK", "International"], "International")],
 [T("rewrite", "Say it professionally", "Blunt or translated → natural", "✍️",
    [LONG("sentence", "What you want to say", "I don't agree with this plan, it will not work"), CH("to", "To whom", ["Boss", "Peer", "Client", "Report", "Whole team"], "Peer")],
    "Rewrite '{sentence}' for a {to} in the profile's English variant. Sections: cards with 3 versions (Direct, Diplomatic, Very formal; meta = when to use it), a table (Your phrasing | Why it may sound off | Natural alternative), and a callout on the single tone rule to remember for this relationship.",
    "cards, table, callout", "Rewrite", "Polishing…"),
  T("meeting", "Meeting phrasebook", "Interrupt, disagree, push back politely", "🗓️",
    [CH("type", "Meeting", ["Status update", "Brainstorm", "Negotiation", "Performance review", "Client pitch", "1:1 with boss"], "Status update"), TXT("goal", "Your goal", "get the deadline moved by two weeks")],
    "Prepare phrases for a {type} where my goal is: {goal}. Sections: a table (Moment | Phrase | Softer version) covering opening, interrupting, disagreeing, asking for clarification, pushing back and closing; a quote with a 3-sentence opening statement of my goal; and a checklist of things to do before the meeting (pre-read, numbers, an ally).",
    "table, quote, checklist", "Prepare me", "Prepping…"),
  T("decode", "What did they mean?", "Idioms, hedging, corporate-speak", "🔍",
    [LONG("said", "What they said or wrote", "Let's take this offline, I'm not sure we're aligned on the ask"), TXT("context", "Context", "Slack from my manager after a demo")],
    "Decode '{said}' (context: {context}). Sections: text with the plain-English meaning and how serious or urgent it really is, kv (Literal meaning, Real meaning, Emotion behind it, Action expected of you), and a quote with a good reply that matches their register.",
    "text, kv, quote", "Decode", "Translating…"),
  T("present", "Presentation rehearsal", "Script, signposts, likely questions", "🎤",
    [LONG("topic", "What you're presenting", "Q3 roadmap to leadership: 3 priorities, need headcount"), NUM("minutes", "Minutes", "10")],
    "Build a {minutes}-minute presentation script for: {topic}. Sections: steps (one per segment with timing, signpost phrase and key sentence), bullets of 6 words in this script that speakers of the profile's first language typically mispronounce or stress wrongly, with tips, and a table of 5 likely tough questions (Question | Buying-time phrase | Answer outline).",
    "steps, bullets, table", "Rehearse", "Setting the stage…"),
  T("smalltalk", "Small talk & networking", "Before the meeting starts", "☕",
    [CH("setting", "Setting", ["Before a call starts", "Conference", "Team lunch", "Client dinner", "Elevator"], "Before a call starts"), TXT("who", "Who with", "American VP I've met once")],
    "Coach small talk for {setting} with {who}. Sections: bullets of 6 safe openers and 4 follow-up questions for this setting, a table (Topic | Safe in US | Safe in UK | Avoid) for the profile's variant, a quote with a graceful exit line, and a callout on the one small-talk habit from the profile's first language that can land badly in English.",
    "bullets, table, quote, callout", "Coach me", "Warming up…")])

APP("kana_dojo", "Kana Dojo", "Hiragana and katakana in two weeks, mnemonics included", "Education", ["#C62828", "#212121", "#F48FB1"], "book",
 "Kana Dojo teaches hiragana and katakana row by row with mnemonics and stroke order, drills you with real words, and reads Japanese signs and packaging from your photos.",
 "You are a patient Japanese script sensei who teaches kana through vivid mnemonics, insists on stroke order, and never introduces kanji before the learner is ready.",
 "Read Japanese, one row at a time", "Tell us where you are so drills start at the right row.", ["Row-by-row lessons with mnemonics", "Real-word reading drills", "Read signs and labels from a photo"],
 [NAME, CH("known", "Already know", ["Nothing yet", "Some hiragana", "All hiragana", "Hiragana + some katakana"], "Nothing yet"), CH("why", "Learning for", ["Travel", "Anime & games", "JLPT N5", "Living in Japan", "Fun"], "Travel"), CH("pace", "Daily time", ["5 min", "15 min", "30 min"], "15 min")],
 [T("lesson", "Today's row", "Next 5 kana with mnemonics", "🎌",
    [CH("script", "Script", ["Hiragana", "Katakana"], "Hiragana"), TXT("row", "Row (optional)", "ka-row, or leave blank for the next one")],
    "Teach the next {script} row for the profile (or the {row} row if given). Sections: a table (Kana | Romaji | Mnemonic image | Looks like / confusable with), steps for the stroke order of each character described in words (stroke count, direction, where to start), and a checklist of 5 tiny tasks to lock it in today (trace, write from memory, find it in a word).",
    "table, steps, checklist", "Teach me", "Grinding ink…"),
  T("drill", "Reading drill", "Real words from kana you know", "🔥",
    [CH("length", "Words", ["10", "20", "30"], "20"), CH("mix", "Include", ["Only kana I know", "Add the newest row", "Everything"], "Add the newest row")],
    "Generate a reading drill of {length} real Japanese words using {mix} for the profile's level. Sections: a numbered table (# | Kana) for reading, then a text line labelled 'Answers' followed by a table (# | Romaji | Meaning), bullets of the 3 most commonly confused pairs appearing in this set (e.g. さ/き, シ/ツ), and a quote with one encouraging sensei sentence in Japanese with romaji.",
    "table, text, table, bullets, quote", "Drill me", "Shuffling cards…"),
  T("read", "Read this", "Photo of a sign, menu or label", "📷",
    [PHOTO("Photo with Japanese text", "", True)],
    "Transcribe the Japanese text in the photo. Sections: a table (Text as written | Reading in kana | Romaji | English), a callout that marks which parts are kanji (with furigana reading) versus kana the learner can already read at the profile's level, and bullets of 3 vocabulary words from the photo worth memorising.",
    "table, callout, bullets", "Read it", "Squinting…"),
  T("loanwords", "Katakana word guess", "Loanwords you already know", "🍔",
    [CH("theme", "Theme", ["Food", "Tech", "Fashion", "Travel", "Music", "Random"], "Food")],
    "Create a katakana loanword game on the theme {theme}: a table (Katakana | Say-it-out-loud hint | Answer (English origin) | Meaning in Japan if different), then bullets explaining 4 rules that transform English sounds into katakana (long vowels, small tsu, l→r, added vowels), and a checklist of 5 katakana words to spot in the wild this week.",
    "table, bullets, checklist", "Play", "Loading menu…"),
  T("plan", "Two-week plan", "Finish both scripts at your pace", "📅", [],
    "Build a 14-day kana plan for the profile's daily time and current knowledge. Sections: a table (Day | Rows to learn | Review | Drill type), bullets on spaced-review timing, and a callout on the moment to stop using romaji entirely.",
    "table, bullets, callout", "Plan it", "Sharpening brushes…")])

APP("harf_arabic", "Harf Arabic", "Read Arabic script letter by letter, form by form", "Education", ["#00695C", "#C8A951", "#EF6C00"], "moon",
 "Harf Arabic teaches the alphabet with all four letter forms, shows how letters join into words, decodes signs from photos and writes your name in Arabic.",
 "You are a calm Arabic reading tutor: you teach Modern Standard script first, always show initial, medial, final and isolated forms, and explain dialect differences only when asked.",
 "28 letters, 4 shapes each", "Tell us your goal so examples come from the right vocabulary.", ["Every letter in all four forms", "Joining practice with real words", "Signs, menus and names decoded"],
 [NAME, CH("goal", "Goal", ["Read the Quran", "Travel", "Living in the Gulf / MENA", "Heritage", "University Arabic"], "Travel"), CH("dialect", "Dialect interest", ["MSA only", "Egyptian", "Levantine", "Gulf", "Maghrebi"], "MSA only"), CH("known", "Already know", ["Nothing", "Some letters", "Can sound out slowly"], "Nothing")],
 [T("letters", "Next letters", "Four forms, sounds, joining rules", "🔤",
    [CH("count", "How many", ["2", "4", "6"], "4"), TXT("letters", "Specific letters (optional)", "ب ت ث")],
    "Teach the next {count} letters for the profile (or these: {letters}). Sections: a table (Letter | Name | Sound in English terms | Isolated | Initial | Medial | Final | Joins to the next letter?), steps for how to write each one (where the pen starts, dots above or below), a callout on the non-connecting letters (ا د ذ ر ز و) and how they break a word, and bullets of one example word per letter with transliteration.",
    "table, steps, callout, bullets", "Teach", "Dipping the qalam…"),
  T("join", "Build a word", "Watch letters connect", "🧩",
    [TXT("word", "Word (Arabic or transliterated)", "kitab / كتاب", True)],
    "Show how {word} is built. Sections: steps (one per letter: the letter, which form it takes here and why, and the partial word so far), kv (Root letters, Meaning, Transliteration, Short vowels that are usually hidden), and a callout on any letter whose shape changes surprisingly in this word.",
    "steps, kv, callout", "Build it", "Connecting…"),
  T("read", "Read a sign", "Photo → letters, sounds, meaning", "📷",
    [PHOTO("Photo of Arabic text", "", True)],
    "Read the Arabic in the photo. Sections: a table (Word as written | Letter-by-letter breakdown | Transliteration | English), bullets naming the letters in the photo the learner at the profile's level should recognise, and a callout on any calligraphic or dialect features (Persian/Urdu letters, decorative kufic) that make it harder than textbook script.",
    "table, bullets, callout", "Read it", "Tracing…"),
  T("vowels", "Harakat and sukun", "The marks that make words readable", "✨",
    [CH("focus", "Focus", ["Fatha, kasra, damma", "Sukun and shadda", "Tanwin", "Long vowels", "All of them"], "Fatha, kasra, damma")],
    "Teach {focus} for the profile's level. Sections: a table (Mark | Looks like | Sound | Example word with it | Same word without it), steps for reading a fully vowelled word, and a checklist of 6 words to read aloud in increasing difficulty, each fully vowelled with transliteration.",
    "table, steps, checklist", "Teach me", "Adding dots…"),
  T("name", "My name in Arabic", "Spelling, forms, and how it sounds", "🪪",
    [TXT("name", "Name to write", "Jessica", True)],
    "Write {name} in Arabic script. Sections: kv (Arabic spelling, Letter-by-letter with forms, Transliteration back, Closest Arabic pronunciation), bullets on the sounds in this name that Arabic lacks and how they are usually approximated (p→b, v→f, g variations), and a quote with the name in a full greeting sentence such as 'My name is …', with transliteration.",
    "kv, bullets, quote", "Write it", "Calligraphing…")])

APP("der_die_das", "Der Die Das", "German genders, cases and word order that finally click", "Education", ["#37474F", "#D32F2F", "#FFB300"], "bulb",
 "Der Die Das explains German noun genders with real rules, cracks cases in any sentence, fixes your word order and drills exactly what you keep getting wrong.",
 "You are a precise, encouraging German grammar tutor who teaches rules with their reliability in percent, always gives the exception, and never says 'just memorise it' without a mnemonic.",
 "Stop guessing der, die or das", "Tell us your level and what trips you up.", ["Gender rules that actually predict", "Case explanations for any sentence", "Drills built from your mistakes"],
 [NAME, CH("level", "Level", ["A1", "A2", "B1", "B2+"], "A2"), CH("pain", "Trips me up", ["Genders", "Cases", "Word order", "Adjective endings", "Separable verbs", "Prepositions"], multi=True), CH("goal", "Goal", ["Exam (Goethe / telc)", "Work in Germany", "University", "Family", "Fun"], "Work in Germany")],
 [T("gender", "Gender detective", "Why is it der, die or das?", "🕵️",
    [LONG("nouns", "Nouns (one per line)", "Mädchen\nTisch\nFreiheit\nAuto")],
    "For each noun in {nouns}: a table (Noun | Gender | Plural | Rule that predicts it | Reliability %). Then bullets explaining the 5 most useful gender rules touched by this list (suffix rules like -ung/-heit/-chen, semantic groups), and a callout on the nouns here that break every rule and need a mnemonic, with one for each.",
    "table, bullets, callout", "Investigate", "Consulting Duden…"),
  T("cases", "Case cracker", "Every case in your sentence, explained", "🔎",
    [LONG("sentence", "German sentence", "Ich habe dem Mann mit dem Hund ein Buch gegeben.")],
    "Analyse '{sentence}'. Sections: a table (Word / phrase | Case | Why — verb, preposition or role | Correct?), text explaining the sentence structure in plain English, and a callout on the one rule from this sentence the profile's level most needs, with two fresh example sentences.",
    "table, text, callout", "Crack it", "Declining…"),
  T("fix", "Fix my German", "Paste → corrected + explained", "✏️",
    [LONG("text", "Your German", "Ich habe gestern gegangen zum Supermarkt weil ich brauche Milch."), CH("register", "Register", ["Text message", "Email", "Essay", "Speaking"], "Email")],
    "Correct this {register}: {text}. Sections: a quote with the corrected text, a table (Original | Corrected | Rule broken | Priority for the profile's level), steps for the word-order rules involved (verb second, verb-final after weil/dass, past participle placement), and bullets of 3 higher-level phrasings the learner could use next time.",
    "quote, table, steps, bullets", "Fix it", "Correcting…"),
  T("verbs", "Verb workshop", "Conjugate, separate, perfect", "⚙️",
    [TXT("verb", "Verb", "anrufen", True), CH("tense", "Tenses", ["Präsens", "Perfekt", "Präteritum", "Futur", "Konjunktiv II"], "Präsens", multi=True)],
    "Conjugate {verb} in {tense}. Sections: a table (Person | one column per requested tense), kv (Separable or inseparable, Auxiliary haben or sein, Case it governs, Preposition it takes), steps showing where the prefix or participle goes in a main clause, a subordinate clause and a question, and a quote with 3 example sentences of increasing length.",
    "table, kv, steps, quote", "Conjugate", "Splitting prefixes…"),
  T("drill", "Drill my weak spot", "10 questions, answers hidden below", "🎯",
    [CH("topic", "Topic", ["Genders", "Akkusativ vs Dativ", "Adjective endings", "Word order", "Two-way prepositions", "Konjunktiv II"], "Akkusativ vs Dativ"), CH("n", "Questions", ["10", "20"], "10")],
    "Write {n} fill-in-the-gap questions on {topic} at the profile's level, as a numbered checklist. Then a text line labelled 'Answers', followed by a table (# | Answer | One-line why). End with a callout naming the pattern behind the two hardest questions.",
    "checklist, text, table, callout", "Drill me", "Sharpening pencils…")])

APP("liaison_french", "Liaison French", "French pronunciation, sound by sound, liaison by liaison", "Education", ["#1E3A8A", "#E8607A", "#B08D57"], "mic",
 "Liaison French breaks any sentence into sounds, marks liaisons and silent letters, drills the vowel pairs English speakers mix up, and builds a plan for your specific accent problems.",
 "You are a French phonetics coach: you use IPA and plain-English mouth instructions side by side, model Parisian standard by default, and celebrate small wins.",
 "Be understood the first time", "Tell us your first language so we target the sounds that matter.", ["Sentence-by-sentence sound maps", "Minimal-pair drills for the hard vowels", "Liaison and silent-letter rules"],
 [NAME, TXT("native", "First language", "English (American)"), CH("level", "Level", ["Beginner", "Intermediate", "Advanced but accent-heavy"], "Intermediate"), CH("accent", "Target accent", ["Parisian standard", "Québécois", "Southern France"], "Parisian standard")],
 [T("map", "Sound map", "How to say this exact sentence", "🗺️",
    [LONG("sentence", "French sentence", "Les enfants ont un petit chien.")],
    "Map the pronunciation of '{sentence}' in the profile's target accent. Sections: a quote with the sentence rewritten showing liaisons with ‿ and silent letters in (brackets), a table (Word | IPA | Mouth instruction | Trap for the profile's first language), steps for practising it syllable by syllable, then in rhythm groups, then at speed, and a callout on the single most important sound in this sentence to nail.",
    "quote, table, steps, callout", "Map it", "Tuning vowels…"),
  T("pairs", "Minimal pairs", "u vs ou, é vs è, nasals", "👂",
    [CH("pair", "Contrast", ["u / ou", "é / è / e", "an / on / in", "r", "eu / œu", "Final consonants"], "u / ou")],
    "Drill the contrast {pair} for the profile. Sections: text explaining the mouth-position difference in plain English (lips, tongue, jaw), a table of 10 minimal pairs (Word A | Word B | IPA A | IPA B | Meaning A | Meaning B), steps for a 5-minute mirror practice, and a quote with one sentence containing both sounds several times.",
    "text, table, steps, quote", "Drill", "Rounding lips…"),
  T("liaison", "Liaison checker", "Which links are required, optional, forbidden", "🔗",
    [LONG("text", "French text", "Ils ont acheté des oranges et un ananas.")],
    "Mark every potential liaison and elision in: {text}. Sections: a table (Between | Sound produced | Required, optional or forbidden | Rule), a quote with the text rewritten marking required liaisons with ‿ and forbidden ones with ‖, and bullets of the 3 liaison rules illustrated here that matter most at the profile's level.",
    "table, quote, bullets", "Check", "Linking…"),
  T("accent", "Fix my accent", "Describe the problem, get a plan", "🎯",
    [LONG("problem", "What goes wrong", "people don't understand when I say 'rue'; my r sounds English")],
    "Diagnose: {problem}, for a speaker of the profile's first language. Sections: text naming the likely phonetic cause, steps for a 2-week fix (daily 5-minute exercises, each with what to listen for), a table (Day | Exercise | Success check), and a callout on how to self-record and compare against a native model.",
    "text, steps, table, callout", "Diagnose", "Listening closely…"),
  T("twister", "Virelangues", "Tongue twisters for one sound", "🌀",
    [CH("sound", "Target sound", ["r", "u", "Nasal vowels", "s / z", "ch / j", "Liaison"], "r"), CH("difficulty", "Difficulty", ["Easy", "Medium", "Brutal"], "Medium")],
    "Give 5 {difficulty} French tongue twisters targeting {sound}: cards (twister with IPA, meta = speed goal · meaning in English), steps for building speed without losing the sound, and a quote with the classic one every French child knows for this sound.",
    "cards, steps, quote", "Twist me", "Untangling…")])

APP("kdrama_korean", "Drama Hangul", "Learn Korean from the K-dramas you already binge", "Education", ["#AD1457", "#7E57C2", "#26C6DA"], "heart",
 "Drama Hangul turns your favourite K-dramas into Korean lessons: scene breakdowns, speech-level explanations, genre phrase packs and Hangul reading from subtitles and screenshots.",
 "You are a Korean tutor who watches everything: you explain speech levels and honorifics through drama scenes, always give Hangul, romanisation and natural English, and flag drama-only expressions you shouldn't use at work.",
 "What are you watching?", "Tell us your dramas and level so every example comes from shows you love.", ["Scene breakdowns with speech levels", "Phrase packs by genre and trope", "Hangul reading from screenshots"],
 [NAME, TXT("shows", "Dramas you love", "Crash Landing on You, Reply 1988"), CH("level", "Level", ["Can't read Hangul yet", "Can read, few words", "Beginner conversations", "Intermediate"], "Can read, few words"), CH("goal", "Goal", ["Watch without subtitles", "Trip to Korea", "Talk to K-pop / K-drama fans", "Exam (TOPIK)"], "Watch without subtitles")],
 [T("scene", "Break down a scene", "Paste the subtitle lines", "🎬",
    [LONG("lines", "Subtitle lines (Korean or English)", "너 진짜 왜 그래? / 됐어, 신경 쓰지 마."), TXT("who", "Who's talking", "boss to intern / two friends")],
    "Break down these lines: {lines}, spoken by {who}. Sections: a table (Korean | Romanisation | Literal | Natural English | Speech level), bullets explaining the honorific and speech-level choices and what they reveal about the relationship, kv (Key grammar point, Key vocabulary, Emotion cue), and a callout on any line that is drama-dramatic and would sound odd in real life.",
    "table, bullets, kv, callout", "Break it down", "Rewinding…"),
  T("levels", "Banmal or jondaetmal?", "Same sentence, every speech level", "🙇",
    [TXT("phrase", "Phrase in English", "Have you eaten?", True), CH("to", "Saying it to", ["Close friend", "Older coworker", "Boss", "Grandmother", "Customer", "Stranger"], "Older coworker")],
    "Render '{phrase}' for a {to}: a table (Level | Korean | Romanisation | When it fits | Drama example type) covering casual banmal, polite -yo, formal -mnida and honorific forms. Then text explaining which one to actually use for a {to} and why, and a callout on the mistake learners make by copying drama leads.",
    "table, text, callout", "Show levels", "Bowing…"),
  T("pack", "Phrase pack", "Vocab for a genre or trope", "💌",
    [CH("genre", "Genre / trope", ["Office romance", "Chaebol family", "Historical (sageuk)", "Crime thriller", "High school", "Food & drinking scenes", "Confession scene"], "Office romance")],
    "Build a phrase pack for {genre} scenes: cards for 8 expressions (Korean + romanisation, meta = level · you'll hear it when), a table of 10 key vocabulary words (Korean | Romanisation | Meaning | Real-life usable?), and a quote with one iconic line type from this genre and a note on which drama made it famous.",
    "cards, table, quote", "Build pack", "Pouring soju…"),
  T("read", "Read this screenshot", "Hangul from captions, signs, texts", "📷",
    [PHOTO("Screenshot or photo with Korean text", "", True)],
    "Transcribe the Korean text in the image. Sections: a table (Korean | Syllable-by-syllable reading | Romanisation | English), steps showing how to sound out the two hardest words letter by letter for the profile's level, and bullets of expressions in the image that are slang, texting abbreviations or drama-specific.",
    "table, steps, bullets", "Read it", "Pausing frame…"),
  T("binge", "Binge study plan", "Learn while you watch this week", "📺",
    [TXT("watching", "Currently watching", "Queen of Tears, episode 6"), CH("episodes", "Episodes this week", ["2", "4", "6+"], "4")],
    "Plan a week of learning around {watching} at {episodes} episodes for the profile's level and goal. Sections: a table (Episode | Listening task | Vocab target | Speaking task), a checklist of subtitle settings and pause habits that make watching count as study, and a callout on one grammar pattern to hunt for across all episodes this week.",
    "table, checklist, callout", "Plan my week", "Buffering…")])

APP("sign_start", "Sign Start", "Your first signs, explained in plain steps", "Education", ["#00838F", "#F57C00", "#3949AB"], "sun",
 "Sign Start explains basic signs in ASL, BSL or Auslan with step-by-step handshape descriptions, turns English into sign-order gloss, drills fingerspelling and teaches Deaf-community etiquette.",
 "You are a hearing-ally sign-language tutor trained by Deaf instructors: you describe signs precisely (handshape, palm orientation, location, movement, facial expression), stay within the chosen sign language, and always point learners to Deaf-led video resources.",
 "Which sign language?", "ASL, BSL and Auslan are different languages; pick yours so the signs are right.", ["Signs described step by step", "English → sign-order gloss", "Fingerspelling and etiquette"],
 [NAME, CH("lang", "Sign language", ["ASL (US / Canada)", "BSL (UK)", "Auslan (Australia)", "ISL (Ireland)"], "ASL (US / Canada)"), CH("why", "Learning because", ["Deaf family member", "Deaf colleague or friend", "Work (health, teaching, service)", "Baby signing", "Curious"], "Curious"), CH("hand", "Dominant hand", ["Right", "Left"], "Right")],
 [T("sign", "How do I sign…", "Handshape, location, movement", "🤟",
    [LONG("words", "Words or phrases (one per line)", "thank you\nhelp\nwhere is the bathroom")],
    "For each item in {words}, in the profile's sign language and dominant hand: steps describing the sign (handshape, palm orientation, location, movement, facial expression), then a table (Sign | Similar-looking sign | How to tell them apart), and a callout on any item that has regional variants or is signed differently from its English word order.",
    "steps, table, callout", "Show me", "Warming up hands…"),
  T("gloss", "English to sign order", "Grammar, gloss and expressions", "📝",
    [LONG("sentence", "English sentence", "Are you going to the store tomorrow?")],
    "Convert '{sentence}' into the profile's sign language. Sections: a quote with the gloss in capitals (e.g. TOMORROW STORE YOU GO?), a table (Gloss word | Sign notes | Non-manual marker — eyebrows, head, mouth), text explaining the grammar difference from English (time first, topic-comment, question face), and bullets with 2 variations for casual vs polite contexts.",
    "quote, table, text, bullets", "Convert", "Reordering…"),
  T("spell", "Fingerspelling drill", "Read and produce faster", "🔤",
    [CH("focus", "Focus", ["My name & family names", "Letters I confuse", "Speed reading", "Numbers"], "Letters I confuse"), TXT("names", "Names to practise", "Priya, Marcus")],
    "Fingerspelling drill for {focus} with {names} in the profile's sign language (two-handed for BSL and Auslan, one-handed for ASL and ISL). Sections: a table (Letter | Handshape description | Commonly confused with | Fix), a checklist of 10 practice words in increasing length, steps for a 3-minute daily speed routine, and a callout on the etiquette of fingerspelling names when you meet a Deaf person.",
    "table, checklist, steps, callout", "Drill me", "Shaping letters…"),
  T("situation", "Signs for a situation", "The 15 you need for one setting", "🏥",
    [CH("setting", "Setting", ["Doctor / hospital", "Classroom", "Café or restaurant", "Workplace", "With a baby / toddler", "Emergency"], "Café or restaurant")],
    "The 15 most useful signs for {setting} in the profile's sign language: cards (sign name, meta = one-line description · category), a quote with a 4-line sample exchange in gloss for this setting, and a checklist of 5 things to do so the conversation works (get attention appropriately, keep eye contact, write it down if stuck).",
    "cards, quote, checklist", "Build set", "Setting the scene…"),
  T("etiquette", "Deaf culture & etiquette", "Do this, never that", "🤝",
    [TXT("context", "Your situation", "new Deaf colleague on my team, interpreter in meetings")],
    "Etiquette guidance for: {context}. Sections: a table (Do | Instead of | Why), bullets on working with interpreters (who to look at, pacing, not saying 'tell her'), a callout on terms to use and avoid (deaf, Deaf, hard of hearing, 'hearing impaired'), and a quote with one respectful sentence to open with.",
    "table, bullets, callout, quote", "Guide me", "Learning norms…")], SIGN)

APP("tone_tamer", "Tone Tamer", "Mandarin tones and pinyin you can actually hear and say", "Education", ["#B71C1C", "#F9A825", "#2E7D32"], "music",
 "Tone Tamer teaches Mandarin's four tones and tricky pinyin sounds with paired drills, explains tone sandhi in any sentence, and reads menus and signs from photos with full pinyin.",
 "You are a Mandarin pronunciation coach who thinks in tone pairs: you always give pinyin with tone marks, describe pitch in plain English, and catch the sounds English speakers merge.",
 "Hear the tones, then say them", "Tell us your level and whether you read characters yet.", ["Tone-pair drills that build muscle memory", "Sandhi explained in real sentences", "Menus and signs with full pinyin"],
 [NAME, CH("level", "Level", ["Absolute beginner", "HSK 1–2", "HSK 3–4", "Conversational"], "HSK 1–2"), CH("chars", "Characters", ["Pinyin only", "Simplified", "Traditional"], "Simplified"), CH("goal", "Goal", ["Travel to China / Taiwan", "Family", "Business", "HSK exam", "Fun"], "Travel to China / Taiwan")],
 [T("pairs", "Tone-pair drill", "Two-syllable words, one pair at a time", "🎵",
    [CH("pair", "Tone pair", ["1-1", "1-4", "2-3", "3-2", "3-3 (sandhi)", "4-4", "4-2", "Neutral tone", "All 20 pairs"], "2-3"), CH("n", "Words", ["10", "20"], "10")],
    "Drill the tone pair {pair} with {n} common words at the profile's level. Sections: text describing each tone's pitch contour in plain English (start, movement, end), a table (Characters | Pinyin | Meaning | Pitch picture e.g. 35+214), steps for a 5-minute practice (clap the contour, hum it, say it, record it), and a callout on the specific way English speakers get this pair wrong.",
    "text, table, steps, callout", "Drill me", "Tuning up…"),
  T("sandhi", "Tone changes in this sentence", "Third-tone, 一 and 不 rules", "🔄",
    [LONG("sentence", "Chinese sentence (characters or pinyin)", "我想买一本书，不贵。")],
    "Analyse the tone changes in '{sentence}'. Sections: a quote with the full pinyin as it is actually pronounced (tone marks after sandhi), a table (Syllable | Dictionary tone | Spoken tone | Rule applied), bullets of the sandhi rules that fired (third-tone, yī, bù, neutral tone), and a callout on the stress and rhythm of the sentence.",
    "quote, table, bullets, callout", "Analyse", "Listening…"),
  T("pinyin", "Pinyin traps", "zh/ch/sh vs j/q/x, ü, -n vs -ng", "🪤",
    [CH("trap", "Trap", ["zh / ch / sh vs j / q / x", "ü vs u", "-n vs -ng", "c / z / s", "r", "e / o", "All"], "zh / ch / sh vs j / q / x")],
    "Teach the pinyin trap {trap} for a speaker at the profile's level. Sections: text on tongue position with a plain-English comparison to English sounds, a table of 8 minimal pairs (Pinyin A | Pinyin B | Characters | Meanings), steps for a mirror drill, and a quote with one sentence packed with these sounds, with pinyin.",
    "text, table, steps, quote", "Teach", "Curling tongue…"),
  T("read", "Read a menu or sign", "Photo → characters, pinyin, meaning", "📷",
    [PHOTO("Photo with Chinese text", "", True)],
    "Read the Chinese text in the photo. Sections: a table (Characters | Pinyin with tones | English | Notes — spicy, price, traditional vs simplified), a quote with the exact sentence to order or ask about the most useful item, with pinyin, and bullets of 3 characters in the image worth learning for the profile's goal.",
    "table, quote, bullets", "Read it", "Focusing…"),
  T("say", "Say this sentence", "Full pinyin, rhythm, tone marks", "🗣️",
    [TXT("english", "What you want to say", "Where is the nearest metro station?", True), CH("style", "Style", ["Casual", "Polite", "Very polite"], "Polite")],
    "Translate '{english}' into {style} Mandarin for the profile. Sections: kv (Characters, Pinyin with tone marks, Pinyin after sandhi, Literal gloss), steps for saying it: syllable groups, which syllables carry stress, where a neutral tone shortens, and bullets with 2 likely replies you'll hear and their meaning.",
    "kv, steps, bullets", "Translate", "Composing…")])

APP("heritage_tongue", "Heritage Tongue", "Reconnect with the language your family speaks", "Education", ["#6D4C41", "#FF7043", "#43A047"], "globe",
 "Heritage Tongue helps heritage speakers who understand but can't quite speak: family phrases, decoding relatives' voice notes and texts, festival greetings, and a gentle plan to talk with grandparents.",
 "You are a warm tutor for heritage speakers: you never shame the accent or the gaps, prioritise the dialect the family actually speaks over the textbook standard, and give romanisation alongside native script.",
 "Which language is at home?", "Tell us the language, the dialect if you know it, and who you want to talk to.", ["Phrases for real family moments", "Decode relatives' texts and voice notes", "A no-shame speaking plan"],
 [NAME, TXT("lang", "Family language & dialect", "Punjabi (Doabi) / Cantonese / Tagalog", True), CH("level", "Where you are", ["Understand a lot, speak little", "Speak a childish version", "Only a few words", "Speak but can't read"], "Understand a lot, speak little"), TXT("who", "Who you want to talk with", "grandmother, aunts at weddings")],
 [T("moment", "Phrases for a family moment", "Say the right thing at the table", "🍲",
    [CH("moment", "Moment", ["Phone call with grandparents", "Family dinner", "Wedding or big gathering", "Comforting a relative", "Asking about family history", "Cooking together", "Religious or festival day"], "Phone call with grandparents"), TXT("detail", "Details", "grandma just got out of hospital")],
    "Phrases for {moment} in the profile's family language and dialect, details: {detail}. Sections: a table (Phrase in native script | Romanisation | Meaning | Respect level), a quote with a short 6-line model conversation that keeps going after the greeting, bullets of the follow-up questions relatives love to be asked, and a callout on one respectful custom for this moment.",
    "table, quote, bullets, callout", "Prepare me", "Setting the table…"),
  T("decode", "Decode a message", "Voice note, text, romanised chat", "💬",
    [LONG("message", "The message (type it or paste romanised text)", "beta tu kab aa raha hai, khana bana ke rakhungi")],
    "Decode this message in the profile's family language: {message}. Sections: text with the meaning, the tone and any affectionate or scolding nuance, kv (Words you probably know, New words, Dialect markers, Implied expectation), and a quote with 3 reply options in native script and romanisation: warm and short, longer and chatty, and one that asks a question back.",
    "text, kv, quote", "Decode", "Reading closely…"),
  T("fix", "Fix my sentence", "Say it the grown-up way", "✏️",
    [LONG("attempt", "What you said or want to say", "mujhe pata nahi kaise bolna")],
    "The learner tried: {attempt}. Sections: a quote with the natural adult version in native script and romanisation in the family dialect, a table (What you said | Natural version | Why it changed), bullets of 3 similar sentences to practise, and a callout reassuring which parts were already perfectly fine.",
    "quote, table, bullets, callout", "Fix it", "Gently correcting…"),
  T("festival", "Festival greetings", "The right words for the day", "🎉",
    [TXT("occasion", "Occasion", "Diwali / Lunar New Year / Eid / Nowruz", True), CH("format", "Format", ["Spoken", "Text message", "Card"], "Text message")],
    "Greetings for {occasion} as a {format} in the profile's family language. Sections: cards with 4 greetings from simple to heartfelt (native script + romanisation, meta = for whom · formality), a kv of the customs and expected replies (What elders say, What you reply, What to bring or do), and a quote with a full 3-sentence message for the relative named in the profile.",
    "cards, kv, quote", "Write greetings", "Lighting lamps…"),
  T("plan", "30-day speaking plan", "From understanding to talking", "🌱", [],
    "A 30-day plan for the profile to move from their current level to holding a 5-minute conversation with the people named. Sections: a table (Week | Daily 10-minute practice | Weekly real conversation task | Success sign), a checklist of 8 tiny wins to tick off (first joke, first phone call without switching to English), steps for handling the moment relatives laugh at your accent, and a quote with an encouraging sentence in the family language.",
    "table, checklist, steps, quote", "Start", "Planting seeds…")])
