from dsl import *
# w23 — Business: job search by field (nurses, travel nurses, teachers, academics, engineers, trades, retail, hospitality, government, first responders)

APP("unit_fit", "Unit Fit", "Land the nursing job on the unit you actually want", "Business", ["#00897B", "#EF5350", "#5C6BC0"], "heart",
 "Unit Fit helps RNs, LPNs and new grads find the right unit, tailor real clinical experience to postings, rehearse scenario interviews, check licence and cert requirements, and compare offers line by line.",
 "You are a nurse recruiter turned career mentor: clinically literate, straight-talking about ratios and differentials, and never willing to let anyone overstate their scope of practice.",
 "Find your unit", "Tell us your licence, experience and the shifts you can work.", ["Unit and specialty matching", "Clinical scenario interviews", "Offer comparisons with differentials"],
 [NAME, CH("licence", "Licence", ["RN", "LPN/LVN", "New grad RN", "NP/APRN", "Student"]), TXT("experience", "Experience", "2 yrs med-surg, ACLS, Epic"), CH("shifts", "Shifts you can work", ["Days", "Nights", "Weekends", "12s", "8s", "Per diem"], multi=True)],
 [T("match", "Match me to a unit", "Specialties that fit your temperament", "🩺",
    [CH("pace", "Pace you like", ["Calm & steady", "Busy but predictable", "Adrenaline"], "Busy but predictable"), CH("patients", "Patient contact", ["Long relationships", "Quick turnover", "Critical/technical", "Community"], "Quick turnover"), TXT("avoid", "Anything to avoid", "paeds, night rotations")],
    "Recommend nursing units for the profile given pace '{pace}', patient contact '{patients}' and avoiding: {avoid}. Give 5 units as cards (meta = typical ratio · shift pattern · entry difficulty) with why each fits, a table (Unit | Certs that help | Typical differentials | How to get a foot in), and bullets of questions to ask on a unit shadow day.",
    "cards, table, bullets", "Match me", "Rounding…"),
  T("bullets", "Clinical bullets", "Turn shift duties into posting-matched bullets", "📝",
    [LONG("posting", "Paste the job posting", "Seeking RN for 32-bed telemetry unit…"), LONG("duties", "What you actually do on shift", "titrate drips, 5:1 ratio, precept new grads…")],
    "Compare the posting {posting} with the nurse's real duties {duties}. Produce bullets of 6 résumé-ready achievement lines that use the posting's language, ratios, acuity, equipment and EHR names honestly; a table (Posting requirement | Your evidence | Gap?) covering every listed requirement; and a callout on anything in the posting the nurse should NOT claim without documented competency.",
    "bullets, table, callout", "Write bullets", "Charting…"),
  T("scenario", "Scenario interview", "Clinical and behavioural questions with SBAR answers", "🗣️",
    [CH("unit", "Unit interviewing for", ["Med-surg", "ICU", "ED", "L&D", "Paeds", "OR", "Oncology", "Psych", "Home health", "Clinic"], "Med-surg"), CH("focus", "Drill", ["Clinical scenarios", "Behavioural", "Mixed"], "Mixed")],
    "Build a mock interview for a {unit} position, focus {focus}, calibrated to the profile's experience. Give 6 questions as cards (meta = type · what the panel is scoring), each with a model answer structured as SBAR or STAR; a quote with a 45-second 'tell me about yourself' for this unit; and a checklist of questions the nurse should ask about ratios, orientation length and float policy.",
    "cards, quote, checklist", "Start mock", "Paging the panel…"),
  T("licence", "Licence & certs check", "What you need before day one", "📋",
    [TXT("state", "State / country of the job", "Texas", True), CH("target", "Target unit", ["Med-surg", "ICU", "ED", "L&D", "Paeds", "OR", "Oncology", "Psych", "Travel"], "Med-surg")],
    "Work out what the profile needs, starting from their current licence, to take a {target} job in {state}. Give kv (licence pathway: compact, endorsement or new application; typical processing time; fees; fingerprinting and background check). Add a table (Certification | Required or preferred | Provider | Renewal) covering BLS, ACLS, PALS, NIHSS, TNCC, CCRN or the unit's equivalents, then steps in order with realistic weeks for each, and a callout to verify with the official board site.",
    "kv, table, steps, callout", "Check", "Verifying…"),
  T("offers", "Compare offers", "Differentials, bonuses and the fine print", "⚖️",
    [LONG("offer_a", "Offer A", "$38/hr, $4 nights, $10k sign-on with 2-yr clawback, 5:1"), LONG("offer_b", "Offer B", "$41/hr, no differential, self-scheduling, 6:1")],
    "Compare {offer_a} and {offer_b} for the profile's shifts. Table (Factor | Offer A | Offer B | Edge) covering base, differentials, realistic annual gross for the shift mix, sign-on terms, ratio, scheduling, PTO and tuition support; kv with an estimated annual difference and the assumptions used; bullets of questions to settle before signing; and a callout on sign-on clawbacks and probation.",
    "table, kv, bullets, callout", "Compare", "Crunching…")],
 "Pay and licensing details are general guidance, not financial or legal advice; confirm with the employer and your nursing board.")

APP("next_assignment", "Next Assignment", "Travel nurse contracts decoded, compared and negotiated", "Business", ["#1E88E5", "#FFB300", "#43A047"], "plane",
 "Next Assignment breaks down travel nursing pay packages into real hourly numbers, spots contract red flags, compares assignments side by side, preps you for each new state and scripts the recruiter conversations.",
 "You are a seasoned travel-nurse mentor with agency-side experience: numbers-first, sceptical of blended rates, and clear about tax-home rules without pretending to be an accountant.",
 "Take the right contract", "Your specialty and home base shape every number.", ["Pay packages broken into real hourly", "Contract red-flag review", "Recruiter negotiation scripts"],
 [NAME, TXT("specialty", "Specialty & years", "ICU, 4 years"), TXT("home", "Tax home (city, state)", "Denver, CO"), CH("licences", "Licences held", ["Compact (NLC)", "Single state", "Several states"])],
 [T("package", "Decode a pay package", "What that weekly number really is", "💵",
    [PHOTO("Screenshot of the pay package (optional)"), LONG("package", "Or paste it", "$2,450/wk gross, 36 hrs, $22 taxable, $1,100 housing, $400 M&IE…", req=False), TXT("location", "Assignment city & state", "Phoenix, AZ")],
    "Break down the pay package from the screenshot and/or the text {package} for an assignment in {location}, given the profile's tax home. Produce kv (taxable hourly, stipends per week, blended hourly, estimated weekly take-home, guaranteed hours, missed-shift penalty), a table (Line item | Weekly | 13-week total | Taxable?), bullets of what to ask the recruiter (OT rate, call-offs, extension bonus), and a callout on stipend limits and duplicating expenses at the tax home.",
    "kv, table, bullets, callout", "Decode", "Doing the maths…"),
  T("compare", "Compare assignments", "Two contracts side by side", "🔀",
    [LONG("contract_a", "Assignment A", "Seattle ICU, $2,600/wk, 48 hrs, nights, 13 wks"), LONG("contract_b", "Assignment B", "Tucson ICU, $2,100/wk, 36 hrs, days, 13 wks")],
    "Compare {contract_a} with {contract_b} for the profile. Table (Factor | A | B | Edge) covering hourly equivalents, hours, shift, housing cost realism, licence needed and time to get it, travel cost, cost of living and cancellation terms; kv with a net 13-week estimate for each and the assumptions used; and a callout naming the deciding factor and what could change it.",
    "table, kv, callout", "Compare", "Weighing…"),
  T("redflags", "Contract red flags", "Paste clauses before you sign", "🚩",
    [LONG("contract", "Paste the contract or worrying clauses", "Facility may cancel with 24 hours notice… nurse liable for housing…")],
    "Review {contract}. Produce a table (Clause | Risk level | Why it matters | Ask for instead) for every notable clause, a checklist of items that must be in writing before signing (guaranteed hours, float policy, cancellation pay, overtime rate, extension terms), a quote with a polite email requesting the changes, and a callout that a lawyer should review anything unusual.",
    "table, checklist, quote, callout", "Review", "Reading fine print…"),
  T("prep", "Prep for the new state", "Licence, compliance, housing, budget", "🧳",
    [TXT("state", "Assignment state", "California", True), TXT("start", "Start date", "3 Nov")],
    "Prepare for an assignment in {state} starting {start} with the profile's licences. Give steps working back from the start date (licence by endorsement or compact check, walk-through options, compliance documents, physical, titres, fit test, housing), a checklist of documents recruiters typically demand, kv (typical licence processing time, fees, furnished-housing sources, rough rent range), and a callout on avoiding housing scams.",
    "steps, checklist, kv, callout", "Prep me", "Packing…"),
  T("negotiate", "Talk to the recruiter", "Scripts for rate, extension and cancellation", "📞",
    [CH("goal", "Goal", ["Higher rate", "Extension bonus", "Cancelled contract", "Switching agencies", "Time off request"], "Higher rate"), TXT("context", "Context", "another agency offered $200 more, 3 weeks in")],
    "Write recruiter conversation scripts for '{goal}' given {context} and the profile. Provide a quote with the opening message (text or phone), bullets of leverage points and what NOT to say, steps for the exchange including when to walk away, and a kv of realistic outcomes (best case, likely, floor).",
    "quote, bullets, steps, kv", "Script it", "Dialling…")],
 "Pay, tax-home and contract information is general guidance, not tax, financial or legal advice; verify with a qualified professional.")

APP("staffroom_ready", "Staffroom Ready", "Teacher applications, demo lessons and panel interviews", "Business", ["#3949AB", "#F9A825", "#8D6E63"], "book",
 "Staffroom Ready gets K-12 teachers hired: it decodes school and district postings, plans the demo lesson minute by minute, drafts a teaching philosophy in your voice, runs panel interviews and assembles a portfolio that shows evidence, not adjectives.",
 "You are a former principal who has sat on hundreds of hiring panels: warm, specific, allergic to jargon, and honest about what schools actually screen for.",
 "Get the classroom you want", "Your subject, level and status shape every answer.", ["Demo lessons that panels remember", "Teaching philosophy in your voice", "Panel interview practice"],
 [NAME, CH("level", "Level", ["Early years", "Primary/Elementary", "Middle", "High school", "SEND/Special ed"]), TXT("subject", "Subject(s)", "Maths, some physics"), CH("status", "Status", ["Student teacher", "NQT/first year", "Experienced", "Returning to teaching", "Career changer"])],
 [T("decode", "Decode a posting", "What the school really wants", "🔍",
    [LONG("posting", "Paste the job ad / person spec", "We seek an inspirational teacher of…"), TXT("school", "School website notes (optional)", "Ofsted good 2023, 60% pupil premium")],
    "Analyse {posting} plus the notes {school}. Produce kv (school type, likely priorities, pay scale or range, application format, deadline), a table (Criterion | Essential or desirable | Evidence from the profile | Strength 1–5), bullets of phrases to mirror in the application, and a callout on warning signs or gaps to address head-on.",
    "kv, table, bullets, callout", "Decode", "Reading the ad…"),
  T("demo", "Plan my demo lesson", "Timed, differentiated, observable", "🍎",
    [TXT("topic", "Topic given", "Fractions of amounts, Year 5", True), NUM("minutes", "Minutes", "30"), TXT("class", "What you know about the class", "28 pupils, 4 EAL, 2 with EHCPs")],
    "Plan a {minutes}-minute demo lesson on {topic} for {class}. Give steps with minute-by-minute timings (hook, modelling, guided practice, independent task, plenary), each naming what the observer sees pupils doing; a table (Group | Adaptation | Resource) for differentiation; a checklist of resources to bring and backup plans if tech fails; and a callout on the three things panels mark hardest: behaviour routines, questioning, checking for understanding.",
    "steps, table, checklist, callout", "Plan lesson", "Sharpening chalk…"),
  T("philosophy", "Teaching philosophy", "A statement that sounds like you", "✍️",
    [LONG("beliefs", "What you believe about learning", "every kid can do maths, mistakes are data…"), LONG("story", "One moment that shows it", "the time a refuser finished a whole problem set…", req=False)],
    "Draft a 350-word teaching philosophy statement from {beliefs} and the story {story}, matched to the profile's level and subject. Provide text (the full statement, first person, concrete, no clichés), a quote with a two-sentence version for a cover letter, bullets of evidence the writer could add, and a callout on phrases that panels read as empty.",
    "text, quote, bullets, callout", "Draft it", "Writing…"),
  T("panel", "Panel interview", "Teacher-specific questions with STAR answers", "🎤",
    [CH("focus", "Focus", ["Behaviour & routines", "Data & progress", "Safeguarding", "Parents & SEND", "Mixed"], "Mixed")],
    "Run a mock panel interview focused on {focus} for the profile. Give 7 questions as cards (meta = what it tests · who usually asks it) with STAR model answers drawn from the profile's level and subject, a quote with a strong answer to 'why this school', bullets of safeguarding phrasing that must be exactly right, and a checklist of questions to ask the panel.",
    "cards, quote, bullets, checklist", "Start mock", "Convening panel…"),
  T("portfolio", "Build my portfolio", "Evidence over adjectives", "📁",
    [CH("format", "Format", ["Physical binder", "Digital site", "PDF", "Slides"], "PDF")],
    "Design a teaching portfolio in {format} for the profile's status and level. Provide a table (Section | Artefact to include | What it proves | Pages or slides), a checklist of artefacts to collect this term (anonymised work samples, data trackers, feedback, lesson plans), steps for assembling it in a weekend, and a callout on pupil privacy and permissions.",
    "table, checklist, steps, callout", "Design it", "Curating…")],
 "Pay-scale, contract and safeguarding information is general guidance, not legal or HR advice; follow your school, union and regulator's official policies.")

APP("tenure_track", "Tenure Track", "Faculty applications from statements to startup package", "Business", ["#4A148C", "#C0CA33", "#00838F"], "hat",
 "Tenure Track guides PhDs and postdocs through the academic job market: research and teaching statements, the job talk, the two-day campus visit and negotiating the startup package, tuned to R1, teaching-focused and community-college searches.",
 "You are a department chair who has run many faculty searches: candid about what committees skim versus read, supportive of non-traditional paths, and precise about negotiation norms.",
 "From ABD to appointment", "Your field and target institutions tune the advice.", ["Statements committees finish reading", "Job talk and Q&A planning", "Startup package negotiation"],
 [NAME, TXT("field", "Field & subfield", "Ecology — plant-pollinator networks"), CH("stage", "Stage", ["ABD", "Recent PhD", "Postdoc", "Adjunct/VAP", "Industry, returning"]), CH("targets", "Targeting", ["R1", "R2/regional", "Liberal arts", "Community college", "Outside US"], multi=True)],
 [T("research", "Research statement", "Vision, agenda, fundability", "🔬",
    [LONG("work", "Your dissertation or current work in plain words", "I study how urban heat changes bee foraging…"), LONG("plans", "Next 3–5 years", "two grants, one field system, one undergrad-friendly project", req=False)],
    "Draft a research statement outline from {work} and {plans} for the profile's targets. Provide steps for the structure (opening problem, contributions so far, three future directions, funding targets, fit) stating what each paragraph must contain; text with the opening paragraph fully written; a table (Direction | First paper | Funding source | Student involvement); and a callout on tailoring length and emphasis by institution type.",
    "steps, text, table, callout", "Outline it", "Drafting…"),
  T("teaching", "Teaching statement", "Evidence-based, not adjectives", "📚",
    [LONG("taught", "What you've taught and how", "TA'd intro bio, designed a seminar on…"), TXT("courses", "Courses you'd want to teach", "Ecology, Biostatistics")],
    "Draft a teaching statement from {taught} and the proposed courses {courses}, tuned to the profile's targets. Give text (a 500-word draft with one concrete classroom example and one piece of evidence), bullets of evidence to gather (evaluations, syllabi, outcomes), a table (Institution type | What to emphasise | What to cut), and a quote with a one-line teaching philosophy for the cover letter.",
    "text, bullets, table, quote", "Draft it", "Writing…"),
  T("jobtalk", "Plan the job talk", "45 minutes, then the hard questions", "🎓",
    [TXT("title", "Talk title / topic", "Pollinator networks in warming cities", True), NUM("minutes", "Minutes for the talk", "45"), CH("audience", "Audience", ["Whole department", "Subfield only", "Mixed with students", "Teaching demo"], "Whole department")],
    "Plan a {minutes}-minute job talk on '{title}' for {audience}. Provide a table (Slide range | Minutes | Content | Purpose) with a 2-minute buffer, steps for rehearsal over two weeks, cards of 8 likely hard questions (meta = who asks · intent) with answer strategies, and a callout on the mistakes that sink talks: too much data, no big picture, ignoring the non-specialists.",
    "table, steps, cards, callout", "Plan talk", "Rehearsing…"),
  T("visit", "Campus visit", "Two days of interviews, meals and one-on-ones", "🏛️",
    [LONG("schedule", "Paste the itinerary", "8:00 breakfast with chair, 9:00 dean, 10:00 grad students…"), TXT("concerns", "What you want to find out", "spousal hire, startup, teaching load")],
    "Prepare for the campus visit itinerary {schedule}, aiming to learn about {concerns}. Produce a table (Meeting | What they assess | What to ask | What to avoid), a checklist of things to pack and prepare, a quote with graceful answers to 'do you have other offers' and to salary questions during the visit, and a callout on meals, alcohol and the dinner that is still an interview.",
    "table, checklist, quote, callout", "Prep visit", "Mapping campus…"),
  T("offer", "Negotiate the offer", "Startup, salary, teaching load, spousal", "💼",
    [LONG("offer", "Paste the offer terms", "$78k 9-month, $150k startup, 2-2 load, 1 semester leave"), TXT("needs", "What your research needs", "field truck, -80 freezer, two grad students")],
    "Review the offer {offer} against the research needs {needs} for the profile. Give a table (Item | Offered | Ask | Justification | Priority), a quote with the negotiation email, bullets of items usually negotiable by institution type (startup, course releases, summer salary, moving, spousal, tenure clock), and a callout on tone, timing and what can cause an offer to be withdrawn.",
    "table, quote, bullets, callout", "Build my ask", "Negotiating…")],
 "Salary and contract guidance is general information, not financial or legal advice; norms vary by institution and country.")

APP("title_block", "Title Block", "Engineering jobs: portfolio, technical rounds, PE path", "Business", ["#37474F", "#FF6F00", "#0097A7"], "gear",
 "Title Block helps mechanical, civil, electrical, chemical and industrial engineers land roles: portfolio entries with real outcomes, technical interview drills by discipline, EIT-to-PE licensure roadmaps, posting decoders and offer comparisons.",
 "You are a principal engineer who hires for a multidisciplinary firm: rigorous about fundamentals, generous with practical tips, and clear that safety and ethics are never negotiable.",
 "Engineer your next role", "Discipline and level set the technical depth.", ["Portfolio entries with real outcomes", "Discipline-specific technical drills", "EIT to PE roadmap"],
 [NAME, CH("discipline", "Discipline", ["Mechanical", "Civil/Structural", "Electrical", "Chemical/Process", "Industrial", "Aerospace", "Environmental"]), CH("level", "Level", ["Student/intern", "Graduate/EIT", "3–7 years", "Senior/PE", "Manager"]), TXT("tools", "Tools & software", "SolidWorks, ANSYS, Python")],
 [T("project", "Portfolio entry", "One project, told like an engineer", "📐",
    [LONG("project", "Describe a project", "redesigned a conveyor bracket that kept cracking…"), PHOTO("Drawing or photo (optional)")],
    "Turn {project} (and the drawing or photo if provided) into a portfolio entry for the profile's discipline. Give 4 cards titled Problem, Constraints, Analysis and Result (meta = your role · tools used · quantified outcome), each 2–3 sentences in engineering language; a quote with a 30-second spoken version for interviews; a table (Skill shown | Evidence in this project | Posting keyword); and a callout on what to redact for confidentiality.",
    "cards, quote, table, callout", "Write entry", "Drafting…"),
  T("technical", "Technical drill", "Fundamentals questions for your discipline", "🧮",
    [CH("topic", "Topic", ["Statics & mechanics", "Thermo & fluids", "Circuits & power", "Controls", "Materials", "Process & mass balance", "Structures & loads", "Manufacturing", "Codes & standards"], "Statics & mechanics"), CH("format", "Interview format", ["Whiteboard", "Verbal", "Take-home", "Panel"], "Verbal")],
    "Drill {topic} in a {format} format for the profile's discipline and level. Provide a table (Question | What it tests | Key formula or concept | Strong answer in one line) with 8 questions, steps that fully solve the hardest one showing units and assumptions, bullets of clarifying questions to ask before solving, and a callout on whiteboard etiquette and recovering from a wrong path.",
    "table, steps, bullets, callout", "Drill me", "Sharpening pencil…"),
  T("licence", "EIT to PE roadmap", "Exams, experience, references", "🪪",
    [TXT("region", "State / country", "Texas", True)],
    "Map the professional licensure path in {region} for the profile's discipline and level. Provide steps (FE/EIT or equivalent, qualifying experience, references, PE exam or chartership, application) with realistic timelines; kv (exam format, pass rates, fees, study hours); a checklist of experience records to start keeping now; and a callout to confirm with the licensing board since rules change.",
    "steps, kv, checklist, callout", "Map it", "Plotting…"),
  T("posting", "Decode a posting", "Required vs nice-to-have, plus gaps", "🔎",
    [LONG("posting", "Paste the job posting", "Mechanical Design Engineer II… GD&T, FEA, DFM…")],
    "Analyse {posting} against the profile. Give a table (Requirement | Must or nice | Your evidence | Gap-closer) for every requirement; kv (seniority level, likely salary band, clearance or citizenship needs, travel, on-site expectations); bullets of five keywords to work into the résumé; and a callout on any mismatch that makes applying a poor use of time.",
    "table, kv, bullets, callout", "Decode", "Parsing…"),
  T("offers", "Compare offers", "Base, bonus, OT exemption, PE support", "⚖️",
    [LONG("offer_a", "Offer A", "$82k, 5% bonus, hybrid, pays PE fees"), LONG("offer_b", "Offer B", "$88k, exempt with 50-hr weeks, relocation $5k")],
    "Compare {offer_a} with {offer_b} for the profile. Table (Factor | A | B | Edge) covering base, bonus, overtime status and real hours, relocation, PE support and mentorship, growth path, commute and cost of living; kv with an estimated effective hourly rate for each; bullets of what to negotiate; and a callout on exempt-status hours and clawbacks.",
    "table, kv, bullets, callout", "Compare", "Calculating…")],
 "Salary and licensing information is general guidance, not financial or legal advice; verify with the licensing board and employer.")

APP("trade_ticket", "Trade Ticket", "Apprenticeships, tickets and job-site hires in the trades", "Business", ["#E65100", "#37474F", "#FDD835"], "wrench",
 "Trade Ticket helps electricians, plumbers, welders, HVAC techs, carpenters and other tradespeople get apprenticeships, pass aptitude tests, sort licences and safety tickets, pitch themselves on site and choose between union, non-union and going solo.",
 "You are a journeyman turned training coordinator: plain-spoken, safety-first, respectful of the trade, and honest about the money.",
 "Get on the tools", "Your trade and region decide the tickets and the path.", ["Apprenticeship applications and tests", "Licence and ticket checker", "Union vs non-union, with numbers"],
 [NAME, CH("trade", "Trade", ["Electrical", "Plumbing/Gas", "HVAC/R", "Welding", "Carpentry", "Heavy equipment", "Ironwork", "Painting/Finishing", "Other"]), CH("stage", "Stage", ["Want an apprenticeship", "Apprentice", "Journeyman", "Master/Licensed", "Switching trades"]), TXT("region", "Region", "Ontario / Ohio / NSW")],
 [T("apprentice", "Get an apprenticeship", "Union, non-union and pre-apprenticeship routes", "🧰",
    [TXT("background", "Your background", "warehouse job, some DIY, good at maths", True), CH("route", "Route", ["Union (JATC/ABC)", "Non-union employer", "Pre-apprenticeship", "Not sure"], "Not sure")],
    "Plan an apprenticeship application for the profile's trade and region via {route}, starting from {background}. Give steps (find sponsors, aptitude test, interview, ranking, employer placement) with realistic timelines and typical intake windows; a checklist of documents and prerequisites (age, education, driving licence, physical); a table (Route | Pay while learning | Time to journeyman | Pros | Cons); and a quote with a 60-second answer to 'why this trade'.",
    "steps, checklist, table, quote", "Plan it", "Lining up…"),
  T("aptitude", "Aptitude test practice", "Algebra, reading and mechanical reasoning", "📏",
    [CH("area", "Practise", ["Algebra & functions", "Reading comprehension", "Mechanical reasoning", "Spatial", "Mixed"], "Mixed"), CH("length", "Length", ["10 questions", "20 questions"], "10 questions")],
    "Generate a practice set of {length} on {area} in the style of trade entrance aptitude tests for the profile's trade. Provide a table (No. | Question | Answer | Method) with every question and worked answer, steps for the fastest method on the hardest question type, bullets of timing strategy, and a callout on what score ranks well and how retakes work.",
    "table, steps, bullets, callout", "Test me", "Setting the test…"),
  T("tickets", "Licence & ticket check", "What you need to work legally", "🪪",
    [TXT("job", "Job you're going for", "commercial electrician, high-rise", True)],
    "List what {job} legally requires in the profile's region and trade. Give a table (Licence or ticket | Who issues it | Prerequisites | Cost | Renewal) covering the trade licence, safety tickets (working at heights, confined space, OSHA/CSCS/White Card equivalents), first aid and equipment cards. Then steps to get the missing ones fastest, a kv of what to carry on day one (cards, ID, PPE, tools), and a callout to verify with the official regulator.",
    "table, steps, kv, callout", "Check", "Checking cards…"),
  T("pitch", "Job-site pitch", "How to get hired by a foreman", "🏗️",
    [CH("how", "Approach", ["Walk-on / cold visit", "Phone call", "Text or email", "Referral"], "Phone call"), TXT("employer", "Who", "mid-size electrical contractor, mostly commercial")],
    "Write a job-site pitch for the profile via {how} to {employer}. Provide a quote with the exact script or message (under 90 seconds), bullets of what to have ready (tickets, tools, boots, references, availability), kv (best time to approach, who to ask for, follow-up timing), and a callout on the things foremen quietly screen out.",
    "quote, bullets, kv, callout", "Write pitch", "Drafting…"),
  T("path", "Union, non-union or solo", "Compare the money and the life", "⚖️",
    [TXT("numbers", "Rates you've been offered or seen", "union scale $42 + benefits; non-union $35; own jobs $80/hr but slow")],
    "Compare union, non-union employment and self-employment for the profile's trade and region using {numbers}. Table (Factor | Union | Non-union | Self-employed) covering hourly, benefits and pension, overtime, steadiness, training, tool and vehicle costs, licensing and insurance; kv with a rough annual net estimate for each and the assumptions; bullets of questions to ask before choosing; and a callout on insurance, tax set-asides and cash-flow risk when going solo.",
    "table, kv, bullets, callout", "Compare", "Adding up…")],
 "Pay, licensing and safety information is general guidance, not financial or legal advice; confirm with your regulator and a qualified adviser.")

APP("shop_floor", "Shop Floor", "Retail jobs from first application to store manager", "Business", ["#D81B60", "#00ACC1", "#FFB300"], "bag",
 "Shop Floor helps retail workers get hired and promoted: applications with no experience, situational interview practice, group assessment days, a plan from associate to keyholder to manager, and honest comparisons of hourly-plus-commission offers.",
 "You are a district manager who started on the till: practical, upbeat, honest about scheduling realities and clear about what stores measure.",
 "Get hired, then get promoted", "Your experience and availability shape the strategy.", ["Applications with zero experience", "Situational interview practice", "Associate to manager plan"],
 [NAME, CH("experience", "Retail experience", ["None yet", "Under 1 year", "1–3 years", "Supervisor/keyholder", "Manager"]), CH("type", "Store type", ["Fashion", "Grocery", "Electronics", "Big-box", "Luxury", "Pharmacy", "Any"], multi=True), TXT("availability", "Availability", "evenings + weekends, not Sundays")],
 [T("apply", "Apply with no experience", "Turn school, sport and volunteering into retail proof", "🛍️",
    [LONG("background", "Everything you've done", "captain of hockey team, babysitting, volunteered at food bank…"), TXT("store", "Store applying to", "Zara, weekend sales assistant")],
    "Build an application for {store} from {background} and the profile. Give bullets of 6 résumé lines that translate the background into retail skills (customer service, cash handling, teamwork, reliability, pace); a quote with a 120-word personal statement or cover note; a table (Application question | Strong answer | Why it works); and a callout on stating availability so the store can actually schedule you.",
    "bullets, quote, table, callout", "Build it", "Folding neatly…"),
  T("situational", "Situational interview", "Angry customers, theft, lazy coworkers", "💬",
    [CH("level", "Role", ["Sales associate", "Cashier", "Stock/backroom", "Keyholder/supervisor", "Assistant manager", "Store manager"], "Sales associate")],
    "Run a situational interview for {level} in the profile's store type. Provide 7 scenarios as cards (meta = what it tests · what a bad answer sounds like) with STAR model answers; a quote with a confident 'tell me about yourself' for this role; bullets on body language and product knowledge to show; and a checklist of questions to ask about hours, commission and progression.",
    "cards, quote, bullets, checklist", "Start", "Opening the till…"),
  T("group", "Group assessment day", "Stand out without steamrolling", "👥",
    [TXT("brand", "Brand & format", "Lush, 2-hour group session with role play")],
    "Prepare for the group assessment {brand} for the profile. Give steps for the day (arrival, icebreakers, group task, role play, one-to-one) with what assessors score at each; a table (Assessor is watching for | Do this | Not this); a quote with an opening line for the icebreaker; and a callout on the classic mistakes: dominating, going silent, ignoring the quiet person.",
    "steps, table, quote, callout", "Prep me", "Warming up…"),
  T("promote", "Get promoted", "Associate to keyholder to manager", "📈",
    [CH("target", "Next role", ["Keyholder", "Supervisor", "Assistant manager", "Store manager", "Visual merchandiser", "Head office"], "Keyholder"), TXT("wins", "Wins so far", "top UPT in store, trained 3 new starters")],
    "Build a promotion plan to {target} for the profile using {wins}. Provide a table (Month | Skill to show | Metric to move | How to make it visible) for 6 months; bullets of retail KPIs to learn and quote (conversion, UPT, ATV, shrink, NPS); a quote with the exact ask to your manager; and a callout on when to look at other stores or brands instead.",
    "table, bullets, quote, callout", "Plan it", "Climbing…"),
  T("compare", "Compare two jobs", "Hourly, commission, hours and holidays", "⚖️",
    [LONG("job_a", "Job A", "$16/hr, 20 hrs guaranteed, 10% staff discount"), LONG("job_b", "Job B", "$14/hr + 3% commission, 35 hrs, open Sundays")],
    "Compare {job_a} with {job_b} for the profile's availability. Table (Factor | A | B | Edge) covering hourly, guaranteed hours, commission realism, weekly and annual estimate, schedule predictability, holiday blackout, discount and progression; kv with the estimated monthly pay for each and the assumptions; bullets of questions to ask before accepting; and a callout on zero-hours or on-call scheduling.",
    "table, kv, bullets, callout", "Compare", "Ringing up…")],
 "Pay estimates are general guidance, not financial or legal advice; check contracts and local employment rules.")

APP("front_of_house", "Front of House", "Hospitality jobs: trial shifts, seasons, tips decoded", "Business", ["#880E4F", "#FFC107", "#00695C"], "cup",
 "Front of House gets hospitality workers hired and paid properly: trial-shift prep for any role, guest-scenario interviews, seasonal and cruise-ship applications, venue knowledge crams, and a decoder for tips, tronc and service charge.",
 "You are a general manager who has run hotels and restaurants: fast, gracious, guest-obsessed, and straight about pay structures and hours.",
 "Service starts here", "Your role and venue type set the standards we prep for.", ["Trial shift and stage preparation", "Guest-scenario interviews", "Tips, tronc and service charge decoded"],
 [NAME, CH("role", "Role", ["Server/waiter", "Bartender", "Barista", "Line cook/chef", "Front desk", "Housekeeping", "Events", "Management"]), CH("venue", "Venue type", ["Casual", "Fine dining", "Hotel", "Bar/club", "Café", "Resort/cruise"], multi=True), TXT("experience", "Experience", "2 years café, 6 months hotel bar")],
 [T("trial", "Ace the trial shift", "What managers watch in the first hour", "⏱️",
    [TXT("shift", "Venue & shift", "busy gastropub, Friday 5–9pm", True), TXT("worries", "What you're nervous about", "carrying three plates, POS system")],
    "Prepare the profile's role for a trial shift at {shift}, worried about {worries}. Give steps from arrival to the end of shift (what to ask, where to stand, how to shadow, when to jump in); a checklist of what to bring and wear; bullets of the things managers score in the first hour; a quote with what to say at the end of the shift; and a callout on trial-shift pay and how to ask about it politely.",
    "steps, checklist, bullets, quote, callout", "Prep me", "Polishing glasses…"),
  T("scenarios", "Guest scenario interview", "Overbooked, complaint, allergen, drunk guest", "🍽️",
    [CH("focus", "Focus", ["Complaints & recovery", "Allergens & safety", "Difficult guests", "Upselling & pace", "Team conflict", "Mixed"], "Mixed")],
    "Run a hospitality interview focused on {focus} for the profile's role and venue types. Provide 7 scenarios as cards (meta = what it tests · the one thing not to do) with model answers that show guest recovery and safety awareness; a quote with a 45-second intro that sounds like a host, not a CV; bullets of questions to ask about rota, tips and breaks; and a callout on allergen and responsible-service phrasing that must be right.",
    "cards, quote, bullets, callout", "Start", "Seating the panel…"),
  T("season", "Seasonal & cruise jobs", "Ski, resort, cruise, festival: timing and papers", "🚢",
    [CH("where", "Type", ["Ski season", "Summer resort", "Cruise ship", "Yacht", "Festival/events", "Working holiday abroad"], "Ski season"), TXT("when", "When you can start", "December, for 5 months")],
    "Plan a {where} job search starting {when} for the profile. Give a table (Month | What to do | Who's hiring | Deadline) working back from the start; a checklist of documents and certificates (passport validity, visa or working-holiday permit, STCW or safety certs, food hygiene, medicals); kv (typical pay, accommodation deal, contract length, hours); and a callout on agency fees and scams.",
    "table, checklist, kv, callout", "Plan season", "Checking tides…"),
  T("cram", "Venue knowledge cram", "Menu, wine list and brand facts before the interview", "📖",
    [LONG("menu", "Paste the menu / wine list / brand info", "Small plates: burrata, nduja croquettes… Wines by glass: Picpoul, Rioja…"), PHOTO("Photo of the menu (optional)")],
    "Cram the venue material {menu} (and the menu photo if given) for the profile's role. Provide a table (Item | What it is | One-line description for guests | Pairs with or upsell); bullets of 10 terms or techniques to pronounce and explain confidently; a quote with three natural upsell lines; and a callout on allergens present in the listed items.",
    "table, bullets, quote, callout", "Cram", "Tasting the menu…"),
  T("pay", "Decode the pay", "Tips, tronc, service charge, split shifts", "💷",
    [LONG("terms", "Paste the offer or describe the pay", "£11.44 + tronc approx £3/hr, 40 hrs, split shifts, service charge 12.5%"), TXT("country", "Country", "UK")],
    "Decode {terms} in {country} for the profile. Give kv (base, tip or tronc estimate, service charge handling, realistic weekly and monthly gross, hours pattern, breaks); a table (Term | What it means | Who controls it | Question to ask); bullets of red flags (unpaid trials, deductions, uniform costs); and a callout on where to check the legal minimum wage and tip rules for that country.",
    "kv, table, bullets, callout", "Decode", "Counting tips…")],
 "Pay and employment-rights information is general guidance, not financial or legal advice; check your country's official rules.")

APP("public_post", "Public Post", "Government jobs: applications that actually get referred", "Business", ["#004D40", "#BF360C", "#78909C"], "globe",
 "Public Post helps you get hired into federal, state, local and civil-service roles: converting a private-sector résumé into the long government format, writing KSA and competency statements, decoding announcements, preparing for clearance and background checks, and scored panel interviews.",
 "You are a former HR specialist for a government agency: meticulous, patient with bureaucracy, and firm that honesty on forms matters more than polish.",
 "Serve, and get paid for it", "Your country and target level tune the format and the jargon.", ["Private to government résumé conversion", "KSA and competency statements", "Clearance and panel-interview prep"],
 [NAME, CH("country", "System", ["US federal", "US state/local", "UK civil service", "Canada public service", "Australia APS/state", "Other"]), TXT("target", "Target roles / series", "IT specialist GS-12, or EO in DWP"), CH("status", "Status", ["Private sector", "Current public servant", "Veteran", "Recent graduate", "Contractor"])],
 [T("resume", "Government résumé", "Convert your CV to the long format", "📄",
    [LONG("resume", "Paste your current résumé", "Senior analyst, Acme Corp, 2019–present…"), LONG("announcement", "Paste the announcement / job ad", "Specialized experience: one year equivalent to GS-11…")],
    "Convert {resume} into the format expected by the profile's system for {announcement}. Provide text (the rewritten experience section with hours per week, dates, supervisor placeholders and detailed duty paragraphs that mirror the specialized-experience language); a table (Announcement requirement | Where it is now evidenced | Strength); bullets on what to add (grades, salary, clearance, veterans' preference documents where relevant); and a callout on length norms and the phrases that get applications screened out.",
    "text, table, bullets, callout", "Convert", "Formatting…"),
  T("ksa", "KSA / competency statement", "Selection criteria and behaviour examples", "🧾",
    [TXT("criterion", "The criterion or competency", "Communicating and Influencing", True), LONG("example", "Your example in rough notes", "led migration project, 3 teams, delivered under budget…")],
    "Write a competency statement for '{criterion}' from {example} in the style the profile's system expects (KSA, Success Profiles behaviour, or STAR selection criteria). Provide text (a 250-word STAR answer with measurable results); a quote with a 100-word compressed version for word-limited forms; bullets of what assessors score and what is missing from the example; and a callout on the rating scale used.",
    "text, quote, bullets, callout", "Write it", "Evidencing…"),
  T("decode", "Decode the announcement", "Grade, series, who may apply, questionnaire", "🔍",
    [LONG("announcement", "Paste the announcement", "Open to: all US citizens… GS-0343-11/12… questionnaire…")],
    "Decode {announcement} for the profile. Give kv (grade or band, salary range, who may apply, hiring path or scheme, closing date, location and remote status, promotion potential); a table (Questionnaire or eligibility item | Honest self-rating advice | Evidence to cite); steps for submitting a complete package by the deadline; and a callout on inflated self-ratings and the documents that cause rejection.",
    "kv, table, steps, callout", "Decode", "Decoding…"),
  T("clearance", "Clearance & background", "Prepare the forms without the panic", "🛂",
    [CH("level", "Level", ["Basic background check", "Public trust / BPSS", "Secret / SC", "Top secret / DV", "Not sure"], "Not sure"), TXT("concerns", "Anything you're worried about", "old debt, foreign contacts, a caution at 19")],
    "Prepare for a {level} check given the concerns {concerns} and the profile's system. Provide a checklist of records and details to gather (addresses, employers, references, travel, finances); a table (Concern | How it is usually viewed | How to disclose it well); kv (typical timeline, who investigates, what to expect in an interview); and a callout that honest full disclosure beats omission, plus when to consult a lawyer.",
    "checklist, table, kv, callout", "Prepare me", "Filing…"),
  T("panel", "Structured interview", "Scored panels, STAR every time", "🎤",
    [CH("focus", "Focus", ["Leadership", "Analysis & judgement", "Customer / public service", "Delivering at pace", "Technical", "Mixed"], "Mixed")],
    "Run a structured panel interview focused on {focus} for the profile's target roles. Provide 6 questions as cards (meta = competency · scoring level) with STAR model answers using the profile's background; a quote with a strong 'why public service' answer; bullets on how scored panels work and why every answer needs a result; and a checklist of questions to ask the panel.",
    "cards, quote, bullets, checklist", "Start panel", "Convening…")],
 "Government hiring, clearance and pay information is general guidance, not legal advice; follow the official announcement and agency instructions.")

APP("badge_bound", "Badge Bound", "Police, fire and EMS hiring from written test to oral board", "Business", ["#0D47A1", "#C62828", "#FFB300"], "shield",
 "Badge Bound guides police, firefighter, paramedic, EMT, corrections and dispatch candidates through the hiring pipeline: process maps, written exam prep, physical ability test plans, background packet and polygraph preparation, and oral board practice.",
 "You are a retired training sergeant who has sat on oral boards and background units: direct, fair, big on integrity, and clear that fitness plans are general guidance.",
 "Earn the badge", "Your target service and agency tune every stage.", ["The full hiring pipeline, staged", "Oral board practice with feedback", "Physical test training plans"],
 [NAME, CH("service", "Service", ["Police", "Fire", "EMS/Paramedic", "Corrections", "Dispatch/911", "Border/Customs"]), TXT("agency", "Agency you're targeting", "Denver PD / county fire district"), CH("stage", "Where you are", ["Researching", "Applied", "Written test next", "Physical test next", "Background", "Oral board", "Academy offer"])],
 [T("pipeline", "Map the process", "Every stage, timeline and what fails people", "🗺️",
    [TXT("country", "Country / state", "USA, Colorado")],
    "Map the hiring pipeline for the profile's service and agency in {country}. Provide a table (Stage | What happens | Typical wait | What fails candidates | How to prep); a checklist of documents to assemble now (ID, driving record, education, references, military records); kv (minimum requirements: age, education, residency, driving, plus common automatic disqualifiers); and a callout to confirm details with the agency's recruiting unit.",
    "table, checklist, kv, callout", "Map it", "Plotting route…"),
  T("written", "Written exam prep", "Reading, report writing, judgement, maths", "✏️",
    [CH("area", "Practise", ["Reading comprehension", "Report writing & grammar", "Situational judgement", "Maths & data", "Mechanical aptitude (fire)", "Mixed"], "Mixed")],
    "Generate a practice set on {area} in the style of entry exams for the profile's service. Provide a table (No. | Question | Answer | Why) with 10 questions; steps for attacking the hardest question type under time pressure; bullets of common wording traps; and a callout on test-day logistics and what score usually makes the eligibility list.",
    "table, steps, bullets, callout", "Test me", "Sharpening pencils…"),
  T("physical", "Physical test plan", "CPAT, POPAT, PAT and academy fitness", "🏃",
    [TXT("test", "Test name / events", "CPAT: stair climb, hose drag, ladder raise…", True), NUM("weeks", "Weeks until the test", "8"), TXT("fitness", "Current fitness", "run 2 miles in 18 min, 10 push-ups")],
    "Build a {weeks}-week training plan for {test} starting from {fitness} for the profile. Provide a table (Week | Sessions | Focus | Test-specific drill) that progresses safely; steps for test day (warm-up, pacing, event-order tips); bullets of technique cues for the hardest events; and a callout on injury red flags, rest days and getting a medical check before starting.",
    "table, steps, bullets, callout", "Build plan", "Lacing up…"),
  T("background", "Background & polygraph", "Disclose well, omit nothing", "🗂️",
    [LONG("history", "Anything that might come up", "smoked weed twice in college, one speeding ticket, fired from a retail job at 19…", req=False), CH("part", "Part of the process", ["Personal history statement", "Background interview", "Polygraph / CVSA", "Psych evaluation", "All"], "All")],
    "Prepare the profile for '{part}' given the history {history}. Provide a checklist of the records and people investigators will contact; a table (Issue | How agencies usually view it | How to disclose it honestly and briefly); steps for the interview or polygraph day (sleep, honesty, consistency with the written statement); a quote with an example of a good disclosure; and a callout that omissions fail more candidates than the issue itself, plus when to get legal advice.",
    "checklist, table, steps, quote, callout", "Prepare me", "Reviewing file…"),
  T("oral", "Oral board practice", "Why us, ethics, use of force, teamwork", "🎙️",
    [CH("focus", "Focus", ["Why this agency", "Integrity & ethics", "Use of force / scene safety", "Teamwork & conflict", "Community & communication", "Mixed"], "Mixed")],
    "Run an oral board focused on {focus} for the profile's service and agency. Provide 6 questions as cards (meta = what it tests · the answer that fails) with model answers that show judgement, honesty and chain-of-command awareness; a quote with a 60-second opening statement; bullets on dress, posture, eye contact and closing; and a callout on the questions where a scripted-sounding answer hurts.",
    "cards, quote, bullets, callout", "Start board", "Board convening…")],
 "Fitness plans are general guidance; get medical clearance before training. Hiring and background information is not legal advice; follow the agency's official process.")
