from dsl import *
LEGAL = "Pricing and contract wording are drafts; have terms, liability and payment clauses reviewed by your legal and finance teams before sending."
FIN = "ROI, cost and forecast figures are illustrative estimates from the numbers you enter, not financial advice; validate every assumption with real data and your finance team."
OUTREACH = "Cold outreach is regulated: check consent, opt-out and B2B rules that apply where your prospects live (CAN-SPAM, GDPR, PECR, CASL) before sending, and honour every unsubscribe."
EST = "ARR, expansion and potential figures are estimates built from what you enter, not financial projections; confirm them in your CRM and with finance before committing to a number."

APP("cold_reach", "Cold Reach", "Outreach that gets replies, not unsubscribes", "Business", ["#1565C0", "#FF6F00", "#00897B"], "bolt",
 "Cold Reach writes multi-touch outreach sequences across email, LinkedIn and phone, personalises each touch from what you actually know about the prospect, and tells you what to say when they reply.",
 "You are a top-performing SDR coach: concise, specific, allergic to buzzwords and fake personalisation; every message leads with the prospect's problem, not the product.",
 "Book more first meetings", "Tell us what you sell and who buys it; every message will be built around that.", ["Multi-touch sequences in minutes", "Real personalisation from profile details", "Reply handling for every response"],
 [NAME, TXT("product", "What you sell", "expense management software for mid-size finance teams"), TXT("icp", "Who buys it", "CFOs and controllers at 200–2,000 employee companies"), CH("tone", "Tone", ["Direct", "Friendly", "Consultative", "Playful"], "Direct")],
 [T("sequence", "Build a sequence", "Email + LinkedIn + call touches", "📨",
    [TXT("persona", "Prospect persona", "VP Finance at a Series C fintech", True), CH("length", "Touches", ["4", "6", "8"], "6"), CH("channels", "Channels", ["Email only", "Email + LinkedIn", "Email + LinkedIn + phone"], "Email + LinkedIn")],
    "Write a {length}-touch cold outreach sequence for {persona} using {channels}, selling the profile's product in the profile's tone. Sections: a table (Day | Channel | Goal | Hook) laying out the cadence, then one quote section per touch with the full copy (subject line under 5 words for emails, under 300 characters for LinkedIn notes, a 20-second opener for calls), and a callout naming the single most common mistake to avoid with this persona.",
    "table, quote, callout", "Build sequence", "Warming up…"),
  T("personalise", "Personalise a touch", "Paste their LinkedIn bio or post", "🎯",
    [LONG("bio", "Profile / bio / recent post", "Head of RevOps at Acme. Posted last week about forecasting pain…"), CH("touch", "Message type", ["Cold email", "LinkedIn connect note", "LinkedIn InMail", "Voicemail"], "Cold email")],
    "From this prospect info: {bio} — write a {touch} that references two specific, non-creepy details and ties them to the profile's product. Sections: bullets listing the details you chose and why, a quote with the final message (under 90 words for email, under 300 characters for a connect note, under 30 seconds spoken for voicemail), and kv (Hook used | Ask | Best send time).",
    "bullets, quote, kv", "Personalise", "Doing homework…"),
  T("subject", "Cold subject lines", "10 lines for a cold email, ranked", "🧪",
    [LONG("email", "Email body", "paste the email you plan to send"), CH("style", "Style", ["Curiosity", "Pain-led", "Referral", "Question", "Mix"], "Mix")],
    "For this cold email to a prospect who has never heard of us: {email} — generate 10 subject lines in the {style} style as a table (Subject | Angle | Open tier: High/Med/Low | Spam-word risk). Then bullets with the 3 preview-text lines that pair best with the top subject, and a callout on words and formatting that trigger spam filters.",
    "table, bullets, callout", "Rank subjects", "Testing lines…"),
  T("reply", "They replied — now what?", "Turn any reply into a next step", "💬",
    [LONG("reply_text", "Their reply", "Thanks but we're all set with our current vendor."), TXT("context", "Context", "3rd touch, they opened twice")],
    "The prospect replied: {reply_text}. Context, if any: {context}. Classify the reply in kv (Type | Real meaning | Win probability), then write 2 response options as quote sections (one short and low-pressure, one that reframes with a question), and steps for what to do if they go silent again.",
    "kv, quote, steps", "Draft reply", "Reading the room…"),
  T("breakup", "Break-up email", "The last touch that gets replies", "👋",
    [LONG("thread", "What you've sent so far", "4 emails about invoice automation over 3 weeks, no reply")],
    "Write a break-up email closing this sequence: {thread}. Sections: a quote with the email (under 60 words, no guilt-tripping, one clear door left open), bullets with 3 alternative closing lines for different personas, and a callout on when to actually re-engage (timing and trigger events).",
    "quote, bullets, callout", "Write it", "Saying goodbye…")], OUTREACH)

APP("disco_call", "Discovery Lab", "Run discovery calls that uncover the real pain", "Business", ["#6A1B9A", "#00ACC1", "#FFB300"], "mic",
 "Discovery Lab preps you for every discovery call with tailored question maps, scores the conversation afterwards against your qualification framework, and writes the recap the prospect actually reads.",
 "You are a veteran enterprise seller and call coach: curious, structured, more interested in the buyer's problem than the pitch, and honest about gaps in qualification.",
 "Ask better questions, close better deals", "A little about what you sell sharpens every question.", ["Question maps for each persona", "Post-call scoring and gaps", "Recap emails in one tap"],
 [NAME, TXT("product", "What you sell", "workforce scheduling software for hospitals"), CH("framework", "Qualification framework", ["MEDDIC", "SPIN", "BANT", "Challenger"], "MEDDIC"), CH("cycle", "Typical sales cycle", ["Under 30 days", "1–3 months", "3–6 months", "6+ months"], "1–3 months")],
 [T("prep", "Prep my call", "Agenda, questions, traps", "📋",
    [TXT("who", "Who you're meeting", "Director of Nursing, 400-bed hospital", True), TXT("known", "What you already know", "using spreadsheets, high overtime costs"), NUM("minutes", "Call length (minutes)", "30")],
    "Prep a discovery call of {minutes} minutes (assume 30 if blank) with {who}; known so far: {known}. Sections: steps for the call agenda with minute markers, a table of 10 questions (Question | What it uncovers | Element of the profile's framework), bullets of 3 likely pushbacks with a one-line handle each, and a quote with the exact opening line.",
    "steps, table, bullets, quote", "Prep call", "Sharpening…"),
  T("bank", "Question bank", "Questions for a pain hypothesis", "🧠",
    [TXT("pain", "Suspected pain", "manual scheduling causes nurse burnout", True), CH("depth", "Depth", ["Surface", "Implication", "Need-payoff"], "Implication")],
    "Build discovery questions around the hypothesis '{pain}' at {depth} depth. Sections: cards grouped by theme (each card = 3 questions, meta = when in the call to ask), a table (Question | Good answer sounds like | Red-flag answer), and a callout on how to transition from this pain to a next step without pitching.",
    "cards, table, callout", "Build bank", "Getting curious…"),
  T("debrief", "Debrief the call", "Notes or transcript → score + gaps", "📝",
    [LONG("notes", "Call notes or transcript", "They mentioned budget freeze until Q3, champion is the ops manager, decision by VP… (or paste the transcript)")],
    "Score this discovery call against the profile's framework from: {notes}. Sections: a table (Element | What we learned | Confidence 1–5 | Gap), kv (Deal stage | Champion | Economic buyer | Compelling event | Next step secured: yes/no | Risk level), a table (Buyer said | What it likely means | Question you should have asked) of up to 5 hints you didn't follow up, a checklist of next steps with owners, and a callout on the single biggest unknown to resolve before proposing.",
    "table, kv, table, checklist, callout", "Score it", "Reviewing tape…"),
  T("recap", "Recap email", "The follow-up they'll forward", "✉️",
    [LONG("summary", "What was discussed", "pain: overtime; they want a pilot in ICU; next step demo on the 14th"), CH("tone", "Tone", ["Crisp", "Warm", "Executive"], "Crisp")],
    "Write a {tone} post-discovery recap email from: {summary}. Sections: a quote with the email (under 150 words, structured as what we heard / what we agreed / next steps with dates), bullets of 2 questions to plant for the next call, and a callout on what NOT to include (pricing, over-promises, jargon).",
    "quote, bullets, callout", "Write recap", "Summarising…"),
  T("fix", "Fix my questions", "Leading, closed or vague → open and sharp", "🔧",
    [LONG("questions", "Questions you plan to ask", "Are you happy with your current scheduling tool? Would you say overtime is a problem?"), TXT("goal", "What you need to learn", "whether overtime cost is big enough to fund a change")],
    "Rewrite these discovery questions: {questions}; what the call must uncover: {goal}. Sections: a table (Your question | Problem: leading/closed/double-barrelled/pitchy/vague | Better version | What the better version uncovers), bullets of 3 questions you are missing for the goal, a quote with the tightest 5-question sequence in order, and a callout on the one habit (e.g. answering your own question) to break on the next call.",
    "table, bullets, quote, callout", "Fix questions", "Sharpening…")])

APP("objection_dojo", "Objection Dojo", "Turn every 'no' into a next step", "Business", ["#B71C1C", "#37474F", "#FFA000"], "shield",
 "Objection Dojo gives you calm, specific responses to price, timing, competitor and 'send me some info' objections, then drills you with role-play until they're second nature.",
 "You are a black-belt sales trainer: composed, empathetic, never argumentative; you acknowledge, clarify, respond and confirm, and you never trash competitors.",
 "Stay calm when they push back", "Tell us what you sell and what you hear most; the responses get sharper.", ["Responses for any objection", "Competitor battle-ready lines", "Role-play drills that build reflexes"],
 [NAME, TXT("product", "What you sell", "cyber-security awareness training"), TXT("competitors", "Main competitors", "KnowBe4, Proofpoint"), TXT("common", "Objections you hear most", "too expensive, we already have a tool")],
 [T("handle", "Handle this objection", "Verbatim → 3 ways to respond", "🥋",
    [LONG("objection", "What they said", "We don't have budget this year."), CH("stage", "Deal stage", ["First call", "Mid-cycle", "Proposal sent", "Closing"], "Mid-cycle")],
    "The prospect said: {objection} at the {stage} stage. Sections: kv (Objection type | What's really behind it | Do not say), steps following acknowledge → clarify → respond → confirm with exact wording for each, 3 quote sections with alternative responses (empathetic, data-led, question-led), and a callout on when to accept the no and walk away.",
    "kv, steps, quote, callout", "Handle it", "Bowing in…"),
  T("price", "Price pushback", "Defend value without discounting", "💸",
    [TXT("quote_amt", "Your price", "$18,000/year", True), TXT("their", "What they said", "Your competitor is 30% cheaper", True), TXT("value", "Value delivered", "cuts phishing click rate from 20% to 3%")],
    "Price objection: they said '{their}' against our price of {quote_amt}; value delivered: {value}. Sections: text reframing price as cost of inaction in 3 sentences, a table (Give | Get | When to use) of 5 trade-based concessions that avoid a naked discount, a quote with the exact response, and a callout on holding a discount floor.",
    "text, table, quote, callout", "Defend price", "Holding the line…"),
  T("compete", "Competitor comparison", "When they name a rival", "⚔️",
    [TXT("rival", "Competitor named", "Proofpoint", True), TXT("their_claim", "What they like about them", "bundled with email security")],
    "They are comparing us with {rival} because: {their_claim}. Sections: a table (Dimension | Us | {rival} | Proof to bring) with 6 dimensions, honest about where the rival wins, bullets of 3 landmine questions that favour our strengths without naming the rival, a quote with a respectful response, and a callout on what never to say about a competitor.",
    "table, bullets, quote, callout", "Compare", "Scouting rival…"),
  T("drill", "Role-play drill", "5 curveballs with model answers", "🎯",
    [CH("focus", "Focus area", ["Price", "Timing", "Authority", "Trust / risk", "Status quo", "Mixed"], "Mixed"), CH("difficulty", "Difficulty", ["Warm-up", "Realistic", "Brutal"], "Realistic")],
    "Run a {difficulty} role-play drill focused on {focus} for the profile's product. Sections: 5 cards, each a prospect line to respond to (meta = objection type · difficulty) with a model answer beneath it, a checklist for self-scoring each response (acknowledged, clarified, no defensiveness, confirmed next step), and a quote with one mantra to say before the next real call.",
    "cards, checklist, quote", "Start drill", "Entering the dojo…"),
  T("library", "My objection library", "Prep before a new campaign", "📚",
    [TXT("segment", "Segment or campaign", "SMB retailers in Q4")],
    "Build an objection playbook for the profile's product targeting {segment}, starting from the common objections in the profile. Sections: a table (Objection | Root cause | 1-line response | Proof point) with 10 rows, bullets of the 3 objections to pre-empt in the pitch itself, and a callout on the objection that usually signals a bad-fit prospect.",
    "table, bullets, callout", "Build playbook", "Stacking shields…")])

APP("proposal_press", "Proposal Press", "Proposals that read like the client wrote them", "Business", ["#1B5E20", "#5D4037", "#FDD835"], "note",
 "Proposal Press turns discovery notes into client-centred proposals, executive summaries, pricing options and scopes of work, then reviews your draft like a sceptical procurement lead.",
 "You are a proposal strategist: client-first, plain-English, precise about scope and assumptions; you write for the executive who reads only page one.",
 "Write proposals that win", "Your offer and style shape every draft.", ["Executive summaries that lead with outcomes", "Good/better/best pricing tables", "Scope, assumptions and a procurement-style review"],
 [NAME, TXT("company", "Your company & offer", "Northwind — managed IT services for law firms"), CH("style", "Proposal style", ["Formal", "Conversational", "Startup-crisp"], "Formal"), TXT("currency", "Currency", "USD")],
 [T("draft", "Draft a proposal", "Notes → full structure", "📄",
    [LONG("notes", "Discovery notes", "client: 40-lawyer firm, pain: outages, wants 24/7 support, budget ~$8k/mo"), TXT("client", "Client name", "Harper & Lowe LLP", True)],
    "Draft a proposal for {client} from these notes: {notes}, in the profile's style and currency. Sections: text executive summary (under 150 words, leading with the client's outcome), steps for the proposed approach in phases with durations, a table (Deliverable | Description | Timeline | Owner), kv (Investment | Term | Payment schedule | Valid until), and a callout of assumptions and exclusions.",
    "text, steps, table, kv, callout", "Draft proposal", "Pressing pages…"),
  T("exec", "Executive summary", "Page one, rewritten", "🏆",
    [LONG("draft", "Current summary or key points", "paste your existing summary"), TXT("goal", "Client's stated goal", "reduce downtime by 80%", True)],
    "Rewrite this executive summary: {draft} so it leads with the client goal '{goal}'. Sections: a quote with the new summary (4 short paragraphs: situation, cost of inaction, our approach, expected outcome), bullets listing every phrase you removed and why, and a callout on the one number to put in bold.",
    "quote, bullets, callout", "Rewrite", "Cutting fluff…"),
  T("pricing", "Pricing options", "Good / better / best", "💰",
    [TXT("base", "Base offer & price", "core support package at $6,000/month", True), TXT("addons", "Possible add-ons", "security monitoring, backup, training")],
    "Design three pricing tiers around {base} with add-ons {addons}, in the profile's currency. Sections: a table (Feature | Essential | Professional | Premium) with prices in the header row, kv per tier (Best for | Price anchor logic | Margin note), bullets on presenting the middle tier as the default, and a callout on discounts to never offer.",
    "table, kv, bullets, callout", "Build tiers", "Anchoring…"),
  T("scope", "Scope of work", "Tight scope, no scope creep", "📐",
    [LONG("work", "What you'll deliver", "migrate 40 mailboxes, set up helpdesk, monthly reviews")],
    "Write a scope of work for: {work}. Sections: bullets 'In scope' and 'Out of scope' as two lists, a table (Milestone | Acceptance criteria | Due), a checklist of client responsibilities, and a callout on change-request handling and how extra work is priced.",
    "bullets, table, checklist, callout", "Write scope", "Drawing lines…"),
  T("review", "Procurement review", "Paste a draft, get torn apart kindly", "🔎",
    [LONG("proposal", "Proposal text", "paste the proposal")],
    "Review this proposal as a sceptical procurement lead: {proposal}. Sections: kv (Overall score /10 | Clarity | Client focus | Risk exposure | Price justification), a table (Issue | Where | Fix), bullets of the 3 questions procurement will ask, and a callout on the sentence most likely to lose the deal.",
    "kv, table, bullets, callout", "Review", "Playing procurement…")], LEGAL)

APP("account_atlas", "Account Atlas", "Strategic account plans that actually get used", "Business", ["#00695C", "#3949AB", "#F4511E"], "globe",
 "Account Atlas builds one-page account plans, stakeholder maps, whitespace analyses and QBR agendas for the accounts that matter most, and tells you which ones deserve your hours.",
 "You are a strategic account director: politically astute, numbers-aware, focused on multi-threading and expansion; you plan in quarters and speak in the customer's KPIs.",
 "Grow the accounts you already have", "Tell us about your book of business.", ["One-page account plans", "Stakeholder & power maps", "Whitespace and QBR prep"],
 [NAME, TXT("products", "Products you can sell", "CRM, marketing automation, analytics add-on"), CH("segment", "Segment", ["SMB", "Mid-market", "Enterprise", "Strategic"], "Enterprise"), NUM("target", "Annual expansion target", "500000")],
 [T("plan", "Account plan", "One page, one quarter", "🗺️",
    [TXT("account", "Account", "Globex Corp — 3,000 employees, on our CRM since 2022", True), LONG("situation", "Current situation", "renewal in 9 months, champion moved teams, new CIO…")],
    "Build a one-page account plan for {account}; situation: {situation}. Sections: kv (Current ARR | Expansion goal | Renewal date | Health | Executive sponsor), a table (Objective | Play | Owner | By when | Success metric) with 4 rows, bullets of the 3 biggest risks, and a checklist of actions for the next 30 days.",
    "kv, table, bullets, checklist", "Build plan", "Charting…"),
  T("stakeholders", "Stakeholder map", "Who matters, who's missing", "👥",
    [LONG("people", "People you know", "Jane (CIO, new, unknown stance), Raj (ops manager, champion), Lee (procurement, blocker)")],
    "Map these stakeholders: {people}. Sections: a table (Name | Role | Influence H/M/L | Stance: champion/neutral/blocker/unknown | What they care about | Next touch), bullets naming the roles missing from the map that usually decide deals in the profile's segment, steps to multi-thread into the two most important gaps, and a callout on the relationship most at risk.",
    "table, bullets, steps, callout", "Map it", "Mapping power…"),
  T("whitespace", "Whitespace analysis", "What else could they buy", "🧩",
    [LONG("owns", "What they own today", "CRM for 200 seats in sales; marketing uses a competitor"), TXT("signals", "Signals", "hiring 3 marketing ops roles, new EMEA office")],
    "Find expansion opportunities given they own: {owns}; signals: {signals}; sellable products from the profile. Sections: a table (Opportunity | Product | Est. value | Trigger | Confidence), cards for the top 3 plays (meta = timing · effort), and a quote with an opening line to the right stakeholder for the best play.",
    "table, cards, quote", "Find whitespace", "Scanning map…"),
  T("qbr", "QBR agenda", "A business review they'll show up to", "📊",
    [TXT("quarter", "Quarter & audience", "Q3 with the CIO and ops leads", True), LONG("results", "Results to share", "adoption 78%, 12% faster response times, 2 open tickets")],
    "Design a QBR for {quarter} using results: {results}. Sections: steps for a 45-minute agenda with minute markers, a table (Slide | Headline | Data to show | Ask), bullets of 3 questions to ask the executive about next quarter, and a callout on the one expansion ask to land and how to phrase it.",
    "steps, table, bullets, callout", "Build QBR", "Prepping deck…"),
  T("prioritise", "Prioritise my book", "Which accounts deserve the hours", "🎯",
    [LONG("accounts", "Your accounts", "Acme $120k renewal Jun, low usage; Globex $400k, growing; Initech $40k, new CIO…")],
    "Rank these accounts for attention this quarter against the profile's expansion target: {accounts}. Sections: a table (Account | ARR | Expansion potential | Risk | Priority tier A/B/C | Hours per week), bullets explaining the tiering logic, kv (Total potential | Coverage of target | Gap to close), and a callout on the account to deliberately deprioritise.",
    "table, bullets, kv, callout", "Rank accounts", "Weighing book…")], EST)

APP("renewal_radar", "Renewal Radar", "Spot churn early, drive adoption, renew on time", "Business", ["#AD1457", "#00838F", "#7CB342"], "heart",
 "Renewal Radar is a customer success manager's toolkit: health scores from messy notes, 30/60/90 onboarding plans, adoption nudge campaigns, renewal playbooks and save plans for accounts going quiet.",
 "You are a seasoned customer success lead: proactive, outcome-obsessed, calm under escalation; you measure success in the customer's metrics, not logins.",
 "Keep customers, grow customers", "Your product and renewal cycle shape the playbooks.", ["Health scores from messy notes", "Onboarding plans that drive adoption", "Renewal and save playbooks"],
 [NAME, TXT("product", "Your product", "B2B payroll platform"), CH("motion", "Motion", ["High-touch", "Tech-touch", "Hybrid"], "Hybrid"), CH("term", "Typical contract", ["Monthly", "Annual", "Multi-year"], "Annual")],
 [T("health", "Health check", "Notes + usage → score", "🩺",
    [LONG("notes", "Account notes & usage", "logins down 30%, champion left, NPS 7, 2 P1 tickets last month, exec sponsor engaged")],
    "Score this customer's health from: {notes}. Sections: kv (Health score /100 | Trend | Renewal risk | Expansion signal | Primary driver), a table (Dimension | Evidence | Score | Action), a checklist of actions for this week, and a callout on what would move the score by 20 points fastest.",
    "kv, table, checklist, callout", "Score health", "Taking pulse…"),
  T("onboard", "Onboarding plan", "30/60/90 to first value", "🚀",
    [TXT("customer", "Customer & goal", "Bravo Logistics, 300 employees, payroll live before April", True), TXT("blockers", "Known blockers", "data migration from legacy system")],
    "Write a 30/60/90-day onboarding plan for {customer} with blockers: {blockers}, matching the profile's motion. Sections: kv (First-value milestone | Target date | Success metric | Exec sponsor cadence), a table (Day | Milestone | Customer owner | Our owner | Done when), a checklist of kickoff-call items, and a callout on the #1 reason onboardings like this stall.",
    "kv, table, checklist, callout", "Plan onboarding", "Rolling out…"),
  T("renewal", "Renewal playbook", "Start 120 days out", "🔁",
    [TXT("account", "Account & renewal date", "Delta Health, renews 30 Nov, $60k ARR", True), CH("mood", "Relationship", ["Delighted", "Fine", "Lukewarm", "Frustrated"], "Fine")],
    "Build a renewal playbook for {account}; the relationship is {mood}. Sections: steps by week counting down from 120 days (who to contact, what to send, what to confirm), a table (Risk | Likelihood | Mitigation), a quote with the renewal-conversation opener, and a callout on price-increase timing and how to justify it with value delivered.",
    "steps, table, quote, callout", "Build playbook", "Counting down…"),
  T("save", "Save plan", "They said they might leave", "🛟",
    [LONG("why", "What they said / what happened", "moving to a cheaper competitor, felt ignored after the outage"), TXT("value_amt", "Account value", "$45k ARR", True)],
    "Build a save plan for a {value_amt} account where: {why}. Sections: kv (Save probability | Root cause | What they need to hear | Decision maker), steps for the next 10 days with owners, a table (Offer lever | Cost to us | Use if…), a quote with the apology-plus-plan message from the CSM, and a callout on when to gracefully let them go.",
    "kv, steps, table, quote, callout", "Build save plan", "Throwing lifeline…"),
  T("adopt", "Adoption nudge", "A feature nobody's using yet", "📈",
    [TXT("feature", "Feature or workflow", "self-service timesheet approvals", True), TXT("usage", "Who's using it and who isn't", "12 of 40 managers; the Spain office hasn't logged in"), TXT("stakes", "Why it matters for renewal", "it's the feature they bought us for")],
    "Design an adoption campaign for {feature} where usage looks like: {usage}; stakes: {stakes}; matching the profile's motion. Sections: kv (Likely blocker: awareness/skill/workflow/permissions | Segment to target first | 30-day adoption target | Metric to watch), steps for a 3-touch nudge campaign over 3 weeks (channel, audience, message goal), two quote sections (the email to the customer admin and a 40-word in-app message), a checklist of enablement assets to prepare, and a callout on the signs that low adoption is a product-fit problem, not a training one.",
    "kv, steps, quote, checklist, callout", "Plan nudges", "Lighting the path…")])

APP("demo_director", "Demo Director", "Product demos that tell a story, not a feature list", "Business", ["#4527A0", "#F57C00", "#00BCD4"], "star",
 "Demo Director scripts persona-tailored product demos with a narrative arc, preps you for live questions and curveballs, critiques your script and writes the follow-up that keeps momentum.",
 "You are a sales-engineering lead and storyteller: you demo the outcome before the feature, keep clicks to a minimum, and handle 'can it do X?' without bluffing.",
 "Show them their future", "Tell us about your product so every demo is grounded in it.", ["Story-driven demo scripts", "Live Q&A and curveball prep", "Script critique and follow-ups"],
 [NAME, TXT("product", "Your product & key features", "field-service app: scheduling, mobile forms, invoicing"), CH("length", "Usual demo length", ["15 min", "30 min", "45 min", "60 min"], "30 min"), CH("format", "Format", ["Live remote", "In person", "Recorded"], "Live remote")],
 [T("script", "Script a demo", "Persona → narrative demo", "🎬",
    [TXT("persona", "Audience", "Operations director at an HVAC company, 25 technicians", True), TXT("pains", "Their top pains", "double bookings, unpaid invoices")],
    "Script a demo for {persona} focused on pains: {pains}, at the profile's usual length and format. Sections: steps for the demo flow with minute markers (each step = what to show, what to say, what to click), a table (Pain | Feature shown | Before/after line | Proof), a quote with the opening 30 seconds, and a callout on features to deliberately NOT show.",
    "steps, table, quote, callout", "Script demo", "Setting stage…"),
  T("questions", "Q&A prep", "Questions they'll ask live", "❓",
    [TXT("audience", "Who's in the room", "CTO, ops director, 2 dispatchers", True), TXT("weak", "Weak spots", "no offline mode yet")],
    "Prep for live demo questions from {audience}, given weak spots: {weak}. Sections: a table (Likely question | Who asks | Honest answer | Bridge back to value) with 10 rows, bullets on how to say 'not yet' without killing the deal, a quote with the response for the toughest weak-spot question, and a callout on the question that signals real buying intent.",
    "table, bullets, quote, callout", "Prep Q&A", "Anticipating…"),
  T("critique", "Critique my script", "Paste it, get a director's notes", "🎭",
    [LONG("script_text", "Your demo script or outline", "paste your script")],
    "Critique this demo script as a demo director: {script_text}. Sections: kv (Story score /10 | Feature-dump risk | Time to first wow | Clicks per minute estimate), a table (Moment | Problem | Fix), steps for a tightened running order, and a quote with a stronger closing line that secures a next step.",
    "kv, table, steps, quote", "Give notes", "Watching rehearsal…"),
  T("curveball", "Curveball rescue", "Demo broke / went off-script", "🧯",
    [CH("what", "What happened", ["Feature crashed", "Audience distracted", "Exec joined late", "Asked for pricing mid-demo", "Competitor mentioned", "Ran out of time"], "Feature crashed")],
    "The demo hit this curveball: {what}. Sections: steps for what to say and do in the next 60 seconds, a quote with the exact recovery line, bullets on how to prevent it next time, and a callout on how to turn the moment into credibility.",
    "steps, quote, bullets, callout", "Rescue me", "Improvising…"),
  T("followup", "Post-demo follow-up", "Keep the momentum", "📬",
    [LONG("what_happened", "How the demo went", "loved scheduling, worried about mobile adoption, CTO wants API docs"), TXT("next", "Proposed next step", "pilot with 5 techs", True)],
    "Write a post-demo follow-up given: {what_happened}, proposing: {next}. Sections: a quote with the email (under 150 words: what resonated, what we'll send, the next step with a date), a checklist of assets to attach, kv (Send by | Cc | Calendar hold to propose), and bullets of 2 internal actions to de-risk the concern raised.",
    "quote, checklist, kv, bullets", "Write follow-up", "Keeping momentum…")])

APP("pipeline_pulse", "Pipeline Pulse", "Honest deal reviews and forecasts you can defend", "Business", ["#00796B", "#C62828", "#FBC02D"], "graph",
 "Pipeline Pulse inspects your deals for real qualification gaps, sorts your forecast into commit, best case and pipeline, revives stalled opportunities and preps you for the weekly forecast call.",
 "You are a no-nonsense sales manager and forecast coach: evidence over optimism, specific next actions, allergic to happy ears.",
 "Know which deals are real", "Your quota and cycle set the bar for every review.", ["Deal inspection against your method", "Forecast categorisation", "Stalled-deal revival plans"],
 [NAME, NUM("quota", "Quarterly quota", "300000"), CH("cycle", "Average cycle", ["2–4 weeks", "1–2 months", "3–4 months", "6+ months"], "1–2 months"), CH("method", "Method", ["MEDDPICC", "BANT", "SPICED", "None yet"], "MEDDPICC")],
 [T("review", "Review my pipeline", "Paste deals, get a ranked view", "📊",
    [LONG("deals", "Your open deals", "Acme $80k, proposal sent, close 30 Sep; Globex $40k, discovery, no champion…")],
    "Review these deals against the profile's quota and method: {deals}. Sections: a table (Deal | Value | Stage | Forecast category: Commit/Best case/Pipeline | Biggest gap | Next action | Close date realistic? yes/no), kv (Total pipeline | Weighted | Commit | Coverage ratio vs quota | Gap to quota), bullets of the 3 deals to spend Monday on, and a callout on deals to push out or disqualify.",
    "table, kv, bullets, callout", "Review pipeline", "Checking pulse…"),
  T("inspect", "Inspect a deal", "Full qualification audit", "🔬",
    [LONG("deal", "Everything you know", "value, stage, champion, competition, timeline, paper process…")],
    "Inspect this deal using the profile's method: {deal}. Sections: a table (Criterion | Evidence | Score 0–3 | How to close the gap), kv (Overall score | True stage | Realistic close date | Win probability), a checklist of the next 5 actions in order, and a quote with the one question to ask the champion this week.",
    "table, kv, checklist, quote", "Inspect deal", "Under microscope…"),
  T("stalled", "Revive a stalled deal", "Silent for weeks", "🧊",
    [TXT("deal_name", "Deal & last contact", "Initech, $25k, last reply 5 weeks ago after pricing", True), TXT("history", "What's happened", "champion went quiet after we sent the quote")],
    "Revive {deal_name}; history: {history}. Sections: kv (Likely reason for silence | Chance of revival | Best channel), 3 quote sections with re-engagement messages (value-add, pattern-interrupt, direct-ask), steps for a 3-week revival cadence, and a callout on when to mark it closed-lost and move on.",
    "kv, quote, steps, callout", "Revive", "Defrosting…"),
  T("forecast", "Forecast call prep", "Defend your number", "🎙️",
    [LONG("commit", "Deals you're committing", "Acme $80k, Delta $45k"), NUM("closed", "Closed so far this quarter", "120000")],
    "Prepare a forecast call: committing {commit}, closed so far this quarter: {closed} (0 if blank), against the profile's quota. Sections: kv (Closed | Commit | Best case | Forecast total | Attainment % | Risk-adjusted forecast), a table (Deal | Value | Why it's in commit | What could slip it | Plan B), bullets of the questions your manager will ask with crisp answers, and a quote with a 30-second opening statement for the call.",
    "kv, table, bullets, quote", "Prep call", "Crunching numbers…"),
  T("weekly", "Weekly selling plan", "Where the hours go", "📅",
    [TXT("focus", "This week's priorities", "2 closes, 5 new discovery calls"), NUM("hours", "Selling hours available", "25")],
    "Plan the selling week with {hours} selling hours (assume 25 if blank) and priorities: {focus}, for the profile's quota. Sections: a table (Day | Block | Activity | Deal or target | Outcome), kv (Hours on closing | Hours prospecting | Hours on admin | Meetings to book), a checklist for the Friday review, and a callout on the activity to cut first if the week goes sideways.",
    "table, kv, checklist, callout", "Plan week", "Blocking time…")], FIN)

APP("champion_kit", "Champion Kit", "Arm your internal champion to sell for you", "Business", ["#E65100", "#283593", "#43A047"], "coin",
 "Champion Kit builds the business case, ROI model, executive one-pager and mutual action plan your internal champion needs to win budget when you're not in the room.",
 "You are a value-engineering consultant: rigorous with numbers, transparent about assumptions, fluent in CFO language; you never inflate ROI.",
 "Win the meeting you're not in", "Your product's value drivers power every business case.", ["Business cases in CFO language", "ROI tables with visible assumptions", "Mutual action plans to close"],
 [NAME, TXT("product", "Your product", "warehouse robotics-as-a-service"), TXT("drivers", "Main value drivers", "labour savings, fewer picking errors, faster shipping"), TXT("currency", "Currency", "USD")],
 [T("case", "Business case", "For the budget meeting", "🏛️",
    [LONG("situation", "Customer situation & numbers", "3 warehouses, 120 pickers at $22/h, 2% error rate, 40k orders/month"), TXT("price", "Our price", "$30k/month", True)],
    "Build a business case for the profile's product at {price} given: {situation}, in the profile's currency. Sections: text executive summary (under 120 words), a table (Value driver | Current cost | With us | Annual impact | Assumption), kv (Total annual benefit | Annual cost | Net benefit | Payback months | 3-year ROI %), a callout listing every assumption to validate, and bullets of the 3 risks a CFO will raise with a one-line answer each.",
    "text, table, kv, callout, bullets", "Build case", "Running numbers…"),
  T("roi", "ROI calculator", "Conservative, base, upside", "🧮",
    [F("cost", "Annual cost of our solution", "number", "360000", required=True), F("benefit", "Estimated annual benefit", "number", "900000", required=True), NUM("ramp", "Months to full value", "6")],
    "Model ROI with annual cost {cost}, estimated annual benefit {benefit} and {ramp} months ramp to full value (assume 6 if blank), in the profile's currency. Sections: a table (Scenario | Year-1 net | Year-3 net | Payback months | ROI %) for Conservative (50% of benefit), Base (100%) and Upside (130%), steps showing how each figure was calculated, a callout on which scenario to present first and why, and a quote with one sentence to say when they challenge the benefit number.",
    "table, steps, callout, quote", "Calculate", "Sharpening pencil…"),
  T("onepager", "Executive one-pager", "What the sponsor forwards", "📃",
    [TXT("exec", "Executive & their priority", "COO, cutting fulfilment cost per order", True), TXT("proof", "Proof points", "cut cost per order 18% at a similar 3PL")],
    "Write an executive one-pager for {exec} with proof: {proof}, for the profile's product. Sections: a quote with the one-pager text (headline, 3-sentence problem, 3-sentence solution, 3 proof bullets, the ask; under 200 words total), kv (Headline metric | The ask | Decision needed by), and bullets on how the champion should present it in 2 minutes.",
    "quote, kv, bullets", "Write one-pager", "Boiling down…"),
  T("map", "Mutual action plan", "Shared close plan with the champion", "🤝",
    [TXT("target", "Target signature date", "15 December", True), LONG("steps_known", "Known steps", "security review, legal redlines, CFO approval, pilot sign-off")],
    "Build a mutual action plan to sign by {target} covering: {steps_known}. Sections: a table (Step | Owner: us/them | Due | Status | Dependency) working backwards from the signature date, a checklist of steps the champion must own, a callout on the step most likely to slip and how to pre-empt it, and a quote with the message that introduces the plan to the champion.",
    "table, checklist, callout, quote", "Build plan", "Working backwards…"),
  T("coach", "Coach the champion", "Prep them for the internal pitch", "🎓",
    [TXT("champion", "Champion & their role", "Priya, ops manager, first time sponsoring a purchase", True), TXT("audience", "Who they're pitching to", "CFO and VP Ops")],
    "Coach {champion} to pitch the profile's product internally to {audience}. Sections: steps for a 5-minute internal pitch, a table (Objection they'll hear | What to say | Backup data), bullets of the questions they should ask us before the meeting, and a quote with a confidence-building message to send them the night before.",
    "steps, table, bullets, quote", "Coach them", "Building confidence…")], FIN)

APP("bid_builder", "Bid Builder", "RFP responses that score, not just comply", "Business", ["#37474F", "#0097A7", "#F9A825"], "book",
 "Bid Builder helps you decide which RFPs to chase, builds compliance matrices from tender text, drafts evaluator-friendly answers and sharpens win themes and cover letters.",
 "You are a bid manager with a high win rate: disciplined about go/no-go, obsessed with the evaluator's scoring sheet, and clear that every claim needs evidence.",
 "Bid smarter, win more", "Your strengths and past wins feed every answer.", ["Go/no-go scorecards", "Compliance matrices from RFP text", "Answers written for evaluators"],
 [NAME, TXT("company", "Company & offering", "Meridian — facilities management for the public sector"), TXT("strengths", "Differentiators", "24h response SLA, ISO 14001, local workforce"), TXT("wins", "Reference wins", "3 county councils, 1 NHS trust")],
 [T("gono", "Go / no-go", "Should you bid at all?", "⚖️",
    [LONG("summary", "RFP summary", "£2m 3-year cleaning contract, 12 sites, incumbent 8 years, 3-week deadline"), TXT("relationship", "Relationship with buyer", "none")],
    "Run a go/no-go on: {summary}; relationship with the buyer: {relationship}; using the profile's strengths and wins. Sections: a table (Criterion | Score 1–5 | Evidence) across fit, winnability, capacity, price competitiveness, incumbent strength and strategic value, kv (Total score | Recommendation | Estimated win probability | Cost to bid), bullets of conditions that would change the answer, and a callout on the one question to ask the buyer before deciding.",
    "table, kv, bullets, callout", "Decide", "Weighing odds…"),
  T("matrix", "Compliance matrix", "Requirements → tracker", "🗂️",
    [LONG("rfp", "Paste the RFP requirements section", "paste the requirements / evaluation criteria")],
    "Extract every requirement from: {rfp}. Sections: a table (Ref | Requirement | Type: mandatory/scored/info | Weight if stated | Owner | Evidence needed | Status), bullets of ambiguous requirements to clarify with the buyer, a checklist of submission documents, and a callout on the mandatory items most bidders miss.",
    "table, bullets, checklist, callout", "Build matrix", "Extracting…"),
  T("answer", "Answer a question", "Evaluator-friendly response", "✍️",
    [LONG("question", "RFP question", "Describe your approach to mobilisation and transition from the incumbent."), NUM("words", "Word limit", "500"), TXT("evidence", "Evidence to use", "took over 12 sites from an incumbent in 6 weeks with zero service gaps")],
    "Answer this RFP question in under {words} words (assume 500 if blank): {question}, using evidence: {evidence} and the profile's strengths. Sections: a quote with the full answer (open with a direct claim, mirror the question's keywords, subheadings that match the scoring criteria), kv (Words used | Scoring criteria addressed | Evidence cited), bullets of the 3 phrases evaluators reward, and a callout on claims that need proof attached.",
    "quote, kv, bullets, callout", "Draft answer", "Writing for score…"),
  T("themes", "Win themes", "Why you, in their words", "🏆",
    [LONG("buyer", "What the buyer cares about", "budget cuts, sustainability targets, complaints about the incumbent's response times"), TXT("rival", "Likely rivals", "incumbent + 2 nationals")],
    "Develop win themes for a buyer who cares about: {buyer}, against {rival}, using the profile's differentiators. Sections: cards for 3–4 win themes (meta = buyer hot button · proof), a table (Theme | Rival weakness it exploits | Where to place it in the bid), a quote with a one-sentence version of each theme for the executive summary, and a callout on ghosting competitors ethically.",
    "cards, table, quote, callout", "Find themes", "Sharpening edge…"),
  T("cover", "Cover letter", "The executive summary they read first", "📨",
    [TXT("buyer_name", "Buyer & contract", "Riverside Council — grounds maintenance 2027–2030", True), TXT("price_pos", "Price position", "8% under incumbent")],
    "Write the executive cover letter for {buyer_name} with price position: {price_pos}, using the profile's company, strengths and wins. Sections: a quote with the letter (under 300 words: their goals, our understanding, 3 win themes, commitment, signature), bullets of what to attach, and a callout on tone mistakes that make public-sector evaluators wince.",
    "quote, bullets, callout", "Write letter", "Sealing envelope…")], LEGAL)
