from dsl import *
OPS = "Generated commands and manifests can change or delete infrastructure; review every line and test in a non-production environment before applying."
SH = "Commands that delete, move or overwrite files can be destructive; read every generated command and dry-run it before using it on real data."
IAC = "Infrastructure changes can destroy resources and data; review every plan and test in a non-production environment before applying."

APP("hook_line", "Hook Line", "React components, hooks and re-renders, sorted", "Tools", ["#0E7490", "#F97316", "#7C3AED"], "spark",
 "Hook Line writes React components and custom hooks in your conventions, explains why things re-render, picks state management for your app and checks your JSX for accessibility.",
 "You are a senior React engineer: pragmatic, allergic to premature abstraction, and you always show the code first and the reasoning second.",
 "Ship components, not spinners", "Tell us your stack so every snippet matches your codebase.", ["Components and hooks in your conventions", "Re-render and performance diagnosis", "Accessibility checks on JSX"],
 [CH("lang", "Language", ["TypeScript", "JavaScript"], "TypeScript"), CH("framework", "Framework", ["Next.js", "Vite SPA", "Remix", "React Native", "Other"]), CH("styling", "Styling", ["Tailwind", "CSS Modules", "styled-components", "Plain CSS", "MUI/Chakra"]), TXT("conventions", "Conventions", "named exports, arrow components, no barrel files")],
 [T("build", "Build a component", "Describe it (or snap a mockup) → typed code", "🧩",
    [LONG("spec", "What it should do", "a paginated table with sortable columns, a loading state and an empty state"), PHOTO("Mockup or screenshot (optional)"), TXT("props", "Props it takes", "rows, onSort, pageSize")],
    "Write a React component for: {spec}, using the mockup photo for layout if one is attached. Props: {props}. Use the profile language, framework and styling. Sections: a quote containing the complete component code (typed props, accessible markup, no unused imports), a table of props (Prop | Type | Required | Description), bullets on the decisions made and the edge cases handled, and a callout on what to test first.",
    "quote, table, bullets, callout", "Build it", "Rendering…"),
  T("rerender", "Why does it re-render?", "Paste a component, get the culprit", "🔁",
    [LONG("code", "Component code", "paste the component and any hooks it uses"), TXT("symptom", "What you're seeing", "the list lags when I type in the search box")],
    "Diagnose rendering behaviour in: {code}. Symptom: {symptom}. Sections: text naming the root cause in two sentences, a table (Cause | Where in the code | Fix | Impact high/med/low), a quote with the corrected code for the single highest-impact fix, and a callout on when NOT to reach for useMemo or useCallback.",
    "text, table, quote, callout", "Diagnose", "Profiling…"),
  T("hook", "Extract a custom hook", "Turn effect soup into a reusable hook", "🪝",
    [LONG("code", "Code to refactor", "the useEffect/useState tangle from a component"), TXT("name", "Hook name", "useDebouncedSearch")],
    "Extract a custom hook called {name} from: {code}. Sections: a quote with the hook (typed parameters and return value, cleanup handled, stale-closure safe) followed by the component after adopting it, steps for the migration, bullets on what changed and why, and a callout on how to unit-test the hook in isolation.",
    "quote, steps, bullets, callout", "Extract", "Hooking…"),
  T("state", "Pick state management", "Context, Zustand, Redux or server state?", "🗂️",
    [LONG("app", "Describe the app and its state", "dashboard with auth, filters shared across pages, live prices via websocket"), CH("team", "Team size", ["Solo", "2–5", "6+"], "2–5")],
    "Recommend state management for: {app}, team size {team}, given the profile framework. Sections: a table (Piece of state | Category: server/URL/local/global | Recommended tool | Why), cards for the top 2 overall options (meta = bundle size · learning curve), a quote with a minimal store or provider setup for the winner, and a callout on the most common mistake with that choice.",
    "table, cards, quote, callout", "Recommend", "Weighing options…"),
  T("a11y", "Accessibility check", "JSX → what screen readers will hit", "♿",
    [LONG("jsx", "JSX to check", "paste a form, modal, menu or list")],
    "Audit the accessibility of: {jsx}. Sections: a table (Issue | Element | WCAG criterion | Severity), a quote with the corrected JSX, a checklist of keyboard interactions to verify by hand, and bullets on which ARIA attributes were unnecessary because native elements already cover them.",
    "table, quote, checklist, bullets", "Audit", "Reading the DOM…")])

APP("tidy_frame", "Tidy Frame", "pandas and polars code from a plain-English goal", "Tools", ["#306998", "#FFD43B", "#0F766E"], "graph",
 "Tidy Frame writes and fixes pandas or polars transformations, builds cleaning plans from a data sample, decodes tracebacks and turns chart descriptions into plotting code.",
 "You are a data engineer who lives in notebooks: vectorised, memory-aware, and you always show the expected output shape next to the code.",
 "Wrangle data without the doc-diving", "Your library and style shape every snippet.", ["Transforms written in your library", "Tracebacks decoded with a fix", "Cleaning plans from a sample"],
 [CH("lib", "Library", ["pandas", "polars", "Both"], "pandas"), CH("env", "Environment", ["Jupyter", "Script", "Databricks/Spark", "Colab"], "Jupyter"), CH("plot", "Plotting", ["matplotlib", "seaborn", "plotly", "altair"], "matplotlib"), TXT("domain", "Typical data", "sales orders, sensor logs, survey exports")],
 [T("transform", "Write the transform", "Columns + goal → code", "🧮",
    [LONG("columns", "Columns (name: dtype)", "order_id: int, customer: str, amount: float, ordered_at: datetime"), LONG("goal", "What you want", "monthly revenue per customer with a running total, top 10 customers only")],
    "Write a transform in the profile library. Input columns: {columns}. Goal: {goal}. Sections: a quote with the code (one function taking and returning a DataFrame, vectorised, no row loops), a table of the expected output columns (Column | dtype | Meaning), bullets on assumptions about nulls and duplicates, and a callout on the memory or performance trap to watch for.",
    "quote, table, bullets, callout", "Write it", "Vectorising…"),
  T("traceback", "Decode a traceback", "Paste the error, get the fix", "🧯",
    [LONG("error", "Traceback", "KeyError: 'amount' … or SettingWithCopyWarning"), TXT("code", "The line(s) that raised it", "df[df.x > 0]['y'] = 1")],
    "Explain and fix this error: {error}, raised by: {code}. Sections: text explaining the root cause in plain English in two sentences, steps to fix it, a quote with the corrected code, and a table of the errors people typically hit next in the same situation (Error | Cause | One-line fix).",
    "text, steps, quote, table", "Fix it", "Reading the stack…"),
  T("clean", "Clean my dataset", "Paste df.head() / df.info() → plan + code", "🧹",
    [LONG("sample", "Sample of the data", "output of df.head(10) and df.info(), or the first rows of the CSV"), TXT("purpose", "What it's for", "joining to a CRM export on email")],
    "Build a cleaning plan for this sample: {sample}, purpose: {purpose}. Sections: a table of problems found (Column | Problem | Evidence | Fix), a quote with a clean() function applying every fix in the profile library, a checklist of validation asserts to run after cleaning, and a callout on anything that needs a human decision before it is automated.",
    "table, quote, checklist, callout", "Plan cleaning", "Sniffing nulls…"),
  T("chart", "Chart it", "Describe the plot, get the code", "📈",
    [LONG("want", "What to show", "weekly signups by plan as stacked bars for the last 12 weeks, with a total line"), TXT("cols", "Columns involved", "week, plan, signups")],
    "Write plotting code with the profile plotting library for: {want}, using columns {cols}. Sections: a quote with the code (figure size, labelled axes, readable legend, saved to PNG), bullets on the reshaping needed before plotting, a kv (chart type, why it fits, what to avoid), and a callout on choosing a colour-blind-safe palette.",
    "quote, bullets, kv, callout", "Plot it", "Drawing axes…"),
  T("speed", "Speed it up", "Slow cell → fast cell", "⚡",
    [LONG("code", "Slow code", "for i, row in df.iterrows(): …"), NUM("rows", "Approximate row count", "2000000")],
    "Optimise this for roughly {rows} rows: {code}. Sections: a table (Bottleneck | Why it's slow | Replacement | Expected speed-up), a quote with the rewritten code, steps to benchmark before and after with %timeit or time.perf_counter, and a callout on when to move to polars, DuckDB or chunked processing instead.",
    "table, quote, steps, callout", "Optimise", "Dropping the loop…")])

APP("compose_kit", "Compose Kit", "Jetpack Compose UI, crashes and Gradle, solved", "Tools", ["#3DDC84", "#073042", "#F86734"], "bolt",
 "Compose Kit writes Jetpack Compose screens with proper state hoisting, decodes logcat crashes, lays out ViewModel and Flow architecture, untangles Gradle failures and preps Play releases.",
 "You are a senior Android engineer who follows the official architecture guidance, prefers Kotlin idioms over Java habits, and always considers configuration changes and process death.",
 "Build Android the modern way", "Your minSdk and libraries shape every snippet.", ["Compose screens with state hoisting", "Logcat crashes decoded", "Gradle errors untangled"],
 [NUM("minsdk", "minSdk", "26"), CH("di", "Dependency injection", ["Hilt", "Koin", "Manual", "None"], "Hilt"), CH("network", "Networking", ["Retrofit", "Ktor", "OkHttp only"], "Retrofit"), CH("db", "Local storage", ["Room", "DataStore", "SQLDelight", "None"], "Room")],
 [T("screen", "Build a screen", "Describe it (or snap a design) → composable", "📱",
    [LONG("spec", "Screen description", "login form with email/password, inline validation, a loading button and an error snackbar"), PHOTO("Design mockup (optional)"), CH("preview", "Include", ["Preview only", "Preview + ViewModel", "Preview + ViewModel + navigation"], "Preview + ViewModel")],
    "Write a Jetpack Compose screen for: {spec}, matching the attached mockup photo if there is one, including {preview}. Sections: a quote with the code (stateless composable taking a UiState and callbacks, a stateful wrapper, @Preview, Material 3 components, remember/rememberSaveable used correctly), a table of the UiState fields (Field | Type | Drives what), bullets on recomposition pitfalls avoided, and a callout on what happens on rotation and process death.",
    "quote, table, bullets, callout", "Compose it", "Recomposing…"),
  T("crash", "Decode a crash", "Paste logcat, get the cause", "💥",
    [LONG("logcat", "Stack trace / logcat", "FATAL EXCEPTION: main … java.lang.IllegalStateException"), TXT("when", "When it happens", "only after returning from the camera")],
    "Diagnose this Android crash: {logcat}, which happens {when}. Sections: text naming the cause in two sentences, a table (Frame | What it means | Suspect? yes/no), steps to fix it, a quote with the corrected Kotlin, and a checklist to reproduce and verify the fix on the profile minSdk.",
    "text, table, steps, quote, checklist", "Diagnose", "Reading logcat…"),
  T("arch", "Architect a feature", "ViewModel, Flow and repository layout", "🏗️",
    [LONG("feature", "Feature", "offline-first notes list synced to a REST API with conflict handling")],
    "Design the architecture for: {feature} using the profile DI, networking and storage choices. Sections: a table (Layer | Class | Responsibility | Depends on), a quote with the ViewModel exposing a single StateFlow<UiState> and handling one user action end to end, steps for the data flow from tap to screen, and a callout on the testability seams.",
    "table, quote, steps, callout", "Design it", "Layering…"),
  T("gradle", "Fix a Gradle error", "Build output → the real cause", "🐘",
    [LONG("output", "Build output", "Execution failed for task ':app:kaptDebugKotlin' …")],
    "Fix this Gradle build failure: {output}. Sections: text with the actual cause (ignore the noise), steps to fix it, a quote with the exact build.gradle.kts or libs.versions.toml lines to change, and a callout on plugin and library version combinations that commonly break together.",
    "text, steps, quote, callout", "Fix build", "Syncing Gradle…"),
  T("release", "Play release check", "Ship without a policy rejection", "🚀",
    [CH("type", "Release", ["First release", "Update", "Target SDK bump"], "Update"), TXT("perms", "Permissions used", "CAMERA, POST_NOTIFICATIONS, background location")],
    "Prepare a Play Store release checklist for a {type} that uses these permissions: {perms}. Sections: a checklist grouped by signing, target SDK, permission declarations, the Data safety form, and R8/ProGuard, a table of the listed permissions (Permission | Policy requirement | Declaration or form needed), and a callout on the top reasons apps like this get rejected.",
    "checklist, table, callout", "Check release", "Bundling…")])

APP("swift_sidekick", "Swift Sidekick", "SwiftUI, concurrency, crashes and App Review, handled", "Tools", ["#F05138", "#1C1C1E", "#5AC8FA"], "gear",
 "Swift Sidekick writes SwiftUI views and SwiftData models, reviews async/await code for actor mistakes, decodes crash logs and Xcode errors, and preps you for App Review.",
 "You are a senior iOS engineer: fluent in modern Swift concurrency and SwiftUI, opinionated about simplicity, and you flag anything that would fail App Review.",
 "Ship iOS without the Stack Overflow spiral", "Your deployment target and frameworks shape every answer.", ["SwiftUI views with previews", "Concurrency reviewed for data races", "App Review rejections avoided"],
 [TXT("target", "Deployment target", "iOS 17"), CH("ui", "UI framework", ["SwiftUI", "UIKit", "Mixed"], "SwiftUI"), CH("data", "Persistence", ["SwiftData", "Core Data", "Realm", "Files/UserDefaults"], "SwiftData"), CH("arch", "Architecture", ["MVVM", "TCA", "MV (plain SwiftUI)", "VIPER"], "MVVM")],
 [T("view", "Build a view", "Describe it (or snap a design) → SwiftUI + preview", "🧱",
    [LONG("spec", "View description", "settings screen with grouped sections, a toggle, a picker and a destructive sign-out row"), PHOTO("Design mockup (optional)"), TXT("model", "Data it shows", "User(name, email, plan)")],
    "Write a SwiftUI view for: {spec} showing {model}, matching the attached mockup photo if there is one and the profile architecture and target. Sections: a quote with the code (view, any view model or @Observable type, #Preview with sample data, Dynamic Type friendly, accessibility labels), a table (State | Wrapper: @State/@Binding/@Observable/@Environment | Why), bullets on layout decisions, and a callout on what changes if the profile UI framework is UIKit or Mixed.",
    "quote, table, bullets, callout", "Build view", "Laying out…"),
  T("concurrency", "Review my concurrency", "async/await, actors, MainActor", "🧵",
    [LONG("code", "Code", "paste the async code, tasks or actor")],
    "Review this Swift concurrency code: {code}. Sections: a table (Line or symbol | Problem: data race/MainActor/cancellation/retain cycle | Severity | Fix), a quote with the corrected code, bullets explaining each isolation decision, and a callout on what Swift 6 strict concurrency checking will flag.",
    "table, quote, bullets, callout", "Review", "Checking isolation…"),
  T("crash", "Decode a crash or error", "Crash log, Xcode error or console noise", "🛠️",
    [LONG("log", "Crash log / error text", "Thread 1: Fatal error: Unexpectedly found nil … or an Xcode build error"), TXT("context", "What you were doing", "tapping a cell right after pull-to-refresh")],
    "Diagnose: {log}, context: {context}. Sections: text naming the cause in two sentences, steps to fix it, a quote with the corrected Swift, and a checklist to reproduce and confirm the fix on both device and simulator.",
    "text, steps, quote, checklist", "Diagnose", "Symbolicating…"),
  T("model", "Design the data model", "Entities → SwiftData or Core Data", "🗃️",
    [LONG("entities", "Entities and relationships", "Trip has many Expenses; Expense has a Category; needs iCloud sync")],
    "Design a persistence model for: {entities} using the profile persistence choice. Sections: a table (Entity | Attributes | Relationships | Delete rule), a quote with the model code, steps for the first schema migration, and a callout on iCloud sync or threading gotchas for that store.",
    "table, quote, steps, callout", "Design model", "Modelling…"),
  T("review", "App Review prep", "Guidelines, privacy manifest, metadata", "🍎",
    [LONG("app", "What the app does", "subscription meditation app with account sign-in and HealthKit sleep import"), TXT("apis", "Sensitive APIs / SDKs", "HealthKit, Sign in with Apple, StoreKit, Firebase Analytics")],
    "Prepare an App Review checklist for: {app}, which uses {apis}. Sections: a checklist grouped by guidelines likely to apply, privacy manifest and nutrition labels, required-reason APIs, and metadata/screenshots, a table (Risk | Guideline | What reviewers look for | Fix), a quote with the review notes to paste into App Store Connect, and a callout on the most common rejection for this kind of app.",
    "checklist, table, quote, callout", "Prep review", "Reading guidelines…")])

APP("crate_mate", "Crate Mate", "Borrow errors explained, types designed, crates picked", "Tools", ["#B7410E", "#2B2B2B", "#DEA584"], "brain",
 "Crate Mate explains borrow-checker and lifetime errors with a working fix, designs idiomatic type models, recommends crates with trade-offs, ports code from other languages and decodes clippy.",
 "You are a patient Rustacean: you explain ownership in terms of who is responsible for the data, prefer the simplest lifetime-free design, and never reach for unsafe without justification.",
 "Make the borrow checker your friend", "Your edition and domain shape the advice.", ["Borrow and lifetime errors fixed", "Idiomatic type design", "Crate picks with trade-offs"],
 [CH("edition", "Edition", ["2021", "2024"], "2021"), CH("domain", "Building", ["CLI tools", "Web services", "Embedded", "Systems/OS", "WASM", "Game dev"]), CH("runtime", "Async runtime", ["tokio", "async-std", "smol", "None"], "tokio"), CH("level", "Rust experience", ["New", "Comfortable", "Advanced"], "Comfortable")],
 [T("borrow", "Fix a borrow error", "rustc error → why, and the fix", "🦀",
    [LONG("error", "Compiler error", "error[E0502]: cannot borrow `v` as mutable because it is also borrowed as immutable"), LONG("code", "The code", "the function or block it points at")],
    "Explain and fix: {error} in: {code}. Sections: text explaining in plain terms who owns what and why the compiler objects (three sentences, no jargon dump), a quote with the fixed code preferring restructuring over clone or Rc, a table of alternative fixes (Approach | When to use | Cost), and a callout on the general rule so it doesn't happen again.",
    "text, quote, table, callout", "Fix it", "Consulting rustc…"),
  T("types", "Design the types", "Domain → enums, structs, traits", "🧬",
    [LONG("domain", "Domain to model", "a payment that can be pending, settled or refunded; refunds reference the settlement")],
    "Model in idiomatic Rust: {domain}. Sections: a quote with the types (make illegal states unrepresentable with enums, newtypes for ids, sensible derives), a table (Type | Role | Key invariant), bullets on trait choices and why, and a callout on where lifetimes or generics were avoided on purpose.",
    "quote, table, bullets, callout", "Design types", "Deriving…"),
  T("crates", "Pick crates", "Task → crate shortlist with trade-offs", "📦",
    [TXT("need", "What you need", "HTTP client with retries and JSON", True), CH("priority", "Priority", ["Small binary", "Speed", "Ergonomics", "Minimal deps", "Well maintained"], "Well maintained")],
    "Recommend crates for: {need}, prioritising {priority}, for the profile domain and async runtime. Sections: a table (Crate | Fit | Maturity | Trade-off), a quote with the Cargo.toml lines and a 15-line usage example for the top pick, and a callout on licence or maintenance red flags to check on crates.io.",
    "table, quote, callout", "Recommend", "Browsing crates.io…"),
  T("port", "Port to Rust", "Python, Go, C or TS → idiomatic Rust", "🔁",
    [LONG("source", "Source code", "paste the function or module"), CH("from", "From", ["Python", "Go", "C/C++", "TypeScript", "Java/Kotlin"], "Python")],
    "Port this {from} code to idiomatic Rust: {source}. Sections: a quote with the Rust version (Result-based errors, iterators over index loops, no unwrap in library code), a table (Original construct | Rust equivalent | Note), bullets on behaviour differences (integer overflow, unicode, nulls, exceptions), and a callout on what to test first.",
    "quote, table, bullets, callout", "Port it", "Rewriting…"),
  T("clippy", "Explain clippy", "Warnings → what they mean and whether to care", "🔧",
    [LONG("warnings", "cargo clippy output", "warning: this `.map` can be written more concisely …")],
    "Explain these clippy warnings: {warnings}. Sections: a table (Lint | Meaning | Fix | Worth it? yes/no/style), a quote with the fixed code for the ones worth fixing, and a callout on which lints are reasonable to allow and how to do that at crate or item level.",
    "table, quote, callout", "Explain", "Reading lints…")])

APP("pod_pilot", "Pod Pilot", "Manifests, crashing pods and pipelines, sorted", "Tools", ["#326CE5", "#FF6B35", "#14B8A6"], "globe",
 "Pod Pilot writes Kubernetes manifests with sane limits and probes, diagnoses crashing or pending pods from kubectl output, slims Dockerfiles, drafts CI pipelines and writes on-call runbooks.",
 "You are an SRE who has been paged too many times: you write boring, explicit YAML, always set resource requests, and treat production changes as a checklist.",
 "Keep the cluster boring", "Your platform and CI shape every manifest.", ["Manifests with limits and probes", "Pod crash diagnosis", "CI pipelines and runbooks"],
 [CH("platform", "Cluster", ["EKS", "GKE", "AKS", "k3s/kind", "OpenShift", "Other"]), CH("ci", "CI", ["GitHub Actions", "GitLab CI", "Jenkins", "Argo/Tekton", "CircleCI"], "GitHub Actions"), CH("packaging", "Packaging", ["Plain YAML", "Helm", "Kustomize"], "Helm"), TXT("stack", "Typical services", "Node APIs, Postgres, Redis")],
 [T("manifest", "Write a manifest", "Service → Deployment, Service, Ingress", "📄",
    [LONG("service", "Service description", "Node API on port 3000, needs a DATABASE_URL secret, 2 replicas, public at api.example.com"), CH("extras", "Include", ["HPA", "PodDisruptionBudget", "NetworkPolicy", "ConfigMap"], multi=True)],
    "Write Kubernetes manifests for: {service}, including {extras}, in the profile packaging style. Sections: a quote with the complete YAML (requests and limits, liveness and readiness probes, non-root securityContext, consistent labels), a table (Setting | Value chosen | Why), a checklist to apply and verify it, and a callout on the value most likely to need tuning.",
    "quote, table, checklist, callout", "Write YAML", "Indenting…"),
  T("crash", "Why is my pod broken?", "kubectl describe / logs → cause", "🚑",
    [LONG("output", "kubectl output", "paste kubectl describe pod and the last logs"), TXT("status", "Pod status", "CrashLoopBackOff / Pending / ImagePullBackOff / OOMKilled")],
    "Diagnose a pod in {status} from: {output}. Sections: text naming the cause in two sentences, steps to confirm it with exact kubectl commands, a quote with the fix (a YAML patch or command), and a table of other common causes of {status} (Cause | How to spot it | Fix).",
    "text, steps, quote, table", "Diagnose", "Describing pod…"),
  T("docker", "Slim my Dockerfile", "Smaller, faster, safer image", "🐳",
    [LONG("dockerfile", "Dockerfile", "paste it")],
    "Review and rewrite this Dockerfile: {dockerfile}. Sections: a table (Line | Problem: size/cache/security/reproducibility | Fix), a quote with the rewritten multi-stage Dockerfile (pinned base image, non-root user, layer order for cache hits, .dockerignore noted), a kv (estimated size before, estimated size after, build-time change), and a callout on secrets that must never be baked into layers.",
    "table, quote, kv, callout", "Slim it", "Squashing layers…"),
  T("pipeline", "Draft a CI pipeline", "Build, test, scan, deploy", "🔄",
    [LONG("steps", "What it should do", "run tests, build the image, push to ECR, deploy to staging on main"), CH("deploy", "Deploy via", ["kubectl apply", "Helm upgrade", "Argo CD sync", "None"], "Helm upgrade")],
    "Write a pipeline for the profile CI that does: {steps}, deploying via {deploy}. Sections: a quote with the complete pipeline file (dependency caching, least-privilege permissions, image tagged by git SHA), a table (Job | Trigger | Secrets needed | Approx. duration), bullets on what would make it flaky, and a callout on protecting the deploy step with environments or approvals.",
    "quote, table, bullets, callout", "Draft pipeline", "Queuing jobs…"),
  T("runbook", "Write a runbook", "Alert → what on-call does at 3am", "📟",
    [TXT("alert", "Alert or symptom", "p95 latency > 2s on the checkout service", True), TXT("arch", "Relevant architecture", "API → Redis cache → Postgres on RDS")],
    "Write an on-call runbook for: {alert}, architecture: {arch}. Sections: a checklist for the first 5 minutes (exact commands and dashboards to check), a table (Hypothesis | How to confirm | Mitigation | Rollback), steps for escalation and communication, and a quote with a status-page update template.",
    "checklist, table, steps, quote", "Write runbook", "Paging…")], OPS)

APP("pipe_wrench", "Pipe Wrench", "Shell scripts and one-liners you can trust", "Tools", ["#14532D", "#4ADE80", "#FBBF24"], "wrench",
 "Pipe Wrench writes robust bash and zsh scripts, explains cryptic pipelines flag by flag, reviews scripts for ShellCheck-style hazards, builds awk/sed/jq one-liners and schedules jobs properly.",
 "You are a grizzled Unix sysadmin: you quote every variable, fail fast, prefer POSIX where it matters and explain what each flag does.",
 "Stop copy-pasting mystery commands", "Your shell and OS shape every command.", ["Scripts with error handling built in", "Pipelines explained flag by flag", "Hazard review before you run it"],
 [CH("shell", "Shell", ["bash", "zsh", "POSIX sh", "fish"], "bash"), CH("os", "OS", ["Linux", "macOS", "WSL", "BSD"], "Linux"), CH("tools", "Tools on hand", ["jq", "ripgrep", "fd", "GNU coreutils", "BusyBox"], multi=True)],
 [T("script", "Write a script", "Goal → robust script with usage", "📜",
    [LONG("goal", "What it should do", "back up ~/projects to an external drive, skip node_modules, keep 7 versions"), TXT("args", "Arguments / flags", "--dry-run, target directory")],
    "Write a script in the profile shell for: {goal} with arguments: {args}. Sections: a quote with the complete script (strict mode, a usage() function with exit codes, quoted variables, a trap for cleanup, no useless cat), a table (Flag | Meaning | Default), steps to test it safely, and a callout on the destructive step and how the dry-run protects it.",
    "quote, table, steps, callout", "Write script", "Quoting variables…"),
  T("explain", "Explain this command", "Pipeline → flag-by-flag breakdown", "🔍",
    [LONG("cmd", "Command", "find . -type f -mtime +30 -print0 | xargs -0 rm -f")],
    "Explain: {cmd}. Sections: text with a one-sentence plain-English summary, a table (Part | What it does | Flags explained), a callout on anything dangerous or surprising (globbing, spaces in filenames, exit codes), and bullets on a safer or more portable equivalent for the profile OS.",
    "text, table, callout, bullets", "Explain", "Parsing…"),
  T("review", "Review my script", "ShellCheck-style hazard hunt", "🧪",
    [LONG("script", "Script", "paste the script")],
    "Review this shell script for hazards: {script}. Sections: a table (Line | Issue | Severity | Fix) covering quoting, word splitting, unchecked exit codes, temp files, race conditions and portability, a quote with the corrected script, and a checklist of edge cases to test (empty input, spaces in names, missing tools, no permission).",
    "table, quote, checklist", "Review", "Linting…"),
  T("oneliner", "One-liner", "awk, sed, jq, find, xargs", "🧵",
    [LONG("task", "Task", "print column 3 of a CSV where column 5 is 'failed', then sum column 7"), TXT("input", "Input sample", "a couple of lines of the file")],
    "Build a one-liner for: {task} on input like: {input}, using the profile tools where available. Sections: a quote with the one-liner, a table of alternatives (Tool | Command | When it's better), steps to verify it on the sample, and a callout on the classic gotcha for that tool (locale, GNU vs BSD flags, CSV quoting).",
    "quote, table, steps, callout", "Build it", "Piping…"),
  T("cron", "Schedule it", "cron, systemd timers, launchd", "⏰",
    [TXT("when", "When", "every weekday at 02:30", True), TXT("what", "What to run", "/usr/local/bin/backup.sh")],
    "Schedule {what} to run {when} on the profile OS. Sections: a quote with the crontab line and the systemd timer or launchd plist alternative, a kv (log file location, lock to prevent overlapping runs, PATH and environment handling, notification on failure), steps to install and verify the first run, and a callout on the timezone and daylight-saving trap.",
    "quote, kv, steps, callout", "Schedule", "Reading crontab…")], SH)

APP("test_bench", "Test Bench", "Tests written, flakes fixed, gaps found", "Tools", ["#16A34A", "#DC2626", "#2563EB"], "shield",
 "Test Bench writes unit and integration tests in your framework, diagnoses flaky tests, plans coverage for a feature, designs test doubles and finds the cases your suite misses.",
 "You are a test engineer who values fast, deterministic tests: one behaviour per test, clear names, no sleeps, and mocks only at real boundaries.",
 "Red, green, refactor, faster", "Your language and framework shape every test.", ["Tests in your framework, edge cases included", "Flaky test diagnosis", "Coverage gap hunting"],
 [CH("lang", "Language", ["TypeScript/JS", "Python", "Kotlin/Java", "Swift", "Go", "Rust", "C#"], "TypeScript/JS"), TXT("framework", "Test framework", "Vitest + Testing Library / pytest / JUnit 5"), CH("style", "Naming", ["describe/it", "should_do_x_when_y", "Given-When-Then", "test_x"], "describe/it")],
 [T("write", "Write tests for this", "Paste code → tests with edge cases", "✅",
    [LONG("code", "Code under test", "paste a function, class or component"), CH("kind", "Test kind", ["Unit", "Integration", "Component/UI", "Property-based"], "Unit")],
    "Write {kind} tests for: {code} in the profile language, framework and naming style. Sections: a table of cases first (Case | Input | Expected | Category: happy/edge/error), a quote with the complete test file (arrange-act-assert, no shared mutable state, parametrised where it helps), bullets on what was deliberately not tested and why, and a callout on any refactor that would make the code easier to test.",
    "table, quote, bullets, callout", "Write tests", "Going green…"),
  T("flaky", "Fix a flaky test", "Intermittent failure → root cause", "🎲",
    [LONG("test", "The test", "paste the test and the failure output"), TXT("freq", "How often it fails", "1 in 20 runs, mostly on CI")],
    "Diagnose flakiness in: {test}, failing {freq}. Sections: a table (Suspect | Evidence in the test | Likelihood high/med/low) covering timing, ordering, shared state, real network or clock, and resource leaks, a quote with the deflaked test, steps to prove it is fixed (run it N times, stress it on CI), and a callout on why automatic retries are not a fix.",
    "table, quote, steps, callout", "Deflake", "Rolling the dice…"),
  T("plan", "Plan the tests", "Feature → test plan with priorities", "🗺️",
    [LONG("feature", "Feature or story", "users can reset their password via an emailed link that expires in 15 minutes")],
    "Write a test plan for: {feature}. Sections: a table (Scenario | Level: unit/integration/e2e | Priority P0–P2 | Data needed), a checklist of non-functional checks (security, accessibility, performance, i18n), bullets on what to automate versus test manually once, and a callout on the riskiest path.",
    "table, checklist, bullets, callout", "Plan tests", "Mapping cases…"),
  T("mock", "Mock it properly", "Dependency → test double strategy", "🎭",
    [TXT("dep", "Dependency to isolate", "Stripe client / system clock / Postgres repository", True), TXT("code", "Code that uses it", "paste the caller if you have it")],
    "Design test doubles for {dep} as used by: {code} in the profile framework. Sections: a table (Option: fake/stub/mock/spy/real-in-container | Fits when | Cost), a quote with the recommended double and one test using it, bullets on the interface seam to introduce if none exists, and a callout on the symptoms of over-mocking.",
    "table, quote, bullets, callout", "Design double", "Faking it…"),
  T("gaps", "Find coverage gaps", "Code + tests → what's missing", "🕳️",
    [LONG("code", "Code", "paste the module"), LONG("tests", "Existing tests", "paste the current test file", False)],
    "Compare {code} against the existing tests: {tests}. Sections: a checklist of untested behaviours (branches, error paths, boundaries, concurrency), a table (Gap | Risk if it breaks | Test to add), a quote with the two most valuable missing tests written out in the profile framework, and a callout on any existing test that asserts nothing useful.",
    "checklist, table, quote, callout", "Find gaps", "Tracing branches…")])

APP("type_foundry", "Type Foundry", "TypeScript errors decoded, types designed, JS migrated", "Tools", ["#3178C6", "#F7B500", "#0F766E"], "bulb",
 "Type Foundry decodes TS2xxx errors, designs precise types and generics, writes runtime validators that match them, migrates JavaScript files safely and tunes tsconfig for strictness.",
 "You are a TypeScript specialist: you prefer inference over annotation and unions over enums, and you never type anything as any without saying why.",
 "Make the compiler work for you", "Your runtime and strictness shape the advice.", ["Compiler errors in plain English", "Types that catch real bugs", "JS → TS migration plans"],
 [CH("runtime", "Runtime", ["Node", "Browser", "Deno/Bun", "Both"], "Node"), CH("strict", "Strictness", ["strict: true", "Partial", "Loose/legacy"], "strict: true"), CH("validation", "Runtime validation", ["zod", "valibot", "io-ts", "None"], "zod"), TXT("tsver", "TypeScript version", "5.x")],
 [T("error", "Decode an error", "TS2345 → what it means and the fix", "🚨",
    [LONG("error", "Compiler error", "Type 'string | undefined' is not assignable to type 'string'"), LONG("code", "The code", "the lines it points at", False)],
    "Explain and fix: {error} in: {code}. Sections: text translating the error into plain English in two sentences, a quote with the fixed code preferring narrowing over assertions, a table of alternatives (Fix | When to use | Risk), and a callout on why 'as' or '!' would hide a real bug here.",
    "text, quote, table, callout", "Decode", "Reading TS2345…"),
  T("design", "Design the types", "Domain → discriminated unions, generics", "🏛️",
    [LONG("domain", "What to model", "an API response that is loading, success with data, or error with a code; plus paginated variants")],
    "Design TypeScript types for: {domain}. Sections: a quote with the types (discriminated unions, readonly where sensible, branded ids if useful, generics only where they earn it), a table (Type | Purpose | Example value), bullets on the specific bugs these types prevent, and a callout on the exhaustiveness-check pattern to add.",
    "quote, table, bullets, callout", "Design", "Narrowing…"),
  T("validate", "Types meet runtime", "One schema → validator and type", "🛡️",
    [LONG("shape", "Data shape", "user: { id: uuid, email, role: 'admin' | 'member', createdAt: ISO date }"), CH("source", "Data comes from", ["HTTP API", "Form input", "Env vars", "Database rows", "Message queue"], "HTTP API")],
    "Write a validator for {shape} arriving from {source} using the profile validation library. Sections: a quote with the schema, the inferred type and a parse function returning a typed result, a table (Field | Rule | Error message), bullets on coercion decisions (dates, numbers from strings, trimming), and a callout on validating at the boundary only.",
    "quote, table, bullets, callout", "Write schema", "Parsing…"),
  T("migrate", "Migrate a JS file", "JavaScript → TypeScript safely", "🚚",
    [LONG("js", "JavaScript code", "paste the module")],
    "Convert this JavaScript to TypeScript at the profile strictness: {js}. Sections: a quote with the converted file (inferred where possible, unknown over any, JSDoc turned into types), a table (Symbol | Type given | Confidence high/med/low | Note), steps for a file-by-file migration order in a larger codebase, and a callout on the allowJs/checkJs staging trick.",
    "quote, table, steps, callout", "Convert", "Annotating…"),
  T("config", "Tune tsconfig", "Flags explained, strictness roadmap", "⚙️",
    [LONG("tsconfig", "Current tsconfig.json", "paste it", False), TXT("goal", "Goal", "get to strict without breaking the build")],
    "Review {tsconfig} against the goal: {goal} for the profile runtime and version. Sections: a table (Option | Current | Recommended | Why), a quote with the updated tsconfig.json, steps to enable strict flags one at a time in the safest order, and a callout on the flags that change emitted JavaScript rather than just type-checking.",
    "table, quote, steps, callout", "Tune it", "Flipping flags…")])

APP("plan_apply", "Plan Apply", "Terraform modules, plans and state, without the fear", "Tools", ["#7B42BC", "#F59E0B", "#0891B2"], "pin",
 "Plan Apply writes Terraform and OpenTofu modules, explains what a plan will really change, guides state surgery like imports and moves, reviews code for cost and security and resolves drift.",
 "You are a platform engineer who treats apply like surgery: explicit, reversible where possible, and always reading the plan out loud before saying yes.",
 "Read the plan before you apply", "Your cloud and workflow shape every module.", ["Modules with variables and outputs", "Plan output explained change by change", "State surgery step by step"],
 [CH("cloud", "Cloud", ["AWS", "GCP", "Azure", "Cloudflare", "Multi"], "AWS"), CH("tool", "Tool", ["Terraform", "OpenTofu", "Terragrunt"], "Terraform"), CH("backend", "State backend", ["S3 + lock", "GCS", "Azure Blob", "Terraform Cloud", "Local"], "S3 + lock"), TXT("env", "Environments", "dev, staging, prod via workspaces")],
 [T("module", "Write a module", "Resource → module with variables", "🧱",
    [LONG("want", "What to provision", "private S3 bucket with versioning, KMS, lifecycle to Glacier after 90 days, access from one IAM role"), CH("form", "Deliver as", ["Single module", "Root + child module", "Example usage only"], "Single module")],
    "Write infrastructure code for: {want} as {form}, for the profile cloud and tool. Sections: a quote with the code (variables with types, descriptions and validation, outputs, tags, no hard-coded secrets, provider version pinned), a table (Variable | Type | Default | Purpose), a checklist to init, plan and apply safely, and a callout on the security setting people most often get wrong for this resource.",
    "quote, table, checklist, callout", "Write module", "Declaring…"),
  T("plan", "Explain this plan", "plan output → what really changes", "🔎",
    [LONG("plan", "Plan output", "paste the terraform plan output")],
    "Explain this plan: {plan}. Sections: a kv (add, change, destroy and replace counts, plus the blast radius in one line), a table (Resource | Action | Why it's happening | Data-loss risk yes/no), a callout on any forced replacement or destroy that should stop the apply, and steps to make the change safer (lifecycle rules, targeted apply, moved blocks).",
    "kv, table, callout, steps", "Explain plan", "Reading the diff…"),
  T("state", "State surgery", "Import, move, rename, split state", "🩺",
    [TXT("op", "Operation", "import an existing RDS instance / rename a module / split prod into its own state", True), TXT("details", "Resource addresses / ids", "module.db.aws_db_instance.main, db-prod-1")],
    "Guide this state operation: {op} with {details} on the profile backend and tool. Sections: steps with exact commands (back up the state first, use moved or import blocks where the version supports them), a quote with the HCL blocks, a checklist to verify that plan shows no changes afterwards, and a callout on what to do if it goes wrong midway.",
    "steps, quote, checklist, callout", "Guide me", "Locking state…"),
  T("review", "Review for cost & security", "HCL → findings before the PR", "🛡️",
    [LONG("hcl", "Terraform code", "paste the module or file"), CH("focus", "Focus", ["Security", "Cost", "Both"], "Both")],
    "Review {hcl} with focus on {focus}. Sections: a table (Line or resource | Finding | Severity | Fix), a kv of the estimated monthly cost drivers and the cheapest sensible alternative for each, a quote with the corrected snippets, and a callout on what a policy-as-code check (tfsec, checkov, OPA) would block.",
    "table, kv, quote, callout", "Review", "Scanning HCL…"),
  T("drift", "Resolve drift", "Reality differs from the code", "🌀",
    [LONG("symptom", "What's different", "someone changed the security group in the console; plan wants to revert it"), CH("truth", "Source of truth should be", ["Code (revert reality)", "Reality (update code)", "Decide per change"], "Decide per change")],
    "Handle drift: {symptom}, where the source of truth should be {truth}. Sections: steps to detect and list every drifted attribute with exact commands, a table (Attribute | In code | In reality | Recommended action), a quote with the code changes or ignore_changes blocks needed, and a callout on preventing recurrence (permissions, plan checks in CI, scheduled drift detection).",
    "steps, table, quote, callout", "Resolve", "Refreshing state…")], IAC)
