from dsl import *

STATS = "Statistical estimates here are approximations; confirm with your experimentation platform or a statistician before high-stakes or revenue-affecting decisions."
FCST = "Forecasts are estimates from the numbers you provide, not financial or business advice; validate before committing money, staff or stock."

# 1 ── Spreadsheet analysis (answers from data; distinct from Sheet Wizard's formula writing)
APP("pivot_pilot", "Pivot Pilot", "Answers from your spreadsheet, not just formulas", "Tools", ["#1B5E20", "#00897B", "#FFB300"], "graph",
 "Pivot Pilot reads a pasted table or CSV and tells you what it says: summary stats, the pivot that answers your question, outliers worth checking and what-if scenarios, all in Excel or Google Sheets terms.",
 "You are a sharp, plain-spoken spreadsheet analyst who works in Excel and Google Sheets, shows the numbers behind every claim and says clearly when the data cannot answer the question.",
 "Paste a table, get the story", "Tell us which spreadsheet you use and what your data is usually about.", ["Findings from pasted data, with numbers", "Pivot tables designed for your question", "Outliers and what-ifs, explained"],
 [NAME, CH("tool", "Spreadsheet", ["Excel", "Google Sheets", "LibreOffice", "Numbers"], "Excel"), CH("level", "Comfort level", ["Beginner", "Comfortable", "Power user"], "Comfortable"), TXT("domain", "Your data is usually about", "sales, inventory, HR…")],
 [T("analyse", "Analyse my table", "Paste rows → what they say", "🔎", [LONG("data", "Paste your data (CSV or tab-separated, with headers)", "date,region,units,revenue\n2024-01-03,North,12,480…"), TXT("question", "What do you want to know?", "which region is slipping?")],
    "Analyse this data: {data}. The user's question: {question}. Produce a table 'Summary' (Column | Type | Min | Max | Mean or top value | Missing) covering every column, then bullets with the 5 most important findings each backed by a specific number, a kv 'Answer' (Answer, Confidence, Caveat) addressing the question directly, and a callout naming what this data cannot answer and which extra column would fix that.", "table, bullets, kv, callout", "Analyse", "Reading the rows…"),
  T("pivot", "Design a pivot", "Question → rows, columns, values", "🧮", [TXT("columns", "Column headers you have", "Date, Rep, Product, Region, Units, Revenue", True), TXT("question", "Question to answer", "revenue by product per quarter", True)],
    "Design the pivot table that answers '{question}' from the columns {columns} in the profile's spreadsheet tool. Sections: kv (Rows, Columns, Values with aggregation, Filters, Sort), steps to build it click-by-click in that tool, a quote with the equivalent single formula (SUMIFS, QUERY or GROUPBY as appropriate), and bullets of 3 follow-up pivots that usually come next.", "kv, steps, quote, bullets", "Design pivot", "Arranging fields…"),
  T("outliers", "Hunt for outliers", "Find the rows that don't belong", "🎯", [LONG("data", "Paste the column(s) to check", "order_id,amount\n1001,45.00\n1002,4500.00…"), CH("method", "Sensitivity", ["Strict", "Balanced", "Loose"], "Balanced")],
    "Check {data} for outliers and anomalies at '{method}' sensitivity. Table 'Flagged' (Row | Value | Why flagged | Likely cause | Action), a kv of the thresholds used (method, lower bound, upper bound, count flagged, % of rows), a checklist of verification steps to complete before deleting anything, and a callout on flagged values that are probably real and should be kept.", "table, kv, checklist, callout", "Find outliers", "Scanning rows…"),
  T("whatif", "What-if scenario", "Change an assumption, see the effect", "🔮", [LONG("model", "Current numbers", "price 20, units 1500/month, unit cost 8, fixed costs 10000"), TXT("change", "What changes?", "price up 10%, units drop 5%", True)],
    "Starting from {model}, apply the scenario '{change}'. Table 'Scenario' (Metric | Now | After | Change | % change), text explaining the mechanics in 3 sentences, bullets of 3 alternative scenarios worth testing next, and a quote with the Excel/Sheets formula to build a one-variable data table for this.", "table, text, bullets, quote", "Run scenario", "Crunching…"),
  T("audit", "Audit a screenshot", "Photo of a sheet → problems", "📷", [PHOTO("Screenshot of the spreadsheet", "", True)],
    "Review the spreadsheet in the photo. Table 'Issues' (Cell/Area | Problem | Risk | Fix), bullets on layout improvements (headers, freeze panes, number formats, named ranges, hard-coded numbers), a checklist for making it safe to share, and a callout on the single change that reduces errors most.", "table, bullets, checklist, callout", "Audit sheet", "Zooming in…")])

# 2 ── Data cleaning
APP("tidy_rows", "Tidy Rows", "Messy exports into clean, trustworthy data", "Tools", ["#37474F", "#FF7043", "#26C6DA"], "wrench",
 "Tidy Rows turns messy CSV exports into clean data: it diagnoses what's wrong, writes the cleaning recipe for your tool, designs validation rules and merges duplicate records without losing information.",
 "You are a meticulous data-cleaning specialist: you never guess, you show before/after examples, and you flag every transformation that could silently lose information.",
 "Clean data, no regrets", "Tell us where the mess comes from and what you clean it with.", ["Diagnose messy columns instantly", "Recipes for Sheets, Excel, pandas, SQL or Power Query", "Dedupe rules that keep the right record"],
 [CH("tool", "Cleaning tool", ["Excel", "Google Sheets", "Python (pandas)", "SQL", "Power Query"], "Google Sheets"), TXT("sources", "Usual data sources", "Shopify export, HubSpot CSV, bank statements"), CH("volume", "Typical size", ["Under 1k rows", "1k–100k rows", "Over 100k rows"], "1k–100k rows")],
 [T("diagnose", "Diagnose my data", "Paste a sample → every problem", "🩺", [LONG("sample", "Paste 20–50 sample rows with headers", "name,email,signup_date,plan\nJohn  Smith,JOHN@x.com,3/4/24,pro…")],
    "Diagnose the data quality of {sample}. Table 'Problems' (Column | Problem | Example value | Rows affected (est.) | Severity), a kv 'Detected formats' (dates, numbers, text case, encoding, delimiter, missing-value markers), a checklist of cleaning tasks ordered by impact, and a callout on anything that looks like a hidden data-loss risk (truncated IDs, dropped leading zeros, timezone shifts, Excel auto-dates).", "table, kv, checklist, callout", "Diagnose", "Inspecting cells…"),
  T("recipe", "Write the cleaning recipe", "Steps, formulas or code for your tool", "🧪", [LONG("problems", "What needs fixing", "mixed date formats, trailing spaces in names, 'N/A' in numeric columns"), CH("output", "Deliver as", ["Step-by-step clicks", "Formulas", "Code"], "Formulas")],
    "Write a cleaning recipe for these problems: {problems}, delivered as {output} for the profile's tool and data volume. Steps in the order to run them (each step says what it changes and how to verify it), a quote containing the exact formulas or code, a table 'Before → After' (Problem | Example before | Example after), and a callout on the steps that are irreversible and must run on a copy.", "steps, quote, table, callout", "Write recipe", "Mixing formulas…"),
  T("dedupe", "Dedupe rules", "Merge duplicates without losing data", "👥", [TXT("entity", "What each row represents", "customers", True), TXT("fields", "Fields available", "name, email, phone, company, created_at", True)],
    "Design a deduplication strategy for {entity} rows with fields {fields}. Table 'Match rules' (Rule | Fields compared | Normalisation applied | Confidence), kv 'Survivor rules' (which record wins, how each field is merged, what to keep from the losers), steps to run it in the profile's tool, and a callout on false-merge risks (shared emails, family members, franchises, test accounts).", "table, kv, steps, callout", "Design rules", "Matching pairs…"),
  T("validate", "Validation rules", "Stop bad data at the door", "🛡️", [LONG("schema", "Columns and what they should contain", "order_id: 8 digits; email: valid address; qty: 1–999; country: ISO-2 code")],
    "Write validation rules for {schema}. Table 'Rules' (Column | Rule | Error message | Example value that fails), a quote with the data-validation formulas, regex or constraints for the profile's tool, a checklist of columns still lacking a rule, and bullets on handling rows that fail (quarantine sheet, alert, fix-forward).", "table, quote, checklist, bullets", "Write rules", "Building guards…"),
  T("photo", "Read a messy sheet", "Photo → what to fix first", "📷", [PHOTO("Photo or screenshot of the data", "", True)],
    "From the photo, catalogue the visible data-quality problems as a table (Area | Problem | Fix), bullets on restructuring it into a tidy one-row-per-record layout with one value per cell, and steps for the first 15 minutes of clean-up.", "table, bullets, steps", "Read sheet", "Squinting…")])

# 3 ── Chart design
APP("chart_tailor", "Chart Tailor", "The right chart, styled so the point lands", "Tools", ["#AD1457", "#00ACC1", "#FDD835"], "spark",
 "Chart Tailor picks the chart type that answers your question, redesigns your existing chart from a screenshot, builds colour-blind-safe palettes from your brand and writes the titles and annotations that make the point obvious.",
 "You are a data-visualisation designer: minimal ink, honest axes, one message per chart, and always practical about what Excel, Sheets, Power BI or Python can actually draw.",
 "Make charts people understand", "Tell us your tools and brand so every suggestion is buildable.", ["Chart type chosen for the question", "Redesigns from a screenshot", "Colour-blind-safe palettes from your brand"],
 [CH("tool", "Charting tools", ["Excel", "Google Sheets", "Power BI", "Tableau", "Python", "Looker Studio"], "Excel", multi=True), TXT("brand", "Brand colours (hex)", "#1E88E5, #F4511E"), CH("audience", "Usual audience", ["Executives", "Analysts", "Customers", "General public"], "Executives")],
 [T("pick", "Which chart?", "Describe the data and the point", "📊", [TXT("data", "Data shape", "monthly revenue for 5 products over 2 years", True), TXT("message", "The point you want to make", "product C is overtaking product A", True)],
    "Recommend the chart for {data} to show '{message}'. Cards for the top 3 chart types (meta = best for · build effort), then a kv 'Recommended build' (chart type, x-axis, y-axis, series, sort order, what to hide), bullets of chart types to avoid here and why, and a callout on the one design choice that most decides whether the message lands.", "cards, kv, bullets, callout", "Pick chart", "Sketching…"),
  T("redesign", "Redesign my chart", "Screenshot → concrete fixes", "📷", [PHOTO("Screenshot of your chart", "", True), TXT("goal", "What should the viewer take away?", "that costs are flat while revenue grows")],
    "Critique the chart in the screenshot against the goal '{goal}'. Table 'Fixes' (Element | Now | Change to | Why), steps to rebuild it in the profile's tool, a quote with a better title and subtitle, and a callout on anything misleading (truncated axis, dual axes, 3D, rainbow colours, cherry-picked range).", "table, steps, quote, callout", "Redesign", "Measuring ink…"),
  T("palette", "Colour palette", "Accessible colours that match your brand", "🎨", [CH("kind", "Palette type", ["Categorical", "Sequential", "Diverging", "Highlight one series"], "Categorical"), NUM("count", "Number of colours", "5")],
    "Build a {kind} palette of {count} colours starting from the profile's brand colours. Table 'Palette' (Role | Hex | Use for | Contrast on white), kv (colour-blind safety verdict, grey for context series, highlight colour, text colour), a quote with the hex list ready to paste into the profile's tool, and bullets on when to break the palette.", "table, kv, quote, bullets", "Build palette", "Mixing colours…"),
  T("annotate", "Title & annotations", "Words that make the chart self-explanatory", "✍️", [TXT("chart", "What the chart shows", "weekly signups, spike in March after launch", True), TXT("insight", "The insight", "launch doubled signups but the effect faded in 6 weeks")],
    "Write the text layer for a chart showing {chart} with the insight '{insight}'. Quote with 3 takeaway-style headline titles (not descriptive ones), kv (subtitle, axis titles, units, source line, footnote), bullets naming exactly which points to annotate and what each label says, and a callout on jargon to remove for the profile's audience.", "quote, kv, bullets, callout", "Write labels", "Wording it…"),
  T("chartset", "Chart set for a report", "Which charts, in what order", "🗂️", [LONG("metrics", "Metrics to show", "MRR, churn, new customers by channel, NPS")],
    "Plan the charts for a report covering {metrics}. Table 'Charts' (Order | Metric | Chart type | Comparison shown | Size), text on the narrative order in 3 sentences, a checklist of consistency rules (same colour per series, shared axes, date formats, sorting), and a callout on the metrics that should be a single big number rather than a chart.", "table, text, checklist, callout", "Plan charts", "Laying out…")])

# 4 ── Survey design
APP("survey_smith", "Survey Smith", "Surveys people finish and answers you can trust", "Business", ["#6A1B9A", "#FFA000", "#00ACC1"], "note",
 "Survey Smith writes questionnaires from your research goal, rewrites leading or confusing questions, sizes your sample, themes open-ended answers and drafts invitations that lift response rates.",
 "You are a survey methodologist: obsessed with unbiased wording, short questionnaires and honest interpretation; you say plainly when a survey is the wrong tool.",
 "Ask better questions", "Tell us who you survey and where you run it.", ["Questionnaires from goals in minutes", "Bias-free rewrites of your questions", "Themes and quotes from open answers"],
 [NAME, CH("platform", "Survey platform", ["Google Forms", "Typeform", "SurveyMonkey", "Qualtrics", "Microsoft Forms", "Other"], "Google Forms"), CH("audience", "Usual respondents", ["Customers", "Employees", "Students", "General public", "Event attendees"], "Customers")],
 [T("write", "Write my survey", "Goal → full questionnaire", "📝", [LONG("goal", "What decision will this survey inform?", "whether to launch a premium tier and at what price"), NUM("minutes", "Max minutes to complete", "5"), CH("type", "Survey type", ["Customer feedback", "Market research", "Employee pulse", "Event feedback", "Academic"], "Customer feedback")],
    "Write a {type} survey for the goal '{goal}' that takes at most {minutes} minutes for the profile's respondents. Table 'Questions' (# | Question | Type (single/multi/scale/open) | Options or scale | Required), steps for the flow (screening, warm-up, core, demographics), a quote with the intro text and the thank-you text, and a callout on questions deliberately left out because they would bias or lengthen it.", "table, steps, quote, callout", "Write survey", "Drafting items…"),
  T("fix", "Fix my questions", "Paste questions → bias removed", "🔧", [LONG("questions", "Paste your questions", "1. How much did you love our fast new checkout?\n2. Do you agree our prices are fair and reasonable?")],
    "Review these survey questions: {questions}. Table 'Review' (Question | Problem (leading / double-barrelled / vague / loaded / scale issue) | Rewrite), bullets on ordering and scale consistency, a checklist for a pre-launch test with 5 people, and a callout on the question most likely to produce useless data.", "table, bullets, checklist, callout", "Fix questions", "De-biasing…"),
  T("sample", "How many responses?", "Margin of error made simple", "🎯", [NUM("population", "Population size", "5000"), CH("margin", "Margin of error wanted", ["±3%", "±5%", "±10%"], "±5%"), NUM("rate", "Expected response rate %", "15")],
    "For a population of {population}, a target of {margin} at 95% confidence and an expected response rate of {rate}%: kv (responses needed, invitations to send, minimum per subgroup, confidence level), a table 'Trade-offs' (Margin | Responses needed | Invitations) for ±3, ±5 and ±10, bullets on reducing non-response bias, and a callout on what the margin of error does and does not mean.", "kv, table, bullets, callout", "Calculate", "Sizing sample…"),
  T("themes", "Theme open answers", "Paste responses → themes and quotes", "🧵", [LONG("responses", "Paste open-ended responses (one per line)", "Checkout was confusing\nLove the app but too pricey…"), TXT("question", "The question they answered", "What would make you use us more?")],
    "Code the open-ended responses to '{question}': {responses}. Table 'Themes' (Theme | Count | % | Sentiment | Representative quote), bullets of surprising or minority themes worth attention, a quote block with the 5 most usable verbatims, and a callout on how representative these themes are given the number of responses.", "table, bullets, quote, callout", "Find themes", "Reading answers…"),
  T("invite", "Invitation & reminders", "Messages that lift response rate", "📨", [TXT("incentive", "Incentive (if any)", "£10 voucher prize draw"), CH("channel", "Channel", ["Email", "In-app", "SMS", "Slack/Teams"], "Email")],
    "Write the {channel} invitation and two reminders for the profile's respondents, incentive: {incentive}. Quote for each message (subject line and body under 90 words), a table 'Schedule' (Message | Send day | Send time | Who receives it), bullets of subject-line variants to test, and a callout on consent, anonymity and opt-out wording.", "quote, table, bullets, callout", "Write invites", "Polishing…")])

# 5 ── A/B tests
APP("test_learn", "Test & Learn", "A/B tests designed, sized and read out honestly", "Business", ["#303F9F", "#EC407A", "#C0CA33"], "scale",
 "Test & Learn turns ideas into crisp hypotheses, sizes and schedules A/B tests, reads results without fooling yourself and keeps a prioritised experiment backlog.",
 "You are a product experimentation lead: rigorous about statistics, allergic to peeking and p-hacking, and focused on decisions rather than significance theatre.",
 "Run tests you can trust", "A little about your product and traffic sharpens every calculation.", ["Hypotheses with a clear success metric", "Sample size and duration in seconds", "Readouts that say ship, iterate or stop"],
 [TXT("product", "Product / site", "SaaS onboarding flow"), NUM("traffic", "Weekly visitors or users", "20000"), TXT("metric", "Primary metric and baseline", "signup conversion, 4.2%"), CH("platform", "Testing platform", ["Optimizely", "VWO", "LaunchDarkly", "GrowthBook", "Custom", "None yet"], "None yet")],
 [T("hypothesis", "Write the hypothesis", "Idea → testable statement", "💡", [TXT("idea", "Your idea", "shorten the signup form to 3 fields", True), TXT("why", "Why you think it helps", "drop-off at the phone-number field")],
    "Turn '{idea}' (reasoning: {why}) into an experiment plan for the profile's product. Kv (hypothesis in 'If we… then… because…' form, primary metric, guardrail metrics, minimum detectable effect, audience, variants), a quote with a one-paragraph test brief, bullets of what would justify abandoning the test early, and a callout on the confounders to control.", "kv, quote, bullets, callout", "Write hypothesis", "Framing…"),
  T("size", "Sample size & duration", "How long to run it", "⏱️", [NUM("baseline", "Baseline conversion %", "4.2"), NUM("mde", "Minimum lift to detect (relative %)", "10"), CH("variants", "Variants incl. control", ["2", "3", "4"], "2")],
    "Baseline {baseline}%, relative MDE {mde}%, {variants} variants, using the profile's weekly traffic. Kv (visitors per variant, total visitors, weeks to run at current traffic, power, significance level), a table 'Trade-offs' (MDE | Per variant | Weeks) for MDE 5, 10, 15 and 20%, a callout on running whole weekly cycles and never stopping early, and bullets on shortening the test without cheating.", "kv, table, callout, bullets", "Calculate", "Powering up…"),
  T("readout", "Read my results", "Paste numbers → decision", "📈", [LONG("results", "Results", "Control: 10,250 users, 431 conversions\nVariant: 10,180 users, 478 conversions\nRan 14 days"), TXT("guardrails", "Guardrail metrics (optional)", "refund rate flat, page load +40ms")],
    "Analyse the A/B results: {results}, guardrails: {guardrails}. Kv (conversion per variant, relative lift, confidence interval, p-value or probability to beat control, sample-ratio check), a text verdict of ship / iterate / stop with reasoning, a table 'Risks' (Risk | Present? | Evidence), and a callout on novelty effects and how long to monitor after shipping.", "kv, text, table, callout", "Read results", "Calculating lift…"),
  T("pitfalls", "Pre-launch check", "Catch the mistakes before launch", "🛑", [LONG("setup", "Describe the test setup", "50/50 split on new visitors, tracking via GA4 event, 2 weeks, metric = signup")],
    "Review this test setup: {setup}. Checklist covering randomisation, tracking, metric definition, sample-ratio mismatch, seasonality, overlapping tests and stopping rules (each item states what pass looks like), bullets of the specific problems spotted, and a callout on the single most likely way this test gives a false result.", "checklist, bullets, callout", "Check setup", "Inspecting…"),
  T("backlog", "Prioritise the backlog", "Which test next", "🗂️", [LONG("ideas", "Test ideas (one per line)", "new pricing page\nsocial proof on checkout\nremove coupon field")],
    "Prioritise these experiment ideas for the profile's product: {ideas}. Table 'Backlog' (Idea | Impact 1–5 | Confidence 1–5 | Ease 1–5 | ICE score | Suggested metric), cards for the top 3 (meta = expected weeks · risk), and a callout on ideas that should simply be shipped without a test, or dropped.", "table, cards, callout", "Prioritise", "Scoring ideas…")], STATS)

# 6 ── KPI dashboards
APP("metric_tree", "Metric Tree", "KPI dashboards that show what actually drives results", "Business", ["#2E7D32", "#F9A825", "#455A64"], "leaf",
 "Metric Tree helps analysts and founders define the metrics that matter, design dashboards people actually read, write metric definitions everyone agrees on and narrate the weekly numbers.",
 "You are a pragmatic analytics lead: you prefer five metrics with owners to fifty without, define every metric precisely, and write commentary that leads with the change and its cause.",
 "Fewer metrics, better decisions", "Tell us about the business so every metric fits.", ["North-star and driver trees", "Dashboard layouts tile by tile", "Weekly commentary from raw numbers"],
 [TXT("business", "Business", "B2B SaaS, 40 staff, £2m ARR"), CH("tool", "Dashboard tool", ["Looker Studio", "Power BI", "Tableau", "Metabase", "Google Sheets", "Excel"], "Google Sheets"), CH("cadence", "Review cadence", ["Daily", "Weekly", "Monthly"], "Weekly")],
 [T("tree", "Build a metric tree", "Goal → drivers → inputs", "🌳", [TXT("goal", "Top-level goal", "grow net revenue 30% this year", True), TXT("team", "Team or function", "marketing + product")],
    "Build a metric tree for '{goal}' owned by {team} in the profile's business. Kv (north-star metric, its definition, why it is the north star), a table 'Tree' (Level | Metric | Formula | Parent metric | Owner | Leading or lagging), bullets on the 3 input metrics with the most leverage, and a callout on vanity metrics to leave off.", "kv, table, bullets, callout", "Build tree", "Growing branches…"),
  T("layout", "Design the dashboard", "Tiles, charts, comparisons", "🧱", [LONG("metrics", "Metrics to include", "MRR, net new MRR, churn %, CAC, activation rate, NPS"), CH("audience", "For", ["Leadership", "Team", "Board", "Myself"], "Leadership")],
    "Design a {audience} dashboard for {metrics} in the profile's tool and review cadence. Table 'Layout' (Position | Metric | Visual (big number / line / bar / table) | Comparison (vs target / prior period) | Filter), steps to build the top row in that tool, a checklist of dashboard hygiene (date-range control, definitions link, last-refreshed stamp, colour rules), and a callout on what to cut to keep it on one screen.", "table, steps, checklist, callout", "Design layout", "Placing tiles…"),
  T("define", "Define a metric", "A definition everyone agrees on", "📖", [TXT("metric", "Metric name", "activation rate", True), TXT("context", "How it's used today", "product counts it differently from marketing")],
    "Write a metric definition for '{metric}' given: {context}. Kv (definition, formula, numerator, denominator, inclusions, exclusions, time window, grain, source table, owner, refresh), a table 'Edge cases' (Case | Counted? | Why), a quote with the one-sentence definition for the dashboard tooltip, and a callout on how the definition will shift historical numbers.", "kv, table, quote, callout", "Define metric", "Pinning it down…"),
  T("narrate", "Narrate this period", "Numbers → commentary", "🗣️", [LONG("numbers", "This period vs last", "MRR 212k (prev 204k), churn 2.1% (prev 1.6%), new logos 14 (prev 19)"), TXT("context", "What happened", "price rise on the 1st, a sales rep left")],
    "Write the commentary for {numbers} given the context: {context}, matching the profile's review cadence. Text with a 3-sentence headline summary leading with the biggest change and its cause, a table 'Movements' (Metric | Value | Change | Driver | Action), bullets of questions to investigate before the next review, and a callout on any number that looks like a data issue rather than a real change.", "text, table, bullets, callout", "Write commentary", "Reading numbers…"),
  T("alerts", "Set alert thresholds", "Know when a metric needs attention", "🚨", [TXT("metric", "Metric", "daily signups", True), LONG("history", "Recent values", "last 14 days: 41, 38, 45, 52, 40, 12, 15, 44, 47…", False)],
    "Propose alert thresholds for {metric} using the history: {history}. Kv (normal range, warning threshold, critical threshold, method used, expected false alarms per month), a table 'Alert rules' (Rule | Condition | Who is notified | First action), bullets on seasonality and weekday effects to account for, and a callout on alert fatigue.", "kv, table, bullets, callout", "Set alerts", "Drawing lines…")])

# 7 ── SQL for analysts (analytical patterns; distinct from Query Buddy's write/explain/optimise)
APP("sql_patterns", "SQL Patterns", "Cohorts, funnels and window functions, written right", "Tools", ["#004D40", "#FF6F00", "#78909C"], "brain",
 "SQL Patterns writes the analyst queries that are hard to get right, such as cohort retention, funnels, window functions and date spines, and sanity-checks your query for fan-out joins, NULL traps and timezone bugs.",
 "You are a senior analytics engineer who writes readable CTE-based SQL, comments every non-obvious line, and never trusts a number until it has been reconciled.",
 "Analyst SQL, minus the gotchas", "Tell us your warehouse and how your tables look.", ["Cohort, funnel and retention queries", "Window-function coaching", "Sanity checks that catch double counting"],
 [CH("dialect", "SQL dialect", ["BigQuery", "Snowflake", "PostgreSQL", "MySQL", "Redshift", "SQL Server", "DuckDB"], "PostgreSQL"), TXT("schema", "Key tables & columns", "users(id, created_at, plan); events(user_id, name, ts); orders(id, user_id, amount, created_at)"), CH("tz", "Reporting timezone", ["UTC", "Local", "Mixed"], "UTC")],
 [T("cohort", "Cohort retention", "Retention by signup cohort", "📅", [TXT("cohort_by", "Cohort users by", "signup month", True), TXT("active", "'Active' means", "any event named 'session_start'", True), CH("grain", "Period", ["Day", "Week", "Month"], "Month")],
    "Write a cohort retention query by {grain} for the profile's dialect and tables: cohort by {cohort_by}, active means {active}. Quote with the full query using CTEs (cohorts → activity → period spine → retention %), a table 'Output columns' (Column | Meaning | Example), steps to reconcile the cohort sizes against a simple count, and a callout on the incomplete latest period and timezone edges.", "quote, table, steps, callout", "Write query", "Building CTEs…"),
  T("funnel", "Funnel query", "Ordered steps with conversion", "🔻", [LONG("steps", "Funnel steps in order", "view_pricing → start_checkout → add_payment → purchase"), CH("window", "Conversion window", ["Same session", "24 hours", "7 days", "30 days"], "7 days"), CH("order", "Step order", ["Strict order", "Any order"], "Strict order")],
    "Write a funnel query for the steps {steps} with a {window} window and {order} matching, in the profile's dialect. Quote with the full query, a kv explaining how each step is attributed (first occurrence, dedupe, window), a table 'Output' (Step | Users | Conversion from previous | Conversion from first), and a callout on user-level versus event-level funnels.", "quote, kv, table, callout", "Write funnel", "Stacking steps…"),
  T("window", "Window function coach", "Running totals, ranks, gaps, lags", "🪟", [TXT("task", "What you need", "previous order date per customer and days since", True)],
    "Solve '{task}' with window functions in the profile's dialect. Quote with the query, a table 'Anatomy' (Clause | What it does here | Common mistake), text explaining PARTITION BY versus GROUP BY for this case in 3 sentences, and bullets of 3 variations (different frame, ties, NULL handling).", "quote, table, text, bullets", "Coach me", "Framing rows…"),
  T("check", "Sanity-check my query", "Fan-outs, NULLs, double counts", "🔍", [LONG("sql", "Paste your query", "SELECT u.plan, COUNT(*) FROM users u JOIN orders o ON o.user_id = u.id GROUP BY 1")],
    "Review for correctness, not performance: {sql}. Table 'Findings' (Clause | Issue (fan-out join, NULL in NOT IN, COUNT(*) vs COUNT DISTINCT, timezone, date boundary, filter after outer join) | Impact | Fix), a quote with the corrected query, a checklist of reconciliation queries that prove the numbers, and a callout on the single most likely wrong number this query produces today.", "table, quote, checklist, callout", "Check query", "Hunting bugs…"),
  T("spine", "Dates & gaps", "Date spines, fill-forward, period-over-period", "🦴", [CH("need", "Pattern", ["Date spine with zeros", "Fill forward missing values", "Period-over-period change", "Rolling 7 and 28 day"], "Date spine with zeros"), TXT("table", "Table and date column", "orders.created_at")],
    "Write the '{need}' pattern for {table} in the profile's dialect and timezone. Quote with the query, steps explaining why a plain GROUP BY fails here, a table 'Sample output' with 5 rows, and a callout on week starts, timezone conversion and daylight-saving edges.", "quote, steps, table, callout", "Write pattern", "Generating dates…")])

# 8 ── Data storytelling
APP("insight_memo", "Insight Memo", "Turn analysis into a memo people act on", "Business", ["#1A237E", "#FF7043", "#4DB6AC"], "bulb",
 "Insight Memo turns your findings into a one-page memo, a readout deck outline and plain-English number comparisons, and rehearses the questions stakeholders will fire back.",
 "You are a data-storytelling coach: bottom line up front, one message per section, every number given a comparison, and honest about uncertainty.",
 "From findings to decisions", "Who reads your work? That shapes the tone.", ["One-page memos from rough findings", "Readout decks slide by slide", "Numbers made memorable"],
 [NAME, CH("readers", "Usual readers", ["Executives", "Product managers", "Marketing", "Engineers", "Clients"], "Executives"), CH("tone", "House tone", ["Formal", "Direct", "Friendly"], "Direct")],
 [T("memo", "Write the memo", "Findings → one page", "📄", [LONG("findings", "Your findings (rough notes are fine)", "churn up 0.5pt since price rise, mostly monthly plans, annual unaffected, billing tickets doubled"), TXT("ask", "Decision or ask", "approve grandfathering monthly customers for 3 months")],
    "Write a one-page insight memo from {findings} with the ask '{ask}' for the profile's readers and tone. Text with a 2-sentence bottom line, bullets 'What we found' (each with the number and its comparison), a table 'Options' (Option | Expected effect | Cost | Risk), kv (recommendation, confidence, what would change our mind, next check-in), and a callout on data limitations.", "text, bullets, table, kv, callout", "Write memo", "Distilling…"),
  T("deck", "Readout deck outline", "Slide by slide", "🖥️", [LONG("analysis", "What you analysed and found", "analysed 6 months of support tickets: 40% are password resets, peak Monday mornings"), NUM("slides", "Number of slides", "8")],
    "Outline a {slides}-slide readout for: {analysis}. Table 'Slides' (# | Headline as a full-sentence takeaway | Visual | Speaker note), steps for the opening 60 seconds, a quote with the closing slide's recommendation text, and a callout on what belongs in the appendix.", "table, steps, quote, callout", "Outline deck", "Ordering slides…"),
  T("plain", "Make numbers land", "Comparisons people remember", "🔢", [LONG("numbers", "Numbers to explain", "0.37% error rate; 4.2M events/day; £18k saved")],
    "Rewrite {numbers} so non-analysts feel them. Table 'Translations' (Number | Plain-English version | Comparison or analogy | When to use it), bullets of rounding and framing rules, and a callout on comparisons that mislead (per cent vs percentage points, relative vs absolute, small bases).", "table, bullets, callout", "Translate", "Humanising…"),
  T("questions", "Stakeholder questions", "What they'll ask and how to answer", "❓", [LONG("summary", "Your main claim and evidence", "recommend pausing paid social: CAC doubled in Q2 with no lift in retention")],
    "For the claim '{summary}', list the 8 hardest questions the profile's readers will ask as a table (Question | Why they ask it | Best answer | Evidence to have ready), a checklist of analyses to run beforehand, and a quote with a graceful answer for a question you cannot answer yet.", "table, checklist, quote", "Prep questions", "Cross-examining…"),
  T("caption", "Chart caption & takeaway", "One chart, one sentence", "🏷️", [PHOTO("Chart screenshot (optional)"), TXT("chart", "Or describe the chart", "weekly active users by platform, iOS flat, Android +30%")],
    "Write the takeaway for the chart in the photo or described as: {chart}. Quote with 3 takeaway titles, kv (caption, source line, footnote on caveats), and bullets on what a reader might misread.", "quote, kv, bullets", "Write takeaway", "Captioning…")])

# 9 ── Time series & forecasting
APP("trend_lens", "Trend Lens", "Read any time series: trend, season, spikes, forecast", "Tools", ["#4527A0", "#00BCD4", "#FFB300"], "clock",
 "Trend Lens reads a pasted time series and explains the trend, seasonality and anomalies, produces a simple forecast with ranges, recommends a forecasting method for your data and scores your past forecasts.",
 "You are a forecasting analyst who prefers simple, explainable methods, always shows the range rather than just the point, and says clearly when the history is too short to trust.",
 "See where the numbers are heading", "Tell us what you track and how often.", ["Trend and seasonality decoded", "Simple forecasts with honest ranges", "Anomalies explained, not ignored"],
 [TXT("series", "What you usually track", "daily orders, monthly revenue"), CH("tool", "Tool", ["Excel", "Google Sheets", "Python", "R", "Power BI"], "Excel"), CH("horizon", "Usual forecast horizon", ["Next week", "Next month", "Next quarter", "Next year"], "Next month")],
 [T("read", "Read my series", "Paste values → what's happening", "📉", [LONG("data", "Paste dates and values", "2024-01,1200\n2024-02,1350\n2024-03,1280…")],
    "Decompose {data}. Kv (overall trend as % per period, seasonality pattern and strength, volatility, most recent change, data quality), a table 'Notable points' (Date | Value | Expected | Deviation | Likely explanation), bullets of 3 things the series suggests checking in the business, and a callout on how much history there is and what it can support.", "kv, table, bullets, callout", "Read series", "Tracing the line…"),
  T("forecast", "Quick forecast", "Point and range for the horizon", "🔭", [LONG("data", "Paste dates and values", "2024-01,1200\n2024-02,1350…"), NUM("periods", "Periods to forecast", "3"), CH("method", "Method", ["Auto", "Moving average", "Linear trend", "Seasonal naive", "Exponential smoothing"], "Auto")],
    "Forecast {periods} periods ahead for {data} using {method} (if Auto, choose and justify). Table 'Forecast' (Period | Point | Low | High | Method note), text explaining the method in plain English, a quote with the formula to reproduce it in the profile's tool, and a callout on the assumptions that would break the forecast.", "table, text, quote, callout", "Forecast", "Extending line…"),
  T("method", "Pick a method", "Which forecasting approach fits", "🧭", [TXT("describe", "Describe the data", "3 years of weekly sales, strong Christmas peak, growing", True), TXT("purpose", "Purpose", "stock ordering")],
    "Recommend forecasting methods for: {describe}, purpose: {purpose}. Cards for the top 3 methods (meta = complexity · data needed), a table 'Comparison' (Method | Handles trend | Handles seasonality | Explainable | Works in the profile's tool), steps to run the recommended one in that tool, and a callout on when to stop forecasting and ask the business instead.", "cards, table, steps, callout", "Recommend", "Weighing methods…"),
  T("anomaly", "Explain a spike or dip", "Was it real?", "⚡", [TXT("event", "What happened", "orders dropped 40% on 14 May", True), LONG("context", "Anything you know", "site outage for 2h that day; bank holiday?", False)],
    "Investigate '{event}' with the context: {context}. Table 'Hypotheses' (Cause | Evidence for | Evidence against | How to confirm), steps to confirm in order of effort, a kv (best guess, confidence, expected recovery), and a callout on whether to exclude the point from future forecasts.", "table, steps, kv, callout", "Investigate", "Zooming in…"),
  T("accuracy", "Score my forecast", "Forecast vs actual", "🎯", [LONG("pairs", "Forecast vs actual pairs", "Jan: 1200 vs 1180\nFeb: 1300 vs 1420…")],
    "Score the forecast accuracy for {pairs}. Kv (MAPE, MAE, bias direction, worst period), a table 'By period' (Period | Forecast | Actual | Error | % error), bullets on whether the bias is systematic and how to correct it, and a callout on what accuracy is realistic for this kind of series.", "kv, table, bullets, callout", "Score it", "Grading…")], FCST)

# 10 ── Analyst request scoping
APP("ask_scope", "Scope the Ask", "Turn vague data requests into clear, sized specs", "Productivity", ["#5C6BC0", "#FF8A65", "#66BB6A"], "chat",
 "Scope the Ask helps analysts turn 'can you pull some numbers?' into a clear spec: the decision behind it, the metrics and cuts, the data needed, the clarifying questions to send and an honest effort estimate.",
 "You are a seasoned analytics manager who protects analysts' time: you find the decision behind every request, ask few but sharp questions, and never start building before the definition of done is agreed.",
 "Fewer re-dos, clearer asks", "Tell us about your team and data so scoping fits.", ["Find the decision behind the request", "Clarifying questions ready to send", "Effort estimates you can defend"],
 [NAME, TXT("team", "Your team & tools", "2 analysts, BigQuery + Looker"), CH("load", "Current workload", ["Light", "Normal", "Slammed"], "Normal")],
 [T("spec", "Scope this request", "Message → spec", "🧭", [LONG("request", "Paste the request", "Hey, can you get me churn by region for the QBR? Need it by Thursday"), TXT("who", "Who asked", "VP Sales")],
    "Scope the request '{request}' from {who}. Kv (underlying decision, real question, metrics, dimensions and cuts, time range, grain, deliverable format, deadline), a table 'Data needed' (Source | Tables or fields | Available? | Risk), a checklist 'Definition of done', and a callout on what to push back on.", "kv, table, checklist, callout", "Scope it", "Reading between…"),
  T("questions", "Clarifying questions", "Ask once, not five times", "❓", [LONG("request", "The request", "can you pull engagement numbers for the new feature?"), CH("channel", "Send via", ["Slack/Teams", "Email", "In a meeting"], "Slack/Teams")],
    "For the request {request}, write the clarifying questions to send via {channel}. Quote with the message (at most 5 questions, each paired with a default assumption so work can start now), a table 'Why each question' (Question | What changes depending on the answer), and bullets on what to assume if there is no reply.", "quote, table, bullets", "Draft questions", "Sharpening…"),
  T("estimate", "Estimate effort", "Hours, risks, shortcuts", "⏳", [LONG("scope", "Scoped work", "churn by region and plan, last 4 quarters, Looker dashboard plus a one-pager"), CH("quality", "Quality bar", ["Quick and rough", "Solid", "Board-ready"], "Solid")],
    "Estimate the effort for {scope} at a '{quality}' bar for the profile's team and current workload. Table 'Breakdown' (Task | Hours low / likely / high | Dependency | Risk), kv (total likely hours, earliest realistic date, biggest uncertainty), bullets describing a cheaper version that answers 80% of the question, and a callout on hidden work (data cleaning, definition disputes, review cycles).", "table, kv, bullets, callout", "Estimate", "Counting hours…"),
  T("triage", "Triage the queue", "Which requests first", "📋", [LONG("requests", "Requests (one per line)", "CEO: revenue by cohort for board\nMarketing: UTM clean-up\nSupport: ticket volume trend")],
    "Triage these requests for the profile's team and workload: {requests}. Table 'Queue' (Request | Decision it supports | Value 1–5 | Effort 1–5 | Urgency | Order), bullets on requests to combine or decline, a quote with a polite defer-or-decline message template, and a callout on self-serve alternatives worth building.", "table, bullets, quote, callout", "Triage", "Sorting queue…"),
  T("handoff", "Deliver & close", "A handoff note that prevents re-asks", "✅", [LONG("delivered", "What you delivered and key caveats", "dashboard link; churn = cancellations / active at period start; excludes trials")],
    "Write the handoff for {delivered}. Quote with the delivery message (what it answers, how to read it, caveats, where it lives), a kv (owner, refresh schedule, definitions link, expiry), a checklist of follow-ups to schedule, and bullets on what to log in the request archive.", "quote, kv, checklist, bullets", "Write handoff", "Wrapping up…")])
