from dsl import *
# w30 — Tools: editing. Grammar coach, plain-language rewriter, translation checker, screenplay format,
# poetry workshop, speech-to-outline, style-sheet consistency, subtitle editing, inclusive language, fiction line edit.

APP("red_pen", "Red Pen", "Grammar fixes that teach you the rule behind them", "Education", ["#B71C1C", "#263238", "#FFC107"], "note",
 "Red Pen marks up your writing like a patient editor: every correction comes with the rule, the reason and a drill so the same mistake stops showing up.",
 "You are a precise, encouraging copy editor and grammar teacher: you correct, name the rule, explain why in one line, and never rewrite the writer's voice away.",
 "Learn from every correction", "Tell Red Pen which English you write and where you tend to slip.", ["Every fix explained with its rule", "Punctuation clinic for commas, dashes and more", "Drills built from your own weak spots"],
 [NAME, CH("variety", "English variety", ["US", "UK", "Australian", "Canadian"], "US"), CH("level", "Your level", ["Native speaker", "Advanced learner", "Intermediate learner"], "Native speaker"), TXT("weak", "Known weak spots", "commas, articles, tenses")],
 [T("markup", "Mark up my text", "Corrections with the rule behind each one", "✍️",
    [LONG("text", "Your text", "Paste a paragraph, email or essay…"), CH("depth", "Depth", ["Errors only", "Errors + style", "Everything"], "Errors + style")],
    "Edit this text at depth '{depth}' in the profile's English variety: {text}. Produce a table (No. | Original | Corrected | Rule | Why, one line) with one row per change, ordered as they appear; then a quote section containing the full corrected text; then kv counting errors by type (punctuation, agreement, tense, word choice, spelling, style); and a callout naming the single pattern to work on next.",
    "table, quote, kv, callout", "Mark it up", "Uncapping the pen…"),
  T("rule", "Explain a rule", "Who vs whom, lay vs lie, that vs which…", "📖",
    [TXT("rule", "Rule or confusion", "who vs whom", True)],
    "Explain '{rule}' for the profile level. Sections: text (the rule in two plain sentences), table (Wrong | Right | Why) with 5 contrasting pairs, steps giving a 3-step decision test to apply in the moment, then a checklist of 5 sentences for the user to mark right or wrong, with the answers in a callout at the end.",
    "text, table, steps, checklist, callout", "Explain", "Checking the rule…"),
  T("punct", "Punctuation clinic", "Fix one mark at a time", "🔧",
    [LONG("sample", "Your text", "Paste a few sentences…"), CH("mark", "Focus mark", ["Commas", "Semicolons & colons", "Apostrophes", "Dashes & hyphens", "Quotation marks", "All"], "All")],
    "Review the punctuation in: {sample}, focusing on '{mark}'. Table (Sentence | Problem | Fixed sentence | Rule) for every issue, a quote with the corrected text, bullets listing each rule used in plain words with a mini example, and a callout on the most common myth about this mark in the profile's variety.",
    "table, quote, bullets, callout", "Fix punctuation", "Counting commas…"),
  T("drills", "Drill my weak spots", "10 practice sentences from your profile", "🏋️", [],
    "Using the profile's weak spots and level (if no weak spots are set, use the 5 most common errors for that level), build 10 fill-in or fix-it drill sentences as steps (each step: the sentence with the tricky spot marked, and what to decide), a table (No. | Rule tested | Common trap) and a callout containing all 10 answers so the user can check afterwards.",
    "steps, table, callout", "Drill me", "Sharpening pencils…"),
  T("page", "Correct a page", "Photo of printed or handwritten text", "📷",
    [PHOTO("Photo of the page", "", True)],
    "Transcribe the text in the photo, then correct it. Sections: quote with the corrected transcription, table (Original | Corrected | Rule) for every change, kv (words, errors found, error rate per 100 words) and a callout flagging any words that were hard to read and may be wrong.",
    "quote, table, kv, callout", "Correct page", "Reading the page…")])

APP("plain_speak", "Plain Speak", "Turn jargon into words anyone understands", "Tools", ["#1565C0", "#FF8F00", "#43A047"], "chat",
 "Plain Speak rewrites dense letters, policies, forms and instructions into plain language at the reading level you choose, and shows exactly what changed and why.",
 "You are a plain-language editor trained on government and healthcare clear-writing standards: short sentences, active voice, everyday words, meaning preserved, never patronising.",
 "Say it so anyone gets it", "Set your audience and target reading level once; every rewrite follows it.", ["Rewrites with a before/after readability score", "Decode letters and forms from a photo", "Jargon glossaries in one tap"],
 [NAME, CH("audience", "Usual audience", ["General public", "Customers", "Patients", "Students", "Colleagues"], "General public"), CH("grade", "Target reading level", ["Grade 5–6", "Grade 7–8", "Grade 9–10"], "Grade 7–8"), CH("voice", "Voice", ["Warm", "Neutral", "Direct"], "Neutral")],
 [T("rewrite", "Rewrite in plain language", "Same meaning, half the effort to read", "🔁",
    [LONG("text", "Text to simplify", "Paste the paragraph, policy or letter…"), CH("keep", "Must keep exactly", ["Legal terms", "Numbers", "Names", "Nothing special"], "Nothing special", True), TXT("aud", "Audience for this piece", "leave blank to use profile")],
    "Rewrite in plain language for the audience '{aud}' (fall back to the profile audience, reading level and voice), keeping exactly: {keep}. Text: {text}. Sections: quote with the full rewrite; table (Original phrase | Plain version | Why) for the 8 most important changes; kv (words before/after, average sentence length before/after, estimated reading grade before/after); and a callout on any place where simplifying could change the meaning.",
    "quote, table, kv, callout", "Make it plain", "Untangling…"),
  T("score", "Readability report", "Where readers get stuck and why", "📊",
    [LONG("text", "Text to check", "Paste up to a page…")],
    "Assess readability of: {text}. kv (estimated reading grade, average sentence length, longest sentence in words, share of passive sentences, jargon count, target grade from profile); table (Sentence | Problem: long / passive / jargon / nominalisation / vague | Fix) for the 10 worst sentences; bullets with the top 3 changes that would move the grade most.",
    "kv, table, bullets", "Score it", "Measuring sentences…"),
  T("letter", "Decode a letter or form", "Photo → what it says and what to do", "📷",
    [PHOTO("Photo of the letter, notice or form", "", True), TXT("worry", "What you need to know", "do I owe money? is there a deadline?")],
    "Read the document in the photo and answer the user's concern: {worry}. Sections: text with a plain-language summary in 3 sentences; kv (who sent it, what they want, deadline, amount or cost, reference numbers); a checklist of actions in order; and a callout on anything that must not be ignored or that needs a phone call.",
    "text, kv, checklist, callout", "Decode it", "Reading small print…"),
  T("glossary", "Jargon glossary", "Every technical term, defined plainly", "📚",
    [LONG("text", "Text containing jargon", "Paste the document…"), CH("style", "Definition style", ["One line", "With an example", "For a 12-year-old"], "One line")],
    "Extract every jargon term, acronym or technical phrase from: {text}. Table (Term | Plain definition | Example in context) in definition style '{style}', ordered by how often the term appears; then a quote with a two-sentence 'Before you read' intro that uses none of the jargon.",
    "table, quote", "Build glossary", "Collecting terms…"),
  T("explain", "Explain it for…", "The same idea for a specific reader", "🎯",
    [LONG("topic", "Text or topic", "Paste text or name a concept, e.g. how APR works"), CH("as", "Explain for", ["A 10-year-old", "A busy manager", "A new customer", "A nervous patient"], "A busy manager")],
    "Explain {topic} for '{as}' in the profile voice. Sections: text of at most 120 words, bullets of the 3 things they must remember, a quote with one analogy they could repeat to someone else, and a callout on what this explanation deliberately leaves out.",
    "text, bullets, quote, callout", "Explain", "Simplifying…")],
 "Plain rewrites can lose legal, financial or medical nuance; check important documents with the sender or a qualified professional.")

APP("back_check", "Back Check", "Catch mistranslations before they ship", "Tools", ["#00695C", "#EF6C00", "#5E35B1"], "globe",
 "Back Check reviews a translation against its source, back-translates it so you can see what it really says, enforces your glossary, and fixes register for the right locale.",
 "You are a senior bilingual reviser: you compare source and target segment by segment, distinguish real meaning errors from preference, and respect the client's glossary over your own taste.",
 "Trust, but verify the translation", "Tell Back Check your language pair and content type.", ["Segment-by-segment error table", "Back-translation to see what readers get", "Glossary and register enforcement"],
 [NAME, TXT("pair", "Language pair (source → target)", "English → Spanish"), CH("domain", "Usual content", ["Marketing", "Legal / contracts", "Technical / UI", "Medical", "Literary", "Subtitles", "General"], "General"), TXT("fixed", "Terms that never change", "brand names, product names")],
 [T("check", "Check a translation", "Source vs target, issue by issue", "🔍",
    [LONG("source", "Source text", "Paste the original…"), LONG("target", "Translation", "Paste the translated text…"), CH("strict", "Strictness", ["Meaning only", "Meaning + tone", "Publish-ready"], "Meaning + tone")],
    "Compare source: {source} with translation: {target} at strictness '{strict}' for the profile language pair and domain. Table (Segment | Issue type: omission / addition / mistranslation / terminology / grammar / tone | Severity: critical / major / minor | Suggested fix) with one row per issue in order; kv (accuracy /10, fluency /10, terminology /10, overall verdict); a quote with the fully corrected translation; and a callout on the single most damaging error and why.",
    "table, kv, quote, callout", "Check it", "Reading both sides…"),
  T("back", "Back-translate", "See what the translation actually says", "↩️",
    [LONG("target", "Translated text", "Paste the translation…"), TXT("into", "Back into (language)", "English")],
    "Back-translate this text literally into {into} (if not given, into the source language of the profile pair), preserving word order and ambiguity rather than smoothing: {target}. Sections: quote with the literal back-translation; bullets listing every place where the meaning a reader gets may differ from what was probably intended; table (Phrase | Literal meaning | Likely intended meaning | Risk).",
    "quote, bullets, table", "Back-translate", "Reversing…"),
  T("terms", "Terminology check", "Enforce the glossary", "📋",
    [LONG("text", "Translated text", "Paste the translation…"), LONG("terms", "Glossary (term = translation)", "Sign in = Iniciar sesión; checkout = pago")],
    "Check {text} against this glossary: {terms}, plus the profile's fixed terms. Table (Term | Expected | Found | Where | Fix) with one row per deviation or missing term; kv (terms checked, compliant, deviations, untranslated terms left in source language); a checklist of edits to apply in order.",
    "table, kv, checklist", "Check terms", "Matching terms…"),
  T("register", "Fix the register", "Formal, casual, or right for the locale", "🎚️",
    [LONG("text", "Translated text", "Paste the translation…"), CH("formality", "Wanted register", ["Formal (usted / vous / Sie)", "Neutral", "Casual", "Youth / slang-aware"], "Neutral"), TXT("locale", "Locale", "Mexico, not Spain")],
    "Rewrite {text} in the target language for register '{formality}' and locale '{locale}' (if no locale is given, use the most widely understood variety of the profile target language). Sections: quote with the rewritten text; table (Original | Changed to | Why: pronoun / verb form / vocabulary / idiom); a callout on locale traps (words that are fine in one country and rude or odd in another).",
    "quote, table, callout", "Adjust register", "Tuning tone…"),
  T("sign", "Check a sign or menu", "Photo of a translated sign, menu or label", "📷",
    [PHOTO("Photo of the translated text", "", True)],
    "Read the original and translated text in the photo. Table (Original | Translation shown | Problem | Better version) for every item, a callout naming the most serious error (safety, allergens, legal) if any, and a quote with a clean corrected version ready to print.",
    "table, callout, quote", "Check sign", "Squinting…")],
 "Back Check is an editing aid, not a certified translation; have legal, medical and safety-critical text reviewed by a qualified professional translator.")

APP("slugline", "Slugline", "Screenplay format and scene notes in seconds", "Art & Design", ["#212121", "#FDD835", "#E53935"], "camera",
 "Slugline converts rough scenes into correctly formatted screenplay pages, gives reader-style coverage on each scene, writes loglines, and checks your outline against a beat sheet.",
 "You are a working script editor: you know industry formatting cold, read like a studio reader, and give notes that name the problem and the fix without rewriting the writer's voice.",
 "Write it like a pro reads it", "Set your format and standard once; every page follows it.", ["Prose → proper screenplay format", "Reader-style scene coverage", "Loglines and beat-sheet checks"],
 [NAME, CH("format", "Format", ["Feature", "TV drama (hour)", "Sitcom (multi-cam)", "Short film", "Web series"], "Feature"), CH("standard", "Standard", ["US (Final Draft style)", "UK (BBC style)"], "US (Final Draft style)"), TXT("project", "Current project", "title, genre, one line")],
 [T("format", "Format this scene", "Rough prose → screenplay page", "🎬",
    [LONG("scene", "Scene as prose or rough script", "Sam walks into the diner, sees Lee, and…"), CH("fix", "Also", ["Format only", "Format + trim action lines", "Format + tighten dialogue"], "Format only")],
    "Convert to the profile's screenplay standard, mode '{fix}': {scene}. Sections: quote containing the formatted scene (INT./EXT. slugline with location and time, present-tense action in blocks of at most 4 lines, character cues in caps, parentheticals only when essential, no camera directions unless present in the source); checklist of formatting rules applied; kv (estimated page length in eighths, speaking characters, word count of action vs dialogue).",
    "quote, checklist, kv", "Format scene", "Setting margins…"),
  T("coverage", "Scene notes", "Coverage on one scene", "📝",
    [LONG("scene", "Scene", "Paste the scene…"), TXT("purpose", "What the scene must do", "reveal that Ana lied about the money")],
    "Give reader coverage on: {scene}, which must accomplish: {purpose} (if not given, first infer the scene's purpose from context and state it). Table (Element: entry point / conflict / turn / exit / subtext / exposition | Working | Not working | Fix); bullets on where exposition is being delivered on the nose; kv (suggested enter-late point, suggested leave-early point, lines that could be cut); a quote with the weakest beat rewritten in the same voice.",
    "table, bullets, kv, quote", "Give notes", "Reading coverage…"),
  T("logline", "Logline & synopsis", "Pitch it in one sentence, then 150 words", "🎯",
    [LONG("premise", "Premise / what happens", "A retired safecracker must…"), CH("genre", "Genre", ["Drama", "Comedy", "Thriller", "Horror", "Romance", "Sci-fi / fantasy", "Documentary"], "Drama")],
    "From the premise {premise} in genre '{genre}' for the profile format: cards with 3 loglines (meta = angle: character-driven / high-concept / ironic), each with protagonist, goal, obstacle and stakes in one sentence; text with a 150-word synopsis in present tense; bullets of 3 comparable titles and what to borrow from each.",
    "cards, text, bullets", "Write loglines", "Boiling it down…"),
  T("dialogue", "Subtext pass", "Cut the on-the-nose lines", "🗣️",
    [LONG("dialogue", "Dialogue exchange", "Paste the exchange…"), CH("mood", "Undercurrent", ["Hidden anger", "Attraction", "Fear", "Guilt", "Power play"], "Hidden anger")],
    "Rewrite this exchange so the undercurrent '{mood}' is felt but never stated: {dialogue}. Sections: quote with the rewritten exchange in screenplay format; table (Original line | Why it is on the nose | Rewritten | What it now hides); a callout on whether the first and last lines of the exchange can be cut.",
    "quote, table, callout", "Add subtext", "Reading subtext…"),
  T("beats", "Beat sheet check", "Outline vs 15 beats with page targets", "🧭",
    [LONG("outline", "Outline or treatment", "Paste your outline…")],
    "Check this outline against a 15-beat structure scaled to the profile format's page count: {outline}. Table (Beat | Page target | Present? yes / weak / missing | Notes) for all 15 beats in order; a callout on the midpoint and the sagging second act; steps to fix the 3 weakest beats.",
    "table, callout, steps", "Check beats", "Counting pages…")])

APP("meter_mate", "Meter Mate", "Scansion, form and rhyme help for poets", "Books & Reference", ["#4A148C", "#F48FB1", "#FFD54F"], "moon",
 "Meter Mate scans your lines for stress and syllables, checks a poem against its form, workshops it like a good reading group, and finds rhymes that fit the mood.",
 "You are a generous poetry workshop leader with a technician's ear: you mark stresses precisely, know the forms, praise specifically, and never flatten a poem into prose.",
 "Hear every line", "Tell Meter Mate what you write and who you read.", ["Line-by-line scansion", "Form checks for sonnets, villanelles, haiku and more", "Workshop notes and rhyme finder"],
 [NAME, CH("forms", "Forms you write", ["Free verse", "Sonnet", "Haiku / tanka", "Villanelle", "Ghazal", "Slam / spoken word", "Rhymed quatrains"], "Free verse", True), TXT("poets", "Poets you admire", "Dickinson, Ocean Vuong, Heaney…"), CH("goal", "Goal", ["Publish", "Workshop", "Perform", "For myself"], "For myself")],
 [T("scan", "Scan my meter", "Stress and syllable map per line", "🎼",
    [LONG("poem", "Poem", "Paste the poem…"), CH("meter", "Intended meter", ["Iambic pentameter", "Iambic tetrameter", "Trochaic", "Anapestic", "Syllabic (count only)", "Not sure"], "Not sure")],
    "Scan this poem against intended meter '{meter}': {poem}. Table (Line | Syllables | Stress pattern using ˘ and / | Feet | Notes) for every line; bullets naming the lines where the rhythm stumbles and the substitution involved (trochaic inversion, feminine ending, spondee); a quote with the two roughest lines smoothed while keeping the sense.",
    "table, bullets, quote", "Scan it", "Tapping out feet…"),
  T("form", "Form check", "Does it obey the form?", "📐",
    [LONG("poem", "Poem", "Paste the poem…"), CH("form", "Form", ["Sonnet (Shakespearean)", "Sonnet (Petrarchan)", "Villanelle", "Haiku", "Tanka", "Sestina", "Ghazal", "Limerick", "Pantoum"], "Sonnet (Shakespearean)")],
    "Check {poem} against the rules of the {form}. Checklist of the form's rules (line count, meter, rhyme scheme, refrains or repeated words, volta or turn, syllable counts) each marked met or not; table (Line | Rhyme letter found | Expected | OK?); a callout on the turn or refrain placement; steps to bring the poem into form with the least damage.",
    "checklist, table, callout, steps", "Check form", "Counting lines…"),
  T("workshop", "Workshop this poem", "Notes like a good reading group", "💬",
    [LONG("poem", "Poem", "Paste the poem…"), TXT("ask", "What you want feedback on", "the ending feels flat")],
    "Workshop {poem}; the poet asks about: {ask} (if nothing is asked, give general notes). Bullets of 3 specific strengths quoting the words; table (Line | Suggestion | Why) for up to 8 lines; text on image, sound and line-break choices; a quote with one stanza revised as an example; a callout naming any cliché or abstraction to cut.",
    "bullets, table, text, quote, callout", "Workshop it", "Reading aloud…"),
  T("rhyme", "Rhyme & sound finder", "Perfect, slant and vowel rhymes", "🔔",
    [TXT("word", "Word", "silver", True), CH("kind", "Kind", ["Perfect", "Slant", "Assonance", "Consonance", "All"], "All"), TXT("mood", "Mood or topic", "loss")],
    "Find rhymes for '{word}' of kind '{kind}' suited to the mood '{mood}' (if no mood is given, judge fit for general lyric use). Table (Type | Words, 8 to 12 each | Fits the mood?); bullets with 4 line fragments using the best matches; a callout on rhymes that would sound forced.",
    "table, bullets, callout", "Find rhymes", "Hunting echoes…"),
  T("daily", "Today's prompt", "Three prompts for your forms", "✨", [],
    "Give 3 writing prompts tuned to the profile forms, admired poets and goal as cards (meta = form · minutes); steps for a 15-minute draft session; a quote with one possible opening line for the first prompt.",
    "cards, steps, quote", "Inspire me", "Calling the muse…")])

APP("talk_outline", "Talk to Outline", "Rambling voice memo → structured outline and draft", "Productivity", ["#0277BD", "#FFA000", "#D81B60"], "mic",
 "Talk to Outline takes the transcript of a voice memo, a dictated brain-dump or a whiteboard photo and turns it into a clean outline, a task list, a first draft and a list of gaps.",
 "You are a sharp editorial assistant who listens to people think out loud, finds the structure they were reaching for, keeps their words where they were good, and drops the tangents.",
 "Think out loud, get an outline", "Tell us what you usually turn your rambles into.", ["Transcript → nested outline", "Tasks and decisions pulled out", "First draft in your voice"],
 [NAME, CH("output", "Usual output", ["Blog posts", "Reports", "Emails", "Talks", "Study notes", "Novel chapters"], "Reports"), CH("depth", "Outline depth", ["2 levels", "3 levels"], "2 levels"), TXT("style", "Writing style notes", "short sentences, British spelling")],
 [T("outline", "Transcript → outline", "Structure from your ramble", "🗂️",
    [LONG("transcript", "Transcript or brain-dump", "Paste the voice-memo transcript…"), CH("purpose", "Purpose", ["Article", "Report", "Talk", "Email", "Notes"], "Article")],
    "Turn this transcript into an outline for a {purpose} at the profile depth: {transcript}. Sections: bullets holding the outline, numbered headings as items and sub-points as items prefixed with '–'; kv (thesis in one sentence, intended audience, tone detected, estimated final length); table (Point | Supporting detail found in transcript | Evidence still missing); a callout listing the tangents dropped so nothing is lost.",
    "bullets, kv, table, callout", "Outline it", "Finding the thread…"),
  T("tasks", "Pull out tasks & decisions", "Everything actionable, with the source line", "✅",
    [LONG("transcript", "Transcript", "Paste the transcript…")],
    "From {transcript} extract commitments and decisions. Table (Task | Owner | Due | Source phrase); bullets listing decisions made; a checklist of tasks in priority order; a callout naming items that are ambiguous and need a follow-up question.",
    "table, bullets, checklist, callout", "Extract tasks", "Listening for verbs…"),
  T("draft", "Ramble → draft", "A first draft in your words", "📝",
    [LONG("transcript", "Transcript", "Paste the transcript…"), CH("form", "Form", ["Email", "Blog post", "Memo", "LinkedIn post", "Script"], "Email"), NUM("words", "Target words", "300")],
    "Write a {form} of about {words} words from: {transcript}, following the profile style notes and keeping the speaker's best phrases verbatim. Sections: quote with the draft; bullets of what was cut and why; a callout listing any factual claims in the transcript that should be verified before sending.",
    "quote, bullets, callout", "Draft it", "Typing it up…"),
  T("gaps", "Find the gaps", "What the outline still needs", "🕳️",
    [LONG("outline", "Outline or transcript", "Paste your outline…")],
    "Review {outline} for the profile's usual output. Bullets of 5 to 8 missing points, counter-arguments and examples a reader would expect; table (Section | Question to answer | Why it matters); steps for the next 30 minutes of work in order.",
    "bullets, table, steps", "Find gaps", "Poking holes…"),
  T("board", "Whiteboard → outline", "Photo of a board or paper notes", "📷",
    [PHOTO("Photo of whiteboard or notes", "", True)],
    "Read everything on the board or page in the photo. Sections: bullets with a nested outline that groups related items; table (Item | Type: idea / task / question / decision | Notes); a checklist of the tasks; a callout for anything illegible or ambiguous.",
    "bullets, table, checklist, callout", "Read board", "Deciphering…")])

APP("style_sheet", "Style Sheet", "Consistency for long manuscripts, chapter by chapter", "Tools", ["#37474F", "#00ACC1", "#FF7043"], "gear",
 "Style Sheet builds a copyeditor's style sheet from your manuscript, checks new chapters against it, converts between US and UK conventions, scans for continuity slips and trims to a word count.",
 "You are a meticulous copyeditor: you record decisions rather than impose taste, follow the chosen house style, and flag inconsistencies with their exact location.",
 "One manuscript, one set of rules", "Tell Style Sheet what you are writing and which conventions you follow.", ["Auto-built style sheet from a sample", "Chapter checks against your decisions", "US ↔ UK conversion and continuity scans"],
 [NAME, CH("kind", "Manuscript type", ["Novel", "Non-fiction book", "Thesis", "Corporate report", "Blog series"], "Novel"), CH("english", "English", ["US", "UK", "Oxford spelling", "Australian"], "UK"), CH("guide", "House style", ["Chicago", "AP", "APA", "New Hart's Rules", "None / my own"], "None / my own")],
 [T("build", "Build my style sheet", "Decisions extracted from a sample", "🧾",
    [LONG("text", "Chapter or sample", "Paste a chapter…")],
    "Extract style decisions from: {text}, respecting the profile English and house style. Table (Item | Chosen form | Variants seen | Rule or reason) covering spellings, hyphenation, capitalisation, numbers, names and recurring terms; kv (numbers policy, serial comma, quotation marks, dashes, italics for titles and thoughts, time and date format); bullets of decisions the author still needs to make.",
    "table, kv, bullets", "Build sheet", "Noting decisions…"),
  T("check", "Check a chapter", "Find every departure from the sheet", "🔎",
    [LONG("text", "Chapter text", "Paste the chapter…"), LONG("sheet", "Your style sheet (optional)", "grey not gray; Dr with no full stop; 1990s not 1990's…", False)],
    "Check {text} against this style sheet: {sheet} (if none is given, treat the chapter's own majority usage as the sheet), plus the profile English and house style. Table (Location: quote 4 to 6 words | Found | Should be | Sheet rule); kv (issues by category: spelling, hyphenation, capitals, numbers, punctuation); a checklist of fixes to apply in order; a callout where the sheet itself is contradictory or silent.",
    "table, kv, checklist, callout", "Check chapter", "Comparing…"),
  T("convert", "US ↔ UK convert", "Spelling, punctuation and vocabulary", "🔁",
    [LONG("text", "Text", "Paste the text…"), CH("to", "Convert to", ["UK", "US", "Australian"], "UK")],
    "Convert {text} to {to} conventions. Sections: quote with the converted text; table (Original | Converted | Category: spelling / punctuation / vocabulary / date and units) for every change; a callout on what was deliberately left alone (quoted speech, proper nouns, titles of works).",
    "quote, table, callout", "Convert", "Swapping letters…"),
  T("continuity", "Continuity scan", "Names, ages, eye colours, timelines", "🧵",
    [LONG("text", "Chapters or notes", "Paste one or more chapters…")],
    "Scan {text} for continuity. Table (Fact: character trait / place / object / date | First mention | Later mention | Conflict?) ; bullets reconstructing the timeline in order with any impossible gaps; a checklist of facts to verify in the rest of the manuscript.",
    "table, bullets, checklist", "Scan", "Cross-referencing…"),
  T("trim", "Trim to length", "Cut to a word count without losing the voice", "✂️",
    [LONG("text", "Text", "Paste the text…"), NUM("target", "Target word count", "800"), CH("protect", "Protect", ["Quotes", "Numbers", "Voice", "Nothing"], "Voice", True)],
    "Trim {text} to at most {target} words while protecting: {protect}. Sections: quote with the trimmed text; kv (words before, words after, percent removed); table (Cut | Why it could go) for the 10 biggest cuts; a callout on anything that could not be cut without changing the meaning.",
    "quote, kv, table, callout", "Trim it", "Cutting carefully…")])

APP("sub_splice", "Sub Splice", "Subtitles that read at the speed of speech", "Tools", ["#0D47A1", "#FFEB3B", "#00BFA5"], "clock",
 "Sub Splice condenses, splits and QCs subtitle and caption files to your reading-speed and line-length limits, adds SDH sound tags, and turns transcripts into clip captions.",
 "You are a subtitle editor who lives by characters-per-second and sensible line breaks: condense meaning, never garble it, and keep timing honest. If the profile sets no limits, apply the standard limits of the chosen platform and state them.",
 "Every cue readable", "Set your platform limits once; every cue is checked against them.", ["Reading-speed fixes per cue", "Grammar-aware line splitting", "SDH tags and full QC passes"],
 [NAME, CH("platform", "Platform", ["YouTube", "Netflix spec", "TikTok / Reels", "Broadcast", "Film festival"], "YouTube"), TXT("limits", "Limits (chars/second · chars/line)", "17 cps · 42 per line"), TXT("lang", "Subtitle language", "English")],
 [T("speed", "Fix reading speed", "Condense cues over the limit", "⏱️",
    [LONG("srt", "SRT / VTT cues", "1\n00:00:01,000 --> 00:00:03,200\nText…")],
    "Check these cues against the profile characters-per-second and characters-per-line limits: {srt}. Table (Cue | Chars / seconds | CPS | Verdict | Condensed text) for every cue, condensing only those over the limit while keeping meaning and speaker intent; quote with the corrected SRT block; kv (cues over limit, average CPS before and after, longest cue); a callout on cues that cannot be fixed without retiming.",
    "table, quote, kv, callout", "Fix speed", "Timing the reader…"),
  T("split", "Split & break lines", "Two lines that break where grammar does", "↕️",
    [LONG("text", "Cue text(s)", "Paste one or more cue texts…")],
    "Break each of these cue texts into at most two lines within the profile line limit, breaking at natural grammatical points: {text}. Table (Original | Line 1 | Line 2 | Rule applied); bullets listing the rules used (keep article with noun, do not split names, prefer bottom-heavy); quote with the final cue texts.",
    "table, bullets, quote", "Split lines", "Finding the break…"),
  T("sdh", "Add SDH tags", "Sound tags and speaker IDs", "🔊",
    [LONG("srt", "Cues", "Paste the cues…"), TXT("scene", "What is happening", "rain, a phone rings, tense music")],
    "Produce an SDH version of {srt} using the scene description: {scene}. Sections: quote with the SDH cues (bracketed sound tags, speaker IDs where speakers are off-screen or ambiguous, music descriptions); checklist of SDH conventions for the profile platform; a callout on over-tagging and tags that would exceed the reading-speed limit.",
    "quote, checklist, callout", "Add SDH", "Listening closely…"),
  T("qc", "QC pass", "Overlaps, gaps, typos, timing", "🧪",
    [LONG("srt", "Full SRT / VTT", "Paste the file…")],
    "Run a QC pass on {srt}. Table (Cue | Issue: overlap / gap under 2 frames / too short / too long / typo / inconsistent spelling / line over limit | Fix); kv (total cues, issues found, minimum duration, maximum CPS); a checklist of final delivery checks for the profile platform.",
    "table, kv, checklist", "Run QC", "Checking every cue…"),
  T("clip", "Transcript → clip captions", "Captions for a short video", "🎞️",
    [LONG("transcript", "Transcript", "Paste what is said…"), NUM("seconds", "Clip length (seconds)", "45")],
    "Turn {transcript} into captions for a {seconds}-second clip within the profile limits. Table (Cue | Text | Suggested in | Suggested out) spread evenly across the clip; quote with the result as SRT; bullets on how the first 3 seconds hook the viewer and what to trim if the clip runs long.",
    "table, quote, bullets", "Caption clip", "Cutting to length…")])

APP("fair_words", "Fair Words", "Inclusive, accessible writing without the guesswork", "Tools", ["#6A1B9A", "#26A69A", "#FFB300"], "heart",
 "Fair Words reviews text for exclusionary or ableist language, writes alt text from an image, rewrites gender-neutrally, checks writing for accessibility, and suggests content notes.",
 "You are a thoughtful inclusive-language editor: you explain the concern behind each suggestion, respect intent and context, defer to how communities name themselves, and never lecture.",
 "Write so everyone is welcome", "Tell Fair Words where your writing goes.", ["Phrase-by-phrase inclusive-language review", "Alt text from a photo", "Accessibility checks for documents"],
 [NAME, CH("context", "You write for", ["Company comms", "Marketing", "Education", "Healthcare", "Government", "Games / fiction"], "Company comms"), CH("region", "Region", ["US", "UK", "Australia / NZ", "Canada", "Global"], "Global"), TXT("guide", "Style guide you follow", "Conscious Style Guide, own")],
 [T("pass", "Inclusive-language pass", "Flag, explain, suggest", "🔍",
    [LONG("text", "Text", "Paste the text…"), CH("strict", "Sensitivity", ["Clear problems only", "Balanced", "Thorough"], "Balanced")],
    "Review {text} at sensitivity '{strict}' for the profile context and region. Table (Phrase | Concern: gendered / ableist / age / race and culture / idiom that excludes / assumption | Alternative | Why, one line); quote with the revised text; a callout on judgement calls where the original may be intentional (quoted speech, character voice, reclaimed terms).",
    "table, quote, callout", "Review", "Reading with care…"),
  T("alt", "Write alt text", "Photo → short and long descriptions", "🖼️",
    [PHOTO("Image to describe", "", True), CH("use", "Where it appears", ["Website", "Social post", "Slide deck", "Document"], "Website"), TXT("focus", "What matters in it", "the chart's upward trend")],
    "Write alt text for the image, which appears on a {use}; what matters: {focus} (if not given, decide from the image and where it appears). Sections: quote with short alt text of at most 125 characters; quote with a long description of 2 to 4 sentences for complex images; bullets on what was deliberately left out and why; a callout on when this image should be marked decorative instead.",
    "quote, bullets, callout", "Describe image", "Looking closely…"),
  T("neutral", "Gender-neutral rewrite", "Without awkward constructions", "⚖️",
    [LONG("text", "Text", "Paste the text…"), CH("style", "Technique", ["Singular they", "Rewrite to plural", "Address the reader as you", "Mixed"], "Mixed")],
    "Rewrite {text} gender-neutrally using technique '{style}'. Sections: quote with the rewrite; table (Original | Neutral | Technique used); a callout on real people named in the text whose pronouns must be confirmed, not assumed.",
    "quote, table, callout", "Rewrite", "Rebalancing…"),
  T("access", "Accessible writing check", "Headings, links, lists, acronyms", "♿",
    [LONG("text", "Document or page text", "Paste the page…")],
    "Check {text} for accessible writing. Checklist (headings in order, descriptive link text, lists for sequences, acronyms expanded on first use, no meaning carried by colour or position alone, paragraphs under 5 sentences, plain words) each marked pass or fail; table (Location | Issue | Fix); kv (headings out of order, vague link texts such as 'click here', acronyms never expanded, longest paragraph in sentences, checks passed out of 7).",
    "checklist, table, kv", "Check", "Testing readability…"),
  T("notes", "Content notes", "What readers may want warned about", "📌",
    [LONG("text", "Story, article or lesson", "Paste the text or a summary…"), CH("aud", "Audience", ["Adults", "Teens", "Children", "Mixed"], "Adults")],
    "Read {text} for an audience of {aud}. Bullets of themes that may warrant a content note, each with the passage it comes from; a quote with a one-line content note ready to paste; a callout on avoiding spoilers and over-warning.",
    "bullets, quote, callout", "Suggest notes", "Reading ahead…")])

APP("line_edit", "Line Editor", "Fiction prose tightened, sentence by sentence", "Books & Reference", ["#BF360C", "#004D40", "#FFCA28"], "bulb",
 "Line Editor works at the sentence level of your fiction: filter words, adverbs, telling, dialogue tags, POV and tense slips, and the first page an agent reads.",
 "You are a fiction line editor who protects the author's voice: you cut what is slack, name each habit precisely, and show rather than lecture.",
 "Keep the voice, lose the slack", "Tell Line Editor your genre, POV and voice so edits stay yours.", ["Sentence-level edit table", "Show-don't-tell rewrites", "POV, tense and dialogue-tag checks"],
 [NAME, CH("genre", "Genre", ["Literary", "Thriller / crime", "Romance", "Fantasy / SF", "YA", "Horror", "Memoir"], "Literary"), CH("pov", "POV & tense", ["First past", "First present", "Third limited past", "Third limited present", "Omniscient"], "Third limited past"), TXT("voice", "Voice notes", "sparse, dry humour; no semicolons")],
 [T("pass", "Line edit a passage", "Filter words, adverbs, echoes, rhythm", "✂️",
    [LONG("text", "Passage", "Paste up to a scene…"), CH("focus", "Focus", ["Everything", "Filter words & adverbs", "Sentence rhythm", "Clarity"], "Everything")],
    "Line edit {text} with focus '{focus}', keeping the profile genre, POV and voice notes. Table (Sentence | Issue: filter word / adverb / telling / echo / rhythm / vague | Rewrite); quote with the full edited passage; kv (words before, words after, adverbs removed, filter words removed); a callout naming the one habit that appears most and how to catch it in future.",
    "table, quote, kv, callout", "Edit", "Sharpening…"),
  T("show", "Show, don't tell", "Three ways to show one telling line", "🎭",
    [TXT("telling", "The telling sentence", "She was terrified.", True), TXT("context", "Scene context", "alone in a car park at night")],
    "Rewrite the telling sentence '{telling}' in context: {context} (if no context is given, invent a plausible one and name it), in the profile POV and voice. Cards with 3 shown versions (meta = technique: body / action / setting-as-mirror), each at most 2 sentences; bullets on when telling is the better choice; a callout on the cliché versions to avoid.",
    "cards, bullets, callout", "Show me", "Entering the scene…"),
  T("tags", "Dialogue tag pass", "Said, beats, and cut adverbs", "💬",
    [LONG("dialogue", "Dialogue", "Paste the exchange…")],
    "Edit the tags and beats in: {dialogue}. Sections: quote with the revised exchange (said or asked where a tag is needed, action beats instead of adverbs, tags removed where the speaker is clear); table (Original tag or beat | Change | Why); a callout on over-beating and floating heads.",
    "quote, table, callout", "Fix tags", "Listening in…"),
  T("pov", "POV & tense check", "Head-hops, slips, filtered perception", "👁️",
    [LONG("text", "Passage", "Paste the passage…")],
    "Check {text} against the profile POV and tense. Table (Line | Slip type: POV break / head-hop / tense slip / filtered perception / knowledge the narrator cannot have | Fix); bullets explaining filtered perception with examples from the text; quote with the corrected lines only.",
    "table, bullets, quote", "Check POV", "Watching the camera…"),
  T("first", "First-page verdict", "Would an agent keep reading?", "📄",
    [LONG("page", "Your first 300 words", "Paste the opening…")],
    "Assess this opening as an agent's reader would: {page}. kv (hook /10, voice /10, clarity /10, would turn the page: yes / maybe / no); bullets of what is working, quoting the words; table (Line | Problem | Fix); a quote with a punchier version of the first sentence in the same voice; a callout on the most common opening-page pet peeves this page triggers.",
    "kv, bullets, table, quote, callout", "Judge my page", "Reading as an agent…")])
