from dsl import *
SAFE = "Coaching, not therapy. If you ever feel unsafe, controlled or afraid of someone close to you, contact a domestic-abuse helpline or emergency services."
LEGAL_FAM = "Not legal advice. Custody, consent and relocation rules differ by jurisdiction; confirm arrangements with a family lawyer or mediator."

# 1 ── Couples: after a fight ────────────────────────────────────────────────
APP("repair_talk", "Repair Talk", "Come back from a fight closer than before", "Lifestyle", ["#AD1457", "#00897B", "#FFB300"], "heart",
 "Repair Talk helps couples recover after an argument: decode what the fight was really about, rewrite a criticism as a soft start, draft an apology that lands, and agree a plan so the same fight doesn't repeat.",
 "You are a warm, Gottman-informed couples coach: you side with the relationship rather than either partner, never diagnose, and keep scripts short enough to actually say out loud.",
 "Fight less, repair faster", "A little about you two makes the scripts sound like you.", ["Decode what a fight was really about", "Apologies and openers that land", "A plan so it doesn't repeat"],
 [NAME, TXT("partner", "Partner's name", "Sam"), CH("together", "Together for", ["Under 1 year", "1–3 years", "3–10 years", "10+ years"]), CH("pattern", "Our usual pattern", ["One pursues, one withdraws", "Both go loud", "Both go quiet", "Not sure"])],
 [T("decode", "Decode the fight", "Paste what happened; see what it was about", "🔍",
    [LONG("fight", "What happened", "I asked about the dishes, they said I always nag, then…"), CH("side", "I mostly felt", ["Unheard", "Attacked", "Dismissed", "Controlled", "Alone"], "Unheard")],
    "Read this argument: {fight}. The user mostly felt {side}. Produce a text section naming the surface topic versus the underlying need for each partner (2–3 sentences), a table (Moment | What was said | What it likely meant | Better move), bullets listing only the destructive patterns actually present (criticism, contempt, defensiveness, stonewalling), and a callout on the one thing to say first when you reconnect.",
    "text, table, bullets, callout", "Decode it", "Reading between…"),
  T("soften", "Soften my start", "Turn a complaint into something they can hear", "🌱",
    [LONG("complaint", "What I want to say", "You never help with bedtime and I'm exhausted"), CH("timing", "When", ["Right now", "Later today", "At our next check-in"], "Later today")],
    "Rewrite this complaint as a soft start-up (I feel… about… I need…) to raise {timing}: {complaint}. Give a quote with the rewritten opener (under 40 words), a kv (Feeling | Situation | Specific request | Good time to raise), bullets of 3 phrases to avoid, and a callout on what to do if they get defensive anyway.",
    "quote, kv, bullets, callout", "Soften it", "Rewording…"),
  T("apology", "Apologise properly", "No 'sorry you feel that way'", "🤍",
    [LONG("did", "What I did / said", "I rolled my eyes and left mid-conversation"), TXT("hurt", "How it landed for them", "they felt abandoned")],
    "Write a real apology for: {did}, which landed as: {hurt}. Sections: a quote with the spoken apology (name the act, name the impact, no 'but', one concrete change), a checklist of the 5 parts of a complete apology with each marked as present or missing in this draft, and a callout on what not to expect straight after apologising.",
    "quote, checklist, callout", "Write it", "Owning it…"),
  T("repeat", "Stop the repeat fight", "Same argument, third time this month", "🔁",
    [LONG("theme", "The recurring fight", "money — I save, they spend on takeaways"), CH("tried", "We've already tried", ["Talking it out", "Avoiding it", "Compromise that didn't stick", "Nothing yet"], "Talking it out")],
    "This fight keeps returning: {theme}; already tried: {tried}. Give text explaining whether this looks solvable or a perpetual difference (2–3 sentences), a table (Underlying need | Partner A | Partner B | Where they overlap), steps for a 20-minute structured conversation with a time-box per step, and a callout on the sign that means pause and see a couples therapist.",
    "text, table, steps, callout", "Break the loop", "Untangling…"),
  T("reconnect", "Reconnect tonight", "Small repair rituals after a rough week", "✨",
    [CH("mood", "Right now we're", ["Cool but civil", "Walking on eggshells", "Fine but distant", "Ready to reconnect"], "Fine but distant"), NUM("minutes", "Minutes we have", "30")],
    "We're {mood} and have {minutes} minutes tonight. Suggest 4 repair rituals as cards (meta = minutes · effort low/med), then a quote with an exact opening line for the best one, and bullets of 3 questions that invite closeness without reopening the fight.",
    "cards, quote, bullets", "Suggest rituals", "Warming up…")], SAFE)

# 2 ── Long-distance ─────────────────────────────────────────────────────────
APP("miles_apart", "Miles Apart", "Long-distance love that feels close", "Lifestyle", ["#1E88E5", "#F4511E", "#8E24AA"], "plane",
 "Miles Apart keeps long-distance couples connected: finds the hours you're both awake, plans virtual dates and visits worth the airfare, and maps the path to living in the same place.",
 "You are an upbeat long-distance-relationship coach who has done it yourself: practical about time zones and budgets, honest about the hard parts, never saccharine.",
 "Closer than the map says", "Tell us where you both are and how often you can visit.", ["Overlap hours across time zones", "Virtual dates beyond video calls", "A real plan to close the gap"],
 [NAME, TXT("partner", "Partner's name", "Priya"), TXT("cities", "Your city → their city", "Manchester → Toronto"), CH("visits", "We see each other", ["Every few weeks", "Every 2–3 months", "Twice a year", "Rarely"])],
 [T("overlap", "Find our hours", "When we're both awake and free", "🕰️",
    [TXT("mine", "My typical day", "work 9–6, gym 7pm, bed 11:30"), TXT("theirs", "Their typical day", "shifts 7–3, free evenings, bed 10")],
    "Using the profile cities for time zones, my day: {mine}; their day: {theirs}. Produce a table (My local time | Their local time | Both free? | Best use) for each waking hour of a typical weekday, a kv (Golden window weekdays | Golden window weekends | Overlap hours per week | Who is losing sleep), bullets of the best weekend windows, and a callout on the daylight-saving dates that will shift this schedule.",
    "table, kv, bullets, callout", "Find overlap", "Syncing clocks…"),
  T("vdate", "Plan a virtual date", "Better than 'so how was your day'", "🎬",
    [CH("vibe", "Vibe", ["Playful", "Romantic", "Cook together", "Deep talk", "Lazy Sunday"], "Playful"), NUM("length", "Minutes", "90"), TXT("budget", "Budget", "under 20")],
    "Design 4 virtual dates that are {vibe}, about {length} minutes, budget {budget}, as cards (meta = minutes · cost · prep needed). Then steps to run the best one from opening message to goodnight, and a checklist of what each person sets up beforehand.",
    "cards, steps, checklist", "Plan the date", "Setting the scene…"),
  T("visit", "Make the visit count", "Plan the days you actually get", "🧳",
    [NUM("days", "Days together", "4"), CH("where", "Where", ["My place", "Their place", "Meet in the middle"], "Their place"), TXT("wishes", "We both want to", "one proper dinner, meet their friends, do nothing one day")],
    "Plan {days} days at {where} with these wishes: {wishes}. Table (Day | Morning | Afternoon | Evening | Alone time?), a callout on the re-entry wobble (first hours awkward, last day sad) and how to handle both, bullets of 3 conversations worth having in person rather than on a call, and a checklist for the goodbye day.",
    "table, callout, bullets, checklist", "Plan the visit", "Packing…"),
  T("drift", "We're drifting", "When calls feel like a chore", "🌫️",
    [LONG("whats_up", "What's going on", "calls got short, they seem distracted, I'm resentful about always booking flights"), CH("want", "I want to", ["Raise it gently", "Understand what's happening", "Decide if this still works"], "Raise it gently")],
    "Situation: {whats_up}. Goal: {want}. Text naming the likely dynamic in plain words (2–3 sentences, no blame), a quote with an opening message or line to send tonight, bullets of what to listen for in their reply, and a callout on the difference between a rough patch and a sign to reconsider.",
    "text, quote, bullets, callout", "Help me", "Thinking it through…"),
  T("close", "Close the distance", "The plan to end up in one place", "🗺️",
    [CH("horizon", "Target", ["6 months", "1 year", "2 years", "Not sure"], "1 year"), TXT("blockers", "What's in the way", "her visa, my lease, whose job moves")],
    "Build a closing-the-gap plan over {horizon} given blockers: {blockers}. Table (Milestone | Who | By when | Depends on), steps for the next 30 days, a kv of the honest questions each partner must answer alone first, and a callout that visa and employment rules vary and need official checking.",
    "table, steps, kv, callout", "Build the plan", "Plotting the route…")], "Relationship coaching only; immigration and employment rules must be checked with official sources.")

# 3 ── In-laws ───────────────────────────────────────────────────────────────
APP("inlaw_bridge", "In-Law Bridge", "Keep the peace with their family, and your sanity", "Lifestyle", ["#6D4C41", "#43A047", "#FB8C00"], "home",
 "In-Law Bridge helps you handle your partner's family: decode loaded comments, agree a united front with your partner, split the holidays fairly, and host or visit without the usual friction.",
 "You are a diplomatic family mediator with a sense of humour: you assume good intent until proven otherwise, keep the couple as the primary team, and give words people can actually say to a mother-in-law.",
 "Two families, one team", "Tell us who's who and where it gets tense.", ["Decode what that comment meant", "United-front scripts with your partner", "Holiday splits that feel fair"],
 [NAME, TXT("partner", "Partner's name", "Jo"), TXT("inlaws", "The in-laws (names, roles)", "Margaret (MIL), Dave (FIL), sister Claire"), CH("friction", "Main friction", ["Unsolicited advice", "Boundaries at visits", "Favouritism / comparison", "Parenting comments", "Money", "None yet"], multi=True)],
 [T("decode", "What did they mean?", "A comment that's still bothering you", "💬",
    [LONG("comment", "What they said", "'Oh, you're feeding him that?'"), TXT("context", "Context", "at Sunday lunch, in front of everyone")],
    "They said: {comment}. Context: {context}. Give a table (Reading | How likely | Evidence) with 3 possible meanings from innocent to pointed, a quote with a light non-escalating reply to use next time, a second quote with a firmer reply if it's a pattern, and a callout on whether this is worth raising with your partner.",
    "table, quote, callout", "Decode", "Reading the room…"),
  T("united", "United front", "Get on the same page as your partner first", "🤝",
    [LONG("issue", "The issue", "his mum drops in unannounced and rearranges the kitchen"), CH("partner_view", "My partner thinks", ["It's no big deal", "Agrees but won't say anything", "Sides with me", "We haven't discussed it"], "Agrees but won't say anything")],
    "Issue: {issue}. Partner's stance: {partner_view}. Steps for a 15-minute conversation with your partner that ends in an agreed line rather than a debate about their family, a quote with the script your partner can say to their own parent (the message should come from the blood relative), a kv (What we'll accept | What we won't | What happens if it continues), and a callout on avoiding the 'me versus your mum' trap.",
    "steps, quote, kv, callout", "Align us", "Team talk…"),
  T("holidays", "Split the holidays", "Whose family gets what", "🎄",
    [TXT("occasions", "Occasions in play", "Christmas, Eid, both mums' birthdays"), TXT("distance", "Distances", "mine 1h drive, theirs a flight"), CH("kids", "Kids involved?", ["No", "Yes, young", "Yes, older"], "No")],
    "Occasions: {occasions}; distances: {distance}; kids: {kids}. Propose 3 rotation systems as cards (meta = fairness · travel load), a table for the next 2 years (Occasion | Year 1 | Year 2 | Notes), a quote announcing the plan to both families warmly, and bullets on handling the family that feels short-changed.",
    "cards, table, quote, bullets", "Propose a split", "Drawing the rota…"),
  T("boundary", "Set a boundary kindly", "Firm, warm, no drama", "🚧",
    [LONG("what", "What needs to change", "she comments on my weight every visit"), CH("who_says", "Who delivers it", ["Me", "My partner", "Both of us together"], "My partner")],
    "Boundary needed: {what}. Delivered by: {who_says}. A quote with the exact wording (under 50 words, warm then clear), steps for the delivery (when, where, what to do right after), a table (If they say… | You say…) with 4 common pushbacks, and a callout on holding it the first three times without re-explaining.",
    "quote, steps, table, callout", "Word it", "Choosing words…"),
  T("visit", "Survive the visit", "Hosting them or staying there", "🧳",
    [CH("type", "Visit", ["They're staying with us", "We're staying with them", "Day visit"], "They're staying with us"), NUM("days", "Days", "3"), TXT("worries", "What I'm dreading", "no privacy, comments on how we parent")],
    "Visit type: {type}, {days} days, dreading: {worries}. Checklist to prep (space, food, ground rules agreed with partner), a table (Day | Plan | Built-in break | Who hosts that slot), bullets of 5 safe conversation topics and 3 to avoid, and a quote with a graceful exit line for when you need ten minutes alone.",
    "checklist, table, bullets, quote", "Plan the visit", "Fluffing pillows…")])

# 4 ── Co-parenting after separation ─────────────────────────────────────────
APP("coparent_calm", "Co-Parent Calm", "Raise the kids together, even apart", "Parenting", ["#00838F", "#7CB342", "#FFA000"], "calendar",
 "Co-Parent Calm helps separated parents keep messages businesslike, build custody and holiday schedules that work, handle disagreements, and explain changes to the kids in words that don't wound.",
 "You are a steady co-parenting coordinator: child-centred, allergic to point-scoring, and precise about keeping written communication brief, informative, friendly and firm.",
 "Kids first, drama last", "Tell us about the kids and the current arrangement.", ["Messages rewritten to defuse, not escalate", "Custody and holiday schedules", "Age-appropriate scripts for the kids"],
 [NAME, TXT("kids", "Kids (names, ages)", "Leo 6, Ava 9"), TXT("ex", "Co-parent's name", "Chris"), CH("tone", "Communication is", ["Civil", "Tense", "Hostile", "Minimal"])],
 [T("biff", "Rewrite my message", "Brief, informative, friendly, firm", "✉️",
    [LONG("draft", "What I want to send", "You're late AGAIN and Leo was crying, this is the third time…"), CH("goal", "I need", ["An answer", "A change in behaviour", "To document it", "To decline a request"], "A change in behaviour")],
    "Rewrite this message so it is brief, informative, friendly and firm, goal: {goal}: {draft}. Give a quote with the rewritten message (under 80 words, no blame words, no questions they can dodge), a table (Original phrase | Why it escalates | Replacement), a callout on what to leave out entirely, and bullets on when to simply not reply.",
    "quote, table, callout, bullets", "Rewrite", "Cooling it down…"),
  T("schedule", "Build a schedule", "2-2-3, week-on/off, or custom", "📅",
    [CH("split", "Time split", ["50/50", "60/40", "70/30", "Every other weekend"], "50/50"), TXT("constraints", "Constraints", "I work nights Mon–Wed, school is nearer my ex"), CH("ages", "Youngest child is", ["Under 3", "3–6", "7–12", "Teen"], "3–6")],
    "Design custody schedules for a {split} split, constraints: {constraints}, youngest child {ages}. Present 3 options as cards (meta = transitions per week · longest gap from each parent), a table of the recommended option over a 2-week cycle (Day | With | Handover time | Handover place), bullets on why fewer transitions matter at this age, and a callout that any schedule should be written into a formal parenting plan.",
    "cards, table, bullets, callout", "Build options", "Drawing the weeks…"),
  T("holidays", "Holiday plan", "Birthdays, school breaks, festivals", "🎂",
    [TXT("dates", "Occasions this year", "Xmas, Easter break, Leo's birthday 14 May, summer 6 weeks"), CH("method", "Preferred method", ["Alternate years", "Split each holiday", "Fixed by tradition", "Suggest for me"], "Suggest for me")],
    "Allocate these occasions: {dates} using {method}. Table (Occasion | This year | Next year | Handover details), a quote with the message proposing it to the co-parent, a checklist of details to agree in advance (travel, gifts, calls with the other parent), and a callout on keeping birthdays about the child rather than the parents.",
    "table, quote, checklist, callout", "Allocate", "Splitting dates…"),
  T("disagree", "We disagree", "School, screens, medical, new partners", "⚖️",
    [LONG("issue", "The disagreement", "they want to move Ava to a private school 40 min away"), CH("stakes", "Stakes", ["Minor — let it go?", "Medium", "Major — affects the kids' lives"], "Medium")],
    "Disagreement: {issue}, stakes: {stakes}. Text separating what is genuinely about the child from what is about the adults (2–3 sentences), a table (Option | Effect on child | Effect on each parent | Reversible?), steps to propose a trial period or mediation, and a callout on which decisions typically need both parents' consent and when to seek legal advice.",
    "text, table, steps, callout", "Work it through", "Weighing it…"),
  T("kidtalk", "Tell the kids", "Explaining changes at their level", "🧒",
    [LONG("change", "What's changing", "Dad is moving in with his girlfriend and her son"), CH("who", "Telling", ["One child", "All together", "Each separately"], "All together")],
    "Change to explain: {change}, telling {who}. Using the profile ages, give a quote with a short script per child (honest, no adult details), bullets of the questions they will probably ask with one-line answers, a checklist for the week after, and a callout on signs a child is struggling and may need extra support.",
    "quote, bullets, checklist, callout", "Draft the talk", "Finding the words…")], LEGAL_FAM)

# 5 ── Boundaries ────────────────────────────────────────────────────────────
APP("boundary_lines", "Boundary Lines", "Say no without the guilt spiral", "Lifestyle", ["#37474F", "#E53935", "#FDD835"], "shield",
 "Boundary Lines gives you the words to decline, delay and draw a line — with a boss, a parent, a friend or a partner — and helps you hold it when the pushback comes.",
 "You are a direct, kind assertiveness coach: you distinguish boundaries (what you will do) from control (what others must do), keep scripts short, and never shame the user for wanting to be liked.",
 "Your yes should mean yes", "Tell us where saying no is hardest.", ["Scripts for the awkward no", "Handle pushback without folding", "Know when a boundary is reasonable"],
 [NAME, CH("hardest", "Hardest to say no to", ["Parents", "Partner", "Friends", "Boss / colleagues", "Kids", "Everyone"], multi=True), CH("style", "When pushed I usually", ["Cave", "Over-explain", "Go cold", "Blow up"])],
 [T("decline", "Say no to this", "A request you don't want to accept", "🙅",
    [LONG("ask", "The request", "my sister wants me to host Christmas again"), CH("relationship", "From", ["Family", "Partner", "Friend", "Work", "Neighbour / other"], "Family"), CH("firmness", "Firmness", ["Soft no", "Clear no", "Final no"], "Clear no")],
    "Request: {ask}, from {relationship}, firmness level {firmness}. Give 3 quote sections — a text-message version, a spoken version, and a one-liner for when you're put on the spot — each under 40 words with no apology stacking. Then bullets on what NOT to add (excuses, over-explaining), and a callout on the guilt that follows and why it fades.",
    "quote, bullets, callout", "Give me words", "Drafting the no…"),
  T("pushback", "They pushed back", "Rehearse round two", "🔁",
    [LONG("said", "What they said after your no", "'After everything I've done for you?'"), CH("goal", "I want to", ["Hold the line", "Offer a smaller yes", "End the conversation"], "Hold the line")],
    "After the no, they said: {said}. Goal: {goal}. Text naming the tactic in one sentence (guilt, urgency, silence, bargaining) without demonising them, a table (If they say… | You say… | Then you do…) with 4 rounds, a quote with the broken-record line to repeat verbatim, and a callout on when leaving the room is the boundary.",
    "text, table, quote, callout", "Prep round two", "Bracing…"),
  T("reasonable", "Is this reasonable?", "Check a boundary before you set it", "🧭",
    [LONG("boundary", "The boundary I want", "no work messages after 7pm"), TXT("cost", "What it costs them", "my manager loses evening availability")],
    "Proposed boundary: {boundary}. Cost to others: {cost}. Assess it in a kv (Boundary or control? | Reasonable? | Likely reaction | Your part to own), text explaining the verdict in 2–3 sentences, a quote with the boundary reworded as what YOU will do rather than what THEY must do, and bullets of 3 ways to soften delivery without softening substance.",
    "kv, text, quote, bullets", "Check it", "Weighing it up…"),
  T("audit", "Weekly asks audit", "Where your time and energy actually went", "📋",
    [LONG("asks", "Requests you got this week", "Mum: drive her Tues; boss: weekend deck; friend: lend £200; school: bake sale")],
    "Requests this week: {asks}. Table (Request | You said | Wanted to say | Cost to you 1–5 | Pattern), bullets naming the 2 patterns that show up most, steps for one boundary to set next week starting with the lowest-stakes person, and a quote with the opening line for that conversation.",
    "table, bullets, steps, quote", "Audit", "Tallying asks…"),
  T("guilt", "Guilt talk-down", "The spiral after you held the line", "🌀",
    [LONG("feeling", "What's going round your head", "I'm selfish, she'll never forgive me, I should just call and say yes")],
    "Thoughts after holding a boundary: {feeling}. Text with a calm reality-check (3–4 sentences, no toxic positivity), a table (Thought | Distortion | Fairer version), a checklist for the next 24 hours (no undoing texts, one grounding action, one kind thing for yourself), and a callout on when persistent guilt or fear suggests talking to a therapist.",
    "text, table, checklist, callout", "Talk me down", "Steadying…")], SAFE)

# 6 ── Adult friendship ──────────────────────────────────────────────────────
APP("friend_keeper", "Friend Keeper", "Keep the friendships that matter from fading", "Social", ["#F9A825", "#00ACC1", "#EC407A"], "star",
 "Friend Keeper helps busy adults maintain real friendships: reconnect after months of silence, plan hangs that fit real life, handle a falling-out, and know when a friendship has run its course.",
 "You are a loyal, unfussy friend-of-friends: you know adult friendship survives on small consistent gestures, you never guilt the user for a long gap, and you write messages that sound like a person, not a greeting card.",
 "Good friends, kept", "Tell us about the people you don't want to lose.", ["Reconnect messages that don't feel awkward", "Low-effort hangs for full calendars", "Repair or release a friendship"],
 [NAME, TXT("friends", "Friends you want to keep close", "Ben (uni), Rosa (old job), the Thursday group"), CH("life", "Life stage", ["Studying", "Early career", "Young kids", "Mid-life busy", "Kids left home", "Retired"]), CH("energy", "Social energy", ["Low", "Medium", "High"])],
 [T("reconnect", "Reconnect", "It's been months; break the silence", "📱",
    [TXT("who", "Friend", "Rosa", True), TXT("gap", "Since when / why", "8 months — she had a baby, I moved"), CH("channel", "Send via", ["Text", "Voice note", "Email", "Call script"], "Text")],
    "Write a reconnect to {who} after a gap of {gap}, via {channel}. Give 3 quote sections (light, warm, honest-about-the-gap) each under 60 words, none opening with an apology, each ending with a low-pressure specific suggestion. Then bullets on what to do if they don't reply within a fortnight, and a callout on why the gap is rarely as loaded for them as for you.",
    "quote, bullets, callout", "Write it", "Warming up…"),
  T("hang", "Plan a hang", "Fits both calendars, costs little", "🍜",
    [TXT("who", "Who", "the Thursday group", True), TXT("limits", "Constraints", "we all have kids, weeknights only, 2 hours max"), NUM("budget", "Budget each", "20")],
    "Plan hangs with {who} within: {limits}, about {budget} per person. 5 ideas as cards (meta = hours · cost · planning effort), a quote with the group message proposing the top pick with two date options, and a checklist for the organiser so it actually happens.",
    "cards, quote, checklist", "Suggest hangs", "Finding a slot…"),
  T("fallout", "We fell out", "Say the hard thing without losing them", "💔",
    [LONG("what", "What happened", "she skipped my birthday, then posted from another party"), CH("want", "I want to", ["Clear the air", "Get an apology", "Understand their side", "Decide if it's worth it"], "Clear the air")],
    "Falling-out: {what}. I want to {want}. Text with a fair reading of both sides (3–4 sentences), a quote with an opening message that names the hurt without an accusation, a table (If they respond with… | It probably means | Your next move) with 4 responses, and a callout on the difference between a repairable rupture and a pattern.",
    "text, quote, table, callout", "Help me say it", "Choosing words…"),
  T("fade", "Is it fading?", "One-sided? Outgrown? Just busy?", "🌅",
    [LONG("signs", "What you've noticed", "I always initiate, cancels last minute, but great when we do meet"), NUM("years", "Years of friendship", "12")],
    "Signs: {signs}, friendship of {years} years. Give a kv (Most likely: busy, drifting, one-sided or outgrown | Confidence | What would confirm it), bullets of 3 low-cost tests over the next month, a quote with a direct-but-kind check-in line, and text on how to let a friendship go down a gear without a dramatic ending.",
    "kv, bullets, quote, text", "Read the signs", "Looking closer…"),
  T("milestone", "Say something real", "Birthday, promotion, loss, big news", "🎈",
    [TXT("who", "Friend", "Ben", True), TXT("event", "What's happened", "his dad died last week", True), CH("form", "Form", ["Text", "Card", "Voice note", "In person"], "Text")],
    "Write a {form} message to {who} about: {event}. Give 2 quote sections — one short (under 30 words) and one fuller (under 90 words) — specific to this friend and event, avoiding clichés. Then bullets of 3 concrete offers of help or celebration that are easy to accept, and a callout on the follow-up to send a few weeks later.",
    "quote, bullets, callout", "Write it", "Meaning it…")])

# 7 ── Stepparenting / blended families ─────────────────────────────────────
APP("step_ahead", "Step Ahead", "Find your footing as a stepparent", "Parenting", ["#5E35B1", "#26A69A", "#FF7043"], "baby",
 "Step Ahead helps stepparents and blended families find their role: how involved to be and when, discipline agreements with your partner, new-family rituals, and what to say to 'you're not my mum'.",
 "You are a seasoned blended-family counsellor: patient about the years it takes, clear that the biological parent leads on discipline early on, and respectful of the other household.",
 "Blend without breaking", "Tell us who's in the family and how long you've been together.", ["Your role, stage by stage", "Discipline agreements with your partner", "Rituals that make a new family"],
 [NAME, TXT("kids", "Stepkids and my kids (names, ages, whose)", "Mia 8 (theirs), Tom 14 (theirs), Ella 5 (mine)"), CH("stage", "Together", ["Dating", "Living together under 1 year", "1–3 years", "3+ years"]), CH("other_home", "Other parent", ["Involved, civil", "Involved, tense", "Absent", "Deceased"])],
 [T("role", "My role right now", "Involved enough, not too much", "🧭",
    [LONG("situation", "What's happening", "Tom ignores me, partner wants me to enforce homework"), CH("push", "I'm being pushed to", ["Do more discipline", "Step back", "Be 'a parent' already", "Nothing — just unsure"], "Do more discipline")],
    "Situation: {situation}; pressure: {push}. Given the profile stage, give text on the realistic role for this stage in 3–4 sentences, a table (Area | Stepparent does | Bio parent does | Not yet), a quote with what to say to your partner about the ask, and a callout on the typical timeline for bonding with older kids.",
    "text, table, quote, callout", "Define my role", "Finding footing…"),
  T("discipline", "Discipline agreement", "Same rules, agreed in private", "📜",
    [LONG("flashpoints", "Where rules clash", "screens at bedtime, swearing, chores"), CH("who_enforces", "Currently", ["Bio parent enforces", "I enforce", "Nobody consistently", "Depends who's home"], "Depends who's home")],
    "Flashpoints: {flashpoints}; enforcement now: {who_enforces}. Build a table (Rule | Applies to whom | Who enforces | Consequence), steps for the private partner meeting to agree it, a quote with how the bio parent introduces the rules to the kids (stepparent present but not presenting), and a callout on the 'monitor, don't discipline' principle for the first year.",
    "table, steps, quote, callout", "Draft agreement", "Aligning rules…"),
  T("notmine", "'You're not my mum'", "The line every stepparent hears", "🛡️",
    [LONG("said", "What the child said / did", "'You can't tell me what to do, you're not my dad'"), CH("age", "Child's age", ["Under 6", "6–10", "11–14", "15+"], "11–14")],
    "The child ({age}) said: {said}. Give a quote with a calm in-the-moment reply (under 25 words, agrees with the true part, holds the house rule), text on what the child is really testing (2–3 sentences), bullets of 3 things not to say, and a checklist for the follow-up with your partner that evening.",
    "quote, text, bullets, checklist", "Reply well", "Staying calm…"),
  T("rituals", "New-family rituals", "Traditions that belong to this household", "🍕",
    [CH("freq", "Frequency", ["Weekly", "Monthly", "Holidays", "Transitions between homes"], "Weekly"), TXT("likes", "What the kids enjoy", "Mia loves baking, Tom gaming, Ella dinosaurs")],
    "Suggest {freq} rituals for this blended family, kids' interests: {likes}. 5 cards (meta = minutes · cost · which kids), a quote with how to pitch the first one without making it a big deal, bullets on including the kids' other-household traditions respectfully, and a callout on what to do when a child refuses to join.",
    "cards, quote, bullets, callout", "Suggest rituals", "Blending…"),
  T("loyalty", "Loyalty binds", "Kids caught between two homes", "💞",
    [LONG("signs", "What you're seeing", "Mia says she's not allowed to like me, goes quiet after weekends at her mum's")],
    "Observed: {signs}. Text explaining loyalty binds in plain language (3 sentences), a quote with what the stepparent can say to the child to release the pressure, a second quote for the bio parent to say, a checklist of things never to say about the other household, and a callout on when a family therapist helps.",
    "text, quote, checklist, callout", "Ease the bind", "Untangling…")], "Family coaching only. Custody, consent and safeguarding matters should be checked with a family lawyer or child-welfare professional.")

# 8 ── Difficult relatives / low contact ─────────────────────────────────────
APP("grey_rock", "Grey Rock", "Stay steady with a difficult relative", "Lifestyle", ["#546E7A", "#8D6E63", "#26C6DA"], "moon",
 "Grey Rock helps you deal with a parent, sibling or relative who guilts, manipulates or explodes: low-reaction replies, plans for visits and holidays, contact levels that protect you, and support for the grief that comes with it.",
 "You are a trauma-informed family-dynamics coach: you never diagnose the relative, you name behaviours not labels, you respect the user's choice on how much contact to keep, and you put the user's safety first.",
 "You don't have to take the bait", "Tell us who the difficult person is and what contact looks like now.", ["Low-reaction replies that end the loop", "Visit and holiday survival plans", "Decide contact levels without guilt"],
 [NAME, TXT("person", "The person (relationship)", "my mother"), CH("behaviours", "What they do", ["Guilt trips", "Criticism", "Rage", "Silent treatment", "Rewriting history", "Triangulating others", "Money control"], multi=True), CH("contact", "Contact now", ["Daily", "Weekly", "Occasional", "Low contact", "No contact"])],
 [T("reply", "Grey-rock reply", "Respond without feeding it", "🪨",
    [LONG("message", "What they sent / said", "'I guess I'm just a terrible mother then. Don't bother coming Sunday.'"), CH("channel", "Via", ["Text", "Call", "In person", "Through a relative"], "Text")],
    "They said ({channel}): {message}. Text identifying the hook in one sentence (guilt, threat, bait, reversal), then 3 quote sections: minimal (under 12 words), neutral-informational (under 30 words), and no-reply with what to do instead; then a table (If they escalate with… | Your response) for 3 escalations, and a callout on not justifying, arguing, defending or explaining.",
    "text, quote, table, callout", "Draft reply", "Going grey…"),
  T("visit", "Visit survival plan", "Get in, get out, stay intact", "🚪",
    [TXT("event", "The occasion", "Dad's 70th, 4 hours at their house"), TXT("ally", "Who's on your side there", "my brother, my partner")],
    "Occasion: {event}; allies: {ally}. Steps for before, during and after (arrival time, exit line, ride home), a checklist of things to arrange with allies beforehand (signal, seating, rescue), bullets of 5 safe topics and 3 to deflect, a quote with the exact exit line, and a callout on the emotional crash the day after.",
    "steps, checklist, bullets, quote, callout", "Plan it", "Mapping exits…"),
  T("contact", "Contact level", "More, less, or none — thinking it through", "📉",
    [LONG("why", "What's prompting the question", "every call ends with me crying; she told my aunt I'm unstable"), CH("leaning", "I'm leaning towards", ["Keep as is", "Reduce", "Structured low contact", "A break", "No contact"], "Reduce")],
    "Prompting this: {why}; leaning: {leaning}. Give a table (Option | What it looks like | Cost to you | Cost to others | Reversible?) across 4 contact levels, a kv of rules for the leaning option (frequency, channels, topics off-limits, what ends a call), a quote announcing the change if one is needed (short, no justification), and a callout on grief and doubt being normal and not evidence of a wrong decision.",
    "table, kv, quote, callout", "Think it through", "Weighing options…"),
  T("reality", "Reality check", "Am I overreacting?", "🔍",
    [LONG("incident", "What happened", "she 'forgot' my birthday then said I never call"), TXT("pattern", "Has this happened before?", "yes, most years")],
    "Incident: {incident}; pattern: {pattern}. Text with a plain, non-diagnostic read of the behaviour (3 sentences), a table (What they said | What happened | What you're being asked to believe), bullets of what a reasonable person could feel here, and a callout on keeping a dated log for your own clarity.",
    "text, table, bullets, callout", "Check reality", "Looking clearly…"),
  T("relay", "Relatives who relay", "When others carry messages for them", "📨",
    [LONG("said", "What the relay said", "Auntie says mum is heartbroken and I should just apologise"), TXT("relay", "Who relayed it", "my aunt")],
    "Relayed by {relay}: {said}. A quote with a warm-but-closed reply to the relay (keeps the relationship, refuses the errand, under 40 words), bullets on what not to share with anyone who reports back, a table (If the relay says… | You say…) with 3 follow-ups, and a callout on protecting the relatives you still want.",
    "quote, bullets, table, callout", "Reply", "Closing the loop…")], "Coaching, not therapy or a diagnosis of anyone. If you are in danger, being threatened or financially controlled, contact a support line or emergency services.")

# 9 ── Mental load / household labour ────────────────────────────────────────
APP("invisible_load", "Invisible Load", "Share the mental load, not just the chores", "Lifestyle", ["#3949AB", "#FF6F00", "#00ACC1"], "scale",
 "Invisible Load makes the hidden work of running a home visible — the noticing, planning and remembering — then helps couples split it fairly, talk about it without a fight, and keep the deal alive.",
 "You are a fair-minded household-labour coach: you count noticing and planning as work, you avoid gender score-keeping, and you give couples language and systems rather than lectures.",
 "See the whole job", "Tell us who lives here and how the work feels right now.", ["Inventory every invisible task", "Split by ownership, not favours", "Raise it without starting a fight"],
 [NAME, TXT("partner", "Partner's name", "Alex"), TXT("household", "Household", "2 adults, 2 kids (4 and 7), a dog"), CH("feel", "Right now it feels", ["Fair", "A bit lopsided", "Very lopsided", "We fight about it"])],
 [T("inventory", "Inventory the load", "Everything that keeps this house running", "📋",
    [LONG("week", "A typical week, as it happens", "I book dentist, remember PE kit, plan meals, Alex cooks Tue/Thu, bins…"), CH("include", "Include", ["Kids", "Pets", "Extended family", "Finances", "Home maintenance"], multi=True)],
    "From this week: {week}, covering {include}. Build a table (Task | Notice and plan | Execute | Owned by now | Hours per week est.) with at least 20 rows including the invisible planning tasks implied but not mentioned, a kv (Total tasks | Owned by each partner | Tasks with no clear owner | Biggest invisible task), and a callout on why noticing and planning count as work.",
    "table, kv, callout", "Make it visible", "Counting everything…"),
  T("split", "Re-split fairly", "Full ownership, start to finish", "⚖️",
    [LONG("tasks", "Tasks to re-split", "meal planning, school admin, laundry, bills, birthday gifts"), TXT("constraints", "Constraints", "Alex travels Mon–Wed; I work weekends")],
    "Re-split: {tasks} given {constraints}. Table (Task | New owner | Standard we agree on | Done by when), bullets on the minimum standard each task needs so the owner can do it their own way, steps for a 30-minute deal meeting, and a callout on the trap of one partner as manager and the other as helper.",
    "table, bullets, steps, callout", "Split it", "Balancing…"),
  T("raise", "Raise it with my partner", "Without 'you never…'", "💬",
    [LONG("frustration", "What I'm frustrated about", "I plan every meal and they ask 'what's for dinner' like it's magic"), CH("mood", "Their likely reaction", ["Defensive", "Willing but oblivious", "Dismissive", "Already tried, slid back"], "Willing but oblivious")],
    "Frustration: {frustration}; partner will probably be {mood}. Give a quote with an opener (under 60 words, one specific example, an invitation not an indictment), a table (If they say… | You say…) with 4 replies, bullets on what to leave out, and a callout on picking a time that isn't mid-task.",
    "quote, table, bullets, callout", "Word it", "Choosing words…"),
  T("meeting", "Weekly household meeting", "15 minutes, one agenda", "🗓️",
    [TXT("coming", "Coming up this week", "school trip Thu, Alex's mum visiting Sat"), CH("issues", "Anything slipping?", ["Nothing", "One task keeps dropping", "Resentment building", "New season or schedule"], "Nothing")],
    "This week: {coming}; status: {issues}. Produce a 15-minute agenda as steps with minutes per item (appreciations, what's coming, who has what, one fix, calendar), a checklist of decisions to leave the meeting with, and a quote with a light way to open it so it doesn't feel like a performance review.",
    "steps, checklist, quote", "Build agenda", "Setting the table…"),
  T("slipped", "The deal slipped", "Back to doing it all again", "📉",
    [LONG("what", "What's slipped", "I'm back to doing all the school admin"), NUM("weeks", "Weeks since the deal", "6")],
    "Deal slipped: {what}, {weeks} weeks after agreeing. Text with the most likely reason (unclear standard, no deadline, silent takeover, life change) in 2–3 sentences, a table (Task | Original agreement | What happened | Fix), a quote with a non-accusing reset line, and a callout on the difference between a lapse and a partner who has quietly opted out.",
    "text, table, quote, callout", "Reset the deal", "Rebalancing…")])

# 10 ── Pre-commitment conversations ─────────────────────────────────────────
APP("big_talks", "Big Talks", "The conversations to have before you commit", "Lifestyle", ["#C2185B", "#303F9F", "#FFC107"], "ring",
 "Big Talks guides couples through the conversations that matter before moving in, getting engaged or having kids — money, chores, family, faith, ambition, deal-breakers — and turns two sets of answers into clear agreements.",
 "You are a candid pre-marital counsellor: curious rather than prescriptive, alert to avoidance, and good at turning 'we'll figure it out' into specifics without killing the romance.",
 "Know before you leap", "Tell us what you're heading towards and we'll tailor the questions.", ["Question decks by topic", "Compare your answers side by side", "Draft agreements you'll both keep"],
 [NAME, TXT("partner", "Partner's name", "Dan"), CH("next", "Next step", ["Moving in", "Engagement", "Marriage", "Kids", "Buying a home", "Just checking we're aligned"]), TXT("worry", "What we avoid talking about", "money, his mum")],
 [T("deck", "Question deck", "Ten questions on one topic", "🃏",
    [CH("topic", "Topic", ["Money", "Chores & home", "Kids & parenting", "Family & in-laws", "Faith & values", "Sex & intimacy", "Careers & ambition", "Deal-breakers"], "Money"), CH("depth", "Depth", ["Warm-up", "Real talk", "Deep end"], "Real talk")],
    "Give 10 {topic} questions at {depth} level for a couple heading for the profile's next step, as a checklist (one question per item, specific, none answerable with yes or no). Then a callout on how to run it (take turns, no interrupting, one 'pass' each), and a quote with a closing question that brings it back to warmth.",
    "checklist, callout, quote", "Deal the deck", "Shuffling…"),
  T("compare", "Compare our answers", "Paste both sets; find the gaps", "🔍",
    [LONG("mine", "My answers", "Money: joint account for bills, separate for fun; kids: 2, in ~3 years…"), LONG("theirs", "Their answers", "Money: everything joint; kids: maybe 1, not soon…")],
    "Compare my answers: {mine} with theirs: {theirs}. Table (Question | Me | Them | Aligned, negotiable or gap), bullets of the 3 biggest gaps in order of importance to the next step, steps for one structured conversation on the top gap, and a callout that most gaps are negotiable but naming the non-negotiables early is the kindest thing you can do.",
    "table, bullets, steps, callout", "Compare", "Lining them up…"),
  T("agreement", "Draft an agreement", "Money, chores or family — written down", "📝",
    [CH("area", "Area", ["Money & bills", "Chores & standards", "Family visits & holidays", "Screens & alone time", "Pets"], "Money & bills"), LONG("terms", "What we've roughly agreed", "split bills by income %, £150 each fun money, purchases over £300 discussed first")],
    "Turn this into a clear agreement for {area}: {terms}. A kv of each term as a specific rule, a table (Situation | What happens | Who decides) covering 5 edge cases, a quote with a review clause (when and how you revisit it), and a callout that anything legally binding — leases, deeds, prenups — needs a solicitor.",
    "kv, table, quote, callout", "Draft it", "Writing it down…"),
  T("dealbreaker", "Deal-breaker check", "Difference, or deal-breaker?", "⚠️",
    [LONG("difference", "The difference", "I want kids, he says 'probably not'"), CH("time", "Been together", ["Under 1 year", "1–2 years", "2–5 years", "5+ years"], "1–2 years")],
    "Difference: {difference}, together {time}. Text with a straight assessment (3–4 sentences: preference, strong preference, or structural incompatibility), a table (Path | What it requires of each of you | Likelihood it holds), a quote with the exact question to ask your partner to get a real answer rather than a soothing one, and a callout on the cost of waiting for them to change.",
    "text, table, quote, callout", "Assess it", "Being honest…"),
  T("avoided", "The talk we keep avoiding", "Start it this week", "🐘",
    [TXT("subject", "The subject", "his mum expects us to live near her", True), CH("why", "We avoid it because", ["It ends in a fight", "One of us shuts down", "Fear of the answer", "Never the right time"], "Fear of the answer")],
    "Avoided subject: {subject}; why: {why}. Steps to set it up (when, where, how long, how to end it), a quote with the opening line (under 40 words, names the avoidance itself), bullets of 3 ground rules for the conversation, and a callout on what to do if it goes badly the first time.",
    "steps, quote, bullets, callout", "Set it up", "Finding courage…")], "Relationship coaching only; cohabitation, property and prenuptial agreements have legal effects and should be reviewed by a solicitor.")
