from dsl import *

BABY_MED = "General parenting information, not medical advice. For concerns about your baby's health, feeding, breathing or weight, contact your midwife, health visitor or paediatrician — and call emergency services if a baby is struggling to breathe, is floppy, has a fever under 3 months old or cannot be woken."
BEHAV = "General parenting guidance, not a clinical assessment. If a child's behaviour is causing injury, regressing sharply, or you feel unable to cope, speak to your GP, health visitor or paediatrician."
SOOTHE = BABY_MED + " If you feel you might hurt your baby or yourself, put the baby down safely in the cot, leave the room and call someone now."
CHILDCARE = "General guidance on childcare choices, not legal or financial advice. Fees, notice periods and illness rules vary by provider and country — confirm anything that matters in writing with the setting, and check its registration and inspection record with your local regulator before signing."
TODDLER_MED = "General parenting information, not medical advice. If your child has pain when weeing, blood in wee or poo, a fever, hard or infrequent poos for more than a week, or is still wet most nights after age 7, see your GP, health visitor or paediatrician."

# 1 — Newborn sleep (0–4 months)
APP("newborn_nights", "Newborn Nights", "Survive newborn nights with a plan, not guesswork", "Parenting", ["#1A237E", "#B39DDB", "#FFAB91"], "moon",
 "Newborn Nights gets families through the first four months of newborn sleep: wake-window schedules for today, a safe-sleep check of your cot from a photo, fair night-shift splits between carers and fixes for day–night confusion.",
 "You are a calm newborn-sleep consultant and safe-sleep educator: evidence-based (AAP / Lullaby Trust guidance), realistic about newborn biology, and never promising a sleeping-through-the-night miracle.",
 "The nights get easier — with a plan", "Tell us about your newborn and who's on duty.", ["Wake windows for today", "Safe-sleep check from a photo", "Fair night shifts for two"],
 [F("baby", "Baby's name & age in weeks", "text", "Leo, 6 weeks", required=True), CH("feeding", "Feeding", ["Breast", "Formula", "Mixed"]), CH("carers", "Night carers", ["One", "Two", "Two + helper"]), TXT("space", "Where baby sleeps", "bedside crib in our room")],
 [T("today", "Today's schedule", "Wake windows + naps from wake-up time", "🌅",
    [TXT("woke", "Baby woke at", "06:40", True), TXT("night", "How last night went", "fed at 1 and 4, hard to settle after 4")],
    "Baby woke at {woke}; last night: {night}. Build today's plan for the profile's age: a table (Time | Wake window / Nap | Feed | Notes) from wake-up to bedtime using age-appropriate wake windows in minutes, bullets of sleepy cues to watch for at this age, and a callout on what is normal at this age and what is not worth fighting.",
    "table, bullets, callout", "Plan today", "Counting windows…"),
  T("safe", "Safe-sleep check", "Photo of the cot or bassinet", "📷",
    [PHOTO("Photo of where baby sleeps", "Cot, bassinet or bedside crib, exactly as it is right now", True)],
    "Assess the sleep space in the photo against current safe-sleep guidance: a table (Item seen | Risk | Fix) covering mattress, bedding, toys, bumpers, sleep position, gaps and cords; a checklist of the ABCs (Alone, on Back, in a Cot) plus room temperature and smoke-free; and a callout on anything to change before tonight.",
    "table, checklist, callout", "Check it", "Looking closely…"),
  T("shifts", "Night-shift split", "A fair plan for two tired adults", "🌙",
    [TXT("constraints", "Constraints", "I'm breastfeeding, partner leaves for work at 7"), CH("style", "Split style", ["Halves", "Alternate nights", "First feed / second feed", "Whoever's least broken"], "Halves")],
    "Design a night-shift plan for the profile using the '{style}' style with constraints: {constraints}. Produce a table (Time block | On duty | Off-duty person does | Feed method), bullets on protecting one 4–5 hour stretch for each adult across the week, a quote with a 2-sentence agreement both partners can say out loud, and a callout on when to renegotiate.",
    "table, bullets, quote, callout", "Split the night", "Negotiating…"),
  T("daynight", "Day–night confusion", "Baby parties at 2am", "🔄",
    [TXT("pattern", "What's happening", "sleeps 4-hour stretches all day, awake 11pm–3am", True)],
    "Fix this day–night confusion: {pattern}. Explain the biology in 2 sentences of text, then steps for a 5-day reset (daylight, noise, feeding rhythm, capping daytime naps) with each step tied to a time of day, and a callout on what to expect on nights 1–3.",
    "text, steps, callout", "Reset the clock", "Opening curtains…"),
  T("putdown", "The night put-down", "Fed, calm-ish, but wakes the second they touch the cot", "😵‍💫",
    [CH("when", "When it fails", ["After a night feed", "At bedtime", "Every time I put them down", "Random"], "After a night feed"), TXT("tried", "Already tried", "swaddle, holding until deep asleep, white noise")],
    "The put-down fails {when}; already tried: {tried}. This is about a fed, not-distressed baby who wakes on transfer in the dark (crying that won't stop is a different problem). Give steps for tonight's put-down sequence in order (feed, burp, dim, swaddle or sleep bag, the 10-minute deep-sleep wait, feet-first transfer, hand-on-chest pause) with timings, a table (Possible cause | Sign | What helps) covering wind, a too-cold cot, startle reflex, hunger and overtiredness, and a callout listing signs that mean call a doctor or emergency services now.",
    "steps, table, callout", "Fix the put-down", "Lowering slowly…")], BABY_MED)

# 2 — Sleep coaching 4 months to 4 years
APP("settle_steps", "Settle Steps", "Gentle sleep coaching from 4 months to 4 years", "Parenting", ["#4527A0", "#26C6DA", "#FFCC80"], "star",
 "Settle Steps chooses a sleep-coaching method that matches your values, writes night-by-night plans, manages nap transitions and night weaning, and handles the move from cot to bed and 5am starts.",
 "You are an experienced paediatric sleep coach: evidence-informed, respectful of how much crying parents can tolerate, precise about timings, and honest that consistency matters more than method.",
 "Nights you can plan for", "Tell us your child's age, current sleep and how you feel about crying.", ["Method matched to your values", "Night-by-night plans", "Nap & big-bed transitions"],
 [F("child", "Child's name & age", "text", "Ada, 9 months", required=True), CH("crying", "Comfort with crying", ["None — fully responsive", "Some fussing OK", "Timed checks OK"]), TXT("now", "Current sleep", "feeds to sleep, wakes 3× a night, 2 naps"), CH("space", "Sleeps in", ["Own room", "Our room, own cot", "Co-sleeping"])],
 [T("method", "Choose a method", "Which approach fits our family", "🧭",
    [TXT("goal", "Main goal", "fall asleep without feeding, one wake max", True), NUM("nights", "Nights we can commit", "10")],
    "Recommend a sleep-coaching approach for the profile with goal '{goal}' and {nights} committed nights. Cards for the 3 best-fitting methods (meta = typical nights to see change · crying level), a kv of prerequisites (bedtime, room, health, teething, developmental leaps to wait out), and a callout on why the profile's comfort-with-crying level rules some methods out.",
    "cards, kv, callout", "Recommend", "Weighing options…"),
  T("plan", "Night-by-night plan", "Exactly what to do each night", "🌙",
    [CH("method", "Method", ["Gradual retreat", "Chair method", "Pick up / put down", "Timed checks", "Fading bedtime"], "Gradual retreat"), TXT("bedtime", "Target bedtime", "19:00")],
    "Write a 10-night '{method}' plan for the profile with target bedtime {bedtime}: a table (Night | Bedtime routine | Where you are / what you do | Response to night wakes | Expect), steps for the bedtime routine with clock times, bullets on what both parents must agree on, and a callout on the night-3 protest peak and when to pause (illness, travel).",
    "table, steps, bullets, callout", "Write plan", "Dimming lights…"),
  T("naps", "Nap transition", "Dropping 3→2, 2→1 or 1→0", "☀️",
    [CH("transition", "Transition", ["3 to 2 naps", "2 to 1 nap", "1 to 0 naps", "Not sure — help me tell"], "2 to 1 nap"), TXT("signs", "What you're seeing", "fights the afternoon nap, bedtime slipping to 9pm")],
    "Manage the '{transition}' transition given: {signs}. First a text verdict on whether it is time (with the signs that confirm it), then a table (Week | Wake-up | Nap 1 | Nap 2 | Bedtime) for a 3-week shift, bullets on surviving the overtired late-afternoon gap, and a callout on quiet time once naps end.",
    "text, table, bullets, callout", "Plan transition", "Shifting naps…"),
  T("nightwean", "Night weaning", "Fewer night feeds, gently", "🍼",
    [NUM("feeds", "Night feeds now", "3"), CH("how", "Feeding", ["Breast", "Bottle", "Both"], "Breast"), TXT("notes", "Notes", "partner can take some wakes")],
    "Plan gradual night weaning from {feeds} feeds ({how}) with notes: {notes}. Steps over 2 weeks reducing minutes or millilitres per feed with actual numbers, a table (Night | Feed 1 | Feed 2 | Feed 3 | Who settles), bullets on daytime calorie top-ups, and a callout on ages and weights where night feeds may still be needed and to check with a health professional first.",
    "steps, table, bullets, callout", "Plan it", "Tapering…"),
  T("bigbed", "Cot to bed / early waking", "Toddler escapes and 5am starts", "🛏️",
    [CH("issue", "Issue", ["Moving to a big bed", "Climbing out of the cot", "Waking before 6", "Bedtime stalling"], "Waking before 6")],
    "Solve '{issue}' for the profile: steps for a 2-week plan (room setup, light, ok-to-wake cue, response script), a quote with the exact 2-sentence script to repeat every single time, bullets of common mistakes, and a callout on safety (bed rails, furniture anchoring, door or stair gate).",
    "steps, quote, bullets, callout", "Fix it", "Tucking in…")], BABY_MED)

# 3 — Starting nursery / childminder / nanny
APP("nursery_start", "Nursery Start", "Settle your baby or toddler into childcare, tear-free-ish", "Parenting", ["#00695C", "#FF8A65", "#FFD54F"], "home",
 "Nursery Start helps you choose between nursery, childminder and nanny, plans the settling-in weeks, scripts the goodbye at drop-off, writes the key-worker handover sheet and decodes the illness policy and contract from a photo.",
 "You are an early-years practitioner and attachment-informed parenting coach: practical, honest that settling takes weeks, and equally respectful of nursery, childminder and nanny choices.",
 "The first goodbye is the hardest", "Tell us about your child and the childcare you're starting.", ["Settling-in week plan", "Goodbye scripts that work", "Handover sheet & policy decoder"],
 [F("child", "Child's name & age", "text", "Zoe, 11 months", required=True), CH("setting", "Setting", ["Nursery / daycare", "Childminder", "Nanny", "Still deciding"]), TXT("start", "Start date & hours", "6 Jan, Mon–Wed 8–5"), CH("temperament", "Temperament", ["Clingy", "Slow to warm", "Goes to anyone", "Depends on the day"])],
 [T("choose", "Nursery, childminder or nanny?", "Compare for your hours and budget", "🧭",
    [NUM("hours", "Hours of care per week", "30"), NUM("budget", "Monthly budget", "1200"), TXT("priorities", "What matters most", "outdoor time, siblings together, flexibility")],
    "Compare childcare options for the profile needing {hours} hours a week on a {budget} monthly budget with priorities: {priorities}. A table (Option | Typical cost for these hours | Ratio & setting | Fits your priorities? | Watch-outs), cards for the 2 best fits (meta = flexibility · cost level), a checklist of questions to ask on a visit, and a callout on registration, inspection reports and references to check before signing.",
    "table, cards, checklist, callout", "Compare", "Weighing options…"),
  T("settle", "Settling-in plan", "Gradual sessions that build trust", "📅",
    [NUM("weeks", "Weeks before full days", "3"), CH("sessions", "Settling sessions offered", ["1–2 short visits", "3–5 sessions", "Flexible — I decide", "None"], "3–5 sessions")],
    "Plan {weeks} weeks of settling-in for the profile with {sessions}. A table (Day | Length | Parent stays? | Goal | What to watch for), steps for each first (first feed there, first nap there, first full day), bullets on what typical settling looks like at this age (clinginess at pick-up, big evenings, first-term bugs), and a callout on signs the setting is not working versus normal adjustment.",
    "table, steps, bullets, callout", "Plan it", "Easing in…"),
  T("goodbye", "Drop-off script", "Short, warm, consistent", "👋",
    [TXT("scene", "What happens now", "clings, screams, I sneak out when distracted", True)],
    "Fix this drop-off: {scene}. A quote with the exact 3-sentence goodbye ritual to repeat every day (name the leaving, name the return, hand over), steps for the 10 minutes before and the 60 seconds of the goodbye, bullets on why sneaking out and lingering both backfire, and a callout on what to ask the key worker to text you afterwards.",
    "quote, steps, bullets, callout", "Give me words", "Practising goodbye…"),
  T("handover", "All-about-me sheet", "What the key worker needs to know", "📝",
    [LONG("routine", "Daily routine & comforts", "naps 12:30 with dummy and muslin; loves bananas; signs 'more'; scared of hand dryers"), TXT("medical", "Allergies / medical", "none")],
    "Write an all-about-me handover for the profile from: {routine}; medical: {medical}. A quote with the one-page sheet (feeds, naps, words and signs, comforts, fears, how to settle, allergies, contacts) in the child's voice, a kv of items to pack labelled, and a checklist of what to agree with the setting in week one (nap rules, food, photos policy, medicine forms).",
    "quote, kv, checklist", "Write sheet", "Introducing them…"),
  T("policy", "Decode the policy", "Photo of the contract or illness rules", "📷",
    [PHOTO("Photo of the illness policy, contract or fee sheet", "", True)],
    "Read the document in the photo: a table (Clause | What it means in practice | Costs you money? | Ask about), a kv of key numbers (notice period, late-pickup fee, exclusion periods for common bugs, holiday charges, deposit), bullets of anything unusual compared with typical UK/US childcare terms, and a callout on questions to get answered in writing before signing.",
    "table, kv, bullets, callout", "Decode", "Reading fine print…")], CHILDCARE)

# 4 — Bottles, formula, combination feeding
APP("bottle_bridge", "Bottle Bridge", "Bottles, formula and combi-feeding, done right", "Parenting", ["#00897B", "#FF7043", "#FFF176"], "cup",
 "Bottle Bridge fixes bottle refusal, teaches paced bottle feeding to any carer, plans combination feeding without losing supply, decodes a formula tin from a photo and troubleshoots fussy, windy or gulping bottle feeds.",
 "You are a practical infant-feeding nurse: precise about millilitres, teat flows and prep rules, and equally supportive of formula, combination and bottle-fed expressed milk.",
 "Every bottle, sorted", "Tell us how your baby is fed and what you're moving towards.", ["Bottle-refusal fixes", "Combination feeding plans", "Formula decoded from a photo"],
 [F("baby", "Baby's name & age", "text", "Kai, 4 months", required=True), CH("milk", "In the bottle", ["Expressed milk", "Formula", "Both"]), CH("goal", "Goal", ["Baby takes a bottle at all", "Combine breast and bottle", "Move fully to formula", "Smoother bottle feeds"]), TXT("bottles", "Bottles & teats you own", "MAM anti-colic, size 1 teats")],
 [T("refuse", "Bottle refusal", "Baby won't take the bottle", "🙅",
    [TXT("tried", "What you've tried", "3 teats, partner offering, warm milk", True), CH("who", "Who's offering", ["Me (breastfeeding parent)", "Partner", "Grandparent / carer"], "Partner")],
    "Fix bottle refusal for the profile; tried: {tried}; offering: {who}. Steps for a 7-day gradual introduction (timing, who, position, teat flow, temperature, milk type), a table (Tactic | Why it works | When to try), bullets on what not to do (forcing, starving into it), and a callout on when to involve a feeding specialist.",
    "steps, table, bullets, callout", "Get a plan", "Warming the bottle…"),
  T("paced", "Paced bottle feeding", "Slow, responsive bottles", "🍼",
    [CH("carer", "Teach it to", ["Me", "Partner", "Nursery / nanny", "Grandparents"], "Grandparents")],
    "Explain paced bottle feeding for {carer} with the profile's bottles: steps with positions, bottle angle, pauses and cues, a quote with a 4-sentence script they can read from a fridge note, bullets of fullness cues to stop at, and a callout on teat flow rates by age and why faster is not better.",
    "steps, quote, bullets, callout", "Teach me", "Tilting…"),
  T("combi", "Combination feeding plan", "Swap feeds for bottles, keep supply", "🔀",
    [NUM("swap", "Feeds to move to bottle per day", "2"), CH("why", "Reason", ["Back to work", "Partner wants to feed", "Sleep / rest", "Moving to formula over time"], "Back to work"), TXT("notes", "Notes", "keep morning and bedtime breastfeeds")],
    "Plan combination feeding for the profile: move {swap} feeds a day to the bottle because '{why}', notes: {notes}. A table (Time | Breast / bottle | Amount | Who | Supply note) for a full day, steps for introducing one swapped feed at a time over 2 weeks, bullets on keeping supply steady (which feeds protect it most, expressing if needed) and avoiding engorgement, and a callout on signs baby is not getting enough during the switch.",
    "table, steps, bullets, callout", "Plan it", "Bridging feeds…"),
  T("tin", "Decode a formula tin", "Photo → prep, amounts, safety", "📷",
    [PHOTO("Photo of the formula tin or label", "Include the scoop table if you can", True)],
    "Read the formula label: a kv (type, stage / age, scoop size, water per scoop, prep temperature notes), a table (Baby age | Feeds per day | ml per feed) for the profile's age, steps for safe preparation and cooling, and a callout on what to never do (microwaving, reusing leftovers, wrong scoop counts, switching stages early).",
    "kv, table, steps, callout", "Decode", "Reading the tin…"),
  T("fussy", "Fussy bottle feeds", "Gulping, wind, spit-up, tiny feeds", "🌪️",
    [CH("issue", "What's happening", ["Gulps and splutters", "Very windy", "Spits up a lot", "Takes tiny amounts", "Falls asleep mid-feed", "Fights the bottle then drinks"], "Very windy"), TXT("details", "Details", "size 2 teat, 120 ml every 3 hours, lots of hiccups")],
    "Troubleshoot '{issue}' with details: {details} for the profile. A table (Possible cause | Sign | Change to make), steps for the next feed (teat, angle, pace, winding breaks with technique), bullets on the difference between normal posseting and concerning vomiting, and a callout on reflux, allergy or dehydration signs that need a doctor.",
    "table, steps, bullets, callout", "Troubleshoot", "Winding…")], BABY_MED)

# 5 — Weaning to solids
APP("first_bites", "First Bites", "Solids made simple, from first spoon to family plate", "Parenting", ["#EF6C00", "#558B2F", "#6A1B9A"], "leaf",
 "First Bites plans the first weeks of solids, schedules allergen introductions, turns tonight's dinner into a baby-safe version from a photo, and progresses textures as your baby grows.",
 "You are a paediatric dietitian who is relaxed about mess and precise about safety: evidence-based on allergens and choking, neutral between baby-led weaning and purées.",
 "Ready for the first spoon?", "Tell us about your baby and how you'd like to start.", ["A 2-week starter plan", "Allergen ladder", "Your dinner, baby-sized"],
 [F("baby", "Baby's name & age", "text", "Mia, 6 months", required=True), CH("approach", "Approach", ["Baby-led weaning", "Purées first", "Mixed"]), CH("family_allergy", "Allergies in the family", ["None", "Egg", "Peanut", "Dairy", "Tree nuts", "Other"], multi=True), TXT("skin", "Eczema or reflux?", "mild eczema")],
 [T("start", "2-week starter plan", "First foods, day by day", "🥄",
    [CH("slot", "Meal slot", ["Morning", "Lunch", "Both"], "Lunch"), TXT("have", "Foods already at home", "sweet potato, avocado, oats")],
    "Build a 14-day starter plan for the profile at the {slot} slot using foods like {have}. A table (Day | Food | Preparation for the profile's approach | Watch for), steps for the first-ever meal (timing after milk, seating, offering, ending), bullets on iron-rich foods to prioritise, and a callout on what a normal gag looks like versus choking.",
    "table, steps, bullets, callout", "Plan it", "Steaming veg…"),
  T("allergens", "Allergen ladder", "Introduce the top allergens safely", "🥜",
    [CH("done", "Already introduced", ["Egg", "Peanut", "Dairy", "Wheat", "Soy", "Fish", "Sesame", "Tree nuts", "None yet"], "None yet", True), TXT("notes", "Notes", "doctor said introduce peanut early")],
    "Plan allergen introduction for the profile; already introduced: {done}; notes: {notes}. A table (Week | Allergen | Form & amount | Time of day | Keep giving how often), steps for the first exposure of each (morning, tiny amount, wait, watch for 2 hours), a checklist of what to have ready, and a callout on mild versus severe reaction signs and when to call emergency services.",
    "table, steps, checklist, callout", "Build ladder", "Climbing…"),
  T("plate", "Baby-size our dinner", "Photo of your plate → baby version", "📷",
    [PHOTO("Photo of tonight's dinner", "", True)],
    "From the dinner in the photo, make a baby-safe version for the profile: a table (Component | Baby-safe? | How to adapt | Cut / serve as), steps to prepare it in under 10 extra minutes, a callout on salt, honey, whole nuts and choking shapes, and bullets on what the adult plate can keep unchanged.",
    "table, steps, callout, bullets", "Adapt it", "Chopping smaller…"),
  T("texture", "Texture progression", "From smooth to lumps to finger foods", "🧩",
    [CH("current", "Currently eating", ["Smooth purées", "Mashed with lumps", "Soft finger foods", "Family foods"], "Smooth purées"), TXT("issue", "Any issue", "gags on lumps and refuses")],
    "Move the profile on from '{current}' with issue: {issue}. Steps for the next 3 weeks of texture changes with a specific food for each, a table (Texture | Example foods | How to cut | Age guide), bullets on handling gagging without panicking, and a callout on signs worth raising with a health visitor or speech-and-language therapist.",
    "steps, table, bullets, callout", "Progress", "Adding lumps…"),
  T("refuse", "Won't eat solids", "Turns head, throws food, wants milk", "🙈",
    [TXT("what", "What's happening", "eats 2 spoons then cries, loves milk", True)],
    "For: {what} — text on what is normal at the profile's age, a table (Possible reason | Sign | Adjust), bullets of low-pressure tactics (timing, self-feeding, modelling, texture), and a callout on when refusal plus weight or dehydration signs needs a clinician.",
    "text, table, bullets, callout", "Help", "Unwrapping the bib…")], BABY_MED)

# 6 — Toddler tantrums
APP("calm_storm", "Calm Storm", "Toddler tantrums: what to say, right now", "Parenting", ["#37474F", "#FFCA28", "#9575CD"], "heart",
 "Calm Storm gives you the words in the middle of a toddler meltdown, finds triggers in your tantrum diary, plans the transitions that always blow up, repairs the relationship afterwards and tackles hitting and biting.",
 "You are a child-development specialist trained in emotion coaching: warm, unflappable, strategy-first, and clear that big feelings are normal and the goal is co-regulation, not obedience.",
 "You can stay calm — we'll give you the words", "Tell us your toddler's age and temperament.", ["Say-this-now scripts", "Trigger detective", "Repair after the storm"],
 [F("child", "Child's name & age", "text", "Theo, 2½", required=True), CH("temperament", "Temperament", ["Big feelings, fast", "Slow to warm", "Intense & persistent", "Easygoing until tired"]), CH("hotspots", "Hot spots", ["Leaving somewhere", "Getting dressed", "Mealtimes", "Screens off", "Sharing", "Bedtime"], multi=True), TXT("approach", "Your approach", "gentle but firm; no time-outs")],
 [T("now", "Right now", "What to say in the next 60 seconds", "🌪️",
    [TXT("scene", "What's happening", "screaming on the supermarket floor because I said no to sweets", True), CH("where", "Where", ["Home", "Public", "Car", "Someone else's house"], "Public")],
    "Setting: {where}. What's happening: {scene}. First a quote with the exact 3-line script to say (validate, name the feeling, hold the limit), then steps for the next 60 seconds (body position, voice, what to ignore), bullets on what to avoid in this setting, and a callout that this is a nervous-system storm, not manipulation.",
    "quote, steps, bullets, callout", "Give me words", "Breathing…"),
  T("diary", "Trigger detective", "Paste a week of tantrums", "🔍",
    [LONG("diary", "Tantrum diary", "Mon 5pm leaving nursery — 15 min; Tue 7am shoes — 5 min; Wed skipped nap, 4pm everything…")],
    "Analyse: {diary}. A table (Trigger | Times seen | Pattern (time of day, hunger, sleep, transition) | Prevention), bullets of the top 3 changes to make this week, steps for one preventive routine, and a callout on how many tantrums a day is typical at the profile's age.",
    "table, bullets, steps, callout", "Find patterns", "Reading the week…"),
  T("transition", "Transition plan", "Leaving the park without a fight", "🚦",
    [CH("moment", "The moment", ["Leaving the park", "Screens off", "Getting dressed", "Into the car seat", "Bath / bedtime", "Nursery drop-off"], "Leaving the park"), NUM("warning", "Minutes of warning you can give", "5")],
    "Plan '{moment}' with {warning} minutes of warning: steps from pre-warning to done (countdown, choices, play cue, physical help), a quote with the exact words for the warning and for the final call, bullets of props (timer, song, transition object), and a callout on what to do when the plan still fails.",
    "steps, quote, bullets, callout", "Plan it", "Setting the timer…"),
  T("repair", "Repair after the storm", "Reconnect once everyone's calm", "💞",
    [TXT("what", "What happened", "I shouted, they cried, now it's awkward", True)],
    "After: {what}. A quote with a short, honest repair script for a toddler (no over-apologising, no lecture), steps for reconnecting in the next hour, bullets for the adult's own reset, and a callout on why repair matters more than never losing it.",
    "quote, steps, bullets, callout", "Repair", "Softening…"),
  T("hitting", "Hitting & biting plan", "Firm limits, no shame", "🦷",
    [CH("behaviour", "Behaviour", ["Hitting", "Biting", "Throwing", "Pushing siblings"], "Hitting"), TXT("context", "When it happens", "at nursery when toys are taken")],
    "Make a 2-week plan for {behaviour} that happens: {context}. A quote with the in-the-moment limit script (short, calm, then move the child), a table (Situation | Prevent | Respond | Teach instead), bullets so nursery or carers stay consistent, and a callout on when frequency or intensity warrants a health-visitor or paediatric review.",
    "quote, table, bullets, callout", "Make plan", "Setting limits…")], BEHAV)

# 7 — Potty training
APP("potty_pilot", "Potty Pilot", "From readiness to dry nights, one clear plan", "Parenting", ["#0288D1", "#FFEB3B", "#66BB6A"], "sun",
 "Potty Pilot checks readiness, runs a 3-day intensive or gentle 3-week training plan, troubleshoots accidents and regressions, tackles poo withholding and night dryness, and writes the handover note for nursery.",
 "You are a relaxed, experienced potty-training coach: no shame, no pressure, evidence-based on readiness and constipation, and honest about when to stop and try again later.",
 "Ready when they are", "Tell us about your child and your household.", ["Readiness check", "3-day or gentle plan", "Accidents & night plan"],
 [F("child", "Child's name & age", "text", "Ravi, 2y 8m", required=True), CH("setup", "Setup", ["Potty", "Toilet seat + step", "Both"]), CH("childcare", "Childcare", ["Home all week", "Nursery / daycare", "Childminder / nanny", "Grandparents"]), TXT("bowel", "Bowel habits", "regular, once a day after breakfast")],
 [T("ready", "Readiness check", "Are we there yet?", "✅",
    [CH("signs", "Signs you see", ["Dry 2 hours", "Tells me after", "Tells me before", "Hides to poo", "Pulls pants down", "Interested in the toilet", "Hates wet nappies", "None yet"], "", True), TXT("notes", "Notes", "just started a new nursery")],
    "Readiness assessment for the profile with signs: {signs} and notes: {notes}. A checklist of readiness signs with the ones seen ticked, a text verdict (go now / wait 4–6 weeks / build skills first) with reasoning, steps to build the missing skills, and a callout on life events that make it worth waiting.",
    "checklist, text, steps, callout", "Check", "Checking signs…"),
  T("plan", "Training plan", "3-day intensive or 3-week gentle", "🗓️",
    [CH("style", "Style", ["3-day intensive (at home)", "Gentle 3 weeks", "Nursery-led"], "3-day intensive (at home)"), TXT("start", "Start date", "Saturday")],
    "Write a '{style}' potty-training plan for the profile starting {start}. A table (Day | Clothing | Prompts & timing | Rewards | Expect), steps for the first morning hour by hour, a checklist of supplies (a potty per floor, wipes, cleaning kit, 10+ pairs of pants, drinks), a quote with the exact prompting phrase to use followed by a 4-sentence handover note for the profile's childcare setting (their words for wee and poo, routine, how to handle accidents; skip the note if home all week), and a callout on the signs to pause the attempt.",
    "table, steps, checklist, quote, callout", "Write plan", "Packing the bag…"),
  T("accidents", "Accidents & regression", "Was dry, now isn't", "💧",
    [TXT("what", "What's happening", "dry for 3 weeks, now 4 accidents a day since baby sister arrived", True), NUM("days", "Days this has been going on", "5")],
    "Troubleshoot: {what} ({days} days). A table (Possible cause | Sign | Response), steps for the next 7 days (reset routine, prompts, zero pressure), a quote with a calm accident script, bullets on what makes regression worse, and a callout on urine-infection or constipation signs that need a doctor.",
    "table, steps, quote, bullets, callout", "Troubleshoot", "Mopping up…"),
  T("poo", "Poo withholding", "Wees on the potty, poos in a nappy", "🚽",
    [CH("pattern", "Pattern", ["Asks for a nappy to poo", "Holds for days", "Poos in pants after leaving the toilet", "Scared of the toilet"], "Asks for a nappy to poo"), TXT("diet", "Diet & fluids", "not much water, loves cheese")],
    "Plan for '{pattern}' with diet: {diet}. Text on why withholding happens and why it must never be forced, steps for a gradual bridge (nappy on while sitting on the potty, in the bathroom, cut a hole, then off), bullets on softening stools through fibre, fluids and footstool posture, and a callout on constipation signs where a doctor should assess before continuing.",
    "text, steps, bullets, callout", "Make a bridge", "Building the bridge…"),
  T("night", "Dry nights", "When and how to ditch night nappies", "🌙",
    [CH("status", "Night status", ["Still in night nappies", "Dry nappy some mornings", "Dry most mornings", "Trying pants at night"], "Dry nappy some mornings"), NUM("wet", "Wet mornings per week", "4")],
    "Night status '{status}' with {wet} wet mornings a week for the profile. A text verdict on whether to try night pants now, wait, or go back to nappies (with the reasoning), a kv (bed protection, last drink and last wee timing, lifting — yes or no and why, night light and potty by the bed, ages where night wetness is still normal), steps for the first 7 nights of night pants including the calm response to a wet bed, and a callout on when bedwetting past age 5–7 should be discussed with a doctor.",
    "text, kv, steps, callout", "Plan nights", "Drying up…")], TODDLER_MED)

# 8 — Twins & multiples
APP("twin_tandem", "Twin Tandem", "Two babies, one schedule, one sane parent", "Parenting", ["#E64A19", "#00ACC1", "#FDD835"], "baby",
 "Twin Tandem builds synchronised feeding and sleep schedules for twins and triplets, coaches tandem feeding positions, decides which gear to double, plans solo outings and helps you raise two individuals, not a unit.",
 "You are a multiples-specialist midwife who is also a parent of twins: brisk, systems-minded, pro-sync but flexible, and alert to prematurity and feeding-volume concerns.",
 "Double the babies, not the chaos", "Tell us about your multiples and your household.", ["Synced feed & sleep schedules", "Tandem feeding positions", "Gear: double or skip"],
 [F("babies", "Names & age (corrected if premature)", "text", "Ivy & Rex, 8 weeks (born at 34 weeks)", required=True), CH("type", "Multiples", ["Twins", "Triplets", "Twins + older sibling"]), CH("feeding", "Feeding", ["Breast", "Formula", "Mixed", "Pumping"]), CH("hands", "Adults at home by day", ["One", "Two", "Two + helper"])],
 [T("sync", "Sync the schedule", "Feed and sleep both together", "🔁",
    [TXT("current", "Current rhythm", "A feeds every 3h, B every 2h and wakes A", True), CH("goal", "Goal", ["Feed together", "Sleep together", "Both", "Stagger by 15 min"], "Both")],
    "Synchronise these babies — goal '{goal}' — from: {current}. A table (Time | Baby A | Baby B (+ C if triplets) | Adult 1 | Adult 2 / helper) for a 24h day at the profile's age, steps for the first 3 days of gently nudging the laggard (wake-to-feed rule), bullets on when to stop forcing sync (illness, different weights), and a callout on prematurity-adjusted feeding volumes and never skipping a feed for the schedule's sake.",
    "table, steps, bullets, callout", "Sync them", "Lining up…"),
  T("tandem", "Tandem feeding", "Positions and setup for two", "🤱",
    [CH("mode", "Mode", ["Tandem breastfeeding", "Two bottles at once", "One breast, one bottle", "Solo bottle-feeding two"], "Tandem breastfeeding"), TXT("setup", "Your setup", "sofa, twin pillow, no helper until 6pm")],
    "Coach '{mode}' with setup: {setup}. Cards for 3 positions (meta = helper needed · difficulty), steps to get both babies latched or bottled without a helper, a checklist of the feeding station to set up before every feed, and a callout on wind, the choking risk of propped bottles, and swapping sides or breasts between feeds.",
    "cards, steps, checklist, callout", "Show me", "Arranging pillows…"),
  T("gear", "Double or skip?", "What actually needs two", "🛒",
    [TXT("item", "Items you're deciding on", "cots, bouncer, car seats, monitor", True), NUM("budget", "Budget", "800")],
    "For '{item}' with budget {budget}: a table (Item | Buy two / one / skip | Why | Cheaper route), bullets of twin-specific gear that earns its place (twin feeding pillow, double pram type by age), a kv of the true minimum kit for the first 3 months, and a callout on safety items never to buy second-hand.",
    "table, bullets, kv, callout", "Decide", "Doing the maths…"),
  T("outing", "Solo outing plan", "Leave the house alone with two", "🚶",
    [TXT("trip", "The outing", "GP appointment 20 min away by bus", True), NUM("hours", "Hours out", "3")],
    "Plan {trip} for {hours} hours solo with the profile's babies: steps timed backwards from leaving (feeds, changes, pram loading), a checklist of the bag with double quantities noted, a table (Scenario | Plan) for both crying at once, one needing a change, and feeding in public, and a quote with a one-line reply for 'are they twins?' questions.",
    "steps, checklist, table, quote", "Plan it", "Packing double…"),
  T("two", "Two individuals", "Bonding, names and one-on-one", "👥",
    [TXT("worry", "What's on your mind", "I feel closer to one of them and feel awful", True)],
    "Respond to: {worry}. Text that normalises it honestly, bullets of daily practices (names not 'the twins', 10-minute solo slots, separate photos), a table (Age | Individuality practice | Why it matters), and a callout on parental burnout and how to find local multiples support groups.",
    "text, bullets, table, callout", "Help me", "Seeing both…")], BABY_MED)

# 9 — New baby + toddler
APP("big_sibling", "Big Sibling", "Get your toddler ready for the new baby", "Parenting", ["#F9A825", "#00897B", "#EC407A"], "gift",
 "Big Sibling prepares a toddler for a new baby with a week-by-week timeline, plans the birth days and the first meeting, handles jealousy and regression, and protects one-on-one time once the baby is home.",
 "You are a family therapist who specialises in sibling arrivals: practical, warm, honest that some regression is normal, and focused on the older child's sense of security.",
 "Two kids, one secure toddler", "Tell us about your older child and when the baby is due.", ["Week-by-week prep timeline", "First-meeting plan", "Jealousy & regression fixes"],
 [F("child", "Older child's name & age", "text", "Ellie, 2 years 10 months", required=True), F("due", "Baby due date / arrival", "text", "12 Nov"), CH("changes", "Changes coming", ["Moving out of the cot", "Starting nursery", "Potty training", "Moving room", "None"], multi=True), CH("help", "Help during the birth", ["Grandparents", "Friend", "Partner staying home", "Unsure"])],
 [T("timeline", "Prep timeline", "What to do each week before the due date", "📅",
    [NUM("weeks", "Weeks until due date", "8"), TXT("notes", "Notes", "she keeps asking if the baby will take her toys")],
    "Build a {weeks}-week preparation timeline for the profile, notes: {notes}. A table (Week | Do | Say | Avoid), bullets of books and play ideas for this age, steps for making any big change (cot, room, nursery) at least 6 weeks before or well after the birth, and a callout on what a toddler of this age can and cannot understand about 'a baby is coming'.",
    "table, bullets, steps, callout", "Build timeline", "Counting weeks…"),
  T("birthday", "Birth-day plan", "Who has the toddler, what they hear", "🏥",
    [CH("birth", "Birth type", ["Hospital, unknown timing", "Planned c-section / induction", "Home birth"], "Hospital, unknown timing"), TXT("carers", "Who can step in", "my mum (40 min away), neighbour for emergencies")],
    "Plan the toddler's care for a '{birth}' with helpers: {carers}. Steps for the go-bag and handover, a table with a row each for a 3am start, a daytime start and a long hospital stay (Scenario | Who has the toddler | What the toddler is told | Comfort items), a quote with age-appropriate words for 'Mummy is going to have the baby', and a checklist for the carer's fridge door.",
    "steps, table, quote, checklist", "Plan it", "Packing the go-bag…"),
  T("meet", "First meeting", "Introducing the baby", "🍼",
    [CH("where", "Where", ["Hospital", "At home", "Grandparents' house"], "At home")],
    "Script the first meeting {where}: steps (who holds the baby when the toddler walks in, the gift 'from the baby', a first job), a quote with what to say in the first minute, bullets of photos and rituals for the day, and a callout on visitors and protecting the toddler's nap.",
    "steps, quote, bullets, callout", "Script it", "Setting the scene…"),
  T("jealous", "Jealousy & regression", "Hitting the baby, wanting a bottle", "😤",
    [TXT("what", "What's happening", "asks to go back in nappies and pinched the baby twice", True), NUM("weeks_home", "Weeks since baby came home", "3")],
    "For: {what} ({weeks_home} weeks in): a table (Behaviour | What it's communicating | Respond), a quote with the limit-plus-love script for aggression toward the baby, steps for a 2-week plan of predictable one-on-one time, bullets on regression to allow versus gently steer, and a callout on safety supervision around a newborn.",
    "table, quote, steps, bullets, callout", "Help", "Holding both…"),
  T("special", "Special time rituals", "10 minutes a day that fixes most things", "⭐",
    [NUM("minutes", "Minutes available daily", "10"), TXT("likes", "What the older child loves", "trains, puddles, baking")],
    "Design daily 'special time' of {minutes} minutes around {likes}: cards for 7 ritual ideas (meta = minutes · baby asleep or awake), a kv of rules (child leads, phone away, name it), bullets on involving the toddler as a helper without it becoming a chore, and a quote with a 2-line closing phrase for the ritual.",
    "cards, kv, bullets, quote", "Design", "Making it special…")], BEHAV)

# 10 — Newborn crying, colic, witching hour
APP("soothe_kit", "Soothe Kit", "Why they're crying and what to try next", "Parenting", ["#6D4C41", "#80CBC4", "#FFCCBC"], "spark",
 "Soothe Kit helps you decode a newborn's crying, walks you through settling techniques step by step, plans for the evening witching hour, survives colic and keeps the parents' own limits in view.",
 "You are a newborn-care specialist — an experienced night nanny with paediatric-nurse training: calm, methodical, never dismissive of exhaustion, and explicit about red flags and never shaking a baby.",
 "Crying is a signal — we'll help you read it", "Tell us about your baby and the crying pattern.", ["Decode the cry", "Step-by-step settling", "Witching-hour & colic plans"],
 [F("baby", "Baby's name & age in weeks", "text", "Sam, 5 weeks", required=True), CH("feeding", "Feeding", ["Breast", "Formula", "Mixed"]), CH("worst", "Worst time", ["Evenings", "Nights", "After feeds", "All day"]), TXT("works", "What sometimes works", "car rides, hairdryer noise")],
 [T("decode", "Decode this cry", "Describe it, get likely causes", "🔊",
    [TXT("cry", "Describe the crying", "rhythmic, starts 30 min after a feed, draws knees up", True), TXT("last", "Last fed / slept / changed", "fed 40 min ago, napped 20 min")],
    "Crying: {cry}; last: {last}. A table (Likely cause | Evidence in your description | Try this first) ranked most to least likely, steps for a check sequence (hunger, wind, nappy, temperature, overstimulation, discomfort such as a hair tourniquet), and a callout listing crying features that need urgent medical assessment (high-pitched, inconsolable for hours, with fever, vomiting or floppiness).",
    "table, steps, callout", "Decode", "Listening…"),
  T("settle", "Settling sequence", "The 5 S's and beyond, in order", "🤫",
    [CH("tried", "Already tried", ["Swaddle", "Side / stomach hold", "Shush", "Swing", "Suck", "Feed", "Fresh air", "Bath"], "", True), NUM("minutes", "Minutes crying so far", "20")],
    "Baby has cried for {minutes} minutes; already tried: {tried}. Steps for the next 15 minutes of settling in order (how to do each and how long to give it), a kv of technique details (swaddle tightness, shush volume, swing amplitude, hold positions), and a callout on when to put baby down safely and step away, and never shaking a baby.",
    "steps, kv, callout", "Walk me through", "Shushing…"),
  T("witching", "Witching-hour plan", "5pm–10pm survival", "🌆",
    [TXT("evening", "Typical evening", "starts 6pm, screams till 9, partner home at 7", True)],
    "Plan the evening: {evening}. A table (Time | Baby | Adult on duty | Other adult), bullets of front-loading tactics (earlier nap, dim early, feed before the peak, baby-wearing), a checklist to set up at 4pm, and a callout on when evening crying is beyond typical and worth discussing with a doctor.",
    "table, bullets, checklist, callout", "Plan evening", "Dimming lights…"),
  T("colic", "Colic survival", "Weeks of it — a plan for the family", "🌀",
    [TXT("pattern", "Pattern", "3+ hours, 4 nights a week, since week 3", True), CH("suspects", "Suspected factors", ["Reflux", "Wind", "Dairy in my diet", "Formula type", "Overstimulation", "Nothing obvious"], "Nothing obvious", True)],
    "For crying pattern {pattern} with suspected factors {suspects}: text on what colic is and when it usually peaks and ends, a table (Factor | Evidence for / against | Reasonable trial | How long), steps for a 1-week trial of one change only, bullets for the family's own survival (shifts, ear defenders, asking for help), and a callout on symptoms that mean it is not colic and needs a doctor.",
    "text, table, steps, bullets, callout", "Make plan", "Rocking gently…"),
  T("limits", "I'm at my limit", "Right now, tonight", "🛑",
    [TXT("state", "How you're feeling", "haven't slept in 3 nights, I shouted at the baby", True)],
    "Respond to: {state}. A quote with 3 short sentences to hear right now, steps for the next 10 minutes (baby safe in the cot, step out, breathe, call someone), a kv of who to call (partner, friend, health visitor or midwife, a local crisis or parent helpline and how to find the number), and a callout on postnatal depression and anxiety signs for any parent.",
    "quote, steps, kv, callout", "Help me now", "Here with you…")], SOOTHE)
