from dsl import *

# w40 — Parenting: school-age routines, screen time, homework, teen mental health,
# college applications, learning differences.

APP("morning_launch", "Launch Pad", "School mornings and bedtimes that run themselves", "Parenting", ["#F57C00", "#1E88E5", "#8BC34A"], "sun",
 "Launch Pad builds morning, after-school and bedtime routines for school-age kids, timed backwards from the bus, with printable checklists kids can run themselves.",
 "You are a calm, systems-minded parent coach for ages 5–12: you design routines around real constraints, put the child in charge of a checklist, and never shame anyone for chaos.",
 "Out the door on time", "Tell us about your kids and your mornings; we'll build routines that stick.", ["Backward-timed morning routines", "Bedtime that actually ends", "Kid-run checklists"],
 [NAME, F("kids", "Kids (name, age)", "text", "Leo 6, Mia 10"), TXT("leave", "School leave time", "07:45"), CH("style", "Household", ["Two parents", "Solo parent", "Shared custody", "Grandparent-led"])],
 [T("morning", "Morning routine", "Backward from leave time", "🌅",
    [TXT("wake", "Current wake time", "06:50"), LONG("pain", "What goes wrong", "shoes missing, Mia dawdles over breakfast, I end up shouting"), CH("prep", "Night-before prep OK?", ["Yes", "Some", "No"], "Some")],
    "Design a school-morning routine for the profile's kids, working backwards from the leave time. Current wake time: {wake}. What goes wrong: {pain}. Night-before prep: {prep}. Sections: a table (Time | Kid(s) | Task | Parent does) at 5-minute granularity, a checklist per child written in kid-friendly words they can tick themselves, bullets for what moves to the night before, and a callout on the one change most likely to end the shouting.",
    "table, checklist, bullets, callout", "Build morning", "Setting alarms…"),
  T("bedtime", "Bedtime routine", "Wind-down that ends on time", "🌙",
    [TXT("child", "Which child", "Leo, 6", True), TXT("bed", "Target lights-out", "20:00"), LONG("issues", "What happens now", "gets a second wind after bath, 6 callbacks for water")],
    "Build a bedtime routine for {child} with lights-out at {bed}. Current problems: {issues}. Sections: steps with clock times from dinner to lights-out (each step 15 minutes or less), a kv of the 'callback budget' (how many, what counts, what to say when it's spent), bullets on age-appropriate sleep needs and the screens cut-off, and a quote with the exact goodnight script to repeat word-for-word every night.",
    "steps, kv, bullets, quote", "Build bedtime", "Dimming lights…"),
  T("afterschool", "After-school reset", "Snack, decompress, then the rest", "🎒",
    [CH("home", "Home at", ["15:00", "15:30", "16:00", "16:30", "17:00+"], "15:30"), CH("activities", "Activities this week", ["None", "1–2", "3+"], "1–2"), TXT("mood", "How they usually arrive", "hungry and grumpy, melts down over nothing")],
    "Plan the after-school window for the profile's kids: home at {home}, activities: {activities}, they usually arrive {mood}. Sections: a table (Time | Block | What it looks like | Screens?) from arrival to dinner, bullets explaining restraint collapse and why the first 30 minutes are for snack and decompression, a checklist for a 'landing zone' by the door (bags, shoes, notes from school), and a callout on when homework should NOT start.",
    "table, bullets, checklist, callout", "Plan afternoon", "Landing…"),
  T("chart", "Routine chart", "Printable, kid-owned", "📋",
    [CH("which", "Routine", ["Morning", "Bedtime", "After school", "Weekend"], "Morning"), TXT("child", "Child", "Mia, 10", True), CH("reader", "Reads yet?", ["Pre-reader (pictures)", "Early reader", "Fluent"], "Fluent")],
    "Create a {which} routine chart for {child}, who is a {reader}. Sections: a checklist of 6–10 items in the child's own voice (with an emoji per item if pre-reader), a kv of how to introduce it (where to hang it, who ticks, when to retire it), bullets on rewards that don't backfire, and a callout on what to do the first time it's ignored.",
    "checklist, kv, bullets, callout", "Make chart", "Laminating…"),
  T("late", "We're always late", "Diagnose the bottleneck", "⏰",
    [LONG("story", "Describe this morning", "Woke 6:50, breakfast 7:10, Leo couldn't find PE kit, left 8:02 (needed 7:45)")],
    "Diagnose lateness from: {story}. Sections: a table (Step | Planned | Actual | Minutes lost | Cause), bullets ranking the three biggest bottlenecks with one fix each, steps for a 'reset week' that changes one thing per day, and a quote with a non-shaming line to say to the kids about the new plan.",
    "table, bullets, steps, quote", "Diagnose", "Rewinding…")])


APP("screen_sherpa", "Screen Sherpa", "Screen limits that fit your kid, not a random number", "Parenting", ["#5E35B1", "#00ACC1", "#FFB300"], "clock",
 "Screen Sherpa checks whether a game or app is right for your child, sizes screen limits by age and day, gets you through the end-of-screen meltdown, and settles the first-phone decision.",
 "You are a level-headed digital-parenting specialist: evidence-aware, allergic to panic, and honest that content and context matter more than the minute count.",
 "Screens without the daily fight", "Tell us your kids' ages and devices so the limits fit real life.", ["Is this game OK for my kid?", "Limits by age and day", "End-of-screen meltdown plan"],
 [NAME, F("kids", "Kids (name, age)", "text", "Sam 8, Ava 13"), CH("devices", "Devices at home", ["Tablet", "Console", "Family PC", "Own phone", "Smart TV"], multi=True), CH("worry", "Biggest worry", ["Too many hours", "Content", "Gaming rage", "Sleep", "Social media"])],
 [T("check", "Is this OK?", "Photo or name of a game/app", "🎮",
    [PHOTO("Screenshot of the app or game listing"), TXT("title", "Game or app name", "Roblox"), TXT("child", "For which child", "Sam, 8", True)],
    "Assess {title} (or the app shown in the photo) for {child}. Sections: a kv (official age rating, real content themes, chat with strangers?, in-app purchases, addictive-design features, our verdict), bullets on settings to change before first use, a callout on the single biggest risk, and a quote with a one-sentence explanation the child will accept if the answer is no or not yet.",
    "kv, bullets, callout, quote", "Assess", "Reading ratings…"),
  T("limits", "Set limits", "By age, day and season", "⏳",
    [TXT("child", "Child", "Ava, 13", True), CH("day", "Day type", ["School day", "Weekend", "Holidays", "Sick day"], "School day"), LONG("now", "What happens now", "3h after school, phone in bed, fights at dinner", False)],
    "Design screen limits for {child} on a {day}. Current pattern: {now}. Sections: a table (Window | Allowed | Not allowed | Device location), bullets separating creative, social and passive use and why they are weighted differently, a checklist of the technical controls to set on each device in the profile, and a callout on the non-negotiables (bedrooms, meals, the hour before sleep) with the reasoning.",
    "table, bullets, checklist, callout", "Set limits", "Measuring…"),
  T("meltdown", "End-of-screen meltdown", "Turning it off without war", "🌋",
    [CH("age", "Age", ["5–7", "8–10", "11–13", "14+"], "8–10"), CH("what", "Turning off", ["A game mid-match", "YouTube/streaming", "Social media", "Homework device"], "A game mid-match")],
    "Coach the transition off {what} for a child aged {age}. Sections: steps for a warning sequence with exact minutes and wording, a quote with the script for when they refuse, bullets on why mid-match cut-offs hurt more and how to plan around natural stopping points, and a callout on which consequences are fair and which backfire.",
    "steps, quote, bullets, callout", "Get the script", "Counting down…"),
  T("phone", "First phone?", "Readiness check + rules", "📱",
    [TXT("child", "Child", "Sam, 11", True), LONG("why", "Why now", "everyone in class has one, walking home alone from September"), CH("option", "Considering", ["Smartwatch", "Basic phone", "Smartphone, locked down", "Full smartphone"], "Smartphone, locked down")],
    "Evaluate first-phone readiness for {child}. Reasons: {why}. Option being considered: {option}. Sections: a table (Readiness sign | Seen? | Evidence to look for), cards comparing the four device options (meta = monthly cost · risk level), a checklist of setup steps for the chosen option (accounts, location sharing, app approval, do-not-disturb at night), and a quote with a phone contract in the child's language, under 120 words.",
    "table, cards, checklist, quote", "Check readiness", "Ringing…"),
  T("audit", "Screen audit", "Paste a week's usage report", "📊",
    [LONG("report", "Paste the usage report", "Mon: YouTube 2h10, Roblox 1h, Messages 40m…"), TXT("child", "Child", "Ava, 13", True)],
    "Analyse this week's usage for {child}: {report}. Sections: a table (App | Hours | Type: creative/social/passive | Concern level), bullets of patterns (time of day, weekday vs weekend, sleep encroachment), a callout with the single change worth making this week, and a quote with how to share the findings with the child so it doesn't feel like surveillance.",
    "table, bullets, callout, quote", "Analyse", "Adding up…")])


APP("safe_feed", "Safe Feed", "Social media, group chats and strangers — handled calmly", "Parenting", ["#00695C", "#EF6C00", "#3949AB"], "shield",
 "Safe Feed helps parents get a child ready for social media, lock down privacy settings platform by platform, respond to cyberbullying or a scary message, and defuse group-chat drama.",
 "You are an online-safety educator who has sat with hundreds of families: practical, non-judgemental, clear about when to involve the school or police, and never in favour of secret surveillance.",
 "Online, and OK", "Tell us your child's age and platforms; we'll make the settings and the conversations concrete.", ["Platform-by-platform settings", "Cyberbullying response plan", "Group-chat drama, defused"],
 [NAME, F("child", "Child (name, age)", "text", "Priya, 12"), CH("platforms", "Platforms they use or want", ["YouTube", "TikTok", "Instagram", "Snapchat", "Discord", "WhatsApp", "Roblox", "BeReal"], multi=True), CH("country", "Country", ["UK", "US", "Canada", "Australia", "India", "Other"])],
 [T("ready", "Ready for this app?", "Readiness + the rules", "✅",
    [CH("platform", "Platform", ["TikTok", "Instagram", "Snapchat", "Discord", "WhatsApp", "YouTube", "Roblox", "BeReal"], "Instagram"), LONG("context", "Why now, and your worries", "best friend is on it, worried about DMs from strangers")],
    "Assess whether the profile's child is ready for {platform}. Context: {context}. Sections: a kv (minimum age, what the platform actually exposes kids to, private by default?, DM controls, disappearing content?), a table (Readiness sign | Yes/Not yet | How to tell), a checklist of the conditions for a yes, and a quote with a two-sentence answer for the child whichever way it goes.",
    "kv, table, checklist, quote", "Assess", "Scrolling…"),
  T("settings", "Lock down settings", "Step-by-step per platform", "🔒",
    [CH("platform", "Platform", ["TikTok", "Instagram", "Snapchat", "Discord", "WhatsApp", "YouTube", "Roblox"], "TikTok"), CH("device", "On", ["iPhone", "Android", "Console", "Browser"], "Android")],
    "Walk a parent through privacy and safety settings for {platform} on {device} for a child of the profile's age. Sections: steps in menu order (name each toggle and the value to set), a checklist of settings to re-check monthly, a callout on settings that reset after app updates or account changes, and bullets on the settings the child will most want to undo and how to talk about it.",
    "steps, checklist, callout, bullets", "Show me", "Toggling…"),
  T("incident", "Something happened", "Bullying, threats, exposure", "🚨",
    [CH("what", "What happened", ["Nasty messages", "Exclusion from group", "Threats", "Shared photo of them", "Sexual message from adult", "Saw disturbing content", "Scam or pressure"], "Nasty messages"), LONG("details", "What you know so far", "screenshots in a class group chat, started Tuesday, names of two kids")],
    "A parent reports: {what}. Details: {details}. Sections: a callout first on whether this needs the police, the platform or the school today and why, steps for the next 24 hours (preserve evidence, don't delete, what to report where), a quote with what to say to the child in the first two minutes, bullets on what NOT to do (confronting other parents, taking the phone away as punishment), and a kv of the reporting routes and hotlines for the profile's country.",
    "callout, steps, quote, bullets, kv", "Help now", "On it…"),
  T("drama", "Group-chat drama", "Friend fallout, screenshots, pile-ons", "💬",
    [LONG("story", "What's going on", "left out of a new group, someone screenshotted her message"), CH("role", "Your child is", ["The target", "A bystander", "The one who sent it", "Not sure"], "The target")],
    "Group-chat situation: {story}. The child is {role}. Sections: text explaining the dynamics in plain language, a quote with a conversation opener that doesn't lead with blame, steps to help the child decide (leave, mute, respond, report), bullets of exact messages the child could send if they choose to respond, and a callout on repair if the child was the one in the wrong.",
    "text, quote, steps, bullets, callout", "Untangle", "Reading the thread…"),
  T("stranger", "Who is this account?", "Friend requests and DMs", "🕵️",
    [LONG("account", "Describe the account or paste the messages", "says he's 14, no mutual friends, asks to move to Snapchat, sends Robux gifts")],
    "Assess the account and messages: {account}. Sections: a table (Red flag | Present? | Why it matters), a kv verdict (risk level, likely pattern such as grooming, scam or peer, next action), steps to check together with the child (mutual friends, reverse image search, account age), and a quote with what to say to the child so they'll keep telling you next time.",
    "table, kv, steps, quote", "Check account", "Looking closer…")],
 "General online-safety guidance, not legal advice. If a child is in immediate danger contact emergency services; for sexual exploitation use your national reporting hotline.")


APP("homework_truce", "Homework Truce", "End the nightly homework fight without doing it for them", "Parenting", ["#3949AB", "#FF7043", "#43A047"], "note",
 "Homework Truce tackles the fight, not the fractions: it chunks assignments into timed sprints, sets up the workspace, builds motivation systems that don't backfire, and plans long projects backwards from the due date.",
 "You are an executive-function coach for families: you treat refusal as a skills gap not a character flaw, keep parents out of the teacher's job, and give one small system at a time.",
 "Peace at the kitchen table", "Tell us about your child and what the fight looks like.", ["Chunked plans with timers", "Motivation without bribery", "Long projects, backwards-planned"],
 [NAME, F("child", "Child (name, age, grade)", "text", "Noah, 9, Year 5"), CH("pattern", "The fight usually is", ["Refusing to start", "Meltdown when stuck", "Rushing and sloppy", "Lying about having none", "Takes hours"]), TXT("support", "Diagnoses or school support", "ADHD, 504 plan")],
 [T("standoff", "Break the standoff", "They won't start. Right now.", "🧱",
    [LONG("scene", "What's happening", "sitting there 40 min, says it's stupid, I've asked 5 times"), NUM("left", "Minutes until bedtime", "60")],
    "A homework standoff: {scene}, with {left} minutes until bedtime. Sections: a callout deciding whether tonight is worth pushing at all, steps for the next 10 minutes (parent moves, exact wording, what to remove from the room), a quote with the one line to say instead of asking again, and bullets on what to tell the teacher tomorrow if it doesn't get done.",
    "callout, steps, quote, bullets", "Unstick", "Lowering the stakes…"),
  T("chunk", "Chunk this assignment", "Photo or paste → timed sprints", "⏱️",
    [PHOTO("Photo of the assignment"), LONG("task", "Or describe it", "2-page report on volcanoes due Friday, 20 spelling words, maths sheet", False)],
    "Turn the assignment (from the photo and/or: {task}) into a plan for the profile's child without solving any of it. Sections: a table (Sprint | Minutes | Exactly what to do | Done when…), a checklist the child ticks as they go, a kv of break rules (length, what's allowed, how to come back), and a callout on where a parent should and should not help.",
    "table, checklist, kv, callout", "Chunk it", "Slicing…"),
  T("station", "Homework station", "Photo of where they work", "🪑",
    [PHOTO("Photo of the homework spot", "", True), CH("where", "It's in the", ["Kitchen", "Bedroom", "Living room", "Shared desk"], "Kitchen")],
    "Assess the homework spot in the photo (located in the {where}) for the profile's child. Sections: a table (Element | Now | Change | Why), a checklist for a 'homework caddy' so nothing needs fetching, bullets on noise, siblings and screens, and a callout on whether this room is the right place for this particular child.",
    "table, checklist, bullets, callout", "Assess spot", "Looking around…"),
  T("motivate", "Motivation system", "Rewards that don't backfire", "🏆",
    [CH("goal", "Target behaviour", ["Starts on time", "Finishes without nagging", "Checks work", "Tells the truth about homework", "Asks for help when stuck"], "Starts on time"), CH("tried", "Already tried", ["Sticker chart", "Screen time as reward", "Taking things away", "Nothing formal"], "Nothing formal")],
    "Design a two-week motivation system for '{goal}' given the family already tried: {tried}. Sections: a kv (the behaviour in observable words, how it's tracked, the reward, when it fades), a table (Day | Expectation | Parent response if yes | If no), bullets on why punishment-based systems fail for this goal, and a quote introducing the system to the child in under 60 words.",
    "kv, table, bullets, quote", "Design system", "Building…"),
  T("project", "Long project planner", "Backwards from the due date", "📅",
    [LONG("brief", "The project", "Egypt diorama + 1-page write-up, due 24 May"), TXT("busy", "Busy days or evenings", "football Tue & Thu")],
    "Backward-plan: {brief}, avoiding {busy}. Sections: a table (Date | Milestone | Minutes | Materials needed), a checklist of materials to buy this weekend, steps for the first session (which should be the boring bit), and a callout on how much the finished thing should look like a child made it.",
    "table, checklist, steps, callout", "Plan project", "Counting back…")])


APP("teen_harbour", "Teen Harbour", "Support a struggling teen with a plan, not just worry", "Parenting", ["#00838F", "#F06292", "#FFD54F"], "heart",
 "Teen Harbour helps parents of teenagers with anxiety, low mood or self-harm build a safety plan, find and prepare for therapy, ask school for support, and get through exam season and bad nights.",
 "You are a youth-mental-health clinician speaking to parents: warm, plain-spoken, evidence-based, clear about crisis lines, and never diagnosing from a message.",
 "You don't have to guess", "A few details let us tailor the plan and point to the right services.", ["A safety plan you build together", "Therapy: find, fund, prepare", "School support requests"],
 [NAME, F("teen", "Teen (name, age)", "text", "Sam, 15"), CH("concern", "Main concern", ["Anxiety", "Low mood", "Self-harm", "Eating", "Panic attacks", "School refusal", "Not sure"], multi=True), CH("country", "Country", ["UK", "US", "Canada", "Australia", "Ireland", "India", "Other"])],
 [T("safety", "Safety plan", "Build it together, tonight", "🛟",
    [LONG("triggers", "What tends to set things off", "exam results, arguments with Dad, late nights scrolling"), TXT("people", "People they trust", "cousin Jess, Mr Patel at school")],
    "Draft a collaborative safety plan for the profile's teen with triggers: {triggers} and trusted people: {people}. Sections: a kv using the standard safety-plan headings (warning signs, coping things I can do alone, people and places that distract me, people I can ask for help, professionals and crisis lines for the profile's country, making my environment safer), a quote with how to introduce the plan to the teen so it doesn't feel like punishment, a checklist of what to make safer at home (medicines, sharps, alcohol), and a callout on what to do if there is immediate risk tonight.",
    "kv, quote, checklist, callout", "Draft plan", "Anchoring…"),
  T("therapy", "Find & prep for therapy", "Types, cost, first session", "🧭",
    [CH("route", "Route", ["Public / school-referred", "Private", "Insurance", "Online", "Not sure"], "Not sure"), NUM("budget", "Budget per session (if private)", "80"), TXT("prefs", "Preferences", "female therapist, evenings, not CBT again")],
    "Guide a parent to therapy for the profile's teen: route {route}, budget {budget} per session, preferences {prefs}. Sections: a table (Therapy type | Good for | Typical wait | Typical cost in the profile's country), steps to get a referral or vet a private therapist (credentials to check, questions for the first call), a checklist of what to prepare for the first session, and a callout on confidentiality between therapist, teen and parent.",
    "table, steps, checklist, callout", "Guide me", "Searching…"),
  T("school", "Ask the school", "Support request letter", "🏫",
    [LONG("situation", "What's happening at school", "panic before assessments, missed 8 days this term"), CH("ask", "What you want", ["Adjustments for tests", "Safe space or pass", "Reduced timetable", "Counsellor access", "Communication plan", "Not sure"], multi=True)],
    "Situation: {situation}. Asking for: {ask}. Sections: a quote with a complete email to the pastoral lead or counsellor (under 250 words, factual, requests a meeting and specific adjustments), bullets of adjustments schools commonly grant for mental-health needs in the profile's country and the formal routes (for example a 504 plan, SEN support or an individual healthcare plan), a checklist of documents to bring, and a callout on what to do if the school is unresponsive.",
    "quote, bullets, checklist, callout", "Write letter", "Drafting…"),
  T("exams", "Exam-season plan", "Pressure without collapse", "📚",
    [TXT("exams", "Exams and dates", "GCSEs, 12 May – 20 June", True), LONG("signs", "What you're seeing", "not sleeping, crying at revision, says she'll fail everything", False)],
    "Plan exam season for the profile's teen: {exams}. Current signs: {signs}. Sections: a table (Week | Parent's job | What to stop doing | Check-in question), steps for a panic-before-exam protocol the teen can run alone, bullets on sleep, food and movement basics that matter more than extra revision hours, a quote with what to say the night before the first exam, and a callout on signs that this is beyond exam stress.",
    "table, steps, bullets, quote, callout", "Plan season", "Steadying…"),
  T("night", "After a bad night", "Repair, rest, next steps", "🌤️",
    [LONG("what", "What happened", "found messages about not wanting to be here; we talked till 2am")],
    "After: {what}. Sections: a callout first on whether this needs same-day professional contact and exactly who to call in the profile's country, steps for today (rest, supervision, who else to tell, what to say to siblings), a quote with a short message to send the teen this morning, bullets for the parent's own support, and a kv of what to observe over the next 72 hours.",
    "callout, steps, quote, bullets, kv", "Help me today", "Here with you…")],
 "This is general information, not therapy or medical advice. If your teen is in immediate danger, call emergency services or your local crisis line now.")


APP("admit_road", "Admit Road", "College applications, timed and costed, for parents", "Education", ["#1A237E", "#FFC107", "#00897B"], "hat",
 "Admit Road gives parents a month-by-month application timeline, builds a balanced college list around budget and fit, decodes financial-aid offers side by side, and preps campus visits and counsellor brag sheets.",
 "You are a former admissions officer turned family advisor: candid about odds and cost, allergic to prestige panic, and firm that the student owns the essays.",
 "The road to a good-fit yes", "Tell us where your student is and what you can afford.", ["Month-by-month timeline", "Balanced list, real costs", "Aid offers decoded"],
 [NAME, F("student", "Student (name, grade/year)", "text", "Maya, Grade 11"), CH("system", "Applying in", ["US", "UK (UCAS)", "Canada", "Australia", "India", "Europe", "Mixed"]), NUM("budget", "Family budget per year", "20000")],
 [T("timeline", "Build the timeline", "From now to decision day", "🗓️",
    [CH("start", "Starting point", ["Grade 9/10 – early", "Grade 11 – on time", "Grade 12 – late start", "Gap year"], "Grade 11 – on time"), TXT("aims", "Aims", "engineering, Common App + 2 UC schools, needs aid")],
    "Build an application timeline for the profile's student starting at '{start}', aims: {aims}, in the profile's system. Sections: a table (Month | Student does | Parent does | Deadline type), a checklist of documents and accounts to set up now (tests, transcripts, FAFSA/CSS or the local equivalent, recommendation requests), bullets on the difference between early and regular rounds, and a callout on the tasks parents must not do for the student.",
    "table, checklist, bullets, callout", "Build timeline", "Plotting…"),
  T("list", "College list builder", "Reach, match, likely — and affordable", "🎯",
    [LONG("stats", "Grades, tests, activities", "3.7 GPA, 1350 SAT, robotics captain, part-time job"), TXT("wants", "What they want", "mid-size, near a city, strong CS, not too far from home"), CH("prefs", "Priorities", ["Cost", "Prestige", "Specific program", "Location", "Campus vibe", "Sports or arts"], multi=True)],
    "Build a balanced college list from: {stats}, wants: {wants}, priorities: {prefs}, within the profile's budget. Sections: a table of 12 schools (School | Tier: reach/match/likely | Est. net cost after typical aid | Why it fits | Watch-out), bullets on how the list is balanced and which to visit first, a callout on sticker price versus net price and merit-aid strategy, and a kv of next actions per tier.",
    "table, bullets, callout, kv", "Build list", "Shortlisting…"),
  T("visit", "Campus visit kit", "What to ask, what to notice", "🏛️",
    [TXT("school", "School", "University of Michigan", True), CH("format", "Format", ["Official tour", "Self-guided", "Virtual", "Admitted-student day"], "Official tour")],
    "Prepare a {format} visit to {school} for the profile's student. Sections: a checklist of what to observe (the dining hall at noon, the library on a weeknight, the notice boards), bullets of 8 questions the student asks (not the parent) with the answer to hope for, a table (Question for the financial-aid office | Why it matters), and a quote with a 3-line debrief prompt for the car ride home.",
    "checklist, bullets, table, quote", "Prep visit", "Packing…"),
  T("aid", "Decode aid offers", "Compare real net cost", "💵",
    [LONG("offers", "Paste the offers", "School A: COA 62k, grant 30k, loan 5.5k, work-study 2k. School B: …")],
    "Decode and compare: {offers}. Sections: a table (School | Cost of attendance | Gift aid | Loans | Work-study | True net cost | 4-year estimate), a callout on which lines are free money versus debt and any one-year-only awards, bullets on how to appeal for more aid and what evidence works, and a quote with a short, polite appeal email the family can send.",
    "table, callout, bullets, quote", "Compare", "Crunching…"),
  T("brag", "Brag sheet", "For counsellor & recommenders", "📝",
    [LONG("notes", "Stories, achievements, growth", "started robotics club, cared for grandma, improved chem from C to A")],
    "Turn {notes} into a parent brag sheet for the counsellor and recommenders of the profile's student. Sections: a kv (three words that describe them with an anecdote each, a challenge overcome, what they do when nobody's watching, growth since Grade 9), bullets of concrete achievements with numbers, a quote with a 150-word paragraph a counsellor could adapt, and a callout on what recommenders don't want to read.",
    "kv, bullets, quote, callout", "Write sheet", "Bragging tastefully…")],
 "Cost and aid figures are estimates, not financial advice; verify with each institution's official net-price calculator and aid office.")


APP("iep_ally", "IEP Ally", "Get your child the school support they're entitled to", "Parenting", ["#6A1B9A", "#26A69A", "#FF8F00"], "scale",
 "IEP Ally walks parents through requesting an evaluation, decoding the psych-ed report, choosing accommodations that fit, and walking into the IEP, 504 or EHCP meeting prepared and calm.",
 "You are a special-education advocate: you know the process cold for the US, UK and beyond, translate jargon into plain English, and keep everything factual and dated because paper trails win.",
 "Prepared, not outnumbered", "Tell us your child's needs and your school system so the paperwork matches.", ["Evaluation request letters", "Reports in plain English", "Meeting prep that works"],
 [NAME, F("child", "Child (name, age, grade)", "text", "Eli, 8, Grade 3"), CH("system", "System", ["US (IEP/504)", "UK (SEN support/EHCP)", "Canada", "Australia", "Ireland", "Other"]), CH("needs", "Suspected or diagnosed", ["Dyslexia", "ADHD", "Autism", "Dyscalculia", "Speech/language", "Anxiety", "Processing", "Not sure yet"], multi=True)],
 [T("request", "Request an evaluation", "The letter that starts the clock", "✉️",
    [LONG("concerns", "Your concerns, with examples", "reads 2 years below grade, avoids writing, teacher mentioned 'slow to finish'"), TXT("history", "Anything already tried", "reading intervention group since January")],
    "Write a formal evaluation request for the profile's child in the profile's system. Concerns: {concerns}. Already tried: {history}. Sections: a quote with the complete letter (dated, addressed to the right role for the system, naming the areas to assess, citing the relevant law or code in one line, requesting a written response), a kv of what happens next and the legal timelines, a checklist of what to attach and how to send it so it's on record, and a callout on the common ways schools deflect and how to respond.",
    "quote, kv, checklist, callout", "Write request", "Starting the clock…"),
  T("decode", "Decode the report", "Paste the evaluation → plain English", "🔍",
    [LONG("report", "Paste sections of the report", "WISC-V FSIQ 104, Processing Speed 78 (7th percentile), WIAT reading fluency 82…")],
    "Explain this evaluation in plain English for a parent: {report}. Sections: a table (Test or index | Score | Percentile | What it measures | What it means at school), text summarising the child's profile in three sentences a parent could repeat, bullets of the specific needs this evidence supports, and a callout on what the report leaves out and what to ask the evaluator.",
    "table, text, bullets, callout", "Decode", "Translating…"),
  T("accom", "Accommodations that fit", "From struggles to specifics", "🧩",
    [LONG("struggles", "What's hard at school", "copying from the board, timed tests, remembering multi-step instructions"), CH("setting", "Setting", ["Mainstream class", "Small group", "Special class", "Home or online"], "Mainstream class")],
    "Propose accommodations and supports for the profile's child in a {setting} given: {struggles}. Sections: a table (Struggle | Accommodation | How it's delivered | How we'll know it works), bullets separating accommodations from modifications and specialist services, a kv of measurable goal wording examples (baseline → target → by when), and a callout on the vague phrases to reject in a plan.",
    "table, bullets, kv, callout", "Propose", "Matching…"),
  T("meeting", "Prep the meeting", "Agenda, questions, your script", "🗂️",
    [CH("type", "Meeting", ["Initial eligibility", "Annual review", "Amendment or complaint", "Transition (new school)", "Discipline or manifestation"], "Initial eligibility"), LONG("goals", "What you want out of it", "reading intervention 4×/week, extended time, a communication log", False)],
    "Prepare a parent for a {type} meeting for the profile's child, wanting: {goals}. Sections: a checklist of what to bring and send ahead, steps for the meeting in order (opening statement, listening, asking, declining to sign today), a quote with a 60-second opening statement about the child as a person, bullets of questions that expose vague plans, and a callout on the parent's rights in the room for the profile's system.",
    "checklist, steps, quote, bullets, callout", "Prep me", "Rehearsing…"),
  T("log", "Paper trail", "Log an incident or call", "📒",
    [LONG("event", "What happened", "called Mrs K, said aide 'not available', 3rd time this month")],
    "Turn {event} into a dated record and a follow-up. Sections: a kv (date, people, what was said, what was agreed, evidence attached), a quote with a short follow-up email confirming the conversation in writing, bullets on whether this is a pattern that supports a formal complaint, and a callout on the escalation route in the profile's system.",
    "kv, quote, bullets, callout", "Log it", "Filing…")],
 "Education law and timelines vary by country and state; this is general guidance, not legal advice. Consider a local parent advocate or lawyer for disputes.")


APP("reading_bridge", "Reading Bridge", "Dyslexia-friendly reading practice, ten minutes a night", "Education", ["#D84315", "#0097A7", "#7CB342"], "book",
 "Reading Bridge gives parents of dyslexic and struggling readers structured-literacy practice at home: phonics-pattern drills, decodable stories, book picks that match reading level and real interests, and assistive-tech setup.",
 "You are a structured-literacy tutor (Orton-Gillingham trained) who coaches parents: explicit, multisensory, patient, and firm that ten minutes daily beats an hour on Sunday.",
 "Reading, one pattern at a time", "Tell us your child's age, level and interests.", ["Phonics drills for one pattern", "Decodable stories they'll like", "Books by level and interest"],
 [F("child", "Child (name, age)", "text", "Zara, 8"), CH("level", "Reads roughly like a", ["Pre-reader", "5-year-old", "6-year-old", "7-year-old", "8-year-old", "9–10-year-old", "11+"]), TXT("interests", "Interests", "horses, Minecraft, gross facts"), CH("dx", "Diagnosis", ["Dyslexia", "Suspected", "Dysgraphia", "Dyscalculia", "None"], multi=True)],
 [T("drill", "Tonight's drill", "One pattern, multisensory", "🔤",
    [TXT("pattern", "Pattern to work on", "silent e, 'ch' vs 'sh', -tion", True), CH("minutes", "Minutes", ["5", "10", "15"], "10")],
    "Plan a {minutes}-minute multisensory session on {pattern} for the profile's child. Sections: steps (review, teach with the rule in child words, sand or air writing, word reading, dictation) with minutes for each, a table (Word list | Read | Spell | Nonsense words), a kv with the rule stated exactly as the child should say it, and a callout on the error to expect and how to correct it without saying 'sound it out'.",
    "steps, table, kv, callout", "Plan session", "Sorting sounds…"),
  T("story", "Decodable story", "Only patterns they know", "📖",
    [LONG("known", "Patterns they've learned", "CVC, digraphs sh/ch/th, silent e, -ing"), CH("length", "Length", ["80 words", "150 words", "250 words"], "150 words")],
    "Write a decodable story of about {length} for the profile's child using ONLY these patterns plus a few listed sight words: {known}. Weave in the profile's interests. Sections: text with the story (short sentences, generous line breaks), a kv of the sight words used, bullets with 3 comprehension questions and one 'find the word with the pattern' task, and a callout on how to handle it if they stumble.",
    "text, kv, bullets, callout", "Write story", "Once upon a…"),
  T("books", "Book picks", "Right level, real interest", "📚",
    [CH("format", "Format", ["Print", "Audiobook", "Graphic novel", "Hi-lo (high interest, low level)", "Any"], "Any")],
    "Recommend 8 {format} books for the profile's child matching the reading level AND the interests (not one or the other). Sections: cards (title and author, meta = reading level · pages · why they'll like it), bullets on hi-lo publishers and dyslexia-friendly fonts, and a callout on why audiobooks count as reading.",
    "cards, bullets, callout", "Find books", "Browsing shelves…"),
  T("explain", "Explain it to my child", "Dyslexia, in their words", "💬",
    [CH("age", "Age band", ["5–7", "8–10", "11–13", "14+"], "8–10"), TXT("feeling", "What they've said", "says she's stupid, hides her book")],
    "Help a parent explain the profile's diagnosis to a child aged {age} who has said: {feeling}. Sections: a quote with a 2-minute script in plain, honest words (brain wiring, not intelligence; famous examples only if asked), bullets of questions the child might ask with answers, a kv of strengths to name that are typical for this profile, and a callout on phrases to avoid.",
    "quote, bullets, kv, callout", "Get script", "Choosing words…"),
  T("tech", "Assistive tech setup", "Text-to-speech, dictation, fonts", "🎧",
    [CH("device", "Device", ["iPad", "Android tablet", "Chromebook", "Windows laptop", "Mac", "Phone"], "Chromebook"), CH("need", "Need", ["Reading text aloud", "Writing by dictation", "Spelling support", "Audiobooks", "All"], "All")],
    "Set up assistive tech for '{need}' on a {device} for the profile's child. Sections: steps for the built-in features (exact settings paths), a table (Tool | Free or paid | Best for | Set-up minutes), a checklist to hand the teacher so the same tools are allowed in class, and a callout on getting the child to actually use it without embarrassment.",
    "steps, table, checklist, callout", "Set up", "Switching on…")],
 "Home practice support, not a substitute for a formal assessment or specialist tuition.")


APP("backpack_brain", "Backpack Brain", "ADHD at school: systems for the kid who loses everything", "Parenting", ["#F4511E", "#3F51B5", "#FDD835"], "brain",
 "Backpack Brain gives parents of ADHD kids aged 6–14 concrete systems: the backpack and planner that don't fail, cues for chronic forgetting, transition plans, a home behaviour plan, and the after-school restraint collapse.",
 "You are an ADHD parent coach who understands executive function deeply: you externalise everything, reduce steps, use novelty deliberately, and never call a child lazy.",
 "Systems beat willpower", "Tell us about your child and what keeps falling apart.", ["Backpack & planner systems", "Fixes for chronic forgetting", "Transitions without meltdowns"],
 [NAME, F("child", "Child (name, age)", "text", "Jack, 10"), CH("meds", "Medication", ["Yes", "No", "Starting soon", "Prefer not to say"]), CH("hardest", "Hardest part", ["Losing things", "Homework not handed in", "Transitions", "Morning launch", "Big emotions", "Sitting still"], multi=True)],
 [T("backpack", "Fix the backpack", "Photo → a system", "🎒",
    [PHOTO("Photo of the backpack, desk or locker", "", True), CH("fails", "What goes missing", ["Homework", "Water bottle", "Jumper or coat", "PE kit", "Planner", "Everything"], "Everything")],
    "Design an organisation system from the photo for the profile's child, who keeps losing: {fails}. Sections: a table (Item | Home location | Bag location | Cue that it's there), steps for a 60-second nightly 'launch check' the child runs, a checklist of cheap gear (one folder, colour tape, a lanyard) and where each goes, and a callout on why 'just be more careful' doesn't work and what to say instead.",
    "table, steps, checklist, callout", "Design system", "Emptying the bag…"),
  T("forgot", "Forgot again", "One recurring failure → a cue", "🔔",
    [LONG("fail", "The thing that keeps failing", "finishes homework then forgets to hand it in, 4 times this month"), TXT("tried", "Already tried", "reminding, taking away Xbox")],
    "Solve: {fail}. Already tried: {tried}. Sections: text naming the exact executive-function gap (working memory, initiation, time blindness, etc.) in one paragraph, a kv of the point of failure and the cue to place there (visual, physical or person-based), steps to install the system in one week, a quote with a note to the teacher asking for a matching cue at school, and a callout on why the punishment tried can't fix this.",
    "text, kv, steps, quote, callout", "Solve it", "Placing cues…"),
  T("transition", "Transition plan", "Screen → dinner, home → bed", "🔁",
    [TXT("from", "From", "Minecraft", True), TXT("to", "To", "dinner", True), CH("blows", "Usually ends in", ["Arguing", "Meltdown", "Ignoring", "Slow-motion compliance"], "Meltdown")],
    "Plan the transition from {from} to {to} for the profile's child, which usually ends in {blows}. Sections: steps with timings (pre-warning, visual timer, bridging activity, the handover), a quote with the exact words at each warning, bullets on why time-blind kids experience this as sudden, and a callout on repair after a blow-up.",
    "steps, quote, bullets, callout", "Plan it", "Setting the timer…"),
  T("plan", "Home behaviour plan", "Points that actually work", "⭐",
    [CH("target", "Target", ["Morning tasks done", "Homework started", "Kind words to sibling", "Bedtime on time", "Chores"], "Homework started"), NUM("days", "Trial length (days)", "14")],
    "Build a {days}-day home behaviour plan for '{target}' for the profile's child. Sections: a kv (behaviour in observable words, immediate reinforcer, daily reward menu, weekly bonus, what happens when missed — never point removal), a table (Day | Goal | Reinforcer | Notes), bullets on immediacy, frequency and novelty for ADHD brains, and a callout on when to fade the plan and what to do if it stops working.",
    "kv, table, bullets, callout", "Build plan", "Charting…"),
  T("collapse", "After-school collapse", "Held it together all day; now this", "🌪️",
    [LONG("scene", "What today looks like", "fine at school, screaming at me within 10 minutes of pick-up")],
    "Address after-school restraint collapse: {scene}. Sections: text explaining what it is and why it's a backhanded compliment, a table (Pick-up to +60 min | Do | Don't), a quote with the words to use in the car, bullets on food, movement and decompression before any demands, and a callout on when a pattern like this warrants a medication-timing conversation with the prescriber (if on medication).",
    "text, table, quote, bullets, callout", "Help now", "Landing softly…")],
 "Parenting strategies, not medical advice; discuss diagnosis and medication with your child's clinician.")


APP("playground_politics", "Playground Politics", "Friendship trouble and bullying, handled with care", "Parenting", ["#C2185B", "#00ACC1", "#7CB342"], "chat",
 "Playground Politics helps parents of 5–12s through friendship fallouts, bullying at school, party exclusions and playdate nerves, with scripts for kids, letters for teachers and social-skills practice at home.",
 "You are a school counsellor with twenty years on the playground: you distinguish conflict from bullying, coach kids rather than fixing it for them, and keep parents from going nuclear.",
 "Kind kids, thick skins", "Tell us about your child and their social world.", ["Conflict vs bullying, clarified", "Scripts your child can use", "Teacher escalation that works"],
 [NAME, F("child", "Child (name, age)", "text", "Ruby, 9"), CH("temperament", "Temperament", ["Shy", "Big feelings", "Bossy", "Anxious", "Class clown", "Easygoing"], multi=True), TXT("school", "School context", "small village school, one class per year")],
 [T("sort", "Conflict or bullying?", "What's really going on", "🔎",
    [LONG("story", "What your child told you", "Ella said she can't sit with them at lunch anymore, third day running"), CH("long", "How long", ["Today", "This week", "Weeks", "Months"], "This week")],
    "Assess: {story}, going on for {long}. Sections: a kv (verdict: normal conflict, relational aggression or bullying; the evidence for it; power imbalance?; repetition?), a table (What your child could do | What you do | What the school does), a quote with what to say to your child tonight, and a callout on the signs that mean escalate now.",
    "kv, table, quote, callout", "Assess", "Listening…"),
  T("coach", "Coach my child", "Words for tomorrow", "🗣️",
    [TXT("situation", "Situation", "kids call him 'baby' when he cries", True), CH("goal", "Goal", ["Stand up for themselves", "Make a new friend", "Join a game", "Say no to a friend", "Apologise and repair"], "Stand up for themselves")],
    "Coach the profile's child to {goal} in this situation: {situation}. Sections: a quote with 3 short lines the child can actually say (age-appropriate, not adult-sounding), steps for a 5-minute role-play at home where the parent plays the other kid, bullets on body language and where to stand, and a callout on what to do if it doesn't work the first time.",
    "quote, steps, bullets, callout", "Coach", "Rehearsing…"),
  T("teacher", "Escalate to school", "Letter, meeting, follow-up", "🏫",
    [LONG("facts", "Facts with dates", "12 Mar: pushed off bench; 14 Mar: lunch taken; told Miss T twice"), CH("stage", "Stage", ["First contact", "Follow-up – nothing changed", "Formal complaint"], "First contact")],
    "Write a '{stage}' message for a bullying concern: {facts}. Sections: a quote with a complete email (factual, dated, asks for specific actions and a reply date, under 220 words), a checklist of what to ask for (supervision points, seating, a named adult for the child, a review date), bullets on the school's likely policy steps, and a callout on the escalation route above the class teacher and when to use it.",
    "quote, checklist, bullets, callout", "Write it", "Drafting…"),
  T("party", "Party & playdate", "Exclusions, invites, nerves", "🎈",
    [CH("issue", "Issue", ["Not invited", "Wants to invite only some of the class", "First playdate nerves", "Hosting a kid they clash with", "Sleepover worries"], "Not invited"), TXT("details", "Details", "whole class went except her and one boy")],
    "Handle '{issue}': {details}. Sections: text on what to say and not say to the child about it, steps for the parent (including whether to contact the other parent, with wording), a quote with a message to the other parent if appropriate, and bullets of a plan for the day itself.",
    "text, steps, quote, bullets", "Handle it", "Thinking it through…"),
  T("skills", "Social skills practice", "Games that teach it", "🎲",
    [CH("skill", "Skill", ["Reading faces", "Taking turns in conversation", "Losing gracefully", "Joining a group", "Being a good sport", "Handling teasing"], "Joining a group")],
    "Plan two weeks of practising '{skill}' with the profile's child. Sections: cards of 5 games or routines (meta = minutes · players), a table (Day | Activity | What to notice | Praise this), bullets on generalising it to school, and a callout on when a skills gap might need an assessment.",
    "cards, table, bullets, callout", "Plan practice", "Setting up…")],
 "General parenting guidance. If a child is being physically hurt or threatened, involve the school immediately and, where needed, the police.")
