from dsl import *

# w41 — Social / Events: community organising, club management, volunteering, meetups, dinner clubs, reunions

APP("committee_kit", "Committee Kit", "Run your club like it's not your second job", "Social", ["#37474F", "#F9A825", "#00695C"], "gear",
 "Committee Kit is for the volunteers who keep clubs and societies going: it drafts AGM notices and agendas, turns scribbled notes into proper minutes, writes officer role descriptions, checks what your constitution is missing and produces a treasurer's report members can actually follow.",
 "You are a seasoned club secretary and treasurer: calm, procedurally careful, plain-English, and you always say when a rule depends on the club's own constitution or local law.",
 "Keep the club running smoothly", "Tell us about your club and your role; the paperwork gets a lot easier.", ["AGM packs in minutes", "Minutes with actions and owners", "Officer roles and handovers"],
 [TXT("club", "Club / society", "Riverside Allotment Society"), CH("role", "Your role", ["Chair", "Secretary", "Treasurer", "Committee member", "Just helping"]), CH("structure", "Structure", ["Unincorporated club", "Registered charity", "Non-profit company / CIC", "Not sure"]), NUM("members", "Members (approx.)", "60")],
 [T("agm", "AGM pack", "Notice, agenda and the chair's script", "📣",
    [TXT("date", "AGM date & venue", "14 Nov, 7pm, village hall", True), TXT("business", "Business to cover", "elect new treasurer, raise subs to 30, new shed"), CH("notice", "Notice period", ["14 days", "21 days", "28 days", "Not sure"], "21 days")],
    "Prepare an AGM pack for the club on {date} covering: {business}, with a {notice} notice period. Sections: a quote containing the formal notice to members (date, venue, agenda headings, how to submit motions and nominations), a table agenda (Item | Presenter | Minutes | Decision needed?), steps for the chair's script from opening to close including the quorum check and each vote, and a callout on what must be checked against the club's own constitution before sending.",
    "quote, table, steps, callout", "Build the pack", "Calling to order…"),
  T("minutes", "Notes → minutes", "Rough notes into proper minutes", "📝",
    [LONG("notes", "Your rough notes", "Present: J, K, M. Apols: R. Treasurer says 1,240 in bank. Agreed to buy new nets, K to get quotes by March…"), CH("style", "Style", ["Formal", "Friendly summary", "Both"], "Formal")],
    "Turn these meeting notes into minutes in a {style} style: {notes}. Sections: kv (meeting, date, present, apologies, quorum met?), text minutes numbered by agenda item recording decisions rather than discussion, a table of actions (Action | Owner | Due | Status), and a checklist of what the secretary must do before the next meeting.",
    "kv, text, table, checklist", "Write minutes", "Typing up…"),
  T("roles", "Role descriptions", "Recruit an officer and hand over cleanly", "🪪",
    [CH("post", "Post", ["Chair", "Secretary", "Treasurer", "Membership secretary", "Events officer", "Welfare officer", "Social media"], "Treasurer"), TXT("context", "What the job really involves", "about 3 hours a month, mostly emails and the bank")],
    "Write a role description for the {post} of the club given: {context}. Sections: cards for the role (responsibilities, time per month, skills; meta = hours/month · term length), a checklist handover pack the outgoing person should leave, a quote with a 120-word recruitment message for the newsletter, and bullets on making the role less scary for a first-timer.",
    "cards, checklist, quote, bullets", "Write it", "Drafting…"),
  T("treasurer", "Treasurer's report", "Figures into a report members follow", "💷",
    [LONG("figures", "Income and spending", "Subs 1,800; bar 640; hall hire -900; insurance -310; equipment -450; bank now 2,140"), TXT("period", "Period", "year to 31 March")],
    "Turn these figures into a treasurer's report for {period}: {figures}. Sections: a table (Category | Income | Spending | Net), kv (opening balance, closing balance, surplus or deficit, months of running costs held in reserve), text of the report in plain English a member can follow in two minutes, bullets of questions members may ask with suggested answers, and a callout on anything that needs the club's own rules or an accountant (reporting thresholds, gift aid, reserves policy).",
    "table, kv, text, bullets, callout", "Write report", "Reconciling…"),
  T("rules", "Constitution check", "Find the gaps in your rules", "📜",
    [LONG("current", "Paste your constitution or rules (or 'none yet')", "none yet")],
    "Review these club rules against what a well-run club of the profile's structure needs: {current}. Sections: a table (Clause | Present? | Gap | Suggested wording), bullets on the biggest risks in the current wording (or in having none), steps to adopt changes properly at a general meeting, and a callout that charities and companies have regulator requirements to check with the regulator or a solicitor.",
    "table, bullets, steps, callout", "Check rules", "Reading clauses…")],
 "General guidance on running a club, not legal, tax or accounting advice; check your own constitution, your regulator's rules and a professional wherever money or liability is involved.")

APP("reunion_ready", "Reunion Ready", "Get the old crowd back in one room", "Events", ["#AD1457", "#00897B", "#FFB300"], "clock",
 "Reunion Ready plans school, university, family, workplace and service reunions: tracking down the lost, invitations people actually answer, a day that flows, ticket pricing that breaks even and a script for the awkward first ten minutes.",
 "You are a warm, organised reunion organiser: good at nostalgia without cringe, realistic about budgets and RSVP rates, and careful that nobody feels left out.",
 "Bring everyone back together", "Tell us who's reuniting and how big it'll be.", ["Find and re-contact the lost", "Invites that get replies", "A run-sheet for the day"],
 [CH("kind", "Reunion type", ["School year", "University", "Family", "Old workplace", "Military / service", "Childhood friends"]), TXT("group", "Who and when", "Class of 2006, Hillcrest High"), NUM("expected", "Expected guests", "60"), CH("scale", "Scale", ["Pub meet-up", "Dinner", "Full day", "Weekend"])],
 [T("find", "Find the lost", "Track people down respectfully", "🔍",
    [LONG("names", "People you can't reach", "Priya S (moved to Canada?), 'Big Dave' from rugby, the twins…"), TXT("have", "What you already have", "an old Facebook group, 2 email addresses")],
    "Help track down these people: {names}, starting from: {have}. Sections: a table (Person | Best lead | Where to look | Who might know), steps for a respectful search that never tips into creepy, a quote with a short reconnect message for someone found after twenty years, and a callout on privacy: never share someone's details or add them to a group without their OK.",
    "table, steps, quote, callout", "Start the search", "Asking around…"),
  T("invite", "Invitation & RSVP push", "The invite and the follow-ups", "✉️",
    [TXT("details", "Date, venue, cost", "Sat 12 Oct, The Crown, 25 for the buffet", True), CH("tone", "Tone", ["Nostalgic", "Funny", "Simple & clear"], "Nostalgic")],
    "Write the invitation for the reunion ({details}) in a {tone} tone. Sections: a quote with the main invitation under 150 words including a clear RSVP deadline and payment instruction, a second quote with a 40-word group-chat version, a table of the follow-up sequence (When | Channel | Message goal), and bullets on lifting RSVP rates from people who go quiet.",
    "quote, table, bullets", "Write invites", "Licking stamps…"),
  T("runsheet", "Run-sheet for the day", "Timings, kit and memory-lane moments", "🗓️",
    [TXT("venue", "Venue and hours", "function room 6pm to midnight"), TXT("extras", "Extras planned", "slideshow, speeches from 2 people, group photo")],
    "Plan the reunion at {venue} with {extras}. Sections: a table run-sheet (Time | What happens | Who's on it | Notes), a checklist for the organiser's kit bag (name badges with old photos, playlist, signage, cash float), cards for 3 memory-lane activities (meta = minutes · setup effort), and a callout on pacing so speeches don't kill the room.",
    "table, checklist, cards, callout", "Plan the day", "Cueing slides…"),
  T("budget", "Budget & ticket price", "Break even at any turnout", "💷",
    [NUM("cost", "Fixed costs total", "900"), NUM("perhead", "Cost per head (food, drink)", "18"), NUM("rsvp", "Confirmed so far", "35")],
    "Fixed costs {cost}, per-head cost {perhead}, {rsvp} confirmed against the expected guests in the profile. Sections: a table of three attendance scenarios (Attendance | Break-even price | Suggested price | Buffer), kv (deposit needed, cut-off date for final numbers, suggested refund policy), bullets on cutting cost without cheapening the night, and a callout on handling money transparently among old friends.",
    "table, kv, bullets, callout", "Price it", "Counting heads…"),
  T("icebreak", "Break the ice", "The first 30 minutes, handled", "🧊",
    [CH("worry", "Biggest worry", ["Cliques re-forming", "Nobody remembers names", "Awkward silence", "One person dominating", "People leaving early"], "Nobody remembers names")],
    "The organiser's biggest worry is: {worry}. Sections: cards for 4 icebreakers suited to the reunion type and size (meta = minutes · props needed?), a quote with a 90-second welcome speech that sets the tone, steps for the first 30 minutes so nobody stands alone, and bullets on gracefully handling someone who has had a hard time since you last met.",
    "cards, quote, steps, bullets", "Get ideas", "Warming up…")])

APP("supper_circle", "Supper Circle", "A rotating dinner club that actually keeps going", "Social", ["#BF360C", "#FBC02D", "#4A148C"], "cup",
 "Supper Circle runs a rotating dinner club among friends or neighbours: a fair hosting rota, themed host briefs that respect every diet at the table, sensible money rules, a newcomer's first night and the nudges that keep the club alive when life gets busy.",
 "You are a generous, organised dinner-club convenor: you love a theme and good food, hate fuss, and quietly make sure the vegan and the shy newcomer both have a great night.",
 "Same good people, month after month", "Tell us about your circle and how often you meet.", ["A fair hosting rota", "Menus that suit every diet at the table", "Nudges that keep the club alive"],
 [TXT("members", "Members and diets", "Sam & Jo (veggie), Ana (no pork), Lee, Priya (gluten-free)"), CH("cadence", "How often", ["Weekly", "Fortnightly", "Monthly", "Every other month"], "Monthly"), CH("style", "Style", ["Host cooks everything", "Host does main, others bring", "Potluck", "Rotating restaurant"], "Host cooks everything")],
 [T("rota", "Hosting rota", "Who hosts when, fairly", "🔄",
    [TXT("start", "Start month", "October"), TXT("constraints", "Constraints", "Ana can't host until spring, Lee's flat fits 6 max")],
    "Build a hosting rota for the circle starting {start} with constraints: {constraints}. Sections: a table (Date | Host | Theme suggestion | Notes), bullets explaining why the order is fair, a quote with the announcement message for the group chat, and a callout on swap rules for when someone has to drop out.",
    "table, bullets, quote, callout", "Build rota", "Passing the salt…"),
  T("theme", "Host brief", "Theme, menu and timings for the host", "🍽️",
    [TXT("theme", "Theme (or 'surprise me')", "Levantine night"), NUM("guests", "Guests", "8"), CH("effort", "Host effort", ["Easy", "Medium", "Show-off"], "Medium")],
    "The host is doing {theme} for {guests} guests at {effort} effort, respecting every diet listed in the profile. Sections: cards for the menu (starter, main, side, dessert; meta = make-ahead? · which diets it covers), a table of timings for the day (Time | Task | Delegable?), a checklist shopping list grouped by shop section, and a callout on labelling allergens and asking guests about allergies before cooking.",
    "cards, table, checklist, callout", "Plan the night", "Preheating…"),
  T("money", "Money rules", "Keep it generous, not awkward", "💸",
    [CH("model", "Preferred model", ["Host pays", "Split evenly each time", "Monthly kitty", "Bring-your-own"], "Host pays"), TXT("tensions", "Any tensions", "one host always over-spends, students on tight budgets")],
    "Set fair money rules for the circle on a {model} basis, given: {tensions}. Sections: kv (per-person budget cap, who covers drinks, kitty amount if any, how extras like a taxi or a special bottle are handled), a quote with a kind, clear message announcing the rules, bullets on keeping it fun rather than accountancy, and a callout on the money situations that most often break dinner clubs.",
    "kv, quote, bullets, callout", "Set rules", "Splitting fairly…"),
  T("revive", "Attendance rescue", "When the chat goes quiet", "🚑",
    [TXT("problem", "What's happening", "last two dinners only 4 came, chat's gone quiet", True)],
    "The circle's problem: {problem}. Sections: text diagnosing the likely cause in a few sentences, steps for a 6-week revival plan (dates, format changes, who to message personally), a quote with a no-guilt check-in message for the whole group, and cards for 3 lower-effort formats to try (meta = effort · cost).",
    "text, steps, quote, cards", "Rescue it", "Relighting candles…"),
  T("newcomer", "Add a newcomer", "Their first dinner, done well", "👋",
    [TXT("who", "Who's joining", "Jo's new partner, quite shy, coeliac")],
    "Bring {who} into the circle well. Sections: steps for the first dinner they attend (seating, introductions, what to tell the host in advance), a quote with a welcome message explaining how the circle works, bullets of conversation openers tailored to the members in the profile, and a callout on updating the diet list and the rota.",
    "steps, quote, bullets, callout", "Welcome them", "Pulling up a chair…")],
 "Always ask guests directly about allergies and intolerances; menu ideas are suggestions, not allergen guarantees.")

APP("gather_round", "Gather Round", "Start a meetup people keep coming back to", "Social", ["#E65100", "#0277BD", "#7CB342"], "pin",
 "Gather Round helps you launch and run a recurring meetup — a walking group, language exchange, sketching club, parents' coffee morning, anything — with a six-week launch plan, listings that fill the room, a first-timer welcome script and fixes for flaky RSVPs.",
 "You are an experienced community organiser who has started a dozen groups: encouraging, specific, honest that the first six weeks are the hard part, and firm about newcomers feeling safe and included.",
 "Find your people, then keep them", "Tell us the group you want to run and where.", ["A 6-week launch plan", "Listings that fill the room", "Welcome scripts and no-show fixes"],
 [TXT("group", "Your group", "Sunday sketching walks, Bristol"), CH("stage", "Stage", ["Just an idea", "First event planned", "Running, but small", "Running well"]), CH("venue", "Usual venue", ["Café / pub", "Outdoors", "Library / community hall", "Online", "Rotating"]), CH("size", "Ideal size", ["4–8", "8–15", "15–30", "30+"])],
 [T("launch", "Launch plan", "From idea to first six events", "🚀",
    [TXT("first", "Target first-event date", "3 weeks from now"), CH("budget", "Budget", ["Zero", "A little", "Some sponsorship"], "Zero")],
    "Build a launch plan for the group with the first event on {first} and a {budget} budget. Sections: a table (Week | Goal | Actions | Success sign) covering 6 weeks, a checklist of what must be decided before announcing (name, cadence, venue rules, cost, code of conduct), cards for 3 places to find the first members (meta = effort · likely reach), and a callout on the biggest reasons new groups die.",
    "table, checklist, cards, callout", "Plan launch", "Pinning the map…"),
  T("listing", "Write the listing", "Event copy for every channel", "📣",
    [TXT("details", "Next event details", "Sun 10am, Harbourside, bring a sketchbook", True), CH("where", "Posting to", ["Event platform", "Facebook / community group", "Poster", "WhatsApp broadcast", "All"], "All")],
    "Write listings for: {details}, aimed at {where}. Sections: a quote with a 120-word event description (what, who it's for, what to bring, what happens if it rains), a second quote with a 30-word short version, kv (3 title options, best posting times, keywords or hashtags), and bullets on what puts first-timers off in a listing.",
    "quote, kv, bullets", "Write it", "Spreading the word…"),
  T("welcome", "First-timer welcome", "The host's first 15 minutes", "👋",
    [TXT("format", "How the session runs", "20 min chat, 90 min drawing, coffee after")],
    "The session runs: {format}. Sections: steps for the host's first 15 minutes (greeting, names, pairing newcomers with regulars, explaining the format), a quote with a 60-second welcome speech, bullets of icebreaker questions specific to the group's interest, and a callout on safety and inclusion basics (leaving early is fine, no pressure to share, how to raise a concern).",
    "steps, quote, bullets, callout", "Get the script", "Setting out chairs…"),
  T("noshow", "Fix flaky RSVPs", "Turn 20 yeses into 15 people", "🎈",
    [NUM("rsvp", "Typical RSVPs", "20"), NUM("show", "Typical turnout", "6"), TXT("tried", "What you've tried", "reminder the day before")],
    "RSVPs {rsvp}, turnout {show}; tried so far: {tried}. Sections: text explaining the likely reasons for the gap, a table (Tactic | Why it works | Effort | Try when), a quote with a reminder message that raises turnout without nagging, and steps for a 4-event experiment to find what works for this group.",
    "text, table, quote, steps", "Fix it", "Counting chairs…"),
  T("grow", "Hand over & grow", "Co-hosts, splits and stepping back", "🌱",
    [CH("goal", "Goal", ["Recruit co-hosts", "Split into two groups", "Add a second format", "Step back without it dying"], "Recruit co-hosts")],
    "Goal: {goal}. Sections: steps to get there over 8 weeks, cards for the roles to fill (meta = hours/month · skills), a quote with the ask-message to a regular you'd like as a co-host, and a callout on what to write down so the group survives you.",
    "steps, cards, quote, callout", "Plan it", "Growing roots…")],
 "Meeting strangers carries some risk: use public venues, tell someone your plans, and follow local rules for events in public spaces.")

APP("shift_captain", "Shift Captain", "Rotas, briefings and thank-yous for your volunteers", "Events", ["#F57F17", "#1A237E", "#00ACC1"], "calendar",
 "Shift Captain is for whoever is coordinating volunteers at a festival, fun run, food bank, fete or weekly service: it builds rotas from messy availability, writes role briefs and the morning briefing, plans for no-shows and says thank you properly.",
 "You are a calm volunteer coordinator who has run hundreds of shifts: you plan for no-shows, brief people so they feel confident, and treat every volunteer's time as precious.",
 "Every shift covered, every volunteer thanked", "Tell us about the event or service you run volunteers for.", ["Rotas from messy availability", "Role briefs and day-of scripts", "No-show plans and retention"],
 [TXT("org", "Event or organisation", "Riverside 10K, September"), CH("setting", "Setting", ["One-off event", "Weekly service", "Seasonal campaign", "Ongoing charity"]), NUM("pool", "Volunteer pool size", "40")],
 [T("rota", "Build the rota", "Slots filled from who's free", "🗓️",
    [LONG("availability", "Availability & skills", "Sam: Sat am only, can marshal; Priya: all day, first-aider; Dev: pm, can't stand long…"), TXT("slots", "Slots to fill", "6 marshals 8–11, 2 water station 9–12, 1 registration 7–9", True)],
    "Fill these slots: {slots} from this availability: {availability}. Sections: a table (Slot | Time | Volunteer | Backup), bullets of gaps and who could plausibly cover them, kv (total volunteer-hours, people under-used, people over-used, longest shift), and a callout on breaks, weather and accessibility needs to check with each person.",
    "table, bullets, kv, callout", "Build rota", "Filling slots…"),
  T("brief", "Role brief", "One page a volunteer can read in 3 minutes", "📋",
    [TXT("role", "Role", "course marshal at the tricky junction", True), TXT("hazards", "Site notes / hazards", "road crossing, cyclists, no shade")],
    "Write a one-page brief for the role: {role}, with site notes: {hazards}. Sections: kv (report to, where, when, what to bring, how to raise a problem), steps for the shift from arrival to sign-off, a checklist of what doing it well looks like, and a callout on safety: what they must never do and who to call.",
    "kv, steps, checklist, callout", "Write brief", "Briefing…"),
  T("morning", "Morning briefing", "The 4-minute speech before doors", "🎤",
    [NUM("count", "Volunteers present", "25"), TXT("changes", "Late changes", "route diverted at mile 3, two marshals off sick")],
    "Write the morning briefing for {count} volunteers with these late changes: {changes}. Sections: a quote with the 4-minute spoken briefing (welcome, purpose, safety, changes, radios and contacts, thanks), a checklist of items to show or hand out, bullets of likely questions with answers, and a callout on the single safety message to repeat.",
    "quote, checklist, bullets, callout", "Write briefing", "Clearing throat…"),
  T("noshow", "No-show contingency", "Minimum safe cover for critical roles", "🚨",
    [TXT("critical", "Critical roles", "first-aiders x2, finish-line timing, lead marshal")],
    "Plan contingencies for these critical roles: {critical}. Sections: a table (Role | If they don't show | Minimum safe cover | Who decides), steps for the 60 minutes before start (confirmations, redeployments, when to delay or cancel), a quote with the confirmation message to send the night before, and a callout on never running unsafe if cover falls short.",
    "table, steps, quote, callout", "Plan cover", "Thinking ahead…"),
  T("thanks", "Thank & retain", "Messages, survey and next-time plan", "💌",
    [TXT("highlights", "What happened", "rain all morning, Priya handled a fall brilliantly, 380 finishers")],
    "Given: {highlights}, write the thank-you and retention plan. Sections: a quote with a 150-word thank-you to all volunteers, a second quote with a personal note to a stand-out volunteer, bullets for a 5-question feedback survey, and a table (When | Touchpoint | Purpose) for staying in contact until the next event.",
    "quote, bullets, table", "Say thanks", "Writing cards…")],
 "Safety, safeguarding and insurance are your organisation's responsibility: follow its policies, risk assessments and local rules on background checks.")

APP("team_sheet", "Team Sheet", "The admin side of amateur sport, sorted", "Sports", ["#0D47A1", "#FFC107", "#D32F2F"], "dumbbell",
 "Team Sheet handles the thankless admin of a Sunday-league, netball, cricket or five-a-side team: availability chasing, selection messages that don't cause sulks, subs collection, match-day logistics and the end-of-season awards night.",
 "You are the unflappable manager-secretary of an amateur team: fair, organised, tactful about dropping people, and allergic to chasing money twice.",
 "Less chasing, more playing", "Tell us about your team so messages and rotas fit.", ["Availability and selection messages", "Subs and kitty chasing", "Match-day logistics and awards"],
 [TXT("team", "Team", "Hackney Wanderers, 11-a-side, Sunday league"), NUM("squad", "Squad size", "18"), CH("level", "Level", ["Social / fun", "Competitive league", "Cup-chasing"], "Competitive league"), NUM("subs", "Match subs per player", "8")],
 [T("avail", "Availability chase", "Get replies before Friday", "📲",
    [TXT("fixture", "Next fixture", "Sun 10:30 vs Rovers, away, Hackney Marshes", True), TXT("silent", "Who hasn't replied", "Tom, Ade, Marcus")],
    "For the fixture {fixture}, with no reply yet from: {silent}. Sections: a quote with a group message that gets replies (deadline, how to reply, what happens if they don't), a second quote with a friendly individual nudge, a table (Day | Message | Purpose) for the week's comms, and bullets on making availability replies a habit.",
    "quote, table, bullets", "Write messages", "Poking the chat…"),
  T("select", "Pick the team", "A line-up and a tactful bench message", "📋",
    [LONG("available", "Who's available and notes", "GK: Jay; Def: Sam, Kofi (just back from injury), Lee…"), TXT("opponent", "Opposition and form", "Rovers, physical, beat us 3–1 last time")],
    "Select the team from: {available} against {opponent}, appropriate to the team's level in the profile. Sections: a table (Position | Player | Why | Sub plan), bullets on rotation so minutes are shared in a way that fits the level, a quote with a tactful message to anyone not starting, and a callout on the fitness or injury risks in the squad list.",
    "table, bullets, quote, callout", "Select", "Picking the XI…"),
  T("money", "Subs & kitty", "Chase once, kindly", "💷",
    [LONG("owed", "Who owes what", "Tom 24 (3 games), Ade 8, Marcus 40 and the ref money"), TXT("costs", "Upcoming costs", "pitch 90/wk, ref 40, new balls 60")],
    "Sort the team money: owed: {owed}; upcoming: {costs}. Sections: a table (Player | Owed | Games | Nudge level), kv (weekly break-even, per-player cost, kitty target, suggested payment method), a quote with a firm-but-friendly chasing message, and a callout on a no-pay-no-play rule and how to introduce it fairly.",
    "table, kv, quote, callout", "Chase subs", "Rattling the tin…"),
  T("matchday", "Match-day logistics", "Lifts, kit bag and timings", "🚗",
    [TXT("details", "Fixture details", "away at Rovers, 10:30 KO, 14 travelling, 3 cars", True)],
    "Organise match day for: {details}. Sections: a table (Time | What | Who) from meet-up to post-match, a checklist for the kit bag (bibs, balls, first-aid kit, ref money, team sheet), kv (car plan, meet point, contact numbers to collect), and a callout on the first-aid and emergency basics the manager should know.",
    "table, checklist, kv, callout", "Plan it", "Loading the boot…"),
  T("awards", "End-of-season night", "Awards, speech and next season", "🏆",
    [LONG("season", "Season summary", "finished 4th, Jay 12 clean sheets, Ade top scorer with 19, Sam never missed a game"), CH("format", "Format", ["Pub night", "Dinner", "Family BBQ"], "Pub night")],
    "From this season: {season}, plan an end-of-season {format}. Sections: cards for 6 awards with winners (meta = award · winner), a quote with a 2-minute manager's speech, a table run-sheet for the night (Time | Item | Who), and bullets on next season's recruitment and retention.",
    "cards, quote, table, bullets", "Plan awards", "Polishing trophies…")],
 "Not medical advice: follow your league's rules on injuries, concussion and first-aid cover, and never let an injured player return on your say-so alone.")

APP("local_voice", "Local Voice", "Organise your neighbours and get the council to act", "Social", ["#B71C1C", "#FDD835", "#263238"], "mic",
 "Local Voice helps residents organise around a local issue — a dangerous crossing, a closing library, a planning application — with a map of who actually decides, petitions and letters that get answered, a public meeting plan, door-knocking scripts and press copy.",
 "You are a seasoned community organiser: practical, non-partisan, respectful of officials and neighbours alike, and clear that lawful, well-evidenced campaigns are the ones that win.",
 "Turn a grumble into a campaign", "Tell us the issue and where it is; we'll map the route to a decision.", ["Petitions and letters that get answered", "Public meeting plans", "Door-knocking and press scripts"],
 [TXT("issue", "The issue", "speeding on Elm Road outside the primary school"), TXT("area", "Area / council", "Elm Road, Greenford, Ealing Council"), CH("stage", "Stage", ["Just noticed", "Gathering support", "Formal campaign", "Decision pending"])],
 [T("map", "Who decides?", "The route from evidence to decision", "🗺️",
    [TXT("known", "What you already know", "councillor's name is on a leaflet, there's a residents' association")],
    "Map the route to a decision on the profile's issue, given: {known}. Sections: a table (Body or person | What they control | How to reach them | The ask), steps for the campaign in order from evidence to decision, bullets of the evidence worth collecting first, and a callout that procedures differ by council and country and must be checked locally.",
    "table, steps, bullets, callout", "Map it", "Mapping power…"),
  T("petition", "Petition & letter", "Wording officials take seriously", "✍️",
    [CH("ask", "Format", ["Petition", "Letter to councillor", "Formal objection / representation", "All three"], "All three"), TXT("evidence", "Evidence so far", "3 near-misses this term, 2 photos, 40 signatures")],
    "Draft the {ask} using this evidence: {evidence}. Sections: a quote with the petition wording (one clear ask, under 100 words) and/or the letter text as appropriate, kv (who it goes to, signatures typically needed for a hearing, deadline, delivery method), bullets on what makes officials take a document seriously, and a callout on data protection when collecting names and addresses.",
    "quote, kv, bullets, callout", "Draft it", "Sharpening pencils…"),
  T("meeting", "Public meeting", "A run-sheet that stays civil", "🏛️",
    [TXT("when", "When and where", "Thu 7pm, school hall, councillor invited"), NUM("expected", "Expected turnout", "50")],
    "Plan a public meeting: {when}, around {expected} people. Sections: a table run-sheet (Time | Item | Who | Purpose), a quote with the chair's opening and the rules for speaking, a checklist for setup and follow-up (sign-in sheet, note-taker, press, accessibility), and a callout on keeping it civil when tempers run high.",
    "table, quote, checklist, callout", "Plan meeting", "Setting chairs…"),
  T("doors", "Door-knocking script", "45 seconds on the doorstep", "🚪",
    [CH("goal", "Goal", ["Signatures", "Meeting turnout", "Volunteers", "Survey"], "Signatures")],
    "Write a door-knocking script aimed at {goal} for the profile's issue. Sections: a quote with the 45-second doorstep script, a table of objections and replies (They say | You say), bullets on safety and etiquette (go in pairs, sensible hours, respect no-cold-calling signs, leave a note), and a checklist for the clipboard.",
    "quote, table, bullets, checklist", "Write script", "Lacing boots…"),
  T("press", "Press & social", "Get the story out, factually", "📰",
    [TXT("hook", "News hook", "council votes next week; 200 signatures", True)],
    "Publicise the campaign with this hook: {hook}. Sections: a quote with a 200-word press release (headline, a resident's quote, the ask, contact line), cards for 3 social posts (meta = platform · goal), a table (Outlet type | Angle | When to send), and a callout on staying factual and avoiding claims about named individuals.",
    "quote, cards, table, callout", "Get coverage", "Calling the paper…")],
 "Not legal advice: rules on petitions, protests, data protection and planning objections vary by council and country; check them before you act.")

APP("green_room", "Green Room", "Run an am-dram show from auditions to curtain call", "Events", ["#4A148C", "#FFD600", "#C62828"], "hat",
 "Green Room is the stage manager's brain for community theatre, school shows and youth productions: audition notices, rehearsal schedules that respect people's evenings, props and costume lists from the script, front-of-house rotas and break-even ticket prices, plus programme and publicity copy.",
 "You are a veteran amateur-theatre producer and stage manager: enthusiastic, ruthlessly organised, kind to nervous first-timers, and fully aware everyone has a day job.",
 "Places, everyone", "Tell us about your society and the show.", ["Rehearsal schedules people can keep", "Audition and casting help", "Props, costume and front-of-house lists"],
 [TXT("society", "Society", "Bramley Players, village hall"), TXT("show", "Show", "Blithe Spirit, 3 performances in March"), CH("role", "Your role", ["Director", "Producer", "Stage manager", "Committee", "Helping out"]), CH("cast", "Cast size", ["Under 8", "8–15", "15–30", "30+"])],
 [T("audition", "Audition pack", "Notice, pieces and panel checklist", "🎭",
    [TXT("dates", "Audition dates", "Tue 14 & Thu 16 Jan, 7:30pm", True), TXT("needs", "Roles you need", "2 men 40s, 3 women 30–60, one cameo any age")],
    "Prepare auditions on {dates} for: {needs}. Sections: a quote with the audition notice (show, dates, roles with age ranges, what to prepare, commitment expected, contact), a table of audition pieces (Role | Scene or moment | What to look for), a checklist for the panel on the night, and a callout on fair casting and telling people kindly when they didn't get it.",
    "quote, table, checklist, callout", "Build pack", "Warming up…"),
  T("schedule", "Rehearsal schedule", "Calls that respect people's lives", "📅",
    [TXT("window", "Rehearsal window", "20 Jan to 12 Mar, Tue and Thu evenings plus 2 Sundays"), TXT("clashes", "Known clashes", "Dev away 2–9 Feb, under-16s not after 9pm"), CH("acts", "Script size", ["One act", "Two acts", "Three acts", "Musical"], "Three acts")],
    "Build a rehearsal schedule across {window} for a {acts} show with clashes: {clashes}. Sections: a table (Date | Scenes | Who's called | Focus), bullets on the plan's logic (blocking first, runs later, tech and dress at the end), kv (total rehearsals, run-throughs, tech, dress, get-in), and a callout on never calling people who aren't needed.",
    "table, bullets, kv, callout", "Schedule", "Calling the cast…"),
  T("lists", "Props & costume", "Production lists from the script", "🎩",
    [LONG("script", "Paste a scene or act summary", "Act 1: living room, seance, gramophone, tray of martinis, Madame Arcati in a cape…")],
    "From: {script}, build production lists. Sections: a table of props (Item | Scene | Who handles | Source: own, borrow, make or buy | Cost est.), a second table of costume by character (Character | Look | Changes | Notes), a checklist setting list per scene for stage management, and a callout on fire, weapons and food on stage.",
    "table, checklist, callout", "Build lists", "Rummaging backstage…"),
  T("foh", "Front of house", "Ticket prices, rota and house rules", "🎟️",
    [NUM("seats", "Seats per night", "120"), NUM("nights", "Performances", "3"), TXT("costs", "Production costs", "rights 400, set 300, costumes 200, hall 250")],
    "{seats} seats across {nights} nights with costs: {costs}. Sections: kv (break-even at three price points, suggested ticket prices, interval bar target), a table front-of-house rota (Night | Box office | Ushers | Bar | Stage door), a checklist for house management (safety announcement, exits, first aid, cash), and a callout on performance rights and licensing to confirm before selling a single ticket.",
    "kv, table, checklist, callout", "Plan FOH", "Counting seats…"),
  T("programme", "Programme & publicity", "Director's note, posts and listing", "📰",
    [TXT("angle", "Angle", "our 50th anniversary, first youth cast member")],
    "Write publicity with this angle: {angle}. Sections: a quote with a 150-word director's note for the programme, cards for 4 social posts across the run (meta = week · goal), a second quote with a 100-word local press listing, and bullets on programme content order (cast, crew, thanks, next show, sponsors).",
    "quote, cards, bullets", "Write copy", "Printing flyers…")],
 "Performance rights, licensing, insurance and safeguarding for under-18s are legal requirements that vary by place; confirm them with the rights holder and your venue.")

APP("club_bulletin", "Club Bulletin", "Newsletters and notices your members actually read", "Social", ["#00695C", "#FF7043", "#3949AB"], "note",
 "Club Bulletin writes the communications for any community group: monthly newsletters from scrappy notes, event announcements in three lengths, welcome packs for new members, member spotlights and a critique of the poster from a photo.",
 "You are a friendly community-communications editor: concise, warm, allergic to jargon and walls of text, and you always give the reader one clear thing to do.",
 "Say it once, clearly", "Tell us about your group and how you reach people.", ["Newsletters from your notes", "Announcements in 3 lengths", "Welcome packs and spotlights"],
 [TXT("group", "Group", "Northfield Cycling Club, about 120 members"), CH("channels", "Channels", ["Email", "WhatsApp", "Facebook group", "Noticeboard", "Website"], multi=True), CH("voice", "Voice", ["Friendly", "Formal", "Playful", "Short & punchy"], "Friendly")],
 [T("newsletter", "Monthly newsletter", "Scrappy notes into a clean issue", "📰",
    [LONG("notes", "This month's notes", "club rode 300km total; kit orders close 20th; Sue won the vets race; AGM 5 Nov; need marshals for the sportive"), CH("length", "Length", ["Short (200 words)", "Standard (400 words)", "Long (700 words)"], "Standard (400 words)")],
    "Write the newsletter at {length} from: {notes}, in the group's voice. Sections: text with a headline, a warm intro and the news in scannable sub-sections, a table of dates (Date | What | Where | Action), a checklist of asks with clear owners and deadlines, and a quote with the subject line plus two alternatives.",
    "text, table, checklist, quote", "Write it", "Typesetting…"),
  T("announce", "Announce an event", "One event, three lengths", "📣",
    [TXT("event", "Event details", "Club sportive Sun 8 Sept, 60/100km, 15 entry, marshals needed", True)],
    "Announce: {event}. Sections: three quotes — a 40-word WhatsApp version, a 120-word email or Facebook version, and a 15-word noticeboard headline with sub-line — then kv (call to action, deadline, link or contact placeholder, best send time), and bullets on a 3-message reminder sequence.",
    "quote, kv, bullets", "Announce", "Ringing the bell…"),
  T("welcome", "New member pack", "Everything a newcomer needs to know", "🤝",
    [TXT("basics", "How the group works", "rides Sat 8am from the café, subs 25/yr, WhatsApp for chat, kit via website")],
    "Build a welcome pack from: {basics}. Sections: a quote with a 150-word welcome message, kv (where and when, cost, how to get help, who's who), a checklist for the first month (join the chat, first session, pay subs, meet the buddy), and bullets of unwritten rules explained kindly.",
    "quote, kv, checklist, bullets", "Build pack", "Opening the door…"),
  T("spotlight", "Member spotlight", "Questions or a finished piece", "🌟",
    [TXT("who", "Member", "Sue, joined 2019, just won her age category", True), TXT("answers", "Their answers (if you have them)", "")],
    "Feature {who}. If answers are provided here — {answers} — write the piece; otherwise write the questions and a draft structure. Sections: bullets of 8 interview questions tuned to the group, text of a 200-word spotlight piece (or its structure if no answers yet), a quote with a one-line pull quote, and a callout on getting consent for the photo and story before publishing.",
    "bullets, text, quote, callout", "Spotlight", "Warming the lights…"),
  T("poster", "Poster check", "Photo → what to fix", "🖼️",
    [PHOTO("Photo of your poster or flyer", "", True)],
    "Critique the poster in the photo. Sections: a table (Element | Now | Fix), bullets on hierarchy and readability from 3 metres away, a quote with a rewritten headline and sub-line, and a callout on what a public poster needs (contact, permission to post, accessibility basics).",
    "table, bullets, quote, callout", "Check poster", "Squinting…")],
 "Handle members' contact details and photos under your local data-protection rules and with consent; this is writing help, not legal advice.")

APP("head_count", "Head Count", "Big group trips and weekends without the chaos", "Events", ["#00838F", "#F4511E", "#FFD54F"], "bag",
 "Head Count organises big-group outings — hen and stag weekends, birthday trips, festival crews, group holidays — from date polling and deposit chasing to an itinerary with a budget per head and scripts for the tricky messages.",
 "You are the friend who always ends up organising: decisive, budget-conscious, tactful with the flaky and the broke, and determined that the guest of honour has a great time.",
 "Wrangle the group", "Tell us what you're organising and for whom.", ["Date polls and deposit chasers", "Itineraries with a budget per head", "Scripts for the tricky messages"],
 [CH("kind", "What is it", ["Hen / bachelorette", "Stag / bachelor", "Birthday trip", "Festival crew", "Group holiday", "Ski / activity weekend"]), TXT("honour", "Guest of honour & vibe", "Maya — loves food, hates clubs"), NUM("people", "Group size", "14"), CH("budget", "Budget per head", ["Under 150", "150–300", "300–600", "600+"])],
 [T("dates", "Lock the dates", "A poll that actually closes", "📆",
    [TXT("options", "Candidate dates", "3–5 May, 17–19 May, 7–9 June"), TXT("constraints", "Known constraints", "two people can't do June, bride prefers May")],
    "Options: {options}; constraints: {constraints}. Sections: a table scoring each option (Dates | Likely attendance | Cost signals | Risk), a quote with a poll message that forces a decision by a deadline, steps to close the decision within 5 days, and a callout on prioritising the guest of honour over perfect attendance.",
    "table, quote, steps, callout", "Run the poll", "Herding calendars…"),
  T("itinerary", "Plan the weekend", "Day by day with cost per head", "🗺️",
    [TXT("where", "Destination & dates", "Lisbon, Fri to Sun", True), TXT("musts", "Must-haves", "one big dinner, a boat, a chill morning")],
    "Plan {where} for the group with must-haves: {musts}, within the profile's budget per head. Sections: a table itinerary (Day | Time | Activity | Cost per head | Booking needed?), cards for 3 optional activities people can opt out of (meta = cost · energy), a checklist of what to book in what order with deposit timing, and a callout on pacing and rest for a group this size.",
    "table, cards, checklist, callout", "Plan it", "Packing…"),
  T("money", "Money & deposits", "Who owes what, and the chaser", "💳",
    [LONG("costs", "Costs so far", "villa 1,800, boat 420, dinner about 45pp, transfers 160"), TXT("paid", "Who's paid", "9 of 14 paid the deposit; Jess says she might drop out")],
    "Costs: {costs}. Payments: {paid}. Sections: kv (total per head, deposit per head, final balance date, what happens if someone drops out), a table (Person | Paid | Owed | Nudge level), a quote with a clear, non-awkward chasing message, and a callout on protecting yourself from being left holding a booking.",
    "kv, table, quote, callout", "Sort money", "Splitting the bill…"),
  T("messages", "The tricky message", "Say the hard thing kindly", "💬",
    [CH("situation", "Situation", ["Someone can't afford it", "Someone's dropping out late", "Two people don't get along", "The plan changed", "Someone's being difficult", "Uninviting someone"], "Someone can't afford it"), TXT("details", "Details", "")],
    "Situation: {situation}. Details: {details}. Sections: text on what's really at stake, a quote with the message to send (kind, clear, under 120 words), a second quote with a version for the wider group if one is needed, and bullets on what not to say.",
    "text, quote, bullets", "Write it", "Choosing words…"),
  T("day", "Run-sheet & kit", "The big day, minute by minute", "🎒",
    [TXT("day", "The big day or night", "Saturday: brunch, boat 2pm, dinner 8pm, bar after")],
    "Build the run-sheet for: {day}. Sections: a table (Time | What | Meeting point | Who's leading), a checklist for the organiser's bag (chargers, cash, painkillers, decorations, booking confirmations), a quote with the morning briefing message for the group, and a callout on looking after people: water, a buddy system and knowing when someone has had too much.",
    "table, checklist, quote, callout", "Build run-sheet", "Setting alarms…")],
 "Look after each other: drink responsibly, follow local laws and never leave someone alone who is unwell; deposits and bookings are your own financial responsibility.")
