from dsl import *

# w42 — Games / Entertainment: GM tools, solo RPG, puzzle setting, escape rooms,
# murder mystery, party games, trivia training, board-game design, video-game
# guides, film nights.

APP("dungeon_desk", "Dungeon Desk", "Session prep, NPCs and encounters in minutes", "Games", ["#4E342E", "#D84315", "#FBC02D"], "hat",
 "Dungeon Desk is the game master's prep desk: it preps tonight's session, balances encounters for your party, invents NPCs with voices and secrets, and improvises when players wander off the map.",
 "You are a veteran tabletop game master: vivid but concise, generous with hooks and secrets, always balancing challenge to the party and respecting the table's tone.",
 "Run tables like a pro", "Tell us your system and party so every encounter and NPC fits.", ["Encounters balanced to your party", "NPCs with voice, secret and hook", "Improv rescue when plans derail"],
 [CH("system", "System", ["D&D 5e", "Pathfinder 2e", "OSR / old-school", "Other d20", "Narrative (PbtA, FATE)"]), NUM("size", "Party size", "4"), NUM("level", "Party level", "3"), CH("tone", "Campaign tone", ["Heroic", "Grim", "Comedic", "Horror", "Political intrigue"])],
 [T("prep", "Prep tonight's session", "Outline, scenes, contingencies", "🗺️",
    [LONG("state", "Where the campaign stands", "Party just reached Greyhollow chasing the cult; the rogue owes the thieves' guild…"), TXT("goal", "What tonight should achieve", "reveal the cult leader's identity"), CH("length", "Session length", ["2 hours", "3 hours", "4+ hours"], "3 hours")],
    "Campaign state: {state}. Tonight's goal: {goal}. Length: {length}. Produce a text opening-scene read-aloud, steps for 4–6 scenes (each with purpose, likely player action and an 'if they skip it' fallback), a table of NPCs needed (Name | Role | Wants | One-line voice), a checklist of things to prepare before play (maps, stat blocks, handouts), and a callout on the one twist to hold back until the right moment.",
    "text, steps, table, checklist, callout", "Prep session", "Rolling initiative…"),
  T("npc", "NPC on the spot", "Name, voice, secret, hook", "🎭",
    [TXT("role", "Who are they", "a suspicious innkeeper in a port town", True), CH("importance", "Importance", ["Throwaway", "Recurring", "Major"], "Recurring")],
    "Create a {importance} NPC: {role}, matching the campaign tone. Output kv (name, ancestry, age, appearance in 8 words, mannerism, voice cue for the GM, what they want, what they fear, the secret they hide), a quote of three lines of dialogue in their voice, and bullets of 3 plot hooks they could hand the party.",
    "kv, quote, bullets", "Create NPC", "Rolling a stranger…"),
  T("encounter", "Build an encounter", "Balanced for the party", "⚔️",
    [CH("difficulty", "Difficulty", ["Easy", "Medium", "Hard", "Deadly"], "Medium"), TXT("setting", "Setting", "collapsed mine shaft, low light, unstable ceiling"), TXT("enemies", "Enemy type (optional)", "goblins and a bugbear")],
    "Design a {difficulty} encounter for the profile party in: {setting}, using {enemies} if given. Sections: a table of combatants (Creature | Count | Role in the fight | Key ability | System notes), text describing the battlefield with 3 interactive features, steps for enemy tactics round by round, a kv of the encounter budget maths for the profile system (XP or level budget, thresholds, adjusted total), and a callout on how to scale it up or down mid-fight.",
    "table, text, steps, kv, callout", "Build it", "Balancing the odds…"),
  T("derail", "They went off the rails", "Improvise the next hour", "🧭",
    [LONG("happened", "What the players just did", "they ignored the quest, robbed the mayor and set sail for the pirate isles")],
    "The players did this: {happened}. Do not punish them; make it fun. Give text with the immediate consequence and a hook, cards for 3 directions the next hour could take (meta = prep needed: none / light / heavy), a table of complications to drop in (Complication | Trigger | Payoff), and a callout on how to reconnect this to the main plot later.",
    "text, cards, table, callout", "Improvise", "Rolling with it…"),
  T("loot", "Loot & treasure", "Rewards that fit the level", "💰",
    [TXT("source", "Where the loot comes from", "dragon's hoard / cult leader's vault", True), CH("style", "Style", ["By the book", "Mostly story items", "Cursed and weird"], "By the book")],
    "Generate a treasure haul from {source} for the profile party, style {style}. Output a table (Item | Type | Value or rarity | Who it suits | Story note), cards for 2 unique signature items (meta = rarity · attunement), a kv of coin totals split per player, and a callout on any item that could unbalance the campaign.",
    "table, cards, kv, callout", "Roll loot", "Opening the chest…")])

APP("solo_quest", "Solo Quest", "A game master in your pocket for solo roleplaying", "Games", ["#37474F", "#8D6E63", "#FFB300"], "moon",
 "Solo Quest runs the game when nobody else can: an oracle that answers with twists, scenes that end in real choices, random places to explore, faction maps and a journal that keeps your threads straight.",
 "You are a solo-RPG game master and oracle: evocative, fair, never railroading; you end every scene with a decision and keep continuity with what the player has told you.",
 "Adventure, no group required", "Tell Solo Quest your hero and world; it remembers them in every scene.", ["Oracle answers with twists", "Scenes that end in choices", "Journal that tracks your threads"],
 [TXT("hero", "Your character", "Kess, a disgraced knight carrying a stolen relic"), CH("genre", "Genre", ["High fantasy", "Grimdark", "Sci-fi", "Post-apocalypse", "Cosy", "Mystery"]), TXT("world", "World notes", "the Empire fell 30 years ago; magic is illegal")],
 [T("oracle", "Ask the oracle", "Yes/no with a twist", "🔮",
    [TXT("question", "Your question", "Is the bridge guarded?", True), CH("odds", "Likelihood", ["Very unlikely", "Unlikely", "50/50", "Likely", "Very likely"], "50/50")],
    "Answer the oracle question '{question}' with likelihood {odds}: choose an outcome whose odds match the likelihood, leaning toward the more interesting result, and state it plainly as one of Yes / Yes, and / Yes, but / No / No, but / No, and. Give kv (answer, twist, how likely it was), text of 2–3 sentences describing what the hero perceives in the profile genre and world, and bullets of 3 things they could do next.",
    "kv, text, bullets", "Consult", "Casting the bones…"),
  T("scene", "Run the next scene", "Narrate, then hand me a choice", "🎬",
    [LONG("situation", "Where we are and what just happened", "I entered the ruined chapel; the relic is humming"), CH("mood", "Scene mood", ["Tense", "Action", "Quiet", "Eerie", "Social"], "Tense")],
    "Continue from: {situation} with a {mood} mood, in the profile genre and world. Write text narrating the scene (150–220 words, second person, never deciding for the hero), then cards for 3 distinct choices (meta = risk: low / medium / high), and a callout with a complication to introduce if the hero plays it safe.",
    "text, cards, callout", "Play on", "Setting the scene…"),
  T("place", "Random location", "Somewhere to explore", "🏚️",
    [CH("kind", "Kind of place", ["Wilderness", "Settlement", "Dungeon or ruin", "Ship or vehicle", "Stronghold"], "Dungeon or ruin"), NUM("rooms", "Rooms or areas", "6")],
    "Generate a {kind} with {rooms} areas for the profile genre. Output text (name and a one-paragraph impression), a table (Area | What's there | Danger | Treasure or clue), bullets of 3 rumours the hero could have heard about it, and a kv of the place's secret, current occupants and what happens if it is left alone.",
    "text, table, bullets, kv", "Generate", "Mapping the unknown…"),
  T("faction", "Factions & rumours", "Who wants what", "🏴",
    [TXT("region", "Region or city", "the free port of Salt Reach", True)],
    "Create the power map of {region} for the profile world. Output a table of 4 factions (Faction | Leader | Wants | Fears | How they treat the hero) and bullets of 6 rumours mixing true and false without marking them. Then a kv headed 'Oracle only' listing which rumours are true for the player to reveal later, and a callout on the conflict about to boil over.",
    "table, bullets, kv, callout", "Map powers", "Listening at doors…"),
  T("journal", "Journal my session", "Notes → recap and threads", "📓",
    [LONG("notes", "Session notes", "fought cultists, met Old Marn, lost the map, oracle said the relic is alive")],
    "Turn these notes into a chronicle: {notes}. Write a quote of 4–6 lines as the hero's journal entry in their voice, a table of open threads (Thread | Status | Next step), a kv of NPCs met and their disposition, and bullets of 3 possible openings for the next session.",
    "quote, table, kv, bullets", "Chronicle", "Inking the page…")])

APP("grid_setter", "Grid Setter", "Crossword clues that are fair, funny and fiendish", "Games", ["#212121", "#D32F2F", "#FBC02D"], "note",
 "Grid Setter is a crossword constructor's assistant: cryptic and quick clues for any answer, themed entry sets that fit your grid, editor-grade fairness checks on your clues and plain-English parses of any cryptic.",
 "You are an experienced crossword setter and editor: precise about cryptic grammar, allergic to unfair indicators, playful with surfaces, and you explain every device you use.",
 "Set puzzles people finish", "Tell us your style so clues match your house rules.", ["Cryptic + quick clues for any word", "Themed entries that fit your grid", "Editor-grade fairness checks"],
 [CH("style", "Clue style", ["British cryptic", "American-style", "Quick / concise", "Mixed"]), CH("level", "Target solver", ["Beginner", "Regular", "Expert"]), TXT("rules", "House rules", "no indirect anagrams, Ximenean")],
 [T("clue", "Clue this word", "Several devices, ranked", "✏️",
    [TXT("answer", "Answer", "CARPENTER", True), TXT("theme", "Puzzle theme (optional)", "tools of the trade"), NUM("count", "How many clues", "5")],
    "Write {count} clues for the answer {answer}, fitting the theme {theme} if given, in the profile style and level. Output a table (Clue | Device | Definition | Wordplay parse | Difficulty 1–5) ordered best first, bullets on which surface reads most naturally and why, and a callout flagging any clue that bends the house rules.",
    "table, bullets, callout", "Write clues", "Sharpening pencils…"),
  T("theme", "Theme a puzzle", "Entries + a gimmick", "🧩",
    [TXT("theme", "Theme", "1990s sitcoms", True), CH("size", "Grid size", ["11×11", "13×13", "15×15", "21×21"], "15×15"), TXT("lengths", "Lengths you need (optional)", "two 15s, four 9s")],
    "Build a themed entry set for a {size} grid on {theme}, honouring the lengths {lengths} if given. Give text with the gimmick or revealer idea, a table of theme entries (Entry | Length | Why it fits | Symmetry partner), bullets of 10 shorter fill words that reinforce the theme, and a callout on obscurity risks for the profile solver level.",
    "text, table, bullets, callout", "Build theme", "Filling the grid…"),
  T("check", "Check my clue", "Editor's verdict", "🔍",
    [TXT("clue", "Your clue", "Sailor's drink taken back in dive (6)", True), TXT("answer", "Intended answer", "the word the clue should yield", True)],
    "Edit this clue: '{clue}' for the answer {answer} under the profile house rules. Provide kv (definition, wordplay parse, device, surface reading score /10, fairness verdict), bullets of specific problems (unindicated parts, indirect anagram, misleading grammar, wrong enumeration), a quote with a revised version of the clue, and a callout on whether it suits the target solver.",
    "kv, bullets, quote, callout", "Check it", "Reading closely…"),
  T("parse", "Explain a cryptic", "How does this clue work?", "💡",
    [TXT("clue", "The clue", "Flower of London? (6)", True), TXT("answer", "Answer if known", "")],
    "Parse the cryptic clue '{clue}' (answer if known: {answer}). Give text naming the answer and the device in one line, steps walking through each part of the wordplay, a kv of the definition, indicator words and fodder, and bullets of 3 similar devices to watch for.",
    "text, steps, kv, bullets", "Explain", "Decoding…"),
  T("fill", "Words for a pattern", "Fit letters and a flavour", "🔤",
    [TXT("pattern", "Letter pattern (? = unknown)", "C?R?E?", True), TXT("flavour", "Preferred flavour", "food words, avoid abbreviations")],
    "List up to 12 words matching the pattern {pattern} (question mark = any letter), preferring {flavour}. Check every candidate letter by letter against the pattern and the exact length before including it. Output a table (Word | Meaning | Familiarity for the profile solver | Clueability note), bullets of the 3 you'd pick for a lively grid, and a callout on any that editors usually reject.",
    "table, bullets, callout", "Find words", "Scanning lexicon…")])

APP("escape_architect", "Escape Architect", "Design escape rooms and puzzle hunts at home", "Games", ["#00695C", "#F57C00", "#5D4037"], "bulb",
 "Escape Architect designs escape rooms and puzzle hunts you can run in a living room, classroom or office: a story, a chain of puzzles with codes that actually work, a hint ladder and a props list.",
 "You are an escape-room designer: you build puzzle chains that flow logically, verify every code and cipher, keep players safe, and never make a puzzle that depends on a leap only the designer would make.",
 "Lock them in (figuratively)", "Tell us your space and players; the puzzles will fit.", ["Puzzle chains with verified codes", "Hint ladders that keep the flow", "Props from what you already own"],
 [CH("space", "Space", ["Living room", "Classroom", "Office", "Garden", "Whole house"]), CH("players", "Players", ["Kids 6–10", "Tweens", "Teens", "Adults", "Mixed ages"]), NUM("budget", "Props budget", "20")],
 [T("room", "Design a room", "Story + puzzle chain", "🗝️",
    [TXT("theme", "Theme", "haunted lighthouse / spy heist / lost pharaoh", True), NUM("minutes", "Time limit", "45"), NUM("puzzles", "Number of puzzles", "7")],
    "Design a {minutes}-minute escape game on the theme {theme} with {puzzles} puzzles for the profile players and space. Sections: text (story premise and win condition), a table of the puzzle chain (# | Puzzle | Type | Solution or code | Unlocks | Est. minutes), steps for the game-master setup order, a checklist of props with an estimated total within the profile budget, and a callout on safety (nothing that actually locks people in, no real fire, no sharp or choking hazards for the age group).",
    "text, table, steps, checklist, callout", "Design room", "Hiding the key…"),
  T("puzzle", "Make one puzzle", "Cipher, lock, physical or logic", "🔐",
    [CH("type", "Puzzle type", ["Cipher", "Combination lock", "Physical / hidden object", "Logic", "Riddle", "Sound or light"], "Cipher"), TXT("output", "Must resolve to", "the code 4 8 1 3", True), TXT("flavour", "Theme flavour", "pirate treasure")],
    "Create a {type} puzzle that resolves to {output}, themed {flavour}, for the profile players. Give text with the exact puzzle as players see it, steps for the intended solve path, a kv (solution, materials, setup time, difficulty 1–5), and a callout that verifies the cipher or maths step by step and confirms the solution is unique.",
    "text, steps, kv, callout", "Make puzzle", "Encrypting…"),
  T("hints", "Hint ladder", "Three nudges per puzzle", "🪜",
    [LONG("chain", "Your puzzle list", "1 UV torch reveals code; 2 book cipher; 3 padlock 4 digits from painting…")],
    "Write a hint ladder for every puzzle in: {chain}, one row each. Output a table (Puzzle | Hint 1 nudge | Hint 2 direction | Hint 3 near-answer), then bullets on when the game master should offer a hint unprompted (time-based triggers per puzzle), and a quote with a short in-character message for delivering hints without breaking immersion.",
    "table, bullets, quote", "Write hints", "Nudging gently…"),
  T("playtest", "Fix from playtest", "Where did they get stuck?", "🧪",
    [LONG("feedback", "What happened", "team of 4 solved in 30 min but stuck 12 min on the mirror cipher; skipped the map puzzle entirely")],
    "Analyse this playtest: {feedback}. Output a table (Problem | Likely cause | Fix | Effort), steps to rebalance the chain so no puzzle exceeds 8 minutes, a callout on whether the finale still lands, and bullets of quick changes to make before the next run.",
    "table, steps, callout, bullets", "Fix it", "Reviewing the tape…"),
  T("hunt", "Outdoor puzzle hunt", "Clues that lead somewhere", "🧭",
    [TXT("area", "Area", "our street and the park", True), NUM("stops", "Stops", "6"), TXT("prize", "Prize location", "under the bird bath")],
    "Design a puzzle hunt around {area} with {stops} stops ending at {prize} for the profile players. Give a table (Stop | Clue text | Answer / next location | Setup needed), bullets of adult-supervision and road-safety points, and a callout on weatherproofing and timing.",
    "table, bullets, callout", "Plan hunt", "Drawing the map…")],
 "Never actually lock anyone in; keep exits clear, avoid real fire and sharp or choking hazards, and supervise children throughout.")

APP("whodunit_host", "Whodunit Host", "Write and run a murder mystery party for your guests", "Entertainment", ["#880E4F", "#455A64", "#D4AF37"], "pin",
 "Whodunit Host writes a complete murder mystery party for exactly your guest list: characters with secrets, a crime timeline, clue reveals per round, invitations and a host script that keeps everyone in the game.",
 "You are a murder-mystery party writer: witty, tightly plotted, fair to the detective in every guest; every character has a secret, a motive and an alibi that can crack.",
 "Everyone's a suspect", "Tell us the size of your party and its tone.", ["Characters sized to your guest list", "Clue reveals round by round", "Host script and printable packets"],
 [NUM("guests", "Number of guests", "8"), CH("tone", "Tone", ["Classic 1920s", "Campy comedy", "Noir", "Sci-fi", "Modern reality-TV"]), CH("rating", "Content rating", ["Family-friendly", "Teens", "Adults only"])],
 [T("plot", "Write the mystery", "Crime, killer, timeline", "🕯️",
    [TXT("setting", "Setting", "a snowed-in ski lodge", True), TXT("victim", "Victim (optional)", "the lodge's tyrannical owner")],
    "Write a murder mystery for the profile guest count, tone and rating, set in {setting} with victim {victim} if given. Sections: text (premise for the invitation, no spoilers), a kv of the solution marked HOST ONLY (killer, motive, method, the one clue that proves it), steps of the crime timeline hour by hour, a table of suspects with exactly one character per guest (Character | Public persona | Secret | Motive | Alibi weakness), and a callout on the red herring.",
    "text, kv, steps, table, callout", "Write mystery", "Plotting the crime…"),
  T("packet", "Character packet", "One guest's secrets and goals", "🎭",
    [TXT("character", "Character name & role", "Lady Ashcombe, the widow", True), LONG("plot", "Paste the mystery summary", "killer is the butler; Lady A. is having an affair with…")],
    "Write the private packet for {character} using the plot: {plot}. Give text (who you are, second person, about 120 words), bullets of what you know about the other guests, a kv of your secret, your goal for the evening and what you must never admit unless confronted with evidence, a quote with your opening line, and a checklist of 3 things to do during each round.",
    "text, bullets, kv, quote, checklist", "Write packet", "Sealing envelope…"),
  T("rounds", "Clue reveals", "What comes out each round", "🔎",
    [LONG("plot", "Paste the mystery summary", "killer is the butler; the poison came from…"), NUM("rounds", "Number of rounds", "3")],
    "Plan {rounds} rounds of revelations for: {plot}. Output a table (Round | Clue revealed | Delivered how | Who it implicates | What it rules out), bullets of physical clue props to prepare, and a callout on the moment of the final accusation and how to run the vote.",
    "table, bullets, callout", "Plan rounds", "Dropping clues…"),
  T("script", "Host script", "Welcome, rounds, reveal", "🎙️",
    [TXT("names", "Guest names (optional)", "Sam, Priya, Jo…"), NUM("minutes", "Evening length (minutes)", "120")],
    "Write the host script for a {minutes}-minute evening with guests {names} if given, in the profile tone. Give steps with clock times (arrival, round openings, dinner break, accusations, reveal), a quote for the welcome speech and the reveal speech, bullets on handling a guest who solves it early or forgets their secret, and a checklist of props, costumes and printing.",
    "steps, quote, bullets, checklist", "Write script", "Clearing my throat…"),
  T("invite", "Invitations & costumes", "Get guests into character", "💌",
    [TXT("date", "Date, time, address", "Sat 14 March, 7pm, ours", True)],
    "Write invitations for the profile party on {date}. Give a quote with the invitation text in the profile tone (including the date, time and address). Then a table with one row per guest (Character | Costume from a normal wardrobe | One prop), and bullets on setting the scene (lighting, music, a themed dish or drink name).",
    "quote, table, bullets", "Write invites", "Licking envelopes…")])

APP("parlour_pack", "Parlour Pack", "Custom party games built for the people in the room", "Entertainment", ["#E91E63", "#00BCD4", "#FFC107"], "gift",
 "Parlour Pack generates party game content on demand: custom question decks, charades and taboo word banks, games invented from whatever is in the room, mini-games tournaments with scoring, and a rescue plan when the room goes quiet.",
 "You are a party-game designer with a quick wit: inclusive, tuned to the crowd's spice level, and you never let a game outstay its welcome.",
 "Never a dull room", "Tell us who's usually at your parties.", ["Question decks for your crowd", "Word banks for charades & taboo", "Games invented from the room"],
 [CH("crowd", "Usual crowd", ["Close friends", "Family with kids", "Work colleagues", "Couples", "Students"]), CH("spice", "Spice level", ["Wholesome", "Cheeky", "Spicy"]), NUM("size", "Typical group size", "8")],
 [T("deck", "Custom question deck", "Cards to print or read out", "🃏",
    [CH("format", "Format", ["Would you rather", "Hot takes", "Never have I ever", "Most likely to", "Two truths prompts"], "Would you rather"), TXT("theme", "Theme or in-jokes", "our hiking trip, Dave's cooking"), NUM("cards", "Cards", "40")],
    "Write {cards} '{format}' cards for the profile crowd and spice level, themed on {theme} if given. Output a table (# | Card | Spice 1–3 | Best for), a kv of rules (how to play, scoring, tie-breaker), and a callout on cards to skip for a mixed crowd.",
    "table, kv, callout", "Build deck", "Shuffling…"),
  T("words", "Word bank", "Charades, taboo, pictionary", "🎨",
    [CH("game", "Game", ["Charades", "Taboo", "Pictionary", "Heads-up style"], "Charades"), TXT("category", "Category", "90s movies, animals, office life", True), CH("difficulty", "Difficulty", ["Easy", "Mixed", "Hard"], "Mixed")],
    "Generate a {game} word bank for {category} at {difficulty} difficulty suited to the profile crowd. Give a table of 30 entries (Word or phrase | Difficulty | Taboo words or hint), where the last column holds 5 forbidden words for Taboo and a one-line hint for the actor or artist in other games. Then bullets on house rules and timing, and a kv of team scoring.",
    "table, bullets, kv", "Generate", "Miming furiously…"),
  T("invent", "Invent a game", "From what's in the room", "🪑",
    [TXT("items", "What's around", "cushions, a deck of cards, spoons, a phone", True), NUM("minutes", "Minutes to fill", "20")],
    "Invent 2 original games for the profile group using only {items}, each playable in about {minutes} minutes. Present both as cards (meta = players · minutes · energy), then steps for the rules of the better one, a kv of scoring and win condition, and a callout on safety (no throwing near glass, no dares that embarrass).",
    "cards, steps, kv, callout", "Invent", "Rummaging…"),
  T("tournament", "Mini-games night", "Rounds, bracket, scoring", "🏆",
    [NUM("hours", "Hours", "2"), TXT("vibe", "Vibe", "competitive but silly")],
    "Plan a {hours}-hour mini-games tournament for the profile group with vibe {vibe}. Output a table (Round | Game | Minutes | Points | Equipment), text explaining team formation and a fair bracket for the profile group size, a kv of scoring rules and tie-breakers, and a quote for a 30-second MC intro.",
    "table, text, kv, quote", "Plan night", "Building bracket…"),
  T("rescue", "Rescue a flat party", "It's gone quiet", "🚨",
    [TXT("situation", "What's happening", "people on phones, two groups not mixing, host stressed", True)],
    "The party situation: {situation}. Give steps for the next 15 minutes (the specific game to launch, who to recruit first, what to say), bullets of 3 backup games needing zero equipment, and a callout on when to just change the music and let it be.",
    "steps, bullets, callout", "Rescue", "Reading the room…")],
 "Every game here works without alcohol; if drinks are involved, keep them optional and drink responsibly.")

APP("buzzer_brain", "Buzzer Brain", "Train to win pub quizzes and game-show auditions", "Games", ["#1565C0", "#FDD835", "#E53935"], "bolt",
 "Buzzer Brain trains trivia players rather than hosts: category drills with answers, study sheets for the topics quizzes love, gap analysis from your results, wager and team strategy, and post-quiz reviews.",
 "You are a trivia coach and former quiz-show contestant: accurate, obsessive about the facts quizzes actually ask, and honest about what is worth memorising.",
 "Know the answer first", "Tell us where you play and where you're weak.", ["Drills in the categories quizzes ask", "Study sheets for the classics", "Wager & team strategy"],
 [CH("arena", "Where you play", ["Pub quiz", "Online leagues", "Game-show hopeful", "University challenge style", "Family bragging rights"]), CH("weak", "Weak categories", ["Sport", "Science", "Geography", "History", "Pop music", "Film & TV", "Literature", "Art"], multi=True), CH("region", "Region", ["UK", "US", "Australia", "Ireland", "Canada", "Global"])],
 [T("drill", "Drill a category", "20 questions with answers", "🎯",
    [TXT("category", "Category", "capital cities / 80s number ones", True), CH("difficulty", "Difficulty", ["Warm-up", "Pub standard", "Expert"], "Pub standard")],
    "Write 20 {difficulty} trivia questions on {category} for the profile region and arena, as a self-test. Output a table (# | Question | Angle quizzes take | Points) with no answers in it, then a kv headed 'Answers' at the very end (number → answer), and bullets of 5 related facts that often appear as follow-up questions.",
    "table, bullets", "Drill me", "Loading buzzers…"),
  T("sheet", "Study sheet", "The classics, condensed", "📄",
    [TXT("topic", "Topic", "Best Picture winners / periodic table basics / US presidents", True)],
    "Build a one-page study sheet for {topic} tuned to the profile region. Provide a table of the core facts (Item | Key detail | Date or number | Common trick question), bullets of 5 quiz favourites from this topic, a kv of 3 memory hooks, and a callout on the fact most often asked and most often got wrong.",
    "table, bullets, kv, callout", "Build sheet", "Cramming…"),
  T("gaps", "Find my gaps", "Paste your results", "📊",
    [LONG("results", "Round scores from recent quizzes", "Week 1: sport 3/10, science 8/10, film 6/10. Week 2: sport 4/10…")],
    "Analyse these round scores: {results} against the profile weak categories. Give a table (Category | Average score | Trend | Priority), text on the pattern behind the low rounds (recall vs knowledge vs buzzer timing), steps for a 2-week study plan of 20 minutes a day, and a callout on the single category with the best points-per-hour return.",
    "table, text, steps, callout", "Analyse", "Marking…"),
  T("strategy", "Wager & buzzer strategy", "Play the game, not just the questions", "🧠",
    [CH("format", "Format", ["Pub quiz with joker round", "Jeopardy-style wagers", "Buzzer head-to-head", "Team of 6"], "Pub quiz with joker round"), TXT("situation", "Situation", "we're 4 points behind going into the last round")],
    "Advise for {format} in this situation: {situation}. Output kv (recommended move, expected-value reasoning, risk), steps for a decision process to reuse, bullets on team-play etiquette (who answers, when to overrule), and a quote with the one rule to remember under pressure.",
    "kv, steps, bullets, quote", "Advise", "Running the numbers…"),
  T("missed", "Learn what we missed", "Answers, hooks and siblings", "📝",
    [LONG("missed", "Questions you got wrong", "1. Which river flows through Vienna? we said Rhine…")],
    "Teach the missed questions: {missed}. Give a table (Question | Correct answer | Why the wrong answer was tempting | Memory hook), then bullets of 2 sibling questions per item that test the same fact from another angle, and a callout on whether any question was unfair or ambiguous and how to appeal it politely.",
    "table, bullets, callout", "Teach me", "Checking answers…")])

APP("meeple_studio", "Meeple Studio", "Design, balance and pitch your own board game", "Games", ["#EF6C00", "#3949AB", "#43A047"], "gear",
 "Meeple Studio is a board-game designer's workshop: it turns a theme into a core loop, checks the maths behind your economy, writes rulebook sections, digests playtest feedback and specs components for print-and-play or a publisher pitch.",
 "You are a published board-game designer and developer: mechanics-first, allergic to fiddliness, honest about what won't work, and fluent in balance maths and rulebook clarity.",
 "From napkin to table", "Tell us about the game you're building.", ["Core loops from a theme", "Balance maths you can trust", "Rulebooks and pitch sheets"],
 [TXT("game", "Working title & one-liner", "Tidewrack: salvage crews race the tide"), CH("weight", "Target weight", ["Party", "Family", "Gateway", "Mid-weight", "Heavy"]), CH("players", "Player count", ["1", "2", "2–4", "3–6", "Large group"]), NUM("minutes", "Target play time", "45")],
 [T("loop", "Design the core loop", "Theme → mechanics", "🔄",
    [LONG("idea", "Your idea so far", "players are lighthouse keepers competing for ships…"), CH("feel", "Feel", ["Tense", "Cosy", "Cutthroat", "Puzzly", "Chaotic"], "Tense")],
    "Develop the profile game from: {idea} with a {feel} feel, for the profile weight, player count and play time. Output text describing the core loop in one paragraph, steps for a full turn, a table of mechanics (Mechanic | Why it serves the theme | Known games that use it | Risk), cards for 3 end-game trigger options (meta = expected length · tension curve), and a callout on the biggest design risk.",
    "text, steps, table, cards, callout", "Design loop", "Sketching turns…"),
  T("balance", "Balance check", "Costs, curves, dominant strategies", "⚖️",
    [LONG("numbers", "Paste cards, costs or stats", "Trawler: cost 3, gives 2 fish/turn; Net: cost 1…"), TXT("worry", "What worries you", "the rush strategy always wins")],
    "Analyse the balance of: {numbers}. Concern: {worry}. Provide a table (Element | Cost | Value per turn | Payback turns | Verdict), text on the dominant strategy and why it dominates, bullets of concrete number changes (before → after), and a callout on what to test first and how many plays to trust the result.",
    "table, text, bullets, callout", "Check balance", "Crunching numbers…"),
  T("rules", "Write a rulebook section", "Clear, ordered, example-driven", "📘",
    [CH("section", "Section", ["Overview & goal", "Setup", "Turn structure", "Scoring", "Edge cases FAQ"], "Turn structure"), LONG("details", "How it works, in your words", "on your turn: move, then take 1 action…")],
    "Write the '{section}' section of the rulebook for the profile game from: {details}. Give text in standard rulebook voice, steps in the exact order players perform things, a quote with a worked example beginning 'Example:', and a callout of terms that must be defined elsewhere in the book.",
    "text, steps, quote, callout", "Write section", "Laying out pages…"),
  T("playtest", "Digest playtest feedback", "Notes → actionable changes", "🧪",
    [LONG("feedback", "Playtest notes", "4 players, 70 min (too long), Sam never used the market, ending felt abrupt…")],
    "Digest: {feedback} for the profile game. Output a table (Observation | Root cause | Change | Priority), bullets of what to keep because it worked, a kv of metrics to log at the next test (length, turns, score spread, lead changes), and a checklist for running the next playtest session.",
    "table, bullets, kv, checklist", "Digest", "Reading notes…"),
  T("components", "Components & pitch", "Spec, cost, sell sheet", "📦",
    [CH("route", "Route", ["Print-and-play", "Small print run", "Publisher pitch", "Crowdfunding"], "Publisher pitch")],
    "For the profile game via {route}: a table of components (Component | Count | Size or material | Est. unit cost), a kv of the sell sheet (hook, player count, time, age, weight, comparable titles), a quote with a 60-second pitch, and a callout on the component that most inflates cost and how to cut it.",
    "table, kv, quote, callout", "Spec it", "Counting meeples…")])

APP("boss_buddy", "Boss Buddy", "Beat the boss, fix the build, spoilers only on request", "Games", ["#B71C1C", "#00B8D4", "#7E57C2"], "spark",
 "Boss Buddy is a spoiler-aware video game guide: boss strategies, build and loadout planning, hint ladders when you're stuck, screenshot decoding and completion checklists, tuned to how much help you actually want.",
 "You are a patient, knowledgeable gaming guide: you give only as much help as asked, respect spoiler limits strictly, and note when a strategy may differ by patch or platform.",
 "Get unstuck your way", "Tell us what you play and how much help you like.", ["Boss strategies at your hint level", "Build & loadout planning", "Screenshot → what am I looking at?"],
 [CH("platform", "Platform", ["PC", "PlayStation", "Xbox", "Switch", "Mobile"], multi=True), CH("help", "Help level", ["Nudge only", "Clear strategy", "Tell me everything"]), CH("style", "Play style", ["Casual", "Completionist", "Competitive", "Speedrun-curious"])],
 [T("boss", "Beat this boss", "Phases, tells, punish windows", "👹",
    [TXT("game", "Game", "Elden Ring", True), TXT("boss", "Boss or fight", "Malenia, second phase", True), TXT("setup", "Your build / level", "level 90, bleed katana, no summons")],
    "Strategy for {boss} in {game} with setup {setup}, at the profile help level. Output a table of phases (Phase | Key attacks & tells | Response | Punish window), steps for the opening 30 seconds, bullets of build or consumable tweaks that help, and a callout on what may differ by patch or platform and what the player should confirm in-game.",
    "table, steps, bullets, callout", "Get strategy", "Studying the tells…"),
  T("build", "Build planner", "Stats, gear, priorities", "🛠️",
    [TXT("game", "Game", "Diablo 4 / Baldur's Gate 3", True), TXT("goal", "What you want", "a lightning sorcerer that survives endgame", True), TXT("have", "What you have", "level 40, mostly rare gear")],
    "Plan a build in {game} for {goal}, starting from {have}. Give a kv of the concept (role, core damage source, defensive answer, weakness), a table of priorities (Stat or skill | Why | Target value | When), steps for the levelling order, and a callout on patch sensitivity and cheap alternatives to key items.",
    "kv, table, steps, callout", "Plan build", "Respeccing…"),
  T("stuck", "I'm stuck", "Hint ladder, spoiler-safe", "🧩",
    [TXT("game", "Game", "Outer Wilds", True), LONG("where", "Where you are and what you've tried", "I'm in the flooded temple, found two levers, the door won't open")],
    "The player is stuck in {game}: {where}. Respect the profile help level and never reveal beyond it. Output steps as a hint ladder (hint 1 gentle, hint 2 directional, hint 3 near-explicit, hint 4 the solution), each labelled so the player can stop reading, bullets of things they may have missed, and a callout stating what remains unspoiled.",
    "steps, bullets, callout", "Give hints", "Hiding spoilers…"),
  T("screen", "Decode a screenshot", "What is this?", "📷",
    [PHOTO("Screenshot of your game", "", True), TXT("question", "Your question", "what do these icons mean / what should I do here")],
    "Look at the screenshot and answer: {question}. Give a kv of what is identified (game, screen or location, key UI elements, any status effects), bullets of what the player should do next at the profile help level, and a callout on anything uncertain from the image.",
    "kv, bullets, callout", "Decode", "Zooming in…"),
  T("complete", "Completion checklist", "Nothing missed", "✅",
    [TXT("game", "Game", "Hollow Knight", True), TXT("done", "What you've already done", "3 dreamers, 1800 essence")],
    "Build a completion plan for {game} given progress {done}, matching the profile play style. Output a checklist of remaining objectives grouped by area, a table of missables (Item or event | When it locks | How to avoid missing it), and a callout on the spoiler-safe phrasing used and what to verify in-game.",
    "checklist, table, callout", "Build list", "Counting relics…")])

APP("reel_pick", "Reel Pick", "Movie nights, watch orders and spoiler-safe catch-ups", "Entertainment", ["#311B92", "#FF8F00", "#00838F"], "camera",
 "Reel Pick picks films and shows the whole room will agree on, plans franchise watch orders, catches you up before a new season without spoiling it, sparks post-credits discussion and schedules marathons.",
 "You are a film-and-TV programmer with encyclopaedic taste: opinionated but generous, spoiler-disciplined, and you recommend for the actual people in the room, not the critics.",
 "What are we watching?", "Tell Reel Pick your tastes and streaming setup.", ["Picks for everyone on the sofa", "Franchise watch orders", "Spoiler-safe catch-ups"],
 [NAME, CH("services", "Streaming", ["Netflix", "Disney+", "Prime", "Apple TV+", "Max", "Paramount+", "Physical / own"], multi=True), TXT("loves", "Loves", "heist films, slow-burn sci-fi"), TXT("hates", "Won't watch", "jump-scares, anything over 3 hours")],
 [T("pick", "Pick tonight's film", "For everyone in the room", "🎬",
    [TXT("who", "Who's watching", "me, partner who likes rom-coms, teen who likes anime", True), CH("mood", "Mood", ["Comfort", "Thrilling", "Funny", "Thought-provoking", "Background noise"], "Comfort"), NUM("minutes", "Max runtime", "120")],
    "Recommend for {who}, mood {mood}, max {minutes} minutes, honouring the profile tastes and services. Output cards for 5 films or series (meta = year · runtime · likely service), a table (Title | Why this room | Who might object | Content notes), and a callout with the one pick to make if nobody can decide.",
    "cards, table, callout", "Pick", "Scanning the shelf…"),
  T("order", "Watch order", "Franchise or universe", "🗂️",
    [TXT("franchise", "Franchise or series", "Star Wars / Marvel / Ghibli / Fast & Furious", True), CH("goal", "Goal", ["Best first experience", "Chronological", "Essentials only", "Complete"], "Best first experience")],
    "Build a '{goal}' watch order for {franchise}. Give a table (# | Title | Year | Runtime | Why here | Skippable?), a kv of total hours and a realistic schedule for the profile viewer, bullets on the entries most people argue about, and a callout on where a newcomer should stop if they're not hooked.",
    "table, kv, bullets, callout", "Build order", "Sorting the reels…"),
  T("catchup", "Catch me up", "Spoiler-safe primer", "⏩",
    [TXT("title", "Series or franchise", "Succession before season 4", True), CH("seen", "What I've seen", ["Nothing", "Some early parts", "Most of it, fuzzy on details"], "Some early parts"), CH("spoilers", "Spoiler policy", ["Keep major twists hidden", "Full recap, spoil everything"], "Keep major twists hidden")],
    "Prepare a primer for {title} for someone who has seen {seen}, policy: {spoilers}. Output text (premise and tone in 4 sentences), a kv of key characters and where they stand, steps summarising what happened in order at the permitted spoiler level, and a callout listing what is deliberately being kept hidden.",
    "text, kv, steps, callout", "Catch me up", "Rewinding…"),
  T("discuss", "Post-film discussion", "Questions and readings", "💬",
    [TXT("title", "What you just watched", "Arrival", True), CH("depth", "Depth", ["Light chat", "Film-club", "Essay-level"], "Film-club")],
    "Lead a discussion of {title} at {depth} depth; spoilers are allowed because the user has seen it. Output bullets of 8 discussion questions ordered from easy to deep, text on 2 competing readings of the film, a kv of craft notes (direction, score, cinematography, editing, a standout scene), and cards for 3 films to watch next (meta = year · why it pairs).",
    "bullets, text, kv, cards", "Discuss", "Rolling credits…"),
  T("marathon", "Marathon planner", "A day or weekend of viewing", "🍿",
    [TXT("what", "What to marathon", "Lord of the Rings extended editions", True), TXT("when", "Time available", "Saturday 10am to midnight")],
    "Plan a marathon of {what} in {when}. Output a table (Start time | Title or episode | Runtime | Break after?), a checklist of snacks, seating and screen prep, bullets on where to place the intermission for maximum drama, and a quote with a short toast to open the day.",
    "table, checklist, bullets, quote", "Plan marathon", "Buttering popcorn…")])
