from dsl import *

# ---------------------------------------------------------------------------
# Kids' birthday parties
# ---------------------------------------------------------------------------
APP("pinata_plan", "Piñata Plan", "Kids' birthday parties, planned down to the party bag", "Parenting", ["#FF3D7F", "#FFC107", "#00BCD4"], "hat",
 "Piñata Plan runs your child's birthday party: a run sheet that keeps the energy right, games by age and space, allergy-safe food, invites, and a rescue plan when it rains.",
 "You are a veteran children's entertainer and parent: calm, funny, realistic about attention spans, and strict about allergies and supervision.",
 "Plan a party they'll talk about all term", "Tell us about the birthday child and the usual set-up.", ["Run sheets that keep the energy right", "Games by age, space and mood", "Allergy-safe food and party bags"],
 [F("kid", "Child's name & age", "text", "Arjun, turning 6"), CH("venue", "Usual venue", ["Home", "Garden / park", "Hired hall", "Soft play / activity centre"]), NUM("guests", "Usual guest count (kids)", "12"), TXT("allergies", "Allergies in the group", "nut-free, one coeliac")],
 [T("plan", "Plan the party", "Run sheet, prep list and budget", "🎉",
    [CH("theme", "Theme", ["Dinosaurs", "Princess & knights", "Space", "Superheroes", "Unicorns", "Football", "Science lab", "Let the kid pick"], "Let the kid pick"), NUM("budget", "Budget", "150"), NUM("hours", "Party length (hours)", "2")],
    "Plan a {theme} birthday party for the profile child at the usual venue, budget {budget}, lasting {hours} hours. Sections: a table run sheet (Time | Activity | Who leads | Kit needed) that follows the energy curve arrival → active game → food → cake → calm activity → party bags; a checklist of shopping and prep grouped 'week before / day before / morning of'; a kv budget split (venue, food, cake, decorations, party bags, entertainment) that totals {budget}; and a callout on the two moments most likely to go wrong at this age and how to prevent them.",
    "table, checklist, kv, callout", "Plan the party", "Inflating balloons…"),
  T("games", "Games by age", "Fill the minutes without chaos", "🎈",
    [CH("space", "Space", ["Small living room", "Big room / hall", "Garden", "Park"], "Big room / hall"), NUM("minutes", "Minutes to fill", "45"), CH("energy", "Energy level", ["Wild", "Mixed", "Calm"], "Mixed")],
    "Suggest games for the profile child's age and guest count in a {space}, filling {minutes} minutes at {energy} energy. Give 6 games as cards (meta = minutes · players · kit), ordered so energy builds then settles; then steps for running the best one, including what to do with a child who doesn't win; then a bullets section of 3 zero-kit backup games for when attention drops.",
    "cards, steps, bullets", "Pick games", "Choosing games…"),
  T("food", "Party food & cake", "Quantities, allergies, make-ahead", "🍕",
    [CH("style", "Food style", ["Classic party plates", "Pizza & sides", "Picnic boxes", "Grazing table"], "Classic party plates"), CH("cake", "Cake plan", ["Baking it", "Buying it", "Cupcakes"], "Buying it")],
    "Build a '{style}' party menu for the profile guest count with cake plan '{cake}', respecting the profile allergies in every item. Sections: a table (Item | Quantity for the group | Allergy notes | Make-ahead?); a checklist of what to prep the night before versus the morning; a callout on portion sizes for this age (children eat less than adults expect) and cross-contamination rules if any allergy is listed; and bullets with 3 drink options plus a parents' corner idea.",
    "table, checklist, callout, bullets", "Plan food", "Cutting crusts…"),
  T("invite", "Invites & thank-yous", "Wording for every message", "💌",
    [TXT("details", "Date, time, place", "Sat 14 Mar, 2–4pm, our house", True), CH("rsvp", "Ask parents about", ["Allergies", "Drop-off or stay", "Both"], "Both"), CH("tone", "Tone", ["Playful", "Simple", "Rhyming"], "Playful")],
    "Write invitation and thank-you wording for the profile child's party at {details}, in a {tone} tone, asking parents about '{rsvp}'. Output a quote with the invitation (under 80 words, with an RSVP line), a second quote with a WhatsApp-length reminder for 3 days before, a third quote with a thank-you note template that mentions the gift, and bullets on when to send each one.",
    "quote, bullets", "Write invites", "Licking envelopes…"),
  T("rescue", "Rescue me", "Rain, no-shows, a broken bouncy castle", "🚨",
    [TXT("problem", "What's gone wrong", "rain forecast for the park party tomorrow", True)],
    "Emergency: {problem}. For the profile party, give steps to fix it in the next few hours (most important first, naming who to message), a bullets section on what to tell the parents and the birthday child, and a callout on the one thing to protect no matter what (usually cake + one group activity + a photo).",
    "steps, bullets, callout", "Rescue", "Grabbing tape…")],
 "Confirm allergies directly with each parent and keep an adult supervising every activity; this is planning help, not safety advice.")

# ---------------------------------------------------------------------------
# Milestone birthdays (30, 40, 50 … 100)
# ---------------------------------------------------------------------------
APP("big_zero", "Big Zero", "Milestone birthdays that feel like them, not a template", "Events", ["#1A237E", "#FFC400", "#E91E63"], "spark",
 "Big Zero plans the big 3-0, 4-0, 5-0 and beyond: party concepts that fit the person, surprise logistics, a born-in-the-year quiz, the toast or roast, and a group memory montage.",
 "You are a milestone-party producer with a warm sense of humour: you build moments people remember, keep surprises watertight, and never embarrass the guest of honour.",
 "Make the big one count", "Tell us who's turning what, and how they like to celebrate.", ["Concepts matched to their style", "Surprise logistics that don't leak", "Toasts, roasts and memory montages"],
 [F("who", "Who's turning", "text", "my dad, Raj"), CH("age", "Milestone", ["30", "40", "50", "60", "70", "80", "90", "100"]), CH("style", "Their style", ["Loves a big party", "Small & meaningful", "Surprise-tolerant", "Hates fuss"]), TXT("date", "Party date", "12 Nov")],
 [T("concept", "Party concepts", "Four ideas that fit the person", "💡",
    [NUM("guests", "Guests", "40"), NUM("budget", "Budget", "1500"), CH("format", "Format", ["Dinner", "Cocktail party", "Weekend away", "Backyard bash", "Afternoon tea", "Activity day"], "Dinner")],
    "Propose 4 celebration concepts for the profile person and milestone: a {format} for {guests} guests within {budget}. Cards (meta = est. cost · effort · surprise-friendly yes/no), each with a one-line hook tied to their style and decade; then a kv budget split for the best fit; then a callout on what people at this milestone say they actually wanted afterwards (a moment, not more stuff).",
    "cards, kv, callout", "Show concepts", "Counting candles…"),
  T("surprise", "Surprise logistics", "Cover story, countdown, reveal", "🤫",
    [TXT("cover", "Cover story", "dinner with just us two", True), NUM("weeks", "Weeks until", "6"), TXT("accomplices", "Who's helping", "sister, best mate Tom")],
    "Plan a surprise for the profile person with cover story '{cover}', {weeks} weeks out, helpers: {accomplices}. Sections: a table (Week | Task | Owner | Leak risk) counting down; a checklist for the day itself (guest arrival window, where they hide, the reveal cue, who films); a quote with the exact message to guests about secrecy and timing; and a callout on the most common ways surprises get spoiled plus a fallback if it's rumbled early.",
    "table, checklist, quote, callout", "Plan surprise", "Shushing everyone…"),
  T("year", "Born in…", "Then-vs-now facts and a quiz", "📻",
    [F("year", "Birth year", "number", "1976", required=True)],
    "For someone born in {year}: a table of that year's world (Category | Then | Now; approximate, for the country the profile suggests) covering price of bread and a house, the No.1 song, the biggest film, the tech people had, and the headline event; then bullets of 8 quiz questions with answers spanning that year and each decade since; then a kv of 'by the numbers' facts for the milestone (days lived, approx. heartbeats, Christmases, Mondays survived) for a card or slide.",
    "table, bullets, kv", "Time travel", "Rewinding…"),
  T("speech", "Toast or roast", "Land the laugh and the lump in the throat", "🥂",
    [CH("kind", "Kind", ["Heartfelt toast", "Gentle roast", "Both in one"], "Both in one"), LONG("stories", "Stories & facts", "always late, ran a marathon at 45, terrible at karaoke, best listener…"), CH("length", "Length", ["1 minute", "3 minutes", "5 minutes"], "3 minutes")],
    "Write a {length} {kind} for the profile person using: {stories}. Output a quote with the full speech (open with a laugh, land one sincere line, end with a raise-your-glass cue; nothing that would embarrass them in front of their boss or their kids), then bullets on delivery (pauses, where to look, what to do with your hands), then a second quote with a 2-line backup version if nerves hit.",
    "quote, bullets", "Write it", "Clearing throat…"),
  T("tribute", "Memory montage brief", "Collect messages from everyone", "🎬",
    [CH("output", "Output", ["Video montage", "Memory book", "Wall of notes", "Playlist with stories"], "Video montage")],
    "Design a group {output} for the profile person. Sections: a quote with the message to send friends and family asking for contributions (what to send, length and format, deadline); a checklist of collection and assembly steps with a timeline working back from the date; bullets of 8 prompt questions to give contributors so the messages aren't all 'happy birthday'; and a callout on staging the reveal.",
    "quote, checklist, bullets, callout", "Brief it", "Gathering memories…")])

# ---------------------------------------------------------------------------
# Baby showers, sprinkles, sip-and-sees
# ---------------------------------------------------------------------------
APP("baby_bash", "Baby Bash", "Host a shower the mum-to-be actually enjoys", "Events", ["#5C6BC0", "#F48FB1", "#FFD54F"], "baby",
 "Baby Bash helps the friend or sister hosting a baby shower, sprinkle or sip-and-see: run sheet and budget, games nobody dreads, a pregnancy-safe menu, invite wording, and a gift log with thank-yous.",
 "You are an experienced shower host: organised, kind, allergic to cringe games, and protective of the guest of honour's comfort and privacy.",
 "Throw a shower with zero cringe", "Tell us about the parents-to-be and the kind of celebration.", ["Run sheet, budget and prep checklist", "Games and activities people enjoy", "Pregnancy-safe menu and mocktails"],
 [F("parents", "Parents-to-be", "text", "Priya & Sam"), TXT("due", "Due date", "late May"), CH("type", "Celebration", ["Baby shower", "Sprinkle (2nd+ baby)", "Sip & see (after birth)", "Co-ed shower", "Virtual shower"]), CH("vibe", "Vibe", ["Brunch", "Garden tea", "Evening mocktails", "Casual at home"])],
 [T("plan", "Plan the shower", "Run sheet, checklist, budget", "🍼",
    [NUM("guests", "Guests", "20"), NUM("budget", "Budget", "400"), TXT("theme", "Theme (optional)", "wildflowers, no pink or blue")],
    "Plan the profile celebration for {guests} guests within {budget}, theme: {theme}. Sections: a table run sheet (Time | What happens | Host job) for a 2.5-hour event with food and gifts placed where guest energy is highest; a checklist across '4 weeks out / 1 week / day before / morning of'; a kv budget split (food, drinks, decor, games & prizes, favours, printing); and a callout on the guest of honour's comfort (seating, bathroom access, timing, no surprises she didn't ask for).",
    "table, checklist, kv, callout", "Plan it", "Tying ribbons…"),
  T("games", "Games people don't dread", "Activities matched to the crowd", "🎲",
    [CH("crowd", "Crowd", ["All close friends", "Mixed family & friends", "Co-ed", "Includes kids", "Online"], "Mixed family & friends"), CH("mood", "Mood", ["Funny", "Sweet", "Low-key"], "Sweet")],
    "Suggest 6 shower activities for a '{crowd}' crowd in a {mood} mood, avoiding anything that puts the guest of honour on the spot or references her body. Cards (meta = minutes · prep · prizes needed) ordered for the flow of the event; then steps to run the best one including any printable wording; then bullets of 3 quiet alternatives for guests who don't do games (advice cards, onesie decorating, book inscriptions).",
    "cards, steps, bullets", "Pick games", "Shuffling…"),
  T("menu", "Menu she can eat", "Pregnancy-safe food and mocktails", "🥂",
    [CH("diet", "Dietary needs in the room", ["None known", "Vegetarian", "Vegan", "Halal", "Gluten-free", "Dairy-free"], multi=True), NUM("guests", "Guests", "20")],
    "Design a menu matching the profile vibe for {guests} people with dietary needs {diet}, where every dish is safe for a pregnant guest of honour (no unpasteurised cheese, raw or undercooked egg, deli meats, high-mercury fish, alcohol). Table (Dish | Serves | Pregnancy-safe note | Make-ahead); a checklist shopping list; cards for 3 signature mocktails (meta = prep minutes · batchable); and a callout on food left out too long at a warm event.",
    "table, checklist, cards, callout", "Plan menu", "Pouring mocktails…"),
  T("invite", "Invites & registry wording", "Say it warmly, not grabbily", "💌",
    [TXT("details", "Date, time, place", "Sun 3 May, 11am, my flat", True), CH("registry", "Gift approach", ["Include registry politely", "Group gift / fund", "No gifts, just come", "Books instead of cards"], "Include registry politely")],
    "Write invitation wording for the profile celebration at {details} with gift approach '{registry}'. Sections: a quote with the invitation (under 90 words, RSVP line, dietary ask); a second quote with a one-line gift sentence that doesn't sound grabby; a third quote with the reminder message for the week before; and bullets on etiquette (who hosts, whether parents' names appear, how far ahead to send, options for remote guests).",
    "quote, bullets", "Write invites", "Addressing…"),
  T("gifts", "Gift log & thank-yous", "Track who gave what, write the notes", "🎁",
    [LONG("gifts", "Gifts received (giver → gift)", "Aunt Meena → pram blanket; work team → voucher…")],
    "From this gift list: {gifts}, build a table (Giver | Gift | Thank-you sent ☐ | Note idea). Then a quote with 3 thank-you note templates (close friend, relative, group or workplace) that mention the specific gift and the baby, and bullets on timing and on thanking the host's helpers too.",
    "table, quote, bullets", "Log gifts", "Writing thanks…")],
 "Food-safety notes are general guidance; pregnant guests should follow their midwife's or doctor's advice.")

# ---------------------------------------------------------------------------
# Diwali
# ---------------------------------------------------------------------------
APP("diya_days", "Diya Days", "Five days of Diwali, lit, fed and sorted", "Lifestyle", ["#B71C1C", "#FF8F00", "#6A1B9A"], "flame",
 "Diya Days plans Diwali at home from Dhanteras to Bhai Dooj: a day-by-day plan for your tradition, rangoli and lighting you can actually finish, the sweets and snacks spread, a taash party night, and hampers with greetings.",
 "You are a warm, practical Diwali host who knows North, South, Gujarati, Bengali, Jain and Sikh variations, respects elders' versions, and keeps oil lamps and kids apart.",
 "Light it up without the last-minute panic", "Tell us your tradition and who's celebrating with you.", ["Day-by-day plan for your tradition", "Rangoli, lights and decor you can finish", "Sweets, taash night and hampers"],
 [NAME, CH("tradition", "Tradition", ["North Indian", "Gujarati", "Marathi", "South Indian", "Bengali (Kali Puja)", "Jain", "Sikh (Bandi Chhor Divas)", "Mixed / just the vibe"]), CH("home", "Home", ["Flat / apartment", "House with garden", "Shared house", "Abroad, small space"]), TXT("household", "Who's celebrating", "us two + parents visiting, kids 5 and 9")],
 [T("five", "5-day plan", "Dhanteras to Bhai Dooj", "🪔",
    [TXT("date", "Lakshmi Puja date", "20 Oct", True), CH("effort", "Effort this year", ["Go all in", "Balanced", "Keep it simple"], "Balanced")],
    "Build a five-day plan around Diwali on {date} for the profile tradition and household at '{effort}' effort. Sections: a table (Day | Name & meaning | Morning | Evening | Food) from Dhanteras to Bhai Dooj or the equivalent days for the tradition; a checklist of one-time shopping (diyas, oil and wicks, puja items, sweets boxes, new clothes, gifts) grouped 'buy early' and 'buy fresh'; and a callout on what to drop first if the week gets busy.",
    "table, checklist, callout", "Plan the week", "Lighting lamps…"),
  T("decor", "Rangoli & lights", "A design you can finish tonight", "🎨",
    [CH("spot", "Where", ["Entrance / doorstep", "Balcony", "Living room", "Puja corner", "Windows (abroad)"], "Entrance / doorstep"), CH("skill", "Rangoli skill", ["First time", "Can copy a design", "Confident"], "Can copy a design"), PHOTO("Photo of the space (optional)")],
    "Design decor for the {spot} at '{skill}' rangoli level, using the photo if given to judge size, surface and light. Sections: steps for a rangoli the user can actually finish (grid method, colour order, powder/flower/stencil options for the skill level); cards for 3 lighting layouts (meta = diyas needed · cost tier · setup minutes); a checklist of materials; and a callout on fire safety with oil diyas near fabric, kids and pets, plus renter-safe ways to fix string lights.",
    "steps, cards, checklist, callout", "Design it", "Sprinkling colour…"),
  T("sweets", "Sweets & snacks", "Mithai and savouries, make or buy", "🍬",
    [NUM("guests", "People to feed", "12"), CH("make", "Make vs buy", ["Mostly home-made", "Half and half", "Mostly bought, plated well"], "Half and half"), TXT("needs", "Dietary needs", "one diabetic uncle, one vegan cousin")],
    "Plan mithai and savouries for {guests} people, '{make}', with needs: {needs}, matching the profile tradition. Table (Item | Make or buy | Quantity | Make-ahead days | Notes for the dietary needs); steps for the two most forgiving home-made items (with sugar-syrup string test and timings); a checklist shopping list; and bullets on plating a thali or box so it looks abundant without waste.",
    "table, steps, checklist, bullets", "Plan the spread", "Stirring ghee…"),
  T("taash", "Taash party night", "Cards, food breaks, friendly stakes", "🃏",
    [NUM("guests", "Guests", "10"), CH("stakes", "Stakes", ["No money, points only", "Small change", "Prizes instead"], "No money, points only"), CH("mix", "Crowd", ["Card sharks", "Mixed, some newbies", "Families with kids"], "Mixed, some newbies")],
    "Host a Diwali card-party night for {guests} guests at '{stakes}' stakes with a '{mix}' crowd. Cards for 4 games (teen patti, rummy, bluff and one non-card option; meta = players · minutes · learning curve); steps for a 3-hour run sheet (arrival, first game, food break, tournament, prizes); bullets on house rules that keep it friendly (buy-in caps, rotating dealers, kids' table); and a quote with the WhatsApp invite.",
    "cards, steps, bullets, quote", "Plan the night", "Shuffling…"),
  T("hampers", "Hampers & greetings", "Gifts for neighbours, team and in-laws", "🎁",
    [TXT("who", "Recipients", "neighbours, my team at work, mother-in-law", True), CH("budget", "Budget each", ["Under 10", "10–25", "25–60", "60+"], "10–25")],
    "Suggest Diwali hampers for: {who}, at {budget} each. Cards per recipient (meta = cost · home-made % · prep time) with 3–4 items each and at least one item that isn't sweets; a quote with card messages in English plus one line in Hindi (or the profile tradition's language) with transliteration; and a checklist for assembly and delivery timing before Lakshmi Puja evening.",
    "cards, quote, checklist", "Build hampers", "Tying ribbons…")],
 "Follow local fireworks laws and never leave lit diyas unattended; customs vary by family and region, so honour your elders' version.")

# ---------------------------------------------------------------------------
# Eid al-Fitr / Eid al-Adha
# ---------------------------------------------------------------------------
APP("eid_table", "Eid Table", "Eid hosting from Chaand Raat to the last guest", "Lifestyle", ["#00695C", "#C9A227", "#3949AB"], "moon",
 "Eid Table plans Eid al-Fitr and Eid al-Adha at home: the Eid-day run sheet, a feast menu in your family's cuisine, Eidi and gifts for the kids, open-house waves for a long day of visitors, and qurbani share distribution.",
 "You are a seasoned Eid host who knows South Asian, Arab, Turkish, Malay, African and convert households, keeps prayer first and the chai flowing, and defers to the local mosque on rulings.",
 "Eid Mubarak, and everything ready", "Tell us which Eid, your family's cuisine and who's at home.", ["Eid-day run sheet around prayer", "Feast menu in your cuisine", "Eidi, open-house waves and qurbani shares"],
 [NAME, CH("eid", "Planning for", ["Eid al-Fitr", "Eid al-Adha"]), CH("cuisine", "Family cuisine", ["South Asian", "Arab / Levantine", "Gulf", "Turkish", "Malay / Indonesian", "North African", "Somali / East African", "West African", "Mixed / convert household"]), TXT("household", "Who's at home", "2 adults, kids 4 and 8, grandparents visiting")],
 [T("morning", "Eid day run sheet", "From pre-dawn to the last visit", "🌙",
    [TXT("prayer", "Eid prayer time & place", "8:30 at the community centre", True), CH("visits", "Visiting plan", ["Hosting all day", "Visiting others", "Host lunch, visit evening", "Quiet at home"], "Host lunch, visit evening")],
    "Build an Eid-day run sheet for the profile household with prayer at {prayer} and plan '{visits}'. Sections: a table (Time | What | Who | Prep done earlier) from pre-dawn ghusl and laid-out clothes, through takbeer, prayer, breakfast (sheer khurma or the cuisine's equivalent), visits and the evening; a checklist for Chaand Raat / the night before (mehndi, ironing, Eidi envelopes, zakat al-fitr paid if it is al-Fitr, phone charged for calls); and a callout on balancing kids' energy with elders' rest.",
    "table, checklist, callout", "Plan the day", "Ironing kurtas…"),
  T("menu", "Eid feast menu", "Dishes, cook timeline, shopping", "🍛",
    [NUM("guests", "Guests to feed", "16"), CH("service", "Service", ["Sit-down lunch", "Buffet open house", "Dessert & chai only", "Brunch after prayer"], "Buffet open house"), TXT("needs", "Dietary needs", "two vegetarians, one nut allergy")],
    "Design an Eid menu in the profile cuisine for {guests} guests as a '{service}' with needs: {needs}, weighted for the profile Eid (sweets-led for al-Fitr, meat-led for al-Adha). Table (Dish | Course | Serves | Make-ahead | Needs notes); steps for the cook timeline working back from serving time; a checklist shopping list grouped by halal butcher / grocer / bakery; and a callout on holding food safely across a long open house.",
    "table, steps, checklist, callout", "Plan the feast", "Simmering…"),
  T("eidi", "Eidi & gifts", "Fair amounts by age, nice presentation", "💵",
    [LONG("kids", "Kids & ages (and others to gift)", "Zayn 4, Amira 9, nephew 15, mum…"), CH("currency", "Currency", ["GBP", "USD", "EUR", "AED", "PKR", "INR", "MYR", "Other"], "GBP")],
    "Plan Eidi and gifts for: {kids} in {currency}. Table (Person | Eidi range | Gift idea | Budget) using sensible age-graded amounts and noting that local norms vary; then bullets on presentation (crisp notes, envelopes, kids' Eid bags); then a callout on keeping it fair between cousins and gently teaching kids to give a share as sadaqah.",
    "table, bullets, callout", "Plan Eidi", "Counting envelopes…"),
  T("waves", "Open house waves", "Forty guests, fourteen seats, one day", "🫖",
    [NUM("total", "Guests expected across the day", "40"), NUM("hours", "Hours open", "8"), NUM("seats", "Seats you have", "14")],
    "Plan an open house for {total} guests over {hours} hours with {seats} seats. Table (Wave | Time | Likely guests | What's served | Reset job) staggering families; a checklist for the reset kit between waves (plates, chai, sweets tray, bathroom, kids' corner); a quote with a warm invite message that gently suggests time slots without sounding like a booking system; and bullets on greeting etiquette across generations.",
    "table, checklist, quote, bullets", "Plan waves", "Refilling chai…"),
  T("qurbani", "Qurbani share plan", "Arrange, divide, distribute", "🐑",
    [CH("form", "Qurbani", ["Local (animal or share)", "Overseas via charity", "Both", "Not doing it this year"], "Local (animal or share)"), NUM("families", "Families to distribute to", "6")],
    "Plan qurbani for Eid al-Adha with '{form}' and {families} families to share with. If the profile says Eid al-Fitr or the form is 'Not doing it this year', open with one line saying qurbani belongs to Eid al-Adha and plan for that Eid anyway. Sections: steps for arranging it (booking, timing after prayer, collection); a table (Portion | Traditional recipient | Households | Storage) applying the customary thirds (own family, relatives and friends, those in need) with distribution across the {families} families; a checklist of containers, labels and freezer space; and a callout on hygiene for fresh meat and on following your local mosque's guidance.",
    "steps, table, checklist, callout", "Plan shares", "Sorting shares…")],
 "Practices vary by school of thought and family; follow your local mosque or scholar for religious rulings, and standard food-safety guidance for fresh meat.")

# ---------------------------------------------------------------------------
# Christmas hosting
# ---------------------------------------------------------------------------
APP("tinsel_ops", "Tinsel Ops", "Christmas hosting with a timetable, not a meltdown", "House & Home", ["#1B5E20", "#C62828", "#FFB300"], "gift",
 "Tinsel Ops runs Christmas at your house: an oven timetable that works backwards from serving time, beds and seating for everyone staying, a fair Secret Santa draw, Christmas Eve and morning plans for the kids, and a Boxing Day leftovers plan.",
 "You are a calm Christmas host and home cook: you plan backwards from serving time, run one oven like a pro, and keep guests, kids and cooks all sane.",
 "Host Christmas on rails", "Tell us who's coming and what the big meal is.", ["Oven timetable from serving time", "Beds, seats and a fair Secret Santa", "Christmas Eve, morning and leftovers"],
 [NAME, NUM("guests", "Usual Christmas headcount", "10"), CH("main", "Main event", ["Christmas Day lunch", "Christmas Eve dinner", "Boxing Day buffet", "Whole week of hosting"]), TXT("household", "Who's coming", "parents, sister's family with 2 kids, one vegan")],
 [T("timetable", "Oven timetable", "Backwards from serving time", "🦃",
    [CH("roast", "Main", ["Turkey", "Turkey crown", "Ham", "Beef", "Goose", "Nut roast / vegan centrepiece", "Two mains"], "Turkey"), NUM("weight", "Weight (kg)", "5"), TXT("serve", "Serving time", "2:00pm", True)],
    "Build a cook timetable for {roast} at {weight} kg to serve at {serve} for the profile headcount, assuming a single oven. Table (Clock time | Task | Oven °C & shelf | Notes) working backwards from serving, including resting, potatoes, sides, gravy and a vegan or vegetarian option if the profile needs one; then a checklist of night-before prep (peel, par-boil, stuffing, table laid); then a kv of quantities per person (potatoes, veg, pigs in blankets, gravy); then a callout on safe internal temperatures and defrosting time.",
    "table, checklist, kv, callout", "Build timetable", "Preheating…"),
  T("beds", "Beds, seats & house prep", "Who sleeps where, who sits where", "🛏️",
    [LONG("staying", "Who's staying and when", "Mum & Dad Tue–Fri; sister + Ben + kids (3, 7) Wed–Thu…"), NUM("rooms", "Spare rooms / sofas", "2")],
    "Allocate sleeping for {staying} across {rooms} spare rooms or sofas. Sections: a table (Night | Room / space | Who | Bedding needed); a second table for the Christmas Day seating plan by the profile household (Seat | Person | Why here); a checklist of house prep (linens, towels, heating, Wi-Fi card, spare toothbrushes, child safety); and a callout on giving hosts and guests one hour of no-plan time each day.",
    "table, checklist, callout", "Allocate", "Plumping pillows…"),
  T("santa", "Secret Santa draw", "Fair pairings and the announcement", "🎅",
    [LONG("people", "Participants (and any 'not with' pairs)", "Amy, Ben, Chloe, Dan, Eve — Amy not Ben"), NUM("limit", "Spend limit", "25"), TXT("date", "Exchange date", "Christmas Eve")],
    "Run a Secret Santa for {people} with a {limit} limit, exchanging on {date}. Produce a table of pairings (Giver | Buys for) that respects every 'not with' rule and forms one loop with nobody drawing themselves; then a quote with the announcement message (rules, limit, date, how to hint at wishes); then a second quote with a private message template each giver can be sent; then bullets of 5 gift ideas under the limit that suit anyone.",
    "table, quote, bullets", "Draw names", "Drawing names…"),
  T("eve", "Christmas Eve & morning", "The magic, scheduled", "🎄",
    [TXT("kids", "Kids & ages", "Leo 4, Zara 8", True), CH("traditions", "Traditions to include", ["Stockings", "Santa tracker", "Christmas Eve box", "Church / carols", "Midnight service", "Pyjama walk"], multi=True)],
    "Plan Christmas Eve and morning for {kids} with traditions {traditions}. Steps for the evening with clock times (wind-down, treats for Santa, bedtime script); a second steps section for the morning (wake rule, stocking order, breakfast before the big gifts, photo moments); a quote with a short note from Santa; and a callout on managing overwhelm and sugar with the youngest.",
    "steps, quote, callout", "Plan the magic", "Sprinkling snow…"),
  T("leftovers", "Leftovers & Boxing Day", "Use it all up safely", "🥪",
    [LONG("left", "What's left", "half a turkey, roast potatoes, red cabbage, stuffing, cheese board…")],
    "Turn {left} into a Boxing Day plan for the profile headcount: cards for 5 dishes (meta = minutes · what it uses up); steps for the best one; a table (Item | Fridge days | Freeze? | Reheat to) for safe storage; and bullets on a lazy Boxing Day buffet layout.",
    "cards, steps, table, bullets", "Rescue leftovers", "Raiding the fridge…")],
 "Cooking times are estimates; always check meat reaches a safe internal temperature with a thermometer.")

# ---------------------------------------------------------------------------
# Lunar New Year
# ---------------------------------------------------------------------------
APP("lunar_feast", "Lunar Feast", "Reunion dinner, red envelopes and the right words", "Lifestyle", ["#E53935", "#FDD835", "#5D4037"], "coin",
 "Lunar Feast plans Chinese New Year, Tết and Seollal: the reunion dinner with the meaning behind each dish, a countdown with the taboos, red envelope amounts by relationship, greetings with romanisation, and a zodiac story for the kids.",
 "You are a bilingual Lunar New Year host who knows Mandarin, Cantonese, Vietnamese and Korean customs, explains the why behind every tradition, and reminds people that families differ.",
 "Bring in the year properly", "Tell us your tradition and your role this year.", ["Reunion dinner with dish meanings", "Red envelopes and greetings done right", "Countdown, taboos and kids' story"],
 [NAME, CH("tradition", "Tradition", ["Chinese (Mandarin)", "Cantonese", "Vietnamese Tết", "Korean Seollal", "Mixed / learning"]), CH("role", "This year you are", ["Hosting the reunion dinner", "Visiting family", "Celebrating abroad", "Introducing a partner or kids"]), TXT("household", "Household", "me, husband, in-laws, toddler")],
 [T("dinner", "Reunion dinner menu", "Lucky dishes, cook order, shopping", "🐟",
    [NUM("guests", "Guests", "10"), CH("skill", "Cooking skill", ["Beginner", "Comfortable", "Confident"], "Comfortable"), TXT("needs", "Dietary needs", "no shellfish, one vegetarian")],
    "Plan a reunion dinner for {guests} in the profile tradition at {skill} skill with needs: {needs}. Table (Dish | Symbolic meaning | Make-ahead | Effort) including a whole fish or the tradition's equivalent lucky dishes; steps for the cook order so hot dishes land together; a checklist shopping list grouped by Asian grocer / regular supermarket; and a callout on which dishes to buy rather than cook at this skill level.",
    "table, steps, checklist, callout", "Plan dinner", "Steaming fish…"),
  T("countdown", "Countdown & taboos", "Clean before, not after", "🧧",
    [TXT("date", "New Year's Day date", "17 Feb", True)],
    "Build a countdown to Lunar New Year on {date} for the profile tradition and role. Sections: a table (Day | Task | Why) covering cleaning (finished before, never on the day), settling debts, haircuts, decorations (couplets, red, kumquat or the tradition's equivalents), the night before, and days 1–15 through to the Lantern Festival; a checklist of decorations and ingredients to buy early; and bullets of common first-day taboos (sweeping, washing hair, broken things, unlucky words).",
    "table, checklist, bullets", "Count down", "Hanging couplets…"),
  T("envelopes", "Red envelopes", "Amounts by relationship, lucky numbers", "💰",
    [LONG("recipients", "Recipients & relationship", "niece 6, nephew 14, parents, in-laws, doorman…"), CH("currency", "Currency", ["CNY", "HKD", "SGD", "MYR", "TWD", "VND", "KRW", "USD", "GBP", "AUD", "Other"], "USD")],
    "Plan red envelopes (hongbao / lai see / lì xì / sebaetdon) for {recipients} in {currency} for the profile tradition. Table (Person | Suggested range | Why this level | New notes?) applying lucky-number conventions (avoid 4; prefer 8 or even amounts where customary; odd amounts where Korean custom applies); then bullets on giving etiquette (two hands, who gives to whom, married versus unmarried, when a gift replaces cash); then a callout that norms vary by region and family, so check the local rate with an elder.",
    "table, bullets, callout", "Plan envelopes", "Folding notes…"),
  T("greetings", "Greetings & phrases", "Say it right, to the right person", "🗣️",
    [CH("to", "Saying it to", ["Elders", "Peers & colleagues", "Kids", "Partner's family (first time)"], "Elders"), CH("lang", "Language", ["Mandarin", "Cantonese", "Vietnamese", "Korean", "Hokkien", "English with the right words"], "Mandarin")],
    "Give greetings in {lang} for {to}. Sections: a table (Phrase | Romanisation | Meaning | When to say it) with 8 phrases including the toast and the reply when receiving a red envelope; a quote with a 3-sentence greeting to say on arriving at the home of {to}; and bullets on bows and hand gestures, seating order, and what not to say.",
    "table, quote, bullets", "Teach me", "Practising tones…"),
  T("kids", "Zodiac & story time", "The animal, the legend, a craft", "🐉",
    [TXT("year", "Year", "2026", True), TXT("ages", "Kids' ages", "4 and 7")],
    "Prepare Lunar New Year {year} for kids aged {ages}. Sections: text explaining the year's animal and element and what it's said to mean (as fun, not fortune); steps for a 20-minute craft (lantern, paper firecracker or dumpling folding) with materials; bullets telling the Nian legend in 6 lines they can retell; and a table (Age | Job they can own at the celebration) so each child has a role.",
    "text, steps, bullets, table", "Tell the story", "Waking the dragon…")])

# ---------------------------------------------------------------------------
# Marriage proposals
# ---------------------------------------------------------------------------
APP("pop_question", "Pop the Question", "Plan a proposal they'll retell for decades", "Lifestyle", ["#AD1457", "#FFD54F", "#4A148C"], "ring",
 "Pop the Question plans a marriage proposal end to end: ideas matched to your partner's personality, a run sheet with backups, the words you'll say, how to talk to their family, and a ring brief that doesn't overspend.",
 "You are a discreet proposal planner and friend: you match the moment to the person, plan for rain and nerves, and never push spending beyond what's sensible.",
 "Make the moment theirs", "Tell us about your partner and roughly when you're thinking.", ["Ideas that fit their personality", "A run sheet with a Plan B", "The words, the family, the ring"],
 [TXT("partner", "Partner's name", "Jess"), CH("personality", "They are", ["Private, hates fuss", "Loves a big moment", "Sentimental", "Adventurous", "Funny & casual"]), TXT("story", "Your story in one line", "met at a climbing gym in 2021, first trip to Lisbon"), TXT("timing", "When you're thinking", "around her birthday in June")],
 [T("ideas", "Proposal ideas", "Five ways, ranked by fit", "💍",
    [CH("setting", "Setting", ["At home", "Somewhere meaningful", "Travel", "With friends & family around", "Outdoors / nature", "Public spectacle (they'd love it)"], "Somewhere meaningful"), CH("budget", "Budget (excluding ring)", ["Under 100", "100–500", "500–2000", "2000+"], "100–500"), CH("privacy", "Privacy", ["Just us", "Us + hidden photographer", "Small group", "Big group"], "Just us")],
    "Suggest 5 proposal ideas for the profile partner and story: setting {setting}, budget {budget}, privacy '{privacy}'. Cards (meta = cost · effort · weather-dependent yes/no), each naming the exact moment the question gets asked; then bullets ranking them by fit with the partner's personality with one line on why; then a callout on ideas to avoid for this personality (no jumbotron for the private type).",
    "cards, bullets, callout", "Inspire me", "Plotting…"),
  T("runsheet", "The run sheet", "Timings, accomplices, Plan B", "🗓️",
    [LONG("plan", "The plan", "sunset at Primrose Hill, picnic, her sister hiding with a camera"), TXT("date", "Date", "Sat 14 June", True)],
    "Turn this plan into an operation: {plan} on {date}. Sections: a table (Time | Action | Who | Backup) from the morning to after the yes; a checklist for the week before (ring insured and sized, accomplices briefed, photographer, bookings, phone charged, nails if they'd want photos); a callout on Plan B for rain, a late train or a bad-mood day; and a quote with the exact message to send accomplices.",
    "table, checklist, callout, quote", "Build run sheet", "Syncing watches…"),
  T("words", "What I'll say", "Your voice, no clichés", "🎤",
    [LONG("notes", "What you love, moments, promises", "the way she laughs at her own jokes; the night we got lost in Porto; I want to…"), CH("length", "Length", ["3 sentences", "30 seconds", "1 minute"], "30 seconds")],
    "Write a {length} proposal speech from: {notes}, in the user's plain voice (no clichés, no 'from the moment I saw you'). A quote with the full speech ending in the question; a second quote with a 2-line version for when nerves erase the script; and bullets on delivery (kneel or not, when the ring comes out, breathe, wait for the answer).",
    "quote, bullets", "Write it", "Finding the words…"),
  T("family", "Ask the family", "Blessing, heads-up or both", "👨‍👩‍👧",
    [CH("who", "Who to ask or tell", ["Their parents", "Their whole family", "Their best friend", "My own family first"], "Their parents"), CH("culture", "Family style", ["Traditional, expects to be asked", "Relaxed, would love a heads-up", "Complicated / estranged", "Cross-cultural"], "Relaxed, would love a heads-up"), TXT("concerns", "Anything tricky", "her dad is old-fashioned; we've only met twice")],
    "Help with asking or telling {who}, where the family is '{culture}' and: {concerns}. Steps for how and when to do it (in person, call, what to lead with); a quote with a script for the conversation including answers to 'why now' and 'what if they say no'; bullets on cross-cultural or divorced-parent nuance where relevant; and a callout on keeping the secret after the conversation.",
    "steps, quote, bullets, callout", "Prepare me", "Steadying nerves…"),
  T("ring", "Ring brief", "Style, size, sensible spend", "💎",
    [CH("style", "Their style", ["Minimal", "Vintage", "Statement", "Nature-inspired", "No idea"], "No idea"), CH("budget", "Budget", ["Under 500", "500–1500", "1500–4000", "4000+"], "500–1500"), TXT("clues", "Clues", "wears silver not gold, thin bands, allergic to nickel")],
    "Brief the ring for {style} style at {budget} using clues: {clues}. Sections: kv (metal, setting, stone options including lab-grown and non-diamond, band width, estimated price range); a table (Priority | Spend here | Save here); steps for finding the ring size without asking (borrow a ring, trace it, ask a friend, resizing allowance); and a callout on returns, insurance and ignoring the 'months of salary' rule invented for marketing.",
    "kv, table, steps, callout", "Brief the ring", "Polishing…")],
 "Ring and budget notes are general guidance, not financial advice; get sizing and stone certification from a jeweller.")

# ---------------------------------------------------------------------------
# Retirement send-offs
# ---------------------------------------------------------------------------
APP("gold_watch", "Gold Watch", "Retirement send-offs worthy of the years", "Events", ["#37474F", "#D4A017", "#00838F"], "clock",
 "Gold Watch helps a colleague, manager or family member organise a retirement send-off: the event plan, the tribute speech, a career timeline and slideshow brief, the collection and card, and a memory jar that captures real stories.",
 "You are a thoughtful events organiser who has run dozens of retirement send-offs: you honour the years without embarrassing the person, keep speeches short and collections discreet.",
 "Send them off properly", "Tell us who's retiring and how you know them.", ["Event plan and budget", "Tribute speech and career timeline", "Collection, card and memory jar"],
 [F("retiree", "Who's retiring", "text", "Linda, head of nursing"), NUM("years", "Years of service", "32"), CH("relation", "You are their", ["Manager", "Colleague / friend", "Direct report", "Partner / family", "HR / office manager"]), TXT("personality", "Their personality", "dry humour, hates being centre of attention, loves gardening")],
 [T("plan", "Plan the send-off", "Run sheet, checklist, budget", "🎓",
    [CH("where", "Where", ["Office, during the day", "Pub / restaurant after work", "Home / garden party", "Off-site venue", "Virtual + in person"], "Pub / restaurant after work"), NUM("guests", "Guests", "35"), NUM("budget", "Budget", "600")],
    "Plan a retirement send-off for the profile retiree at '{where}' with {guests} guests and {budget} budget, matched to their personality. Table run sheet (Time | Moment | Who | Notes) with speeches early while people are attentive; a checklist across '6 weeks out / 2 weeks / week of / on the day'; a kv budget split (venue and food, drinks, gift, printing and decor, contingency); and a callout on inviting former colleagues and on handling a retiree who says 'don't make a fuss'.",
    "table, checklist, kv, callout", "Plan it", "Booking the room…"),
  T("speech", "Tribute speech", "How they arrived, what they built", "🎙️",
    [LONG("stories", "Stories, milestones, traits", "started as a porter in 1994; the night she stayed 14 hours; the famous flip-chart; 'I'll just check' catchphrase…"), CH("tone", "Tone", ["Warm & sincere", "Funny with heart", "Formal (senior leadership)"], "Funny with heart"), CH("length", "Length", ["2 minutes", "4 minutes", "6 minutes"], "4 minutes")],
    "Write a {length} {tone} retirement speech from the profile relation using: {stories}. A quote with the full speech (arc: how they arrived, what they built, who they made better, what's next, the toast); bullets on delivery and where to pause for laughs; and a callout on lines to cut if the retiree hates attention.",
    "quote, bullets, callout", "Write speech", "Warming up…"),
  T("timeline", "Career timeline & slideshow", "Slides, photos, who to ask", "📽️",
    [LONG("highlights", "Highlights by year (rough)", "1994 joined; 2001 promoted; 2010 led the merger; 2020 the pandemic year…")],
    "Build a career timeline and slideshow brief from {highlights}. Sections: a table (Year | Milestone | Slide title | Photo or prop to find | Who to ask); then steps to collect photos and clips from colleagues within two weeks; then bullets of 6 'then vs now' slide ideas (tech, uniforms, the office, prices); then a quote with the request message to send around.",
    "table, steps, bullets, quote", "Build timeline", "Scanning photos…"),
  T("kitty", "Collection & card", "Discreet kitty, easy card messages", "💌",
    [NUM("headcount", "People to ask", "60"), CH("method", "Collect via", ["Envelope on a desk", "Online kitty link", "Both"], "Online kitty link"), TXT("gift", "Gift idea (if known)", "greenhouse voucher + engraved trowel")],
    "Organise a collection from {headcount} people via '{method}' toward: {gift}. Sections: a quote with the collection email (no pressure, a suggested range, deadline, who to contact); a second quote with 4 card message options of different lengths for colleagues who don't know what to write; a checklist for closing the kitty, buying, wrapping and presenting; and a callout on discretion (amounts private, include remote and part-time staff, allow anonymity).",
    "quote, checklist, callout", "Organise", "Passing the hat…"),
  T("memories", "Memory jar & guest book", "Prompts that pull real stories", "🫙",
    [CH("format", "Format", ["Memory jar cards", "Guest book", "Video messages", "Wall of sticky notes"], "Memory jar cards")],
    "Set up a '{format}' for the profile retiree. Sections: bullets of 10 prompts that pull specific memories rather than 'good luck' (first impression, a time they saved the day, advice they gave, a phrase only they say); steps for running it at the event so everyone contributes; a quote with the printed instruction card; and a callout on how to present it at the end.",
    "bullets, steps, quote, callout", "Set it up", "Gathering stories…")])

# ---------------------------------------------------------------------------
# Coming-of-age celebrations
# ---------------------------------------------------------------------------
APP("rite_night", "Rite Night", "Quinceañeras, Sweet 16s, Debuts and Mitzvah parties", "Events", ["#6A1B9A", "#00E5FF", "#FF4081"], "star",
 "Rite Night plans coming-of-age celebrations — quinceañera, Sweet 16, bar or bat mitzvah party, Filipino 18th debut, 18th and 21st — with the timeline, the traditional moments scripted, court coordination, the playlist, and a parent speech the teen won't hate.",
 "You are a coming-of-age party planner fluent in Latin American, Jewish, Filipino and secular traditions: you respect the elders, protect the teen's taste, and keep the run sheet moving.",
 "Their big night, planned right", "Tell us who's celebrating and which tradition.", ["Timeline, budget and run sheet", "Traditional moments scripted", "Court, playlist and the parent speech"],
 [F("teen", "Celebrant's name", "text", "Sofia"), CH("tradition", "Celebration", ["Quinceañera", "Sweet 16", "Bar / Bat Mitzvah party", "Filipino Debut (18th)", "18th / 21st birthday", "Coming-of-age, our own way"]), TXT("taste", "Their taste", "reggaeton, aesthetic photos, hates speeches"), CH("scale", "Scale", ["Small family dinner", "Medium party (30–60)", "Big (60–150)", "Grand (150+)"])],
 [T("plan", "Plan the celebration", "Timeline, budget, run sheet", "📋",
    [NUM("budget", "Budget", "5000"), TXT("date", "Date", "Sat 20 Sept", True), CH("venue", "Venue", ["Home / garden", "Restaurant", "Hall / banquet", "Hotel", "Outdoor / marquee"], "Hall / banquet")],
    "Plan the profile celebration for {date} at a '{venue}' within {budget}, at the profile scale. Table (Months or weeks out | Task | Owner | Done ☐) from venue and outfit to DJ and photographer; a kv budget split with typical percentages for this kind of event; a second table for the night's run sheet (Time | Moment | Who cues it); and a callout on the three things families most often forget (vendor meals, a changing space, the celebrant actually eating).",
    "table, kv, callout", "Plan it", "Booking the hall…"),
  T("moments", "Ceremony moments", "Scripted, cued, adaptable", "👑",
    [CH("include", "Traditional moments", ["Grand entrance", "Court / entourage dance", "18 roses / 18 candles", "Changing of the shoes", "Last doll / last toy", "Candle lighting", "Hora / chair lift", "Parent dance", "Toast"], multi=True)],
    "Script the moments {include} for the profile tradition and celebrant; if none were chosen, pick the customary moments for that tradition. Sections: steps in order with what happens, who's involved and music suggestions; a quote with MC lines to introduce each moment (short, no cringe); a table (Moment | People to brief | Props | Rehearsal needed?); and bullets on adapting or skipping a tradition without offending elders.",
    "steps, quote, table, bullets", "Script it", "Cueing the music…"),
  T("court", "Court & entourage", "Damas, chambelanes, 18 roses", "🕺",
    [LONG("people", "Court members / roles", "damas: Ana, Lucia…; chambelanes: Mateo…; 18 roses: dad, uncle Rey…"), NUM("weeks", "Weeks until", "10")],
    "Coordinate the court {people} with {weeks} weeks to go. Sections: a table (Person | Role | Outfit spec | Rehearsal dates | Confirmed ☐); a checklist for rehearsals and fittings across the weeks; a quote with the group-chat message that sets expectations kindly (cost, dates, commitment); and a callout on dropouts and lining up a substitute.",
    "table, checklist, quote, callout", "Coordinate", "Herding the court…"),
  T("vibe", "Playlist & photo plan", "Every generation on the floor", "🎧",
    [CH("music", "Music", ["DJ", "Live band", "Playlist from a phone"], "DJ"), TXT("rules", "Must-play / never-play", "must: Bad Bunny; never: anything Dad picks")],
    "Plan the vibe with {music} and rules: {rules}, for the celebrant's taste in the profile. Table (Phase | Energy | 5 example tracks | Notes) from arrival to last dance across generations; bullets of 8 photo set-ups (with lighting and timing) the teen won't hate; cards for 3 activities besides dancing (meta = minutes · cost); and a callout on volume and a quiet zone for grandparents.",
    "table, bullets, cards, callout", "Set the vibe", "Testing the mic…"),
  T("speech", "Parent speech", "Two minutes, zero embarrassment", "🎤",
    [LONG("memories", "Memories & what you're proud of", "first day of school; her stubborn streak; how she looked after her brother…"), CH("speaker", "Speaker", ["Mum", "Dad", "Both parents", "Grandparent", "Sibling", "Godparent"], "Both parents")],
    "Write a 2-minute speech for {speaker} using {memories}, for the profile celebrant who may hate speeches. Output a quote with the full speech (one funny story, one proud moment, one hope, under 300 words, nothing that embarrasses them in front of friends); bullets on delivery; and a second quote with a 4-line version for a nervous speaker.",
    "quote, bullets", "Write speech", "Wiping tears…")],
 "If alcohol is served, follow local law on serving minors and arrange safe rides home.")
